DEV-3176 | Add support for new feature flag for mail chimp integration
newsrevenuehub/rev-engine pull request #1008
Opened 2023-02-16 18:23 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

This PR adds a new DRF permission, `HasFlaggedAccessToMailChimp` that can be used to gate access to arbitrary API endpoints based on whether or not user has this flag. 

This same flag will be available on the front end to gate access to componentry there, but this PR does not itself touch the front end.

This PR adds a temporary view that allows us to fully test the new permission through the view layer. In future PRs, we'll start using this permission to gate access to substantive resources.

#### Why are we doing this? How does it help us?

This is prelliminary work that will allow us to gate server- and SPA-side resources based on whether or not a user has the `"mailchimp-integration-access"` flag.

#### How should this be manually tested? Please include detailed step-by-step instructions.

In one browser tab, sign in to the Django 

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No

#### Have automated unit tests been added? If not, why?

Yes

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

No

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-3176](https://news-revenue-hub.atlassian.net/browse/DEV-3176)

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

Across environments, after this PR is merged, we'll need to create a feature flag with the name "mailchimp-integration-access" in the Django admin. Initially, it can be created with the false for super users and staff, and "everyone" set to "Unknown".  

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No

2023-02-17 18:25 UTC, njharman requested changes
Little bit of test coverage missing and covering unrelated line 99 would get this file to 100%! But I don't suppose that possibility gets you as excited as it does I. 

Otherwise looks good.

The AC are written confusing as heck.  I'm assuming (and it looked that way by tests) it is "additive" and not "exclusive" so that if SuperUser is ON, individual non-superuser users with feature flag set ON have access. Despite what AC7 "only superusers can access the Mailchimp connection UI components and APIs." says.

In "simpler to me" words. If any flag gives you access, you have access. If no flag gives you access, you do not have access.  

Right?

2023-02-17 18:25 UTC, njharman commented on apps/api/permissions.py
> +        return f"`HasFlaggedAccessToMailChimp` via {self.flag.name}"
Not that it's important, just FYI. __str__ could be handled in BaseFlaggedResource as

`return f"`{self.__class__.__name__}` via {self.flag.name}"`

A little less boilerplate and repeated code.

2023-02-17 18:25 UTC, njharman commented on apps/api/permissions.py
> +    def __str__(self):
The __str__ method is uncovered by tests

2023-02-17 18:25 UTC, njharman commented on apps/api/permissions.py
> +            raise ApiConfigurationError()
This raise is uncovered by tests

2023-02-17 21:20 UTC, benjaminEwhite commented on apps/api/permissions.py
> +            raise ApiConfigurationError()
833d19b4183

2023-02-17 21:20 UTC, benjaminEwhite commented on apps/api/permissions.py
> +    def __str__(self):
833d19b4183

2023-02-17 21:20 UTC, benjaminEwhite commented on apps/api/permissions.py
> +        return f"`HasFlaggedAccessToMailChimp` via {self.flag.name}"
833d19b4183

2023-02-17 21:22 UTC, benjaminEwhite commented
@njharman 

> In "simpler to me" words. If any flag gives you access, you have access. If no flag gives you access, you do not have access.

yes, that's a correct and well put reading of spirit of AC.

2023-02-20 17:02 UTC, njharman approved these changes
Ship it!

2023-02-23 20:42 UTC, x110dc commented on apps/api/permissions.py
> +class HasFlaggedAccessToMailChimp(BaseFlaggedResourceAccess):
Terribly minor, but should probably be `HasFlaggedAccessToMailchimp` (lowercase 'c') to match our style guide.

2023-02-23 20:42 UTC, x110dc commented on apps/api/tests/test_permissions.py
> +class TestHasFlaggedAccessToMailChimp:
`chimp`

2023-02-23 20:42 UTC, x110dc commented on apps/api/tests/test_permissions.py
> +        assert HasFlaggedAccessToMailChimp().has_permission(request, None) is True
`chimp` -- I won't flag the rest.

2023-03-01 03:31 UTC, x110dc approved these changes

2023-03-07 18:46 UTC, merged