Dev 3298 | Expose Mailchimp connection state in Revenue Program serializer
newsrevenuehub/rev-engine pull request #1027
Opened 2023-03-03 19:19 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

The purpose of this PR is narrowly to expose mailchimp connection state in the RevenueProgramSerializer. 

In order to do so, I've pulled in upstream changes in an in-flight branch (DEV-3297) that add two new columns + a migration to the RevenueProgram model, as this ticket presupposes those model changes (but not the rest of the changes in 3297).

- Adds a new property `RevenueProgram.mailchimp_integration_connected` which returns a boolean (see ticket for details on business logic).
- Exposes this property in the `RevenueProgramSerializer`
- Adds a new trait to `RevenueProgramFactory`: `mailchimp_connected_via_oauth`. When set to `True`, this trait will create a revenue program that has its `mailchimp_access_token` and `mailchimp_server_prefix` values set.

#### Why are we doing this? How does it help us?

It's a small change that is required as part of shipping Phase 0 for Mailchimp integration.

#### How should this be manually tested? Please include detailed step-by-step instructions.

In the review app, pick 

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-03-06 06:33 UTC, leo-dcfa commented on apps/organizations/migrations/0016_DEV-3297_add_mailchimp_fields.py
> +    operations = [
I'm confused about this one, I thought we would need to retrieve mc access token from secrets manager?

2023-03-06 18:13 UTC, njharman approved these changes
Looks good, 
Just couple possible issues which are comment/documentation/PR related. So, approving with assumption that any action needed will be taken. [also major one is on pulled in DEV-3297]

2023-03-06 18:13 UTC, njharman commented on apps/organizations/models.py
> +    mailchimp_access_token = models.TextField(null=True, blank=True)
[3297?]
Why is one TextField and other CharField? There might be reason, but it makes me wonder...

[With postgres, I pick TextField unless there is business case for max_length (e.g. field is part of 3rd party standard with max length) Which seems like it could be case here. 
In postgress Text/Varchar are same just, Text not having constraint. in other dbs Text can be stored differently with query/performance consequences)

2023-03-06 18:47 UTC, benjaminEwhite commented on apps/organizations/migrations/0016_DEV-3297_add_mailchimp_fields.py
> +    operations = [
Added [DEV-3302](https://news-revenue-hub.atlassian.net/browse/DEV-3302) to the PR description next steps. That's ticket where we'll introduce secrets management.

2023-03-06 18:50 UTC, benjaminEwhite commented
Closing and reopening because I made a change to migrations and want review app rebuilt from scratch.

2023-03-06 18:54 UTC, benjaminEwhite commented on apps/organizations/models.py
> +    mailchimp_access_token = models.TextField(null=True, blank=True)
6611b43ca764c11 + a510c48b2fdd

2023-03-09 23:00 UTC, x110dc requested changes
Probably okay, but I have one question. If you want to discuss further, you, me and @leo-dcfa could chat.

2023-03-13 14:10 UTC, benjaminEwhite commented on apps/organizations/models.py
> +                self.organization.show_connected_to_mailchimp,
49e4bddb22

2023-03-14 20:39 UTC, x110dc approved these changes

2023-03-14 20:40 UTC, x110dc commented on apps/organizations/models.py
> +                self.organization.show_connected_to_mailchimp,
👍

2023-03-14 21:21 UTC, merged