DEV-3300 | Expose available Mailchimp email lists in the revenue program serializer
newsrevenuehub/rev-engine pull request #1030
Opened 2023-03-06 14:41 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-03-06 18:42 UTC, njharman approved these changes
Looks good, approved. Only one request to add to comment. I don't feel need to rereview for that.

2023-03-06 18:42 UTC, njharman commented on apps/organizations/tests/test_models.py
> +        assert revenue_program.mailchimp_email_lists == []
[me talking myself into this is non-issue, will resolve]
Shouldn't these also mock get_all_lists to return value?  ... I guess it's minor/moot, We know the guard clause comes before list request. It's unlikely future mailchip_email_lists would refactor to cut/break guard and just rely try/catch to return empty list... [just triggered my "Review Mode pattern recognition...]

could assert no logging, to ensure setting checked and empty list not just from failed api call

2023-03-06 18:42 UTC, njharman commented on revengine/settings/base.py
> +MAILCHIMP_CLIENT_SECRET = os.getenv("MAILCHIMP_CLIENT_SECRET", None)
These don't seem to be used anywhere. Are they used by mailchimp_marketing lib? comment should mention that.

2023-03-06 19:02 UTC, benjaminEwhite commented
Closing and reopening after pushing upstream migration changes.

2023-03-06 19:06 UTC, benjaminEwhite commented on revengine/settings/base.py
> +MAILCHIMP_CLIENT_SECRET = os.getenv("MAILCHIMP_CLIENT_SECRET", None)
Yeah these actually aren't required here. I pulled them in from 3298 at beginning cause thought I would need them, and turns out I didn't, but didn't remember to remove.

523d362aaeae07

2023-03-09 23:09 UTC, x110dc requested changes
One super-small change request.

2023-03-09 23:09 UTC, x110dc commented on pyproject.toml
> +mailchimp-marketing = "^3.0.80"
Prefer that this be `^3.0`

2023-03-13 14:18 UTC, benjaminEwhite commented on pyproject.toml
> +mailchimp-marketing = "^3.0.80"
95145589a90a27

2023-03-18 23:08 UTC, x110dc approved these changes

2023-03-21 14:25 UTC, merged