DEV-2999: Add custom styles to emails
newsrevenuehub/rev-engine pull request #1031
Opened 2023-03-06 17:00 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
Added custom styles to emails, test them on dev, write tests

#### What's this PR do?
This is the second of 2 stacked PRs:
1. https://github.com/newsrevenuehub/rev-engine/pull/1020
2. This one

#### Why are we doing this? How does it help us?
Implement custom style in emails for Core & Plus users to maintain their brand in the email communication.

#### How should this be manually tested? Please include detailed step-by-step instructions.
Send usual emails:
- Log in with user with styled emails unset
- Contributions & Magic link

Send branded emails

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-03-08 19:36 UTC, benjaminEwhite requested changes
@GuiMend left some comments. Also, looks like PR description needs to be completed, and there are some failing Python tests (which is fine, I know this is in flight work :) )

Biggest piece of feedback is about where the conditionality around logo_url and similar lives. I think we're further ahead to refactor a bit so that conditionality is not being managed in the email templates, but instead in the code that calls the tasks.  

Let me know if you want to discuss more!

2023-03-08 19:36 UTC, benjaminEwhite commented on apps/api/views.py
> +                and revenue_program.organization.send_receipt_email_via_nre,  # Has feature flag enabled
Not sure what this last condition is about. I don't think that `send_receipt_email_via_nre` should have any bearing on whether or not a magic link email gets styles applied.

2023-03-08 19:36 UTC, benjaminEwhite commented on apps/contributions/models.py
> +                and self.donation_page.revenue_program.organization.send_receipt_email_via_nre,  # Has feature flag enabled
Ditto. Don't think this value is relevant.

2023-03-08 19:36 UTC, benjaminEwhite commented on conftest.py
> +
Let's remove this. It's trivial to implement once Core is implemented (which is also the right time to add fixtures for that plan as required).

2023-03-08 19:36 UTC, benjaminEwhite commented on apps/emails/templates/nrh-default-contribution-confirmation-email.html
> +      >
I would prefer that we keep the email templates relatively "dumb" and have the conditionality happen in the call to the email tasks. 

In other words, I think this template and the other ones should just get sent a value for `logo_url`, and the calling context should send the custom logo if it's available, otherwise default.  This also makes testing easier.

That also would allow us to get rid of the `apply_custom_style` context var.

2023-03-08 19:36 UTC, benjaminEwhite commented on apps/api/views.py
> +                "apply_custom_style": revenue_program.organization.plan.name
See comment below about getting rid of this context var altogether. Think we want to do that and just send a value for `logo_url` and decide in calling context here whether or not it gets the default value or a custom logo value.

That also means we probably don't need to send `default_style`.  Think we can just have the template expect to get logo url, header color, font whatever the values are -- and it shouldn't know where the values come from or why.

2023-03-08 19:36 UTC, benjaminEwhite commented on apps/emails/templates/nrh-default-contribution-base-template.html
> +    }
If font changes are being descoped from this PR (which I saw is happening, in JIRA), let's remove these in-flight attempts to get fonts working.

2023-03-08 20:53 UTC, GuiMend commented on apps/api/views.py
> +                and revenue_program.organization.send_receipt_email_via_nre,  # Has feature flag enabled
It's in the AC: 
![image](https://user-images.githubusercontent.com/9381325/223847142-36dca669-66de-4a8f-95b2-d0dd0891d695.png)

2023-03-10 15:30 UTC, benjaminEwhite commented on apps/api/views.py
> +                and revenue_program.organization.send_receipt_email_via_nre,  # Has feature flag enabled
You're right! I believe that AC needed some revision. I made a change to AC and am awaiting confirmation.  https://news-revenue-hub.atlassian.net/browse/DEV-2999?focusedCommentId=75656

2023-03-15 14:48 UTC, benjaminEwhite requested changes
Overall looking good. Have some suggestions on how we can simplify the interface a bit (namely, don't think we need/want the custom_style attribute).

2023-03-15 14:48 UTC, benjaminEwhite commented on apps/emails/templates/recurring-contribution-email-reminder.html
> +      <h1 class="template-header inner-center template-margin-bot">Scheduled Contribution</h1>
Probably don't need to repeat this part. if the conditionality can just be around the differing parts, that's slightly easier to maintain.

2023-03-15 14:48 UTC, benjaminEwhite commented on apps/emails/templates/recurring-contribution-email-reminder.html
> +  {% if style.custom_style %}
Don't think we need this `custom_style` attribute. The template shouldn't know anything about this context. If we need conditionality here, it should just be around if there's a `style.logo_url` value.  

@GuiMend I know in status quo that this email doesn't have NRE logo, but I discussed with Mariclare in Slack and she's 👍 on having default to NRE here if it's available and there's not a default style value.

so yea, think the conditionality here can just be around if there's a value for `style.logo_url` then display this block.

2023-03-15 14:48 UTC, benjaminEwhite commented on apps/organizations/models.py
> +    custom_style=False,
Don't believe we need this. As commented elsewhere, any conditionality around other TransactionalEmailStyle attributes in a template should be focused on the presence/non-presence of that attribute, not why its present or not present. So for instance a block that only displays if `style.logo_url` is present, and not based on if it's a "custom style" or not.

2023-03-15 14:48 UTC, benjaminEwhite commented on apps/contributions/tests/test_models.py
> +            # pytest_cases.fixture_ref("core_plan_revenue_program"),
Let's just remove for now.

2023-03-15 14:48 UTC, benjaminEwhite commented on apps/emails/tests/test_tasks.py
> +            # pytest_cases.fixture_ref("core_plan_revenue_program"),
Either remove or make this a JIRA todo.

2023-03-15 22:05 UTC, GuiMend commented on apps/emails/templates/recurring-contribution-email-reminder.html
> +  {% if style.custom_style %}
Hey @benjaminEwhite , actually I still think we need the "custom_styles". We have to hide the RP_NAME only if we have the custom logo, and show it with NRE logo.

Do you mind if we keep that property or do you have another suggestion to handle this scenario?
![image](https://user-images.githubusercontent.com/9381325/225454128-a7d29ccf-e6dd-4995-ba44-c0e5f0a42a44.png)

2023-03-17 18:41 UTC, benjaminEwhite approved these changes
@GuiMend I had a couple of small comments that I believe should be quick to resolve. No need for me to review after you've handled those.

2023-03-17 18:41 UTC, benjaminEwhite commented on apps/emails/tests/test_tasks.py
> +    # that the correct styles are applied to the email. We just need to know that it uses `revenue_program.transactional_email_style`.
```suggestion
```

2023-03-17 18:41 UTC, benjaminEwhite commented on apps/emails/tests/test_tasks.py
> +        has_tax_id: bool,
I don't think we need the type hinting for test signatures.  They're not going to get called anywhere else, so value of having the types is lower. If there were a utility method on a test class that was getting called in individual tests, I could see typing that, but these feels like overkill, with high chance of going stale.

2023-03-17 18:41 UTC, benjaminEwhite commented on apps/emails/tests/test_tasks.py
> +    ):
Don't think we need type hints for tests. See comment below.

2023-03-17 18:41 UTC, benjaminEwhite commented on apps/emails/tests/test_tasks.py
> +        self, monkeypatch, interval: Literal[ContributionInterval.ONE_TIME, ContributionInterval.MONTHLY]
See comment below -- no need for type hints in tests.

2023-03-20 18:50 UTC, GuiMend commented on apps/emails/tests/test_tasks.py
> +        has_tax_id: bool,
Hey @benjaminEwhite , you added all of these type definitions in the commit: `fix broken things [1b9fdad]`

2023-04-17 15:31 UTC, benjaminEwhite commented
Closing and reopening to trigger rebuild.

2023-05-02 18:00 UTC, x110dc approved these changes

2023-05-02 19:52 UTC, merged