[WIP] DEV-3302 | introduce google cloud secrets management and retire mailchimp access token from revenue program model
newsrevenuehub/rev-engine pull request #1036
Opened 2023-03-07 22:07 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-03-08 06:13 UTC, leo-dcfa commented on apps/common/google_cloud_secrets.py
> +
I think this file belongs inside the google cloud app, instead of commons. And should be called secrets_manager, to keep consistent with other file in app called `pubsub` representing another service provided by gcloud

2023-03-08 06:14 UTC, leo-dcfa commented on apps/organizations/models.py
> +    def mailchimp_access_token_secret_name(self) -> str:
In addition to the access token secret name, how can I retrieve server from switchboard api?

2023-03-08 06:21 UTC, leo-dcfa commented on apps/common/google_cloud_secrets.py
> +
Not sure if it's helpful, but I took a different approach in switchboard api where I composed a secret manager client https://github.com/newsrevenuehub/switchboard-api/pull/625/files#diff-3a0d4be3a54cf0bbe0a1fc9568965b284f2ca624aa64cec0a42f5ea09cb4614dR1

This is again similar to the approach here https://github.com/newsrevenuehub/rev-engine/blob/main/apps/google_cloud/pubsub.py

2023-03-08 16:20 UTC, benjaminEwhite commented on apps/common/google_cloud_secrets.py
> +
I tend to prefer a more functional vs. OOP approach. That probably comes down to individual dev preferences, but in this case, I find I can follow code flow more easily because there's less indirection.

2023-03-08 16:22 UTC, benjaminEwhite commented on apps/organizations/models.py
> +    def mailchimp_access_token_secret_name(self) -> str:
I believe that will just be on the serialized revenue program.

2023-03-08 16:45 UTC, benjaminEwhite commented on apps/common/google_cloud_secrets.py
> +
cf06b294f58

2023-03-09 18:40 UTC, njharman requested changes
Don't like it. There's too much interdependency between SecretManagerService Client, google_cloud.secrets_manager.py and where it's used (models.py, signals.py)

If we go to trouble of wrapping third party library we should some of (isolate means from callers of our wrapper)

- isolate implementation details of 3rd party lib
- isolate complexity of 3rd party lib
- genericize access so 3rd party lib can be swapped out for another
- add business logic/logging/features or otherwise alter how 3rd party operates

I would have liked to see more of that in this code. Specifically the isolate complexity and implementation details.

2023-03-09 18:40 UTC, njharman commented on apps/google_cloud/secrets_manager.py
> +def create_secret(secret_id: str, project_id: str = settings.GOOGLE_CLOUD_PROJECT) -> Secret:
This (usage) is not very clear.  I think I would have hidden/isolated the "version concept" in these functions. In general I would have hidden platform (google) implementation details from users of these functions. Ideally they would be swappable with another provider's functions.

1. create_secret() is creating a contianer for sercret versions?  
2. and use create_secret_version to actually store my secret which is "payload"?

2023-03-09 18:40 UTC, njharman commented on apps/organizations/models.py
> +            return get_secret_version(self.mailchimp_access_token_secret_name).payload.data.decode("utf-8")
get_secret_versin should return string.  Do the decoding.  Caller of function should not (have to) know the internal data structure of Secret.

2023-03-09 18:40 UTC, njharman commented on apps/organizations/models.py
> +            logger.debug(
[edit: I guess it's logged in get_secret_version().... nm?] Should this be debug? and not warning or error.  [It's configured but failed to work sounds like something we'd want to hear about]

2023-03-09 18:40 UTC, njharman commented on apps/organizations/models.py
> +        except Exception:
What exception are we expecting here?  network failures? I'm at default mildly adverse to catching Exception.

2023-03-09 18:40 UTC, njharman commented on apps/organizations/signals.py
> +    if instance.mailchimp_access_token:
(In secrets_manager)Should check for and log error if delete requested and settings.ENABLE_GOOGLE_CLOUD_SECRET_MANAGER is False. 

Or perhaps do nothing/log debug if it's expected only dev/test env won't have that set and we don't want spurious exceptions logged.

2023-03-09 18:40 UTC, njharman commented on apps/organizations/signals.py
> +                "Failed to delete mailchimp_access_token_secret for RevenueProgram with ID %s", instance.id
Maybe we should define a code practice on how we log identifying information. I need consistency! :)

first logger its _instance.__str___, in second its _instance.id_

2023-03-09 18:40 UTC, njharman commented on apps/organizations/models.py
> +                "`RevenueProgram.mailchimp_access_token` failed to fetch access token from Google Cloud Secrets for RP with ID %s",
Should GoogleCloudSecretManagerException as e: and include in log (it will be the first param, the explanation note given when exception raised.

2023-03-09 18:40 UTC, njharman commented on apps/google_cloud/secrets_manager.py
> +    secret_detail = f"projects/{project_id}/secrets/{secret_id}/versions/{version_id}"
What's the relationship with this and client.secret_path() I see used below? I mean can secret_path() or some other client method be used to create this? This "magic" literal stands out...

2023-03-09 18:40 UTC, njharman commented on apps/google_cloud/secrets_manager.py
> +def create_secret_version(
I don't see this called anywhere. How do secrets get added?

2023-03-09 18:40 UTC, njharman commented on apps/google_cloud/secrets_manager.py
> +        logger.info("`create_secret_version` created a new version for secret with name %s", version.name)
secret_id, project_id

2023-03-09 18:40 UTC, njharman commented on apps/google_cloud/secrets_manager.py
> +            "`delete_secret` cannot delete secret with name %s because project %s is not permitted", name, project_id
secret_id

2023-03-09 18:40 UTC, njharman commented on apps/organizations/signals.py
> +            logger.exception(
Should GoogleCloudSecretManagerException as e: and include in log (it will be the first param, the explanation note given when exception raised.

2023-03-09 18:40 UTC, njharman commented on apps/organizations/models.py
> +        if not settings.ENABLE_GOOGLE_CLOUD_SECRET_MANAGER:
Check for settings should be in google_cloud.secrets_manager

2023-04-19 02:11 UTC, benjaminEwhite commented on apps/organizations/signals.py
> +    if instance.mailchimp_access_token:
It's common/expected behavior. Now logging when none.

2023-04-19 16:30 UTC, benjaminEwhite commented
Closing and tearing down in order to re-open and trigger fresh build because need the Google credentials file to be recreated.

2023-05-01 19:02 UTC, benjaminEwhite commented
Closing and reopening to trigger fresh build because of upstream migrations that affect migration dependencies herein.

2023-05-01 22:27 UTC, benjaminEwhite commented
Closing and reopening to trigger rebuild.

2023-05-03 18:48 UTC, benjaminEwhite commented
closing and reopening to trigger rebuild.

2023-05-11 16:55 UTC, njharman approved these changes
Approved.

Minor code coverage. Questions/considerations on code structure for testability. Philosophical ramblings.

2023-05-11 16:55 UTC, njharman commented on apps/common/secrets.py
> +        raise NotImplementedError("Subclasses of SecretProviderSecret should implement __get__ but does not")
comment mark to not test, I think  `# noqa`

2023-05-11 16:55 UTC, njharman commented on apps/common/secrets.py
> +    return SecretManagerServiceClient(credentials=credentials)
not covered

2023-05-11 16:55 UTC, njharman commented on apps/common/secrets.py
> +            raise SecretProviderException("Permission denied")
[ignorable]  Man, I'd made a decorator, helper, something. Just to not have to repeat all this code. Whatever happened to Laziness being a programmer virtue?  Otoh, how many levels on indirection before inescapable confusion.

2023-05-11 16:55 UTC, njharman commented on apps/common/secrets.py
> +    )
Why not just mock _get_secret_manager_client?

2023-05-11 16:55 UTC, njharman commented on apps/common/secrets.py
> +def _get_secret_manager_client() -> SecretManagerServiceClient:
Since this only works for Google, why is this not a member function of the GoogleCloudSecretProvider 
Where it could also be mocked.

2023-05-11 16:55 UTC, njharman commented on apps/common/tests/test_secrets.py
> +    @pytest.mark.parametrize("enabled", [True, False])
Appreciate that there are multiple paths to happiness

2023-05-12 20:56 UTC, benjaminEwhite commented on apps/common/secrets.py
> +        raise NotImplementedError("Subclasses of SecretProviderSecret should implement __get__ but does not")
Addressed in 84e4a4d3d16770e6d44ad405453b8ae466505463

2023-05-12 20:58 UTC, benjaminEwhite commented on apps/common/secrets.py
> +def _get_secret_manager_client() -> SecretManagerServiceClient:
This had to do with complexity around patching and when the GoogleCloudSecretProvider gets loaded initially vs. when we're able to patch it.  In order to test across context (that is, narrow unit tests of secrets, as well as testing features that use secrets), it proved easiest to have this as module level function.

2023-05-12 20:59 UTC, benjaminEwhite commented on apps/common/secrets.py
> +    )
No longer relevant. code outdated.

2023-05-12 21:18 UTC, benjaminEwhite commented on apps/common/secrets.py
> +    return SecretManagerServiceClient(credentials=credentials)
b80dbc2c7cdef4b09dc843e3535b053080035c38

2023-05-19 19:08 UTC, x110dc requested changes
Just had a couple of questions.

2023-05-19 19:08 UTC, x110dc commented on deployment-tasks.sh
> +ENABLE_GOOGLE_CLOUD_SECRET_MANAGER=False python manage.py migrate --noinput
Why is this here?

2023-05-19 19:08 UTC, x110dc commented on docker-entrypoint.sh
> +
Can you explain this change?

2023-05-19 19:08 UTC, x110dc commented on google_sa.sh
Can you explain this change?

2023-05-19 19:17 UTC, benjaminEwhite commented on google_sa.sh
I made this change when I was trying to understand why the account credentials file was not available in Celery tasks before I understood the underlying issue (which was separate). 

IMO the change here is worth keeping as it simplifies the logic in this script --whether the file exists already or not, we're creating it anew. I don't see the value in removing the file only to recreate when can just override if already exists instead.

2023-05-19 20:47 UTC, benjaminEwhite commented on docker-entrypoint.sh
> +
This was leftover from when I was trying to run down missing Google account credentials file. Change not required. Removed.

2023-05-19 20:47 UTC, benjaminEwhite commented on deployment-tasks.sh
> +ENABLE_GOOGLE_CLOUD_SECRET_MANAGER=False python manage.py migrate --noinput
I've now removed this change.

2023-05-20 00:01 UTC, x110dc approved these changes
LGTM.

2023-05-22 13:14 UTC, merged