DEV-3297: new api endpoint for spa to post to after completes mailchimp oauth flow
newsrevenuehub/rev-engine pull request #1055
Opened 2023-03-23 16:22 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

This PR goes directly into main, but worth noting an oddity about the diff that appears here. There are a large number of SPA-related changes in this PR that were reviewed and approved in #1041.

Therefore, the review in this PR can and should ignore all changes ini the /spa folder. 

#### What's this PR do?

Notwithstanding the already-reviewed SPA-side changes, this PR provides backend support for the Mailchimp Oauth flow. Specifically, it replaces the previously stubbed `apps.organizations.views.mailchimp_integration_stub` view with a fully implemented `handle_mailchimp_oauth_success` view. 

After a user completes the form on Mailchimp's site, they are redirected back to the SPA and provided with an Oauth code from Mailchimp that the SPA forwards on to this view.  

The view enqueues a Celery task that exchanges the Oauth code for an access token, which gets saved back to the revenue program, and which gets used to make an additional request to retrieve the Mailchimp server prefix, which also gets saved to the RP.

Here's a more granular view of some of the key changes:

- Adds a migration and alters the `RevenueProgram.mailchimp_server_prefix` field to be CharField instead of TextField
- Adds a new serializer field: `RevenueProgramSerializer.mailchimp_integration_connnected`
- Adds a new serializer `MailchimpOauthSuccessSerializer` which is used in the Mailchimp view mentioned above.
- Adds a new task, `apps.organizations.tasks. exchange_mailchimp_oauth_code_for_server_prefix_and_access_token `. This task does the work of exchanging auth code for access token, and then getting a server prefix. It is retryable, and can handle the situation where a previous attempt got the access token but failed at getting the server prefix (and vice versa, though I don't think that's really possible in real life).
- Adds a new view, apps.organizations.views.handle_mailchimp_oauth_success, which validates the request and enqueues a task the exchange_mailchimp_oauth_code_for_server_prefix_and_access_token task.

#### Why are we doing this? How does it help us?

Facilitates Mailchimp integration

#### How should this be manually tested? Please include detailed step-by-step instructions.

As an org user whose org has been assigned the plus plan, log in to the review app dashboard. Go to https://dev-3297.revengine-review.org/settings/integrations/ and click on the toggle to connect to Mailchimp.

You should be taken to the Mailchimp site where you can authorize Revengine to make requests to Mailchimp API on your behalf.

After successfully completing that form, you should be sent back to the settings page of the SPA. After a few seconds if not immediately, you should see that the toggle for the Mailchimp integration is toggled on.

Additionally, in the Django admin, you should see that the revenue program now has values set for mailchimp server prefix and access token.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No

#### Have automated unit tests been added? If not, why?

Yes

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

No

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-3297](https://news-revenue-hub.atlassian.net/browse/DEV-3297)

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

Yes.  

We need new env vars for:
 
- MAILCHIMP_CLIENT_ID
- MAILCHIMP_CLIENT_SECRET

These should also be added in settings vars that get copied over to review apps.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

N/A

[DEV-3297]: https://news-revenue-hub.atlassian.net/browse/DEV-3297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-03-30 14:11 UTC, benjaminEwhite commented on README.md
> +**Attention**: If the environment variable is going to be needed in deployed environments (e.g: dev, prod) don't forget to add it also in the file `revengine/settings` inside `SPA_ENV_VARS`, and also
This has been reviewed elsewhere and need not be reviewed here.

2023-03-31 16:47 UTC, njharman requested changes
Looks good, just "typo", coverage, documentation issues and confirmation questions about security.

2023-03-31 16:47 UTC, njharman commented on .envrc.example
> +export REACT_APP_HUB_GOOGLE_MAPS_API_KEY=
REACT_APP_HUB_... seems unrelated to current ticket and included cause it was missing.

Just confirming it need not be mentioned in PR pre-deployment changes.

2023-03-31 16:47 UTC, njharman commented on apps/organizations/tasks.py
> +    """ """
cut empty docstirng

2023-03-31 16:47 UTC, njharman commented on apps/organizations/tasks.py
> +        request_data,
No security issue with logging _oauth_code_?

2023-03-31 16:47 UTC, njharman commented on apps/organizations/tasks.py
> +    if not response.status_code == status.HTTP_200_OK:
Not saying it needs to change. Just find it "weird" to say _if not foo ==_ instead of  _if foo !=_.  Is former a "style"?

2023-03-31 16:47 UTC, njharman commented on apps/organizations/tasks.py
> +            oauth_code,
Again curious about logging oauth_code.  I never really grokked oauth... brief googling tokens seem ok but I don't think this is token, this is code to get token right? But it's only temporarily valid. So, risk of being in our logs is low.

Really just confirming someone, oauth smarter than norm, thought about it and determined "A OK!"

2023-03-31 16:47 UTC, njharman commented on apps/organizations/tasks.py
> +    if not prefix:
no := this time ;)

2023-03-31 16:47 UTC, njharman commented on apps/organizations/tasks.py
> +        return
Cut superfluous return

2023-03-31 16:47 UTC, njharman commented on revengine/settings/base.py
> +    "NRE_MAILCHIMP_CLIENT_ID": MAILCHIMP_CLIENT_ID,
The PR pre-deployment changes seems to call this `REACT_APP_NRE_MAILCHIMP_CLIENT_ID`

Also `REACT_APP_NRE_MAILCHIMP_CLIENT_SECRET`

Neither of which do I see grepping code.

2023-03-31 16:47 UTC, njharman commented on apps/organizations/tasks.py
> +        logger.exception(
Uncovered Exception

2023-03-31 19:10 UTC, benjaminEwhite commented on .envrc.example
> +export REACT_APP_HUB_GOOGLE_MAPS_API_KEY=
That is correct. It was missing and became relevant in work that Gui was doing on DEV-3296 that got merged into this branch.

2023-03-31 19:14 UTC, benjaminEwhite commented on revengine/settings/base.py
> +    "NRE_MAILCHIMP_CLIENT_ID": MAILCHIMP_CLIENT_ID,
`REACT_APP_` is not explicitly in our code. The React build, however, looks for env vars with that prefix and they become available in the SPA env at build time. See: https://create-react-app.dev/docs/adding-custom-environment-variables/

2023-03-31 19:28 UTC, benjaminEwhite commented on apps/organizations/tasks.py
> +        request_data,
My thinking was that the code has a very short TTL, so even if in logs, no impact, but just to be safe, I've removed all logs of the code.

2289a3c3b119e

2023-03-31 19:28 UTC, benjaminEwhite commented on apps/organizations/tasks.py
> +    """ """
2289a3c3b119e

2023-03-31 19:28 UTC, benjaminEwhite commented on apps/organizations/tasks.py
> +            oauth_code,
2289a3c3b119e

2023-03-31 19:29 UTC, benjaminEwhite commented on apps/organizations/tasks.py
> +    if not response.status_code == status.HTTP_200_OK:
d2dd0a7db4a

2023-03-31 19:31 UTC, benjaminEwhite commented on apps/organizations/tasks.py
> +def exchange_mailchimp_oauth_code_for_server_prefix_and_access_token(rp_id: int, oauth_code: str) -> None:
ac507540d0e

2023-03-31 19:32 UTC, benjaminEwhite commented on apps/organizations/tasks.py
> +    if not prefix:
Hah. Thanks for the reminder!  cbe7a9991ebee

2023-03-31 19:33 UTC, benjaminEwhite commented on apps/organizations/tasks.py
> +        return
8c83c58e0aa35

2023-03-31 19:37 UTC, benjaminEwhite commented on revengine/settings/base.py
> +    "NRE_MAILCHIMP_CLIENT_ID": MAILCHIMP_CLIENT_ID,
Oh, to make matters more confusing -- there are two contexts in which env vars for spa get used. One is This place -- these values get used in deployed environments.

However, in our local dev environment using webpack to serve the SPA, it also looks for `REACT_APP` prepended vars to be set, but it then turns them into the non prefixed version (see here: https://github.com/newsrevenuehub/rev-engine/blob/main/spa/src/appSettings.js#L58-L68).  

I believe everything though quite confusing, does work out here, env var wise.

2023-03-31 19:54 UTC, benjaminEwhite commented on apps/organizations/tasks.py
> +        logger.exception(
1c44ce84211c

2023-04-03 18:41 UTC, njharman commented on revengine/settings/base.py
> +    "NRE_MAILCHIMP_CLIENT_ID": MAILCHIMP_CLIENT_ID,
Ok. I will, probably, ask same question every time. Might be worth line of explanation comment above these vars in Python code.

Please resolve convo.

2023-04-03 18:46 UTC, njharman approved these changes
Looks good, one conversation left open for you to read/consider.

2023-04-26 19:27 UTC, merged