Dev 3301 handle mailchimp email list selection from spa
newsrevenuehub/rev-engine pull request #1060
Opened 2023-03-24 22:27 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
This is the second of 2 stacked PRs:

1. https://github.com/newsrevenuehub/rev-engine/pull/1125
2. This one

#### What's this PR do?
- Creates AudienceList modal component
- Implements logic around showing the Audience List modal
- Creates 2 temporary BE fields so that the FE doesn't break (as soon as BE is implemented, no FE should be necessary as it's already done)

#### Why are we doing this? How does it help us?
This is the final step to connect Mailchimp to the user, selecting the email Audience List.

#### How should this be manually tested? Please include detailed step-by-step instructions.
Can't test right now. But can check that Audience List modal UI is correct in storybook.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
yes

#### Have automated unit tests been added? If not, why?
yes

#### How should this change be communicated to end users?
Mailchimp connection final step is done (FE work)

#### Are there any smells or added technical debt to note?
No

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3301

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
Yes, BE work implementing audience list selection.
Parent ticket: https://news-revenue-hub.atlassian.net/browse/DEV-3257

2023-03-27 20:22 UTC, nrh-cklimas requested changes

2023-03-27 20:22 UTC, nrh-cklimas commented on spa/src/components/common/Modal/AudienceListModal/AudienceListModal.tsx
> +              {sortedAudienceList.length &&
```suggestion
              {sortedAudienceList.length > 0 &&
```

I just learned this, that if length is 0 you will get 0 onscreen instead of rendering nothing.

2023-03-27 20:22 UTC, nrh-cklimas commented on spa/src/components/common/Modal/AudienceListModal/AudienceListModal.tsx
> +                  <MenuItem key={audience?.name} value={audience?.id} data-testid={`select-revenue-program-${index}`}>
I don't think you need optional chaining on any of these, e.g. everything in here can be `audience.name` instead of `audience?.name`.

2023-03-27 20:22 UTC, nrh-cklimas commented on spa/src/components/common/Modal/AudienceListModal/AudienceListModal.tsx
> +        <Button color="information" disabled={loading! || isLoading} type="submit" data-testid="select-audience-submit">
```suggestion
        <Button color="information" disabled={loading || isLoading} type="submit" data-testid="select-audience-submit">
```

2023-03-27 20:22 UTC, nrh-cklimas commented on spa/src/hooks/useRevenueProgram.ts
> +export default function useRevenueProgram(): useRevenueProgramResult {
It feels more in line with how we are using other data retrieval hooks to put the RP ID as the argument to this hook, rather than make it an argument to `updateRevenueProgram`. That way, the hook can be used to retrieve data about a RP, and that retrieval could be invalidated after `updateRevenueProgram` runs.

2023-03-27 20:22 UTC, nrh-cklimas commented on spa/src/hooks/useRevenueProgram.ts
> +      onSuccess: () => queryClient.invalidateQueries({ queryKey: ['user'] })
I think a comment explaining why we're invalidating the user query would be helpful here.

2023-03-27 20:22 UTC, nrh-cklimas commented on spa/src/components/dashboard/Dashboard.js
>  import { useEffect } from 'react';
We should have unit tests for these changes.

2023-03-27 21:58 UTC, GuiMend commented on spa/src/components/common/Modal/AudienceListModal/AudienceListModal.tsx
> +                  <MenuItem key={audience?.name} value={audience?.id} data-testid={`select-revenue-program-${index}`}>
Thanks. Added it before I had the TS defined

2023-03-27 22:00 UTC, GuiMend commented on spa/src/components/common/Modal/AudienceListModal/AudienceListModal.tsx
> +import useRevenueProgram from 'hooks/useRevenueProgram';
They are from different files. With this comment you are suggesting I add `useRevenueProgram` to `useContributionPage`? Not sure they match 🤔

2023-03-27 22:21 UTC, GuiMend commented on spa/src/components/common/Modal/AudienceListModal/AudienceListModal.tsx
> +import useRevenueProgram from 'hooks/useRevenueProgram';
Hey @nrh-cklimas , not sure I agree with merging `useRevenueProgram` into `useContributionPage`. I think they are different hooks for different purposes.

2023-03-28 15:41 UTC, nrh-cklimas commented on spa/src/components/common/Modal/AudienceListModal/AudienceListModal.tsx
> +import useRevenueProgram from 'hooks/useRevenueProgram';
I misread this--thought you were importing twice from the same file.

2023-03-28 15:47 UTC, nrh-cklimas commented on spa/src/components/dashboard/Dashboard.test.tsx
> +jest.mock('components/common/Modal/AudienceListModal');
```suggestion
jest.mock('components/common/Modal/AudienceListModal/AudienceListModal');
```

Mocks need to match the exact path of the file you've created the `__mock__` for. This is mocking `components/common/Modal/AudienceListModal/index.ts`, which misses the mock you had created.

2023-03-28 20:16 UTC, GuiMend commented on spa/src/components/dashboard/Dashboard.test.tsx
> +jest.mock('components/common/Modal/AudienceListModal');
Oh 🤦 ... this might have been the issue all along. Thanks. Didn't see that import diff until now 🙃

2023-03-28 20:29 UTC, nrh-cklimas approved these changes

2023-05-26 13:56 UTC, benjaminEwhite commented
Not sure why no review app, but closing and reopening to create.

2023-05-26 20:22 UTC, merged