DEV-3344-login-case-insensitive
newsrevenuehub/rev-engine pull request #1064
Opened 2023-03-28 15:16 UTC by harsha09

#### What's this PR do?
User login should be case-insensitive w.r.t username (Email).
Database still maintains unique emails irrespective of case.

#### Why are we doing this? How does it help us?
As usernames are not case agnostic the user should be given access if credentials are matched.

#### How should this be manually tested? Please include detailed step-by-step instructions.
Open create-account page -> Fill Email with all lowers -> Provide password -> click on create account
Next iteration -> Fill Email with all upper case -> Provide password -> click on create account 
Page should display `This email is already being used by an account. Try signing in.`

Login to admin page -> Click on Add in users section and follow the same process.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
NA

#### Have automated unit tests been added? If not, why?
Yes

#### How should this change be communicated to end users?
NA

#### Are there any smells or added technical debt to note?
Django 4 has a nicer way to implement this using functional unique constraints https://docs.djangoproject.com/en/4.0/ref/models/constraints/#expressions

#### Has this been documented? If so, where?
No

#### What are the relevant tickets? Add a link to any relevant ones.
[DEV-3344]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
`python manage.py migrage`

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
No

2023-03-31 16:26 UTC, benjaminEwhite requested changes
Seems like maybe some of the changes aren't needed??? 

Also, we should have tests of the name case insensitive uniqueness for the Django admin (so in apps.users.test_admin).

2023-03-31 16:26 UTC, benjaminEwhite commented on apps/users/models.py
> +    def validate_unique(self, exclude) -> None:
Is this actually doing anything?  I commented out and ran tests locally, and all tests passed (and if you look at test coverage, this code never executes).

I removed `lookup="icontains"` from UserSerializer, and that caused tests to fail for view -- so maybe that's all that's needed for API layer?

2023-03-31 16:26 UTC, benjaminEwhite commented on apps/users/managers.py
> +        return self.get(**{f"{self.model.USERNAME_FIELD}__iexact": username})
Is this actually required? I tried commenting out and all tests passed locally.

2023-04-05 11:38 UTC, harsha09 commented on apps/users/models.py
> +    def validate_unique(self, exclude) -> None:
We will need `validate_unique` because, users can also be added from Django Admin, this function will enforce the unique constraint on Email (no need to convert to lower or upper case) as DB's unique constraint will fail.

If we remove `validate_unique` function email column can contain duplicate values and api will fail if it encounters more than one email.

For example: A user with email `Test@test.com` is already registered, when another user with email `test@test.com` is being added from Django Admin `validate_unique` function will validate the uniqueness irrespective of case.

2023-04-05 11:40 UTC, harsha09 commented on apps/users/managers.py
> +        return self.get(**{f"{self.model.USERNAME_FIELD}__iexact": username})
We need this as this will allow user to be able to login Admin page irrespective of case and using this method in `validate_unique`.

2023-04-06 11:26 UTC, harsha09 commented on apps/users/models.py
> +    def validate_unique(self, exclude) -> None:
Added UT with bb64bab2d1e361f1114dd03b1f7325f2787080f9

2023-04-06 11:27 UTC, harsha09 commented on apps/users/models.py
> +
Implemented with bb64bab2d1e361f1114dd03b1f7325f2787080f9

2023-04-12 20:06 UTC, x110dc approved these changes
This LGTM.

2023-04-13 13:42 UTC, benjaminEwhite approved these changes

2023-04-13 18:44 UTC, merged