DEV-3454 | Fix receipt emails bug
newsrevenuehub/rev-engine pull request #1065
Opened 2023-03-28 18:15 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-03-31 17:27 UTC, njharman requested changes
Looks good.

1. Do not the send_templated emails also potentially suffer from this issue and need to be similarly refactored? The "Generally AC"
2. Noticed that apps/users/views.py:382 send_templated_email is called without delay (in signal handler for reset_password_token_created). I don't believe Django signals are asynchronous. But shouldn't the send mail be asynchronous .delay()?

2023-03-31 18:34 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            logger.info("Contribution.handle_thank_you_email: the parent org (%s) sends emails with NRE", org.id)
```suggestion
            logger.debug("Contribution.handle_thank_you_email: the parent org (%s) sends emails with NRE", org.id)
```

2023-03-31 18:34 UTC, benjaminEwhite commented on apps/contributions/models.py
>          logger.info("`Contribution.handle_thank_you_email` called on contribution with ID %s", self.id)
```suggestion
        logger.debug("`Contribution.handle_thank_you_email` called on contribution with ID %s", self.id)
```

2023-03-31 19:22 UTC, benjaminEwhite commented
Thanks @njharman 

That's a good point re: the other email task. I ended up pushing up a commit that refactors both `send_templated_email` and `send_templated_email_with_attachment` so that they don't have possibility of accessing out of scope assets.  I've updated the PR description accordingly.

Re: apps/users/views.py:382 send_templated_email -- although Git blame shows that I wrote that code, I don't know off hand why I made it synchronous instead of async. I'm inclined here to leave as is with an "if it ain't broke..." mentality.

2023-04-03 19:01 UTC, njharman approved these changes
Ship it

2023-04-06 20:24 UTC, x110dc commented
Closing in favor of https://github.com/newsrevenuehub/rev-engine/pull/1090

2023-04-06 20:24 UTC, closed without merging