Dev 3187 setup profiling
newsrevenuehub/rev-engine pull request #1066
Opened 2023-03-28 18:56 UTC by harsha09

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
Setup profiling

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-04-25 05:17 UTC, x110dc requested changes
Also, can you research and provide some guidance about what we set `SENTRY_PROFILING_SAMPLE_RATE` to in production? Thanks.

2023-04-25 05:17 UTC, x110dc commented on revengine/settings/deploy.py
> +        _experiments={"profiles_sample_rate": SENTRY_PROFILING_SAMPLE_RATE},
This is the syntax for an older version of the Sentry package. Let's just upgrade to the latest (1.20.0 as of right now) and use the non-experimental syntax.

2023-05-09 10:20 UTC, harsha09 commented on revengine/settings/deploy.py
> +        _experiments={"profiles_sample_rate": SENTRY_PROFILING_SAMPLE_RATE},
Addressed with 0bc73cbf7377f1df9538f960c10b59b4f5341746.

2023-05-23 20:02 UTC, x110dc requested changes

2023-05-23 20:02 UTC, x110dc commented on revengine/settings/base.py
> +SENTRY_PROFILING_SAMPLE_RATE = float(os.getenv("SENTRY_PROFILING_SAMPLE_RATE", "1.0"))
Let's set the default rate to something that would be safe in production, so may "0.1". Then good to go.

2023-07-03 16:26 UTC, x110dc approved these changes

2023-07-03 19:08 UTC, merged