DEV-3289: Add plan upgrade prompt on test email
newsrevenuehub/rev-engine pull request #1068
Opened 2023-03-28 21:31 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
Adds upgrade plan prompt on test emails for free users.

#### Why are we doing this? How does it help us?
This shows the user that we offer more features for paid tiers.

#### How should this be manually tested? Please include detailed step-by-step instructions.
Can't be tested yet (blocked by https://news-revenue-hub.atlassian.net/browse/DEV-3308)

As soon as unblocked, can be tested by:
- Request for a test email in the edit style page with a user in FREE, CORE and PLUS plan
- FREE should display the upgrade prompt
- CORE and PLUS should not show the prompt

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
yes

#### Have automated unit tests been added? If not, why?
yes

#### How should this change be communicated to end users?
n/a

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3289

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
https://news-revenue-hub.atlassian.net/browse/DEV-3308

2023-03-29 19:27 UTC, benjaminEwhite submitted a review, later dismissed

2023-06-07 14:19 UTC, benjaminEwhite requested changes
Overall looks good. Just one request for a small change to the `SendContributionEmailData` type definition.

2023-06-09 14:49 UTC, GuiMend commented on apps/emails/tasks.py
> +    show_upgrade_prompt: bool | None
Left it `show_upgrade_prompt: bool` because I can't add the default value here. 👍

2023-06-09 15:15 UTC, benjaminEwhite commented
Closing and reopening because no review app exists (perhaps because of Heroku issues yesterday???).

2023-06-14 18:06 UTC, benjaminEwhite approved these changes

2023-06-14 18:49 UTC, merged