[WIP] DEV-3328 | Back end support for page restrictions
newsrevenuehub/rev-engine pull request #1075
Opened 2023-03-30 19:11 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-03-31 17:55 UTC, njharman requested changes
1. Communicate to endusers: mentioned page limit changed, do not our user docs need to be updated?
2. Pre deployment step: Are we sure, do we need to check that no existing production plans exceed their limits?

Looks good, minor typo, coverage, doc, log requests.

2023-03-31 17:55 UTC, njharman commented on apps/pages/serializers.py
> +        logger.info("DonationPageFullDetailSerializer.validate_publish_limit called with data: %s", data)
debug level log?

2023-03-31 17:55 UTC, njharman commented on apps/pages/serializers.py
> +                "DonationPageFullDetailSerializer.validate_publish_limit returning early because request doesn't attempt to createa or update a page"
typo "createa or" 

Also debug level log?

2023-03-31 17:55 UTC, njharman commented on apps/pages/serializers.py
> +        ):
Can we explain this offset. Or is it obvious to any def who understands these models better than I?

2023-03-31 17:55 UTC, njharman commented on apps/pages/serializers.py
> +                "DonationPageFullDetailSerializer.validate_publish_limit returning early because request doesn't attempt to createa or update a page"
Uncovered by test

2023-03-31 18:12 UTC, benjaminEwhite commented on apps/pages/serializers.py
> +        logger.info("DonationPageFullDetailSerializer.validate_publish_limit called with data: %s", data)
b0b1009c8307

2023-03-31 18:12 UTC, benjaminEwhite commented on apps/pages/serializers.py
> +                "DonationPageFullDetailSerializer.validate_publish_limit returning early because request doesn't attempt to createa or update a page"
b0b1009c8307

2023-03-31 18:12 UTC, benjaminEwhite commented on apps/pages/serializers.py
> +        ):
b0b1009c8307

2023-03-31 18:12 UTC, benjaminEwhite commented on apps/pages/serializers.py
> +                "DonationPageFullDetailSerializer.validate_publish_limit returning early because request doesn't attempt to createa or update a page"
Removed this path in b0b1009c8307

Validation only happens on post and patch anyways,  so wasn't necessary.

2023-04-03 19:00 UTC, njharman approved these changes
Ship it!

2023-04-06 17:14 UTC, x110dc approved these changes

2023-04-11 14:22 UTC, njharman approved these changes
looks good

2023-04-12 13:17 UTC, nrh-cklimas commented on apps/pages/serializers.py
> +        offset = 0 if self.instance else 1
@benjaminEwhite @njharman I'm wondering if this line is our problem, and we need to be a little more nuanced about this logic. I think this assumes that the created page will be published (adding 1 to the count of existing published pages in line 261), but that is not actually true in most cases. Does that seem right to you?

Here's the unit test I wrote to try to exercise this:

```python
# Skipping PLUS here because there is no publish limit on that plan.

    @pytest_cases.parametrize("plan", (Plans.FREE.value, Plans.CORE.value))
    def test_can_create_when_at_publish_limit(self, plan, hub_admin_user):
        org = OrganizationFactory(plan_name=plan)
        rp = RevenueProgramFactory(organization=org)
        print(org.plan.name, org.plan.publish_limit, org.plan.page_limit)
        DonationPageFactory.create_batch(org.plan.publish_limit, published_date=timezone.now(), revenue_program=rp)
        serializer = DonationPageFullDetailSerializer(
            data={
                "slug": "my-new-page",
                "revenue_program": rp.pk,
            }
        )
        request = APIRequestFactory().post("/")
        request.user = hub_admin_user
        serializer.context["request"] = request
        assert serializer.is_valid() is True
```

2023-04-26 18:17 UTC, nrh-cklimas commented on apps/pages/serializers.py
> +        # If the page already exists but is gaining a publish date:
@benjaminEwhite I'm not sure if this logic can be simpler.

2023-04-26 18:18 UTC, nrh-cklimas commented on apps/pages/serializers.py
> +        if "published_date" in data:
@benjaminEwhite not sure if we need to do something here if the object is already published.

2023-04-27 14:51 UTC, benjaminEwhite commented on apps/pages/serializers.py
> +            offset = 1
```suggestion
        if any([
            # If the page already exists but is gaining a publish date
            self.instance and self.instance.published_date is None and data["published_date"] is not None,
            # If the page is being created with a publish date:
            not self.instance and data["published_date"] is not None,
        ]):
            offset = 1
        # If the page is being created with a publish date:
        if not self.instance and data["published_date"] is not None:
            offset = 1
```

2023-04-27 15:25 UTC, nrh-cklimas commented on apps/pages/serializers.py
> +        if "published_date" in data:
Two things I wasn't clear on here were...
- In methods like `validate_publish_limit` we're checking both `data` and `self.instance`. Should I do that here too?
- Originally I wrote this logic to prevent the validator from blocking people from creating new pages if the publish limit had been met. I think that may not actually be needed anymore because the publish limit validator should now be smart enough to not block that.

2023-04-27 15:25 UTC, nrh-cklimas commented on apps/pages/serializers.py
> +            offset = 1
Works for me--updated in 16a47fbaa6e7042473a6bc870db552e757b71c24

2023-04-27 17:40 UTC, benjaminEwhite commented on apps/pages/serializers.py
> +        if "published_date" in data:
In `validate`? I don't think we need to do anything with self.instance here.  It's enough to know that published_date appears in the serializer data.

Yeah, looks to me like you can still create new page (if unpublished) when at publish limit. And that's tested in `test_can_create_when_at_publish_limit`, right?

2023-04-27 17:42 UTC, nrh-cklimas commented on apps/pages/serializers.py
> +        if "published_date" in data:
Yup, that's correct re: the unit test. It sounds like we're good to go here.

2023-04-28 14:43 UTC, merged