DEV-3372: Add CORE tests to styled email
newsrevenuehub/rev-engine pull request #1079
Opened 2023-03-31 19:40 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
Adds tests to custom styles for CORE plan.

#### Why are we doing this? How does it help us?
We didn't have tests for the CORE plan because it was inexistent before.

#### How should this be manually tested? Please include detailed step-by-step instructions.
- Contribute to a custom styled donation page from a CORE plan organization
- Should show custom style email receipts.
- Free and Plus emails should continue to work

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
No

#### Have automated unit tests been added? If not, why?
Yes

#### How should this change be communicated to end users?
n/a

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3372

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
Don't think there are any next steps.
Related tickets: https://news-revenue-hub.atlassian.net/browse/DEV-3170

2023-04-05 16:03 UTC, njharman requested changes
The AC seem to cover more than is in this ticket. Perhaps the AC are "bad", victim of chain of tickets doing bits and pieces of this functionality.

The PR Manual Test instructions don't seem to cover all the AC. I don't see any tests covering AC4 or 5, contribution portal.  If other tickets covered those that should be mentioned in PR.

Also the PR Test instructions should include;

1. test for the Plus customization
2. test that Core/Plus use generic when no default page set
3. clarify that Free should not have any customization even if default page set

2023-04-05 18:20 UTC, GuiMend commented on apps/emails/tests/test_tasks.py
> +            expect_missing = (custom_button_background, custom_header_background, default_logo)
It's because the "Thank you email" doesn't have background colors in the template:
https://www.figma.com/file/uZpKfBbZ4HxUpNIsImkVeh/%5BDES-9%5D-Transactional-Emails?node-id=25-78&t=HQ8R9eoU9RJH2JKO-0

I can add a comment in the code to make it clearer.

2023-04-05 18:20 UTC, GuiMend commented on apps/contributions/tests/test_models.py
> +            expect_missing = (custom_button_background, default_logo)
In this case, the email template doesn't have a CTA button to have the custom background applied.
https://www.figma.com/file/uZpKfBbZ4HxUpNIsImkVeh/%5BDES-9%5D-Transactional-Emails?node-id=42-164&t=HQ8R9eoU9RJH2JKO-0

I will add a comment in the code to make it clearer.

2023-04-05 19:04 UTC, GuiMend commented
Updated PR description with @njharman's suggestion and moved unhandled ACs to appropriate ticket

2023-04-06 17:38 UTC, njharman approved these changes
Ship it!

2023-04-19 19:50 UTC, merged