DEV-1657: Add line 2 support for donation address
newsrevenuehub/rev-engine pull request #1085
Opened 2023-04-05 18:05 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
This is the second of 2 stacked PRs:
1. https://github.com/newsrevenuehub/rev-engine/pull/1084
2. This one

#### What's this PR do?
- Adds Line 2 support for donation address
- Adds button text variation

#### Why are we doing this? How does it help us?
Enable users with complementary information (apartment, suite) to fill in the correct full address when making donations.

#### How should this be manually tested? Please include detailed step-by-step instructions.
- Make a donation and add Line 2 address.
- Check stripe address to see if entire address is saved successfully (including line 2)

- Make a donation without using Line 2 address
- Make sure that it keeps working as expected.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
Yes

#### Have automated unit tests been added? If not, why?
yes

#### How should this change be communicated to end users?
Line 2 of address now enabled in donations.

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-1657

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
https://news-revenue-hub.atlassian.net/browse/DEV-3442
https://news-revenue-hub.atlassian.net/browse/DEV-3443

2023-04-05 19:23 UTC, nrh-cklimas commented on spa/src/components/donationPage/DonationPage.js
> +        line2: data.mailing_complement || '', // stripe will complain if its null or undefined, and it's an optional field
```suggestion
        line2: data.mailing_complement ?? '', // stripe will complain if its null or undefined, and it's an optional field
```

2023-04-05 21:30 UTC, nrh-cklimas requested changes

2023-04-05 21:30 UTC, nrh-cklimas commented on spa/src/components/base/Button/Button.tsx
> +  &&.NreButtonText {
I talked with Rachel about this button and we think right now that it's not likely to be used elsewhere in the app. For now, could you move these changes into the DDonorAddress component?

2023-04-05 21:35 UTC, nrh-cklimas commented
I'd suggest one more QA test:

1. Add line 2 in a contribution.
2. Type something in the additional field.
3. Hide line 2.
4. Confirm the contribution doesn't contain line 2.

2023-04-06 21:02 UTC, GuiMend commented on spa/src/components/base/Button/Button.stories.tsx
It's not, I just added a disabled state for the `outlined` variant (even if we don't have the style implemented yet, it still has a default disabled state that I added just in case)

2023-04-07 13:36 UTC, nrh-cklimas commented on spa/src/components/base/Button/Button.stories.tsx
I see. Well, it's fine to include, I think, but we should explain to Rachel that the story doesn't correspond to anything she's spec'd out.

2023-04-07 13:38 UTC, GuiMend commented on spa/src/components/base/Button/Button.stories.tsx
Sure, I will let her know.

2023-04-07 13:40 UTC, nrh-cklimas approved these changes

2023-04-12 13:33 UTC, nrh-cklimas approved these changes

2023-04-17 19:14 UTC, merged