DEV-3442: Configure address editor block
newsrevenuehub/rev-engine pull request #1093
Opened 2023-04-10 21:28 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
Adds the following to address editor block:
- Address optionality
- Show only Zip and Country fields

#### Why are we doing this? How does it help us?
Increase flexibility on address information when it's not required

#### How should this be manually tested? Please include detailed step-by-step instructions.
Edit address, make a contribution and see that the flow works unchanged:

1) Check address optional fields
- Make sure contribution no longer requires any address fields to move forward 

2) Check Optional and go back to Required:
- Make sure it keeps working as expected

3) Make no changes
- Default/legacy address editor configurations should keep working

4) Select only Zip and Country code + Optional
- Make sure only these 2 fields show up and they are optional

5) Select only Zip and Country code + Required
- Make sure only these 2 fields show up and they are required

6) Select only zip + country
- Make sure State label configuration hides
 
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
Yes

#### Have automated unit tests been added? If not, why?
yes

#### How should this change be communicated to end users?
Addresses for contribution now are configurable and more flexible to fit your needs.

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3442

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
https://news-revenue-hub.atlassian.net/browse/DEV-3443

2023-04-13 13:33 UTC, nrh-cklimas requested changes

2023-04-13 13:33 UTC, nrh-cklimas commented on spa/src/components/donationPage/pageContent/DDonorAddress.test.tsx
> +      tree({}, { element: { ...element, content: { zipAndCountryOnly: true } } });
Let's add an `expect.assertions(1);` so that if something gets garbled in the conditional logic below, this test fails.

2023-04-13 15:11 UTC, GuiMend commented on spa/src/components/pageEditor/elementEditors/donorAddress/DonorAddressEditor.tsx
> +                  checked={!!elementContent.additionalStateFieldLabels?.includes('region')}
Same here

2023-04-13 17:22 UTC, nrh-cklimas commented on spa/src/components/pageEditor/elementEditors/donorAddress/DonorAddressEditor.tsx
> +                  checked={!!elementContent.additionalStateFieldLabels?.includes('province')}
Ah, right.

2023-04-13 17:23 UTC, nrh-cklimas approved these changes

2023-04-14 12:57 UTC, nrh-cklimas commented on apps/contributions/serializers.py
> +    street = serializers.CharField(max_length=255, required=False, default="", allow_blank=True)
I _think_, but ask a real BE dev, that `allow_blank=True` implies `required=False`.

2023-04-14 12:59 UTC, nrh-cklimas commented on spa/src/components/donationPage/DonationPage.js
> +        city: data.mailing_city ?? '',
This feels like it's worth a comment about Stripe allowing empty strings but not `undefined`, since that was confusing initially.

2023-04-14 13:23 UTC, nrh-cklimas commented on spa/src/components/pageEditor/elementEditors/donorAddress/DonorAddressEditor.tsx
> +  const prevZipAndCountryOnly = usePreviousState(zipAndCountryOnly);
Instead of using `usePreviousState` and the effect below, let's call `handleChangeRequiredFields` from the event handlers below (if I'm understanding correctly, the effect you have should only fire in response to changes in the controls below). The new React docs have a [good explanation of best practice here](https://react.dev/learn/you-might-not-need-an-effect#sharing-logic-between-event-handlers).

2023-04-14 13:23 UTC, nrh-cklimas requested changes
A couple small suggested changes.

2023-04-14 15:17 UTC, GuiMend commented on spa/src/components/pageEditor/elementEditors/donorAddress/DonorAddressEditor.tsx
> +  const prevZipAndCountryOnly = usePreviousState(zipAndCountryOnly);
I tried doing that initially @nrh-cklimas , but if we call `onChangeElementContent` and `onChangeElementRequiredFields` it only runs the first function called. The second one is "skipped", that's why I went with this solution.

In the function `addBatchChange` which is responsible for doing the update, we have `setBatchChanges((existing) => ({ ...existing, ...value }))`, so it should keep the "previousState" preserved, which would mean that running both function together is possible. But the issue is that we want to save the `elements` prop, that is an array inside of `value`, and not `existing`, so the previous state isn't preserved as we want it to.

2023-04-14 15:20 UTC, GuiMend commented on spa/src/components/pageEditor/elementEditors/donorAddress/DonorAddressEditor.tsx
> +  const prevZipAndCountryOnly = usePreviousState(zipAndCountryOnly);
For that to work, we would have to refactor `addBatchChange` function, which could cause some side effects as it's a really important function. (Not sure we would want to go there in this ticket).

One additional "benefit" from the side effect that you pointed out on the reference link, is that in our case it's good to have the function be called on the refresh because the default "requiredFields" is an empty array, and when the function runs because of the side effect it updates the "requiredFields" to the correct value.

@nrh-cklimas , do we have a way of setting a default "requiredFields"? I didn't find it looking around.

2023-04-17 14:11 UTC, nrh-cklimas commented on spa/src/components/pageEditor/elementEditors/donorAddress/DonorAddressEditor.tsx
> +  const prevZipAndCountryOnly = usePreviousState(zipAndCountryOnly);
I created DEV-3506 as a followup to fix the main problem you've described here. Could you put a comment here with that story name so we can follow up on it there?

We need to address the second part of your comment though in this PR if I'm not mistaken--a user could add an Address block, never edit it, and the resulting contribution page would be in an incorrect state with required fields. (Let me know if I have that wrong.)

[AddElementModal](https://github.com/newsrevenuehub/rev-engine/blob/main/spa/src/components/pageEditor/editInterface/pageElements/addElementModal/AddElementModal.js#L22) is where new elements are added to the page. We have functionality there for setting default content and we'd want to expand that aspect of it to include default required fields. I think now would be a great time to refactor that into a hook that we can get good unit test coverage on, because complexity is starting to get high on the component and we have no unit tests on it now. Don't hesitate to follow up with me on Slack on how we can approach it.

2023-04-18 16:38 UTC, GuiMend commented
@nrh-cklimas, I talked with @benjaminEwhite about the address validation issues and not having the "required" validation for legacy donation pages for a while until we fix the entire address data structure on https://news-revenue-hub.atlassian.net/browse/DEV-3440 is acceptable as we already have the FE validation.

2023-04-18 19:24 UTC, nrh-cklimas commented on spa/src/components/pageEditor/editInterface/pageElements/addElementModal/AddElementModal.js
> +      ...(defaultRequiredFields[type] && { requiredFields: defaultRequiredFields[type] }),
Could we make it parallel how `content` is set above it? I think it achieves the same purpose as the line above it, so let's make it look the same if we can.

Is it possible to add tests, either in Cypress or Jest, to cover this new behavior?

2023-04-20 14:10 UTC, benjaminEwhite approved these changes

2023-04-20 20:02 UTC, nrh-cklimas requested changes

2023-04-20 20:35 UTC, GuiMend commented on spa/src/components/pageEditor/editInterface/pageElements/addElementModal/AddElementModal.tsx
> +        <S.PageItemWrapper key={`${element?.displayName}${i}`}>
It's because `displayName` is `?` inside ContributionPageElement TS
```js
export interface ContributionPageElement {
 ...
  /**
   * User-visible name of the element.
   */
  displayName?: string;
```

2023-04-21 14:13 UTC, nrh-cklimas commented on spa/src/components/pageEditor/editInterface/pageElements/addElementModal/AddElementModal.tsx
> +        <S.PageItemWrapper key={`${element?.displayName}${i}`}>
If that's the case, maybe we want something like

```tsx
<S.PageItemWrapper key={`${element.displayName ?? ''}${i}`}></code>
```

Or just leave it without the `?`, since that's operating on `element`, not `element.displayName`.

2023-04-21 15:07 UTC, GuiMend commented on spa/src/components/pageEditor/editInterface/pageElements/addElementModal/AddElementModal.tsx
> +        <S.PageItemWrapper key={`${element?.displayName}${i}`}>
What about just affirming that it won't be undefined/null? It should always have a displayName in this part of the code.
`element.displayName!`

2023-04-21 16:16 UTC, nrh-cklimas approved these changes

2023-04-26 21:23 UTC, nrh-cklimas requested changes

2023-04-26 21:23 UTC, nrh-cklimas commented on spa/src/components/base/Radio/Radio.stories.tsx
> +    <FormControlLabel control={<Radio checked={props.checked} />} disabled={true} label="Disabled Radio Label" />
```suggestion
    <FormControlLabel control={<Radio checked={props.checked} />} disabled label="Disabled Radio Label" />
```

2023-04-26 21:23 UTC, nrh-cklimas commented on spa/src/components/pageEditor/elementEditors/donorAddress/DonorAddressEditor.styled.ts
> +  color: ${({ theme }) => theme.colors.muiGrey[900]};
```suggestion
  color: ${({ theme }) => theme.basePalette.greyscale.black};
```

2023-04-26 21:23 UTC, nrh-cklimas commented on spa/src/components/pageEditor/elementEditors/donorAddress/DonorAddressEditor.styled.ts
> +  color: ${({ theme }) => theme.colors.muiGrey[600]};
```suggestion
  color: ${({ theme }) => theme.basePalette.greyscale.grey1};
```

2023-04-26 21:23 UTC, nrh-cklimas commented on spa/src/components/pageEditor/elementEditors/donorAddress/DonorAddressEditor.styled.ts
> +  color: ${({ theme }) => theme.colors.muiGrey[900]};
Just noting the updates on the changed lines--looks like there are other colors in here that could be changed, but up to you if you want to tackle that here.

2023-05-01 18:22 UTC, merged