DEV-3443: Make address block deletable in list view
newsrevenuehub/rev-engine pull request #1094
Opened 2023-04-11 00:22 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
Make address block deletable from list view

#### Why are we doing this? How does it help us?
Making address more flexible for contributions that don't need to know this information.

#### How should this be manually tested? Please include detailed step-by-step instructions.
- Make a contribution to an existing page with the address block.
- Edit that donation page, remove the address block, and save the page.
- Make another contribution and make sure everything works as expected.
- Add the address block once again, save, and make a contribution. Should still work as expected
- Create a new donation page, address block should initially be in the page.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
yes

#### Have automated unit tests been added? If not, why?
n/a

#### How should this change be communicated to end users?
Address block now deletable from donation pages

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3443

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
Not a next step, but it's a related ticket https://news-revenue-hub.atlassian.net/browse/DEV-3442

2023-04-12 18:36 UTC, nrh-cklimas requested changes

2023-04-12 18:36 UTC, nrh-cklimas commented on apps/contributions/serializers.py
> +    mailing_country = serializers.CharField(max_length=80, write_only=True, required=False, default="")
These changes don't appear related to this specific PR?

2023-04-13 13:03 UTC, GuiMend commented on apps/contributions/serializers.py
> +    mailing_country = serializers.CharField(max_length=80, write_only=True, required=False, default="")
It is related, I've added the explanation in the PR description:
> Make address fields optional on BE so that it doesn't block a donation that doesn't have address information

2023-04-13 13:10 UTC, nrh-cklimas approved these changes

2023-04-13 14:28 UTC, benjaminEwhite approved these changes

2023-04-27 20:45 UTC, GuiMend commented
Ticket closed. Address block cannot be deletable because stripe needs at least postal code + country

2023-04-27 20:45 UTC, closed without merging