DEV-2884: make Apple Pay domain verification a background job after s…
newsrevenuehub/rev-engine pull request #1096
Opened 2023-04-13 07:29 UTC by leo-dcfa

…tripe oauth succcess

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

- Adds automation to verify apple domain as a celery task after successful stripe oauth callback

#### Why are we doing this? How does it help us?

We expect the Apple Pay domain to be created as part of the onboarding process

#### How should this be manually tested? Please include detailed step-by-step instructions.

Cannot be tested manually outside of production, see unit tests for details

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

N/A

#### Have automated unit tests been added? If not, why?

Yes

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

N/A

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-2884]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

N/A

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

N/A

2023-04-17 18:52 UTC, benjaminEwhite commented on apps/contributions/tasks.py
> +            "[task_verify_apple_domain] Apple Pay domain verified for revenue program %s with slug %s",
We should standardize how we offset function/method names. I like this style you're using here. For a while I was doing ``foo`` but recently have just been doing `foo`.  Square brackets seem like a good way to go.

2023-04-17 18:53 UTC, benjaminEwhite commented on apps/contributions/tasks.py
> +            "[task_verify_apple_domain] task failed for slug %s due to exception: %s", revenue_program_slug, ex.error
Would we get `ex.error` anyways just by virtue of exception being logged via .exception?

2023-04-17 19:20 UTC, benjaminEwhite commented on apps/contributions/tests/test_tasks.py
> +        mock_rp_get.assert_called_with(slug=slug)
It's a little hard to follow what this test is doing and why. Would be a lot cleaner, IMO, to just have a `test_task_verify_apple_domain_happy_path` and a `test_task_verify_apple_domain_when_stripe_error`.   Also, not sure why we're mocking out `RevenueProgram.get`. We should ensure there's an rp with the expected slug in the db, then just test that calling the task with that slug causes it to be retrieved etc.

2023-04-17 19:21 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        logger.info("Attempting to perform oauth with Stripe for revenue program %s", revenue_program_id)
Prefix the log message with `[stripe_oauth]`

2023-04-17 19:21 UTC, benjaminEwhite commented on apps/contributions/views.py
> +                "Payment provider not yet created for revenue program %s, proceeding with creation...",
Prefix

2023-04-17 19:21 UTC, benjaminEwhite commented on apps/contributions/views.py
> +            logger.info("Payment provider for revenue program %s created: %s", revenue_program_id, payment_provider.id)
Prefix

2023-04-17 19:21 UTC, benjaminEwhite commented on apps/contributions/views.py
> +                "Updating existing payment provider %s for revenue program %s", payment_provider.id, revenue_program_id
And here -- not going to make this comment again, but apply it anywhere else relevant.

2023-04-17 19:22 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        logger.info("Delaying Apple Pay domain verification for revenue program slug: %s", revenue_program.slug)
We're not really delaying anything, just calling an async task.

2023-04-17 21:22 UTC, leo-dcfa commented on apps/contributions/views.py
> +        logger.info("Delaying Apple Pay domain verification for revenue program slug: %s", revenue_program.slug)
good point. Badly named methods lead to bad assumptions 😂

2023-04-17 21:23 UTC, leo-dcfa commented on apps/contributions/tasks.py
> +            "[task_verify_apple_domain] task failed for slug %s due to exception: %s", revenue_program_slug, ex.error
I tried it, but the linter complained so I changed it to `ex.error`

2023-04-17 21:24 UTC, leo-dcfa commented on apps/contributions/tasks.py
> +            "[task_verify_apple_domain] Apple Pay domain verified for revenue program %s with slug %s",
nice - I wonder if we could achieve the same using some logging configuration, instead of doing it manually on each log statement

2023-04-17 21:32 UTC, leo-dcfa commented on apps/contributions/tests/test_tasks.py
> +        mock_rp_get.assert_called_with(slug=slug)
It's a good point, I'll separate into two methods. It's also the standard you establish in rev engine, so it makes sense

Concerning mock, depends how you see this - having a record on a db is closer to an integration than a unit test. We technically don't care about the result of mock_rep_get; we just care that the method is called with the correct parameters.

2023-04-17 21:40 UTC, leo-dcfa commented on apps/contributions/views.py
> +        logger.info("Attempting to perform oauth with Stripe for revenue program %s", revenue_program_id)
fixed

2023-04-17 21:40 UTC, leo-dcfa commented on apps/contributions/views.py
> +                "Payment provider not yet created for revenue program %s, proceeding with creation...",
Fixed

2023-04-17 21:40 UTC, leo-dcfa commented on apps/contributions/views.py
> +            logger.info("Payment provider for revenue program %s created: %s", revenue_program_id, payment_provider.id)
Fixed

2023-04-17 21:40 UTC, leo-dcfa commented on apps/contributions/views.py
> +                "Updating existing payment provider %s for revenue program %s", payment_provider.id, revenue_program_id
Fixed

2023-04-20 13:40 UTC, benjaminEwhite commented on apps/contributions/tasks.py
> +            "[task_verify_apple_domain] Apple Pay domain verified for revenue program %s with slug %s",
Yeah, probably configure the logging to automatically prepend the function name with desired formatting. Think we could do something with a decorator to achieve this:

https://ankitbko.github.io/blog/2021/04/logging-in-python/

And looks like we could use `inspect` to derive function names to pass to the logger: https://stackoverflow.com/questions/5067604/determine-function-name-from-within-that-function-without-using-traceback

Not suggesting that we do that in this ticket, but it would be a worthwhile thing to document and standardize in our code base.

2023-04-20 13:42 UTC, benjaminEwhite commented on apps/contributions/tasks.py
> +            "[task_verify_apple_domain] task failed for slug %s due to exception: %s", revenue_program_slug, ex.error
Oh, more importantly, you're re-raising on next line, which makes my original comment irrelevant.

2023-04-20 13:51 UTC, benjaminEwhite commented on apps/contributions/views.py
>              revenue_program.save()
As long as you're touching contiguous code, I'd like us to start being disciplined about using `update_fields` when we save model instances because it tends to protect against a certain class of race conditions (that stem from saving an instance's local state + some single changed attribute without reference to global state change representing the instance).  DEV-3073 (see [here](https://github.com/newsrevenuehub/rev-engine/pull/927)) standardizes this pattern for views touching the contribution model.

Additionally, in that ticket/PR, I added testing that proves that the underlying model instance gets saved at most _once_ per request session, and with the expected update fields, and that a django reversion revision gets created. Together, these comprise a guarantee that changes to a given model are deliberate (via update_fields), predictable ( via guarantee on number of saves), and auditable (via revisions being created that will provide a clear trail of when model changed and how/why).

2023-04-20 14:01 UTC, benjaminEwhite requested changes
@leo-dcfa this looks good overall. Have one suggestion for a follow up ticket. And then have a suggestion around using `update_fields` in the calls to `.save()` in `apps.contributions.views.py`.  Ideally, we'd adopt a similar pattern as in #927 whereby we have a test that proves that the relevant model instance(s) get(s) saved an expected number of times (ideally only once) per request session, and that `update_fields` is called with right values when saved, and that a revision is created.  

In case it's helpful, you can see the pattern I used for creating an `update_data` set at the top of view functions that gets fields dynamically added. i mutate the instance state and add the mutated property name to `update_data`, then at the end of the request cycle I save the instance if there are any fields in `update_data`. When I save, i set `update_fields` to the value of `update_data` plus the keys for `created` and `modified`, as they are autoadded.

I know you're about to be off so I'd be fine with the less ambitious version here of simply using `update_fields` without refactoring tests right now to guarantee this.

2023-04-20 21:14 UTC, leo-dcfa commented on apps/contributions/views.py
>              revenue_program.save()
Is this part of scope of current ticket though? I just added a few logging statements here

2023-04-20 21:14 UTC, leo-dcfa commented on apps/contributions/tasks.py
> +            "[task_verify_apple_domain] Apple Pay domain verified for revenue program %s with slug %s",
agree it belongs in a separate ticket

2023-04-20 21:20 UTC, leo-dcfa commented on apps/contributions/tasks.py
> +            "[task_verify_apple_domain] Apple Pay domain verified for revenue program %s with slug %s",
New ticket created https://news-revenue-hub.atlassian.net/browse/DEV-3520

2023-04-21 15:44 UTC, benjaminEwhite approved these changes

2023-06-20 20:25 UTC, x110dc requested changes

2023-06-20 20:25 UTC, x110dc commented on coverage.xml
> +<coverage version="7.2.1" timestamp="1681767534851" lines-valid="4412" lines-covered="1474" line-rate="0.3341" branches-valid="908" branches-covered="79" branch-rate="0.087" complexity="0">
This file shouldn't be committed.

2023-06-20 20:36 UTC, leo-dcfa commented on coverage.xml
> +<coverage version="7.2.1" timestamp="1681767534851" lines-valid="4412" lines-covered="1474" line-rate="0.3341" branches-valid="908" branches-covered="79" branch-rate="0.087" complexity="0">
good catch!

2023-06-30 22:09 UTC, x110dc approved these changes

2023-07-03 13:08 UTC, merged