DEV-3303 |  API work to trigger initial creation of mailchimp entities when rp and mailchimp list are newly connected
newsrevenuehub/rev-engine pull request #1106
Opened 2023-04-26 15:12 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-04-26 16:01 UTC, benjaminEwhite commented
Closing and reopening to trigger rebuild because migration had edits.

2023-05-01 22:26 UTC, benjaminEwhite commented
Closing and reopening because migrations changed.

2023-05-11 18:01 UTC, njharman requested changes
Just uncovered (new) code. 

I'm only 90% sure AC2 is covered by RP_MAILCHIMP_LIST_CONFIGURATION_COMPLETE_TOPIC et al as it's the only pubsub code I saw.

2023-05-15 13:35 UTC, benjaminEwhite commented on apps/organizations/apps.py
> +        import apps.organizations.signals  # noqa
7366668425

2023-05-15 13:47 UTC, benjaminEwhite commented on apps/organizations/tasks.py
> +    Publisher.get_instance().publish(settings.RP_MAILCHIMP_LIST_CONFIGURATION_COMPLETE_TOPIC, Message(data=str(rp.id)))
8a8668657d0

2023-05-19 16:52 UTC, benjaminEwhite commented on apps/organizations/models.py
> +                raise MailchimpIntegrationError("Error retrieving recurring contribution product")
In a perfect world, I would have intuited the shared logic ahead of time and abstracted it then. But it would actually require more effort at this point (opposite of lazy) to pull this out for little benefit, so will keep as is.

2023-05-19 16:53 UTC, benjaminEwhite commented on apps/organizations/models.py
> +            raise ValueError("Mailchimp integration not connected for this revenue program")
8069bb64a9c

2023-05-19 16:55 UTC, benjaminEwhite commented on apps/organizations/models.py
> +    def make_mailchimp_recurring_segment(self) -> MailchimpSegment:
Also called in organizations.tasks.py, and tested.

2023-05-19 16:57 UTC, benjaminEwhite commented on apps/organizations/models.py
> +                raise MailchimpIntegrationError("Error retrieving one-time contribution product")
8069bb64a9c2

2023-05-22 17:10 UTC, njharman requested changes
Two PR conversations unresolved. Duplicated below

1) uncovered (https://github.com/newsrevenuehub/rev-engine/pull/1106/files#t543)

if not self.mailchimp_recurring_contributor_segment_id: 543 ↛ 544
    logger.debug("No mailhcimp_recurring_contributor_segment_id on RP %s, returning None", self.id)
    return None
    

2) Don't see */apps.py in coverage report and I don't understand how https://github.com/newsrevenuehub/rev-engine/commit/736666842550e322d57d38b009aad490a8fc1def is related.

2023-05-22 17:10 UTC, njharman commented on apps/organizations/apps.py
> +        import apps.organizations.signals  # noqa
I still don't see */apps.py in coverage report and I don't understand how 7366668 is related.

2023-05-22 17:10 UTC, njharman commented on apps/organizations/models.py
> +            return None
This is still uncovered

(https://github.com/newsrevenuehub/rev-engine/pull/1106/files#t543)

```
if not self.mailchimp_recurring_contributor_segment_id: 543 ↛ 544

    logger.debug("No mailhcimp_recurring_contributor_segment_id on RP %s, returning None", self.id) 

    return None
```

2023-05-22 20:01 UTC, benjaminEwhite commented on apps/organizations/apps.py
> +        import apps.organizations.signals  # noqa
Looks like I got some bad SO advice on how to test for signal registration. 

In that case, I don't see an obvious way to test this. Open to suggestions about how to test, but feels pretty low value (especially given this is an already established pattern in this repo).

2023-05-22 20:15 UTC, benjaminEwhite commented on apps/organizations/apps.py
> +        import apps.organizations.signals  # noqa
a353ae331 (left code comment)

2023-05-22 20:18 UTC, benjaminEwhite commented on apps/organizations/models.py
> +            return None
Bad copy pasta. Fixed in 1c4da4d8e

2023-05-23 21:08 UTC, njharman approved these changes
Approved with caveat that following lines be deleted from .coveragerc.  

I see no reason that */apps.py is skipped, they all are 100% covered. 

I don't see any files matching */template*/*.py

```
--- a/.coveragerc
+++ b/.coveragerc
@@ -6,9 +6,7 @@ omit =
     */tests/*
     */migrations/*
     */settings/*.py
-    */template*/*.py
     */wsgi.py
-    */apps.py
 branch = True
```

2023-05-23 21:52 UTC, x110dc requested changes

2023-05-23 21:52 UTC, x110dc commented on apps/organizations/signals.py
> +        logger.info("Enqueing task to setup mailchimp entities for revenue program mailing list for RP %s", instance.id)
Spelling: enqueuing

2023-05-23 21:52 UTC, x110dc commented on apps/organizations/signals.py
> +            "Not enqueing task to setup mailchimp entities for revenue program mailing list for RP %s", instance.id
Spelling: enqueuing

2023-05-23 21:52 UTC, x110dc commented on apps/organizations/tasks.py
> +    chord(header, publish_revenue_program_mailchimp_list_configuration_complete.si(rp_id)).delay()
I've wanted to, but haven't used chords like this. What's the retry behavior? If one of the sub-tasks fails what happens? Can we define a number of retries? I can see hitting rate limits or something else that would allow some tasks to complete while others fail.

2023-05-23 21:52 UTC, x110dc commented on pyproject.toml
> +django-celery-results = "^2.5.0"
Was this required in order to use chords? Or something else?

2023-05-23 21:52 UTC, x110dc commented on pyproject.toml
> +pytest-celery = "^0.0.0"
"^0"

2023-05-23 21:52 UTC, x110dc commented on revengine/settings/base.py
> +CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "django-db")
Why use the database as the result backend?

2023-05-23 21:52 UTC, x110dc commented on revengine/settings/base.py
> +CELERY_RESULT_EXTENDED = True
Since there's significant changes to the celery configuration here can we make a note during QA to test the other processes that use celery tasks? Sending email, etc.

2023-05-23 21:53 UTC, x110dc requested changes
I had a few comments, changes and questions.

2023-05-23 21:53 UTC, x110dc requested changes
I had a few comments, changes and questions.

2023-05-24 14:04 UTC, benjaminEwhite commented on pyproject.toml
> +pytest-celery = "^0.0.0"
869577b72344

2023-05-24 14:14 UTC, benjaminEwhite commented on revengine/settings/base.py
> +CELERY_RESULT_EXTENDED = True
Added note in AC for ticket and made comment tagging Agustín 

https://news-revenue-hub.atlassian.net/browse/DEV-3303?focusedCommentId=81553

2023-05-25 19:11 UTC, benjaminEwhite commented on revengine/settings/base.py
> +CELERY_RESULT_EXTENDED = True
Based on substantive refactor in 5348637e9abb, this comment is no longer relevant.

2023-05-25 19:11 UTC, benjaminEwhite commented on revengine/settings/base.py
> +CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "django-db")
FYI, based on refactor in 5348637e9abb, this conversation thread is no longer relevant.

2023-05-25 19:12 UTC, benjaminEwhite commented on pyproject.toml
> +django-celery-results = "^2.5.0"
This dependency was removed in 5348637e9abb

2023-05-25 19:26 UTC, benjaminEwhite commented on apps/organizations/tasks.py
> +    chord(header, publish_revenue_program_mailchimp_list_configuration_complete.si(rp_id)).delay()
This question turned out to be a good one, that led me to pretty substantially refactor in 5348637e9abb -- enough that I'm going to have to revisit the PR description.

In trying to test retry `setup_mailchimp_entities_for_rp_mailing_list` I ran into several hurdles. The final straw was like this: I created a test that was meant to mock `ensure_mailchimp_store` such that on first call, it would raise a `MailchimpRateLimitError` and on second call, it would succeed. 

I discovered that while the mock was applied on first call, on retry, the original implementation of `ensure_mailchimp_store` was used. Google searches were fruitless, but eventually a convo with Chat-GPT revealed that it's not possible to mock behaviors in retried Celery tasks, as they run in an entirely new context with no reference to mocks etc.

Given that Celery chords/groups/chains have a reputation for complexity/buginess,  and given that it would not be possible to test the retry behavior, I decided to flatten the async/task side of things and move most of the logic to idempotent model methods (while retaining retry behavior around   MailchimpRateLimitError).

2023-05-26 00:02 UTC, x110dc approved these changes
LGTM. I think there could be other retryable errors besides a 429 (50x, for example). So may want to add that but we can wait and see and address that separately.

2023-05-26 11:24 UTC, merged