Dev 2202 contributor portal is not styled unless default donation page is designated update contributor portal to use r ps default style if it exists and if parent org is on plus plan
newsrevenuehub/rev-engine pull request #1115
Opened 2023-05-04 14:50 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
- Updates Contributor Portal do only display custom style if user Organization belongs to CORE or PLUS, and RP has a default donation page 
- Fix bugs with: not showing custom font on header,  showing "RevEngine" as portal name instead of the correct one
- Transcribe some JS files to TS
- Create test for ContributorRouter

#### Why are we doing this? How does it help us?
- Make the logic consistent across the entire app for when custom style is shown to contributors. (Email styling was done in DEV-2999, contributor portal was done now)

#### How should this be manually tested? Please include detailed step-by-step instructions.
Access Contributor portal in the following scenarios:
(In all scenarios, the headline should always show the correct Portal name, and not "RevEngine" portal)
1. Org = CORE, default donation page set -> show **custom** styling in portal
2. Org = PLUS, default donation page set -> show **custom** styling in portal 
3. Org = FREE, default donation page set -> show **default** styling in portal
4. Org = CORE, default donation page **not** set -> show **default** styling in portal
5. Org = PLUS, default donation page **not** set -> show **default** styling in portal 
6. Org = FREE, default donation page **not** set -> show **default** styling in portal

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
No new changes, just updated the logic for when custom styles appears.

#### Have automated unit tests been added? If not, why?
yes

#### How should this change be communicated to end users?
n/a

#### Are there any smells or added technical debt to note?
Input inside `ContributorEntry.tsx` can be updated from the legacy input to `TextField` (but the style isn't consistent, so I didn't make this change for this PR).

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-2202

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2023-05-04 17:51 UTC, nrh-cklimas requested changes

2023-05-04 17:51 UTC, nrh-cklimas commented on spa/src/components/ContributorRouter.test.tsx
> +  });
I know what I'm suggesting is longer than what you have, but it avoids some eslint warnings and I think it's better to be explicit about the behavior you're expecting (e.g. the free plan not getting custom styles) up top instead of putting it in a conditional inside the test.

```suggestion
  describe.each([
    ['CORE', { shouldUsePageStyle: true }],
    ['FREE', { shouldUsePageStyle: false }],
    ['PLUS', { shouldUsePageStyle: true }]
  ])('For the %s plan', (plan, { shouldUsePageStyle }) => {
    const mockDonationPage = { id: 'mock-id' };
    const mockCustomData = {
      styles: {
        font: 'mock-font'
      },
      revenue_program: {
        default_donation_page: mockDonationPage,
        organization: {
          plan: {
            name: plan
          }
        }
      }
    };
    const mockCustomDataWithoutPage = {
      ...mockCustomData,
      revenue_program: { ...mockCustomData.revenue_program, default_donation_page: undefined }
    };

    if (shouldUsePageStyle) {
      it("uses the RP's default page's style if it exists", () => {
        useRequestMock.mockReturnValue((_: any, { onSuccess }: { onSuccess: ({ data }: { data: any }) => void }) =>
          onSuccess({ data: mockCustomData })
        );
        tree();
        expect(screen.getByTestId('page-data')).toHaveTextContent(JSON.stringify(mockCustomData));
      });
    } else {
      it('uses the default page style even if the RP has a default page', () => {
        useRequestMock.mockReturnValue((_: any, { onSuccess }: { onSuccess: ({ data }: { data: any }) => void }) =>
          onSuccess({ data: mockCustomData })
        );
        tree();
        expect(screen.getByTestId('page-data')).toHaveTextContent('false');
      });
    }

    it('uses the default page style if the RP has no default page', () => {
      useRequestMock.mockReturnValue((_: any, { onSuccess }: { onSuccess: ({ data }: { data: any }) => void }) =>
        onSuccess({ data: mockCustomDataWithoutPage })
      );
      tree();
      expect(screen.getByTestId('page-data')).toHaveTextContent('false');
    });

    it('uses the default page style if the RP has no default page', () => {
      useRequestMock.mockImplementation(
        () =>
          (_: any, { onSuccess }: { onSuccess: ({ data }: { data: any }) => void }) =>
            onSuccess({ data: mockCustomDataWithoutPage })
      );
      tree();
      expect(screen.getByTestId('page-data')).toHaveTextContent('false');
    });
  });
```

2023-05-04 17:51 UTC, nrh-cklimas commented on spa/src/components/ContributorRouter.test.tsx
> +    it('calls with page style', () => {
```suggestion
    it('calls with page style once loaded', () => {
```
Not sure the description I'm suggesting is accurate, though.

2023-05-04 17:51 UTC, nrh-cklimas commented on spa/src/components/ContributorRouter.test.tsx
> +    it('calls with undefined', () => {
```suggestion
    it('calls with undefined while the page is loading', () => {
```
Is this an accurate description?

2023-05-04 17:51 UTC, nrh-cklimas commented on spa/src/components/ContributorRouter.test.tsx
It's awesome to have testing on this component--it's kind of a beast. Could you add tests for what happens when loading the page fails, though? I would aim to just describe the behavior as it is unless it does something really egregious (e.g. if it shows an error message or throws an error, that's fine to test, that doesn't need to be changed).

2023-05-05 11:42 UTC, GuiMend commented on spa/src/components/ContributorRouter.tsx
> +import { PageType } from 'constants/propTypes';
Sure! I forgot the name and couldn't find the existing Type, so I created a new one. Will update!

2023-05-05 12:05 UTC, GuiMend commented on spa/src/components/ContributorRouter.test.tsx
> +  it('renders nothing when: subdomain is not set + no page data + fetchedPageData = false', () => {
Correct

2023-05-05 16:16 UTC, GuiMend commented on spa/src/components/ContributorRouter.test.tsx
> +    it('calls with page style', () => {
Fixed it

2023-05-05 18:14 UTC, nrh-cklimas commented on spa/src/hooks/useContributionPage/useContributionPage.types.ts
> +  organization: Organization | number;
Not sure about this... in what circumstances would it be a number? I looked at the review app on the page editor and a live page and I think it's no longer a number in those responses.

2023-05-05 18:15 UTC, nrh-cklimas commented on spa/src/components/ContributorRouter.test.tsx
> +jest.mock('hooks/useRequest');
I don't feel strongly on this one. Eventually we'll get rid of useRequest anyway.

2023-05-05 20:54 UTC, GuiMend commented on spa/src/hooks/useContributionPage/useContributionPage.types.ts
> +  organization: Organization | number;
The BE serializer that I added the `"organization = Organization JSON object"` didn't have an "organization" field beforehand, so it shouldn't have affected anywhere we currently use RevenueProgram.

We do have some other RP serializers that return "organization = Org ID" (and those instances are still in use). That's why I opted to type this `Organization | number` so that the new use case is covered, but we don't lose any existing cases where number is still expected.

2023-05-09 15:20 UTC, benjaminEwhite commented on apps/organizations/serializers.py
> +    # We need organization.plan
This is minor, but not sure how helpful this comment is, and likely to go stale. Think can just remove.

2023-05-09 19:12 UTC, benjaminEwhite requested changes
Overall looks good. Two small comments.

2023-05-10 18:57 UTC, GuiMend commented on apps/pages/views.py
> +            # The serializer returns rp.default_donation_page, so we can check on the Frontend if the donation page is the default page or not
self.donation_page is going to be serialized by `DonationPageListSerializer` that uses `RevenueProgramListInlineSerializer`, which returns the `"default_donation_page"` field, which is going to be undefined if default_donation_page is not set, or it will return the default_donation_page id.

Here we do the check: `ContributorRouter.tsx`, line 45.
```js
const hasDefaultDonationPage = !!pageData?.revenue_program?.default_donation_page;
```

2023-05-10 19:09 UTC, benjaminEwhite approved these changes

2023-05-12 18:00 UTC, merged