DEV-3519: add header bar to email receipts
newsrevenuehub/rev-engine pull request #1118
Opened 2023-05-05 15:43 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

- Syncs up header bar in contribution receipts with the appearance on recurring contribution reminders (https://github.com/newsrevenuehub/rev-engine/pull/1111).
- Adds debug URL for contribution receipts.

#### Why are we doing this? How does it help us?

- Fixes appearance for logos that are meant for a dark background.
- Makes email dev work easier.

#### How should this be manually tested? Please include detailed step-by-step instructions.

To test styled emails for regressions:

1. Make a contribution to an org whose default page has a style set.
2. Confirm the receipt email appearance is correct (header color and logo are correct, appear above text header) and contains accurate info.
3. Make a contribution to an org whose default page has a style set, but no header logo.
4. Confirm the receipt email appearance is correct (has left-aligned NRE logo at top, no background color in header) and contains accurate info.

To test unstyled emails for regressions:

1. Make a contribution to an org whose default page doesn't have a style set.
2. Confirm the receipt email appearance is correct (has left-aligned NRE logo at top) and contains accurate info.

To test free plan emails for regressions:

1. Make a contribution to an org whose default page has a style set, but whose org is on the free plan.
2. Confirm the receipt email appearance is correct (does not use custom style, has left-aligned NRE logo at top) and contains accurate info.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No.

#### Have automated unit tests been added? If not, why?

Updated existing tests.

#### How should this change be communicated to end users?

n/a

#### Are there any smells or added technical debt to note?

No.

#### Has this been documented? If so, where?

Updated the readme.

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-3519

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No.

2023-05-05 20:45 UTC, GuiMend requested changes
Need a fix in the python tests

2023-05-05 20:45 UTC, GuiMend commented on apps/emails/tests/test_tasks.py
> +        custom_button_background = "header-background: #mock-button-color !important"
@nrh-cklimas this change doesn't make sense. `background` is the css atribute, so `header-background` isn't a valid test option. 

I believe what you want to do is this:
![image](https://user-images.githubusercontent.com/9381325/236565290-a2f611d8-ef9a-4688-bd58-189be6bf91c5.png)

The tests aren't failing with this update because we are actually testing that those custom colors aren't being applied to the email (which is True as they don't exist)

2023-05-05 21:02 UTC, nrh-cklimas commented on apps/emails/tests/test_tasks.py
> +        custom_button_background = "header-background: #mock-button-color !important"
@GuiMend yikes--that makes sense. My brain read `background` as a class name which of course it's not. Thanks for the suggested fix. Only thing I noticed is, it doesn't seem like `style.save()` is needed on line 136? The tests pass without it but I'm wondering if there's more to it that I'm not understanding.

2023-05-05 21:16 UTC, GuiMend commented on apps/emails/tests/test_tasks.py
> +        custom_button_background = "header-background: #mock-button-color !important"
It's not needed for this test, but I've added it for "context consistency" (not sure it's named this way).

If we don't save the `style` there, the custom style set in the lines previous are only accessible in this current context. So if we in the future modify the email send function and it happens to get the data from another context instead of getting it passed in as props in line `143` we don't get any weird error because we didn't save the style.

I faced this issue in a another PR I worked on and it was really difficult to find this issue (at least for someone without a lot of BE experience).

2023-05-08 13:32 UTC, nrh-cklimas commented on apps/emails/tests/test_tasks.py
> +        custom_button_background = "header-background: #mock-button-color !important"
Thanks for the explanation! Updated in 51c947cfce0450f042c609e1b1edcedacec260df

2023-05-08 14:05 UTC, GuiMend approved these changes
👍

2023-05-08 14:05 UTC, GuiMend commented on apps/emails/tests/test_tasks.py
>              # Email template doesn't have a button to apply the custom button color to and also doesn't have a header background to customize
@nrh-cklimas could you also update the comment?
```suggestion
            # Email template doesn't have a button to apply the custom button color to
```

2023-05-08 14:10 UTC, nrh-cklimas commented on apps/emails/tests/test_tasks.py
>              # Email template doesn't have a button to apply the custom button color to and also doesn't have a header background to customize
316ea5c1f1de1e273fa01f9b4a5a06cb977c91e1

2023-05-08 17:25 UTC, merged