DEV-3279: update connected mailchimp modal copy
newsrevenuehub/rev-engine pull request #1137
Opened 2023-06-01 13:42 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
Updates copy for connected mailchimp modal.

#### Why are we doing this? How does it help us?
Updates copy for connected mailchimp modal.

#### How should this be manually tested? Please include detailed step-by-step instructions.
Check storybook `Common/IntegrationCard/MailchimpModal/PaidPlanWithMailchimpConnected`

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
yes

#### Have automated unit tests been added? If not, why?
yes

#### How should this change be communicated to end users?
n/a

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3279

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
Mailchimp epic:
https://news-revenue-hub.atlassian.net/browse/DEV-3275

2023-06-01 14:29 UTC, nrh-cklimas approved these changes

2023-06-06 14:34 UTC, nrh-cklimas commented on spa/src/components/common/IconList/IconList.tsx
> +  console.log({ list, iconSize });
Stray `console.log`

2023-06-06 14:40 UTC, nrh-cklimas requested changes
Two small tweaks.

2023-06-06 21:20 UTC, nrh-cklimas approved these changes

2023-06-14 18:17 UTC, nrh-cklimas requested changes

2023-06-14 18:17 UTC, nrh-cklimas commented on spa/src/hooks/useConnectMailchimp.test.tsx
> +      it('shows a connection success notification if audience selection patch succeeds', async () => {
Let's add a test for it not showing a success notification if the request fails, conversely. I would do a `await Promise.resolve()` to let any pending async tasks complete, then expect that `enqueueSnackbar` isn't called.

2023-06-16 13:28 UTC, nrh-cklimas approved these changes

2023-06-20 17:33 UTC, GuiMend commented on spa/src/components/common/IntegrationCard/MailchimpIntegrationCard/MailchimpModal/MailchimpModal.test.tsx
> +          expect(enqueueSnackbar).toBeCalledTimes(2);
Correct, but isn't perhaps the objective of the test to know exactly how many buttons there are?
Say for example we delete one of the close buttons, we should warn the user that a test has failed and either you update the test, or undo the mistake deletion.

2023-06-21 14:25 UTC, GuiMend commented on spa/src/hooks/useConnectMailchimp.types.ts
> +  recentlyConnectedToMailchimp: boolean;
I like the suggestion.
It's going to be true not for 1 render, but for only 1 api call to `mailchimp_configure`. When the `mailchimp_integration_connected` flag changes from false to true it will return `true`. In the following refresh, `mailchimp_configure` will go from `true` to `true` so this will return `false`.

2023-06-21 14:25 UTC, GuiMend commented on spa/src/hooks/useConnectMailchimp.test.tsx
> +        // When the second request finishes, the notification should fire.
Thanks for catching that. I copy/pasted and forgot to remove this part.

2023-06-21 14:31 UTC, GuiMend commented on spa/src/components/common/IntegrationCard/MailchimpIntegrationCard/MailchimpModal/MailchimpModal.test.tsx
> +        const setup = () => {
Can't: 
<img width="640" alt="image" src="https://github.com/newsrevenuehub/rev-engine/assets/9381325/7db36399-ff97-4d25-b44d-a6a3cc6e01a5">

2023-06-21 14:51 UTC, nrh-cklimas commented on spa/src/components/common/IntegrationCard/MailchimpIntegrationCard/MailchimpModal/MailchimpModal.test.tsx
> +          expect(enqueueSnackbar).toBeCalledTimes(2);
If that's something we should test, that to me is separate from testing `should show successful connection notification on any "Close" click`, the current test description.

```tsx
it('has two close buttons', () => {
  setup();
  expect(screen.getAllByRole('button', { name: 'Close' }).length).toBe(2);
});
```

2023-06-23 15:33 UTC, nrh-cklimas commented on poetry.lock
Any idea why this is in the diff now?

2023-06-23 15:38 UTC, nrh-cklimas commented on spa/src/hooks/useConnectMailchimp.tsx
> +    () => !!mailchimpData?.mailchimp_list_id && !prevMailchimpAudienceId,
Let's be explicit here since `mailchimp_list_id` is no longer a boolean.

```suggestion
    () => (typeof mailChimpData?.mailchimp_list_id === 'number' && prevMailchimpAudienceId === null),
```

2023-06-23 15:39 UTC, nrh-cklimas requested changes
Two suggestions here.

2023-06-23 15:52 UTC, nrh-cklimas commented on spa/src/hooks/useConnectMailchimp.tsx
> +    () => !!mailchimpData?.mailchimp_list_id && !prevMailchimpAudienceId,
(or 'string', probably)

2023-06-23 17:31 UTC, GuiMend commented on poetry.lock
<img width="649" alt="image" src="https://github.com/newsrevenuehub/rev-engine/assets/9381325/4afae344-f5d1-4134-ae5d-12fbbae5bfa5">

2023-06-23 17:48 UTC, nrh-cklimas approved these changes

2023-06-26 13:10 UTC, merged