DEV-3394  Automate default donation page designation when plan is on core
newsrevenuehub/rev-engine pull request #1143
Opened 2023-06-09 17:47 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

Registers a post-save signal receiver function called `handle_set_default_donation_page` with `Organization` as sender.

Under well-defined conditions, this signal handler will set a default donation page on one of the org's revenue programs. Specifically, if the org is on core plan, and there is no default donation page for the relevant RP, then the handler attempts to set an existing page controlled by the RP as the default donation page.

Note that this a post-save handler, and does not differentiate between if the value being set is `org.plan_name`. This handler will fire any time an org is being saved and it has a core plan, but no default donation page.  The expected way an org will get in this state is when a user upgrades via the SPA.

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-06-12 17:24 UTC, njharman approved these changes
Lgtm. Only a couple "opinions" ;) re structure.

+1 the handler function renames, info -> debug logging changes.

2023-06-12 17:24 UTC, njharman commented on apps/organizations/signals.py
> +            "plan_name" in update_fields,
Don't believe (this) update_fields used below. Simplier, less local name pollution as 

`"plan_name" in (kwargs.get("update_fields", None) or {})`

2023-06-12 17:24 UTC, njharman commented on apps/organizations/signals.py
> +    if rp.default_donation_page:
Minor/meh.  I'd put rp default page check above update/create after the related does rp exist check

2023-06-13 13:43 UTC, benjaminEwhite commented on apps/organizations/signals.py
> +            "plan_name" in update_fields,
a3bab546f7

2023-06-15 20:18 UTC, x110dc requested changes
LGTM. I just had one request that we make sure we document how we select the default page/RP for the support team's use.

2023-06-15 20:18 UTC, x110dc commented on apps/organizations/signals.py
> +    logger.debug("get_page_to_be_set_as_default called on rp %s", rp.id)
May want to document a text description of how we pick the default page. And in the PR description under documentation we'll want to note this in case there are questions the support team gets.

2023-06-16 03:09 UTC, benjaminEwhite commented on apps/organizations/signals.py
> +    logger.debug("get_page_to_be_set_as_default called on rp %s", rp.id)
Attaching a first pass documenting default donation pages, but in Jira.

2023-06-16 18:03 UTC, x110dc approved these changes

2023-06-16 19:30 UTC, merged