DEV-3560: Magic link is sent to emails that have never made a contribution
newsrevenuehub/rev-engine pull request #1153
Opened 2023-06-22 15:30 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a 
#### What's this PR do?
- Validates that contributor exists before sending magic link email
- Update send email logic & tests

#### Why are we doing this? How does it help us?
Avoid spamming.  

#### How should this be manually tested? Please include detailed step-by-step instructions.
- Go to a contributor portal
- Request a magic link for a valid email that has made a contribution (request should succed)
- Request a magic link for a valid email, but one that hasn't done any contributions (request should fail)

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
no

#### Have automated unit tests been added? If not, why?
yes

#### How should this change be communicated to end users?
n/a

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3560

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2023-06-29 03:33 UTC, njharman requested changes

2023-06-29 12:31 UTC, GuiMend commented on apps/api/views.py
> +        contributor = get_object_or_404(Contributor, email=request.data["email"])
I don't think we have a way of validating that the email actually belongs to the person typing it at this point. 
The `/contributor/` url doesn't have any previous login or any cookies in the browser that we can use to make that verification.

2023-06-29 12:35 UTC, GuiMend commented on apps/api/tests/test_views.py
> -        # We don't want to indicate in any way whether or not an email is in the system.
> This is security concern (not allowing 3rd parties to "fish" for valid emails).
Yes, but the request for this ticket is to validate that the email belongs to a contributor before sending the magic link to avoid spamming.

> fails when contributorA uses contributorB's email
I went into more details above, but I don't think that is possible.

> Also, if contributor typos or enters wrong email, proly should provide better UI than just generic 404.
Correct, but at the same time, this generic message helps to avoid the email fishing

The only thing that `ContributorObtainTokenSerializer` does is validate that we have all the necessary fields to complete the request (email, subdomain) and refreshes the token.

2023-07-03 18:50 UTC, njharman requested changes
The build failed due to failing tests.

The view should return 200, whether email sent or not. see PR comment.

2023-07-03 18:50 UTC, njharman commented on apps/api/tests/test_views.py
> -        # We don't want to indicate in any way whether or not an email is in the system.
[Ok, I now understand my previous confusion. Since this was cut and changed to return differing responses, I had thought that the POST was from an authenticated contributor]

If indeed any random person can submit request with arbitrary email it is a security concern that same, neutral response always be returned. Regardless of whether email sent or not.  Also, the time of response should be identical as possible (using celery async task to send email handles that sufficiently).

The concern is malicious actor could submit emails to discover who our contributors or, find valid emails for spamming, etc.

1. The test should revert back to validating 200 is always returned.
2. The no contributor created is correct.
3. I did not look deeply, but wrapping get_object_or_404() in try except or using get_object() should then pass test.

2023-07-03 20:05 UTC, GuiMend commented
Ticket got suspended: https://news-revenue-hub.atlassian.net/browse/DEV-3560?focusedCommentId=84299

2023-07-03 20:05 UTC, closed without merging