DEV-3687-add-default-page-indicator-to-page-editor
newsrevenuehub/rev-engine pull request #1164
Opened 2023-07-05 15:29 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
Adds a bookmark icon to page title editor to indicate it's the default contribution page
#### Why are we doing this? How does it help us?
Indicates for the user that they are editing the default page.

#### How should this be manually tested? Please include detailed step-by-step instructions.
- Check the edit page of a default page, make sure bookmark icon appears in the "edit page name" section on the top of the screen
- Check a non default and make sure no bookmark icon shows.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
yes

#### Have automated unit tests been added? If not, why?
yes

#### How should this change be communicated to end users?
Default page indicator now shows in edit screen

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3687
#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2023-07-06 17:39 UTC, nrh-cklimas requested changes

2023-07-06 17:39 UTC, nrh-cklimas commented on spa/src/components/base/Radio/Radio.tsx
> +      checkedIcon={props.disabled ? <CheckedIconDisabled aria-hidden /> : <CheckedIcon aria-hidden />}
Sorry, I didn't realize my suggestion would mean these changes would be needed across the app... I did some more research and evidently the [ARIA role for inline SVGs is 'graphics-document', not 'img'](https://www.unimelb.edu.au/accessibility/techniques/accessible-svgs#:~:text=SVG%20Roles,%3D%22graphics%2Dsymbol%22.). I tried locally changing the svgr mock to this and it looked like all tests passed without having to stick aria-hidden on these elements.

```tsx
export const ReactComponent = (props) => <icon-mock {...props} role="graphics-document" />;
```

2023-07-06 17:39 UTC, nrh-cklimas commented on spa/src/components/pageEditor/PageName/PageName.styled.ts
> +export const ListItemIcon = styled(MuiListItemIcon)`
Could you talk through why you went with a ListItemIcon here? Typically I've seen them only used inside a ListItem component--not sure if this buys us much that using a plain `span` wouldn't give us, for example.

2023-07-06 17:39 UTC, nrh-cklimas commented on spa/src/components/pageEditor/PageName/PageName.tsx
> +
I think this can be simplfied but I might be missing a nuance. A page should always have a `revenue_program`, and the `revenue_program`'s default page might be `null`, but that's OK since the page ID will never be `null`.

```suggestion
  const defaultDonationPage =
    updatedPagePreview && updatedPagePreview.id === updatedPagePreview.revenue_program.default_donation_page;

```

2023-07-07 12:52 UTC, GuiMend commented on spa/src/components/pageEditor/PageName/PageName.styled.ts
> +export const ListItemIcon = styled(MuiListItemIcon)`
That was a mistake, did a copy/paste from another place of the app. Thanks for catching that

2023-07-11 21:06 UTC, nrh-cklimas commented on spa/src/components/pageEditor/PageName/PageName.tsx
> +  console.log({ defaultDonationPage, updatedPagePreview });
Leftover console.log

2023-07-12 14:58 UTC, nrh-cklimas approved these changes

2023-07-12 19:11 UTC, merged