Dev 3741 refactor management command to accommodate creation of two separate webhook endpoints and accounts
newsrevenuehub/rev-engine pull request #1174
Opened 2023-07-14 18:23 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-07-15 13:45 UTC, benjaminEwhite commented
Tearing down and rebuilding to trigger new review app and test that Hookdeck webhook creation works as expected.

2023-07-17 13:26 UTC, benjaminEwhite commented
Closing and reopening to trigger rebuild.

2023-07-18 21:57 UTC, njharman requested changes
see comments

2023-07-18 21:57 UTC, njharman commented on .envrc.example
> +export STRIPE_WEBHOOK_SECRET_FOR_CONTRIBUTIONS=whsec_???
This does not match PR text.  CONRIBUTORS vs CONTRIBUTIONS
and I don't see that STRIPE_WEBHOOK_EVENTS has been renamed

> Churns some var names in settings.base..py
> STRIPE_WEBHOOK_SECRET becomes STRIPE_WEBHOOK_SECRET_FOR_CONTRIBUTORS
> STRIPE_WEBHOOK_EVENTS becomes STRIPE_WEBHOOK_EVENTS_FOR_CONTRIBUTIONS

2023-07-18 21:57 UTC, njharman commented on .envrc.example
> +export STRIPE_WEBHOOK_SECRET_FOR_CONTRIBUTIONS=whsec_???
Although it does seem correct later in "what changes for deployment"

> Rename STRIPE_WEBHOOK_SECRET to STRIPE_WEBHOOK_SECRET_FOR_CONTRIBUTIONS

2023-07-18 21:57 UTC, njharman commented on apps/organizations/tests/test_models.py
> +            api_key=settings.STRIPE_LIVE_SECRET_KEY_CONTRIBUTIONS,
Believe on line 495 a STRIPE_LIVE_SECRET... rename was missed.

2023-07-18 21:57 UTC, njharman commented on apps/contributions/tests/test_views.py
> +        response = client.post(reverse("stripe-webhooks-contributions"), payment_method_attached_request_data, **header)
[nothing to do with this line. not sure how to comment on lines not changed]

Believe few STRIPE_TEST_SECRET_KEY  renamed missed, lines 745, 884, 940

2023-07-18 21:57 UTC, njharman commented on apps/organizations/views.py
> +        """Initially we'll just return 200 without doing anything, ahead of full implementation"""
If there is already ticket for full implementation, should reference it. If not, then gtg.

2023-07-19 13:10 UTC, benjaminEwhite commented on .envrc.example
> +export STRIPE_WEBHOOK_SECRET_FOR_CONTRIBUTIONS=whsec_???
Fixed in PR description. It is now:

> Churns some var names in settings.base..py
> STRIPE_WEBHOOK_SECRET becomes STRIPE_WEBHOOK_SECRET_FOR_CONTRIBUTIONS
> STRIPE_LIVE_SECRET_KEY  becomes STRIPE_LIVE_SECRET_KEY_CONTRIBUTIONS 
> STRIPE_TEST_SECRET_KEY becomes STRIPE_TEST_SECRET_KEY_CONTRIBUTIONS

2023-07-19 13:13 UTC, benjaminEwhite commented on apps/contributions/tests/test_views.py
> +        response = client.post(reverse("stripe-webhooks-contributions"), payment_method_attached_request_data, **header)
b382f661496ecb5a5afb718f7a05c6374a826f56

2023-07-19 13:15 UTC, benjaminEwhite commented on apps/organizations/tests/test_models.py
> +            api_key=settings.STRIPE_LIVE_SECRET_KEY_CONTRIBUTIONS,
65926a82adf

2023-07-19 13:15 UTC, benjaminEwhite commented on apps/organizations/tests/test_models.py
> +            api_key=settings.STRIPE_LIVE_SECRET_KEY_CONTRIBUTIONS,
65926a82adf

2023-07-19 13:17 UTC, benjaminEwhite commented on apps/organizations/views.py
> +        """Initially we'll just return 200 without doing anything, ahead of full implementation"""
6472acf06

2023-07-25 22:11 UTC, x110dc approved these changes
LGTM.

2023-07-26 03:43 UTC, merged