DEV-3748 | Implement organization stripe webhook receiver endpoint
newsrevenuehub/rev-engine pull request #1177
Opened 2023-07-18 13:01 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

This is PR 3 of 5 stacked PRs to fully implement server-side support for self-upgrade webhook events.

1. #1174
2. #1178
3. #1177 (this PR)
4. #1185 
5. #1176 

**NOTE** In short term, this PR  has `DEV-3746` as its base, but that branch is itself going to be merged into DEV-1750, which is the intended  base for this PR.  Once #1178  has been merged, DEV-1750 should be merged in here, and base should be DEV-1750.

#### What's this PR do?

This PR implements the business logic for self-upgrades in an API endpoint that is designed to receive POST requests made by Stripe webhook events.

The specific endpoint is `/api/v1/organizations/handle_stripe_webhook`. The happy path flow for this endpoint is:

1. Construct a Stripe event object from the request data (which by default includes header validation)
2. The event will include a "client_reference_id". We try to find an org whose `uuid` value (a net new field on the model) is the same as "client_reference_id".
3. We then set that org's stripe subscription ID (a net new field on the model) to the Stripe subscription ID in request data.
4. We set org's plan name to CorePlan.name.
6. We save the org creating a reversion revision and using update fields.

Some important implementation details:

- We rename some env vars:
  + STRIPE_WEBHOOK_SECRET_FOR_CONTRIBUTIONS => STRIPE_WEBHOOK_SECRET_CONTRIBUTIONS
  + STRIPE_WEBHOOK_SECRET_FOR_UPGRADES => STRIPE_WEBHOOK_SECRET_UPGRADES
  + HOOKDECK_WEBHOOK_SOURCE => HOOKDECK_STRIPE_WEBHOOK_SOURCE_CONTRIBUTIONS
- We add some env vars:
  + STRIPE_CORE_PRODUCT_ID
  + HOOKDECK_STRIPE_WEBHOOK_SOURCE_UPGRADES
- In an earlier ticket for Hookdeck refactoring (DEV-3741), we didn't know we needed a requirement around having distinct Hookdeck sources, but that need became apparent in trying to do e2e testing on full user flow. In this ticket, we refactor `bootstrap_endpoint` such that it gets passed a `source_id` parameter.
- The call signature for the `create_stripe_webhooks` command changes to use optional args instead of positional
- Opportunistically rewrote `apps.contributions.tests.test_utils` to use pytest instead of unittest.
- Adds `uuid` and `stripe_subscription_id` new fields on Organization model. This includes a migration.
- Adds `Organization.stripe_subscription` property, which attempts to provide a Stripe subscription corresponding to `organization.stripe_subscription_id`, using either the test or live upgrades API key.
- Refactors `apps.organizations.tests.test_management` to be pytest only. There was a broken test and was minimal effort to upgrade.
- Creates two new class methods on `OrganizationViewSet` that are used in `OrganizationViewSet.handle_stripe_webhook`: `construct_stripe_event` and `handle_checkout_session_completed_event`.

#### Why are we doing this? How does it help us?

Incremental step in accomplishing epic around self-upgrades

#### How should this be manually tested? Please include detailed step-by-step instructions.

There is not a good way to manually test this (manual testing will be unlocked in #1185 ). In fact, we'll ultimately withhold QA for the first 4 of the 5 stacked PRs.

There is an attached Sentry issue in the JIRA ticket for this PR that contains evidence that the webhook as implemented in this PR fires and begins its work, before failing because it has been provided an org id for `client_reference_id` instead of UUID (which comes in #1185).

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

Yes

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

No

#### What are the relevant tickets? Add a link to any relevant ones.

- [DEV-3748](https://news-revenue-hub.atlassian.net/browse/DEV-3748)
- [DEV-1750](https://news-revenue-hub.atlassian.net/browse/DEV-1750)

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

We'll need to get values for `STRIPE_CORE_PRODUCT_ID` from Stripe for both test/review app envs and prod. This value will be in the `NRH (customer billing)` stripe account. The product ID can be found by going to Products => `RevEngine Core` (for prod) or `CorePlan` (for all other envs).  

- `STRIPE_CORE_PRODUCT_ID`
- `HOOKDECK_STRIPE_WEBHOOK_SOURCE_UPGRADES`

Some cleanup on settings names that requires renaming existing config vars:

- `STRIPE_WEBHOOK_SECRET_FOR_CONTRIBUTIONS` becomes `STRIPE_WEBHOOK_SECRET_CONTRIBUTIONS`
- `STRIPE_WEBHOOK_SECRET_FOR_UPGRADES` becomes `STRIPE_WEBHOOK_SECRET_UPGRADES`
- `HOOKDECK_STRIPE_WEBHOOK_SOURCE` becomes `HOOKDECK_STRIPE_WEBHOOK_SOURCE_CONTRIBUTIONS`

Doesn't require follow up, but also worth noting that there is a migration for this PR: apps/organizations/migrations/0021_3748_add_uuid_and_stripe_subscription_id.py

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

[DEV-3748]: https://news-revenue-hub.atlassian.net/browse/DEV-3748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-07-24 02:42 UTC, njharman requested changes
Looks good, couple inline comments, little uncovered code and ...

1. Assume AC3 Idempotent they really mean it won't jack up if creation attempted > once, which handled by AC2.b, and ignoring race conditions cause YNGNI
2. +1 > refactor to use pytest instead of unittest
3. code says HOOKDECK_STRIPE_WEBHOOK_SOURCE_CONTRIBUTIONS,  PR says HOOKDECK_WEBHOOK_SOURCE_CONTRIBUTIONS but is correct in were it counts (deployment changes)

2023-07-24 02:42 UTC, njharman commented on README.md
> -echo "export STRIPE_TEST_SECRET_KEY_CONTRIBUTIONS=sk_test_???" >> .envrc
STRIPE_TEST_SECRET_KEY_CONTRIBUTIONS exists / is used in several tests, contributions/utils.py

2023-07-24 02:42 UTC, njharman commented on apps/organizations/models.py
> +    @property
Isn't this making a api call to Stripe? Shouldn't this be cached? I thought we already had cache thing... @cached_property

2023-07-24 02:42 UTC, njharman commented on apps/organizations/views.py
> +            reversion.set_comment("`handle_checkout_session_completed_event` upgraded org to core")
Uncovered,  "happy path"?

2023-07-24 15:01 UTC, benjaminEwhite commented on README.md
> -echo "export STRIPE_TEST_SECRET_KEY_CONTRIBUTIONS=sk_test_???" >> .envrc
good catch. 

 15dae79258f4

2023-07-24 15:12 UTC, benjaminEwhite commented on apps/organizations/views.py
> +            reversion.set_comment("`handle_checkout_session_completed_event` upgraded org to core")
🤦 it's because i messed up naming the test in apps.organizations.tests.test_views. Had `handle_checkout_session_completed_event` and needed `test_handle_checkout_session_completed_event`

see 7c7a5dd51

2023-07-24 21:38 UTC, njharman approved these changes

2023-07-27 04:49 UTC, x110dc approved these changes

2023-07-27 04:54 UTC, merged