DEV-3746 | WIP - refactor stripe webhook creation
newsrevenuehub/rev-engine pull request #1178
Opened 2023-07-18 13:07 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-07-19 17:09 UTC, njharman approved these changes
Looks good, AC met AFAICT

PR text just confirming wasn't typo with two different CONSTANTS

> Add STRIPE_TEST_SECRET_KEY_UPGRADES env var (for both prod and in settings that get copied over in review apps once 1750 merged)
> After running the create_stripe_webhooks command in prod, you should add a value for STRIPE_WEBHOOK_SECRET_FOR_UPGRADES.

2023-07-26 04:06 UTC, x110dc approved these changes
LGTM

2023-07-26 04:06 UTC, x110dc requested changes
There's an unresolved question for you (from me) on this one.

2023-07-26 14:29 UTC, benjaminEwhite commented on revengine/settings/base.py
> +    "checkout.session.completed",
The `checkout.session.completed` event has a `client-reference-id` value that we control by virtue of configuring the pricing table. In DEV-3748, we add a `uuid` field to the organization model. We then set the client reference id in the Stripe pricing table in the SPA to the value of the org's UUID.

This provides what is hopefully a relatively clean and dependable way to link up an org's state with Stripe webhook events. 

In comparison, pairing a `customer.subscription.created/updated` with an org seems less clean and possibly more error prone. We'd end up having to do something like search for org by role assignment user emails, which seems kind of roundabout when we can cut straight to the chase setting `client-reference-id` in the pricing table.

When we bring in app, I think that's the moment to decide how to derive org's from initial `customer.subscription.created/updated` before which time the target org does not have a stripe subscription ID saved to it. It's true that we're guaranteed that we'll have to change later, but we get to kick the can down the road on some business logic that is not totally straight-forward, in favor of a quick clean interface in the short term that shouldn't paint us in any corners.

2023-07-26 18:27 UTC, benjaminEwhite commented on revengine/settings/base.py
> +    "checkout.session.completed",
@x110dc here's the relevant places in DEV-3748:

- https://github.com/newsrevenuehub/rev-engine/blob/95087240b433bcfa6c57f62281ac3925cad7c393/apps/organizations/models.py#L125-L128
- https://github.com/newsrevenuehub/rev-engine/blob/95087240b433bcfa6c57f62281ac3925cad7c393/apps/organizations/views.py#L123

2023-07-27 04:25 UTC, x110dc commented on revengine/settings/base.py
> +    "checkout.session.completed",
That's a great explanation and makes a lot of sense! I'd been wondering how we'd match up a payer if say, they paid with a different email address than what we have recorded for them. I guess this is one of the difficulties of reviewing stacked PRs in isolation.

2023-07-27 04:26 UTC, merged