DEV-3695-move-style-editing-into-page-editor-style-tab
newsrevenuehub/rev-engine pull request #1181
Opened 2023-07-18 16:27 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-07-18 20:37 UTC, nrh-cklimas commented on spa/src/hooks/useContributionPage/useContributionPage.tsx
> +  const updateStyleMutation = useMutation(
What are your thoughts on moving most of this new logic into a separate hook that useContributionPage would use in turn? We have `useStyleList` already and could move creation into that, similar to how creating a contribution page is done via `useContributionPageList`. To me, this would increase our flexibility so that when we do the full-fledged style editor changes later, we can re-use most of the work here instead of having to extract it from `useContributionPage`, and unit tests would be easier to work with.

2023-07-18 20:37 UTC, nrh-cklimas commented on spa/src/hooks/useContributionPage/useContributionPage.tsx
>      }
(I can't flag the deletePage line specifically)

Reading through this made me realize we have a need that wasn't captured in AC: when a page is deleted, then the style it owns needs to be deleted too if it exists. We can't rely on the backend to do it for us since there's no relationship in Django, I don't think.

2023-07-18 20:37 UTC, nrh-cklimas commented on spa/src/hooks/useStyleList.ts
> +  [x: string]: StyleStyles;
Confused by this type declaration. It seems to be saying that the interface can have any key.

2023-07-18 20:37 UTC, nrh-cklimas commented on spa/src/styles/DonationPageGlobalStyles.js
> +    font-size: ${(props) => props.theme.fontSizes[3]};
Will this impact existing contribution pages?

2023-07-19 16:55 UTC, GuiMend commented on spa/src/hooks/useContributionPage/useContributionPage.tsx
>      }
Correct, I just checked that Django sets the style page field as `null` so we would have to manually delete it.
```python
styles = models.ForeignKey("pages.Style", null=True, blank=True, on_delete=models.SET_NULL)
```

2023-07-19 16:56 UTC, GuiMend commented on spa/src/hooks/useStyleList.ts
> +  [x: string]: StyleStyles;
I added that for one reason that I can't remember anymore, but I removed it and no TS errors popped up.

2023-07-21 14:09 UTC, nrh-cklimas requested changes

2023-07-21 14:18 UTC, nrh-cklimas commented
Forgot to add, I think we can delete StylesChooser.js and StylesChooser.styled.js now.

2023-07-24 17:10 UTC, GuiMend commented on spa/src/styles/DonationPageGlobalStyles.js
> +    font-size: ${(props) => props.theme.fontSizes[3]};
Added notes to QA. Let's keep this comment unresolved for now @nrh-cklimas so that this PR is blocked from merging until we have a final answer on this topic (either remove the changes or approve them)

2023-07-24 20:21 UTC, GuiMend commented on spa/src/components/pageEditor/editInterface/pageStyles/StylesTab.tsx
> +            onChange={(e: any, value) => {
I updated 1 of the instances, didn't notice there were 3. Done now 👍

2023-07-24 20:26 UTC, GuiMend commented on spa/src/components/base/ColorPicker/__mocks__/ColorPicker.tsx
> +    <div data-testid="color-picker" data-label={label} data-value={value}>
Misread this one. Instead of putting inside the button, I added a label + input. Fixed it

2023-07-24 20:57 UTC, nrh-cklimas approved these changes

2023-08-03 14:34 UTC, GuiMend commented on spa/src/components/pageEditor/editInterface/pageStyles/StylesTab.tsx
> +import Select from 'elements/inputs/Select';
Created ticket https://news-revenue-hub.atlassian.net/browse/DEV-3812

2023-08-09 22:08 UTC, merged