add uuid to inline org serializer
newsrevenuehub/rev-engine pull request #1185
Opened 2023-07-20 19:57 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-07-20 20:57 UTC, nrh-cklimas approved these changes
TypeScript changes look good to me.

2023-07-24 21:50 UTC, njharman approved these changes

2023-07-27 04:59 UTC, x110dc approved these changes

2023-07-28 20:32 UTC, x110dc requested changes
I just had one question about the migration. Probably nothing.

2023-07-28 20:32 UTC, x110dc commented on apps/organizations/migrations/0021_DEV-1750_add_uuid_and_stripe_subscription_id_to_org.py
> +
I haven't thought about migrations in a while so this may be a non-issue, but could this be potentially destructive if this migration is run more than once? Under what circumstances could that happen? If that is unlikely to ever happen in production that seems fine.

2023-07-28 21:19 UTC, benjaminEwhite commented on apps/organizations/migrations/0021_DEV-1750_add_uuid_and_stripe_subscription_id_to_org.py
> +
That's a good point. I pushed up this commit that bf6e2dc7f4d8e filters down to only org objects whose uuid is null. Does that address your concern?

bf6e2dc7f4d8e

2023-07-28 21:42 UTC, merged