DEV-3690: Update transactional emails to use header logo alt text
newsrevenuehub/rev-engine pull request #1195
Opened 2023-08-04 12:32 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
Adds logo alt text to email templates

#### Why are we doing this? How does it help us?
Improve email templates

#### How should this be manually tested? Please include detailed step-by-step instructions.
- Log in with HUB admin
- Go to style edit modals
- Send test emails
- Check in your inbox the received email
- Inspect browser, focus on header logo
- If style is default style, logo should have alt text = News Revenue Hub
- If style is custom, logo should either have empty alt text "" if alt-text is not set or it should have the alt text set in default-donation-page style

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
no

#### Have automated unit tests been added? If not, why?
yes

#### How should this change be communicated to end users?
n/a

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3690

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
Parent ticket: https://news-revenue-hub.atlassian.net/browse/DEV-3056

2023-08-07 18:23 UTC, benjaminEwhite requested changes
@GuiMend looking good overall. A couple of small inline comments, and one other request. We're trying to be more detailed with QA instructions.  Would be helpful to provide links to specific styles / pages that are set up with default vs. non default styles so that part of QA requires less guesswork/setup.

2023-08-07 18:23 UTC, benjaminEwhite commented on apps/organizations/models.py
> +    logo_alt_text: str = None
Not a big deal, but any reason can't default to empty string?

2023-08-07 18:23 UTC, benjaminEwhite commented on apps/organizations/models.py
> +                else HubDefaultEmailStyle.logo_alt_text,
There's enough complexity wrapped up here that might make sense to bust out into a separate method on page model (or better yet, as a property `DonationPage.logo_alt_text` or whichever name is most appropriate).

2023-08-08 13:34 UTC, GuiMend commented on apps/organizations/models.py
> +    logo_alt_text: str = None
We can. Updated

2023-08-08 13:41 UTC, GuiMend commented on apps/organizations/models.py
> +                else HubDefaultEmailStyle.logo_alt_text,
I've made a suggestion. Let me know if it's good enough this way.

2023-08-08 14:09 UTC, benjaminEwhite requested changes
@GuiMend I looked more closely, and think we can simplify the logo alt text value assignment.

2023-08-15 20:20 UTC, benjaminEwhite commented on apps/organizations/models.py
> +                else HubDefaultEmailStyle.logo_alt_text,
I'm okay with what's here.

2023-08-15 20:20 UTC, benjaminEwhite commented on apps/organizations/models.py
> +            custom_logo_alt_text = page.header_logo_alt_text or ""
This is all good.

2023-08-15 20:21 UTC, benjaminEwhite commented on apps/organizations/models.py
> +    logo_alt_text: str = None
@GuiMend looks like this small change didn't make it  here (defaulting to empty string).

2023-08-16 13:09 UTC, benjaminEwhite approved these changes

2023-08-17 13:10 UTC, merged