WIP | Dev 3821 start enforcing stripe metadata schema v 1 4 and support passing swag choices value
newsrevenuehub/rev-engine pull request #1196
Opened 2023-08-04 21:05 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-08-07 12:44 UTC, benjaminEwhite commented on apps/contributions/models.py
> -    def stripe_metadata(contributor, validated_data, referer):
moved this to serializer, because relies on `validated_data` which normally only is around in a serializer.

2023-08-09 20:08 UTC, njharman requested changes
Consider using pydantic constraints for min_length, max_length rather than rollon validator.

2023-08-09 20:47 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +        return stripped
5cf49e1d4a44f

2023-08-09 20:47 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            if v.lower() in ["true", "yes", "y"]:
5cf49e1d4a44f

2023-08-10 16:11 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    def validate_swag_choices_string(cls, v: str) -> str:
I beg to differ! I ended up going down the regex pattern matching path and think it's better.  Allows removing `SwagChoice` model which was only there for validation purposes.

8209b401e9a233b5

2023-08-10 16:11 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +        if len(v) > settings.METADATA_MAX_SWAG_CHOICES_LENGTH:
8209b401e9a233b5

2023-08-10 16:12 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +                raise ValueError(msg)
No longer relevant given 8209b401e9a233b5

2023-08-10 16:16 UTC, benjaminEwhite commented on apps/contributions/tests/test_serializers.py
> +            ("YES", True),
1f006764621b and 6bd661ecd117c

2023-08-10 16:18 UTC, benjaminEwhite commented on apps/contributions/tests/test_serializers.py
> +    @pytest.mark.parametrize("value", (0, 1, 2, "0", "1", "cats"))
9ad030c7e17

2023-08-10 16:19 UTC, benjaminEwhite commented on revengine/settings/base.py
> +from enum import Enum
9cd3d755

2023-08-10 19:31 UTC, njharman requested changes
regexes be like hard and stuff ;)

2023-08-10 19:31 UTC, njharman commented on apps/contributions/serializers.py
> +        rf" *[a-z0-9_\-]+ *{SWAG_SUB_CHOICE_DELIMITER}? *[a-z0-9_\-]*)*{SWAG_CHOICES_DELIMITER}? *$"
1. I've always used \s* (which catches tabs, CR, other whitespace), probably unneeded. But if any whitespace character gets in there, I don't want it!
2. doesn't support spaces after trailing ";", not this "foo:bar ;"
3. I was gonna say "[a-z0-9_\-]" can be written as "[-\w]" until I noticed no A-Z, intentional?  (hyphen doesn't need escape if listed first.
4. I'm not sure what (?{SWAG_SUB_CHOICE_DELIMITER} ...) is. I'm fairly certain it's (?: ...) non-capturing. maybe overzealous replacement of ":" with GLOBAL? btw both parens should/could be non-capturing, I don't think it matters as we aren't extracting subelements in this use case. 
5. this matches "foo bar;bizz:bang"  and "foo bar"
6. matches "foo:bar;gah:;" (which may be valid given rules, just pointing out)

I think the space (possibly?) issue can be resolved with 
`^ *[a-z0-9_\-]+ *(: *[a-z0-9_\-]*)?( *; *[a-z0-9_\-]+ *(: *[a-z0-9_\-]*)?)* *;? *$`

Sorry took out GLOBAL to test on https://pythex.org/

Also I might do something like.
```
SUBCHOICE = rf"[a-z0-9_\-]+ *(: *[a-z0-9_\-]*)?"
pattern = rf"^ *{SUBCHOICE}( *; *({SUBCHOICE})* *;? *$"
```

All these variations; leading/trailing white space, inner whitespace, upper/lower case should have tests.

See, regexes are cool!

2023-08-15 21:11 UTC, benjaminEwhite commented on apps/contributions/tests/test_serializers.py
> +    @pytest.mark.parametrize("value", ("", "foo:bar", "foo:bar;bizz:bang"))
Uppercase okay. Had included but lost when reformatting at one point.

2023-08-16 04:44 UTC, x110dc requested changes
I may want to take another pass at reviewing, but thought I'd submit what I've already looked at in case it's helpful.

2023-08-16 04:44 UTC, x110dc commented on apps/contributions/serializers.py
> +    in_memory_of: str = ""
Shouldn't these be `Optional`?

2023-08-16 04:44 UTC, x110dc commented on apps/contributions/serializers.py
> +    reason_for_giving: str = ""
Shouldn't these be optional?

2023-08-16 04:44 UTC, x110dc commented on apps/contributions/serializers.py
> +    swag_opt_out: bool | None = None
Optional?

2023-08-16 04:44 UTC, x110dc commented on apps/contributions/serializers.py
> +    occupation: str = ""
optional?

2023-08-16 04:44 UTC, x110dc commented on apps/contributions/serializers.py
> +        logger.info("Normalizing boolean value %s", v)
logger.debug?

2023-08-16 04:44 UTC, x110dc commented on revengine/settings/base.py
> -METADATA_SOURCE = os.getenv("METADATA_SOURCE", "rev-engine")
I doubt we overrode these in any of our environments, but if these as environment variables are being deprecated here worth noting in the deployment instructions to verify in each environment.

2023-08-16 13:35 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    in_memory_of: str = ""
They certainly can be. It depends on what we want/need down stream. If default of `None`/`null` is better, we can do that.

2023-08-16 13:37 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    occupation: str = ""
ditto.

2023-08-16 14:38 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    in_memory_of: str = ""
be010e90f73

2023-08-16 14:38 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    occupation: str = ""
be010e90f734

2023-08-16 14:39 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +        logger.info("Normalizing boolean value %s", v)
be010e9

2023-08-16 14:51 UTC, benjaminEwhite commented on revengine/settings/base.py
> -METADATA_SOURCE = os.getenv("METADATA_SOURCE", "rev-engine")
Updated instructions.

2023-08-16 15:50 UTC, benjaminEwhite commented on apps/contributions/tests/test_serializers.py
> +    @pytest.mark.parametrize("value", ("", "foo:bar", "foo:bar;bizz:bang"))
See [comment in JIRA](https://news-revenue-hub.atlassian.net/browse/DEV-3821?focusedCommentId=88092). Ended up pivoting on approach and not using "pure" regex anymore.

2023-08-16 21:08 UTC, njharman approved these changes
Really just looked at updated validator and tests

Few suggestions in PR comments, consider and apply or not, no need for rereview

2023-08-16 21:08 UTC, njharman commented on apps/contributions/tests/test_serializers.py
> +            "foo",
Some other options to consider (which I'm fairly certain your code passes, but I'm a "completest" when it comes to test cases ;)

foo;
foo:bar;bizz
bizz;foo:bar

2023-08-16 21:08 UTC, njharman commented on apps/contributions/tests/test_serializers.py
> +            "foo: bar ;",
options to consider

;foo:bar
f oo
fo'o:bar
fo-o:bar
1foo:bar
foo2:bar
foo:bar\n

2023-08-16 21:15 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            if choice and not re.fullmatch(choice_pattern, choice):
`<sarcasm>`I've known about it for ages and definitely didn't learn about it from ChatGPT a couple hours ago `</sarcasm>`

2023-08-16 21:18 UTC, benjaminEwhite commented on apps/contributions/tests/test_serializers.py
> +            "foo",
fcdb735dd55d

2023-08-16 21:25 UTC, benjaminEwhite commented on apps/contributions/tests/test_serializers.py
> +            "foo: bar ;",
Some of these are allowed (numbers and dashes are okay, and it's okay if there's a `;` followed by valid choice cause we allow empty swag choices), so put the ones that should fail in this test and ones that should pass in previous test.

129eeffe7ce5

2023-08-18 03:12 UTC, x110dc requested changes
A couple things:

The metadata for the customer object and the payment objects are both in this code, but those schemas are separate. I just updated this wiki page to try to make that more clear: 

https://news-revenue-hub.atlassian.net/wiki/spaces/~412508230/pages/2485551160/Stripe+Metadata

There's no change in the customer metadata for v1.4, so can probably just leave those out.

It could be argued that the Switchboard code is incorrect, but for now it should be considered the reference implementation, so any idiosyncrasies there should be duplicated here so we don't produce metadata in RevEngine that's rejected by Switchboard. 

Ideally the JSON Schema emitted by the model(s) in RevEngine should be identical to that from Switchboard, but given Switchboard is using the previous version of Pydantic that's probably difficult or impossible until it's upgraded. 

The Switchboard code doesn't define as many (any?) `None` defaults as this code does. That may be okay, but it may also be safer to make them consistent?

2023-08-21 12:46 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    contributor_id: str | int
The problem is that if we restrict to `str`, our tests fail, because these IDs are `int`s in tests.

2023-08-23 14:14 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    contributor_id: str | int
Ended up adding a validator and converting to string.

b11201e519278e4

2023-08-23 14:15 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    donor_selected_amount: int
33f7d3ab6

2023-08-23 14:17 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    referer: str
982bf7840

2023-08-23 14:20 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    revenue_program_id: str | int
f0b595e03c51

2023-08-23 14:21 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    marketing_consent: Optional[bool] = None
Removed, but not a single commit to point to because there was some intermediate state that would cause pointing to most recent relevant commit confusing.

2023-08-23 14:23 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    occupation: Optional[str] = None
Removed, but not a single commit to point to because there was some intermediate state that would cause pointing to most recent relevant commit confusing.

2023-08-23 14:24 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    source: str = settings.METADATA_SOURCE_REVENGINE
982bf78403

2023-08-23 14:24 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    @pydantic.validator("marketing_consent", "swag_opt_out", "agreed_to_pay_fees")
Removed.

2023-08-23 14:25 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    schema_version: str = settings.METADATA_SCHEMA_VERSION_1_4
982bf78403

2023-08-24 19:25 UTC, x110dc requested changes
One minor typo in a comment. And then just a question about TEST vs. PROD.

2023-08-24 19:25 UTC, x110dc commented on apps/contributions/serializers.py
> +    """Schema for used for generating metadata on Stripe payment intents and subscriptions"""
"Schema is used"?

2023-08-24 19:25 UTC, x110dc commented on apps/contributions/serializers.py
> +        In prod, IDs will aready be a string, but in test, they will be an integer. This allows
Why would the IDs be different in PROD vs. TEST?

2023-08-24 19:43 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +        In prod, IDs will aready be a string, but in test, they will be an integer. This allows
This theory was wrong, but am moving conversation to JIRA.

2023-08-24 20:32 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +        In prod, IDs will aready be a string, but in test, they will be an integer. This allows
8441c6a52a7c58

2023-08-24 20:32 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +        In prod, IDs will aready be a string, but in test, they will be an integer. This allows
8441c6a52a7c58

2023-08-24 20:32 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    """Schema for used for generating metadata on Stripe payment intents and subscriptions"""
8441c6a52a7c58

2023-08-31 04:14 UTC, x110dc approved these changes

2023-09-07 20:22 UTC, x110dc approved these changes

2023-09-12 14:01 UTC, merged