DEV-3847_flake8_versions_match_precommit_upgrade
newsrevenuehub/rev-engine pull request #1199
Opened 2023-08-09 22:59 UTC by njharman

#### What's this PR do?

1. update pre-commit hooks
2. ensure poetry and pre-commit flake8 versions match
3. flake8 test revengine/settings/*
4. add couple import os (flake8 issues)
5. add ignore "undefined" revengine/settings/* (the reasons files were ignored, but narrower "exception" is better / will catch other issues)
6. enabled talisman checker (lets see if it works in CI...)
7. checked the dockerlinter issue was till issue (it was so remains commented out)
8. briefly checked pylint. it's too much more change for this ticket. and I don't really pylint...

As part of upgrade a heap of changes were made by

- black in ./apps/
- js prettier in ./spa/

eslint reports many issues. opened separate ticket [DEV-3848] to fix those.

#### Why are we doing this? How does it help us?
Consistency between dev and CI is good.
In some review noticed flake8 error in revengine/settings. pre-commit check will catch now.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
Yes

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
N/A

#### Have automated unit tests been added? If not, why?
N/A
#### How should this change be communicated to end users?
N/A
#### Are there any smells or added technical debt to note?
N/A
#### Has this been documented? If so, where?
N/A
#### What are the relevant tickets? Add a link to any relevant ones.
[DEV-3847] broke out resolving eslint to [DEV-3848] 
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
Should not.
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
eslint reports many issues, resolving them is up to [DEV-3848]

2023-08-17 22:41 UTC, x110dc approved these changes

2023-08-18 14:04 UTC, nrh-cklimas requested changes

2023-08-18 19:55 UTC, njharman commented on .gitignore
> +package-lock.json
They were untracked (and newly created by me after doing some js upgrade things to make the js linter pre-commit check happy), I committed them.

https://github.com/newsrevenuehub/rev-engine/commit/e31b34c3d2c7c815bff94e7a6f2923e6fbbb818e

2023-08-28 23:29 UTC, x110dc approved these changes

2023-10-11 12:45 UTC, nrh-cklimas approved these changes

2023-10-12 20:58 UTC, merged