DEV-3779: Style this email in accordance with design spec
newsrevenuehub/rev-engine pull request #1200
Opened 2023-08-09 23:52 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
Update style for email template: Upgrade to core confirmation

#### Why are we doing this? How does it help us?
Make email template styling consistent

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
[in progress]

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
yes

#### Have automated unit tests been added? If not, why?
n/a

#### How should this change be communicated to end users?
n/a

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3779

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
Parent ticket: https://news-revenue-hub.atlassian.net/browse/DEV-3318

2023-08-15 20:41 UTC, benjaminEwhite requested changes
From AC perspective, looks all good.

One small request to use the `static` template tag instead of sending in context for the image assets.

2023-08-15 20:41 UTC, benjaminEwhite commented on apps/organizations/views.py
> +                "check_icon": os.path.join(settings.SITE_URL, "static", "check-icon.png"),
I think you should be able to use the `static` tag in the mail template in order to avoid sending additional context.  See Django docs here: https://docs.djangoproject.com/en/3.2/howto/static-files/

2023-08-15 20:41 UTC, benjaminEwhite commented on apps/organizations/views.py
> +                "check_icon": os.path.join(settings.SITE_URL, "static", "check-icon.png"),
In which case, not something we need to test around, since you'd be testing Django implementation.

2023-08-15 20:41 UTC, benjaminEwhite commented on apps/emails/tests/test_templates.py
> +        "check_icon": os.path.join(settings.SITE_URL, "static", "check-icon.png"),
See comment below. Think you probably don't need this if use the `static` template tag.

2023-08-16 20:27 UTC, GuiMend commented on apps/organizations/views.py
> +                "check_icon": os.path.join(settings.SITE_URL, "static", "check-icon.png"),
@benjaminEwhite , I tried doing it like you suggested but I'm not able to make it work yet.
Could you review my code to see if you spot what I'm doing wrong?

![image](https://github.com/newsrevenuehub/rev-engine/assets/9381325/b2ac78bb-babb-4d74-9b82-38ff6d3b8952)

Btw, I tried adding the icons into `revengine/static/...` and I also tried creating a static folder into the parent folder for `templates` (in the same format as `admin_limited_select.html` file)

2023-08-16 21:12 UTC, benjaminEwhite commented on apps/organizations/views.py
> +                "check_icon": os.path.join(settings.SITE_URL, "static", "check-icon.png"),
@GuiMend I looked into this and I believe it would require some configuration of whitenoise that we don't already do. On other hand, I'm finding pre-existing examples of the approach you originally took. I thought this would be a quick fix, but don't think it's worth the effort just to avoid sending context. No need to change.

2023-08-16 21:13 UTC, benjaminEwhite approved these changes

2023-08-18 15:37 UTC, merged