DEV-3692: Add/move logo-related fields from Setup tab of page editor to Style
newsrevenuehub/rev-engine pull request #1208
Opened 2023-08-17 14:20 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a 

#### What's this PR do?
- Move logo related fields from PageSetup tab to style tab and add logo alt text field
- Add variation for ImageUpload component (default is bulky and the new one - slim - is to handle the logo upload in the style tab)
- Add z-index on EditSaveControls.styles.ts so that action button stays on top of color picker fields
- Create helper function for `addMiddleEllipsis`

#### Why are we doing this? How does it help us?
- One more step needed for the style improvements

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
yes

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
yes

#### Have automated unit tests been added? If not, why?
yes

#### How should this change be communicated to end users?
Logo editing are now in styles tab

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3692

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
Epic: https://news-revenue-hub.atlassian.net/browse/DEV-3056

2023-08-18 18:04 UTC, nrh-cklimas requested changes

2023-08-18 18:04 UTC, nrh-cklimas commented on spa/src/components/pageEditor/editInterface/pageStyles/StylesTab.test.tsx
> +    it('should update logo image', () => {
We should add a test for if the logo image is removed.

2023-08-18 18:04 UTC, nrh-cklimas commented on spa/src/utilities/addMiddleEllipsis.ts
> +    return str.substring(0, 20) + '...' + str.substring(str.length - 10, str.length);
```suggestion
    return str.substring(0, 20) + '…' + str.substring(str.length - 10, str.length);
```
e.g. a single Unicode char instead of three periods.

2023-08-22 16:01 UTC, GuiMend commented on spa/src/components/pageEditor/editInterface/pageStyles/StylesTab.tsx
> +  }
The equivalent would be `const showLogoInput = (headerThumbnail && headerLogo) || headerLogo;`

2023-08-22 16:07 UTC, GuiMend commented on spa/src/components/pageEditor/editInterface/pageStyles/StylesTab.tsx
> +            value={headerLogo as any}
I've updated the TS of value inside ImageUpload to accept `string` as I'm handling that scenario in the component

2023-08-22 17:13 UTC, GuiMend commented on spa/src/components/base/ImageUpload/ImageUpload.styled.ts
> +  width: 432px;
That is right @nrh-cklimas . I've copy&pasted the style from figma and didn't remember to remove this one

2023-08-23 15:15 UTC, nrh-cklimas commented on spa/src/utilities/addMiddleEllipsis.ts
> +    return str.substring(0, 20) + '…' + str.substring(str.length - 10, str.length);
I think these numbers need to change based on `maxLength`. Right now `addMiddleEllipsis('12345', 3)` returns `"12345…12345"`.

2023-08-23 15:20 UTC, nrh-cklimas commented on spa/src/components/base/ImageUpload/ImageUpload.tsx
> +      <Slim className={className!}>
I think let's remove the `showLabel` prop and let consumers do whatever they want here.

2023-08-31 13:52 UTC, nrh-cklimas commented on spa/src/utilities/addMiddleEllipsis.ts
> +}
I don't see that much benefit in asking consumers to decide on how much of each part of the string they want--here's an alternate solution that splits the excerpt as evenly as possible and adds some error checking.

```tsx
function addMiddleEllipsis(string: string, maxLength = 35) {
  if (maxLength < 3) {
    throw new Error("Max length must be at least 3");
  }

  if (string.length <= maxLength) {
    return string;
  }

  // We want to truncate the string to maxLength - 1, to leave room for the
  // ellipsis in the middle.

  const sliceLength = Math.floor((maxLength - 1) / 2);

  // However, if the requested length is even, we need uneven slices--we'll
  // favor the start.

  if (maxLength % 2 === 0) {
    return string.slice(0, sliceLength + 1) + "…" + string.slice(-sliceLength);
  }

  return string.slice(0, sliceLength) + "…" + string.slice(-sliceLength);
}

```

2023-09-01 12:11 UTC, GuiMend commented on spa/src/utilities/addMiddleEllipsis.ts
> +}
The idea behind doing it the way I did is because we don't want the pre & post slices to be variable depending on the size. The ellipsis is supposed to reduce the string to a manageable size so it doesn't seem right to have a 50 length string go to a 25 length with ellipsis and a 100 length go down to a 50. I would expect both to behave the same 50 -> 25 and 100 -> 25.

I can remove the option to add a custom pre/post sizes, but I wanted to leave the option for the developer using the function.

2023-09-01 13:18 UTC, nrh-cklimas commented on spa/src/utilities/addMiddleEllipsis.ts
> +}
Another way to put it is, it doesn't feel logical to me that I could call `addMiddleEllipsis('1234567890', 5, 2, 1)` and end up with a string of length 4 (`12…0`) when I asked for a max length of 5.

2023-09-01 14:12 UTC, GuiMend commented on spa/src/utilities/addMiddleEllipsis.ts
> +}
Oh, sorry about that @nrh-cklimas . I was the one who made the wrong assumption. 
I think I made a quick test of the code you suggested and misinterpreted the results. I like your suggestion and will update the function. 

You can ignore my previous comment.

2023-09-01 14:25 UTC, nrh-cklimas approved these changes

2023-09-06 12:58 UTC, merged