DEV-3724-page-previews-missing-incorrect
newsrevenuehub/rev-engine pull request #1214
Opened 2023-08-23 16:31 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
- Fixes image preview when saving changes to a donation page

#### Why are we doing this? How does it help us?
- Previews are broken

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
yes

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
no

#### Have automated unit tests been added? If not, why?
No. The files changed doesn't have test files, it will be addressed in a future ticket: https://news-revenue-hub.atlassian.net/browse/DEV-3895

#### How should this change be communicated to end users?
Page previews are updating whenever a donation page is saved

#### Are there any smells or added technical debt to note?
Yes. `DonationPage` & `PageEditor` are still JS files with no tests. We should address this when available to improve quality and reliability of the code. 

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3724

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
Ticket to update `DonationPage` & `PageEditor` to TS files and add tests.
https://news-revenue-hub.atlassian.net/browse/DEV-3895

2023-08-24 14:43 UTC, nrh-cklimas requested changes

2023-08-24 14:43 UTC, nrh-cklimas commented on spa/src/components/common/Button/ContributionPageButton/ContributionPageButton.styled.ts
> +  background-position-x: center;
?

2023-08-24 15:07 UTC, GuiMend commented on spa/src/hooks/useContributionPage/pageUpdateToFormData.ts
> +      `${screenshotBaseName.replace(/\s/g, '')}_${formatDatetimeForAPI(new Date())}.png`
This is a test to see if the issue with updating the image preview was related to spaces in the filename. Probably isn't but worth the try.

2023-08-24 15:10 UTC, GuiMend commented on spa/src/components/common/Button/ContributionPageButton/ContributionPageButton.styled.ts
> +  background-position-x: center;
I made this change because IMO it improved the preview with only centering `x` instead of `y` as well.

with `background-position-x: center`
![Screenshot 2023-08-24 at 12 07 13](https://github.com/newsrevenuehub/rev-engine/assets/9381325/7d9df69c-cdf7-422f-89e0-7b01f98ad1db)

with `background-position: center`
![Screenshot 2023-08-24 at 12 07 29](https://github.com/newsrevenuehub/rev-engine/assets/9381325/5d9b84a6-85cf-401d-98ad-42f4449fa81d)

I can confirm with Rachel this change, though I don't remember seeing anywhere requiring the thumbnail centered x & y.

2023-08-25 15:38 UTC, GuiMend commented on spa/src/components/common/Button/ContributionPageButton/ContributionPageButton.styled.ts
> +  background-position-x: center;
Rachel approved the changes @nrh-cklimas (DM in slack)

2023-08-26 18:06 UTC, nrh-cklimas commented on spa/src/components/common/Button/ContributionPageButton/ContributionPageButton.styled.ts
> +  background-position-x: center;
Oh, I see. My nitpick would be in that case, let's be explicit and do `background-position: top center`.

2023-08-26 18:07 UTC, nrh-cklimas commented on spa/src/hooks/useContributionPage/pageUpdateToFormData.ts
> +      `${screenshotBaseName.replace(/\s/g, '')}_${formatDatetimeForAPI(new Date())}.png`
I think based on Ben's work we don't need this.

2023-08-26 18:10 UTC, nrh-cklimas commented on spa/src/components/donationPage/DonationPage.js
> +function DonationPage({ page, live = false }, ref) {
I haven't seen this code style before, e.g. sans `forwardRef`. I think it's a moot point here since it's JS, but it would be good to use in TypeScript since it would provide typing? Curious what your thoughts are on this style point.

2023-08-28 13:24 UTC, GuiMend commented on spa/src/components/donationPage/DonationPage.js
> +function DonationPage({ page, live = false }, ref) {
I'm actually using the `forwardRef` @nrh-cklimas , but it's in the export.
```js
export default forwardRef(DonationPage);
```

Would you like me to change that?

2023-08-31 13:14 UTC, nrh-cklimas approved these changes

2023-09-06 13:53 UTC, merged