[WIP] DEV-3865 | Update caches on subscription update and cancelation
newsrevenuehub/rev-engine pull request #1215
Opened 2023-08-23 20:36 UTC by benjaminEwhite

…iews

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-08-24 23:16 UTC, benjaminEwhite commented on apps/contributions/views.py
> -            return Response({"detail": "Revenue Program not found"}, status=status.HTTP_404_NOT_FOUND)
I came across this and realized that it will not lead to a response. Instead it will lead to an unexpected error in calling context, because caller expects this to return a list of `StripePiAsPortalContribution`s, not a Response.

2023-08-25 19:52 UTC, njharman requested changes
Great code coverage, good changes, +1 converting 403 to 404 for security greatness!

Some small requests/clarifications and larger DRY one.

2023-08-25 19:52 UTC, njharman commented on apps/contributions/stripe_contributions_provider.py
> +        self.email_id = email_id.lower()
I don't see a test that verifies email_id will be lowercased. I could have missed.  Probably more important for the cache key creation in `__init__`s below.

Reasoning being, if it mattered to add to code (supposedly to catch some issue), then it matters enough to protect against regression with test case.

2023-08-25 19:52 UTC, njharman commented on apps/contributions/views.py
> -            return Response({"detail": "Revenue Program not found"}, status=status.HTTP_404_NOT_FOUND)
+1 (for adding test :) oh, and for making method that does not use self, @static.

2023-08-25 19:52 UTC, njharman commented on apps/contributions/views.py
>          subscriptions = cache_provider.load()
If I understand logic; should this (second call to cache_provider.load()) not be indented into the `if not subscriptions`. As it is now subscriptions will be pulled from cache twice (when it was there first time).

2023-08-25 19:52 UTC, njharman commented on apps/contributions/stripe_contributions_provider.py
> +        self.key = f"{email_id.lower()}-payment-intents-{self.stripe_account_id}"
Are stripe_account_id strictly numeric (not uuid)?  I'd just lower() the entire key to not have to ever worry about it.

ICYDK, literal strings have methods like lower `f"{email...}-payment...".lower()`

2023-08-25 19:52 UTC, njharman commented on apps/contributions/views.py
> +        except stripe.error.StripeError:
[Not actionable commentary]  I failed to find a definitive answer if Django cache system will not raise Exception. So, I can't really recommend also catching those (Although I'd really recommend that our CacheProviders catch, log, and suppress Exceptions (which is probably/hopefully what Django is doing)).

Caching being an "add on" should fail gracefully, but loudly (logigng).

2023-08-25 19:52 UTC, njharman commented on apps/contributions/views.py
> +        return response
Isn't this largely the same repeated code from partial_update? It should be DRY.

@x110dc Out of scope but I'm still gonna complain; 
I don't think I like the way we've implemented caching [I might not know enough of our business/use cases and be wrong]. It should be much lower down and more invisible to "users" of storage system (such as this view). I'd probably want to wrap stripe.retrieve/modify/etc with cache (I think those are the "store").  Which would mean the cache always matches "store" and would probably have prevented this tickets issue.

I just see more errors as "users" forget to also update cache and even if they do, requiring too much repeated boiler plate code.

2023-08-25 20:28 UTC, benjaminEwhite commented on apps/contributions/stripe_contributions_provider.py
> +        return (self.payment_intent.get("payment_method", {}) or {}).get("card", {}) or default
They're `AttrDict`-like in that Stripe objects behave both like dicts and objects.

The change here is narrowly to make this property after changing things so we update cache. I'm reluctant to rethink the overall existing implementation.

2023-08-25 20:31 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        except stripe.error.StripeError:
Don't disagree, but out of scope for this PR.

2023-08-25 20:34 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        return response
FWIW, @njharman part of the reason we're not doing a deeper rethink of the caching layer here is there's a good chance it will go away altogether in some currently planned work. I believe we'll be relying more on storing relevant stripe data in Revengine and ingesting it via webhooks.

2023-08-25 20:40 UTC, benjaminEwhite commented on apps/contributions/views.py
>          subscriptions = cache_provider.load()
Great point! 6cc54832a0f

2023-08-25 21:39 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        return response
I'm generally all for DRYing up, but going to push back on that here. 

The first try/except block in the code you cited is not comparable to partial update. In the case of partial_update, we don't need to re-retrieve the subscription because `stripe.Subscription.modify` returns it (and can expand requried fields). 

In destroy, we need to re-retrieve the subscription to get fresh state, as `stripe.Subscription.delete`  does not  allow for expanding fields, and we need those for things to work out with serialization/caching.

That said, the second try/except can be dried up. Did that in 00db11f4522

2023-08-25 21:54 UTC, benjaminEwhite commented on apps/contributions/stripe_contributions_provider.py
> +        self.email_id = email_id.lower()
Ended up just lowering as you suggested below when creating `self.key` in respective caches.

9c83555ad0f

2023-08-25 22:00 UTC, benjaminEwhite commented on apps/contributions/stripe_contributions_provider.py
> +        return (self.payment_intent.get("payment_method", {}) or {}).get("card", {}) or default
AttrDict and Stripe objects are similar though not identical in behaviors. Shared traits: act like dict, act like object.

Difference is that if you look up a nonexistent property/key in an attrdict, you get back an empty dict. 

If you do that on a Stripe object, you get an AttributeError.

2023-08-25 22:02 UTC, benjaminEwhite commented on apps/contributions/stripe_contributions_provider.py
> +        self.key = f"{email_id.lower()}-payment-intents-{self.stripe_account_id}"
agree. this is a better approach. 

9c83555ad0f

2023-08-25 23:10 UTC, njharman approved these changes
Ship it!

2023-08-25 23:10 UTC, njharman commented on apps/contributions/stripe_contributions_provider.py
> +        return (self.payment_intent.get("payment_method", {}) or {}).get("card", {}) or default
Yep, ok

2023-08-25 23:10 UTC, njharman commented on apps/contributions/views.py
> +        return response
fair enough

2023-08-29 00:24 UTC, x110dc approved these changes

2023-08-31 03:22 UTC, merged