DEV-3907 | change log to info to reduce sentry noise, and test customize_account
newsrevenuehub/rev-engine pull request #1219
Opened 2023-08-25 18:22 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

This PR changes a .warning log in the customize-account view to .info in order to reduce noise in Sentry. Validation errors are normal/expected, and Sentry shouldn't hear about them.

Additionally, I noticed that there were no unit tests for this view, so I added.

#### Why are we doing this? How does it help us?

Reducing noise in Sentry makes it more valuable.

Also, this view is critical business logic, and therefore really should be testsed.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-08-29 16:39 UTC, njharman approved these changes
approved

2023-09-01 21:46 UTC, benjaminEwhite commented on apps/organizations/models.py
> +    def generate_unique_name(cls, name: str) -> str:
This logic used to live  inline in the `customize_account` view function. Isolated and moved it to model so potentially can be used in other context and to make it more easily testable.

2023-09-01 21:47 UTC, benjaminEwhite commented on apps/organizations/models.py
> +    name = models.CharField(max_length=RP_NAME_MAX_LENGTH)
Moved to a constant so can reference in other files (especially tests).

2023-09-01 21:50 UTC, benjaminEwhite commented on apps/users/permissions.py
> +    return bool(request.user) and request.user.email_verified
Added unit test for this, and in so doing discovered that original implementation returns None instead of boolean when request.user is None, which is not what we want (even if both are falsy).

2023-09-01 21:51 UTC, benjaminEwhite commented on apps/users/permissions.py
> +        return request.user is not None and request.user.accepted_terms_of_service is not None
Also here, wanted to ensure we will get a boolean, not None if no user.

2023-09-01 21:54 UTC, benjaminEwhite commented on apps/users/serializers.py
>              )
These are field-level errors, and so should return dict with key that's field name to follow pattern elsewhere.

2023-09-01 22:04 UTC, benjaminEwhite commented on apps/users/serializers.py
> +        """Create an organization, revenue program and role assignment. Also update user with new data
This logic used to live in the view layer, but this is more idiomatic to have here, and also more easily testable.

2023-09-01 22:05 UTC, benjaminEwhite commented on apps/users/serializers.py
> +            reversion.set_comment("CustomizeAccountSerializer.create updated user")
We were't doing this before, but in general, good idea to add revision any time we're modifying a model so there's a "paper" trail.

2023-09-01 22:07 UTC, benjaminEwhite commented on apps/users/tests/test_permissions.py
We weren't unit testing these permissions in isolation before, which seemed non-ideal. By unit testing here, it allows us to just test that the customize_account endpoint has the right permissions set, and allows us to avoid having slow tests via view layer that check that permissions (i.e., log in as user who shouldn't have permissions, try to do the thing, assert about response).

2023-09-01 22:08 UTC, benjaminEwhite commented on apps/users/tests/test_serializers.py
> +    def test_validate_fiscal_status(
Opportunistically added unit test for this method to get coverage on this file to 100%

2023-09-05 19:21 UTC, njharman requested changes
Looks good, +1 coverage

Small issue and +1 comment, no need for re-rereview

2023-09-05 19:21 UTC, njharman commented on apps/organizations/migrations/0022_DEV-3907_decrease_org_name_max_length.py
> +            field=models.CharField(max_length=63, unique=True),
Just commenting/approving, good choice to use literal and not CONSTANT var here for max_length in DB migration file.

Not doing so has caused me pain.  Migrations are a state change at specific point in time.  A later modification of the  CONSTANT should not alter what this (or any previous) migration did. Instead, a new migration should be added that reflects the modification of constant's value.

2023-09-05 19:21 UTC, njharman commented on apps/users/permissions.py
> +    return bool(request.user) and request.user.email_verified
fair, I dislike that it's been implemented two different ways, casting here and ` if not None` below. I prefer if not None

2023-09-05 19:21 UTC, njharman commented on apps/organizations/models.py
> +                counter += 1
Counters are so "C". I'd use the power of Python!

```
for counter in range(1, MAX_APPEND_ORG_NAME_ATTEMPTS):
      appended = f"{name}-{counter}"
            if not cls.objects.filter(name=appended).exists():
                return appended
# after 99 attempts, naturally falls out of loop to log & raise.
```

2023-09-05 20:20 UTC, benjaminEwhite commented on apps/organizations/migrations/0022_DEV-3907_decrease_org_name_max_length.py
> +            field=models.CharField(max_length=63, unique=True),
Just the behavior I got by default by setting it to a literal in the model file, but I'll take the complement :) 

That said, I've encountered migration files in past that had hard coded constants and it caused headaches to be sure.

2023-09-06 00:01 UTC, benjaminEwhite commented on apps/users/permissions.py
> +    return bool(request.user) and request.user.email_verified
71a9bb9d51b3

2023-09-06 00:04 UTC, benjaminEwhite commented on apps/organizations/models.py
> +                counter += 1
29d6ed8b4f2

2023-09-07 21:09 UTC, x110dc approved these changes

2023-09-07 21:09 UTC, x110dc commented on apps/organizations/models.py
> +        counter = 1
Does this need to be set when the loop will already set it to 1?

2023-09-07 21:09 UTC, x110dc requested changes
One question.

2023-09-08 13:13 UTC, benjaminEwhite commented on apps/organizations/models.py
> +        counter = 1
No, bad copy pasta after Norm's suggestion.

2023-09-08 13:14 UTC, benjaminEwhite commented on apps/organizations/models.py
> +        counter = 1
98ad4c26aef283071631d895e5d45f59cb3d9ec6

2023-09-12 04:58 UTC, x110dc approved these changes

2023-09-12 18:50 UTC, merged