DEV-3911: Handle error + add validation to Profile Form
newsrevenuehub/rev-engine pull request #1225
Opened 2023-09-04 14:14 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
This PR can be merged to main (it works by itself with the BE that we currently have), but to be functional and to display BE field errors in the form https://github.com/newsrevenuehub/rev-engine/pull/1219 needs to be merged (That other PR is responsible for adjusting the BE error messages)

#### What's this PR do?
Adds field validation to Profile Form and relays BE errors to the correct place in the form. 

#### Why are we doing this? How does it help us?
Displays to the user if any actionable error has occurred and suggests a way to fix it.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
yes

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
yes, showing error more clearly

#### Have automated unit tests been added? If not, why?
yes

#### How should this change be communicated to end users?
n/a

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3911
https://news-revenue-hub.atlassian.net/browse/DEV-3907 (https://github.com/newsrevenuehub/rev-engine/pull/1219) 

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
Finalize https://news-revenue-hub.atlassian.net/browse/DEV-3907

2023-09-05 14:25 UTC, nrh-cklimas requested changes

2023-09-05 14:30 UTC, GuiMend commented on spa/src/state/fetch-reducer.ts
> +  errors: null,
This file was outdated. There was only 1 place where we used `fetch-reducer`'s error as an array, and it was the file I changed in this PR. In all the other use cases, the error was an object.

There is no practical difference between setting from `[]` to `null`. It's just making it type-consistent with how we actually use it.

2023-09-05 14:32 UTC, GuiMend commented on spa/src/components/account/Profile/ProfileForm.tsx
> +              error={!!errors?.firstName || !!error?.first_name}
I can make this change, but I'd rather have the input let me type and show a max char error. It's a more explicit way of identifying that you reached max chars.

If we halt chars from being typed, the user might try to type and not notice that the chars are not being updated. Let's ask Rachel's input on this as it affects UX.

2023-09-06 15:20 UTC, nrh-cklimas commented on spa/src/state/fetch-reducer.ts
> +  errors: null,
OK, got it. Right now the typing on `errors` is very weak--just `any`. But the goal is to get rid of this reducer in favor of react-query so I think this is OK for the time being.

2023-09-19 14:45 UTC, nrh-cklimas approved these changes

2023-09-19 14:45 UTC, merged