ITS-2024: Only run tests when relevant code changes
newsrevenuehub/rev-engine pull request #1236
Opened 2023-09-14 00:05 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

Adds logic so that unit tests only run when the related code changes.

#### Why are we doing this? How does it help us?

Faster CI, uses fewer GH Actions minutes.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

n/a

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No.

#### Have automated unit tests been added? If not, why?

n/a, CI-related only

#### How should this change be communicated to end users?

Not needed.

#### Are there any smells or added technical debt to note?

No.

#### Has this been documented? If so, where?

No.

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/ITS-2024

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No.

2023-09-15 17:57 UTC, benjaminEwhite requested changes
Overall seems good. Think we may be filtering out some files at root level for which we should run Python tests if changes.

2023-09-15 17:57 UTC, benjaminEwhite commented on .github/workflows/test-python.yml
> +              - 'revengine/**'
I don't know exactly how this works, but does this mean we would not get Python tests running if the following files (located at repo root folder) change?

- conftest.py
- manage.py
- poetry.lock
- pyproject.toml
- pytest.ini

If any of those changes, I think we want to run tests, even if no other python code has changed.

2023-09-19 13:29 UTC, nrh-cklimas commented on .github/workflows/test-python.yml
> +              - 'revengine/**'
That's correct--thanks for the feedback! I added those in c0beed5711c3931e1095d77c597fd1e5ec524810.

2023-09-19 13:43 UTC, benjaminEwhite approved these changes

2023-09-25 03:40 UTC, x110dc approved these changes

2023-09-25 14:43 UTC, closed without merging