DEV-3975 | Contributor portal does not show imported legacy subscriptions
newsrevenuehub/rev-engine pull request #1238
Opened 2023-09-14 20:31 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

The primary objective of this PR is to solve for a bug that resulted in contributors not being able to see some expected recurring contributions, which blocks them from updating payment method or cancelling. 

Contributions were being filtered out of that response by the API because they had a null value set for payment type property (see explanation in JIRA ticket).

This PR solves for this by implementing a path to assign a non-null value for payment type for PIs associated with legacy imported recurring contributions. 

The underlying problem was that  our code had faulty implicit assumptions about what payment intents resulting from legacy import look like. We expected them to have a payment method object (in expanded form) but there are no guarantees that PIs retrieved from Stripe will meet this expectation.

In particular, all NRE-generated payment intents (that are not tied to flagged recurring contributions) should meet this expectation because of how we confirm those payments on frontend using payment element. However, it appears that the imported payment intents we are getting were created in such a way where this expectation is not met.

In that case, there is another place we can derive the payment method from, and that allows us to assign a value for `payment_type` which is derived from payment method.

In addition to solving for the underlying bug, I took the opportunity to retire some unittest implemented tests.

#### Why are we doing this? How does it help us?

Solves for critical bug that stops some contributors from being able to update or cancel their recurring contributions.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-09-15 19:21 UTC, benjaminEwhite commented on apps/contributions/stripe_contributions_provider.py
> +    def convert_uninvoiced_subs_into_contributions(
This is drying up some logic that lived inline but is now valuable in two places.

2023-09-18 20:51 UTC, benjaminEwhite commented on apps/contributions/stripe_contributions_provider.py
> +    def payment_method(self) -> StripeObject | None:
Moved this into its own property. Some of this was inlined in other places.

2023-09-18 20:54 UTC, benjaminEwhite commented on apps/contributions/stripe_contributions_provider.py
> -            return [{}]
Returning `[{}]` was a mistake in the original. This should only ever return a single item, not an array of items.

2023-09-18 23:05 UTC, njharman requested changes
> I took the opportunity to retire some unittest implemented tests.
+1

Changes, questions/suggestions, some missing coverage

2023-09-18 23:05 UTC, njharman commented on apps/contributions/views.py
>          sub_cache_provider.upsert([subscription])
Not covered by unit tests

2023-09-19 13:17 UTC, benjaminEwhite commented on apps/contributions/stripe_contributions_provider.py
> +            return self.payment_intent.amount_refunded > 0
This entire method is broken. See the todo at line 202 above. We'll fix in a separate ticket.

2023-09-19 13:29 UTC, benjaminEwhite commented on apps/contributions/stripe_contributions_provider.py
> +        pm = None
e1ba75df

2023-09-19 16:35 UTC, njharman approved these changes

2023-09-19 16:35 UTC, njharman commented on apps/contributions/views.py
>          )
good

2023-09-19 16:35 UTC, njharman commented on apps/contributions/stripe_contributions_provider.py
> +            raise InvalidMetadataError(f"Metadata is invalid for payment_intent : {self.id}, %s", metadata)
Darn, I was hoping there was some cool, obscure reason why.

2023-09-19 21:59 UTC, x110dc approved these changes

2023-09-20 15:33 UTC, merged