[WIP] DEV-3909 | Fix N+1 and poor performance in /api/v1/token endpoint
newsrevenuehub/rev-engine pull request #1242
Opened 2023-09-19 15:10 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-09-20 14:37 UTC, benjaminEwhite commented on apps/common/utils.py
> +            # NB: adding `str(error)` because this function gets run in bootstrap-review-app management command
This is here because we were having issues with deploying review app. Good to keep this note and updated log around until that's resolved (see https://news-revenue-hub.atlassian.net/browse/DEV-4011)

2023-09-20 14:38 UTC, benjaminEwhite commented on apps/common/utils.py
> -# class AttrDict(dict):
Removed this because it's unused/commented and we use a third-party library for this purpose.

2023-09-20 14:38 UTC, benjaminEwhite commented on apps/users/migrations/0007_DEV-3909_alter_roleassignment_user.py
> +class Migration(migrations.Migration):
only change here is that we get a related name.

2023-09-20 14:42 UTC, benjaminEwhite commented on apps/users/serializers.py
> -    super_user status and RoleAssignment.
removed this part of docstring because we no longer explicitly do this in serializer. instead we rely on the queryset having been appropriately filtered upstream.

2023-09-20 14:43 UTC, benjaminEwhite commented on apps/users/serializers.py
> -        if not isinstance(obj, get_user_model()):
ditto here. no need to check if create, because set as read only now.

2023-09-20 14:44 UTC, benjaminEwhite commented on apps/users/tests/test_serializers.py
> -class UserSerializerTest(APITestCase):
Got rid of another unit-test based test class.

2023-09-22 21:04 UTC, njharman requested changes
Django ORM N+1 is the worse. the Django solutions are good for simple and moderately hard case. Could never get it to work with (very) complex dynamic queries, where I could write "static" SQL np.  

PR comments, plus 

Should not DEV-2738 be added to PR Next Steps?

2023-09-25 12:26 UTC, benjaminEwhite commented on apps/api/views.py
> +        ]
75e2681f

2023-09-25 12:26 UTC, benjaminEwhite commented on apps/api/views.py
> +        return [f"organization__{x}" for x in self.org_onlies] + [f"revenue_programs__{x}" for x in self.rp_onlies]
75e2681f

2023-09-25 12:29 UTC, benjaminEwhite commented on apps/api/views.py
>          )
No logging in status quo, and i don't have any specific logging needs here at the moment, so am not going to add logs.

Did remove the unnecessary var assignment though.

f0d38f246f9

2023-09-25 17:43 UTC, njharman approved these changes
ship it!

2023-09-25 20:57 UTC, benjaminEwhite commented
@njharman mentioned the in-progress [DEV-4006](https://news-revenue-hub.atlassian.net/browse/DEV-4006) as a next step (it solves for DEV-2738). 4006 is non-blocking for this PR.

2023-09-29 04:08 UTC, x110dc requested changes

2023-09-29 14:56 UTC, benjaminEwhite commented on apps/organizations/serializers.py
> +    # of api/v1/users. That endpoint serializers orgs using organizaioninline serializer, then seriales
d5ce04bda15

2023-09-29 15:03 UTC, benjaminEwhite commented on apps/api/views.py
> +            # TODO: [DEV-3913] Change this to .organizations once that's no longer on user model
We can decide to bring removing the table into scope, but I was trying to keep it out. As long as there is user.organizations in our model (because of that through table), we can't set user.organizations here (I don't remember exact details, but it causes serialization to have an error, downstream).

2023-09-29 18:42 UTC, x110dc commented on apps/api/views.py
> +            # TODO: [DEV-3913] Change this to .organizations once that's no longer on user model
I don't think I phrased it well. If we're about to remove that table anyway, why write new code that uses that table. Since we're not using it then we won't miss it here (or anywhere), right?

2023-09-29 19:14 UTC, x110dc requested changes
Added another comment on the organization user.

2023-09-29 19:26 UTC, benjaminEwhite commented on apps/api/views.py
> +            # TODO: [DEV-3913] Change this to .organizations once that's no longer on user model
This code doesn't use the through table. 

The problem is that with the through table existing and being mapped to user.organizations on the model, it creates problems if we want to assign to directly assign user.organizations to be the queryset returned by .get_all_orgs_and_rps.  If we try to fake like these are the organizations returned by user.organizations, DRF serializer ends up with some sort of error (would have to get code in this state again to reproduce to see). 

The user object returned by this method gets serialized by AuthedUserSerializer, and it's a model serializer, and I think that conflicts with directly assigning value to organizations here. 

FWIW, this code gets moved/refined a bit in DEV-4006 because it was useful in more than one place, but in both cases, situation is same re: through table.

2023-09-29 19:31 UTC, x110dc approved these changes

2023-10-02 13:02 UTC, merged