DEV-3882: Create new SPA router for portal, implement magic link login
newsrevenuehub/rev-engine pull request #1244
Opened 2023-09-20 14:04 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

WIP

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-09-20 15:15 UTC, nrh-cklimas commented on spa/src/components/base/TextField/TextField.tsx
> +      background-color: white;
Should use theme.

2023-09-20 15:21 UTC, nrh-cklimas commented on spa/src/components/DashboardRouter.tsx
> +      <SentryRoute path={Object.values(ROUTES.PORTAL)} render={() => <TrackPageView component={PortalRouter} />} />
Prefer to move this into MainLayout--doesn't make sense to me at first glance to have this remain a child of DashboardRouter.

2023-09-20 20:50 UTC, GuiMend commented on spa/src/components/PortalRouter.tsx
> +function PortalRouter() {
> If we're repeating SegregatedStyles and DonationPageHeader on each route, let's make a PortalPage component that is responsible for that 

✅ 

> Can we get away without fetching the page here? It's hard for me to tell. I'd like to avoid it because it adds overhead to every pageload, e.g. people will get white screens while the request completes. Would much prefer to delegate it into routes, even if it means showing a loading spinner.

Asked for clarification on slack DM, but I don't think it's possible as we need the page fetched to get custom styles

> Any reason we can't use useContributionPage() to fetch the page?

We are getting the information from `/pages/live-detail/` in this page and in the `useContributionPage` hook we only fetch from `/pages/id` or `/pages/draft-detail`. If you mean update the hook to handle this, yes I can do that. But as it currently is, we cannot just plug&play.

2023-09-20 20:56 UTC, GuiMend commented on spa/src/components/DashboardRouter.tsx
> +      <SentryRoute path={Object.values(ROUTES.PORTAL)} render={() => <TrackPageView component={PortalRouter} />} />
If that's the case we would need to create an entirely new router as we have with `ContributorRouter`.

I agree that it doesn't sound right to have the `PortalRouter` inside `DashboardRouter`, but it would be true as well for  `ContributorRouter` (which is also inside Dashboard). It would be way simpler to move `ContributorRouter` to MainLayout.

I think this change would probably be outside the scope of this ticket. We could have a new ticket to solve some of the tech debt we have with our Routers or I do it all in here and we have an even larger ticket than what it is.

2023-09-21 19:07 UTC, nrh-cklimas commented on spa/src/components/PortalRouter.tsx
> +function PortalRouter() {
> We are getting the information from /pages/live-detail/ in this page and in the useContributionPage hook we only fetch from /pages/id or /pages/draft-detail. If you mean update the hook to handle this, yes I can do that. But as it currently is, we cannot just plug&play.

I see--I think it would be good in that case to move retrieval to a separate hook that doesn't return updatePage or deletePage, so it's clear that when you're using the unauthenticated endpoint, you can only GET. If you see a clean way to do that by modifying useContributionPage instead, I'm OK with that, but I fear it'd mean adding a lot of conditional statements across the app.

2023-09-21 19:08 UTC, nrh-cklimas commented on spa/src/components/base/TextField/TextField.tsx
> +      background-color: white;
Saw the update but grey4 is #f9f9f9, not white, so I'm confused.

2023-09-21 19:13 UTC, nrh-cklimas commented on spa/src/components/DashboardRouter.tsx
> +      <SentryRoute path={Object.values(ROUTES.PORTAL)} render={() => <TrackPageView component={PortalRouter} />} />
I agree, I don't think we should touch anything in ContributorRouter in this PR.

I don't fully understand what you mean by "creating an entirely new router". What does that entail, beyond wrapping it in RouterSetup? I'm looking at DonationPageRouter as a model we could use.

2023-09-22 12:35 UTC, GuiMend commented on spa/src/components/base/TextField/TextField.tsx
> +      background-color: white;
My mistake. I was talking to Rachel and grey4 is the background color for the new portal and I added it here as well

2023-09-22 12:38 UTC, GuiMend commented on spa/src/components/DashboardRouter.tsx
> +      <SentryRoute path={Object.values(ROUTES.PORTAL)} render={() => <TrackPageView component={PortalRouter} />} />
> I don't fully understand what you mean by "creating an entirely new router". What does that entail, beyond wrapping it in RouterSetup? I'm looking at DonationPageRouter as a model we could use.

You are right, I didn't mean it as a lot of work, I just meant that it would keep on following the pattern of having multiple different router components instead of only one (which I was trying to implement when I added the portal routes inside the main router). I'm not against making your suggestion, will do it now 👍

2023-09-22 16:07 UTC, GuiMend commented on spa/src/components/PortalRouter.tsx
> +function PortalRouter() {
Done that 👍

2023-09-25 14:15 UTC, nrh-cklimas requested changes

2023-09-25 14:15 UTC, nrh-cklimas commented on spa/src/components/donationPage/DonationPageHeader/DonationPageHeader.tsx
I'd like to avoid changing this component because there are effects to live contribution pages and widens our QA scope. What I'd suggest is we conditionally render DonationPageHeader in PortalPage, only after the page has been fetched.

If this causes an ugly layout shift or if the behavior is different than the contribution page--I'm not sure if the placeholder NRE logo is only meant to appear while the page is loading, or if the page has no custom image set--then I think a separate component is better to use here.

2023-09-25 14:15 UTC, nrh-cklimas commented on spa/src/components/portal/PortalEntry.tsx
> +              <br />
This extra spacing doesn't match Figma.

2023-09-25 14:15 UTC, nrh-cklimas commented on spa/src/components/portal/PortalEntry.tsx
> +                  <TextField
Let's add `type="email"` to get nicer browser UX.

2023-09-25 14:15 UTC, nrh-cklimas commented on spa/src/components/portal/PortalEntry.styled.ts
> +  max-width: 693px;
This doesn't seem to be rendering at 693px in practice--for me in the review app, I got 633px instead.

2023-09-25 19:59 UTC, GuiMend commented on spa/src/components/donationPage/DonationPageHeader/DonationPageHeader.tsx
From what I understood the default NRE logo should appear if no custom styles.
I removed it from DonationPageHeader 👍

2023-09-25 20:14 UTC, GuiMend commented on spa/src/components/portal/PortalEntry.styled.ts
> +  max-width: 693px;
The padding was taking space from the 693px. Thanks for catching that.

2023-09-25 21:51 UTC, nrh-cklimas commented on spa/src/components/portal/PortalEntry.tsx
> +              <br />
I see an extra line break in the review app.
<img width="719" alt="Screenshot 2023-09-25 at 5 51 11 PM" src="https://github.com/newsrevenuehub/rev-engine/assets/112435785/91da5d49-680a-461f-87a9-aacb83ed46c1">

2023-09-26 17:29 UTC, nrh-cklimas approved these changes

2023-10-03 19:17 UTC, merged