DEV-3960 | Add language to donation page model modify page limit validation to account for language
newsrevenuehub/rev-engine pull request #1245
Opened 2023-09-20 16:16 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-09-20 16:19 UTC, benjaminEwhite commented on apps/pages/models.py
> +    elements = models.JSONField(null=True, blank=True, default=defaults.get_default_page_elements)
FYI, i sorted the model attributes alphabetically so easier to find what you're looking for.

The only non-sorting change here is that we add `locale` on line 60.

2023-09-20 18:21 UTC, benjaminEwhite commented on apps/pages/tests/test_views.py
> +        for i in range((limit := rp.organization.plan.publish_limit)):
Looks like the test in the original was actually testing around page limit, not publish limit :( notwithstanding the test name.

2023-09-26 19:42 UTC, njharman requested changes
one uncovered method

2023-09-26 19:42 UTC, njharman commented on apps/pages/serializers.py
> +                "DonationPageFullDetailSerializer.validate_publish_limit raising ValidationError because org (%s) has reached its publish limit for %s",
log, not big deal, seems weird grammer?   "... publish limit for English".   

- "...English publish limit"
- "publish limit for English pages"

2023-09-26 19:42 UTC, njharman commented on apps/pages/serializers.py
> +        return value
Uncovered by unittests

2023-09-26 19:43 UTC, njharman commented on apps/pages/serializers.py
>          ).count() + 1 > (pl := org.plan.page_limit):
We log publish limit, should we not log here too?

2023-09-27 13:16 UTC, benjaminEwhite commented on apps/pages/serializers.py
> +        return value
Would help if I spelled val**_i_**date correctly 🤦

2023-09-27 13:26 UTC, benjaminEwhite commented on apps/pages/serializers.py
> +        return value
f6a0df48181

2023-09-27 13:30 UTC, benjaminEwhite commented on apps/pages/serializers.py
>          ).count() + 1 > (pl := org.plan.page_limit):
424d225494a

2023-09-27 13:31 UTC, benjaminEwhite commented on apps/pages/serializers.py
> +                "DonationPageFullDetailSerializer.validate_publish_limit raising ValidationError because org (%s) has reached its publish limit for %s",
9176b71e9150

2023-09-28 00:05 UTC, njharman approved these changes
There's two branches and one raise that is uncovered.  I'm not super stressed about that. If you are , you can fix it. Otherwise, ship it!

2023-09-28 00:05 UTC, njharman commented on apps/pages/serializers.py
> +            locale=locale.code,
I don't think it matters.  Mentioning in case you expected otherwise.

This branch is always taken, the if on #342 is always true.

2023-09-28 00:05 UTC, njharman commented on apps/pages/serializers.py
> +            raise serializers.ValidationError({"locale": f"Invalid locale: {value}"})
Uncovered raise. if on #284 was never true.

2023-09-28 13:24 UTC, benjaminEwhite commented on apps/pages/serializers.py
> +            raise serializers.ValidationError({"locale": f"Invalid locale: {value}"})
56b8d3cc2

2023-09-28 23:41 UTC, x110dc approved these changes
LGTM.

2023-09-29 17:26 UTC, merged