[WIP] initial proof of concept to try in review app
newsrevenuehub/rev-engine pull request #1248
Opened 2023-09-22 19:25 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-09-29 15:50 UTC, benjaminEwhite commented on apps/api/serializers.py
> -class TokenObtainPairCookieSerializer(TokenObtainPairSerializer):
This change happens in DEV-3909, which has been reviewed separately.

2023-09-29 18:12 UTC, benjaminEwhite commented on spa/src/components/settings/Organization/Organization.tsx
> +    () => user?.revenue_programs?.filter((rp) => rp.organization === currentOrganization?.id),
We just return org as an ID now, not as a nested object.

2023-10-02 18:05 UTC, njharman requested changes
Little harder to follow these changes.  comments, change requests in comments.

haven't checked coverage, I have no more time today; will have to do in rereview.

2023-10-02 18:05 UTC, njharman commented on apps/users/views.py
> -            return
Are really email-less users no longer possible?

Sorry, lots of deletes, small changes; it's hard to follow everything.

2023-10-03 15:01 UTC, benjaminEwhite commented on apps/organizations/views.py
> -    if not request.user.roleassignment.can_access_rp(revenue_program):
Backed out of this change, which is a nice to have, but need not be in scope.

4d10661c6f7f

Created a follow up ticket to standardize use of user.permitted_revenue_programs, user.permitted_organizations, user.active_flags (and one we should create, user.permitted_styles) across app.

2023-10-03 15:02 UTC, benjaminEwhite commented on apps/pages/serializers.py
> +    Note that at present, pagiation is not enabled for this serializer, and superusers and hub
d3abe335f

2023-10-03 15:12 UTC, benjaminEwhite commented on apps/pages/views.py
> +        # serializer defines its own fields that can be passed to .only() in order to make queries mroe performant
Code comment removed in 3887ecc

2023-10-03 16:01 UTC, benjaminEwhite commented on apps/users/views.py
> -            return
FWIW, the reason this even came in scope was that I had a single line in apps/users/views.py that was untested, and I was tempted to get to 100%.

2023-10-03 16:30 UTC, nrh-cklimas requested changes

2023-10-03 16:35 UTC, benjaminEwhite commented on spa/src/hooks/useContributionPage/useContributionPage.types.ts
> +export interface ContributionPageRevenueProgram extends Omit<RevenueProgram, 'organization'> {
ccc04b61eedd

2023-10-03 16:39 UTC, benjaminEwhite commented on spa/src/components/settings/Organization/Organization.tsx
> +    () => user?.revenue_programs?.filter((rp) => rp.organization === currentOrganization?.id),
That makes sense.

I pushed up 67d2008eb8

@nrh-cklimas can you provide detail on expanded QA scope?

2023-10-03 17:56 UTC, nrh-cklimas commented on spa/src/components/settings/Organization/Organization.tsx
> +    () => user?.revenue_programs?.filter((rp) => rp.organization === currentOrganization?.id),
@benjaminEwhite I mean we'd need to test this Organization settings page with org admin and RP admin, which currently isn't part of the testing instructions. It's not a lot, though.

2023-10-03 17:56 UTC, nrh-cklimas approved these changes

2023-10-03 18:42 UTC, benjaminEwhite commented on spa/src/components/settings/Organization/Organization.tsx
> +    () => user?.revenue_programs?.filter((rp) => rp.organization === currentOrganization?.id),
Updated testing instructions accordingly

2023-10-06 23:20 UTC, njharman approved these changes

2023-10-18 03:09 UTC, x110dc requested changes

2023-10-18 03:09 UTC, x110dc commented on pyproject.toml
> +dateparser = "^1.1.8"
It looks like this is only used in one test right? Shouldn't it be a dev dependency then?

2023-10-18 12:41 UTC, benjaminEwhite commented on pyproject.toml
> +dateparser = "^1.1.8"
Took care of this when merging in main here: f26b1bcbb

2023-10-18 16:35 UTC, x110dc approved these changes

2023-10-18 16:45 UTC, merged