DEV-3824: Re-enable swag element
newsrevenuehub/rev-engine pull request #1249
Opened 2023-09-22 19:49 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

- Re-enables swag elements in contribution pages and updates the editor panel to match new designs.
- Updates the element as displayed in a contribution page to send the correct encoded value for `swag_choices`.
- Replaces `validateInputPositiveFloat` with `parseFloatStrictly`.

#### Why are we doing this? How does it help us?

- Unblocks rev engine migration for some clients.
- re: `parseFloatStrictly`, I needed to allow the swag contribution threshold to be set to 0 but otherwise filter out non-numeric values. Refactoring to just parse the number meant we didn't have to create a whole other function for this.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

Going to add these after design review.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

Yes, we re-enabled the swag element.

#### Have automated unit tests been added? If not, why?

Yes.

#### How should this change be communicated to end users?

Should reach out to clients who would make use of this.

#### Are there any smells or added technical debt to note?

No.

#### Has this been documented? If so, where?

No.

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-3824

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No.

2023-09-26 14:37 UTC, GuiMend approved these changes
LGTM @nrh-cklimas

2023-09-26 14:50 UTC, GuiMend requested changes
1) Breaking page
![image](https://github.com/newsrevenuehub/rev-engine/assets/9381325/1dd263bf-d8a5-4bbd-ac74-da39696b78f5)
When trying to edit "Contributor Benefits" the page breaks. (Testing with this donation page: https://dev-3824.revengine-review.org/edit/pages/54/ ) 
Btw: I removed and re-added the block and the error stopped occurring. (Might be an outdated config issue, but I didn't dig into too much.)

2) Updates not showing on preview:
After making changes to the element and clicking "update" nothing happens:
https://dev-3824.revengine-review.org/edit/pages/67/
(Even after saving the page it still doesn't show the changes)
![image](https://github.com/newsrevenuehub/rev-engine/assets/9381325/818c05e5-e58f-451c-9e9c-c7c9aa6bcbf0)

3) Validation is working, but max chars doesn't show error, it only stops the user from entering more chars
![image](https://github.com/newsrevenuehub/rev-engine/assets/9381325/a264e130-8b96-4524-b47f-92ef0cfb107b)
Also, perhaps make the text break line and wrap so that we don't get the scrollbar?
![image](https://github.com/newsrevenuehub/rev-engine/assets/9381325/9982c93d-927d-4407-b926-aafe49aca458)

2023-09-26 21:01 UTC, nrh-cklimas commented
@GuiMend thanks for the review!

1. I looked at that page and the element content is totally empty. What I'd like to do is since we have very few if any pre-existing swag elements in prod, would like to address individually instead of writing conditions around the element missing all data. It's something I'll flag in QA though.

2. That's a side effect of the swag threshold--if you change the contribution amount in the page preview to hit the threshold, you should see the options.

3. Talked to Rachel and she is OK with keeping the field max length as our validation method here. I did add a fix for the scrolling caused by long option names in 2bdddc9982f27d191ac29528cba508b30120baf7.

2023-09-26 21:22 UTC, GuiMend approved these changes
👍

2023-09-27 14:36 UTC, benjaminEwhite reviewed
Saw one place that there's some commented code that could be removed.

2023-09-27 14:36 UTC, benjaminEwhite commented on spa/src/components/pageEditor/editInterface/pageElements/addElementModal/AddElementModal.tsx
> -  // }, [page?.plan?.page_elements, page?.plan?.sidebar_elements]);
Get rid of this?

2023-09-27 15:08 UTC, nrh-cklimas commented on spa/src/components/pageEditor/editInterface/pageElements/addElementModal/AddElementModal.tsx
> -  // }, [page?.plan?.page_elements, page?.plan?.sidebar_elements]);
I did? :)

2023-10-02 18:33 UTC, merged