DEV-3350: Move log detail to debug level
newsrevenuehub/rev-engine pull request #1255
Opened 2023-09-28 19:15 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

I did a search in our code for `logger.info()` calls and shifted calls that appeared to be logging dictionaries into `logger.debug()`. I kept the `logger.info()` calls around but shortened what they logged.

#### Why are we doing this? How does it help us?

Makes logs less verbose and helps with Papertrail quotas.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

Yes.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No.

#### Have automated unit tests been added? If not, why?

No, because this affects logging only.

#### How should this change be communicated to end users?

Not needed.

#### Are there any smells or added technical debt to note?

No.

#### Has this been documented? If so, where?

No.

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-3350

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No.

2023-09-29 15:46 UTC, benjaminEwhite reviewed
Overall looks good. Will expand on this in JIRA, but should coordinate with Leo re: standardization of logging approach and prepending function names (or not).

2023-09-29 18:27 UTC, nrh-cklimas commented
@benjaminEwhite I tweaked the log messages in 1845314b1fd31a87e7b3d1939b5e9d68b4de6007.

2023-10-03 15:29 UTC, benjaminEwhite approved these changes

2023-10-06 23:44 UTC, njharman requested changes
Couple minor comments. Request a look, no need for rereview.

Also was this limited to just those apps.
I seem similar logs 

1. "request.data" users/views.py:297
2. "data" common/hookdeck.py:35
3. "request.data" api/views.py:155, 160, 213
4. "template.data" emails/tasks.py:207
5. "payload" organizations/views.py:208
6. "validated_data contributions/serilizsers.py:687
stopped looking here

2023-10-06 23:44 UTC, njharman commented on apps/organizations/serializers.py
> +        logger.info("Updating RP %s", instance)
verifying "instance" is something like django model instance and will just output str() or repr() and not something large, right?

2023-10-06 23:44 UTC, njharman commented on apps/organizations/tasks.py
>          request_data | {"code": "REDACTED", "client_secret": "REDACTED"},
clever

2023-10-06 23:44 UTC, njharman commented on apps/organizations/tasks.py
> +    logger.info("making a request to Mailchimp")
I question the value of "making a request" log at .info level...

2023-10-10 14:01 UTC, nrh-cklimas commented on apps/organizations/serializers.py
> +        logger.info("Updating RP %s", instance)
I checked this class (and others) and they have `__str__` methods, so I believe so.

2023-10-10 14:04 UTC, nrh-cklimas commented on apps/organizations/tasks.py
> +    logger.info("making a request to Mailchimp")
Removed in 239fafd5dc696a5bbd3dd0d55497e00b78a64476

2023-10-10 19:18 UTC, njharman approved these changes
Ship it!

2023-10-12 17:23 UTC, merged