DEV-3955: Add localization to stripe modal components
newsrevenuehub/rev-engine pull request #1258
Opened 2023-10-02 17:39 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
- Adds support for localization in components related to stripe modal.
- Updates helper functions to also use localization
- Fixed all test that were affected by localization
 
#### Why are we doing this? How does it help us?
We want to add Spanish support to our platform

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
yes

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
no

#### Have automated unit tests been added? If not, why?
yes

#### How should this change be communicated to end users?
n/a
#### Are there any smells or added technical debt to note?
no
#### Has this been documented? If so, where?
n/a
#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3955
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
https://news-revenue-hub.atlassian.net/browse/DEV-3153

2023-10-03 14:03 UTC, nrh-cklimas commented on spa/src/components/donationPage/FinishPaymentModal/ContributionDisclaimer.tsx
>  function ContributionDisclaimer({ formattedAmount, interval }: ContributionDisclaimerProps) {
This component needs to be refactored to use translation keys as-is instead of concatenations of partially-translated strings, as this will become problematic once we are dealing with languages whose sentence structure differs from English.

1. First sentence, with links to privacy policy and terms & conditions. The end result should look something like this:

```tsx
<Trans
  i18nKey="donationPage.contributionDisclaimer.policyAgreement"
  components={[
    <Link href={t('common.urls.privacyPolicy')} target="_blank" />,
    <Link href={t('common.urls.tsAndCs')} target="_blank" />
  ]}
/>
```

with the translation key looking like this (wrapping lines here for readability):

```
"policyAgreement": "By proceeding with this transaction, you agree to our <0>privacy policy</0>
and <1>terms and conditions</1>.",
```

See [docs on the Trans component](https://react.i18next.com/latest/trans-component#interpolation) for details on how this works.

2. Second sentence, which says the user authorizes payment with a particular amount. This should have three keys:

- `donationPage.contributionDisclaimer.paymentAgreement.oneTime`
- `donationPage.contributionDisclaimer.paymentAgreement.monthly`
- `donationPage.contributionDisclaimer.paymentAgreement.annually`

Values should look like this:

```
Additionally, by proceeding with this transaction, you're authorizing today's payment of
<0>{{amount}} $1 to be processed on or adjacent to {{date}}.</0>.
```

```
Additionally, by proceeding with this transaction, you're authorizing today's payment of
<0>{{amount}}, to be processed on or adjacent to the {{billDay}} of the month until you
cancel.</0>
```

```
Additionally, by proceeding with this transaction, you're authorizing today's payment of
<0>{{amount}}, to be processed on or adjacent to {{billDate}} yearly until you cancel.</0>
```

And use `components` on `<Trans>` to pass a `<strong>` HTML tag. The monthly string will also need to use [ordinals](https://www.i18next.com/translation-function/plurals#ordinal-plurals) to get the correct `1st`, `2nd`, and so on.

2023-10-03 14:08 UTC, nrh-cklimas commented on spa/src/components/paymentProviders/stripe/stripeFns.ts
> +    throw new Error(i18n.t('stripeFns.missingArgumentError', { error: Object.keys(missingParams).join(', ') }));
Is this going to be visible to a user? If not, it doesn't need to be localized.

2023-10-03 14:14 UTC, nrh-cklimas commented on spa/src/test-utils.tsx
> +i18n.use(initReactI18next).init({
I'm confused about the approach on testing. We should strive to make this something we don't need to mock in individual tests, but I see mocks in many of components, and they seem to be doing it in different ways. I would prefer that we have no i18next mocks in test files at all to testing on English strings.

2023-10-03 14:15 UTC, nrh-cklimas commented on spa/src/utilities/parseFrequency.ts
> +import i18n from 'i18next';
This needs to import the instance we export in `spa/src/i18n.ts` instead.

2023-10-03 19:20 UTC, GuiMend commented on spa/src/test-utils.tsx
> +i18n.use(initReactI18next).init({
Discussion resolved in slack. We will have a global mock for i18n to ensure we can test params being passed

2023-10-03 19:32 UTC, GuiMend commented on spa/src/components/paymentProviders/stripe/stripeFns.ts
> +    throw new Error(i18n.t('stripeFns.missingArgumentError', { error: Object.keys(missingParams).join(', ') }));
I think it is user facing. I couldn't find the component wrapped in our `GenericErrorBoundary` that shows a generic error instead of the thrown one.

2023-10-03 19:33 UTC, GuiMend commented on spa/src/components/donationPage/FinishPaymentModal/ContributionDisclaimer.tsx
>  function ContributionDisclaimer({ formattedAmount, interval }: ContributionDisclaimerProps) {
I believe I managed to fit both items into 1 translation component. Let me know if it's ok or if you'd still like me to update to your suggestion.

2023-10-03 19:41 UTC, GuiMend commented on spa/src/components/paymentProviders/stripe/stripeFns.ts
> +  return i18n.t('stripeFns.paymentElementButtonText', {
I think we can leave it. It had great testing around it

2023-10-03 19:41 UTC, GuiMend commented on spa/src/components/donationPage/FinishPaymentModal/ContributionDisclaimer.styled.ts
> +  text-transform: lowercase;
Not needed anymore

2023-10-03 20:43 UTC, nrh-cklimas requested changes

2023-10-03 20:43 UTC, nrh-cklimas commented on spa/public/static/locales/en/translation.json
> +    "conjunctions": {
This key can now be removed.

2023-10-03 20:43 UTC, nrh-cklimas commented on spa/public/static/locales/en/translation.json
> +    "urlLabels": {
This key can now be removed.

2023-10-03 20:43 UTC, nrh-cklimas commented on spa/src/components/donationPage/FinishPaymentModal/ContributionDisclaimer.tsx
>  function ContributionDisclaimer({ formattedAmount, interval }: ContributionDisclaimerProps) {
This is looking better but I think trying to put a translation call into the `values` on line 54 is still problematic--we can take this shortcut in English but I'm not confident we'll be able to do it in other languages. I'm good with using named component placeholders (`privacy`, `terms`) instead of indexed ones.

2023-10-03 20:43 UTC, nrh-cklimas commented on spa/src/components/paymentProviders/stripe/stripeFns.ts
> +    throw new Error(i18n.t('stripeFns.missingArgumentError', { error: Object.keys(missingParams).join(', ') }));
OK, good call then.

2023-10-03 20:43 UTC, nrh-cklimas commented on spa/src/test-utils.tsx
> +i18n.use(initReactI18next).init({
I think now that we have the global mocks, the diff on this file can be reverted completely--not needed anymore.

2023-10-03 20:43 UTC, nrh-cklimas commented on spa/src/components/paymentProviders/stripe/stripeFns.ts
> +  return i18n.t('stripeFns.paymentElementButtonText', {
OK.

2023-10-03 20:43 UTC, nrh-cklimas commented on spa/src/utilities/parseFrequency.ts
> +import i18n from '../i18n';
Nitpick: can just be `'i18n'`

2023-10-03 20:43 UTC, nrh-cklimas commented on spa/src/components/paymentProviders/stripe/stripeFns.ts
> +import i18n from '../../../i18n';
Nitpick: can just be `'i18n'`

2023-10-04 14:33 UTC, nrh-cklimas commented on spa/src/components/donationPage/FinishPaymentModal/ContributionDisclaimer.tsx
> +      // TODO: Add locale to "format" when we have translations
I think this could be done now, since we don't need a translation, we just need a locale code. https://news-revenue-hub.atlassian.net/browse/DEV-3960 added this.

If it would widen scope too much, let's create a followup story specifically for date formatting.

2023-10-04 14:34 UTC, nrh-cklimas approved these changes

2023-10-05 00:00 UTC, nrh-cklimas commented on spa/src/components/donationPage/FinishPaymentModal/ContributionDisclaimer.tsx
> +      // TODO: Add locale to "format" when we have translations
Followup ticket sounds good to me, then.

2023-10-05 17:06 UTC, GuiMend commented on spa/src/components/donationPage/FinishPaymentModal/ContributionDisclaimer.tsx
> +      // TODO: Add locale to "format" when we have translations
https://news-revenue-hub.atlassian.net/browse/DEV-4105

2023-10-10 16:26 UTC, nrh-cklimas requested changes

2023-10-10 16:26 UTC, nrh-cklimas commented on spa/src/components/donationPage/DonationPage.js
> +                    locale={page?.locale}
`page` should never be undefined if we've gotten this far. It's a little hard to see what the right move here exactly is since this is a JS component, but I think the right high-level behavior is to throw an error if we think it's time to show the modal but we don't have page--just not sure where to put that logic.

2023-10-11 15:13 UTC, GuiMend commented on spa/src/components/donationPage/DonationPage.js
> +                    locale={page?.locale}
You are right. Page won't be undefined. It was a habit of adding the optional chaining.

2023-10-11 20:41 UTC, nrh-cklimas approved these changes

2023-10-12 18:26 UTC, merged