DEV-4069: Remove name and slug from readonly_fields for RP admin
newsrevenuehub/rev-engine pull request #1273
Opened 2023-10-12 15:00 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

- Removes `name` and `slug` from the read-only fields for an RP in Django admin, and `name` from the read-only field of organizations in Django admin.
- Fixes an issue with pre-commit where it will scan a virtualenv created by direnv and bog down for a long time.

#### Why are we doing this? How does it help us?

- Re-enables creation of an RP via admin, and allows further editing in the admin.
- Fixes a local dev issue.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

Yes.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No.

#### Have automated unit tests been added? If not, why?

No--if we think it's useful, I could add one that asserts on the configuration.

#### How should this change be communicated to end users?

n/a

#### Are there any smells or added technical debt to note?

No.

#### Has this been documented? If so, where?

No.

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-4069

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No.

2023-10-12 19:52 UTC, benjaminEwhite approved these changes
Code change looks good to me. Looks like because we have field definition in model set to `editable=False` we don't need to manage this field in django admin.

2023-10-16 21:11 UTC, benjaminEwhite requested changes
Had a question about one of the to-be-removed readonly fields, and a suggestion for test.

2023-10-17 13:50 UTC, nrh-cklimas commented on apps/organizations/admin.py
> +    readonly_fields = ["mailchimp_server_prefix", "mailchimp_list_id"]
It's AC 8 of the story.

2023-10-17 19:18 UTC, nrh-cklimas commented on apps/organizations/tests/test_admin.py
> +        assert save_spy.call_args.kwargs == {}
👍 8e514abb8cece31cc21924d82ba1dabf5159f653

2023-10-17 21:14 UTC, benjaminEwhite approved these changes

2023-10-18 03:14 UTC, x110dc requested changes

2023-10-18 03:14 UTC, x110dc commented on pyproject.toml
> +exclude_dirs = ["tests", ".direnv"]
This unrelated change should be called out in the "What's this PR do?" section of the PR description. Alternately it could be removed here and and handled separately.

2023-10-20 03:42 UTC, x110dc approved these changes

2023-10-20 14:20 UTC, merged