DEV-4130 | mock implementation of new contributor contributions endpoint for new contributor portal
newsrevenuehub/rev-engine pull request #1274
Opened 2023-10-12 15:40 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-10-12 17:59 UTC, nrh-cklimas requested changes

2023-10-12 17:59 UTC, nrh-cklimas commented on apps/contributions/views.py
> +def get_mock_contributor_contributions_results(
I appreciate the idea behind this in that it'll give us all kinds of different data, but I think this might be problematic in practice. Because react-query re-fetches at various intervals, during testing we could see the UI change completely on us midstream, because I think every time I hit the endpoint, I'll get totally different results. Same for testing filtering/sorting--each resultset will be internally consistent, but will be confusing to test.

I think just a static set of data would work better here, or if you want to get fancy here, maybe use the contributor ID as the random seed with faker.

2023-10-12 18:39 UTC, benjaminEwhite commented on apps/contributions/views.py
> +def get_mock_contributor_contributions_results(
That makes sense. I stored output from initial implementation as JSON fixture. We now load that fixture and then reserialize it (so we have a better guarantee that our serializer upholds contract).

f2b07581f4e4

2023-10-12 20:47 UTC, nrh-cklimas approved these changes

2023-10-18 03:34 UTC, x110dc approved these changes
Just one comment.

2023-10-18 03:34 UTC, x110dc commented on apps/contributions/serializers.py
> +class ContributionAgreementSerializer(serializers.Serializer):
I'm not a fan of this name. I think it's confusing. But I guess it's just temporary?

2023-10-18 12:51 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +class ContributionAgreementSerializer(serializers.Serializer):
I would like a way to systematically distinguish between "common parlance" of what a contribution means (which is a single instance of someone giving money) vs. the intention to give on an ongoing basis. The latter is not itself a "contribution" even though that's how we've been referring to it in our system. 

To my mind, this name captures exactly what a user is doing when making a one time or recurring gift. In both cases, they're agreeing to send money to the org, either once or recurrently.

If there's a more appealing way to refer to this, I'm all ears, but I would like to have the name we choose reflect this nuance (in a way that, say, `ContributionSerializer` does not).

2023-10-19 18:03 UTC, merged