DEV-4062: Remove locale considerations from page limits
newsrevenuehub/rev-engine pull request #1279
Opened 2023-10-16 14:08 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

Removes locale calculations from page limits. It essentially reverts that part of https://news-revenue-hub.atlassian.net/browse/DEV-3960 / https://github.com/newsrevenuehub/rev-engine/pull/1245.

#### Why are we doing this? How does it help us?

Updated requirements.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

TBD

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No.

#### Have automated unit tests been added? If not, why?

Updated existing tests.

#### How should this change be communicated to end users?

n/a

#### Are there any smells or added technical debt to note?

No.

#### Has this been documented? If so, where?

No.

#### What are the relevant tickets? Add a link to any relevant ones.

-https://news-revenue-hub.atlassian.net/browse/DEV-4062
- https://news-revenue-hub.atlassian.net/browse/DEV-3960

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No.

2023-10-17 15:07 UTC, benjaminEwhite approved these changes
LGTM. FWIW, you could update the PR description section about the testing instructions to be "Yes", since they are on ticket.

2023-10-18 19:03 UTC, njharman requested changes
All cuts, did not check coverage.

2023-10-18 19:03 UTC, njharman commented on apps/pages/tests/test_serializers.py
> +    def test_plan_page_limits_are_respected(self, plan, hub_admin_user):
DonationPage still has a locale attribute. Assuming because localized pages are still valid and not just oversight.

These page_limit and publish_limit tests should include some Pages in different locales.  To show that 2x en, 2x es is error with 3 page limit now, where before it would be fine. [total pages vs total pages per locale]

Ideally tests with all en, all es, and mix of en/es.

2023-10-19 14:30 UTC, nrh-cklimas commented on apps/pages/tests/test_serializers.py
> +    def test_plan_page_limits_are_respected(self, plan, hub_admin_user):
Took a stab at this in d4a12ec888e8e2d1403ee6f78b21eef98a18d786. It doesn't test all locale combinations exhaustively (I couldn't figure out a good way to express "en and es existing page, try to publish en") though. It does just "en and en existing, publish en or es".

2023-10-19 14:35 UTC, nrh-cklimas commented on apps/pages/serializers.py
> +                {"non_field_errors": [f"Your organization has reached its limit of {pl} page{'s' if pl > 1 else ''}"]}
I created https://news-revenue-hub.atlassian.net/browse/DEV-4168 as a followup.

2023-10-19 23:22 UTC, njharman approved these changes
Ship it

2023-10-19 23:22 UTC, njharman commented on apps/pages/tests/test_serializers.py
> +    def test_plan_page_limits_are_respected(self, plan, hub_admin_user):
Good enough.

2023-10-23 13:29 UTC, merged