Nrh 180  sidebar blurb
newsrevenuehub/rev-engine pull request #128
Opened 2021-08-12 21:56 UTC by JeremyGibson

#### What's this PR do?
Add the ability to create sidebar blurbs. Currently the supported blocks are RichText and Images.  Once #116 is merged we can add in benefit levels.

#### How should this be manually tested?

1. Go to any page, and open up the page editor.
2. You will note a new tab `Sidebar`
3. Open `Sidebar` and begin adding elements
4. Reorder as you wish
5. Close the editor and save the page
6. Note the sidebar is displayed as constructed. 

#### Do any changes need to be made before deployment to staging? production? (adding environment variables, for example)?
No.

2021-08-13 20:10 UTC, michael-caktus commented
This rocks, I love this feature.

2021-08-13 20:11 UTC, michael-caktus commented
Oddly, the images are saving, but from `MediaImage.create_from_request` I'm getting `IntegrityError: null value in column "height" violates not-null constraint`

2021-08-13 20:12 UTC, michael-caktus commented
Also, one thing we should sort out now is the props violation in the Image block-- 
<img width="1369" alt="Screen Shot 2021-08-13 at 4 06 41 PM" src="https://user-images.githubusercontent.com/52928110/129413521-1e3595ee-1df2-4871-9823-64879ea22226.png">

We were probably a bit too eager to make that required, since we're allowing the data-url to be used in edit mode, pre-save.

2021-08-13 20:19 UTC, michael-caktus requested changes
See comments in conversation section.

2021-08-13 20:37 UTC, JeremyGibson commented
> Oddly, the images are saving, but from `MediaImage.create_from_request` I'm getting `IntegrityError: null value in column "height" violates not-null constraint`

Hmmm. That is odd. I saw that in tests when I wasn't passing a good image object to the constructor.

2021-08-16 12:29 UTC, michael-caktus commented on spa/src/components/donationPage/DonationPage.js
> +    debugger;
👆🚨

2021-08-16 16:08 UTC, merged