DEV-3956: Add localization to Contribution page components
newsrevenuehub/rev-engine pull request #1280
Opened 2023-10-16 17:24 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
Adds localization to Contribution page components

#### Why are we doing this? How does it help us?
Support Spanish language

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
yes

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
n/a

#### Have automated unit tests been added? If not, why?
yes

#### How should this change be communicated to end users?
n/a

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
n/a

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3956

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
Parent ticket: https://news-revenue-hub.atlassian.net/browse/DEV-3153

2023-10-17 13:25 UTC, nrh-cklimas requested changes

2023-10-17 13:25 UTC, nrh-cklimas commented on spa/src/components/donationPage/pageContent/DDonorAddress.tsx
> +                  sign: showComplement ? '-' : '+'
How would you feel about turning the +/- into an icon so we don't have to interpolate? It feels iffy to me because it's not really part of the text per se. I asked Rachel about it and she is open to it. I don't consider this a must, more a possible improvement.

2023-10-17 13:36 UTC, GuiMend commented on spa/src/components/donationPage/pageContent/DDonorAddress.tsx
> +    let result = t('donationPage.dDonorAddress.stateLabel.state');
Sure, I will do that. I thought of doing it the way you suggested from the start, but I changed my mind before finishing the PR

2023-10-17 18:12 UTC, GuiMend commented on spa/src/components/donationPage/pageContent/DAmount.tsx
> +DAmount.displayName = i18n.t('donationPage.dAmount.contributionAmount');
Talked over on slack. Removed 👍

2023-10-17 18:21 UTC, GuiMend commented on spa/src/components/donationPage/pageContent/DDonorAddress.tsx
> +                  sign: showComplement ? '-' : '+'
I'm cool with it being an icon, but as of now, this really looks more like a string than a button and if we add the icon it would probably be a bit weird. Perhaps make a change in the entire button?

<img width="309" alt="image" src="https://github.com/newsrevenuehub/rev-engine/assets/9381325/c9f38535-3d0e-4fdc-a23a-f3435b1412be">

2023-10-17 20:10 UTC, GuiMend commented on spa/src/components/donationPage/pageContent/DDonorAddress.tsx
> +                  sign: showComplement ? '-' : '+'
I just now saw the comment on JIRA. Fixed it 👍

2023-10-18 21:10 UTC, nrh-cklimas approved these changes

2023-10-19 14:25 UTC, merged