DEV-3207: add a request ID to the logs
newsrevenuehub/rev-engine pull request #1285
Opened 2023-10-18 20:34 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
- Adds request_id to celery logs
- Adds configuration to make request_id enabled for services that can’t generate the X-Request-Id header at the web server level (GKE/Google)

#### Why are we doing this? How does it help us?
- Adds request_id to missing places, helps debugging/tracking issues.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
n/a

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
no

#### Have automated unit tests been added? If not, why?
n/a

#### How should this change be communicated to end users?
n/a

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
n/a

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3207

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
Yes, https://news-revenue-hub.atlassian.net/browse/ITS-2125

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2023-10-20 15:49 UTC, benjaminEwhite requested changes

2023-10-20 15:49 UTC, benjaminEwhite commented on apps/common/__init__.py
> +setup_logs()
If i'm reading `setup_logs` correctly, this function is not about setting up logs in general, but specifically about setting up logging handlers for Celery tasks.

This code gets invoked in apps.common.__init__.py, which means it will run the first time a Python session executes code that imports from apps.common (and not on subsequent runs imports in the sesion).

But since this function is narrowly about handling the case of code running in Celery task (not in web app), I'm not sure we need to be running it in the general case of importing from apps.common.

I wonder if we might instead be able to call this (and possibly define it) in `revengine.celery.py`.  The function name could stay the same (and within that module's name space, it would better align with its behavior of narrowly setting up log handling for celery).

If we call `setup_logs` at module level in `revengine.celery.py`, I believe it would execute when a Celery worker process first starts.

2023-10-20 15:49 UTC, benjaminEwhite commented on apps/common/logger.py
> +import contextvars
See above. I think this code maybe should live in `revengine.celery.py`. My guess is that `RequestIdFilter` doesn't have broader applications than celery task logs, but if it does, it could continue to live in this file.

Otherwise, `set_request_id` and `setup_logs` could go in `revengine.celery.py`

2023-10-20 15:49 UTC, benjaminEwhite commented on apps/common/logger.py
> +def setup_logs():
Would be good to have a docstring here detailing what the end result of this setup is (namely, what we're trying to accomplish in our celery task logs). A year from now, it will be hard to suss out that intentionality from just reading through implementation here.

2023-10-20 15:51 UTC, benjaminEwhite commented on apps/common/logger.py
> +def setup_logs():
Also, wouldn't be a bad idea to unit test this function.

2023-10-24 20:10 UTC, benjaminEwhite commented on revengine/celery.py
> +request_id = contextvars.ContextVar("request_id", default=str(uuid.uuid4())[:8])
Can you give some context for use of `ContextVar` here? What is the lifecycle of `request_id` , and do we really need this module level var?

2023-10-24 20:14 UTC, benjaminEwhite commented on revengine/tests/test_celery.py
> +        expected_output = f"WARNING [{request_id.get()}]  test_celery:20 - This is a warning"
This should be pytest-based, not unittest.

```python
class TestLoggingConfiguration:
    def test_log_format(self, mocker):
        mock_stderr = mocker.patch("sys.stderr")
        ....

```

Also, might as well set line 23 above's message to a var, reference that var there,  and then can use it in f-string at line 29 instead of hardcoding "This is a warning" here.

2023-10-24 20:36 UTC, GuiMend commented on revengine/celery.py
> +request_id = contextvars.ContextVar("request_id", default=str(uuid.uuid4())[:8])
I'm not sure how to answer that @benjaminEwhite. I was adapting the implementation we have in switchboard to revengine: https://news-revenue-hub.atlassian.net/browse/DEV-1219

2023-10-24 22:20 UTC, benjaminEwhite commented on revengine/celery.py
> +request_id = contextvars.ContextVar("request_id", default=str(uuid.uuid4())[:8])
Okay. In that case, let's not block with this. But let's leave this conversation around for when @x110dc does his review, and he can weigh in.

I'd like better understand what problem we're trying to solve by using contextvars.

2023-10-24 22:45 UTC, benjaminEwhite requested changes
Had one suggestion for simplifying test.

Also, looks like there's one untested path in `RequestIdFilter.filter`.

<img width="1409" alt="Screenshot 2023-10-24 at 6 44 18 PM" src="https://github.com/newsrevenuehub/rev-engine/assets/960351/2f7bfa4f-c30b-4d8e-95d5-159af7e1d459">

2023-10-24 22:45 UTC, benjaminEwhite commented on revengine/tests/test_celery.py
> +        assert expected_output in log_output
```suggestion
        assert f"WARNING [{request_id.get()}]  test_celery:22 - [test_log_format] {message}" in mock_stderr.write.call_args[0][0]
```

2023-10-25 13:12 UTC, benjaminEwhite commented on revengine/celery.py
> +from celery.signals import task_prerun
I know this is not code you touched, but I read lines 9-10 more closely, and I don't understand what it's doing. 

The Django app won't run if `DJANGO_SETTINGS_MODULE` is not set, and our workers run in a context where they have access to app-level settings. Across local, review apps, standing envs, and prod, we set this env var ahead of building image/ deploying etc.

So this code is reading in DJANGO_SETTINGS_MODULE, but expecting that sometimes it won't be set (I don't think there's a path to that happening in reality), only to then set the environment variable to a new value (revengine.settings.deploy) if it wasn't already set.

Not necessarily your responsibility to solve here, but I wonder if everything works if we remove this.

2023-10-25 13:14 UTC, benjaminEwhite commented on revengine/celery.py
> +
Know it's untouched code and not necessarily in scope, but I wonder if we could remove `debug_task`. Only place i see it referenced is in its unit test. It uses `print` instead of logger, which i don't like (though maybe there are good reasons for that).

Seems like we could remove `debug_task` and `test_debug_task`.

2023-10-25 13:16 UTC, benjaminEwhite commented on revengine/celery.py
> +        return True
```suggestion
    def filter(self, record):
        req_id = request_id.get()
        record.request_id = f"[{req_id}]" if req_id else ""
        return True
```

2023-10-25 13:55 UTC, GuiMend commented on revengine/celery.py
> +from celery.signals import task_prerun
From what I understood `TaskFormatter` is formatting the log to display this information:
```python
"%(levelname)s %(request_id)s %(module)s:%(lineno)d - [%(funcName)s] %(message)s"
```

As for `task_prerun`, seems to me that it's setting a new request_id before a new task is started.

Did I get things wrong? 🤔

2023-10-30 22:03 UTC, njharman commented on revengine/celery.py
> +request_id = contextvars.ContextVar("request_id", default=str(uuid.uuid4())[:8])
@benjaminEwhite

2023-12-12 14:58 UTC, benjaminEwhite requested changes

2023-12-12 14:58 UTC, benjaminEwhite commented on revengine/tests/test_celery.py
> +# Tests works locally but fail in CI, so we skip them for now
**blocking**

@GuiMend would like to understand more about why this is the case. Let's do that in Slack or Zoom because I have a feeling that will be easier. You can reach out to me when you're working on this.

2023-12-12 14:58 UTC, benjaminEwhite commented on revengine/tests/test_celery.py
> +class TestLoggingConfiguration:
**blocking, but trivial**

The PR description section about unit tests says N/A, but in fact unit tests are added but skipped. PR description should reflect this.

2023-12-12 18:34 UTC, GuiMend commented
Celery logs will be addressed in https://news-revenue-hub.atlassian.net/browse/DEV-4313
AC1 of DEV-3207 will be done in https://github.com/newsrevenuehub/rev-engine/pull/1342

2023-12-12 18:34 UTC, closed without merging