DEV-4043: Payment model
newsrevenuehub/rev-engine pull request #1291
Opened 2023-10-23 18:41 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-11-03 03:54 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> -class StripeMetadataSchemaBase(pydantic.BaseModel):
Moved to apps.contributions.types

2023-11-06 20:13 UTC, njharman requested changes
Good coverage

2023-11-06 20:13 UTC, njharman commented on apps/contributions/tests/test_models.py
> +import json
I don't think i saw test i was looking for.

One(s) that exercises many to one relationship. Specifically test that adds multiple Payments to recurring Contribution.  [I wanted to ref AC, but the many-to-one is not AC.

2023-11-06 20:13 UTC, njharman commented on apps/contributions/models.py
> +class Payment(IndexedTimeStampedModel):
surprised there was no requirement for timestamp/date

2023-11-14 14:40 UTC, benjaminEwhite commented on apps/contributions/models.py
> +class Payment(IndexedTimeStampedModel):
we get created/modified via IndexedTimeStampedModel, or are you looking for something different?

2023-11-14 14:44 UTC, benjaminEwhite commented on apps/contributions/types.py
> +        return v
Correct. It is moved code.

2023-11-14 16:44 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        cache.set(cache_key, json.loads(json.dumps(result)), 60 * 3)
1c2980127c

2023-11-14 17:28 UTC, benjaminEwhite commented on apps/contributions/models.py
> +                    if balance_transaction
0538c77

2023-11-14 17:44 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            raise ValueError("Could not find a balance transaction for this event")
285888b3c8

2023-11-14 17:45 UTC, benjaminEwhite commented on revengine/settings/base.py
> +        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
yes. see settings/deploy.py:

```
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{CACHE_HOST}/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": CONNECTION_POOL_KWARGS,
        },
    }
}
```

2023-11-14 18:00 UTC, benjaminEwhite commented on apps/contributions/tests/test_models.py
> +        }
186d966

2023-11-14 20:10 UTC, benjaminEwhite commented on apps/contributions/tests/test_models.py
> +import json
This help? 60b702d

2023-11-16 19:02 UTC, njharman approved these changes

2023-11-20 04:06 UTC, x110dc requested changes
A few questions.

2023-11-20 04:06 UTC, x110dc commented on apps/contributions/models.py
> +            raise ValueError("Could not find a balance transaction for this event")
Again, why both the warning and the exception?

2023-11-20 04:06 UTC, x110dc commented on revengine/settings/dev.py
> -if BROKER_URL.startswith("memory"):
Why was this changed? Should be mentioned in the PR description, I'd think.

2023-11-20 14:49 UTC, benjaminEwhite commented on apps/contributions/models.py
> +    def get_subscription_id_for_balance_transaction(
No. This returns an ID. I believe I changed implementation along the way and didn't update type def.

2023-11-20 14:51 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            raise ValueError("Cannot link payment intent to a single balance transaction")
Seems like a good idea to guarantee a log from this method, and lave it to calling context to decide what to do if an error occurs.

2023-11-20 14:55 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        cls._ensure_pi_has_single_charge(pi, event.id)
And then some. I lightly refactored here: 56ef8344ae

2023-11-20 14:56 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            raise ValueError("Could not find a balance transaction for this event")
Same reason as above. I think it's good for this method to log that something went wrong, and leave itto calling context to decide whether to halt or something different.

2023-11-20 15:17 UTC, benjaminEwhite commented on revengine/settings/dev.py
> -if BROKER_URL.startswith("memory"):
Added to PR description.

2023-11-20 15:22 UTC, benjaminEwhite commented on apps/contributions/models.py
> +    def get_valid_metadata(cls, metadata: dict | None, schema=StripePaymentMetadataSchemaV1_4) -> bool | None:
This was more broadly in use at one point, but then moved away from it. Removed in daa1beb16e2b

2023-11-20 19:54 UTC, x110dc approved these changes
Would be nice to have answer on 2 Sentry alerts but not essential and approved either way.

2023-11-20 19:54 UTC, x110dc commented on apps/contributions/models.py
> +    def get_subscription_id_for_balance_transaction(
Thanks for fixing the type.

2023-11-20 19:54 UTC, x110dc commented on apps/contributions/models.py
> +            raise ValueError("Cannot link payment intent to a single balance transaction")
In this case what does the calling context do? Will we have two Sentry alerts for the same issue?

2023-11-20 19:54 UTC, x110dc commented on apps/contributions/models.py
> +            raise ValueError("Could not find a balance transaction for this event")
Same response as above.

2023-11-20 19:54 UTC, x110dc commented on revengine/settings/dev.py
> -if BROKER_URL.startswith("memory"):
👍

2023-11-20 20:07 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            raise ValueError("Cannot link payment intent to a single balance transaction")
30f762868

2023-11-20 20:07 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            raise ValueError("Could not find a balance transaction for this event")
30f762868

2023-11-20 20:08 UTC, benjaminEwhite commented
@x110dc removed one of the sentry logs in 30f762868

2023-11-21 16:05 UTC, merged