DEV-3884: Implement new contributions list
newsrevenuehub/rev-engine pull request #1320
Opened 2023-11-16 16:34 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

1. Adds a list of contributions in the new contributor portal. Lots of functionality yet to come; see Jira for out of scope stuff.
2. Adds a new context, PortalAuthContext, and a component to manage it.
3. Uses a new component, TokenVerification, instead of the older ContributorVerify.
4. Adds a new hook, usePortalContributionList, to retrieve contributions from the new API endpoint. Existing hook is marked deprecated.
5. Adds a CircularProgress base component.
6. Migrates `formatCurrencyAmount` to TypeScript and adds parameter to optionally omit the cents in an amount if it's a round number.
7. Changes the name of the `PORTAL.DASHBOARD` route to `PORTAL.CONTRIBUTIONS`.

#### Why are we doing this? How does it help us?

1. Makes progress toward new portal.
2. The existing approach on auth in the contributor portal relied on storing context in local storage. The new context stores it there, but provides a typed interface to consumers who need it (i.e. the contributions list needs to know the contributor ID). This will increase reliability/dev speed since consumers no longer need to use local storage directly and handle possible errors every time they access it.
3. TokenVerification uses the new context in point 2.
4. New hook keeps business logic separate/more testable. I marked the existing one deprecated to avoid confusion since the names are pretty similar.
5. It's a better UI experience to see part of the page show a spinner instead of the entire page graying out. This CircularProgress component allows that.
6. The new contributions list omits cents in round amounts.
7. I thought it was confusing to have a route in the contributor portal named "dashboard" when we are calling the admin area "the dashboard".

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

Yes.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

Need updated docs around the new portal, but even merged, users will continue to be directed to the existing portal.

#### Have automated unit tests been added? If not, why?

Yes.

#### How should this change be communicated to end users?

n/a

#### Are there any smells or added technical debt to note?

No.

#### Has this been documented? If so, where?

No.

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-3884

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

See rest of epic.

2023-11-20 16:39 UTC, benjaminEwhite requested changes

2023-11-20 16:39 UTC, benjaminEwhite commented on spa/src/hooks/usePortalContributionList.ts
> +   * What payment card was used on the contribution.
FWIW, this value is likely to be whatever the current payment method is, regardless of what was used on any given payment for a contribution.

2023-11-20 16:39 UTC, benjaminEwhite commented on spa/src/hooks/usePortalContributionList.ts
> +  last_payment_date: string;
Seems like this might be null sometimes. For instance, IIRC imported legacy subscriptions will initially be in a state where our system doesn't see a last payment date and there hasn't been a charge in new system.

2023-11-20 16:39 UTC, benjaminEwhite commented on spa/src/hooks/usePortalContributionList.ts
> +  credit_card_expiration_date: string;
This may be a red herring, but we should see if we ever expect to see contributions that are by check or otherwise don't have a cc.

2023-11-20 16:39 UTC, benjaminEwhite commented on spa/src/hooks/usePortalContributionList.ts
> +  next_payment_date: string;
This can be null in case of one-time or canceled recurring.

2023-11-20 16:39 UTC, benjaminEwhite commented on spa/src/hooks/usePortalContributionList.ts
> +  payment_type: string;
Would maybe expect an enumerated set of literals here.

2023-11-20 16:39 UTC, benjaminEwhite commented on spa/src/hooks/usePortalAuth.tsx
> +    localStorage.setItem(LS_CSRF_TOKEN, data.csrftoken);
Might make sense to key off of contributor ID, perhaps for both values here. reason being i think that in status quo the localstorage + auth settings is sometimes a source of oddities in when you log in as an org user and then separately log in as a hubadmin/superuser. Since we're keying off a static var name here, can get stale.

2023-11-20 18:49 UTC, nrh-cklimas commented on spa/src/hooks/usePortalContributionList.ts
> +  payment_type: string;
There are 30 possible ones :( https://stripe.com/docs/api/payment_methods/object#payment_method_object-type

Do you think it's plausible to make these the ones we expect to see? I think that would be 

- card
- link
- us_bank_account?

2023-11-20 18:57 UTC, nrh-cklimas commented on spa/src/hooks/usePortalAuth.tsx
> +    localStorage.setItem(LS_CSRF_TOKEN, data.csrftoken);
This reminds me I needed to create a followup story. https://news-revenue-hub.atlassian.net/browse/DEV-4252

Because of this, I'll request leniency on this point as it maintains backwards compat.

2023-11-20 18:57 UTC, nrh-cklimas commented on spa/src/hooks/usePortalContributionList.ts
> +  credit_card_expiration_date: string;
If that happened, would this be null or an empty string (or something else)?

2023-11-20 19:03 UTC, nrh-cklimas commented on spa/src/hooks/usePortalContributionList.ts
> +   * What payment card was used on the contribution.
Updated comment in 3c9788004f2b0801618f8d98a786f5e21d654e51

2023-11-21 14:17 UTC, benjaminEwhite commented on spa/src/hooks/usePortalContributionList.ts
> +  credit_card_expiration_date: string;
I believe it would be `null`. It's not a case I've thought a lot about. Maybe we just worry about it later.

2023-11-21 14:20 UTC, benjaminEwhite commented on spa/src/hooks/usePortalContributionList.ts
> +  payment_type: string;
30s a lot!

I'm not gung ho about a partial list, TBH.

I think we can leave as is and if we have any issues arise around payment type, then we can get more restrictive at that point.

2023-11-21 14:22 UTC, benjaminEwhite approved these changes

2023-11-28 14:40 UTC, merged