DEV-4213: pin deps, unpin dev deps
newsrevenuehub/rev-engine pull request #1323
Opened 2023-11-18 08:57 UTC by leo-dcfa

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

N/A

#### What's this PR do?

- Pin regular dependencies
- Unpin dev dependencies

#### Why are we doing this? How does it help us?

This will make it so we can do a regular poetry update; pre-commit autoupdate once per sprint to keep deps up-to-date

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

Yes

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

N/A

#### Have automated unit tests been added? If not, why?

N/A

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

N/A

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-4213]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

N/A

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

N/A

2023-11-27 15:08 UTC, benjaminEwhite commented on apps/contributions/tests/test_serializers.py
> +import pydantic_core
**Question**

This change seems out of scope. What's reasoning?

2023-11-27 15:09 UTC, benjaminEwhite commented on apps/contributions/tests/test_stripe_contributions_provider.py
> +        ).replace(microsecond=0)
Unclear why this change and similar ones below required.

2023-11-27 15:12 UTC, benjaminEwhite reviewed
Have a couple questions of small questions (the answer to which I'm assuming is that changes were required to make pre-commit happy, but want to understand).

2023-11-28 09:26 UTC, leo-dcfa commented on apps/contributions/tests/test_serializers.py
> +import pydantic_core
I was also surprised with this one - when I ran `poetry update` the test that references `pydantic.pydantic_core.Url` started failing. I noticed that pydantic_core got bumped from `2.10.1`to `2.14.3`, check the documentation and imported directly instead.

2023-11-28 14:27 UTC, benjaminEwhite commented on apps/contributions/tests/test_stripe_contributions_provider.py
> +        ).replace(microsecond=0)
**blocking request**

worth adding a code comment about why this is required.


**non-blocking question**

do you know why the test started failing now?

2023-11-28 14:27 UTC, benjaminEwhite approved these changes

2023-11-30 06:01 UTC, leo-dcfa commented on apps/contributions/tests/test_stripe_contributions_provider.py
> +        ).replace(microsecond=0)
Comment added. 

Concerning why, I don't know, some dependency update led to it

2023-12-04 05:27 UTC, x110dc requested changes
One dep doesn't look correct. 

Adding more detail to the "what does this PR do" section I think could've avoided some of the back-and-forth for the non-obvious changes here.

2023-12-04 05:27 UTC, x110dc commented on pyproject.toml
> +dateparser = "1.1.8"
Why is this pinned and not set to `*`?

2023-12-13 06:06 UTC, x110dc approved these changes

2023-12-21 16:08 UTC, merged