DEV-4045 | refactor webhooks to account for payment model
newsrevenuehub/rev-engine pull request #1331
Opened 2023-12-04 21:12 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

- Adds two new webhook event types to `revengine.settings.base`. Both create a payment instance in the success case. If a matching contribution cannot be found, the task catches this and does a debug log:
  - `invoice.payment_succeeded`
  -  `charge.refunded` 
- Adds `.contribution` property to `apps.contributions.webhooks.StripeWebhookProcessor`. This tries to derive an NRE contribution from the webhook event data.
- Alters existing payment_intent.succeeded webhook so that in case of recurring contribution, no processing is done, in favor of handling that in `invoice.payment_succeeded` webhook handler.
- Removes caching of result for `Payment.stripe_balance_transaction`. Caching proved to be bad move here as this is under initial development because it masked other problems.

#### Why are we doing this? How does it help us?

- part of migrating to new transaction model for contributions
- support new contributor portal

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

Not yet

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No

#### Have automated unit tests been added? If not, why?

Yes

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

Yes

(attach whiteboard links)

#### What are the relevant tickets? Add a link to any relevant ones.

- [DEV-4045](https://news-revenue-hub.atlassian.net/browse/DEV-4045)

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

- [ITS-2187](https://news-revenue-hub.atlassian.net/browse/ITS-2187) (can come right after deploy)

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

[DEV-4045]: https://news-revenue-hub.atlassian.net/browse/DEV-4045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-12-04 23:57 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            # typeddict unfortunately does not support `isinstance` checks so have to look at keys
Got this wrong in original implementation and fixing here.

2023-12-04 23:59 UTC, benjaminEwhite commented on apps/contributions/tests/test_models.py
> -@pytest.fixture
several of these moved to conftest.py

2023-12-05 21:49 UTC, benjaminEwhite commented on .coveragerc
> -fail_under = 95
We're already above 97, but figured should formalize.

2023-12-05 22:17 UTC, benjaminEwhite commented on apps/contributions/models.py
> -            return stripe.BalanceTransaction.construct_from(cached_result, key=stripe.api_key)
Caching proved to be bad move here as this is under initial development because it masked other problems.

2023-12-05 22:26 UTC, benjaminEwhite commented on apps/contributions/webhooks.py
> -                "provider_payment_id": self.id,
There's no scenario where the webhook should be overriding the value already on `provider_payment_id`.  This happens to have not had negative side effects in status quo because the value doesn't get updated with anything new, but there is no good reason to be doing it.

2023-12-07 19:21 UTC, njharman requested changes
Good coverage
Just questions around AC

2023-12-07 19:21 UTC, njharman commented on apps/contributions/webhooks.py
> +            payment = Payment.from_stripe_invoice_payment_succeeded_event(event=self.event)
AC3.a says Payment.from_invoice_refunded_event() which seems wrong.  Why refunded for payment_succeeded.

2023-12-07 19:21 UTC, njharman commented on apps/contributions/webhooks.py
> +    def handle_invoice_payment_succeeded(self):
I'm unsure what the match in AC3b "if not match, log warning" refers to.  I don't see any logging here, is it elsewhere?

2023-12-07 19:21 UTC, njharman commented on apps/contributions/models.py
> +        new_refunds = [
AC 2.a says to use Payment.from_charge_refunded_event() which doesn't exist in code. Probably should update AC? I'm assuming this code does what is needed.

2023-12-15 00:31 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            # typeddict unfortunately does not support `isinstance` checks so have to look at keys
Well, I ended up considering this because I was not happy with the way the check had to be to accommodate. Named tuple (which i was not aware of!) worked great, and in implementing uncovered some deficiencies in the test implementation in places. Took a few commits to get this change through, but proved valuable. I don't have single commit to point to, but you can look at the StripeEventData object in apps.contributions.types to see what changed.

2023-12-15 00:42 UTC, benjaminEwhite commented on apps/contributions/webhooks.py
> +    def handle_invoice_payment_succeeded(self):
I ended up changing old behavior (debug log only when contribution not exist comes up when running task so we are explicitly testing around that AC.

69c01c703d9f

2024-01-04 21:08 UTC, x110dc requested changes
Just a few questions and small requests.

2024-01-04 21:08 UTC, x110dc commented on apps/contributions/models.py
> -            return stripe.BalanceTransaction.construct_from(cached_result, key=stripe.api_key)
I think it would be good to add this to the "what's this PR do" section of the description.

2024-01-04 21:08 UTC, x110dc commented on apps/contributions/tasks.py
> +        logger.warning("Could not find contribution. Here's the event data: %s", event, exc_info=True)
Why make this a warning when we fully expect this condition and won't take any action based on it?

2024-01-05 14:15 UTC, benjaminEwhite commented on apps/contributions/models.py
> -            return stripe.BalanceTransaction.construct_from(cached_result, key=stripe.api_key)
Added to PR description.

2024-01-05 14:17 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            # logger.something
aa58848fe1

2024-01-05 14:19 UTC, benjaminEwhite commented on apps/contributions/tasks.py
> +        logger.warning("Could not find contribution. Here's the event data: %s", event, exc_info=True)
831cbf98b

2024-01-09 21:24 UTC, x110dc approved these changes
LGTM

2024-01-16 19:04 UTC, benjaminEwhite commented
Tearing down and reopening to build fresh review app because past papertrail quota for existing one.

2024-01-19 14:37 UTC, merged