WIP | DEV-4032 | implement new contributor facing contributions api endpoint
newsrevenuehub/rev-engine pull request #1346
Opened 2023-12-15 03:30 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-12-15 15:33 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        return datetime.datetime.fromtimestamp(self.stripe_subscription.current_period_end, tz=pytz.UTC)
**Question**

What will this be in case of canceled subscription? Is there an edge case to handle there?

2023-12-15 16:33 UTC, benjaminEwhite commented on apps/contributions/models.py
> +    def is_modifiable(self) -> bool:
**Question** 

Is this the right way to determine. It turns out the status quo way of determining is_modifiable seems to reference non-existent statuses (as well as one existent one).  See https://github.com/newsrevenuehub/rev-engine/blob/1d114f81e3acbb0b971cd58adddf84b8e89d0d14/apps/contributions/serializers.py#L801

Best i can tell, we would want to allow modificaiton of recurring if it's status is either paid (implying first payment has been processed and there's potential for future ones) or if status is failed, in which case the user couldl update their CC info to make work. 

Does this seem right?

2023-12-19 03:15 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        if (email := request.user.email.lower()) != subscription.customer.email.lower():
**Question**

Can this be removed? I copied this business logic from the status quo Stripe-cache based approach to showing users their contributions.  Maybe this is not a concern here? And if it is, probably better handled more explicitly  and in an easily reproducible way (perhaps with a decorator).

2024-01-03 22:35 UTC, njharman requested changes

2024-01-03 22:35 UTC, njharman commented on apps/contributions/views.py
> +        if (email := request.user.email.lower()) != subscription.customer.email.lower():
Seems to be covered by  `contribution = contributor.contribution_set.get(pk=contribution_id)` in contribution_detail(), right?  Or can user with valid contribution, twiddle the http payload/url to set provider_subscription_id to unrelated one one they don't own. If that's not non-sensical question/case should be unit test for it.

I worry a little that that contribution_set() "check" is outside these handle_ methods (some future dev will call them without similar check).  Maybe rename handle_* to _handle_* to give hint these are internal/depend on internal implementation/use with caution.
 
Seems issue prone and "sad" (because it can change, is out of our control) to verify user by email. I remember complaining before and it has to be this way cause we don't have User records for contributors, just whatever is passed via magic link which is email based, so email **is** the best id.

If this logic is kept, wouldn't it be better to pass the contributor (retrieved line #620) and using that instead of pulling out of request.  Cut request and pass contributor and provider_payment_id

2024-01-03 22:35 UTC, njharman commented on apps/contributions/views.py
> +        try:
Shouldn't we be checking it is in cancellable state?  maybe via is_cancelable()

2024-01-03 22:35 UTC, njharman commented on apps/contributions/views.py
> +            case "DELETE":
Coverage says DELETE never matched. I'm not sure I believe that.

2024-01-04 14:13 UTC, benjaminEwhite commented on apps/api/permissions.py
> +class UserIsContributor(permissions.BasePermission):
709250bfebe3

2024-01-04 14:16 UTC, benjaminEwhite commented on apps/api/permissions.py
> +class UserIsContributor(permissions.BasePermission):
8d5a1b2 and 082ca1a8c

2024-01-04 14:18 UTC, benjaminEwhite commented on apps/api/permissions.py
> +        has_permission = obj == request.user and isinstance(obj, Contributor)
Good catch!  8d5a1b2c

2024-01-04 14:19 UTC, benjaminEwhite commented on apps/api/permissions.py
> +        logger.info("Temp log showing object permission in UserIsContributor: %s", has_permission)
709250bf

2024-01-04 14:24 UTC, benjaminEwhite commented on apps/contributions/models.py
> +import pytz
Good to know:

ffaa2f0218

2024-01-04 14:29 UTC, benjaminEwhite commented on apps/contributions/models.py
> +    def card_expiration_date(self) -> str:
Ultimately, I'm liking having "neat" serializers that have the client-facing names we want (no need to have `_str`  ending for the client) and don't require additional configuration (that is to say, we just name the fields we want in `PORTAL_CONTRIBUTION_BASE_SERIALIZER_FIELDS` and don't have to explicitly declare those fields with `foo = serializers. SerializerMethodField(source="foo_str")`

2024-01-04 14:46 UTC, benjaminEwhite commented on apps/contributions/models.py
> +    # add index on transaction time since wwill need to sort by for last pasyment
Also turned this into a JIRA todo

c3f889d8

2024-01-04 14:47 UTC, benjaminEwhite commented on apps/contributions/models.py
> +    # add index on transaction time since wwill need to sort by for last pasyment
Turns out that also requires a data migration so we can manually retrieve the balance_transaction for the Payment (which is source for payment.transaction_time).  Would prefer to do that in a follow up ticket, as that adds scope here in short term, and would like to move this through.

2024-01-04 14:48 UTC, benjaminEwhite commented on apps/contributions/models.py
> +    # add index on transaction time since wwill need to sort by for last pasyment
also turned this into a JIRA todo

c3f889d8

2024-01-04 16:32 UTC, benjaminEwhite commented
Closing and reopening because migrations changed and need to build from scratch.

2024-01-04 16:35 UTC, benjaminEwhite commented on apps/contributions/models.py
> +    # add index on transaction time since wwill need to sort by for last pasyment
Ended up adding now, which requires allowing transaction_time to be nullable in short term, and an additional data migration to backfill. Once this PR is merged, we can make non-nullable in DEV-4379 (which is. TODO).

2024-01-04 18:28 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            K for K in PORTAL_CONTRIBUTION_DETAIL_SERIALIZER_DB_FIELDS if K != "provider_payment_method_id"
Another good catch. This is a vestige of earlier iteration of schema. No longer needed. Removed in f69b1d2a4c

2024-01-05 17:38 UTC, benjaminEwhite commented on apps/contributions/views.py
> +            case "DELETE":
@njharman yeah i'm not sure what's going on here. we definitely test this path (you can put in a debugger and run `test_contribution_detail_delete_happy_path`, for instance).

2024-01-05 17:40 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        return Response(serializer.data, status=status.HTTP_200_OK)
See 4397e94a9

2024-01-08 15:15 UTC, benjaminEwhite commented on apps/contributions/models.py
> +    # add index on transaction time since wwill need to sort by for last pasyment
This is outdated

2024-01-08 15:49 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        return datetime.datetime.fromtimestamp(self.stripe_subscription.current_period_end, tz=pytz.UTC)
9a452fc536

2024-01-08 15:49 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        try:
Good catch. I did this, and also removed the check on contribution interval, since the critical thing here is the status of the stripe subscription (if any).   Did the same in handle_patch (but with is_modifiable).

9a452fc536

2024-01-08 15:52 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        if (email := request.user.email.lower()) != subscription.customer.email.lower():
@njharman implementation you suggest makes sense, but want to hear from @x110dc if he thinks this check can/should be removed altogether.

2024-01-08 22:03 UTC, njharman approved these changes

2024-01-09 15:48 UTC, benjaminEwhite commented on apps/contributions/migrations/0009_DEV-4032_transaction_time_data_migration.py
> +        payment.save(update_fields={"modified", "transaction_time"})
Thinking about this more, I wonder if this is an argument to not do this as a data migration, in favor of porting that set_transaction_time function into a management command or one off script. Going to leave this conversation thread open to get @x110dc 's thoughts on best way to handle.

2024-01-09 21:59 UTC, x110dc requested changes
A few questions/comments.

2024-01-09 21:59 UTC, x110dc commented on apps/api/schemas/portal-contribution-detail.openapi.yml
How are these schemas used? How with they be kept in sync with the code?

2024-01-09 21:59 UTC, x110dc commented on apps/contributions/migrations/0009_DEV-4032_transaction_time_data_migration.py
> +        payment.save(update_fields={"modified", "transaction_time"})
Yes, I think it should be a management command and not part of the migration. Since there's no batch way to do this it could take quite some time and that will halt/slow deployment.

2024-01-09 21:59 UTC, x110dc commented on apps/contributions/models.py
> +
The card could also be on `customer.invoice_settings.default_payment_method` -- it may not for RevEngine but for other sources (migrated to RevEngine, for example) it will be.

2024-01-09 21:59 UTC, x110dc commented on apps/contributions/models.py
> +    # TODO: [DEV-4333] Update this to be ._last_payment_date when no longer in conflict with db model field
remove underscore in comment?

2024-01-09 21:59 UTC, x110dc commented on apps/contributions/models.py
> +                    balance_transaction.created, tz=datetime.timezone.utc
Why use the date from the balance transaction and not the payment intent or invoice? The datetimes should be close, but it's not technically the same thing.

2024-01-09 21:59 UTC, x110dc commented on apps/contributions/views.py
> +        if (email := request.user.email.lower()) != subscription.customer.email.lower():
I don't recall why this logic is there. Can we look at the previous PR/commit that added it to see if there's a clue there? If that doesn't help answer the question I'm okay with removing it.

2024-01-10 18:29 UTC, benjaminEwhite commented on apps/contributions/models.py
> +                    balance_transaction.created, tz=datetime.timezone.utc
I'd prefer to have a single stable referent here and not have conditionality around where transaction time comes from. Whether it's a one-time charge, a recurrence, or a refund, we'll always have a balance transaction.  

We could rename this field to `balance_transaction_created` or something that makes source explicit if that's important, or add a docstring if that suffices.

2024-01-10 19:27 UTC, benjaminEwhite commented on apps/contributions/models.py
> +    # TODO: [DEV-4333] Update this to be ._last_payment_date when no longer in conflict with db model field
69e16efaab

2024-01-10 19:49 UTC, benjaminEwhite commented on apps/api/schemas/portal-contribution-detail.openapi.yml
I considered writing a test, but I think that's maybe overkill. I think I'll remove from source, as this was initially for coordinating simultaneous SPA and server-side work around not-yet-created interfaces.

In principle, I like the idea of committing schema to source code and then having tests that prove that API implements the schema. I created a followup task around that here: https://news-revenue-hub.atlassian.net/browse/DEV-4387

2024-01-10 20:19 UTC, benjaminEwhite commented on apps/contributions/migrations/0009_DEV-4032_transaction_time_data_migration.py
> +        payment.save(update_fields={"modified", "transaction_time"})
7217d0de

2024-01-11 14:09 UTC, benjaminEwhite commented on apps/contributions/models.py
> +
4588933102

2024-01-11 14:27 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        if (email := request.user.email.lower()) != subscription.customer.email.lower():
I looked back a few commits and didn't see any obvious reason we were doing that. 

Best I can come up with is that it may have been defensive programming re: how we're storing data in cache (which keys off of email).  

I've removed this code inclusive of the todo comment (for which i've added a note to ticket and PR description).

9501630bc7

2024-01-16 04:46 UTC, x110dc approved these changes
Approved.

2024-01-16 04:46 UTC, x110dc commented on apps/contributions/management/commands/sync_payment_transaction_time.py
> +            bt = stripe.BalanceTransaction.retrieve(
It can be addressed in another ticket/PR but I think we'll find that some of these will fail. For example, for accounts that were connected but no longer are. So, we'd want a way to skip those and continue.

2024-01-16 04:46 UTC, x110dc commented on apps/contributions/models.py
> +                    balance_transaction.created, tz=datetime.timezone.utc
Either remedy is okay by me.

2024-01-16 14:31 UTC, benjaminEwhite commented on apps/contributions/management/commands/sync_payment_transaction_time.py
> +            bt = stripe.BalanceTransaction.retrieve(
d4f65817

2024-01-16 14:36 UTC, benjaminEwhite commented on apps/contributions/models.py
> +                    balance_transaction.created, tz=datetime.timezone.utc
a84413b

2024-01-16 15:58 UTC, benjaminEwhite commented on apps/contributions/models.py
> -    def card(self) -> stripe.Card | None:
@x110dc wanted to get your feedback on this. In QA, Agustin found that card was not populated. I thought it would work with original implementation here, but ended up needing to mimic implementation in status quo stripe/cache based approach (where there's attempt to get card from pi).  

Wondering if you have any insight into why customer approach didn't work out.

2024-01-16 17:37 UTC, merged