DEV-4220: Add cancel and payment method update notification emails
newsrevenuehub/rev-engine pull request #1359
Opened 2024-01-04 21:41 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

Creating review app to debug webhook events

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2024-01-16 17:32 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            "contribution_date": datetime.datetime.today().strftime("%m/%d/%Y"),
I don't love that we're overloading `contribution_date` presumably to get some common formatting.

Would prefer to see var name be more generic, or possibly use two separate var names.

2024-01-16 17:34 UTC, benjaminEwhite commented on apps/contributions/models.py
> +                f"https://{construct_rp_domain(self.donation_page.revenue_program.slug)}/{settings.CONTRIBUTOR_VERIFY_URL}"
Should be able to use existing `Contributor.create_magic_link` static method for this.  https://github.com/newsrevenuehub/rev-engine/blob/main/apps/contributions/models.py#L104

2024-01-16 17:35 UTC, benjaminEwhite commented on apps/contributions/models.py
> +
Ditto re imports

2024-01-16 17:35 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            "magic_link": mark_safe(
Ditto re: using static method

2024-01-16 17:37 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        data = {
Looks like this is largely overlapping with data creation in send_recurring_contribution_payment_updated_email so probably could dry up.

2024-01-16 19:22 UTC, benjaminEwhite commented on apps/contributions/tests/test_models.py
> +            f"?token={token}&email={quote_plus(contribution.contributor.email)}"
Is there any reason we need to construct a realistic URL in this test, or could this just as simply be an empty string or some dummy value?

2024-01-16 19:25 UTC, benjaminEwhite commented on apps/contributions/tests/test_models.py
> +        for x in email_expectations:
This is totally optional, but I like using match/case for situation like this where conditional is on same condition for each branch.

```
match revenue_program.fiscal_status:

    case FiscalStatusChoices.FISCALLY_SPONSORED:
        // do stuff

    case FiscalStatusChoices.NONPROFIT:
        // do other stuff

    case _:
        // do default stuff

2024-01-16 19:29 UTC, benjaminEwhite commented on apps/contributions/tests/test_models.py
> +            )
```suggestion
    def test_send_recurring_contribution_payment_updated_email_styles(
        self, revenue_program, has_default_donation_page, monkeypatch, mocker, settings
    ):
       mocker.patch("apps.contributions.models.Contribution.fetch_stripe_payment_method", return_value=None)
        contribution = ContributionFactory(
            interval=ContributionInterval.YEARLY, provider_customer_id="test-customer-id"
        )
```

2024-01-17 20:47 UTC, benjaminEwhite commented on apps/contributions/tests/test_models.py
> +            )
Just going to note this here, but ^^ would be preferred style throughout.

2024-01-17 20:53 UTC, benjaminEwhite commented on apps/emails/views.py
> +    if rp.default_donation_page:
Looks like this path doesn't get tested (according to coverage report).  Should test this path (which will get to 100%).

2024-01-18 14:46 UTC, benjaminEwhite commented on apps/emails/views.py
> +    if DEBUG is set (see revengine/urls.py).
This is probably a good guard against leaking sensitive data, but otherwise, this endpoint does not have access control. Could it be limited to superusers or hub admins (look for usage of `@permission_classes` decorator in existing code).

This is true for other view as well.

2024-01-18 15:18 UTC, benjaminEwhite requested changes
Left some inline comments and requests for changes.

2024-01-18 15:18 UTC, benjaminEwhite commented on apps/emails/views.py
>  def preview_recurring_contribution_reminder(request):
Think it might be better to have a single view function that takes the name of an email template as one of its params (in addition to current ones).  With current design, we have to add a distinct URL to urls.py and distinct view here for any additional emails. 

Below is not totally worked out, but gives a single view function we can use for all email preview needs.

```python
from dataclasses import asdict

from django.http import HttpResponse
from django.template.loader import get_template
from django.template import TemplateDoesNotExist

PERMITTED_TEMPLATES = (
    "recurring-contribution-email-reminder.html",
    "recurring-contribution-canceled.html",
    "recurring-contribution-email-reminder.txt",
    "recurring-contribution-canceled.txt",
    "nrh-default-contribution-confirmation-email.html"
    "nrh-default-contribution-confirmation-email.txt"
)

def preview_email_template(request):
    template_name = request.GET.get('email_template', None)
    if template_name not in PERMITTED_TEMPLATES:
        return HttpResponse("Template not permitted.", status=400)
    
    rp_id = request.GET.get('rp_id', None)
    if rp_id is None:
        return HttpResponse("`rp_id` is a required field.", status=400)
    try:
        rp = RevenueProgram.objects.get(id=rp_id)
    except RevenueProgram.DoesNotExist:
        return HttpResponse("RevenueProgram does not exist.", status=404)
    style = (rp_style:=asdict(rp.transactional_email_style) | {"logo_url": (url:=request.GET.get('logo_url', rp_style["logo_url"]))})
    
    try:
        template = get_template(template_name)
    except TemplateDoesNotExist:
        return HttpResponse("Template does not exist.", status=404)

    data = {
        "contribution_interval_display_value": "year",
        "contribution_date": datetime.now(),
        "contribution_amount": "$123.45",
        "contributor_name": "Contributor Name",
        "copyright_year": datetime.now().year,
        "contributor_email": "nobody@fundjournalism.org",
        "magic_link": "https://magic-link",
        "rp_name": rp.name,
        "style": style,
        "default_contribution_page_url": rp.default_donation_page.page_url if rp.default_donation_page else None,
    }
    return HttpResponse(
        template.render(
            data,
            request,
        ),
        content_type=f"text/{'plain' if template_name.endswith("txt") else 'html'}"
    )

```

2024-01-18 15:18 UTC, benjaminEwhite commented on apps/emails/views.py
>  def preview_recurring_contribution_reminder(request):
This approach should also allow the tests to be dried up and simplified. Should be able to have one test that uses pytest.mark.parametrize calls to vary on logo url and default donation page, and to iterate over the permitted templates.

Then would have a separate tests for:

- when unpermitted name used
- when template not found
- when rp id not included
- when rp not exist

2024-01-18 19:09 UTC, nrh-cklimas commented on apps/contributions/models.py
> +        from apps.emails.tasks import send_templated_email
Removed in 1794655befcbbd033ef92582d84869c6ab578890

2024-01-18 19:09 UTC, nrh-cklimas commented on apps/contributions/models.py
> +
Removed in 1794655befcbbd033ef92582d84869c6ab578890

2024-01-18 19:09 UTC, nrh-cklimas commented on apps/contributions/models.py
> +            "magic_link": mark_safe(
Added in 1794655befcbbd033ef92582d84869c6ab578890

2024-01-18 19:22 UTC, nrh-cklimas commented on apps/contributions/tests/test_models.py
> +            )
Updated in 41e41d828832662e61ddf5309fe6be9a1d8997d2

2024-01-18 19:22 UTC, nrh-cklimas commented on apps/contributions/tests/test_models.py
> +        for x in email_expectations:
👍 Updated in 41e41d828832662e61ddf5309fe6be9a1d8997d2

2024-01-18 19:41 UTC, nrh-cklimas commented on apps/contributions/tests/test_models.py
> +            f"?token={token}&email={quote_plus(contribution.contributor.email)}"
This is used to validate that the email is sending a link with the correct URL--used the method to generate this in cd447c8a5c61209168861ba1e5e07cde87e7a68b

2024-01-18 19:42 UTC, nrh-cklimas commented on apps/emails/views.py
> +        style["logo_url"] = request.GET.get("logo")
This is overriding the logo that is already set in `rp.transactional_email_style`, so I don't think we can change this.

2024-01-18 20:10 UTC, nrh-cklimas commented on apps/contributions/models.py
> +        data = {
It hit me that the two methods, `send_recurring_contribution_canceled_email` and `send_recurring_contribution_payment_updated_email`, are almost identical except for

- subject line
- which template to use

Maybe they should just be one method like `send_recurring_contribution_change_email` that takes one arg as to the type of change? What do you think?

2024-01-18 20:11 UTC, nrh-cklimas commented on apps/emails/views.py
>  def preview_recurring_contribution_reminder(request):
Going to defer on this until we agree on an approach on https://github.com/newsrevenuehub/rev-engine/pull/1359#discussion_r1457930561, because I think this is essentially the same question.

2024-01-18 20:11 UTC, nrh-cklimas commented on apps/contributions/models.py
> +            "contribution_date": datetime.datetime.today().strftime("%m/%d/%Y"),
Going to defer until we resolve https://github.com/newsrevenuehub/rev-engine/pull/1359#discussion_r1457930561 because it might affect approach here.

2024-01-18 20:53 UTC, nrh-cklimas commented on apps/emails/views.py
> +    if rp.default_donation_page:
Added in 457dacb27f51d8df827994b2ae9f28fff7c14fa0

2024-01-18 21:10 UTC, nrh-cklimas commented on apps/emails/views.py
> +    if DEBUG is set (see revengine/urls.py).
Added in eb5bd97d76300bdbd9efc61ded888b9be45a23ce

2024-01-22 15:44 UTC, benjaminEwhite reviewed
Reviewed again. Left some comments @nrh-cklimas re: function names and shared code.

2024-01-23 19:43 UTC, nrh-cklimas commented on apps/contributions/models.py
> +        data = {
I like this idea a lot--done in 0a1e6370b850cdff507ffac7388333665752a86e. I didn't add unit tests directly on the underlying method but I could if you think it's a good idea. We have coverage indirectly.

2024-01-23 19:44 UTC, nrh-cklimas commented on apps/contributions/models.py
> +            "contribution_date": datetime.datetime.today().strftime("%m/%d/%Y"),
Changed this to `timestamp` in 34f77746f95ff9410a0070980e9e1bc36b31a7e1 and updated QA instructions because this affects confirmation email potentially.

2024-01-24 15:49 UTC, nrh-cklimas commented on apps/emails/views.py
>  def preview_recurring_contribution_reminder(request):
Took a stab at this in e7cd024fc89909489a31a536fbcc3fa6895fc33a.

2024-01-25 22:51 UTC, benjaminEwhite reviewed
@nrh-cklimas left a couple comments here and then (as discussed) ended up doing a PR with a set of suggested changes into DEV-4220 branch. Thought we could huddle and talk through them so I can impart some of the not-yet documented reasoning behind some of the approaches and conventions.

Will link to that PR in the main ticket on JIRA.

2024-01-30 03:04 UTC, benjaminEwhite approved these changes
Left one comment you can resolve on your own @nrh-cklimas re: adding docstring.

Also worth adding to PR description "What's this do?" section a bullet about the existing `send_recurring_contribution_email_reminder` implementation shifting to use the new abstracted method for recurring contribution emails.

I'm approving, as above does not need re-review.

2024-01-30 15:44 UTC, nrh-cklimas commented on apps/contributions/models.py
> +    def send_recurring_contribution_change_email(self, subject_line: str, template_name: str) -> None:
Done in 760e2ad6ba6ae42d45cacb03b6bc3993a99572b0

2024-02-05 15:47 UTC, benjaminEwhite approved these changes

2024-02-06 15:06 UTC, merged