DEV-3869: Implement sorting dropdown on contribution list
newsrevenuehub/rev-engine pull request #1382
Opened 2024-01-22 21:40 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?
- Creates Sort component
- Implement Sorting functionality in contribution list page 

#### Why are we doing this? How does it help us?
- Facilitate visibility of contributions
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
- yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
- yes
#### Have automated unit tests been added? If not, why?
- yes
#### How should this change be communicated to end users?
- Sorting enabled in contributions list
#### Are there any smells or added technical debt to note?
- no
#### Has this been documented? If so, where?
- no
#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3869
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
- no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
Epic: https://news-revenue-hub.atlassian.net/browse/DEV-3782

2024-01-23 14:49 UTC, nrh-cklimas requested changes
Two general things:

- I think right now there's too much vertical space between the menu and the contribution list. Looking in Figma, I think it should be 25px.
- Would it be a lot of work to change the mock to honor the sorting query params? Right now, it's going to be hard to QA because changing the sort doesn't cause anything to change.

2024-01-23 14:49 UTC, nrh-cklimas commented on spa/src/components/base/Select/Select.tsx
Can you talk through advantages of using this over `<TextField select>`? [According to the docs](https://v4.mui.com/components/text-fields/#select), that prop causes the component to use `Select`, so it feels possibly redundant.

2024-01-23 14:49 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionsList.test.tsx
> +const refetch = jest.fn();
If we move this to a global in the module, I think we need to call `refetch.mockClear()` in `beforeEach` so that test runs don't potentially pollute each other. I personally prefer to use a specific mock in a test so there's no possibility for this to get missed, but it's a code style concern.

2024-01-23 14:49 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionsList.tsx
> +  useEffect(() => {
Instead of using an effect, let's change `usePortalContributionList` to put the query string into the [React query key](https://tanstack.com/query/latest/docs/react/guides/query-keys). This should trigger a refetch for free and means that any other consumers of the hook don't have to think about it.

2024-01-23 14:49 UTC, nrh-cklimas commented on spa/src/components/common/Sort/Sort.tsx
> +      <Typography variant="body2" color="textSecondary">
Right now there's no relationship between this label and the field. This doesn't get flagged by axe because the select's role is `button`, but I'd suggest either using the `labelId` prop here, or `<TextField>` because that handles labelling for you.

2024-01-23 14:49 UTC, nrh-cklimas commented on spa/src/components/common/Sort/Sort.tsx
> +  const handleChange = (event: ChangeEvent<{ value: unknown }>) => {
`value` will always be `string` in a change event, won't it?

2024-01-23 14:49 UTC, nrh-cklimas commented on spa/src/components/common/Sort/Sort.tsx
> +export const CONTRIBUTION_SORT_OPTIONS = [
I feel like this belongs more in ContributionsList, unless you see this being used elsewhere.

2024-01-23 23:05 UTC, GuiMend commented on spa/src/components/base/Select/Select.tsx
Now that you mentioned it, I don't think there are any differences. I checked the html and they seem the same. I guess MUI just made them separate to make it easier to glance at?
Would you rather I removed this `Select` component and added it's implementation directly to the `Sort` component?

2024-01-24 13:06 UTC, GuiMend commented on spa/src/components/common/Sort/Sort.tsx
> +  const handleChange = (event: ChangeEvent<{ value: unknown }>) => {
I believe so, but the `Select` TS only accepts onChange with `value: unkown`
![image](https://github.com/newsrevenuehub/rev-engine/assets/9381325/c40d997c-42a1-46d2-b588-5caa44cbbbd8)

2024-01-24 13:06 UTC, GuiMend commented on spa/src/components/common/Sort/Sort.tsx
> +    if (typeof onChange === 'function') onChange(event.target.value as string);
Made it simpler using optional chaining:
```js
onChange?.(event.target.value as string);
```

2024-01-24 13:18 UTC, GuiMend commented on spa/src/components/common/Sort/Sort.tsx
> +      <p style={{ margin: 0 }}>
Used `span`

2024-01-24 16:02 UTC, nrh-cklimas commented on spa/src/components/base/Select/Select.tsx
I think so, if it's a drop-in replacement here.

2024-01-24 16:04 UTC, nrh-cklimas commented on spa/src/components/common/Sort/Sort.tsx
> +      <Typography variant="body2" color="textSecondary" id="sort">
Not sure if this will still be needed with a switch to TextField, but the id should be a prop--otherwise two Sorts on the page will conflict with each other.

2024-01-24 16:04 UTC, nrh-cklimas commented on spa/src/components/common/Sort/Sort.tsx
> +  const handleChange = (event: ChangeEvent<{ value: unknown }>) => {
Let's revisit with the change to TextField.

2024-01-25 12:42 UTC, GuiMend commented on spa/src/components/common/Sort/Sort.tsx
> +  const handleChange = (event: ChangeEvent<{ value: unknown }>) => {
Fixed with the TextField 👍

2024-01-25 14:41 UTC, nrh-cklimas approved these changes

2024-01-29 14:04 UTC, merged