DEV-4407: Implement Cancel Contribution in New Portal
newsrevenuehub/rev-engine pull request #1394
Opened 2024-01-30 14:36 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
- Adds Cancel Contribution functionality to Contribution details screen

#### Why are we doing this? How does it help us?
- Allow donors to cancel contributions

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
- yes

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
- yes

#### Have automated unit tests been added? If not, why?
- yes
#### How should this change be communicated to end users?
- Recurring contributions are now cancelable
#### Are there any smells or added technical debt to note?
-no
#### Has this been documented? If so, where?
-no
#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-4407
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
- no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
Epic: https://news-revenue-hub.atlassian.net/browse/DEV-3780

2024-01-31 16:18 UTC, nrh-cklimas requested changes

2024-01-31 16:18 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/Modals/CancelContributionModal.styled.ts
> +export const ExclamationIcon = styled(InfoIcon)`
Couldn't we just use the Error icon?

2024-01-31 16:18 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/Modals/CancelContributionModal.styled.ts
This is both a nitpick and a pain to correct (as far as I know, you have to do a commit to delete the folder, then another to bring it back with the changed case), but could we change the directory name to `modals` not `Modals`? We've only been capitalizing component names in directories.

2024-02-01 12:29 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/Actions.tsx
> +  cancelContribution: (id: number) => void;
I was using it, but I removed it and updated the mutation to use the `contributionId` that we already have in the hook

2024-02-01 12:31 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/Actions.tsx
> +    async (id: number) => {
Removed the need for passing in the ID

2024-02-01 12:40 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/Actions.tsx
> +        console.error(error);
Not sure it was actually necessary. Removed it

2024-02-01 12:42 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/Modals/CancelContributionModal.styled.ts
> +export const ExclamationIcon = styled(InfoIcon)`
Yes! I didn't find that icon when glancing through the library. Thanks

2024-02-01 12:47 UTC, GuiMend commented on spa/src/components/base/Modal/Modal.tsx
> +    max-width: calc(100vw - 40px);
Sure. This is necessary for smaller screens (mostly mobile). We have a `width` property in the modal to make it the size we want, but in smaller screens we need the modal to be limited by the available space (plus 20px margin on each side).

with changes:
<img width="409" alt="image" src="https://github.com/newsrevenuehub/rev-engine/assets/9381325/e014bdf2-8ce0-4850-8123-001cfbe18783">

without changes:
<img width="509" alt="image" src="https://github.com/newsrevenuehub/rev-engine/assets/9381325/16e4b807-b580-4d62-8923-e571fc21f267">

2024-02-01 16:32 UTC, nrh-cklimas commented on spa/src/components/base/Modal/Modal.tsx
> +    max-width: calc(100vw - 40px);
Makes sense :) could you add a comment on that?

2024-02-01 16:33 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/Banner.test.tsx
> +    // TODO: update test when "Failed" banner is implemented
Do we have a story number we could add here?

2024-02-01 16:34 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/Actions.tsx
> +        console.error(error);
I think it would be good to log it for Sentry, unless you're thinking it would show up elsewhere.

2024-02-01 21:08 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/Actions.tsx
> +        console.error(error);
Oh, right. Will add a sentry log for this on the `onError` callback

2024-02-02 12:30 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/Banner.test.tsx
> +    // TODO: update test when "Failed" banner is implemented
I didn't find any in the epic

2024-02-02 14:53 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/Banner.test.tsx
> +    // TODO: update test when "Failed" banner is implemented
```suggestion
    // TODO: DEV-4464: update test when "Failed" banner is implemented
```

2024-02-02 14:54 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/Banner.test.tsx
> +    // TODO: update test when "Failed" banner is implemented
Added ticket number

2024-02-05 14:30 UTC, nrh-cklimas commented on spa/src/hooks/usePortalContribution.test.tsx
> +    it.skip('invalidates the contribution list and detail query', async () => {
This works for me locally:

```tsx
it('invalidates the contribution list and detail query', async () => {
      const { result, waitFor } = hook(123, 1);

      await waitFor(() => expect(axiosMock.history.get.length).toBe(1));
      expect(invalidateQueries).not.toHaveBeenCalled();

      jest.useFakeTimers();
      await result.current.cancelContribution();
      await waitFor(() => expect(axiosMock.history.delete.length).toBe(1));
      expect(invalidateQueries).toHaveBeenCalledWith(['portalContribution', 123, 1]);
      expect(invalidateQueries).toHaveBeenCalledTimes(1);

      act(() => {
        jest.runAllTimers();
      });

      await waitFor(() => expect(invalidateQueries).toHaveBeenCalledTimes(3));
      expect(invalidateQueries).toHaveBeenCalledWith(['portalContributionList']);
      expect(invalidateQueries).toHaveBeenLastCalledWith(['portalContribution', 123, 1]);

      jest.useRealTimers();
    });
```

I noticed that we have merge issues with main. To invalidate the detail query, it should be `      queryClient.invalidateQueries(['portalContribution', contributorId, contributionId]);` This was a mistake I made in the initial implementation--forgot that you could use multiple keys, and this usage matches up to other places we've used Tanstack Query, e.g. useContributionPage.

2024-02-06 01:52 UTC, nrh-cklimas approved these changes

2024-02-09 14:04 UTC, merged