DEV-4467: Portal pre-release refinements
newsrevenuehub/rev-engine pull request #1407
Opened 2024-02-09 19:28 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
- Align the loading, error, empty contribution components in the correct place on screen
- Refetches data 15 seconds after update or cancel contribution
- Redirects to magic link page if not logged in
- Remove sentry alert from being triggered if stripe returns "card declined" error
#### Why are we doing this? How does it help us?
- Refining new portal for launch
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
- yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
- no
#### Have automated unit tests been added? If not, why?
- yes
#### How should this change be communicated to end users?
- n/a
#### Are there any smells or added technical debt to note?
- no
#### Has this been documented? If so, where?
- no
#### What are the relevant tickets? Add a link to any relevant ones.
- https://news-revenue-hub.atlassian.net/browse/DEV-4467
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
- no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
- New Portal UI Updates Epic: https://news-revenue-hub.atlassian.net/browse/DEV-3780

2024-02-09 21:47 UTC, nrh-cklimas commented
@GuiMend how would you feel about creating a function similar to `ajax/axios.js` but tailored for use in the portal? There is similar logic there for 401 errors and the advantage to me is we don't have to think about it in each query. I think potentially the Axios interceptor could do the redirect to the portal login for us instead of passing back a particular error, but I haven't thought this through fully.

2024-02-13 14:39 UTC, nrh-cklimas requested changes

2024-02-13 14:39 UTC, nrh-cklimas commented on spa/src/ajax/portal-axios.ts
> +import Axios from './axios';
I think we need a new Axios instance here; otherwise we're getting the interceptors used in the admin dash, and our interceptors will fire in the admin dash also.

2024-02-13 14:39 UTC, nrh-cklimas commented on spa/src/ajax/portal-axios.ts
> +}
```suggestion
function handleResponseError(error: AxiosError) {
  if (error?.name === 'AuthenticationError') {
    window.location.assign(PORTAL.ENTRY);
  }
  
  return Promise.reject(error);
}
```

I'm fuzzy on whether JS code would continue to execute after `location.assign()` is called, but it seems like it's a good idea to always return the error.

2024-02-13 14:39 UTC, nrh-cklimas commented on spa/src/hooks/usePortalContribution.test.tsx
> +    it('redirects user to magic link (login) page if GET error = Authentication Error', async () => {
I'd prefer to move these tests (and those in usePortalContributionList) into a new test file for `portal-axios.ts`, since they're testing the behavior over there.

2024-02-13 14:39 UTC, nrh-cklimas commented on spa/src/hooks/usePortalContribution.tsx
> -        console.error('[usePortalContribution:cancelContribution] ', error);
Curious, why remove this line? Will the error get logged elsewhere?

2024-02-13 14:45 UTC, GuiMend commented on spa/src/hooks/usePortalContribution.test.tsx
> +    it('redirects user to magic link (login) page if GET error = Authentication Error', async () => {
Sure. I had left them there because they were already implemented

2024-02-13 15:05 UTC, GuiMend commented on spa/src/hooks/usePortalContribution.tsx
> -        console.error('[usePortalContribution:cancelContribution] ', error);
Shouldn't have. Re-added deleted line

2024-02-13 15:41 UTC, nrh-cklimas approved these changes

2024-02-13 20:34 UTC, benjaminEwhite approved these changes
Backend changes LGTM.

2024-02-14 15:26 UTC, merged