DEV-4046 | Enhanced management command to backfill payment and contribution objects
newsrevenuehub/rev-engine pull request #1410
Opened 2024-02-12 15:09 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2024-02-20 22:16 UTC, benjaminEwhite commented on apps/contributions/stripe_contributions_provider.py
> +        return UntrackedStripeSubscription.get_interval_from_subscription(subscription)
Move this logic to new `UntrackedStripeSubscription` class because reusing logic there, and this will be retired soon.

2024-02-22 13:17 UTC, benjaminEwhite commented on apps/contributions/models.py
> -    def create_stripe_customer(
Discovered this wasn't used in object code, so opportunistically removed.

2024-02-22 13:31 UTC, benjaminEwhite commented on apps/contributions/tests/test_models.py
> -    def test_create_stripe_customer(self, monkeypatch, mocker, contributor_user):
Method was retired, so also retiring test.

2024-02-23 18:59 UTC, benjaminEwhite commented on apps/common/secrets.py
> +        logger.debug("GoogleCloudSecretProvider initializing with model_attr %s", model_attr)
Opportunistically moved this to debug because was creating noise and we've had confidence around cloud secrets for a while now.

2024-02-23 19:23 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            "product": self.revenue_program.payment_provider.stripe_product_id,
NB: This is not guaranteed to have referential integrity. An imported contribution may or may not have a .revenue_program (in status quo that relationship is via DB join, but would need to be able to derive from RP in order to have broader integrity.

[ADD TODO ITEM HERE}

2024-02-23 19:24 UTC, benjaminEwhite commented on apps/contributions/models.py
> +                stripe_account=self.stripe_account_id,
Question: Should we have a decorator on these methods that confirms stripe account ID? or just allow to bubble up.

2024-02-23 19:25 UTC, benjaminEwhite commented on apps/contributions/models.py
> -    def stripe_account_id(self):
This wasn't used anywhere so removed.

2024-02-23 21:13 UTC, benjaminEwhite commented on apps/contributions/tasks.py
> +def task_backfill_contributions_and_payments(
Question:

Should we consider having secondary task here which handles at per account level?  I.e., one task that spawns 1 task per available stripe account id.

2024-02-26 00:16 UTC, njharman requested changes
Have not verified AC or Test Coverage yet. It's big, I'm burnt after intense code review, and maybe lots of code changes in response to my comments (which could invalidate AC/coverage verification)

2024-02-26 00:16 UTC, njharman commented on apps/contributions/stripe_sync.py
> +        results = []
This should be called `contributions `or above, in backfill_contributions_and_payments_for_subscriptions, `contributions `should be called results

2024-02-26 00:16 UTC, njharman commented on apps/contributions/stripe_sync.py
> +        the async version of the backfill method for each account.
Not sure which class "If the class was initialized as async..." is referring to. Seems this one. There is no async_mode on this dataclass.  There is on StripeEventSyncer.

This appears to handle syncing in Command. So, methinks

A) This docstring should be updated/clarified

Or,

B) StripeTransaction Sync command/dataclass should be updated to pattern of StripeEventSyncer (setting async_mode and handling sync/async in dataclass, not Command.

2024-02-26 13:21 UTC, benjaminEwhite commented on apps/common/utils.py
> +    with reversion.create_revision():
On creation, it will create a revision. Not "empty" as such, just no comment (you can only add comments in Django reversion on updates, apparently).

I think this is acceptable (maybe even good) behavior as you end up with a full history (inclusive of original creation).  

If there's a good reason to reconsider, let me know. The cost would be additional code complexity (can't use update_or_create).

2024-02-26 13:23 UTC, benjaminEwhite commented on apps/common/utils.py
> +        needs_update = False
88ecff90ae

2024-02-26 13:24 UTC, benjaminEwhite commented on apps/common/utils.py
> +            if needs_update:
I'd prefer to keep current implementation and allow callers to decide whether or not to log about updates (which is in fact how this is being used in practice).

2024-02-26 13:32 UTC, benjaminEwhite commented on apps/contributions/management/commands/sync_stripe_event.py
> +    def add_arguments(self, parser: CommandParser) -> None:
ff03354a

2024-02-26 13:36 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +        )
ccabb33ccb

2024-02-26 13:44 UTC, benjaminEwhite commented on apps/contributions/management/commands/sync_stripe_transactions_data.py
> +            return
809bf1ff4

2024-02-26 13:48 UTC, benjaminEwhite commented on apps/contributions/stripe_contributions_provider.py
> +
498bf9b

2024-02-26 13:50 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +MAX_STRIPE_RESPONSE_LIMIT = 100
ccac56c2e

2024-02-26 13:53 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +            logger.info("Updated payment %s for refund %s for contribution %s", payment.id, refund.id, contribution.id)
0193b24e56a

2024-02-26 13:53 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +            logger.info("Updated payment %s for refund %s for contribution %s", payment.id, refund.id, contribution.id)
0193b24e56a

2024-02-26 14:03 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +        the async version of the backfill method for each account.
Fixed in this commit (which also more generally moved "backfill" to "sync" throughout code).

440c1f68407

2024-02-26 14:08 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +            return None
cd6cb938

2024-02-26 14:09 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +    def get_invoice(self, invoice_id: str, stripe_account_id: str, **kwargs) -> stripe.Invoice | None:
0eee281ffbe

2024-02-26 14:10 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +        return None
9d6aed2f8

2024-02-26 14:13 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +        )
the `any` option is much better. e700e4a720

2024-02-26 14:14 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +        return None
4d1a03256a7

2024-02-26 14:15 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +        # Question: should we be creating a contribution for a pi that has no charge, in the first place
Was note to myself meant to remind me to make a comment in PR. Removed comment and adding note.  

0cccdea06d

2024-02-26 14:16 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +        if not (charge := self.charge):
**Question**

(especially for @x110dc)

Should we be creating a contribution for a pi that has no charge, in the first place?

2024-02-26 14:17 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +        return None
255e64a829a

2024-02-26 14:30 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +        if interval == "year" and interval_count == 1:
`stripe_contributions_provider.py` will be removed in its entirety when we release the new contributor portal, and `SubscriptionsSerializer` is only used in stripe contributions provider, so I think we can live with short term redundancy here.

2024-02-26 14:31 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +            # In revengine terms, we conflate active and past due because we don't have an internal status
f2e0f81173

2024-02-26 14:33 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +        results = []
261c06a1ac6

2024-02-26 15:30 UTC, benjaminEwhite commented on apps/contributions/models.py
>          return None
@njharman  i've created [DEV-4507](https://news-revenue-hub.atlassian.net/browse/DEV-4507) and 
[DEV-4508](https://news-revenue-hub.atlassian.net/browse/DEV-4508) as follow up tasks to address this.

Also have updated the tech debt section of the PR description to reflect consequences of above.

2024-02-26 15:44 UTC, benjaminEwhite commented on apps/contributions/management/commands/sync_stripe_transactions_data.py
> +        parser.add_argument("--gte", type=lambda s: dateparser.parse(s, settings={"TIMEZONE": "UTC"}))
I think this was actually relevant. Ended up removing this, and we'll. just rely on getting cast to the apps's tz in default case. Also added help text.

93310e7475

2024-02-26 16:24 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +            except (InvalidMetadataError, ValueError) as exc:
Makes sense. Think this should address: 40fdd667cc

2024-02-26 20:54 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +                if isinstance(cust, str):
162d08c6ffe3

2024-02-28 14:50 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +        if not (charge := self.charge):
I believe what is happening in this case (or at least some cases where this happens) is that we have payment intents created via completing first page of checkout, but not filling out the second form. 

Contributions in this state that are created via normal checkout flow end up in a permanent "processing" state, which is what should also happen when imported via management command.

2024-03-01 17:48 UTC, njharman approved these changes

2024-03-01 17:48 UTC, njharman commented on apps/contributions/stripe_sync.py
> +            charges = [y.id for y in x.charges.data if y.status != "failed"]
["style" comment (meaning it's not a change request)

Having need for another minor/unimportant/unnamed variable is a "signal" that the outer loop `for x in pis:` is too "large a scope" for a minor/unimportant/unnamed variable.

My rules of thumb [explanation of my rational].

- try to use only 'x'  (same theory as "don't think about formatting, use black)
- use x when knowledge of what the variable represents is obvious or unimportant (compared to other names)
- should be able to see in same screen/context (say more than +/- 7 lines) what/where x is assigned.

So all the time in comprehensions, or short loops/conditional blocks. Less so other places.]

2024-03-01 17:48 UTC, njharman commented on apps/contributions/stripe_sync.py
> +            charges = [y.id for y in x.charges.data if y.status != "failed"]
[If you agree this should be addressed, I'd suggest it is out of scope and put into another ticket/todo]

With prevalent use of CONSTANTS, the literal` "failed"` stood out to me

Isn't there some attribute/method from Django to use TextChoices for there "constants"?

I believe this is from ContributionStatus(TextChoices):

2024-03-01 17:48 UTC, njharman commented on apps/contributions/stripe_sync.py
> -        if payment_intent.charges.total_count > 1:
I'm unsure (just highlighting for you to double check),  I lack the depth of knowledge of stripe/payment business logic which you have.

Should this not also use and still raise if there are more than one `[y.id for y in x.charges.data if y.status != "failed"]`?

As is, cutting exception seems to include more than just "should not block contribution creation if there is only 1 successful charge".

2024-03-01 17:53 UTC, njharman approved these changes

2024-03-01 19:18 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +            charges = [y.id for y in x.charges.data if y.status != "failed"]
These are actually separate statuses (specific to stripe PaymentIntents),, so not something we're tracking as a ContributionStatus.

2024-03-04 14:18 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> -        if payment_intent.charges.total_count > 1:
It's okay to have >1 failed charge. That couuld happen if, for instance, a contributor attempts to checkout with bad credit card 1, again with bad credit card, and then a third time with a good credit card.   >1 successful charge is a problem because our system (for now) assumes that a single one-time contribution will have a single successful charge.

2024-03-05 06:17 UTC, x110dc requested changes

2024-03-05 06:17 UTC, x110dc commented on apps/contributions/stripe_sync.py
> +                    "Payment intent %s has more than one successful or pending charge so cannot be processed: %s",
Why are we doing this check? 

I ask because the Charge API is deprecated and Stripe advises not writing new code that uses so I wouldn't think they'd say that unless there were other (supported) ways of getting at whatever you need here. 

https://docs.stripe.com/payments/charges-api

2024-03-05 06:17 UTC, x110dc commented on apps/contributions/stripe_sync.py
> +        # We'll use processing as catch all. Concretrely, this would mean not refunded and one of other PI statuses of
typo: "Concretrely"

2024-03-05 06:17 UTC, x110dc commented on apps/contributions/stripe_sync.py
> +        if updated:
`else`?

2024-03-05 06:17 UTC, x110dc commented on apps/contributions/stripe_sync.py
> +        if updated:
Can updated and created both be true? If not should this be an `else`?

2024-03-05 12:59 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        # TODO: [DEV-4507] Remove this property and replace with a direct FK to RevenueProgram
All contributions should have a revenue program, but not all contributions have a donation page, so we do need an RP FK directly on contribution.

I suppose those two values could get out of sync, but I'm not sure there's a better approach here given the optionality around donation page and contributions.

Do you have any alternative suggestions?

2024-03-05 13:03 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +    """Class for sycning a stripe event to revengine. Uses existing webhook processor for this."""
9c96790d4

2024-03-05 13:04 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +        # We'll use processing as catch all. Concretrely, this would mean not refunded and one of other PI statuses of
9c96790d4

2024-03-05 13:27 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +        if updated:
Wasn't possible for it to be both given implementation of upsert_with_diff_check, but I ended up refactoring so that function returns a string value indicating action that was taken, and then updated calling code accordingly.

dd0707dcff5e

2024-03-05 13:27 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +        if updated:
Wasn't possible for it to be both given implementation of upsert_with_diff_check, but I ended up refactoring so that function returns a string value indicating action that was taken, and then updated calling code accordingly.

dd0707dcff5e

2024-03-05 13:32 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +        if updated:
Else do nothing. If you would like to have "did nothing" entry in logs, that can be added, but I figured the important thing to have a papertrail of is which contributions are created or updated.

Let me know.

2024-03-05 13:37 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +                contribution, created, updated = x.upsert()
I had left a comment from Norm's review about this for you to weigh in on, but there were changes and it got buried.

https://github.com/newsrevenuehub/rev-engine/pull/1410/files/3828cb09865c01b15460432a31a5fd811740e4c2#r1502718340

TLDR; i agree, but think we should do this in a follow up ticket.

2024-03-05 13:42 UTC, benjaminEwhite commented on apps/contributions/management/commands/sync_stripe_transactions_data.py
> +        self.stdout.write(self.style.HTTP_INFO("Running `sync_contribution_and_payments_from_stripe`"))
See similar comment here: https://github.com/newsrevenuehub/rev-engine/pull/1410/files/8ea15fbaa9d434283a6518583f259cbea094fc7a#r1512837602

2024-03-05 13:58 UTC, benjaminEwhite commented on apps/contributions/management/commands/sync_stripe_transactions_data.py
> +            StripeTransactionsSyncer(
dd5c124dafd

2024-03-05 14:08 UTC, benjaminEwhite commented on apps/contributions/management/commands/process_stripe_event.py
> +        parser.add_argument("--stripe_account", required=True)
d9eab1db09f

2024-03-05 16:23 UTC, njharman commented on apps/contributions/management/commands/process_stripe_event.py
> +        parser.add_argument("--stripe_account", required=True)
Ben already did it. Just adding '-', dash is the more common, across at least "modern" CLIs. In my experience and told by coworker E.S.

We should define it as our standard. https://news-revenue-hub.atlassian.net/wiki/spaces/TECH/pages/2047311873/Python+Style+Guide#Command-Line-Tools

2024-03-06 17:24 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +                contribution, created, updated = x.upsert()
Update. I ended up doing a pretty dep refactor and went ahead and took care of this. The task is now scoped to a single account.

2024-03-06 17:38 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        # TODO: [DEV-4507] Remove this property and replace with a direct FK to RevenueProgram
But if you go this route, then a page without contributions cannot be connected to a donation page.  I think a lot of stuff breaks if the link between rp and page is removed.

For instance:

- Pages need to know the RP slug, and that requires the page - rp linkage (so that URLs can be generated with correct subdomain).
- Access control for pages needs this linkage. A user has read/write access to pages based on the RPs in their role assignment. If pages don't have a link to RPs unclear how this is managed.

Probably other cases but these come to mind right away.

If we want to avoid denormalization at all costs, one alternative would be to create a "dummy" donation page for each revenue program, and use that page for imported contributions that don't have an RP.

Thoughts @njharman @x110dc ?

2024-03-06 17:40 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +        # Subscriptions are not directly attached to invoices, but we can get them from the respective charges.
This ends up going away altogether in refactored implementation of `stripe_import.py`.

2024-03-06 17:43 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +                    "Payment intent %s has more than one successful or pending charge so cannot be processed: %s",
While the charge api is deprecated for creating/changing charges, the charge object itself is not deprecated.  I confirmed this with a Stripe dev in discord.

That said, I also asked about `payment_intent.charges` property, which is not referenced in the API docs. Turns out that property is retired in newer versions of Stripe API, so relying on that would block us from upgrading Stripe.

With this in mind, I substantially refactored stripe_import.py to iterate over payment intents and retrieve charges separately.  

In addition to being compatible with current version of Stripe, new implementation is about 200 lines shorter.

2024-03-06 20:22 UTC, njharman approved these changes

2024-03-07 14:29 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        # TODO: [DEV-4507] Remove this property and replace with a direct FK to RevenueProgram
Yr understanding of data model is correct @njharman (and also your point about denormalization).  

Makes me lean more towards denorm + keep in sync.

I'm awaiting @x110dc weigh in before moving forward.

2024-03-07 18:18 UTC, njharman commented on apps/contributions/models.py
> +        # TODO: [DEV-4507] Remove this property and replace with a direct FK to RevenueProgram
After further investigation and explanation by DC.

I don't know. All options seem equivalently less good. I don't have enough scope of domain knowledge / project history to provide definitive advice.

But, I can still offer creating SQL constraint that will prevent denormalized fields from having diverging data.

2024-03-07 20:36 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        # TODO: [DEV-4507] Remove this property and replace with a direct FK to RevenueProgram
Call me Tony Blair, because i have a _third way_...

```python

class RevenueProgram(models.Model):
    # no changes

class DonationPage(models.Model):
    revenue_program = models.ForeignKey(RevenueProgram, on_delete=models.CASCADE)
    # no changes

class ContributionBase(models.Model):
    # gets existing Contribution fields EXCEPT for donation_page
    class Meta:
        abstract = True

class Contribution(ContributionBase):
    donation_page = models.ForeignKey(DonationPage, on_delete=models.CASCADE)

class ImportedContribution(Contribution):
    # how to *not* have donation_page?
    revenue_program = models.ForeignKey(RevenueProgram, on_delete=models.CASCADE)

```

This would require some refactoring of the relevant view and serializer, but not going to run that down here.


Seems like this approach would not have any syncing issues, and would also allow us to avoid having the (clunky from ORM perspective???) SQL constraint.

2024-03-07 20:57 UTC, x110dc commented on apps/contributions/stripe_sync.py
> +                contribution, created, updated = x.upsert()
I like that option @benjaminEwhite . Besides some refactoring are there downsides? 

I have another option as well – to use the default page. So I think there’s four options now:

1. create a dummy page (con: page limits, con: hide dummy page in user-facing UIs)
2. denormalize with two paths from a contribution to an RP (con: the two paths could get out of sync)
3. inherit from Contribution to make an ImportedContribution model (con: a refactor)
4. use the default page (con: the page a contribution came from may be technically incorrect (would this matter?))

From what I know now I like the new options: 3 or 4. But I'd like to hear more from y'all about what the downsides of each approach could be.

2024-03-07 21:04 UTC, x110dc commented on apps/contributions/models.py
> +        # TODO: [DEV-4507] Remove this property and replace with a direct FK to RevenueProgram
I like that option @benjaminEwhite . Besides some refactoring are there downsides? 

I have another option as well – to use the default page. So I think there’s four options now:

1. create a dummy page (con: page limits, con: hide dummy page in user-facing UIs)
2. denormalize with two paths from a contribution to an RP (con: the two paths could get out of sync)
3. inherit from Contribution to make an ImportedContribution model (con: a refactor)
4. use the default page (con: the page a contribution came from may be technically incorrect (would this matter?))

From what I know now I like the new options: 3 or 4. But I'd like to hear more from y'all about what the downsides of each approach could be.

2024-03-07 22:10 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        # TODO: [DEV-4507] Remove this property and replace with a direct FK to RevenueProgram
Not having to touch the models would be a big win, so that's appealing about 4.

A couple of things we'd have to address:

A  A revenue program is not currently guaranteed to have a default donation page. In the case of orgs that go through self sign up, their default page  currently only gets  assigned when they create their first page. That moment could be shifted to initial revenue program creation. And it could be that we take a calculated risk that the only instances of default-pageless RPs are ones that enter the system through self sign up (though at model level, it would still be possible for a default-pageless RP to exist).
B. Contribution.revenue_program currently uses on_delete=PROTECT. This means that if the org wants to delete a default donation page (which our system motivates people to do insofar as plan tiers have page limits), they'd be blocked if it has legacy donations pointing at it.  

LOE to address A in code is probably not that much, while B is probably higher. 

Altogether, in terms of code, LOE for option 3 or 4 is roughly comparable.

Unless.... there edge cases  or downsides re: 3 that we haven't identified.

2024-03-07 22:35 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        # TODO: [DEV-4507] Remove this property and replace with a direct FK to RevenueProgram
Also, fwiw, another possibility would be to try to identify any/all places in our code that expect their to be a stripe account ID available via contribution.donation_page.revenue_program.payment_provider.stripe_acccount_id and solve for that relationship differently.  We'd also want to track down any other assumptions in our code around contribution.donation_page.X. and  contribution.donation_page.revenue_program.X.   I don't have good sense of LOE of that without spending some time searching code.

2024-03-08 18:07 UTC, njharman commented on apps/contributions/models.py
> +        # TODO: [DEV-4507] Remove this property and replace with a direct FK to RevenueProgram
I can create new options too! ;)

5. Contribution has both DP and RP FKs. only one of which may be non-null (this is an easier "single table" SQL constraint, and easier to test for). Use @property(s) to hide implementation from users of Contribution. Something like this.

```
class Contribution(model)
   @property
   def revenue_program(self):
        return self._rp_fk or self._dp_fk.rp
   def save(self):
         if self._rp_fk and self._dp_fk:
            raise both
         if not self._rp_fk and not self._dp_fk
            raise neither
         super().save
```

2024-03-08 18:11 UTC, njharman commented on apps/contributions/models.py
> +        # TODO: [DEV-4507] Remove this property and replace with a direct FK to RevenueProgram
tldr tier list; 3 (assuming changes below which led me to option 5), 1, 2, 4

The root cause seems to be need for Contributions without Donation Page which doesn't match our [model hierarchy ](https://news-revenue-hub.atlassian.net/wiki/spaces/TECH/pages/2044559361/Rev+Engine+NRE+architecture+and+engineering+data+model). Which suggests the most direct, explicit "fix" to that. 1, 2, or 3.

1,4: The fact that users can't delete donation pages because Contributions are tied to them; seems like a big issue, no?  Can they "disable/turn off" page to no longer count against their limit? If so, then not a problem.

3: Do you mean ImportedContribution to inherit from **ContributionBase**?  Otherwise it will also have a donation_page FK. Which I assume is not null?  Contribution will have revenue_program property that gets it through donation_page?

Doesn't inherited models mean there are two tables of Contributions? Will have to remember to query both every time we want all contributions?... seems problematic.  Could probably do something with https://docs.djangoproject.com/en/5.0/topics/db/models/#proxy-model-managers 


I translate "speed of release, or elegance of solution" as "effort now vs (more) effort later"

[Funnily, Norm's knee jerk reaction to "refactor code" is that it's not a con. Maybe a even a pro cause you get to "fix stuff".]

2024-03-11 14:42 UTC, benjaminEwhite commented on apps/contributions/stripe_sync.py
> +        if updated:
Either way, ended up being a good prompt because I ended up having the `upsert_with_diff_check` return a single string value indicating if it updated, created, or did nothing, which simplifies things.

2024-03-11 19:53 UTC, x110dc approved these changes

2024-03-11 19:56 UTC, x110dc requested changes
Just want to make sure we capture the key points from the data model discussion somewhere. After that approved by me and doesn't need a re-review.

2024-03-11 19:56 UTC, x110dc commented on apps/contributions/models.py
> +        # TODO: [DEV-4507] Remove this property and replace with a direct FK to RevenueProgram
Are the takeaways from this discussion and a summary of the options captured in a ticket? @benjaminEwhite

2024-03-11 21:07 UTC, x110dc requested changes
No need to rereview.

2024-03-11 21:10 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        """Ensure there's onlly one successful or pending charge.
9f43b43c3

2024-03-11 21:17 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        if self.refunded:
Good point. The tuple matching is nifty.

cbbc6168

2024-03-11 21:25 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        """Retrieve a stripe entity for a given stripe account"""
That's a good point. Think I'll keep as is for now since that would introduce additional edge cases to test for (what happens if called with an entity id that's not in the mapping).

2024-03-13 21:18 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        # TODO: [DEV-4507] Remove this property and replace with a direct FK to RevenueProgram
Noting that we'll continue this discussion in https://news-revenue-hub.atlassian.net/jira/software/c/projects/DEV/issues/DEV-4562

2024-03-15 18:13 UTC, njharman approved these changes

2024-03-15 21:29 UTC, benjaminEwhite commented on apps/common/tests/test_utils.py
> +                assert result
758da9c9b46

2024-03-18 13:03 UTC, benjaminEwhite commented on apps/contributions/management/commands/process_stripe_event.py
> +    """Allows user to provide a Stripe event and acccount ID and then process that event using our webhookhandler."""
223796df0

2024-03-18 13:07 UTC, benjaminEwhite commented on apps/contributions/management/commands/import_stripe_transactions_data.py
> +        self.stdout.write(self.style.HTTP_INFO("Running `import_contribution_and_payments_from_stripe`"))
16039e52c

2024-03-18 13:23 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +            case _:
a66578735

2024-03-19 19:33 UTC, x110dc approved these changes

2024-03-22 17:11 UTC, merged