DEV-4347: Show placeholders for contribution detail instead of spinner in new portal
newsrevenuehub/rev-engine pull request #1421
Opened 2024-02-19 14:21 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
- Improves loading indicator for contribution detail
#### Why are we doing this? How does it help us?
- Improve UX
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
- yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
- yes
#### Have automated unit tests been added? If not, why?
- yes
#### How should this change be communicated to end users?
- n/a
#### Are there any smells or added technical debt to note?
- no 
#### Has this been documented? If so, where?
- no
#### What are the relevant tickets? Add a link to any relevant ones.
- https://news-revenue-hub.atlassian.net/browse/DEV-4347
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
- no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
- Parent ticket: https://news-revenue-hub.atlassian.net/browse/DEV-3780

2024-02-20 14:59 UTC, nrh-cklimas requested changes

2024-02-20 14:59 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/ContributionDetail.styled.ts
> +export const Desktop = styled.div`
It doesn't look like this style is used in `ContributionDetail`. Maybe a leftover from previous PRs? I removed it in something I did last week IIRC.

2024-02-20 14:59 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/ContributionDetail.tsx
> +  if (isLoading || contribution?.id !== contributionId) {
Is this change intended to handle when you click from one contribution to the other? If so, I think we have an issue with `usePortalContribution` we need to fix, probably by getting rid of `{ keepPreviousData: true }` there.

2024-02-20 14:59 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/LoadingSkeleton/LoadingSkeleton.stories.tsx
> +const LoadingSkeletonDemo = () => <LoadingSkeleton />;
Don't think we need this--can just make the `component` on line 7 `LoadingSkeleton` directly. I've been making demo components in Storybook either when we need some kind of enclosing component around it (like to provide context) or to make the Storybook controls more usable (when a prop is a JS object and hard to edit in Storybook).

2024-02-21 20:21 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/ContributionDetail.styled.ts
> +export const Desktop = styled.div`
You are right. I added it back by mistake during a merge conflict

2024-02-21 20:21 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/ContributionDetail.tsx
> +  if (isLoading || contribution?.id !== contributionId) {
Yes, I'll check to see if this solution works

2024-02-21 20:25 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/ContributionDetail.tsx
> +  if (isLoading || contribution?.id !== contributionId) {
It works 👍

2024-02-21 20:29 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/LoadingSkeleton/LoadingSkeleton.stories.tsx
> +const LoadingSkeletonDemo = () => <LoadingSkeleton />;
This was because I copied this file and made a "find & replace all" to change the component name. I didn't even notice I did that this wasn't needed. Fixed it

2024-02-21 21:35 UTC, nrh-cklimas approved these changes

2024-02-23 14:52 UTC, merged