DEV-4315: Mailchimp/Integrations page upsell prompt
newsrevenuehub/rev-engine pull request #1425
Opened 2024-02-21 13:14 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
- Updates Mailchimp and Salesforce cards
- Creates FeatureBadge component
- Remove self upgrade flag as per conversation in slack (https://newsrevenuehub.slack.com/archives/C0365F2046S/p1708463356766699) 
#### Why are we doing this? How does it help us?
Improve UX
Remove unnecessary feature flag (self upgrade)
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
yes
#### Have automated unit tests been added? If not, why?
yes
#### How should this change be communicated to end users?
n/a
#### Are there any smells or added technical debt to note?
no
#### Has this been documented? If so, where?
no
#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-4315
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2024-02-21 21:22 UTC, nrh-cklimas requested changes

2024-02-21 21:22 UTC, nrh-cklimas commented on spa/src/components/common/IntegrationCard/MailchimpIntegrationCard/MailchimpIntegrationCard.test.tsx
> +jest.mock('hooks/useUser');
Why is this needed when `useUser` was removed from MailchimpIntegrationCard?

2024-02-21 21:22 UTC, nrh-cklimas commented on spa/src/components/common/IntegrationCard/MailchimpIntegrationCard/MailchimpIntegrationCard.test.tsx
> +    it('calls "sendUserToMailchimp" mailchimp card', () => {
```suggestion
    it('calls sendUserToMailchimp when the connect button is clicked', () => {
```

2024-02-21 21:22 UTC, nrh-cklimas commented on spa/src/components/common/IntegrationCard/MailchimpIntegrationCard/MailchimpIntegrationCard.test.tsx
> +      expect(screen.queryByTestId('rightAction')).toBeNull();
```suggestion
      expect(screen.queryByText('Upgrade')).not.toBeInTheDocument();
      expect(screen.queryByTestId('rightAction')).not.toBeInTheDocument();
```

2024-02-21 21:22 UTC, nrh-cklimas commented on spa/src/components/common/IntegrationCard/MailchimpIntegrationCard/MailchimpIntegrationCard.tsx
> +    cornerMessage: showUpgradePrompt && (
It looks like all cards that set a `cornerMessage` prop are wrapping it in a `CornerMessage` div. Let's put that around the content in `IntegrationCard`--I think having a component import styles from another can lead to unintended side effects when a change is needed later.

2024-02-21 21:22 UTC, nrh-cklimas commented on spa/src/components/settings/Subscription/ManageSubscription.test.tsx
>    describe('When the user has a nonfree plan and the self-upgrade feature flag', () => {
```suggestion
  describe('When the user has a nonfree plan', () => {
```

2024-02-21 21:22 UTC, nrh-cklimas commented on spa/src/components/settings/Subscription/UpgradePlan.test.tsx
Can't comment on it directly, but lines 122 on here have mentions of feature flags. I think the last two tests can now be combined into one.

2024-02-21 21:22 UTC, nrh-cklimas commented on spa/src/components/content/customize/Customize.test.tsx
> -      it('should render core upgrade prompt with the user', () => {
I think most of this test should still remain, just the check around `dataset.user`?

2024-02-22 13:47 UTC, GuiMend commented on spa/src/assets/icons/award_star.svg
I ok with adding this library instead of managing the asset itself. Both are less-than-ideal ways to handle it, but it's what we need to do to have this icon available.

2024-02-22 16:17 UTC, GuiMend commented on spa/src/components/content/customize/Customize.test.tsx
> -      it('should render core upgrade prompt with the user', () => {
It doesn't make sense to have this test anymore because the upgrade prompt no longer receives the **user** as a prop

2024-02-23 15:03 UTC, nrh-cklimas commented on spa/src/components/settings/Subscription/UpgradePlan.test.tsx
>    it('displays nothing if the user is on the Plus plan, even if they have the self-upgrade feature flag', () => {
```suggestion
  it('displays nothing if the user is on the Plus plan', () => {
```

2024-02-23 15:05 UTC, nrh-cklimas commented on spa/src/components/content/customize/Customize.test.tsx
> -      it('should render core upgrade prompt with the user', () => {
What about `expect(upgradePrompt).toBeVisible()`? I don't see a test for that elsewhere but I might be missing it.

2024-02-23 16:20 UTC, GuiMend commented on spa/src/components/content/customize/Customize.test.tsx
> -      it('should render core upgrade prompt with the user', () => {
Sure, makes sense. Added it back 👍

2024-02-23 19:01 UTC, nrh-cklimas approved these changes

2024-03-01 14:46 UTC, merged