DEV-4482: Don't let contributors see rejected or processing contributions
newsrevenuehub/rev-engine pull request #1429
Opened 2024-02-23 16:44 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

Filters out rejected and processing contributions from new endpoints. They don't appear in contribution lists and trying interact with detail (GET, PATCH, DELETE) returns a 404.

#### Why are we doing this? How does it help us?

These shouldn't be visible to contributors.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

Yes.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No..?

#### Have automated unit tests been added? If not, why?

Yes.

#### How should this change be communicated to end users?

n/a

#### Are there any smells or added technical debt to note?

No.

#### Has this been documented? If so, where?

No.

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-4482

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No.

2024-02-23 22:16 UTC, benjaminEwhite requested changes
Looks good. Think we need to include REJECTED and FLAGGED statuses. And probably can just inline some of the logic (in spit of what i advised when we huddled).

2024-02-23 22:16 UTC, benjaminEwhite commented on apps/contributions/views.py
> +    HIDDEN_STATUSES = [ContributionStatus.FAILED, ContributionStatus.PROCESSING]
I think we also want `REJECTED` and `FLAGGED` here.

2024-02-23 22:16 UTC, benjaminEwhite commented on apps/contributions/views.py
> +
Notwithstanding my advice when we huddled @nrh-cklimas i think this doesn't really need its own separate method. I didn't realize that it would be a one liner/this easy. In that case, might as well just do it inline at line 623. In this case, I think the "native" django code is self-documenting.

2024-02-23 22:16 UTC, benjaminEwhite commented on apps/contributions/tests/test_views.py
> +    @pytest.mark.parametrize("contribution_status", (ContributionStatus.FAILED, ContributionStatus.PROCESSING))
See note below, but think we should also have rejected and flagged here.

2024-02-26 15:03 UTC, nrh-cklimas commented on apps/contributions/views.py
> +
Updated in 396e562c9356b2a04efeef513f24ab32b70da47f

2024-02-26 15:03 UTC, nrh-cklimas commented on apps/contributions/tests/test_views.py
> +    @pytest.mark.parametrize("contribution_status", (ContributionStatus.FAILED, ContributionStatus.PROCESSING))
Updated in db58f0c93f53169becaee0b2d5e1f34955b4827c

2024-02-26 15:03 UTC, nrh-cklimas commented on apps/contributions/views.py
> +    HIDDEN_STATUSES = [ContributionStatus.FAILED, ContributionStatus.PROCESSING]
Updated in db58f0c93f53169becaee0b2d5e1f34955b4827c

2024-02-27 14:43 UTC, benjaminEwhite requested changes
@nrh-cklimas I missed on first time review that "FAILED" is one of the excluded statuses in this PR, and as commented in line, I don't think that's one we should be excluding.

Other than that, things look good. I made some totally optional suggestions for drying up tests.

Only other request is to update PR description to reflect the final state of excluded contribution statuses.

2024-02-27 14:43 UTC, benjaminEwhite commented on apps/contributions/tests/test_views.py
> +    )
**Optional suggestion**

Chris, this is more a "just so you know". Since these same statuses get used across several tests, another approach would be to create a fixture called something like "excluded_contributor_status" and then add that as a parameter for the test functions that need it.

```
@pytest.fixture(params=[ContributionStatus.FAILED, ..., ContributionStatus.REJECTED]
def excluded_contributor_status(self, request):
    return request.param
```

if you include `excluded_contributor_status` as param (instead of current `status`), pytest will run the test once for each of the statuses in the fixture params.

2024-02-27 14:43 UTC, benjaminEwhite commented on apps/contributions/tests/test_views.py
> +    def test_contributions_detail_when_hidden_status(
**Optional suggestion**

Looks like for the different detail methods, the test code is pretty much the same. Could combine into a single test, and parametrize the HTTP method (which will give you cross product of status params + method params -- also true if you went with the fixture approach mentioned above).

```
    @pytest.mark.parametrize(
        "contribution_status",
        (
            ContributionStatus.FAILED,
            ContributionStatus.FLAGGED,
            ContributionStatus.PROCESSING,
            ContributionStatus.REJECTED,
        ),
    )
    @pytest.mark.parametrize("http_method", ("delete", "get", "patch"))
  def test_contributions_detail_view_when_hidden_status(
        self, contribution_status, http_method, api_client, one_time_contribution, portal_contributor_with_multiple_contributions
    ):
        contributor = portal_contributor_with_multiple_contributions[0]
        one_time_contribution.status = contribution_status
        one_time_contribution.save()
        api_client.force_authenticate(contributor)
        response = getattr(api_client, http_method)(
            reverse(
                "portal-contributor-contribution-detail",
                args=(
                    contributor.id,
                    one_time_contribution.id,
                ),
            )
        )
        assert response.status_code == status.HTTP_404_NOT_FOUND
        assert response.json() == {"detail": "Contribution not found"}
```

2024-02-27 14:43 UTC, benjaminEwhite commented on apps/contributions/views.py
> +
@nrh-cklimas I missed this first time around, but I don't think we want to excluded "failed". That status can happen (among other reasons) if the payment method on a recurring contribution expires.

Also don't see "failed" mention in AC for ticket.

2024-03-01 18:20 UTC, nrh-cklimas commented on apps/contributions/tests/test_views.py
> +    )
Curious what your opinion would be of importing HIDDEN_STATUSES and using that as a basis for the fixture. We sometimes do similar things on the SPA side but there's always the danger of the test being vacuously true--e.g. if HIDDEN_STATUSES has incorrect values, tests still pass.

2024-03-01 18:33 UTC, nrh-cklimas commented on apps/contributions/views.py
> +
Updated in 2ff011339f5e1417c308344bbd71437ed3d6eee4

2024-03-04 15:11 UTC, benjaminEwhite approved these changes
LGTM. Approved.

2024-03-04 15:11 UTC, benjaminEwhite commented on apps/contributions/tests/test_views.py
> +    )
I like that idea (but leave it up to you whether or not you want to act on it).

2024-03-04 16:16 UTC, nrh-cklimas commented on apps/contributions/tests/test_views.py
> +    )
I got a little lost in details trying to do this so I think I'll try this next time and ask for help.

2024-03-06 14:22 UTC, merged