DEV-4431: Add secondary sorting field to New Portal
newsrevenuehub/rev-engine pull request #1432
Opened 2024-02-28 13:50 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
- Adds support for New Portal to order contributions by multiple fields (ex: status + date[new first])
- Update FE New Portal sort field to fetch:
   - Status + Date descending (new first)
   - Amount + Date descending (new first)

#### Why are we doing this? How does it help us?
- To better present relevant data to the user in new portal
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
- yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
- no
#### Have automated unit tests been added? If not, why?
- yes
#### How should this change be communicated to end users?
- n/a
#### Are there any smells or added technical debt to note?
- no
#### Has this been documented? If so, where?
- no
#### What are the relevant tickets? Add a link to any relevant ones.
- https://news-revenue-hub.atlassian.net/browse/DEV-4431
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
- no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
- no

2024-02-28 13:54 UTC, GuiMend commented on apps/contributions/views.py
> +    ALLOWED_ORDERING_FIELDS = ["created", "amount", "status"]
I don't think we are using this `ALLOWED_ORDERING_FIELDS` @benjaminEwhite. Should I remove this line?

_btw: I added the "status" here in case we do use this variable and I didn't find out where_

2024-03-01 14:40 UTC, benjaminEwhite requested changes
@GuiMend made a suggestion for using OrderingFilter. Otherwise, backend code looks good. Didn't review SPA code changes.

2024-03-01 14:40 UTC, benjaminEwhite commented on apps/contributions/views.py
> +    ALLOWED_ORDERING_FIELDS = ["created", "amount", "status"]
You're right! This wasn't being used, but I think we should keep around (see suggestion below).

2024-03-01 14:40 UTC, benjaminEwhite commented on apps/contributions/views.py
>      def contributions_list(self, request, pk=None):
We can lean a bit more on DRF OrderingFilter here.

Would need to import OrderingFilter at top of module (`from rest_framework.filters import OrderingFilter`).

```python
@action(
        methods=["get"],
        url_path="contributions",
        url_name="contributions-list",
        detail=True,
        serializer_class=serializers.PortalContributionListSerializer,
    )
def contributions_list(self, request, pk=None):
        """Endpoint to get all contributions for a given contributor"""
        contributor = self._get_contributor_and_check_permissions(request, pk)

        filters = {}
        for k in self.ALLOWED_FILTER_FIELDS:
            if (v := self.request.query_params.get(k)) is not None:
                filters[k] = v

        ordering_filter = OrderingFilter()
        ordering_filter.ordering_fields = self.ALLOWED_ORDERING_FIELDS
        qs = contributor.contribution_set.filter(**filters)
        qs = (
            ordering_filter.filter_queryset(request, qs, self)
            if request.query_params.get("ordering")
            else qs.order_by(*self.DEFAULT_ORDERING_FIELDS)
        )
        paginator = self.pagination_class()
        page = paginator.paginate_queryset(qs, request)
        serializer = self.get_serializer(page, many=True)
        return paginator.get_paginated_response(serializer.data)

```

I tried  this change and ran view tests locally, and everything passes.

2024-03-04 15:21 UTC, benjaminEwhite approved these changes

2024-03-04 18:43 UTC, nrh-cklimas approved these changes

2024-03-08 18:51 UTC, merged