DEV-4500-convert-local-storage-based-auth-to-session-storage-instead
newsrevenuehub/rev-engine pull request #1446
Opened 2024-03-05 15:47 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
Swaps new portal authentication from localStorage to sessionStorage so that the user "logs out" when the tab is closed
#### Why are we doing this? How does it help us?
Implementing a logout to new portal
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
no
#### Have automated unit tests been added? If not, why?
yes
#### How should this change be communicated to end users?
Closing the tab logs the donors out of the new portal
#### Are there any smells or added technical debt to note?
no
#### Has this been documented? If so, where?
no
#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-4500
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2024-03-05 16:31 UTC, nrh-cklimas requested changes

2024-03-05 16:31 UTC, nrh-cklimas commented on spa/src/components/contributor/ContributorVerify.jsx
> +      sessionStorage.setItem(LS_CONTRIBUTOR, JSON.stringify(response.data.contributor));
I think this will cause problems for the existing portal because ContributorVerify is used by both workflows. I think the best we can do right now is to set both here, but I kind of like the idea of using a different constant than `LS_CONTRIBUTOR` for the session storage key (could even be the same value, just a different constant) to make it obvious if we accidentally use the wrong key in the future.

While we're here... do you think it would expand scope a lot to convert this component to TypeScript and/or add tests? I think unit tests are more valuable if I had to pick between the two.

2024-03-05 16:31 UTC, nrh-cklimas commented on spa/src/utilities/isAuthenticated.ts
> +    return window.sessionStorage.getItem(LS_CONTRIBUTOR) !== null;
Either:

- Need a check here for either local or session storage, so that we keep auth working the same in the existing portal.
- We create a new component like ProtectedRoute that looks at session storage only.

2024-03-05 16:31 UTC, nrh-cklimas commented on spa/src/hooks/usePortalAuth.test.tsx
We should update the test descriptions to say "session storage" instead of "local storage" to avoid confusion.

2024-03-06 14:40 UTC, nrh-cklimas requested changes
Changes in code look good! There are still some lingering mentions of local storage in comments that should be cleaned up in usePortalAuth.ts.

- Line 91: should rewrite the comment to explain auth changes made here to ProtectedRoute
- Line 127: "their local storage" -> "their session storage"

2024-03-06 20:10 UTC, GuiMend commented
> Changes in code look good! There are still some lingering mentions of local storage in comments that should be cleaned up in usePortalAuth.ts.
> 
> * Line 91: should rewrite the comment to explain auth changes made here to ProtectedRoute
> * Line 127: "their local storage" -> "their session storage"

@nrh-cklimas , the only mention left in `usePortalAuth` is supposed to continue as local storage.

```js
  it('saves the CSRF token to local storage', async () => {
        tree();
        expect(window.localStorage.getItem(LS_CSRF_TOKEN)).toBe(null);
```

Not sure about what you mean by on line 91: 
![image](https://github.com/newsrevenuehub/rev-engine/assets/9381325/a66e6390-5e14-411a-a040-1b2df36e7ff2)

2024-03-06 20:41 UTC, nrh-cklimas commented
> @nrh-cklimas , the only mention left in `usePortalAuth` is supposed to continue as local storage.

I meant in usePortalAuth.tsx, not usePortalAuth.test.tsx.

2024-03-06 21:09 UTC, nrh-cklimas approved these changes

2024-03-08 14:16 UTC, merged