DEV-3877: Add top buttons to contributor portal
newsrevenuehub/rev-engine pull request #1448
Opened 2024-03-07 21:37 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

Adds buttons to go to an RP's web site and make a new contribution to the contributor portal.

#### Why are we doing this? How does it help us?

Continues implementation of the new portal.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

Yes.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

Need to add/update docs around how the buttons are configured.

#### Have automated unit tests been added? If not, why?

Yes.

#### How should this change be communicated to end users?

Updated docs.

#### Are there any smells or added technical debt to note?

No.

#### Has this been documented? If so, where?

No.

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-3877

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No.

2024-03-08 16:35 UTC, GuiMend requested changes
There is one test with the wrong title. Besides that, ✅

2024-03-08 16:35 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionsHeader/ContributionsHeader.test.tsx
> +  it("doesn't show a Return to Website link if not given a default page", () => {
```suggestion
  it("doesn't show a Make A New Contribution link if not given a default page", () => {
```

2024-03-08 18:52 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionsHeader/ContributionsHeader.test.tsx
> +  it("doesn't show a Return to Website link if not given a default page", () => {
Copy/paste got me :(

2024-03-11 15:19 UTC, GuiMend approved these changes

2024-03-12 13:36 UTC, merged