DEV-3435: Allow Org Admin to configure "other" contribution amount option on a per-frequency basis
newsrevenuehub/rev-engine pull request #1449
Opened 2024-03-12 21:32 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
- Adds "other" amount fields on a per frequency basis
- Migrates the legacy allowOther format to the new format
- Updates DAmount to render "other" field based on legacy or new format
#### Why are we doing this? How does it help us?
- Allow orgs to specify which frequencies they want to allow for custom donation amounts

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
yes
#### Have automated unit tests been added? If not, why?
yes
#### How should this change be communicated to end users?
You can now allow donors to select a custom donation amount per frequency.
#### Are there any smells or added technical debt to note?
no
#### Has this been documented? If so, where?
n/a
#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3435
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2024-03-13 19:31 UTC, nrh-cklimas requested changes

2024-03-13 19:31 UTC, nrh-cklimas commented on spa/src/components/pageEditor/elementEditors/amount/AmountEditor.tsx
> +    // Migrate legacy data to the new format on first render.
```suggestion
    // Migrate legacy data to the new format.
```
The effect will run whenever `elementContent` changes, so this comment's a little misleading.

2024-03-13 19:31 UTC, nrh-cklimas commented on spa/src/components/pageEditor/elementEditors/amount/AmountEditor.tsx
> +    const newInterval = [...(elementContent.options[interval] ?? []), value].sort((a, b) => {
I don't think this custom sort is needed. `[2, 1, 'other', 3].sort()` gives me `[1, 2, 3, 'other']`.

2024-03-13 19:31 UTC, nrh-cklimas commented on spa/src/components/pageEditor/elementEditors/amount/AmountEditor.tsx
> +            <AllowOtherFormControlLabel
How about moving this into `AmountInterval`? I think it could simplify things a little, as you could combine `handleAddAmount` here with `handleOtherChange`.

2024-03-13 19:31 UTC, nrh-cklimas commented on spa/src/components/pageEditor/elementEditors/amount/AmountEditor.test.tsx
> +                [frequency]: [...(elementContent.options?.[frequency] ?? []), 'other']
```suggestion
                [frequency]: [...elementContent.options[frequency]!, 'other']
```
We know that `elementContent.options` will be defined here.

2024-03-13 19:31 UTC, nrh-cklimas commented on spa/src/components/pageEditor/elementEditors/amount/AmountEditor.tsx
> +        },
```suggestion
        options: Object.entries(elementContent.options).reduce(
            (acc, [interval, options]) => ({
              ...acc,
              [interval]: options.includes('other') ? options : [...options, 'other']
            }),
            {}
          ),
```

Don't need the outermost spread here.

2024-03-13 20:06 UTC, nrh-cklimas commented on spa/src/components/pageEditor/elementEditors/amount/AmountEditor.test.tsx
> +      it('updates element content when changed', () => {
For the sake of coverage, we should have a test for the opposite direction, where unchecking the checkbox removes the other option.

2024-03-18 15:30 UTC, GuiMend commented on spa/src/components/pageEditor/elementEditors/amount/AmountEditor.tsx
> +            <AllowOtherFormControlLabel
I was making this change @nrh-cklimas, but it actually makes things a bit uglier. Can we leave it here?

2024-03-18 17:57 UTC, GuiMend commented on spa/src/components/pageEditor/elementEditors/amount/AmountEditor.tsx
> +    const newInterval = [...(elementContent.options[interval] ?? []), value].sort((a, b) => {
It doesn't work. JS limitation, https://www.w3schools.com/jsref/jsref_sort.asp

![image](https://github.com/newsrevenuehub/rev-engine/assets/9381325/3eac115c-e841-48d5-902e-7a18cd1ecf9c)

2024-03-18 21:29 UTC, nrh-cklimas commented on spa/src/components/pageEditor/elementEditors/amount/AmountEditor.tsx
> +    const newInterval = [...(elementContent.options[interval] ?? []), value].sort((a, b) => {
Wow, didn't know this! Thanks for the info.

2024-03-18 21:30 UTC, nrh-cklimas commented on spa/src/components/pageEditor/elementEditors/amount/AmountEditor.tsx
> +            <AllowOtherFormControlLabel
OK, works for me if you'd tried it.

2024-03-18 21:39 UTC, nrh-cklimas approved these changes

2024-03-20 18:11 UTC, merged