DEV-4477 | Add filtering by revenue program to portal contributor contributions endpoint
newsrevenuehub/rev-engine pull request #1450
Opened 2024-03-13 23:18 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2024-03-14 02:33 UTC, benjaminEwhite commented on apps/contributions/tests/test_views.py
> +            ContributionFactory.create_batch(size=2, status=ContributionStatus.PAID)
Added these changes around status because they were causing test failures when factory created non-viewable statuses.

2024-03-18 05:52 UTC, njharman requested changes

2024-03-18 05:52 UTC, njharman commented on apps/contributions/views.py
> +        return PortalContributionFilter().filter_queryset(request, queryset)
Is this part of DRF "machinery"?  I don't see this method being called anywhere in our code.

It's uncovered by unittests. So must be deletable ;)

2024-03-18 05:52 UTC, njharman commented on apps/contributions/views.py
> +    def handle_ordering(self, request, queryset):
Can we not use DRF filter_backends and ordering_fields? Not work with view_sets? 

https://www.django-rest-framework.org/api-guide/filtering/#specifying-which-fields-may-be-ordered-against

2024-03-18 05:52 UTC, njharman commented on apps/contributions/views.py
> +    # NB: This view is about returning contributor.contributions and never returns contributors, but
This is out of scope, probably ignorable. [without looking deeply there seems a fair bit of code to work around DRF expectations. I like less code.]

Why is this not Contributions.objects.all() and instead of `contributor.contribution_set`, filter viewsets query .filter(contributor=self.._get_contributor...(request, pk). 

Could then make` queryset = Contributions.objects.exclude(status__in=HIDDEN_STATUSES)` and not have to remember to use exclude_hidden_statuses method

2024-03-18 05:52 UTC, njharman commented on apps/contributions/views.py
> +    def paginate_results(self, queryset, request):
Don't like that request and queryset params are reversed compared to handle_ordering().  Are these overriding DRF methods which dictate parameter order? 

[edit oh, because paginator.paginate_queryset() param order?  Even if I'd make it match the order of this Viewsetclass (hide implementation detail of paginator.paginate_queryset) from this "layer".]

request is often first param in Django/DRF methods I believe.

2024-03-18 05:52 UTC, njharman commented on apps/contributions/views.py
> +    def paginate_results(self, queryset, request):
It annoys me that this method is between the @action methods.  Would like all the @action to be right next to each other.  As they are the mental "entry points" to this view set. Other methods are in support of the them.

2024-03-18 05:52 UTC, njharman commented on apps/contributions/filters.py
> +                filters[field] = value
Does (value := in dictionary comprension) work this way? too tricky?

filters = {x: value for x in self.ALLOWED_FILTER_FIELDS if x != "revenue_program" and (value :=  request.query_params.get(field)}

2024-03-18 05:52 UTC, njharman commented on apps/contributions/filters.py
> +            value = request.query_params.get(field)
you explicitly set default below `.get("revenue_program", None)`.  Is default not require here too?

2024-03-18 13:47 UTC, benjaminEwhite commented on apps/contributions/filters.py
> +            value = request.query_params.get(field)
Good catch!  0d48262a98

2024-03-18 13:51 UTC, benjaminEwhite commented on apps/contributions/filters.py
> +                filters[field] = value
Think that gets a little too tricky (for me) to read, so would like to keep as is.

2024-03-18 13:53 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        return PortalContributionFilter().filter_queryset(request, queryset)
Yeah, missed removing this.   3b17018

2024-03-18 14:04 UTC, benjaminEwhite commented on apps/contributions/views.py
> +    def paginate_results(self, queryset, request):
1f65c7d88

2024-03-18 14:05 UTC, benjaminEwhite commented on apps/contributions/views.py
> +    def paginate_results(self, queryset, request):
89cf6173e

2024-03-18 17:48 UTC, njharman approved these changes

2024-03-18 17:48 UTC, njharman commented on apps/contributions/views.py
> +    def handle_ordering(self, request, queryset):
Fair enough. But I'm suggesting making initial queryset model be Contributions.  and using the reverse FK Contributions.filter(where contributor_id == contributor)

But sure out of scope.

2024-03-18 17:48 UTC, njharman commented on apps/contributions/views.py
> +    def paginate_results(self, queryset, request):
Well did the opposite, but it is consistent so ok.

2024-03-19 19:16 UTC, x110dc approved these changes

2024-03-21 14:39 UTC, merged