DEV-3930: Map domains using HOST_MAP env variable
newsrevenuehub/rev-engine pull request #1451
Opened 2024-03-14 13:45 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

Adds a `HOST_MAP` environment variable. It's a JSON-encoded string that maps hostnames -> RP slugs. Code is modified here to use this mapping when:

- Deciding what contribution page to show
- Deciding what RP a contributor portal belongs to
- Sending login links to the contributor portal

On the SPA side, I replaced `useSubdomain()` with `getRevenueProgramSlug()` because a) doesn't need to be a hook b) make it clearer what it is actually doing—it's not just parising a domain name for the subdomain. It's now also doing hostname mapping.

#### Why are we doing this? How does it help us?

Enables us to serve contribution pages at client-owned domains.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

Yes.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No.

#### Have automated unit tests been added? If not, why?

Yes.

#### How should this change be communicated to end users?

Setting up a custom domain is a manual process we will do with clients.

#### Are there any smells or added technical debt to note?

No.

#### Has this been documented? If so, where?

I have a Confluence page talking through the approach linked in Jira.

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-3930

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

Not needed before deploy, but we will need to modify the `ALLOWED_HOSTS` and `HOST_MAP` environment variables eventually.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No.

2024-03-18 14:34 UTC, GuiMend approved these changes
LGTM

2024-03-18 15:05 UTC, benjaminEwhite requested changes

2024-03-18 15:05 UTC, benjaminEwhite commented on apps/common/utils.py
> +        pass
This is not super well considered, just a gut reaction, but seems to me we should only have to look at settings.HOST_MAP in a single place. I don't like that conditionality around this is turning up in two places. Would prefer calling context to determine if we're dealing with a custom domain, and if need be, have a separate function for generating subdomain from custom.

The edge case I mentioned above (what if map is valid, but custom domain is not in it) would also need to be handled here, which is probably a good indicator that need to dry up, probably in calling context.

2024-03-18 15:05 UTC, benjaminEwhite commented on revengine/settings/base.py
> +# of { "customhostname.org": "rp-slug" } values.
consider linking to the confluence wiki here for more info.

2024-03-18 21:05 UTC, nrh-cklimas commented on apps/api/tests/test_views.py
> +    settings.HOST_MAP = '{"custom.example.com":"test-rp-slug"}'
Updated in 2eaa00159043c93e99c3d9743f8cade2436a0e98

2024-03-18 21:05 UTC, nrh-cklimas commented on apps/api/tests/test_views.py
> +        assert "custom.example.com" == construct_rp_domain("custom", "")
Updated in 2eaa00159043c93e99c3d9743f8cade2436a0e98

2024-03-18 21:05 UTC, nrh-cklimas commented on apps/common/tests/test_utils.py
> +
Updated in 2eaa00159043c93e99c3d9743f8cade2436a0e98

2024-03-18 21:06 UTC, nrh-cklimas commented on revengine/settings/base.py
> +# of { "customhostname.org": "rp-slug" } values.
Going to hold off on this til we've proven this out completely.

2024-03-18 21:06 UTC, nrh-cklimas commented on apps/api/views.py
> +                return hostname
The logic falls through to the existing code. Should that be explicit or commented?

2024-03-18 21:11 UTC, nrh-cklimas commented on apps/api/views.py
> +    except json.JSONDecodeError:
Updated (narrowly) in 87d10ab079b758751f96979d86e908fa4bf34f94; did the truthy check but not the separate function, as we discussed.

2024-03-20 18:15 UTC, benjaminEwhite requested changes

2024-03-20 19:41 UTC, nrh-cklimas commented on apps/api/tests/test_views.py
> +        assert "custom.example.com" == construct_rp_domain("test-rp-slug", "")
I agree on this: 7bef913415fb13246af0d937d93a243e0197aa23

2024-03-20 19:44 UTC, nrh-cklimas commented on apps/api/tests/test_views.py
> +    with override_settings(SITE_URL="https://custom.example.com"):
Fixed the override_settings calls in 4040fc22b7e853d6e4706905907073738e5ad919, and you're right--we need to test that SITE_URL doesn't match the custom hostname, so I updated that too.

2024-03-20 19:44 UTC, nrh-cklimas commented on apps/api/tests/test_views.py
> +    settings.HOST_MAP = '{"custom.example.com":"test-rp-slug"}'
Added this in 7bef913415fb13246af0d937d93a243e0197aa23

2024-03-20 19:44 UTC, nrh-cklimas commented on apps/api/tests/test_views.py
> +def test_construct_rp_domain(expected, site_url, post, header, settings):
Added in 7bef913415fb13246af0d937d93a243e0197aa23

2024-03-20 19:46 UTC, nrh-cklimas commented on apps/api/views.py
> +                    return hostname
I think we can't do this because we want to skip this loop if `map` fails to get set.

2024-03-20 21:18 UTC, nrh-cklimas commented on apps/api/views.py
>  def construct_rp_domain(subdomain, referer=None):
Added to DEV-4575.

2024-03-20 21:20 UTC, nrh-cklimas commented on apps/common/utils.py
> +            # Continue. Either the variable isn't set or is malformed JSON.
Fixed in abd81ab37fa67749cadaf7eb324a18feddfe83f3

2024-03-20 21:21 UTC, nrh-cklimas commented on apps/common/utils.py
> +                return map[host]
Replied on the other comment.

2024-03-20 21:21 UTC, nrh-cklimas commented on apps/api/views.py
> +            # Continue. Either the variable isn't set or is malformed JSON.
Fixed in abd81ab37fa67749cadaf7eb324a18feddfe83f3

2024-03-20 21:21 UTC, nrh-cklimas commented on apps/api/views.py
> +            logger.warning("settings.HOST_MAP couldn't be parsed as JSON; continuing")
Updated in abd81ab37fa67749cadaf7eb324a18feddfe83f3

2024-03-20 21:36 UTC, nrh-cklimas commented on apps/common/tests/test_utils.py
> +    assert resultant_subdomain == "custom"
Updated in c5e6cf083775e0728f44aeb16014d0c9f7e97698

2024-03-20 21:38 UTC, nrh-cklimas commented on apps/common/utils.py
> +def get_subdomain_from_request(request) -> str | None:
Added in ce19c5efc6bff0138f80c4139b3fcf29530627b9

2024-03-20 21:40 UTC, nrh-cklimas commented on apps/api/views.py
> +                if slug == subdomain:
I'll push back on this a little bit on the grounds of readability, at least for novices like myself :).

2024-03-21 12:50 UTC, benjaminEwhite commented on apps/api/views.py
> +                if slug == subdomain:
That's fine. FWIW, `next` is pretty idiomatic, but map here is unlikely to be huge, so iterating over the entire set of items is not going to be costly.

2024-03-21 12:54 UTC, benjaminEwhite commented on apps/common/utils.py
> +                return map[host]
Ditto re: `else`

2024-03-21 13:23 UTC, benjaminEwhite requested changes
Looking good. Can use `else` with try/except in those two blocks where we have conversation thread.

2024-03-21 14:04 UTC, nrh-cklimas commented on apps/api/views.py
> +                    return hostname
b79d34b6847ea6a21e50618281ef6214366ef969

2024-03-21 17:52 UTC, benjaminEwhite approved these changes

2024-03-24 18:08 UTC, njharman requested changes

2024-03-24 18:08 UTC, njharman commented on apps/api/views.py
> +            logger.exception("settings.HOST_MAP couldn't be parsed as JSON; continuing")
This code is duplicated. Why do we not have this code in settings, once. 

```
try:
      HOST_MAP = json.loads(os.getenv("HOST_MAP", ""))
except json.JSONDecodeError:
      logger.exception("settings.HOST_MAP couldn't be parsed as JSON; continuing")
else:
    HOST_MAP = {}
```
Also have to change SPA_ENV_VAR `"HOST_MAP": os.getenv("HOST_MAP", "")`


Then here we can just:

```
for hostname, slug in settings.HOST_MAP.items():
     if slug == subdomain:
         logger.info("Mapped %s to %s", subdomain, hostname)
         return hostname 
```

and in utils.py:

```
if host in settings.HOST_MAP:
    return map[host]
```


Finally, should avoid overwriting python builtins `map()` ;)

2024-03-24 18:29 UTC, njharman requested changes

2024-03-24 18:29 UTC, njharman commented on apps/common/tests/test_utils.py
> +        (custom_map, f"rp-slug.{test_domain}", "rp-slug"),
Is it intended that this test produces double dots "rp-slug..test.org" ?

2024-03-25 17:46 UTC, nrh-cklimas commented on apps/common/tests/test_utils.py
> +        (custom_map, f"rp-slug.{test_domain}", "rp-slug"),
Nope--fixed in 16230b8d1309129cfc267f47333401e94e3ac07f. I didn't need to change any functionality once I updated this test, so I think the algorithm is just forgiving of multiple dots.

2024-03-25 17:51 UTC, nrh-cklimas commented on apps/api/views.py
> +            logger.exception("settings.HOST_MAP couldn't be parsed as JSON; continuing")
Updated in 16230b8d1309129cfc267f47333401e94e3ac07f. Two things I wasn't sure about:

- Usage of `logger` inside of the settings module--my inclination was to declare `logger = ...` at the top of the module, but it depends on a setting defined later in the module.
- If we need testing around parse failure in the settings module, and if so, how to do that.

2024-03-26 21:01 UTC, njharman approved these changes

2024-03-28 21:28 UTC, x110dc approved these changes

2024-03-28 21:28 UTC, x110dc commented on apps/common/utils.py
> +    if host in settings.HOST_MAP:
This is fine and perfectly readable but some may argue that it would more pythonic to ask forgiveness than permission by wrapping it in try/except with a KeyError.

2024-03-28 21:31 UTC, nrh-cklimas commented on apps/common/utils.py
> +    if host in settings.HOST_MAP:
Like this?

```python
try:
  return settings.HOST_MAP[host]
except KeyError:
  pass
```

2024-03-28 21:32 UTC, x110dc commented on apps/common/utils.py
> +    if host in settings.HOST_MAP:
Yes.

2024-03-28 21:33 UTC, x110dc commented on apps/common/utils.py
> +    if host in settings.HOST_MAP:
https://realpython.com/python-lbyl-vs-eafp/

2024-03-28 21:39 UTC, nrh-cklimas commented on apps/common/utils.py
> +    if host in settings.HOST_MAP:
Going to leave as-is, but good to know in general.

2024-04-02 17:50 UTC, merged