DEV-4560 | limit import stripe transactions data command to only import where can link to donation page
newsrevenuehub/rev-engine pull request #1452
Opened 2024-03-14 15:58 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2024-03-18 18:21 UTC, njharman approved these changes

2024-03-18 18:21 UTC, njharman commented on apps/contributions/stripe_import.py
> +        if not (rp_id := self.stripe_entity.metadata.get("revenue_program_id", None)):
Is this not worthy of logger.warning?

2024-03-19 19:59 UTC, x110dc requested changes

2024-03-19 19:59 UTC, x110dc commented on apps/contributions/stripe_import.py
> +]
This hardcoded list feels a little icky. Why not just consider anything that's not `DOMAIN_APEX` as something to discard?

2024-03-19 19:59 UTC, x110dc commented on apps/contributions/stripe_import.py
> +        if not (rp_id := self.stripe_entity.metadata.get("revenue_program_id", None)):
1.2 is obsolete and was never used. Not sure if that helps inform something here. (But in the future we may use something similar to 1.2 with DigestBuilder).

2024-03-20 15:01 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +]
Great suggestion. ffc01b1aa4a2

2024-03-20 15:09 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        if not (rp_id := self.stripe_entity.metadata.get("revenue_program_id", None)):
Based on this, I removed v1.2 schema entirely from revengine in d7c1019cb4.  In 1e10c5e5c3ce, I changed updated this method to log a warning in case of no rp id (metadata schema as currently implemented guarantees key is present, but allows empty string through).

2024-03-21 20:42 UTC, x110dc approved these changes

2024-03-22 16:10 UTC, merged