DEV-4403 | make sync_transaction_time resilient vs. normal failure scenarios
newsrevenuehub/rev-engine pull request #1454
Opened 2024-03-15 16:39 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2024-03-15 17:26 UTC, benjaminEwhite commented on apps/contributions/tests/test_views.py
As noted in PR description, the only reason these changes are here is because there was a test that failed because ContributionFactory chooses statuses at random, and we have test code that expects org/contributor viewable statuses on created contributions.

2024-03-18 05:11 UTC, njharman requested changes

2024-03-18 05:11 UTC, njharman commented on apps/contributions/management/commands/sync_payment_transaction_time.py
> +                        f"Error while retrieving balance transaction {payment.stripe_balance_transaction_id}: {e}"
I'm not sure how all these ids relate. Would it be useful for debugger/investigator to have payment.id and payment.contribution.stripe_acount_id output as well?

2024-03-18 05:11 UTC, njharman commented on apps/contributions/management/commands/sync_payment_transaction_time.py
> +            self.style.SUCCESS(
Doing this stdout.write(self.style... all the time would annoy me enough,  to create a MoreBaseCommand class that had print_success(), print_info() print_error() methods.

2024-03-18 13:36 UTC, benjaminEwhite commented on apps/contributions/management/commands/sync_payment_transaction_time.py
> +                account = stripe.Account.retrieve(account_id)
Yeah, good point. Had that thought too after implementing, and was lazy, but it runs much faster with this change.  f005c726

2024-03-18 13:37 UTC, benjaminEwhite commented on apps/contributions/management/commands/sync_payment_transaction_time.py
>      # TODO: [DEV-4403] Make sync_payment_transaction_time command resilient vs. Stripe API errors (esp. no longer-connected accounts)
8a7aa1dd

2024-03-18 13:37 UTC, benjaminEwhite commented on apps/contributions/management/commands/sync_payment_transaction_time.py
> +        self.stdout.write(self.style.HTTP_INFO(f"Found {eligible_payments.count()} eligible payments to sync"))
897199d0

2024-03-18 13:43 UTC, benjaminEwhite commented on apps/contributions/management/commands/sync_payment_transaction_time.py
> +                        f"Error while retrieving balance transaction {payment.stripe_balance_transaction_id}: {e}"
aa883e7e

2024-03-18 13:44 UTC, benjaminEwhite commented on apps/contributions/management/commands/sync_payment_transaction_time.py
> +            self.style.SUCCESS(
I think i'm not quite annoyed enough. If we really want to do this, should do it across all commands with a custom BaseCommand base class that does it for success, info, and error. Going to call this out of scope for now.

2024-03-19 14:00 UTC, benjaminEwhite commented on apps/contributions/management/commands/sync_payment_transaction_time.py
> +        accounts = self.get_stripe_accounts_and_their_connection_status(account_ids)
That was haste makes waste. Was trying to resubmit ahead of heading out for an appointment 🤷 . Only called once now.

2024-03-19 14:01 UTC, benjaminEwhite commented on apps/contributions/management/commands/sync_payment_transaction_time.py
> +        ineligible_because_of_account = Payment.objects.filter(
Good points. I did some light refactoring over several commits, and this should be addressed now.

2024-03-19 14:02 UTC, benjaminEwhite commented on apps/contributions/management/commands/sync_payment_transaction_time.py
> +                accounts[account_id] = False
Cleaned up this function (it used to look at account.charges_enabled but turns out that's not relevant), and updated the logs that explain about disconnected accounts in line with your point here. That was across several commits so not linking to a single one here.

2024-03-19 16:36 UTC, njharman requested changes

2024-03-19 16:36 UTC, njharman commented on apps/contributions/management/commands/sync_payment_transaction_time.py
> +        ineligible_because_of_account = payments_missing_transaction_time.exclude(
above you` .exclude(id__in=ineligible_because_no_donation_page) `here `.exclude(contribution__donation_page__isnull=True)` and and shouldn't fixable_payments have exclude?

Instead of repeating exclude, make a new query right after ineligible

`eligible_payments = payments_missing_transaction_time.exclude(id__in=ineligible_because_no_donation_page)`

Or

`eligible_payments = payments_missing_transaction_time.filter( contribution__donation_page__isnull=False)`



One of the advantages of Django lazy eval queries is you can build, compose them. which you do sometimes.

2024-03-20 15:29 UTC, benjaminEwhite commented on apps/contributions/management/commands/sync_payment_transaction_time.py
> +        ineligible_because_of_account = payments_missing_transaction_time.filter(
@njharman ended up removing the restriction re: donation page here. It's possible for a payment to be unfixable both because its account can't be retrieved and because it has no page. At one point I was logging a.) ones with no account; b.) ones with no page; c.) ones with neither page nor account. But better solution is just to allow overlap between a and b and to omit c.

2024-03-20 15:30 UTC, benjaminEwhite commented on apps/contributions/management/commands/sync_payment_transaction_time.py
> +        ineligible_because_of_account = payments_missing_transaction_time.exclude(
8b7ed5a076

2024-03-21 17:54 UTC, njharman approved these changes

2024-03-21 20:49 UTC, x110dc approved these changes

2024-03-21 20:49 UTC, x110dc approved these changes

2024-03-25 13:28 UTC, merged