DEV-4497: Upgrade prompt for all plans
newsrevenuehub/rev-engine pull request #1463
Opened 2024-03-25 14:23 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2024-03-26 20:03 UTC, nrh-cklimas requested changes

2024-03-26 20:03 UTC, nrh-cklimas commented on spa/src/components/dashboard/sidebar/DashboardSidebarFooter.tsx
> +    return setCoreUpgradePromptClosed(true);
Instead of defaulting here, I'd prefer to either throw an error if `plan.name` doesn't match any of these, or do nothing and log a Sentry error. I'd lean toward throwing an error because we should never have shown the prompt in the first place.

2024-03-27 11:58 UTC, GuiMend commented on spa/src/components/dashboard/sidebar/SidebarUpgradePrompt/SidebarUpgradePrompt.test.tsx
I couldn't do this by mocking, but I managed it with a test ID.
When I mock both icons, the latest mock overrides the previous one.

2024-03-27 11:59 UTC, GuiMend commented on spa/src/components/dashboard/sidebar/SidebarUpgradePrompt/SidebarUpgradePrompt.styled.ts
> +      case 'FREE':
Updated the other component to be strings as well

2024-03-27 13:45 UTC, nrh-cklimas commented on spa/src/components/dashboard/sidebar/SidebarUpgradePrompt/SidebarUpgradePrompt.tsx
> +    icon: React.FC<React.SVGProps<SVGSVGElement>>;
```suggestion
    icon: React.ComponentType;
```

I think better to type it less restrictively in case we end up using a different approach on icons later.

2024-03-27 14:21 UTC, nrh-cklimas approved these changes

2024-04-10 14:14 UTC, merged