DEV-4604: Don't update contribution metadata during Stripe import
newsrevenuehub/rev-engine pull request #1465
Opened 2024-03-28 15:44 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

- Adds a `dont_update` arg to `upsert_with_diff_check`, which is a list of fields to only set on a new object, not update on an existing one.
- Changes `SubscriptionForRecurringContribution.upsert` and `PaymentIntentForOneTimeContribution.upsert` to skip updating `contribution_metadata`.

#### Why are we doing this? How does it help us?

We are seeing with migrated data useless updates of metadata that result in almost the same metadata, but not exactly. We want to skip these updates entirely.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

See Jira for more details.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No.

#### Have automated unit tests been added? If not, why?

Yes.

#### How should this change be communicated to end users?

n/a

#### Are there any smells or added technical debt to note?

Wasn't sure how to test that 

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2024-03-28 18:07 UTC, njharman requested changes

2024-03-28 18:18 UTC, nrh-cklimas commented on apps/contributions/stripe_import.py
> +            dont_update=["contribution_metadata"],
I think no in this case because it's upserting a payment, and we don't have metadata issues with payments (that we're aware of). Might have to revise this later.

2024-03-28 18:43 UTC, nrh-cklimas commented on apps/contributions/tests/test_stripe_import.py
> +            assert contribution.contribution_metadata != payment_intent.metadata
I spent a good amount of time trying to figure out how to pull out the original contribution from a fixture--I think we'd have to revise it in some way. See line 131 for where it gets created. The puzzle is that it gets created as a side effect from another fixture. Do you have advice on how to make that work?

2024-03-28 18:54 UTC, nrh-cklimas commented on apps/common/tests/test_utils.py
> +            {"instance": "instance_only_needs_amount_update", "dont_update": ["amount"], "action": "left unchanged"},
I think I added the test you're suggesting in e4f2d14721571fc35432bb47a764b0c5877b9619. Let me know if I didn't understand you fully.

2024-03-28 19:55 UTC, njharman commented on apps/contributions/tests/test_stripe_import.py
> +            assert contribution.contribution_metadata != payment_intent.metadata
I wouldn't block ticket on this.

Isn't contribution (one created by test fixture) in database? can query it from there with subscription.id or whatever it's pk is.

2024-03-28 19:57 UTC, njharman approved these changes

2024-03-28 19:57 UTC, njharman commented on apps/contributions/stripe_import.py
> +            dont_update=["contribution_metadata"],
I thought it might be like that. But too fuzzy on business / domain / data details, thought it was worth double check.

2024-04-01 03:05 UTC, x110dc approved these changes

2024-04-01 13:33 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +            # metadata and conversions of null <-> None.
FYI: This comment isn't quite right. The issue is not null/None conversion, but instead that Stripe drops key/value pairs from metadata we give it if we send None/null

2024-04-01 13:47 UTC, nrh-cklimas commented on apps/contributions/stripe_import.py
> +            # metadata and conversions of null <-> None.
Updated in 228f160d308fda5babf84f16c033045e59450729

2024-04-01 17:24 UTC, merged