DEV-3870: Add contact phone to RP model
newsrevenuehub/rev-engine pull request #1476
Opened 2024-04-04 19:47 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
Adds contact_phone to Revenue Program
#### Why are we doing this? How does it help us?
Add phone number to RP so that we can display it for contributors
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
no
#### Have automated unit tests been added? If not, why?
yes
#### How should this change be communicated to end users?
n/a
#### Are there any smells or added technical debt to note?
@benjaminEwhite , I added a file `.talismanrc` to ignore the issue with `phonenumbers` library when trying to commit. Please leet me know if there is a better way to handle this issue

#### Has this been documented? If so, where?
no
#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3870
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
https://news-revenue-hub.atlassian.net/browse/DEV-3871
https://news-revenue-hub.atlassian.net/browse/DEV-3872

2024-04-08 14:14 UTC, benjaminEwhite requested changes
Left some suggestions and requests for changes.

Also, I would like to see the `TestRevenueProgramViewSet.test_patch_when_have_access` test case updated to include patching phone number (via an parametrized fixture in `patch_test_case`.

2024-04-08 14:14 UTC, benjaminEwhite commented on apps/organizations/admin.py
> +            raise ValidationError(f"Phone not parsable: {contact_phone}")
Those lines are not tested, so eve more reason to not duplicate the code here.

2024-04-08 14:14 UTC, benjaminEwhite commented on apps/organizations/validators.py
> +            raise ValidationError(f"Invalid phone number: {value}")
These lines don't get touched in tests, so should add test for this scenario.

2024-04-08 14:14 UTC, benjaminEwhite commented on .talismanrc
When I run pre-commit locally after having removed this file, I don't get talisman errors.  I got version of 8.13.34 of that library, whereas this PR is committing 8.13.33, so I'm guessing that if you update phonenumbers, that may solve the problem and then we won't need to add this file.

2024-04-08 16:57 UTC, GuiMend commented on apps/organizations/tests/test_validators.py
> +        assert False, f"{valid_number} raised an exception {er}"
It's not raising any errors. This is to catch, if `ValidationError` occurs, fail test by returning `assert False` with message "{valid_number} raised an exception {er}"

2024-04-08 17:37 UTC, GuiMend commented on .talismanrc
I tried bumping up the version to 8.13.34 but still got the talisman failure. Can you try committing the deletion of this file to this PR?

2024-04-09 14:37 UTC, benjaminEwhite requested changes
A few more small requests.

2024-04-09 14:37 UTC, benjaminEwhite commented on .talismanrc
> +fileignoreconfig:
Still need to delete this file.

2024-04-09 14:37 UTC, benjaminEwhite commented on apps/organizations/serializers.py
> +            "contact_email",
I believe we need to make a small change below.

As i understand it, if you call `.save` manually, you won't get the model-field level validation checks by default.  So that means we need to call `instance.full_clean()` before `instance.save(...` on line 243.

Would also be good to have a test of update that proves that you get a validation error when updating to an invalid phone number.

2024-04-09 14:37 UTC, benjaminEwhite commented on apps/organizations/tests/test_models.py
> +            revenue_program.clean_fields()
I think we should do `.full_clean` instead of `.clean_fields` because we're more likely to manually call full_clean in our code base. It calls `.clean_fields` internally, I believe.

Ditto below at line 598.

2024-04-09 14:39 UTC, benjaminEwhite commented on apps/organizations/tests/test_validators.py
> +        assert False, f"{valid_phone_number} raised an exception {er}"
No need to explicitly add this in the test. If a valid phone number were to trigger a validation error, the test would fail anyways. Can remove try/except here.

2024-04-09 14:43 UTC, benjaminEwhite commented on .talismanrc
c4f40cfe32e

2024-04-09 15:26 UTC, GuiMend commented on apps/organizations/serializers.py
> +            "contact_email",
From my testing it does check for the validation. When I run the patch in Postman I get the validation errors:
<img width="773" alt="image" src="https://github.com/newsrevenuehub/rev-engine/assets/9381325/91987bca-5ca3-4b38-84bb-47cb1ec644ac">

And I also added tests for this to make sure the validation error is being returned:
https://github.com/newsrevenuehub/rev-engine/pull/1476/commits/f7b0d6278ada80b994014c22a3e63db0a6866388#diff-2e94684a518366d0afa11fdb95b8daee995519812b209f76498076df07727e46R778-R799

2024-04-09 15:29 UTC, GuiMend commented on apps/organizations/tests/test_models.py
> +            revenue_program.clean_fields()
I used `clean_fields` because it's the pattern I got from other parts of the code. Example:

```python
# Line 561
def test_slug_validated_against_denylist(self, revenue_program):
        denied_word = DenyListWordFactory()
        revenue_program.slug = denied_word.word
        with pytest.raises(ValidationError) as validation_error:
            revenue_program.clean_fields()
```

Should I update all places to use `full_clean`,  leave them all as `clean_fields` or just update the new tests to `full_clean`?

2024-04-09 15:39 UTC, benjaminEwhite commented on apps/organizations/tests/test_models.py
> +            revenue_program.clean_fields()
Fine to leave as is. Key thing is that the code gets run in a test.

2024-04-09 15:39 UTC, benjaminEwhite approved these changes
Approved (narrowly for backend changes).

2024-04-10 13:42 UTC, nrh-cklimas approved these changes

2024-04-16 17:59 UTC, merged