Dev 3872 implement button above contribution list in portal
newsrevenuehub/rev-engine pull request #1479
Opened 2024-04-08 19:00 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
- Adds contact information popover in Portal
#### Why are we doing this? How does it help us?
- Helping donors contact the Org if necessary
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
yes
#### Have automated unit tests been added? If not, why?
yes
#### How should this change be communicated to end users?
Contact information now available for donors in the portal
#### Are there any smells or added technical debt to note?
no
#### Has this been documented? If so, where?
no
#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3872
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
https://news-revenue-hub.atlassian.net/browse/DEV-3871

2024-04-10 18:57 UTC, nrh-cklimas requested changes

2024-04-10 18:57 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContactInfoPopover/ContactInfoPopover.styled.ts
> +    justify-content: center;
It doesn't appear that these three lines are needed--if I remove them, the icon is still centered.

2024-04-10 18:57 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContactInfoPopover/ContactInfoPopover.styled.ts
> +export const TitleTypography = styled(MuiTypography)`
I want to get Typography as a base component eventually, but I think until then, let's make this and `ContactTypography` `styled.p` instead.

2024-04-10 18:57 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContactInfoPopover/ContactInfoPopover.test.tsx
> +  it('shows contact info', () => {
We should test that if phone or email are empty strings, that the `'Phone:'` or `'Email:'` text isn't present. e.g. I'm envisioning a regression where the labels show but have no link.

2024-04-10 18:57 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContactInfoPopover/ContactInfoPopover.tsx
> +export type { ContactInfoPopoverProps };
Don't think you need this line--change line 17 to be `export interface ContactInfoPopoverProps`.

2024-04-10 18:57 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContactInfoPopover/ContactInfoPopover.tsx
> +}
I think it'd be better (looser coupling between components) if the component takes the RP as prop--its job is to display contact info for an RP and doesn't need to know about a contribution page.

2024-04-10 18:57 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContactInfoPopover/ContactInfoPopover.tsx
> +      <ContactInfoButton color="primaryDark" onClick={showContactInfoPopover} aria-label="Open contact info">
Appreciate adding an ARIA label, but it needs to vary based on the state of the popup.

2024-04-10 18:57 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContactInfoPopover/ContactInfoPopover.tsx
Could this component be added to Storybook showing the different display possibilities (phone only, email only, both phone and email)?

2024-04-10 18:57 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContactInfoPopover/ContactInfoPopover.styled.ts
> +`;
I talked with Rachel about this--we are soon going to change the hyperlink blue to engine blue, but I want to do this as an app-wide change. In the meantime, please use the base Link component without any custom color.

2024-04-11 12:56 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContactInfoPopover/ContactInfoPopover.tsx
Added it to storybook, but to see the popover we need to click the question mark button

2024-04-11 15:02 UTC, nrh-cklimas approved these changes

2024-04-16 18:15 UTC, merged