DEV-3873: Add interval filtering to portal contributions
newsrevenuehub/rev-engine pull request #1485
Opened 2024-04-15 15:15 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
- Add filter based on interval type for contributions
#### Why are we doing this? How does it help us?
- Enable user to filter contributions by "All", "One-time", "Recurring"
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
no
#### Have automated unit tests been added? If not, why?
yes
#### How should this change be communicated to end users?
n/a
#### Are there any smells or added technical debt to note?
no
#### Has this been documented? If so, where?
no
#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3873
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
https://news-revenue-hub.atlassian.net/browse/DEV-3874

2024-04-16 11:37 UTC, benjaminEwhite commented on apps/contributions/filters.py
> +
Minor suggestion, but this is a good place for match/case:

```suggestion
        match request.query_params.get("interval"):
            case ContributionInterval.ONE_TIME.value:
                return queyrset.filter(interval=ContributionInterval.ONE_TIME)
            case "recurring":
                return queryset.exclude(ContributionInterval.ONE_TIME)
            case _:
                return queryset
```

2024-04-16 11:49 UTC, benjaminEwhite requested changes

2024-04-16 11:49 UTC, benjaminEwhite commented on apps/contributions/filters.py
> +
Minor suggestion, but this is a good place for match/case:

```suggestion
        match request.query_params.get("interval"):
            case ContributionInterval.ONE_TIME.value:
                return queyrset.filter(interval=ContributionInterval.ONE_TIME)
            case "recurring":
                return queryset.exclude(ContributionInterval.ONE_TIME)
            case _:
                return queryset
```

2024-04-16 11:49 UTC, benjaminEwhite commented on apps/contributions/filters.py
> +
Consider putting "recurring" into a constant at top of file (all caps), and then can import that var in tests.

2024-04-16 11:49 UTC, benjaminEwhite commented on apps/contributions/tests/test_filters.py
> +        else:
Also good to use match/case here.

2024-04-17 18:37 UTC, GuiMend commented on apps/contributions/filters.py
> +
I tried adding the variable at the top of the file but when trying to use it inside of the match/case it didn't work.
![image](https://github.com/newsrevenuehub/rev-engine/assets/9381325/75908779-497f-43f2-8038-5eeb19b6d668)

I was able to make it work by adding it inside `PortalContributionFilter`. Is this a good workaround?
![image](https://github.com/newsrevenuehub/rev-engine/assets/9381325/2e9c8318-3f06-49ee-9b70-d1c41fae5b2d)
![image](https://github.com/newsrevenuehub/rev-engine/assets/9381325/a2dc9358-c5b5-4ed5-b145-9799b0f17aee)

2024-04-22 19:52 UTC, benjaminEwhite approved these changes
LGTM

2024-05-01 16:31 UTC, merged