reimplimented, payment upsertion not quite working yet
newsrevenuehub/rev-engine pull request #1491
Opened 2024-04-18 23:06 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2024-04-22 22:42 UTC, benjaminEwhite commented on apps/contributions/stripe_contributions_provider.py
> -        return SubscriptionForRecurringContribution.get_interval_from_subscription(subscription)
SubscriptionForRecurringContribution went away and there was no need for this logic in its module. I just pasted the logic over into this method.

2024-04-24 17:47 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +    def get_provider_payment_id_for_subscription(self, subscription: dict) -> str | None:
This provides net new data. As mentioned in PR description, we should have been capturing this in earlier versions of the command, but I missed it.  There is a follow up ticket ([DEV-4705](https://news-revenue-hub.atlassian.net/browse/DEV-4705)) to add for any affected recurring contributions created by earlier versions of the stripe import command.

2024-05-02 20:51 UTC, x110dc requested changes
I added a few minor comments. At this point my main concern is the CACHE_TTL. If this is working as I think it is then if the cache expires for entities before the process is complete then we'll only be processing part of the entities for that org and it may happen silently. I guess we could also have some indeterminant behavior if some entities  get evicted but related ones don't. Say some charges get evicted before their related PIs or vice versa. So, my inclination would be to (1) make the default TTL longer, (2) issue a warning at the end of the command if the runtime (it looks like you're tracking it) exceeds or nears the TTL. May also want to clear the cache at the beginning of the command so we don't risk running out of space in cache. Also, may be useful to have a simple command to clear the entire cache if something goes wrong and we want to start from a clean slate or we run out of cache.

2024-05-02 23:45 UTC, njharman requested changes

2024-05-02 23:45 UTC, njharman commented on apps/contributions/stripe_import.py
> +        if invoice_id:
`if invoice_id := ...`

2024-05-02 23:45 UTC, njharman commented on apps/contributions/stripe_import.py
> +        return provider_payment_id
instead of assignment, could `return invoice.get()` and cut` provider_payment_id = None `and `return provider_payment_id`

2024-05-02 23:45 UTC, njharman commented on apps/contributions/stripe_import.py
> +        )
```
if slug :=  parse_slug_from_url(metadata["referer"]):
    return  revenue_program.donationpage_set.filter(slug=slug).first()
return  revenue_program.default_donation_page
```

Isn't that nicer, more comprehensible? If nothing else it's shorter.

Are if/else single liners much more common in JS/webdev? [Which I'm much less exposed to]. Wondering why it seems to be your "default" or "prefereded" construct.

2024-05-02 23:45 UTC, njharman commented on apps/contributions/stripe_import.py
> +                    "Unable to upsert subscription %s because %s %s", subscription["id"], type(exc).__name__, exc
Maybe is useful (and I see it commonly (at least in switchboard)) to indicate in log that processing is continuing with some like  `; skip` or `; continuing` ?

2024-05-02 23:45 UTC, njharman commented on apps/contributions/stripe_import.py
> +        for key in self.redis.scan_iter(match=f"{CACHE_KEY_PREFIX}_*{self.stripe_account_id}", count=1000):
How did we arrive at the value of 1000?  
How many of these things are we expecting?

Maybe some comment for future devs. Looking at performance/impact on cache system [we are using redis cache for other production stuff right, it's not dedicated to this?]

2024-05-02 23:45 UTC, njharman commented on apps/contributions/stripe_import.py
> +            self.redis.delete(key)
Was looking for something like mdelete().  It takes delete(*names).  I'm not sure how python deals with say 100 long argument list.

I'm also probably guilty of pre-mature optimization... above something to keep in mind if performance of this turns out to matter. lots of network round trips to delete.

Should maybe add elapsed time in log to this like you did in import_contributions_and_payments()

2024-05-02 23:45 UTC, njharman commented on apps/contributions/stripe_import.py
> +            (1, (" byte", " bytes")),
I'll trust you got this right.  [I quit wanting to be C/ASM dev around age 19 cause bit shifting, powers,  thinking about bytes make my brain hurt]

2024-05-02 23:45 UTC, njharman commented on apps/contributions/stripe_import.py
> +                total_memory += memory_usage
no scan_iter(..., count=1000)?

Do we care about accuracy? Are these nested, see samples=0 https://redis-py.readthedocs.io/en/stable/commands.html#redis.commands.core.CoreCommands.memory_usage

2024-05-02 23:45 UTC, njharman commented on apps/contributions/stripe_import.py
> +    def list_and_cache_payment_intents(self) -> None:
Each of these list methods has a test coverage branch "miss". That I do not understand.  It's a function call, I don't see branch logic?  Do you understand?  I suggest # pragma: no branch with mention of weirdness. Which would restore 100%ness of this file.


```def list_and_cache_payment_intents(self) -> None: 
        """List and cache payment intents for a given stripe account""" 
        logger.info("Listing and caching payment intents for account %s", self.stripe_account_id) 
        self.cache_stripe_resources(     # **328 ↛ exitline 328 didn't jump to the function exit**
            resources=self.list_stripe_entity((name := "PaymentIntent"), **self.list_kwargs), 
            entity_name=name, 
            exclude_fn=self.should_exclude_from_cache_because_of_metadata, 
            prune_fn=lambda x: {k: v for k, v in x.items() if k in CACHED_PAYMENT_INTENT_FIELDS}, 
        ) 
```

2024-05-03 12:29 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +    _STRIPE_SEARCH_FILTER_METADATA_QUERY: str = '-metadata["referer"]:null AND -metadata["schema_version"]:null'
1339dac58b69

2024-05-03 12:31 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        """Map Stripe splan interval to Revengine contribution interval"""
7070ae94083

2024-05-03 12:43 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +    def list_and_cache_payment_intents(self) -> None:
Yeah, I didn't get that "miss" either. 

 a29368fe65c04

2024-05-03 19:18 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +    pipeline: Pipeline
So no action required here?

2024-05-03 19:23 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        pipeline = RedisCachePipeline(
I went with your suggestion to take advantage of context manager, however, I didn't see a good way to provide the entity name when overriding `__enter__`.  As best I can tell, we would have to do something wonky like manually set `._entity_name` on the initialized RedisCachePipeline in calling context.  

Might be missing something here, so please look at reimplementation via a629d52975 and let me know if you see a way to improve.

2024-05-03 19:23 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        # need to do this at end in case we have a small number of resources waiting in buffer that didn't trigger a flush
a629d52975

2024-05-03 19:23 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        """ "Put a stripe resource in buffer and if buffer is full, flush it"""
Went away in a629d52975

2024-05-03 19:23 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +    def put_in_buffer(self, key: str, value: dict) -> None:
a629d52

2024-05-03 19:23 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +    buffered: int = 0
a629d529751

2024-05-03 19:24 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +class RedisCachePipeline:
a629d529751

2024-05-03 20:50 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        if interval == "year" and interval_count == 1:
Addressed in fe62f44c7ec5

Note that I will need to update test instructions to do smoke tests on recurring contributions for status quo portal with this change.  Also will need to update tests, but going to hold off on test updates until get green light on object code changes.

2024-05-03 20:50 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        raise InvalidIntervalError(f"Invalid interval {interval}")
Addressed in fe62f44c7ec5

Note that I will need to update test instructions to do smoke tests on recurring contributions for status quo portal with this change.  Also will need to update tests, but going to hold off on test updates until get green light on object code changes.

2024-05-03 21:19 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        match subscription_status:
223830fb4dd

2024-05-03 21:34 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +    def list_and_cache_payment_intents(self) -> None:
Also, I dried up list_and_cache_* methods in 9f2fefdd28815 so this issue may be a moot point (haven't refactored/rerun tests yet to determine).

2024-05-03 21:47 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +    def cache_charges_by_payment_intent_id(self) -> None:
Didn't move to the custom pipeline, but did dry up.

7263c6799d42c

2024-05-03 21:48 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        return json.loads(cached) if cached else None
ac82a5f210

2024-05-03 21:49 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        return json.loads(cached) if cached else None
ac82a5f210

2024-05-03 21:53 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +                results.append(charge)
527e071850

2024-05-03 21:54 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        for charge in charges:
f0e9159273c

2024-05-03 21:56 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +            return pm.to_dict() if pm else None
f190c872b62

2024-05-03 22:13 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +                pass
b761d9234e9

2024-05-03 22:35 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        if len([x for x in charges if x["status"] == "succeeded"]) > 1:
8c87eb8eb208

2024-05-03 22:36 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        if len([x for x in charges if x["status"] == "succeeded"]) > 1:
8c87eb8eb208

2024-05-03 22:39 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        if invoice_id:
bd978f396c

2024-05-03 22:41 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        return provider_payment_id
1907f245

2024-05-03 22:43 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        )
Was preferred style of a former boss early in my coding career, so that's probably why/

df23bbdaf2

2024-05-03 22:44 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +                    "Unable to upsert subscription %s because %s %s", subscription["id"], type(exc).__name__, exc
996ba6356f6

2024-05-03 22:46 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +            (1, (" byte", " bytes")),
I'm relying on crowd-sourcing via stack overflow here

🤷 

That said, this is pretty low stakes.  If we don't get this exactly right, airplanes won't fall out of the sky, we'll just have this command crash (perhaps?) or an incorrect report on mem footprint.

2024-05-03 22:50 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        for key in self.redis.scan_iter(match=f"{CACHE_KEY_PREFIX}_Invoice_*"):
That won't work here because this is fuzzy matching, whereas `make_key` makes a full key.

2024-05-03 22:50 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        for key in self.redis.scan_iter(match=f"{CACHE_KEY_PREFIX}_Refund_*"):
This went away because DRYed up those methods, but see comment above about how won't work because fuzzy matching.

2024-05-03 23:08 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        for key in self.redis.scan_iter(match=f"{CACHE_KEY_PREFIX}_*{self.stripe_account_id}", count=1000):
d3f35cfb

2024-05-03 23:08 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +            self.redis.delete(key)
Used redis pipeline ot batch this

d3f35cfb

2024-05-03 23:15 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +                total_memory += memory_usage
I'm not able to glean enough from the docs to ascertain what value would make sense to use. That said, most of the values we're storing are only one layer deep. There are some exceptiosn like subscription.metadata (2 levels) and payment_intent.metadata (2 levels) and customer.invoice_settings and subscription.items (~3 levels deep), but so far seems like we're good in review apps with 25 MB for redis (no OOM errors for redis). If that changes, we'll get Sentry errors and can adjust.

In prod, our redis allowance is orders of magnitude bigger (gigabytes) so i don't think there's a big risk here.

2024-05-04 00:23 UTC, benjaminEwhite commented on revengine/settings/deploy.py
> -### Performance optimizations
Review apps and standing envs already use settings.deploy.

settings.dev is only used in CI (or as fallback in wsgi.py if DJANGO_SETTINGS_MODULE not set). The fact that tests pass in CI seems to indicate that's not a problem.

local.example.py (and therefore presumably local.py for most devs) inherits from dev. Running tests locally, everything works. And from what I can tell other parts of app work locally. FWIW, I did not try the status quo portal (which definitely involves caching) locally to see if it's effected, but a.) that code will soon be gone; b.) I don't think devs test that much locally anyways and c.) the risk is pretty low. 

Ultimately, we need cache set like this locally so can run command locally.

2024-05-04 03:17 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        for key in self.redis.scan_iter(match=f"{CACHE_KEY_PREFIX}_Charge_*"):
bb8d2184de17

2024-05-04 03:17 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        for key in self.redis.scan_iter(match=f"{CACHE_KEY_PREFIX}_Invoice_*"):
bb8d2184de17

2024-05-06 00:35 UTC, njharman commented on apps/contributions/stripe_import.py
> +            (1, (" byte", " bytes")),
Using github code ai thing, I can't remember name of.  Man, I tab complete a lot of "logic" that I assume is right.

2024-05-06 00:39 UTC, njharman commented on apps/contributions/stripe_import.py
> +        )
fair. 

accidental apropos typo? prefereded;  something preferred in the past.

2024-05-07 20:59 UTC, x110dc requested changes
I noted one minor typo, but my main concern is that I don't see if/where this was addressed: https://github.com/newsrevenuehub/rev-engine/pull/1491#pullrequestreview-2036712711

2024-05-07 20:59 UTC, x110dc commented on apps/contributions/stripe_import.py
> +        """Flush the pipeline by cachching its resources in Redis"""
typo: "cachching"

2024-05-07 23:19 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        """Flush the pipeline by cachching its resources in Redis"""
3bd813b1652

2024-05-08 01:45 UTC, benjaminEwhite commented
@x110dc I just pushed up this commit which I believe addresses almost all of the concerns you raised in the comment about TTL and reaching limits. The only part I didn't act on was this suggestion:

> May also want to clear the cache at the beginning of the command so we don't risk running out of space in cache.

We can easily add that at any point if need arises, but it would also mean we couldn't have multiple async versions of the command running at same time.

Let me know your thoughts.

2024-05-08 04:36 UTC, x110dc approved these changes

2024-05-08 04:36 UTC, x110dc commented on revengine/settings/base.py
> +# We set this to two hours. We expec stripe import runs to take less than 2 hours, but this gives
Comment should be updated for new value here. 2 vs. 8

2024-05-08 04:58 UTC, x110dc commented
> We can easily add that at any point if need arises, but it would also mean we couldn't have multiple async versions of the command running at same time.

Makes sense. We can also run the clear cache command first if needed.

2024-05-08 11:43 UTC, benjaminEwhite commented on revengine/settings/base.py
> +# We set this to two hours. We expec stripe import runs to take less than 2 hours, but this gives
b678669b79a

2024-05-08 15:36 UTC, merged