DEV-3879: Implement "Resend Receipt" button in Portal
newsrevenuehub/rev-engine pull request #1492
Opened 2024-04-23 13:37 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
Stacked PRs:
[main <- DEV-3878](https://github.com/newsrevenuehub/rev-engine/pull/1490) <- DEV-3879

#### What's this PR do?
- Implements "Resend Receipt" button in Portal
#### Why are we doing this? How does it help us?
- Allow for donors to get the receipt email if they lost the original one
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
- yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
- yes
#### Have automated unit tests been added? If not, why?
- yes
#### How should this change be communicated to end users?
- Contributors now are allowed to resend receipts
#### Are there any smells or added technical debt to note?
- no
#### Has this been documented? If so, where?
- no 
#### What are the relevant tickets? Add a link to any relevant ones.
- https://news-revenue-hub.atlassian.net/browse/DEV-3879
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
- no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
- no

2024-04-23 14:16 UTC, nrh-cklimas requested changes

2024-04-23 14:16 UTC, nrh-cklimas commented on spa/src/hooks/usePortalContribution.test.tsx
> +    });
```suggestion
    it('is returned even when a contribution is loading', async () => {
      const { result, waitForNextUpdate } = hook(123, 1);

      expect(typeof result.current.sendEmailReceipt).toBe('function');
      await waitForNextUpdate();
    });
```

This lets the hook initial load finish properly; otherwise you get an intermittent "tried to update an unmounted component" error in test runs.

2024-04-23 14:16 UTC, nrh-cklimas commented on spa/src/hooks/usePortalContribution.test.tsx
> +      );
```suggestion
      expect(axiosMock.history.post[0].url).toBe('/contributors/123/contributions/1/send-receipt/');
```

2024-04-23 19:14 UTC, GuiMend commented on spa/src/hooks/usePortalContribution.test.tsx
> +    });
I'm not sure I follow @nrh-cklimas, we already assert it's calling the correct URL:
```js
it('makes a POST to /api/v1/contributions/{id}/send-receipt/', async () => {
      const { result, waitFor } = hook(123, 1);

      expect(axiosMock.history.post.length).toBe(0);

      result.current.sendEmailReceipt();
      await waitFor(() => expect(axiosMock.history.post.length).toBe(1));
      expect(axiosMock.history.post[0]).toEqual(
        expect.objectContaining({
          url: '/contributors/123/contributions/1/send-receipt/'        <--------------
        })
      );
    });
```

2024-04-24 18:53 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/BillingHistory.tsx
> +      })}
```suggestion
      controls={
        sendNreEmail && <SectionControlButton onClick={onSendEmailReceipt}>Resend receipt</SectionControlButton>
      }
```

A little more concise.

2024-04-25 18:41 UTC, nrh-cklimas approved these changes

2024-05-01 16:14 UTC, merged