DEV-4244: Send "All contributors" MC segment, rename one-time segment
newsrevenuehub/rev-engine pull request #1493
Opened 2024-04-25 15:01 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

- Creates a new Mailchimp segment during integration setup, "All contributors". This has filter criteria defined in the AC of the story, e.g. that a contact has made any purchase.
- Renames the existing segment for one-time contributors from "Contributors" to "One-time contributors".

#### Why are we doing this? How does it help us?

- Clients often want to email contributors regardless of type.
- Rename is to make the purpose of the segments clearer.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

Yes.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No.

#### Have automated unit tests been added? If not, why?

Yes.

#### How should this change be communicated to end users?

Updated docs.

#### Are there any smells or added technical debt to note?

I didn't rename `RevenueProgram.mailchimp_contributor_segment_id` because it felt like a petty reason to make a migration, but I changed the name elsewhere in code to `one_time`.

#### Has this been documented? If so, where?

No.

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-4244

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No.

2024-04-26 11:45 UTC, benjaminEwhite requested changes
Made some requests for drying up and adding tests. Plus a comment that I'm genuinely on the fence about as to whether or not we should move mailchimp segment into its own model.

2024-04-26 11:45 UTC, benjaminEwhite commented on apps/organizations/models.py
> +    mailchimp_all_contributors_segment_id = models.CharField(max_length=100, null=True, blank=True)
I'm on the fence about this, but here's a thought.

Now that we're at 3 segments we're tracking, this makes me think that it's only a matter of time before there's a fourth, so we might want to consider separating out MailchimpSegment into a separate model/table. 

We might further have a RevenueProgramMailchimpSegment model.

MailchimpSegment would have  a (non unique) name and we'd probably want to start storing the segment ID (which gets returned when created, but which we do not currently store)., along with the parent list ID for the segment.  We'd want a uniqueness constraint on  list_id + segment name.

Then we'd have RevenueProgramMailchimpSegment which would be have just two columns, RP id and MC segment ID (or maybe segment name instead? with a uniqueness constraint on RP id + segment name?).

This would lead to cleaner data modeling, but that said, it would require a fair amount of refactor. 

Again, I'm on the fence about this.  Might be worthwhile asking Norm to weigh in on in this question.

2024-04-26 11:45 UTC, benjaminEwhite commented on apps/organizations/models.py
> +    def make_mailchimp_all_contributors_segment(self) -> MailchimpSegment:
This method also could be dried up so there's common abstracted method for each of three segments, and the existing methods for creating call this common method with right args.

2024-04-26 11:45 UTC, benjaminEwhite commented on apps/organizations/models.py
> +
This logic is repeated 3x over now for each segment. Think we should create a method that has the abstracted logic required for retrieving this for each of the three segments. Then we can keep the cached properties, but have them call this new method.

2024-04-26 11:45 UTC, benjaminEwhite commented on apps/organizations/models.py
> +    def make_mailchimp_all_contributors_segment(self) -> MailchimpSegment:
Also, looks like this method is not tested. Should add a unit test.

2024-04-26 11:45 UTC, benjaminEwhite commented on apps/organizations/models.py
>      def ensure_mailchimp_entities(self) -> None:
I know you didn't implement original method here (i did!) but since it's being touched, I can't help but note that it's not tested.  Think we should add a unit test for this. Should be an easy one to write because we can mock each of the constituent methods called in body of this method. Think its enough just to mock and call and assert the methods are called.

2024-04-30 12:32 UTC, benjaminEwhite requested changes
Made some requests for additional changes, and it looks like most recent set of changes broke a good number of existing tests.

2024-04-30 12:32 UTC, benjaminEwhite commented on apps/organizations/models.py
> +    def __init__(self, rp: "RevenueProgram"):
For "forward referencing" on this type hint, I believe should have full path to the class (so `"apps.organizations.models.RevenueProgram"`).

2024-04-30 12:32 UTC, benjaminEwhite commented on apps/organizations/models.py
> +            RevenueProgramMailchimpClient(self).create_store()
Minor, but can we do `rp=self`?

2024-04-30 12:32 UTC, benjaminEwhite commented on apps/organizations/models.py
> +        if not getattr(self, f"mailchimp_{type}_contribution_product"):
Need to define default otherwise will cause error if no value is there.

```suggestion
        if not getattr(self, f"mailchimp_{type}_contribution_product", None):
```

2024-04-30 12:32 UTC, benjaminEwhite commented on apps/organizations/models.py
> +            RevenueProgramMailchimpClient(self).create_mailchimp_product(
try/catch for valueerror/whatever replaces value error?

2024-04-30 12:32 UTC, benjaminEwhite commented on apps/organizations/models.py
> +            segment = RevenueProgramMailchimpClient(self).create_segment(
ditto try/catch for valueerror/whatever replaces value error?

2024-04-30 12:32 UTC, benjaminEwhite commented on apps/organizations/models.py
> +            client = RevenueProgramMailchimpClient(self)
ditto minor (`rp=self`).

2024-04-30 17:02 UTC, nrh-cklimas commented on apps/organizations/models.py
> +    def __init__(self, rp: "RevenueProgram"):
Hmm. When I do that, I get:

`apps/organizations/models.py:517:28: F821 undefined name 'apps'`

Wondering if it's something about how we've set up the app.

2024-05-03 15:23 UTC, benjaminEwhite requested changes
A couple of small requests for changes, but overall looking good.

2024-05-03 15:23 UTC, benjaminEwhite commented on apps/organizations/models.py
> +            print("Creating")
Think this print statement can be removed

2024-05-03 15:23 UTC, benjaminEwhite commented on apps/organizations/models.py
> +            print("already exists")
Ditto removing `print`

2024-05-03 15:23 UTC, benjaminEwhite commented on apps/organizations/models.py
> +    def __init__(self, rp: "RevenueProgram"):
Huh, yeah, i guess it understands where RevenueProgram comes from but not the fully qualified path 🤷

2024-05-07 16:17 UTC, benjaminEwhite reviewed
Left a couple additional comments looking over again.

2024-05-07 16:17 UTC, benjaminEwhite commented on apps/organizations/models.py
> +            client = RevenueProgramMailchimpClient(self)
Looks like that commit didn't update this line.

2024-05-07 16:17 UTC, benjaminEwhite commented on apps/organizations/models.py
> +            RevenueProgramMailchimpClient(self).create_mailchimp_product(
I'm a little hazy on my intentions when originally implementing, but yes, I think that was the idea. That way if task gets retried (that calls this method), it potentially has less to do next time around.

2024-05-07 16:39 UTC, nrh-cklimas commented on apps/organizations/models.py
> +            print("Creating")
Fixed in 622c49de07a3ea7651f87584bba23d131090dc39

2024-05-07 16:39 UTC, nrh-cklimas commented on apps/organizations/models.py
> +            print("already exists")
Fixed in 622c49de07a3ea7651f87584bba23d131090dc39

2024-05-07 16:41 UTC, nrh-cklimas commented on apps/organizations/models.py
> +            client = RevenueProgramMailchimpClient(self)
Argh, apologies. 21a9feaa436273c7902910fb62beb2e7ff868a40

2024-05-07 16:46 UTC, nrh-cklimas commented on apps/organizations/models.py
> +            return self._handle_write_error(product_id, error)
Updated in d8a2580d2e11d5a7aec6d911b0b73274b476ef19

2024-05-07 16:47 UTC, nrh-cklimas commented on apps/organizations/models.py
> +            return self._handle_read_error("store", exc)
Updated in 30c950e66f1e233d8ad6ddf55e379969807957b3

2024-05-07 16:52 UTC, nrh-cklimas commented on apps/organizations/models.py
> +            raise MailchimpIntegrationError("Mailchimp must be connected and email list ID must be set")
Added in 4c0ac9d02981db1a57b62d215ca78d1529969e0c

2024-05-07 18:24 UTC, nrh-cklimas commented on apps/organizations/models.py
> +    def _handle_read_error(
Added in 3d2d23108631216cd50229e2b331adefd91c8d86

2024-05-07 18:25 UTC, nrh-cklimas commented on apps/organizations/models.py
> +    def _handle_write_error(self, entity: str, exc: ApiClientError) -> None:
Added in 3d2d23108631216cd50229e2b331adefd91c8d86

2024-05-07 18:36 UTC, nrh-cklimas commented on apps/organizations/models.py
> +            RevenueProgramMailchimpClient(self).create_mailchimp_product(
Added in 2019725ae09b73942274acaf1092cf4192f4f92d

2024-05-07 18:36 UTC, nrh-cklimas commented on apps/organizations/models.py
> +            segment = RevenueProgramMailchimpClient(self).create_segment(
Added in 2019725ae09b73942274acaf1092cf4192f4f92d

2024-05-07 20:39 UTC, benjaminEwhite commented on apps/organizations/models.py
> +                logger.exception(
This path through doesn't get tested

2024-05-07 20:40 UTC, benjaminEwhite reviewed
Two (small) untested exception paths, but other than that good to go.

2024-05-07 20:40 UTC, benjaminEwhite commented on apps/organizations/models.py
> +            except MailchimpIntegrationError:
This path through doesn't get tested

2024-05-07 20:40 UTC, benjaminEwhite commented on apps/organizations/models.py
> +            except MailchimpIntegrationError:
This path is untested

2024-05-07 23:13 UTC, benjaminEwhite approved these changes
LGTM

2024-05-08 17:13 UTC, njharman requested changes

2024-05-08 17:13 UTC, njharman commented on apps/organizations/models.py
> +        self, segment_type: Literal["all_contributors", "contributor", "recurring_contributor"], options
Seems worth reducing future confusion to change to mirror property values. And not to have some plurals, some not. Already making migration, adding rename to it doesn't seem big deal.

```
All contributors -> all_contributors
One-time contributors -> contributor
Recurring contributors -> recurring_contributor
```

Suggest `contributor `be changed to `one_time_contributors` and adding s to `recurring_contributors`. Or, if not practicable, a code comment/docstring be added along lines of contributor means One-time contributor

2024-05-08 17:13 UTC, njharman commented on apps/organizations/models.py
> +        self, segment_type: Literal["all_contributors", "contributor", "recurring_contributor"], options
With perfect future vision (and I'd have to think through it more but knee jerk reaction is) I'd have created JSON field or hash field to store segment_type -> id, name, whatever. The takeaway

If making db fields whose names vary by value, Consider modifying schema to store variable part of name as a value.    x_type, y_type, z_type -> type {x=..., y=..., z=...}.

2024-05-08 18:29 UTC, nrh-cklimas commented on apps/organizations/models.py
> +            raise MailchimpIntegrationError("Mailchimp integration not connected for this revenue program")
Makes sense. e8f048038a1ecc17857552dc6c9bd953e937d2ca

2024-05-08 18:42 UTC, nrh-cklimas commented on apps/organizations/models.py
> +        return RevenueProgramMailchimpClient(rp=self).get_store()
I like this a lot, updated in ebc07dbeb58f01574b393287316893c0cd494c66. I called it `mailchimp_client` to parallel other MC-related properties.

2024-05-08 18:47 UTC, nrh-cklimas commented on apps/organizations/models.py
> +        return "One-time contributors"
I think we are safe because the name is only used for cosmetic purposes. This model looks up segments by ID, e.g. `mailchimp_all_contributors_segment`. Otherwise the name is unused, e.g. not returned by `MailchimpRevenueProgramForSpaConfiguration` or `MailchimpRevenueProgramForSwitchboard`.

It's true this won't help out RPs that have already been connected to Mailchimp, but that's a big can of worms as some orgs have renamed their MC segments on their own, so we can't reliably find an existing segment to update it--at least not easily.

2024-05-08 18:49 UTC, nrh-cklimas commented on apps/organizations/models.py
> +            logger.info("Creating store for RP %s", self.id)
The hobgoblin of consistency makes me ask, do you think we should also do this for `ensure_mailchimp_contributor_segment`?

2024-05-08 18:56 UTC, nrh-cklimas commented on apps/organizations/models.py
> +            logger.info("%s contribution product already exists for RP with ID %s", product_type, self.id)
👍 Updated in bf9a95a500f52fd2d5ce0eda3809b198b14964c3

2024-05-08 19:28 UTC, nrh-cklimas commented on apps/organizations/models.py
> +        self, segment_type: Literal["all_contributors", "contributor", "recurring_contributor"], options
Right now, switchboard expects the products to follow this naming scheme, or at least expects the API response to do that. [This test](https://github.com/newsrevenuehub/rev-engine/blob/99f04b66f47d1354ec656003f70617b3c535dfb4/apps/organizations/tests/test_serializers.py#L192) shows the fields in question. Not sure the best way to handle this would be. We could rename the field but keep the names in existing format for that serializer? Or change rev-engine and switchboard in tandem?

2024-05-08 19:32 UTC, nrh-cklimas commented on apps/organizations/models.py
>          return "Recurring contributors"
Asked Ben about this since he wrote this originally--thought was to parallel other properties like `mailchimp_recurring_contributor_segment`. But I don't have a strongly held opinion about it, one way or the other, so whichever direction makes sense to you.

2024-05-10 18:06 UTC, njharman approved these changes
Approved with two responses to be read and resolved by Chris

2024-05-10 18:06 UTC, njharman commented on apps/organizations/models.py
> +            logger.info("Creating store for RP %s", self.id)
Without looking, yes!

I'm (and it may only be me) am very "pattern recognition" oriented when looking/understanding code.  The differences stick out. And if not immediately apparent why different (inherently or via comment) I am left wondering why? Bug? Lack of my understanding? It distracts and sidelines whatever task I really wanted to accomplish.

A non-small part of my reviewing process is attempting to minimize that occurrence for future maintainers.  So, generally +1 on consistency for things that are consistent,  +1 on being dramatically/obviously different things that are different, -1 muddy middle.

2024-05-16 20:36 UTC, x110dc submitted a review, later dismissed
LGTM, but it looks like this is a significant refactor of the Mailchimp client. Please mention that in the PR description.

2024-06-04 18:21 UTC, merged