DEV-4562 | Solve for importing pageless contributions in Stripe transactions importer
newsrevenuehub/rev-engine pull request #1496
Opened 2024-05-01 13:04 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2024-05-07 17:13 UTC, njharman requested changes

2024-05-07 17:13 UTC, njharman commented on apps/contributions/models.py
>                  )
line #136   `donation_page__revenue_program__organization=role_assignment.organization`

Does this require dual dp/_rp treatment? If not, maybe short comment to explain the difference with RP_ADMIN query.

2024-05-07 17:51 UTC, benjaminEwhite commented on apps/contributions/models.py
>                  )
Great catch. Thanks!

bf908920b1

2024-05-07 18:04 UTC, benjaminEwhite commented on apps/contributions/models.py
>          # TODO: [DEV-4507] Remove this property and replace with a direct FK to RevenueProgram
No longer relevant given model changes. 2e16c67f46

2024-05-07 18:07 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +            # additional note
That was a note to myself to leave a comment, which I didn't get back to. Fixed in 84af7f4ec

2024-05-08 04:55 UTC, x110dc approved these changes

2024-05-08 15:11 UTC, merged