DEV-4699: Create Contributor Impact endpoint
newsrevenuehub/rev-engine pull request #1497
Opened 2024-05-01 13:45 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
Creates endpoint to return "contributor impact" (total amount donated)

#### Why are we doing this? How does it help us?
Enable impact tracker in new Portal

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
no
#### Have automated unit tests been added? If not, why?
yes
#### How should this change be communicated to end users?
n/a
#### Are there any smells or added technical debt to note?
no
#### Has this been documented? If so, where?
no
#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-4699
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
https://news-revenue-hub.atlassian.net/browse/DEV-4565

2024-05-01 20:31 UTC, GuiMend commented on apps/contributions/views.py
> +        contribution_qs: QuerySet = contributor.contribution_set
Hey @benjaminEwhite , I just saw that the FE [ticket](https://news-revenue-hub.atlassian.net/browse/DEV-4565) has an AC that the BE didn't contain.

```
It doesn’t include payments that were cancelled, failed, or otherwise did not actually send money to the RP.
```

Do I need to filter out the hidden status contributions like we do in other places or does the Payment `net_amount_paid` already handles this?
```python
qs = PortalContributionFilter().filter_queryset(
            request, self.exclude_hidden_statuses(contributor.contribution_set)
        )
```

2024-05-03 14:36 UTC, benjaminEwhite requested changes
Several requests for changes.

2024-05-03 14:36 UTC, benjaminEwhite commented on apps/contributions/views.py
> +    def contributor_impact(self, request, pk=None):
This doesn't seem to filter by revenue program, which according to AC is what we want. Contributors are not unique to an RP, so need to filter by RP.

2024-05-03 14:36 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        contribution_qs: QuerySet = contributor.contribution_set
Yes, I think we need to do something to exclude some statuses. That said, hiding cancelled is problematic. If you have a recurring contribution that, say, has had 6 monthly payments, then you end it, the contribution status in our system will be canceled, and I think we would want the payments that happened under the now canceled subscription to show up in impact.

If a one-time contribution shows up as canceled, I am pretty sure that can only happen if the user clicks "back" on the payment form (in which case we do not want it to count towards impact).  In that case, we shouldn't end up with a payment, because those only get created when a `payment_intent.suceeded` webhook fires (which is caused by completing the payment form in case of non-flagged, or contribution being accepted in Django admin/by task in case of flagged). Note that there are two other events that can lead to payment creation in revengine: `invoice.payment_succeeded` and `charge.refunded`.


Might be worth clarifying this AC in JIRA with Rache/Sophie.

2024-05-03 14:36 UTC, benjaminEwhite commented on apps/contributions/views.py
> +    def contributor_impact(self, request, pk=None):
Also, I think it would be worthwhile to abstract out the logic for generating impact numbers into a method on `Contributor` model. That method would probably take `revenue_programs` as an argument, and would allow you to filter the impact by 0 or more revenue program ids.

The advantage here is that we could then narrowly unit test the logic around totaling up these numbers. The view layer can then become "thin" in that it just calls the class method on Contributor, and returns the results.

2024-05-03 14:36 UTC, benjaminEwhite commented on apps/contributions/tests/test_views.py
> +    def test_contributor_impact(self, portal_contributor_with_multiple_contributions, api_client):
See suggestion below about moving contributor impact calculation into a method on the `Contributor` model. Would like to see that logic narrowly unit tested with a variety of cases.

2024-05-03 18:49 UTC, GuiMend commented on apps/contributions/tests/test_views.py
> +            amount_refunded=(contribution.amount - 100) / 2,
I just added some random value so that I could test if the total impact was the sum of payments minus refunded. I'll remove it since, with your suggested changes, this wouldn't be needed anyways.

2024-05-06 18:44 UTC, benjaminEwhite requested changes
A few small requests (mainly having to do with tests).

2024-05-06 18:44 UTC, benjaminEwhite commented on apps/contributions/tests/test_models.py
> +        assert contributor_user.get_impact() == {"total": 0, "total_paid": 0, "total_refunded": 0}
Although if alter test_get_impact so that the contributor has some contributions that are canceled that have no payments, I think maybe this test can go away entirely.

2024-05-06 18:44 UTC, benjaminEwhite commented on apps/contributions/tests/test_views.py
> +    def test_contributor_impact(self, portal_contributor_with_multiple_contributions, api_client):
Since contributor impact is being narrowly unit tested else where, I don't think this test needs to prove the values returned are correct. Instead can just show that get expected keys in response and expected status code.

2024-05-07 12:55 UTC, benjaminEwhite requested changes
Looks good. Just have one unresolved question about a test.

2024-05-07 13:39 UTC, GuiMend commented on apps/contributions/tests/test_models.py
> +        assert contributor_user.get_impact() == {"total": 0, "total_paid": 0, "total_refunded": 0}
Renamed and added a test with contribution, but no payments

2024-05-07 14:12 UTC, benjaminEwhite approved these changes

2024-05-10 18:45 UTC, merged