DEV-4753 | PATCH endpoint for switchboard to change contribution.revenue_program
newsrevenuehub/rev-engine pull request #1507
Opened 2024-05-09 20:50 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2024-05-10 18:57 UTC, njharman requested changes

2024-05-10 18:57 UTC, njharman commented on apps/api/permissions.py
> +            and settings.SWITCHBOARD_ACCOUNT_EMAIL
+3.14 
You thought of tricky case, "no email" and "unset" SWITCHBOARD_ACCOUNT_EMAIL.

I don't think I would have...

2024-05-10 18:57 UTC, njharman commented on apps/api/permissions.py
> +            and settings.SWITCHBOARD_ACCOUNT_EMAIL
The code is covered. I was still saddened to not see a test for IsSwitchboardAccount in api/tests/test_permissions.py

2024-05-10 18:57 UTC, njharman commented on apps/contributions/serializers.py
> +            update_fields.add("donation_page")
Instead of _rp_being_set bool, consider indenting this if statement and cutting _rp_being_set

```
if (rp := validated_data.pop("_revenue_program", None)) and instance._revenue_program != rp:
    ...
    if instance.donation_page and _rp_being_set:
       ...
```

2024-05-10 18:57 UTC, njharman commented on apps/contributions/serializers.py
> +        with reversion.create_revision():
Shouldn't this be indented (so that it only runs if rp_being_set)?

As it is now, it seems, that when if (rp := ...): is false we will be creating revisions consisting only of `modified` being changed.

2024-05-10 18:57 UTC, njharman commented on apps/contributions/serializers.py
> +        if (rp := validated_data.pop("_revenue_program", None)) and instance._revenue_program != rp:
[have to read the comments below first to grok this one]

Another way to handle this, avoiding indentation is to reverse if statement into a "guard clause". I don't feel strongly about it either way. An alternative if you were opposed to indentation suggested below.

```
if not ((rp := validated_data.pop("_revenue_program", None)) and instance._revenue_program != rp):
    return instance
```

Although, due to too much parens and double negation I'd probably rewrite
```
rp = validated_data.pop("_revenue_program", None)
if not rp or rp == instance_revenue_program:
    return instance
```

2024-05-10 18:57 UTC, njharman commented on apps/contributions/serializers.py
> +        if (rp := validated_data.pop("_revenue_program", None)) and instance._revenue_program != rp:
Tests show it works.  Just surprised the validated field is the underscore one. Guess DRF is getting that from the source="_revenue_program".

Self resolving this rubber duck moment.

2024-05-10 18:57 UTC, njharman commented on apps/contributions/serializers.py
> +        Note that the actual model attribute here is `._revenue_program`.
nm, everything is good. The dual source rp is really a pain in the head/tricky.

[edit I don't think I was understanding correctly]

This is "auto called" validator on revenue_program field which is actually checking _revenu_program because of the `source=` above.

~But now the question is:  what if contribution being changed is one that got rp via donation_page~

[/edit]

If I understand correctly, isn't this a bit misleading?  

Code is using, correctly, the property that resolves to either `._revenue_program` or` .dontation_page.revenue_program`.

2024-05-10 18:57 UTC, njharman commented on apps/contributions/tests/test_views.py
> +    def test_update_when_patching_rp_for_different_org(self, api_client, switchboard_user, contribution, other_orgs_rp):
Maybe contribution fixture already does [if not suggest we add it (so all tests that use fixture cover this)  [fixtures can return > 1 value causing multiple tests similar to parametrize, right?] ].

Do we test both "paths" to rp?  _revenue_program and donation_page.revenue program?

2024-05-13 19:10 UTC, benjaminEwhite commented on apps/api/permissions.py
> +            and settings.SWITCHBOARD_ACCOUNT_EMAIL
Added in 635811401f

2024-05-13 19:17 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +        if (rp := validated_data.pop("_revenue_program", None)) and instance._revenue_program != rp:
07952b080fbf

2024-05-13 19:17 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            update_fields.add("donation_page")
07952b080fbf

2024-05-13 19:18 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +        with reversion.create_revision():
07952b080fbf

2024-05-13 19:24 UTC, benjaminEwhite commented on apps/contributions/tests/test_views.py
> +    def test_update_when_patching_rp_for_different_org(self, api_client, switchboard_user, contribution, other_orgs_rp):
431f9ba27

2024-05-17 01:04 UTC, x110dc approved these changes
lgtm

2024-05-21 20:04 UTC, merged