Dev 4775 ruff revengine
newsrevenuehub/rev-engine pull request #1508
Opened 2024-05-13 01:39 UTC by njharman

#### What's this PR do?
Replaces isort, flake8 pylint other linters with Ruff

Notes: 

- Pytest fixtures that don't pass value are underscored by convention. Ruff "requires" this.
- Slight difference from previous isort behavior
  - Now line length 140, was 100 (there is only one length in ruff).
  - migrations are now isorted
- Ruff complains about long lines black does not format; comments and docstrings. 
  - I fixed existing ones. I
  - In future you will have to manually fix too long lines added in comment or docsting.
- .flake8 had max-complexity set to 18, which is extremely high
   - 0 is default. 
   - I set to 12 which was highest existing complexity.
   - Should we reduce these? 
      - apps/organizations/views.py:281:5: C901 `handle_stripe_account_link` is too complex (12 > 10)
      - apps/users/forms.py:14:9: C901 `clean` is too complex (12 > 10)
   - I don't think after the fact decomplexicating is worth it (outside of total refactor).
   - Should noqa: these and set maxcomplex to 10 [I didn't think of that until now]

Some explanations on code changes:

- Move to main dependency and version pin in pyproject.toml
     - colorama imported by ./tasks.py
     - dateparse just cut from dev, already present in dependency
     - invoke imported by ./tasks.py
    
- Cut unnecessary else, elif, return None
- Refactor fl: to be "Path().open() as f:"
- Refactor e: ex: to be "catch X as exc:"
- Refactor use "raise from" inside exceptions
- Refactor Python reserved names id_, input_, filter_
- B018 useless access in tests, noqa'd as I believe these are @property / don't want to change functionality.
- 
- OMG! stop abusing os.path.join to construct URLs

#### Why are we doing this? How does it help us?
Ruff is faster, it also covers a lot more things. (it replicates many flake8 plugins, among others).
It caught quite a few `foo == bar` lacking assert in tests. 
Just a bunch of consistency. Like a higher level black.

Many of the little "code should be this way", but aren't "bugs" that Norm inflicts on reviewees or that Norm suppresses mentioning making him cranky; are automatically enforced before Norm ever has to review any code!

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
For dev side. We should include some smoke tests like on [DEV-4174] but Norm is not sure what they are for rev-engine.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
No

#### Have automated unit tests been added? If not, why?
N/A

#### How should this change be communicated to end users?
N/A

#### Are there any smells or added technical debt to note?
There are a handful of ruff issues that are being ignored, see listing with explanation on why in pyproject.toml. A few are "temporarily" ignored. Resolving them as part of this ticket would be "too risky".

Three that Norm gauged as "important" and got follow on tickets see below.

Norm is not "invested" enough in type annotations to either resolve these or create a follow on ticket.
> ANN", "RUF012", "RUF013", # TODO @njh: type annotations

This one is kind of major change. Which, sadly, I don't believe there is buy in for doing, so didn't bother with ticket for it. [vaguely remember bringing it up long ago and no traction]
> DJ001", # TODO @njh: charfields should not be nullable

#### Has this been documented? If so, where?
N/A

#### What are the relevant tickets? Add a link to any relevant ones.
[DEV-4775]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? 
No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
Yes, 
[DEV-4777]
[DEV-4778] 
[DEV-4779]

2024-05-23 18:44 UTC, x110dc requested changes
A couple typos and a few questions. Didn't review tests or migrations because I was worn out. :-/

2024-05-23 18:44 UTC, x110dc commented on apps/common/management/commands/seed_dev_db.py
> +def create_org_users(orgs, n=1, password="tHiSiStHePaSwOrD"):  # noqa: S107 hardcoded passwors is ok cause dev?
typo: passwors

2024-05-23 18:44 UTC, x110dc commented on apps/common/management/commands/seed_dev_db.py
> +                    contributions.append(  # noqa: PERF401 readability > optomization here
typo: optomization

2024-05-23 18:44 UTC, x110dc commented on apps/contributions/webhooks.py
> +                # TODO: [DEV-4295] Get rid of payment_provider_data as it's an inconistent reference to whichever event
typo: inconistent

2024-05-23 18:44 UTC, x110dc commented on revengine/views.py
> +    # @njh: Probably should be read once on import and stored in a variable, or cached.
Add a todo/ticket?

2024-05-23 18:44 UTC, x110dc commented on scripts/rp-apple-check.py
>              continue
Is this going to show the stack trace? If so would make the output unreadable.

2024-05-23 18:44 UTC, x110dc commented on scripts/rp-apple-check.py
> +            logging.error("apple pay domain missing for %s", rp.slug)
Same here.

2024-05-28 15:16 UTC, benjaminEwhite requested changes

2024-05-28 15:16 UTC, benjaminEwhite commented on apps/organizations/tasks.py
> +    response = requests.post(MAILCHIMP_EXCHANGE_OAUTH_CODE_FOR_ACCESS_TOKEN_URL, data=request_data, timeout=31)
Ditto 31 here as well. If this is meant to be an app wide default, consider putting in settings.

2024-05-28 15:16 UTC, benjaminEwhite commented on apps/organizations/tasks.py
> +        MAILCHIMP_GET_SERVER_PREFIX_URL, headers={"Authorization": f"OAuth {access_token}"}, timeout=31
Ditto re: 31 (last time i'll note though).

2024-05-28 15:16 UTC, benjaminEwhite commented on apps/users/forms.py
> +        """Ensure that.
Was "meh" on being forced to end initial docstring line with period, but this change makes me slightly more annoyed. `Ensure that.` is horrible.

2024-05-28 15:16 UTC, benjaminEwhite commented on apps/users/models.py
> +        return f"{self.organization} - {self.user}"
Why do we add a `__str__` method in this PR?

2024-05-28 21:03 UTC, njharman commented on apps/contributions/tests/test_stripe_contributions_provider.py
> +        stripe_account_id = "test"
Ruff did not like A001 Variable `id` is shadowing a Python builtin.
Norm did not like assignments buried in keyword params.

d0469bb20

2024-05-28 21:07 UTC, njharman commented on apps/contributions/views.py
> +        raise ValidationError({"interval": "The provided value for interval is not permitted"})
More code change than eliminating redundant conditionals. If you write it, I'll add it.

2024-05-28 21:15 UTC, njharman commented on apps/organizations/models.py
> +        help_text="Indicates Slack integration status, designed for manual operation by staff members when connected to the Hub’s Slack",  # noqa: RUF001, RUF003 the "’"
Certainly. help_text is "user" facing. Didn't know if it was specifically chosen for UI reasons. So, didn't change.

Actually, it would require migration. I think. running tests after change got this error:

```
Ensuring no pending migrations                                                                                                                                                                                                                
python manage.py makemigrations --dry-run --check                                                                                                                                                                                             
Migrations for 'organizations':                                                                                                                                                                                                               
  apps/organizations/migrations/0025_alter_organization_show_connected_to_slack.py                                                                                                                                                            
    - Alter field show_connected_to_slack on organization         
```

2024-05-28 21:20 UTC, njharman commented on apps/organizations/tests/test_models.py
> +        mc_connected_rp.mailchimp_store  # noqa: B018 useless .mailchimp_store?
updated comment  7feeb724c

# noqa: B018 Ruff doesn't understand this is a property 
# and accessing it has side effects we are testing.

2024-05-28 21:21 UTC, njharman commented on apps/organizations/tasks.py
> +    response = requests.post(MAILCHIMP_EXCHANGE_OAUTH_CODE_FOR_ACCESS_TOKEN_URL, data=request_data, timeout=31)
7feeb724c

2024-05-28 21:21 UTC, njharman commented on apps/organizations/tasks.py
> +        MAILCHIMP_GET_SERVER_PREFIX_URL, headers={"Authorization": f"OAuth {access_token}"}, timeout=31
7feeb724c

2024-05-28 21:26 UTC, njharman commented on apps/users/models.py
> +        return f"{self.organization} - {self.user}"
DJ008 Model does not define `__str__` method

https://docs.astral.sh/ruff/rules/django-model-without-dunder-str/

2024-05-28 21:27 UTC, njharman commented on apps/users/forms.py
> +        """Ensure that.
67a680243

2024-05-29 14:41 UTC, benjaminEwhite commented on apps/api/tests/test_permissions.py
> +    [
I don't buy the interpretation of tuples as heterogenous and lists as homogenous, but fine with going with this standard.

2024-05-29 14:51 UTC, benjaminEwhite commented on apps/organizations/models.py
> +        help_text="Indicates Slack integration status, designed for manual operation by staff members when connected to the Hub’s Slack",  # noqa: RUF001, RUF003 the "’"
Yeah, no need for migration just for this.

2024-05-29 14:57 UTC, benjaminEwhite approved these changes

2024-05-30 19:12 UTC, x110dc approved these changes

2024-05-31 18:00 UTC, merged