DEV-3871: Add Contact Info screen
newsrevenuehub/rev-engine pull request #1509
Opened 2024-05-13 14:12 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
- Creates Contributor Portal page to update contact information for RP

#### Why are we doing this? How does it help us?
- Allows admins to update contact information that will show in the new portal
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
- yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
- yes
#### Have automated unit tests been added? If not, why?
- yes
#### How should this change be communicated to end users?
- Contact information that shows in new portal can be updated
#### Are there any smells or added technical debt to note?
- no
#### Has this been documented? If so, where?
- no
#### What are the relevant tickets? Add a link to any relevant ones.
- https://news-revenue-hub.atlassian.net/browse/DEV-3871
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
- no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
- Parent ticket: https://news-revenue-hub.atlassian.net/browse/DEV-3782

2024-05-14 14:59 UTC, nrh-cklimas requested changes

2024-05-14 14:59 UTC, nrh-cklimas commented on spa/src/hooks/useRevenueProgram.test.ts
> +      expect(axiosMock.history.patch[0].url).toBe('revenue-programs/123/');
Already tested above.

2024-05-14 14:59 UTC, nrh-cklimas commented on spa/src/hooks/useRevenueProgram.test.ts
> +    it('invalidates the user query on success', async () => {
Should have a matching test under the error section that it doesn't invalidate the user query.

2024-05-14 14:59 UTC, nrh-cklimas commented on spa/src/components/dashboard/Dashboard.styled.js
> +  padding: 48px 60px 0 60px;
Could you explain this change?

2024-05-14 14:59 UTC, nrh-cklimas commented on spa/src/components/content/contributor-portal/ContributorPortal.test.tsx
> +  describe('onSubmit: Saving changes', () => {
Generally, I'd prefer mocking useRevenueProgram instead of mocking the endpoint, since we have good coverage on the hook itself.

2024-05-14 14:59 UTC, nrh-cklimas commented on spa/src/components/content/contributor-portal/ContributorPortal.tsx
> +  );
```suggestion
  const isDifferent = useMemo(
    () => contact_email !== (revenueProgram?.contact_email ?? '') || contact_phone !== (revenueProgram?.contact_phone ?? ''),
    [contact_email, contact_phone, revenueProgram?.contact_email, revenueProgram?.contact_phone]
  );
```
Since it looks like you don't need to distinguish between changes on each field, only that a field was changed.

2024-05-14 14:59 UTC, nrh-cklimas commented on spa/src/components/content/ContributorPortalRoute.test.tsx
> +  it.each([
Need a test that it renders the actual page for RP and org admins.

2024-05-14 14:59 UTC, nrh-cklimas commented on spa/src/components/content/ContributorPortalRoute.test.tsx
> +  it('shows a loading indicator while the user is loading', () => {
Should we add a test for failure to load user?

2024-05-14 15:33 UTC, GuiMend commented on spa/src/components/content/contributor-portal/ContributorPortal.tsx
> +          contact_email: axiosError.response.data?.contact_email?.[0],
Nope, it's only going to be 1 error at a time, but it's in an array format

2024-05-14 21:09 UTC, GuiMend commented on spa/src/components/content/contributor-portal/ContributorPortal.tsx
> +                <TextField
Max length is 255, so it's probably never going to be reached, but I adde it 👍

2024-05-14 21:10 UTC, GuiMend commented on spa/src/components/content/contributor-portal/ContributorPortal.tsx
> +      console.error(error);
it's not necessary to have it.

2024-05-14 21:32 UTC, GuiMend commented on spa/src/hooks/useRevenueProgram.tsx
It had to be tsx because I was returning a snackbar, but I removed it and forgot to update the fie type

2024-05-14 21:37 UTC, GuiMend commented on spa/src/components/dashboard/Dashboard.styled.js
> +  padding: 48px 60px 0 60px;
It's because in Figma it's not matching the design:
(I changed the card's background color to be easier to see the difference)

with `padding: 48px 60px 0 60px;`:
![image](https://github.com/newsrevenuehub/rev-engine/assets/9381325/9d7594d9-008f-4a6f-adb2-75f0f1060b2c)

with `padding: 3rem 3rem 0 3rem;`:
![image](https://github.com/newsrevenuehub/rev-engine/assets/9381325/607c77c8-3e79-4f5a-a3ad-a145636d3176)


figma: https://www.figma.com/design/j5ZbLQqjx8N5wKqgikzUUB/[DES-10]-V1-Contributor-Portal-improvements?node-id=1276-4042&t=mlInRkZLZLpSnOAg-0

2024-05-16 15:12 UTC, nrh-cklimas commented on spa/src/hooks/useRevenueProgram.tsx
> +  return { updateRevenueProgram };
I think you misinterpreted my suggestion. What I intended was something like this:

```
if (rpId) {
 return { updateRevenueProgram };
}

return {};
```

This will get TypeScript to flag usage of `updateRevenueProgram` without first checking that it's defined, so you don't have to worry about warning or otherwise erroring--TS will do it for you.

2024-05-16 15:17 UTC, nrh-cklimas commented on spa/src/components/content/contributor-portal/ContributorPortal.tsx
> +          </SuccessMessage>
You mentioned in Jira that this is using a UI pattern on the Organization page. Let's move this to a separate component in that case that we reuse in both places.

2024-05-16 15:18 UTC, nrh-cklimas commented on spa/src/components/content/ContributorPortalRoute.test.tsx
> +  ])('should render Contributor Portal page', () => {
Think we're missing setting `getUserRoleMock` here?

2024-05-16 15:23 UTC, nrh-cklimas commented on spa/src/components/dashboard/Dashboard.styled.js
> +  padding: 48px 60px 0 60px;
This is causing a layout shift on the Pages route as well. Is that intentional? I feel like something is off here because the highlighted area is below main content in your screenshot, but framing the entire page content on the Pages route. I'll attach a screen recording in Jira showing the shift.

2024-05-16 20:27 UTC, GuiMend commented on spa/src/components/dashboard/sidebar/DashboardSidebar.styled.ts
> +export const ManageAccountIcon = styled(ManageIcon)`
It's a good idea, but I didn't find all the icons in one lib 😢

2024-05-16 20:29 UTC, GuiMend commented on spa/src/components/content/contributor-portal/ContributorPortal.tsx
> +                <TextField
Done!

2024-05-17 19:38 UTC, nrh-cklimas approved these changes

2024-05-20 14:26 UTC, GuiMend commented on spa/src/components/content/ContributorPortalRoute.test.tsx
> +  ])('should render Contributor Portal page', () => {
Yes, thanks for catching that! Also updated the text which was outdated

2024-05-20 15:01 UTC, nrh-cklimas commented on spa/src/components/dashboard/sidebar/DashboardSidebar.styled.ts
> +export const ManageAccountIcon = styled(ManageIcon)`
Got it. Maybe one day we can clean this up.

2024-05-20 15:04 UTC, nrh-cklimas commented on spa/src/components/common/SuccessBanner/SuccessBanner.tsx
> +  if (!show) return null;
Nitpicking: since this isn't animated, I think the prop could be removed and consumers could do `{show && <SuccessBanner .../>`?

2024-05-20 17:03 UTC, GuiMend commented on spa/src/components/common/SuccessBanner/SuccessBanner.tsx
> +  if (!show) return null;
Sure. Done!

2024-05-20 17:09 UTC, nrh-cklimas commented on spa/src/components/common/SuccessBanner/SuccessBanner.test.tsx
> +  it('should render message text when show is true', async () => {
```suggestion
  it('should render message text', async () => {
```

2024-05-22 13:12 UTC, merged