DEV-4784 | create a management command to fix imported contributions that incorrectly point to default donation page
newsrevenuehub/rev-engine pull request #1512
Opened 2024-05-14 15:11 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

This PR adds a management command to fix a subset of imported contributions created by Stripe transactions import.

There was a bug in the command implementation — fixed in []() — whereby default donation page for a contribution's RP got assigned as the value for contribution.donation_page, even when this wasn't warranted.

The management command herein identifies contributions that ended up in this state.  Specifically, it looks for contributions that:

- Have a revision comment indicating they were created by Stripe transactions import
- Have contribution metadata that either doesn't have an entry for `referer` or an empty string for that value
- Have a donation page set, and that donation page is the same donation page as the parent RP's default donation page

For these contributions, the command deletes the donation_page foreign key and sets `.revenue_program` to the revenue program indicated by the `revenue_program_id` field in the metadata.

Additionally, this PR makes a small change to `StripeTransactionsImporter.get

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2024-05-15 15:37 UTC, njharman approved these changes

2024-05-15 15:37 UTC, njharman commented on apps/contributions/management/commands/fix_imported_contributions_with_incorrect_donation_page_value.py
> +REVISION_COMMENT = "StripeTransactionsImporter.upsert_contribution created Contribution"
I believe this string is derived from utils.py::upsert_with_diff_check() There are two paths in that function, "created" and "updated". 

Checking, asking; updated Contributions can't or didn't create any of the bad records being corrected with this command?

2024-05-15 15:37 UTC, njharman commented on apps/contributions/management/commands/fix_imported_contributions_with_incorrect_donation_page_value.py
> +            self.style.HTTP_INFO("Running `fix_imported_contributions_with_incorrect_donation_page_value`")
To protect against filename changes/DRY. I tend to make use of __file__ for these kind of messages. Maybe you have to strip off path, I think so. Path.stem()

2024-05-15 16:22 UTC, benjaminEwhite commented on apps/contributions/management/commands/fix_imported_contributions_with_incorrect_donation_page_value.py
> +REVISION_COMMENT = "StripeTransactionsImporter.upsert_contribution created Contribution"
That is correct. We only want to target ones that were created, not ones that were updated. In fact, updated ones should not have been able to be put in the state caused by original bug necessitating this management command.

2024-05-15 16:53 UTC, benjaminEwhite commented on apps/contributions/management/commands/fix_imported_contributions_with_incorrect_donation_page_value.py
> +            self.style.HTTP_INFO("Running `fix_imported_contributions_with_incorrect_donation_page_value`")
d95b4bdfc4

2024-05-16 20:22 UTC, x110dc requested changes
a couple very minor changes and some possible discrepancies with what's in the this PR and what's in the PR description

2024-05-16 20:22 UTC, x110dc commented on apps/contributions/management/commands/fix_imported_contributions_with_incorrect_donation_page_value.py
> +            rp = RevenueProgram.objects.get(pk=x.contribution_metadata["revenue_program_id"])
minor: looks like `rp` variable is only used once so probably didn't need it

2024-05-16 20:22 UTC, x110dc commented on apps/contributions/management/commands/fix_imported_contributions_with_incorrect_donation_page_value.py
> +            self.stdout.write(self.style.HTTP_INFO("No effected contributions found, exiting"))
super minor: affected, not effected

2024-05-16 20:22 UTC, x110dc commented on apps/contributions/stripe_import.py
> +    def get_payment_method_id_for_stripe_entity(
the set of changes in this file doesn't seem to be mentioned in the PR description? Maybe I'm misunderstanding.

2024-05-16 20:22 UTC, x110dc commented on apps/contributions/stripe_import.py
>                  contribution, action = self.upsert_contribution(stripe_entity=pi, is_one_time=True)
The PR description says: 

> Additionally, this PR makes a small change to StripeTransactionsImporter. get_or_create_contributor_from_customer to solve for an edge case discovered when running transactions import locally when a Stripe customer is encountered that has no value for the email property.

But I don't see those changes in this PR.

2024-05-16 20:27 UTC, benjaminEwhite commented on apps/contributions/management/commands/fix_imported_contributions_with_incorrect_donation_page_value.py
> +            self.stdout.write(self.style.HTTP_INFO("No effected contributions found, exiting"))
145033e265dc

2024-05-16 20:29 UTC, benjaminEwhite commented on apps/contributions/management/commands/fix_imported_contributions_with_incorrect_donation_page_value.py
> +            rp = RevenueProgram.objects.get(pk=x.contribution_metadata["revenue_program_id"])
b4a8d52a01

2024-05-16 20:45 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +    def get_payment_method_id_for_stripe_entity(
Not misunderstanding. I seem to have accidentally committed/pushed changes from another branch when switching between branches locally. I've removed the errant changes, so everything should be in line with PR now.

2024-05-16 20:46 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
>                  contribution, action = self.upsert_contribution(stripe_entity=pi, is_one_time=True)
See previous comment. I seem to have accidentally saved some changes from a different branch into this one, likely when switching between branches with VSCode open.

Changes should now align with PR description.

2024-05-16 21:28 UTC, x110dc approved these changes
LGTM.

2024-05-21 14:59 UTC, merged