DEV-4761: pre Django 4 updates
newsrevenuehub/rev-engine pull request #1517
Opened 2024-05-17 18:19 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

This pulls the majority of work out of https://github.com/newsrevenuehub/rev-engine/pull/1453. The goal is to make all changes that aren't dependent on Django 4 here.

- Replace usage of csrf._get_new_csrf_token() with csrf._get_new_csrf_string() in tests.
- Fix Heisenbug behavior in ContributionFactory.
- Repace usage of the pytz library with zoneinfo.
- Replace path specs in apps/api/urls.py with plain path instead of re_path.
-  Make the denylistword.word field case-insensitive.
- Replace usage of short_description in admin.py files with @admin.display annotation.
- Add rule number to noqa comment in revengine.settings.deploy module.
- Revise imports in revengine/urls.py to use best practices.

#### Why are we doing this? How does it help us?

Derisk the Django upgrade itself.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

Yes.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No.

#### Have automated unit tests been added? If not, why?

A few test updates.

#### How should this change be communicated to end users?

n/a

#### Are there any smells or added technical debt to note?

No.

#### Has this been documented? If so, where?

No.

#### What are the relevant tickets? Add a link to any relevant ones.

- https://news-revenue-hub.atlassian.net/browse/DEV-4761
- https://news-revenue-hub.atlassian.net/browse/DEV-4110

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

Actual upgrade-- probably will be done in DEV-4110.

2024-05-17 19:33 UTC, nrh-cklimas commented on scripts/heroku-postdeploy.sh
> +DROP OWNED by current_user CASCADE;
This resolved the deploy issue we had been seeing where it complained about a collation with the same name already existing. I don't believe there are any downsides to adding this but I can't say I'm an expert.

2024-05-22 15:18 UTC, benjaminEwhite requested changes
code changes look good to me. I’m basically :thumbsup: save for this oddity around the integrity error around the collation. Ideally, I’d like us to understand root cause instead of changing post deploy script as workaround. That said, I’d also like to unblock this work, so on the fence. I’d like to get Daniel’s feedback on that conversation thread.

 

Other than that, only thing to note is I think it would be good to have a bit more detail in the “What’s this PR do?” section.  Would be good to list the main changes (inclusive of the changes to factory code setting status to paid, which IIRC wasn’t strictly necessary for upgrade, but kills some intermittent test failures that were creating noise when trying to understand if there were regressions with upgrade).

2024-05-22 15:18 UTC, benjaminEwhite commented on scripts/heroku-postdeploy.sh
> +DROP OWNED by current_user CASCADE;
@nrh-cklimas this seems like an okay workaround, but I'm not crazy about modifying this script without understanding why this bug is happening in the first place. 

Think I'd like to defer to @x110dc on best way forward here.  Daniel for additional context, without this line added to post deploy, the build for review app fails because when migrations run, a collation called `case_insensitive` is already found, and get error when trying to create new collation with same name.

I poked around in staging and discovered that we had a collation with that name (probably from testing changes in staging). I deleted the collation and migration records from staging, which I would have thought would have prevented the integrity error, but turns out we still got it even after deleting case_insensitive from staging.

2024-05-22 19:21 UTC, benjaminEwhite approved these changes

2024-05-23 16:44 UTC, benjaminEwhite approved these changes

2024-05-23 18:52 UTC, njharman requested changes

2024-05-23 18:52 UTC, njharman commented on apps/config/tests/test_models.py
> +        DenyListWord(word=new_text).save()
Man, I find this test massively confusing. I don't know what it is suppose to be testing. It doesn't appear to be testing anything other than if a == b (test_basics), then I change b, a != b. 😕  

First, do I understand collation correctly?  It only has to do with sorting, right https://www.postgresql.org/docs/current/collation.html

1. Why do we need collation at all?  I don't think we are concerned with denylist sort order. We lower() in validator (only thing we need to do). 
def validate_slug_against_denylist(value):
```
    denylist_words = DenyListWord.objects.all().values_list(Lower("word"), flat=True)
    if value.lower() in denylist_words:
```
2. In this test; Why create new fixture and not use DenyListWordFactory (which should be updated to have words of mixed capitalization)
3. Why even have this test?

2024-05-23 20:15 UTC, benjaminEwhite commented on apps/config/tests/test_models.py
> +        DenyListWord(word=new_text).save()
yeah, this was lazy/trivial testing. added substantive tests in 9dc780bd3a8b2

2024-05-28 18:34 UTC, njharman approved these changes

2024-05-30 19:44 UTC, x110dc approved these changes

2024-06-04 18:00 UTC, merged