DEV-4703: Add BE validation errors to ResetPassword
newsrevenuehub/rev-engine pull request #1518
Opened 2024-05-20 15:06 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
- Add BE password validation error to ResetPassword
#### Why are we doing this? How does it help us?
- If ResetPassword fails, show the user the error so that they can fix it
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
- yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
- no
#### Have automated unit tests been added? If not, why?
- yes
#### How should this change be communicated to end users?
- n/a
#### Are there any smells or added technical debt to note?
- no
#### Has this been documented? If so, where?
- no
#### What are the relevant tickets? Add a link to any relevant ones.
- https://news-revenue-hub.atlassian.net/browse/DEV-4703
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
- no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
- no

2024-05-20 18:24 UTC, nrh-cklimas requested changes

2024-05-20 18:24 UTC, nrh-cklimas commented on spa/src/components/account/ResetPassword/ResetPasswordForm.tsx
> +  passwordError?: string;
I think InferProps gives us this--no need to specify, unlike functions where we need to spec the arguments.

2024-05-20 18:24 UTC, nrh-cklimas commented on spa/src/components/account/ResetPassword/ResetPassword.test.tsx
We should add tests here exercising the network aspects of ResetPassword.

- Sends to correct endpoint using POST
- Handles success correctly
- Passes errors down to ResetPasswordForm 👈 this is the part we really want to test, but coverage on the component isn't good in main

2024-05-21 15:50 UTC, GuiMend commented on spa/src/components/account/ResetPassword/ResetPasswordForm.tsx
> +  passwordError?: string;
The `InferProps` does `passwordError = null | undefined | string` and I was overriding to not accept null

2024-05-23 18:36 UTC, nrh-cklimas commented on spa/src/components/account/ResetPassword/ResetPasswordForm.tsx
> +  passwordError?: string;
Hm--I took this line out locally and TypeScript doesn't complain. It's not a big deal either way.

2024-05-23 18:39 UTC, nrh-cklimas commented on spa/src/components/account/ResetPassword/ResetPassword.test.tsx
> +    it('should pass validation errors to the form', async () => {
One last coverage thing--should test what happens if the endpoint returns a network error. That part appears uncovered in `npm run test:coverage`.

2024-05-27 16:46 UTC, GuiMend commented on spa/src/components/account/ResetPassword/ResetPassword.test.tsx
> +    it('should pass validation errors to the form', async () => {
@nrh-cklimas , I'm not sure how to cover line 48-49. I actually don't think that is ever used. What do you say we remove it?

2024-05-28 16:59 UTC, nrh-cklimas approved these changes

2024-05-28 17:00 UTC, nrh-cklimas commented on spa/src/components/account/ResetPassword/ResetPassword.test.tsx
> +    it('should pass validation errors to the form', async () => {
Noting for future reference that we talked this through on Slack.

2024-05-29 13:51 UTC, merged