DEV-4610: Add custom integrations to settings
newsrevenuehub/rev-engine pull request #1521
Opened 2024-05-27 17:22 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
- Adds custom integration to user settings
#### Why are we doing this? How does it help us?
- Expand integrations visible to user
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
- Yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
- yes
#### Have automated unit tests been added? If not, why?
- yes
#### How should this change be communicated to end users?
- New integrations available in settings
#### Are there any smells or added technical debt to note?
- no
#### Has this been documented? If so, where?
- no
#### What are the relevant tickets? Add a link to any relevant ones.
- https://news-revenue-hub.atlassian.net/browse/DEV-4610
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
- no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
- no

2024-05-31 19:47 UTC, nrh-cklimas requested changes

2024-05-31 19:47 UTC, nrh-cklimas commented on apps/organizations/models.py
Because it's not yet possible for an RP to be connected to any of these integrations, I think it's not worth it to add these fields to the model yet. I think this would lessen the scope of the PR a lot.

2024-05-31 19:47 UTC, nrh-cklimas commented on spa/src/components/common/IntegrationCard/DigestbuilderIntegrationCard/DigestbuilderIntegrationCard.tsx
Since all these cards are doing essentially the same thing--showing some info but otherwise are inert--I think it makes sense to collect that functionality into a component so you don't have to repeatedly test nearly the same thing.

2024-05-31 19:47 UTC, nrh-cklimas commented on spa/src/components/common/IntegrationCard/DigestbuilderIntegrationCard/DigestbuilderIntegrationCard.tsx
> +          <a href={HELP_URL} style={{ textDecoration: 'underline' }} target="_blank" rel="noreferrer">
```suggestion
          <Link href={HELP_URL} target="_blank">
```
Getting it onto our base component.

2024-06-03 13:48 UTC, GuiMend commented on apps/organizations/models.py
AC 2 asks for the BE. Should we change that?

2024-06-03 15:13 UTC, nrh-cklimas commented on apps/organizations/models.py
I feel yes but I think @benjaminEwhite should have the final say. To be honest, I don't understand the intent of AC 2.

2024-06-03 15:16 UTC, nrh-cklimas commented on spa/src/components/common/IntegrationCard/CustomIntegrationCard/CustomIntegrationCard.tsx
> +export const CARD_TYPES = {
How would you feel about making these props on CustomIntegrationCard and having Integration pass them?

2024-06-03 15:19 UTC, nrh-cklimas commented on spa/src/components/common/IntegrationCard/CustomIntegrationCard/CustomIntegrationCard.tsx
> +        cardType?.toggleLabel ?? (
I think based on commentary in Jira, it should never show a contact support message. If I have that correct, this, `toggleTooltipMessage`, and `toggleConnectedTooltipMessage` should be hard-coded.

2024-06-03 17:06 UTC, GuiMend commented on spa/src/components/common/IntegrationCard/CustomIntegrationCard/CustomIntegrationCard.tsx
> +        cardType?.toggleLabel ?? (
Only GA should have the "coming soon" tooltip. All the other cards should still have "contact support"

2024-06-05 13:09 UTC, benjaminEwhite approved these changes
Backend changes LGTM.

2024-06-05 14:16 UTC, nrh-cklimas commented on spa/src/components/common/IntegrationCard/CustomIntegrationCard/CustomIntegrationCard.test.tsx
Let's improve coverage here.

We should add tests around the props, to prove that:
- They are displayed if passed
- toggleLabel uses the default if toggleLabelOverride isn't set
- Same for toggleTooltipMessage

Because this is using useUser directly, this should have tests around loading and error state there (e.g. what its behavior is while user is loading, and what it does if user can't load). Or move that logic upward into Integration and test there.

2024-06-10 14:35 UTC, GuiMend commented on spa/src/components/common/IntegrationCard/CustomIntegrationCard/CustomIntegrationCard.test.tsx
[fix migration name and order + increase test coverage](https://github.com/newsrevenuehub/rev-engine/pull/1521/commits/3ad2fe2efedcb7d5556d2195ba75a5362cb3d423)

2024-06-10 15:51 UTC, nrh-cklimas approved these changes

2024-06-25 20:10 UTC, merged