DEV-4818 | Solve for backfill slowness
newsrevenuehub/rev-engine pull request #1524
Opened 2024-05-28 18:15 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2024-05-28 20:54 UTC, x110dc requested changes

2024-05-28 20:54 UTC, x110dc commented on apps/contributions/stripe_import.py
> +        hub = Hub.current
I'm a little confused about the Sentry profile setup here. It doesn't seem to follow the instructions here https://docs.sentry.io/platforms/python/profiling/#enable-profiling . I don't see the the DSN anywhere so I don't know how this could work.

2024-05-30 19:04 UTC, x110dc requested changes

2024-05-30 19:04 UTC, x110dc commented on apps/contributions/management/commands/import_stripe_transactions_data.py
> +        account_ids = [account for account in _account_ids if self.stripe_account_connected(account)]
Since most accounts are connected I'd think it would make sense to optimistically assume they'll connect and just catch and handle the exceptions when they don't instead of this long-running up-front work to connect to every single account?

2024-05-30 19:20 UTC, benjaminEwhite commented on apps/contributions/management/commands/import_stripe_transactions_data.py
> +        account_ids = [account for account in _account_ids if self.stripe_account_connected(account)]
The alternative was something like adding try/except stripe.error.PermissionError around `.import_contributions_and_payments`, which I don't love, but perhaps for aesthetic reasons more than anything substantive.

2024-05-30 19:37 UTC, benjaminEwhite commented on apps/contributions/management/commands/import_stripe_transactions_data.py
> +        account_ids = [account for account in _account_ids if self.stripe_account_connected(account)]
Ended up moving to a try/except that wraps the synchronous calling context (if there's a problem in async, that won't stop execution of each account/org). 999e9571adf

2024-05-30 19:59 UTC, x110dc approved these changes

2024-05-30 20:40 UTC, merged