DEV-4777 Don't use naive datetimes
newsrevenuehub/rev-engine pull request #1529
Opened 2024-05-31 21:58 UTC by njharman

#### What's this PR do?

- Enables Ruff DTZ naive datetime rules
- Enlightens naive datetimes.

Note: three `make_aware `and ne `convert_to_timezone_formatted `tests helperare testing naive to non-naive conversion and are noqa'd

PR comments highlight these issues to be resolved during review
- Several tests depend on `user.accepted_terms_of_service` being naive. I'm not sure this is valid. But did not want to "fix" before receiving review feedback.
- There are some set cookie that i updated to use aware timezones for expiry. Note sure if this is correct standard?

#### Why are we doing this? How does it help us?
Time is hard. This helps avoid problems. Like, don't you expect datetime.datetime.utcnow() to have UTC timezone set. I did.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
No. Not sure what should be tested.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
No.

#### Have automated unit tests been added? If not, why?
Slight change to some, no new ones.

#### How should this change be communicated to end users?
N/A

#### Are there any smells or added technical debt to note?
There are noqa that should be better documented or removed (see above and PR comments)

#### Has this been documented? If so, where?
N/A

#### What are the relevant tickets? 
[DEV-4777]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
No.

2024-05-31 22:11 UTC, njharman commented on apps/api/tests/test_views.py
> +        datetime.datetime.utcnow()  # noqa: DTZ003 test depends on naive, breaks test
I question if tests should expect naive datetime. 

Isn't this "user" eventually a DB model with timezone? Or, is this simulation "web" data, with no actual TZ.  users test_serializers compares to pytz.utc.localize() on this

2024-05-31 22:11 UTC, njharman commented on conftest.py
> +        accepted_terms_of_service=datetime.datetime.utcnow(), email_verified=True  # noqa: DTZ003 test fails
test fails if not naive

2024-05-31 22:11 UTC, njharman commented on apps/api/tests/test_views.py
> +    rp_user.accepted_terms_of_service = datetime.datetime.utcnow()  # noqa: DTZ003 test depends on naive, breaks test
test fails if not naive

2024-05-31 22:11 UTC, njharman commented on apps/api/views.py
> +            datetime.datetime.now(datetime.timezone.utc) + settings.SIMPLE_JWT["ACCESS_TOKEN_LIFETIME"],
This sets cookie lifetime. I assume it eventually gets formatted into whatever HTTP standard requires for cookies. And that making it tz aware won't break the internet.

2024-06-04 18:16 UTC, x110dc requested changes

2024-06-04 18:16 UTC, x110dc commented on apps/api/tests/test_views.py
> +        datetime.datetime.utcnow()  # noqa: DTZ003 test depends on naive, breaks test
I think we should make all of these TZ aware.

2024-06-04 18:16 UTC, x110dc commented on apps/api/tests/test_views.py
> +    rp_user.accepted_terms_of_service = datetime.datetime.utcnow()  # noqa: DTZ003 test depends on naive, breaks test
Make it TZ aware.

2024-06-04 18:16 UTC, x110dc commented on apps/api/views.py
> +            datetime.datetime.now(datetime.timezone.utc) + settings.SIMPLE_JWT["ACCESS_TOKEN_LIFETIME"],
I would think so but I'm not sure.

2024-06-04 18:16 UTC, x110dc commented on conftest.py
> +        accepted_terms_of_service=datetime.datetime.utcnow(), email_verified=True  # noqa: DTZ003 test fails
And we can rewrite the test to use aware?

2024-06-11 15:30 UTC, benjaminEwhite approved these changes
LGTM.

2024-06-11 15:30 UTC, benjaminEwhite commented on apps/api/views.py
> +            datetime.datetime.now(datetime.timezone.utc) + settings.SIMPLE_JWT["ACCESS_TOKEN_LIFETIME"],
Should be straightforward to look at actual jwt in review app in authorization cookie and decode it at jwt.io and confirm that the iat/exps values make sense.

<img width="658" alt="Screenshot 2024-06-11 at 5 27 00 PM" src="https://github.com/newsrevenuehub/rev-engine/assets/960351/87b76d6d-a36d-4e0a-8bea-4c9d1ef205c2">

2024-06-12 21:44 UTC, x110dc approved these changes
lgtm

2024-06-25 18:45 UTC, merged