DEV-4779 consistent boolean environment vars
newsrevenuehub/rev-engine pull request #1530
Opened 2024-05-31 23:22 UTC by njharman

#### What's this PR do?
Resolve Ruff issue PLW1508 which has to do with os.getenv default values being something other than string.

Creates function to booleanize envvar strings. 

#### Why are we doing this? How does it help us?
To replace the hodgepodge of inconsistent conversion too bool.
Missing or malformed envvars produce clear error message (exception).

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
No. Not sure how to test.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
No.

#### Have automated unit tests been added? If not, why?
Yes.

#### How should this change be communicated to end users?
N/A

#### Are there any smells or added technical debt to note?
No.

#### Has this been documented? If so, where?
N/A

#### What are the relevant tickets? Add a link to any relevant ones.
[DEV-4779]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
Production settings.py should be altered to use get_bool_envvar()

This "changes" how environment variables are read.  It is now more consistent and accepts a superset of booleans; case insensitive, leading/trailing white space ignored "true", "false".  Being a super set, nothing should break.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
No.

2024-06-11 14:03 UTC, nrh-cklimas requested changes

2024-06-11 14:03 UTC, nrh-cklimas commented on revengine/settings/base.py
> +DEBUG = env.bool("DJANGO_DEBUG", False)
I was curious about how this works and it appears this is a change in functionality we will want to test around. I can't find documentation in `environs` on what values it exactly takes, but it's looser than what we've been doing:

- `"t"` is parsed to `True`
- `"f"` is parsed to `False`
- empty string raises a `EnvValidationError`
- unset env variable raises a `EnvError`

It's the empty string and unset vars that raise a flag for me because I could see us using the looser defaulting in the existing code. Think something to address in QA and/or possibly document.

2024-06-12 16:42 UTC, njharman commented on revengine/settings/base.py
> +DEBUG = env.bool("DJANGO_DEBUG", False)
I considered adding coverage to settings files. Seemed too low ROI

1. many potential test would really just be testing how 3rd party lib works
2. still wouldn't provide actual coverage/protection as it can't test prod
3. there's **a lot** of envars, tons of Mocking, lots of time to test

Added to PR a list of Booleans andand the truthy values for deployers to check against env.

environs docs are severly lacking. Looking at code it uses [marshmellow ](https://marshmallow.readthedocs.io/en/stable/marshmallow.fields.html#marshmallow.fields.Boolean.truthy) which defaults are 

```
falsy = {'0', 'F', 'FALSE', 'False', 'N', 'NO', 'No', 'OFF', 'Off', 'f', 'false', 'n', 'no', 'off', 0}
truthy = {'1', 'ON', 'On', 'T', 'TRUE', 'True', 'Y', 'YES', 'Yes', 'on', 't', 'true', 'y', 'yes', 1}
```

2024-06-12 16:42 UTC, njharman commented on revengine/settings/base.py
>  except json.JSONDecodeError:
I should have wrote those tests!

2f1a948e3

2024-06-12 16:58 UTC, nrh-cklimas approved these changes

2024-06-12 23:04 UTC, x110dc approved these changes
LGTM.

2024-06-17 14:38 UTC, merged