DEV-4772: Add management command to fix contributions w/o sub IDs
newsrevenuehub/rev-engine pull request #1535
Opened 2024-06-04 14:32 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

Creating PR for an initial review on the approach.

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2024-06-04 15:00 UTC, benjaminEwhite requested changes

2024-06-04 15:00 UTC, benjaminEwhite commented on apps/contributions/management/commands/fix_recurring_contribution_missing_provider_subscription_id.py
> +            c_id = contribution.id
If this is only referenced once, no need for var.

2024-06-04 15:02 UTC, nrh-cklimas commented on apps/contributions/management/commands/fix_recurring_contribution_missing_provider_subscription_id.py
> +            c_id = contribution.id
This was to placate ruff telling my line was too long :(

2024-06-05 20:00 UTC, nrh-cklimas commented on apps/contributions/management/commands/fix_recurring_contribution_missing_provider_subscription_id.py
> +            except stripe.error.InvalidRequestError:
This was the exception I got when I asked for a nonexistent payment intent ID, which feels like a potentially common scenario?

2024-06-05 21:13 UTC, nrh-cklimas commented on apps/contributions/management/commands/fix_recurring_contribution_missing_provider_subscription_id.py
> +            fixed = fixed + 1
Done in bf3903e2902152e61fb91c5a77bbe676c3f7252a

2024-06-05 21:13 UTC, nrh-cklimas commented on apps/contributions/management/commands/fix_recurring_contribution_missing_provider_subscription_id.py
> +                intent = stripe.PaymentIntent.retrieve(
Done in bf3903e2902152e61fb91c5a77bbe676c3f7252a

2024-06-05 21:13 UTC, nrh-cklimas commented on apps/contributions/management/commands/fix_recurring_contribution_missing_provider_subscription_id.py
> +                    contribution.provider_payment_id, stripe_account=contribution.payment_provider_data["account"]
Done in bf3903e2902152e61fb91c5a77bbe676c3f7252a

2024-06-07 17:29 UTC, benjaminEwhite requested changes

2024-06-07 17:29 UTC, benjaminEwhite commented on apps/contributions/management/commands/fix_recurring_contribution_missing_provider_subscription_id.py
> +        for contribution in contributions:
This loop will be ended if there is a problem connecting to a Stripe account (say for instance we touch a contribution whose RP has disconnected stripe access).  We should consider checking stripe account connection status for eligible contributions and not attempting with disconnected accounts (examples of that in other management commands) or else gracefully handle that stripe error in situ so it doesn't cause the entire command to fail.

2024-06-07 17:29 UTC, benjaminEwhite commented on apps/contributions/management/commands/fix_recurring_contribution_missing_provider_subscription_id.py
> +            with reversion.create_revision():
Instead of db committing one contribution at a time, consider doing a bulk update.

This block would remove the reversion bits and would not call save. Just update the contribution, then should append it to a list of updated_contributions.

After loop completes, then do:

```
with reversion.create_revision():
    Contribution.objects.bulk_update(updated_contributions)
    reversion.set_comment("Updated by fix_recurring_contribution_missing_provider_subscription_id....."
```

2024-06-07 17:29 UTC, benjaminEwhite commented on apps/contributions/management/commands/fix_recurring_contribution_missing_provider_subscription_id.py
> +            except stripe.error.InvalidRequestError:
Not sure how frequent, but fine to be defensive here.

2024-06-07 18:02 UTC, nrh-cklimas commented on apps/contributions/management/commands/fix_recurring_contribution_missing_provider_subscription_id.py
> +        self.stdout.write(self.style.HTTP_INFO("Running `fix_recurring_contribution_missing_provider_subscription_id`"))
Updated in 2f94c4587722eaeb41c53d55ee606d248e1c39a1

2024-06-07 18:08 UTC, nrh-cklimas commented on apps/contributions/management/commands/fix_recurring_contribution_missing_provider_subscription_id.py
> +            c_id = contribution.id
Not sure what I was doing before, but you're right. 0f7d89da0b1fd75cc197658385958799f40e8b45

2024-06-07 18:23 UTC, nrh-cklimas commented on apps/contributions/management/commands/fix_recurring_contribution_missing_provider_subscription_id.py
> +            with reversion.create_revision():
Updated in 9ba36322c409be0f5af20184b5b80349b1602811.

2024-06-07 20:11 UTC, nrh-cklimas commented on apps/contributions/management/commands/fix_recurring_contribution_missing_provider_subscription_id.py
> +        for contribution in contributions:
Updated in 90b1e8ebc354ac228aad5851ec6b09e6b6c3fbb2

2024-06-10 14:22 UTC, nrh-cklimas commented on apps/contributions/management/commands/fix_recurring_contribution_missing_provider_subscription_id.py
> +            with reversion.create_revision():
Added in 397c060258f43dfef40178ba43aefb3444ec9f2a

2024-06-11 15:43 UTC, benjaminEwhite requested changes
One small request for change in object code.

Re: tests, ideally would like 100% coverage on the command file, and currently its at 74%.

<img width="1410" alt="Screenshot 2024-06-11 at 5 42 58 PM" src="https://github.com/newsrevenuehub/rev-engine/assets/960351/9258d7a4-a5ac-426a-aa6d-0b5553adf5d0">

2024-06-11 15:43 UTC, benjaminEwhite commented on apps/contributions/management/commands/fix_recurring_contribution_missing_provider_subscription_id.py
> +            Contribution.objects.bulk_update(fixed, fields=["provider_subscription_id"])
Just for consistency sake elsewhere, let's make this a set instead of a list (and you can make commit and resolve this).

```suggestion
            Contribution.objects.bulk_update(fixed, fields={"provider_subscription_id"})
```

2024-06-11 20:51 UTC, nrh-cklimas commented
> Re: tests, ideally would like 100% coverage on the command file, and currently its at 74%

This was a regression I added in recent commits. Fix should be in 9ec14621cf57ef0e7914dfe2f96c78d3c278250a -- now I finally understand the comment on the other management command test around mocking issues.

2024-06-12 18:02 UTC, benjaminEwhite approved these changes
Had a handful of minor suggestions, around logs but no need for me to review again.

Approved.

2024-06-13 14:37 UTC, njharman approved these changes

2024-06-13 14:37 UTC, njharman commented on apps/contributions/management/commands/fix_recurring_contribution_missing_provider_subscription_id.py
> +        )
I bet we can't use the revenue_program @property in a Query?

Out of scope; but we should consider adding something (I forget exactly how with django ORM, custom QueryResult class?  ContributionManager method?) to implement this dual id source logic. Rather than duplicate this everywhere.

2024-06-21 20:58 UTC, x110dc approved these changes
lgtm

2024-06-25 18:47 UTC, merged