DEV-4110: Upgrade Django to 4
newsrevenuehub/rev-engine pull request #1539
Opened 2024-06-07 14:25 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

This is a redo of https://github.com/newsrevenuehub/rev-engine/pull/1453 now that we pulled a lot of its content into a separate PR we've already merged, https://github.com/newsrevenuehub/rev-engine/pull/1517.

The most significant change here is using a vanilla `CharField` in the `DenyListWord` model instead of `CICharField`, which has been deprecated in Django 4. I added a uniqueness constraint there and updated `apps/config/validators.py` to move the case-insensitivity into our own code.

#### Why are we doing this? How does it help us?

Keeps us up-to-date.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No.

#### Have automated unit tests been added? If not, why?

Updated a few tests. Removed the tests around case-insensitive retrieval because that's not possible with a plain charfield (I think). The goal is to change everything using that retrieval to be case-insensitive.

#### How should this change be communicated to end users?

n/a

#### Are there any smells or added technical debt to note?

No.

#### Has this been documented? If so, where?

No.

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-4110

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No.

2024-06-07 14:26 UTC, nrh-cklimas commented on apps/users/models.py
> +    def validate_unique(self, exclude: set) -> None:
This was a little odd because it wasn't in the original PR, but I got an error in unit tests without this change. [Docs say this is a set, not a list](https://docs.djangoproject.com/en/4.2/ref/models/instances/#django.db.models.Model.validate_unique).

2024-06-17 13:18 UTC, benjaminEwhite reviewed
One comment around pivot away from collation strategy and PR description.

Also wanted to point out that we could at least consider moving the case insensitive validation bits into a separate PR so that we have the upgrade changes here in isolation, but that might be overkill.

2024-06-17 13:18 UTC, benjaminEwhite commented on apps/config/models.py
> +        ]
Why are we going with this over using collation strategy we were pursuing in past?

Might be worth addressing this in PR description.  Downside of this approach is that it's likely less performant than using a db-level collation, but that's probably not a big deal here since `DenyListWord` is infrequently accessed.

2024-06-17 13:27 UTC, benjaminEwhite requested changes
Final request:

Think it's worthwhile adding unit tests of `validate_slug_against_denylist`. It is not tested in isolation in status quo.

2024-06-17 21:53 UTC, nrh-cklimas commented on apps/config/models.py
> +        ]
Updated in b78c5ea6876252891341b1f4612f019d91998bce

2024-06-17 21:54 UTC, nrh-cklimas commented
> Think it's worthwhile adding unit tests of `validate_slug_against_denylist`. It is not tested in isolation in status quo.

ac1d96d880f49b2c8d03eb77ece0f0b2baa02297

2024-06-18 13:30 UTC, benjaminEwhite requested changes
@nrh-cklimas 

- The PR description needs to be updated to reflect the current decisions around collation
-  I think in an earlier version there was testing around the confiword model that proved that you got case inensitive search. I think that would be good to bring back, because the business logic here spans both not allowing creation of duplicate (from perspective of case insensitivity) and furnishing case insensitive results.

2024-06-18 13:30 UTC, benjaminEwhite commented on apps/config/migrations/0003_DEV-4110_add_case_insensitive_collation.py
Probably worth squashing the two migrations into a single one if possible (fwiw, [this is the standard established in 17 here](https://news-revenue-hub.atlassian.net/wiki/spaces/TECH/pages/44466177/Pull+Request+Policies)).

2024-06-25 21:34 UTC, benjaminEwhite approved these changes

2024-06-26 03:19 UTC, njharman approved these changes

2024-06-26 15:11 UTC, nrh-cklimas commented on apps/common/tests/test_utils.py
> +    middleware = SessionMiddleware(get_response=(dummy := lambda request: request))
6b8569e67cf1b6b477bff8cab3c13e3db45e321e

2024-06-27 23:31 UTC, x110dc requested changes
A couple of questions about settings.

2024-06-27 23:31 UTC, x110dc commented on revengine/settings/deploy.py
> +            "bucket_name": os.getenv("GS_BUCKET_NAME"),
It looks like there was a default here (`rev-engine-media`) that was removed here. Are we certain this is defined in the environments where it's required?

2024-06-27 23:31 UTC, x110dc commented on revengine/settings/deploy.py
> -GS_MEDIA_LOCATION = "media"
I see why the other params are no longer necessary because they're specified inline, but will the removal of `GS_MEDIA_LOCATION` affect anything?

2024-06-28 19:45 UTC, nrh-cklimas commented on revengine/settings/deploy.py
> +            "bucket_name": os.getenv("GS_BUCKET_NAME"),
This is currently set in all envs, but I don't see much upside to removing the default. Updated in c79bef069849dd9cd6bdeeec9783a0b7f51ee129

2024-06-28 19:46 UTC, nrh-cklimas commented on revengine/settings/deploy.py
> -GS_MEDIA_LOCATION = "media"
I think this was an oversight on my part when I was translating settings to the new config structure. Added in in c79bef069849dd9cd6bdeeec9783a0b7f51ee129

2024-07-02 04:51 UTC, x110dc approved these changes
lgtm

2024-07-11 14:46 UTC, merged