DEV-4848: Implement Phone Number input
newsrevenuehub/rev-engine pull request #1546
Opened 2024-06-13 14:18 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
- Implements Phone Number input and add it to Contributor Portal Edit page
#### Why are we doing this? How does it help us?
- Improve the UX of adding a phone number
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
- Yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
- yes
#### Have automated unit tests been added? If not, why?
- yes
#### How should this change be communicated to end users?
- n/a
#### Are there any smells or added technical debt to note?
- no
#### Has this been documented? If so, where?
- no
#### What are the relevant tickets? Add a link to any relevant ones.
- https://news-revenue-hub.atlassian.net/browse/DEV-4848
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
- no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
- no

2024-06-13 17:05 UTC, nrh-cklimas requested changes

2024-06-13 17:11 UTC, nrh-cklimas commented on spa/src/components/base/TextField/PhoneTextField.test.tsx
> +describe('PhoneTextField', () => {
Test coverage says we should add tests around choosing a country from the flag menu.

2024-06-13 18:23 UTC, GuiMend commented on spa/src/components/base/TextField/PhoneTextField.tsx
> +  onChange?: (...event: any[]) => void;
I'm not sure I understand how this component would be used in 2 different forms. The prop onChange is only being used inside `usePhoneInput`
Btw, the TS for this `onChange` I got from `react-hook-form`.

2024-06-13 18:43 UTC, GuiMend commented on spa/src/components/base/TextField/PhoneTextField.test.tsx
> +describe('PhoneTextField', () => {
[e1b117d](https://github.com/newsrevenuehub/rev-engine/pull/1546/commits/e1b117d38f11467e5dd68f5e6434fc066cc3c0a9)

2024-06-13 18:43 UTC, GuiMend commented on spa/src/components/base/TextField/PhoneTextField.test.tsx
> +  it('calls onChange with default number', () => {
[e1b117d](https://github.com/newsrevenuehub/rev-engine/pull/1546/commits/e1b117d38f11467e5dd68f5e6434fc066cc3c0a9)

2024-06-13 18:43 UTC, GuiMend commented on spa/src/components/base/TextField/PhoneTextField.tsx
> -    forceDialCode: true,
[e1b117d](https://github.com/newsrevenuehub/rev-engine/pull/1546/commits/e1b117d38f11467e5dd68f5e6434fc066cc3c0a9)

2024-06-13 20:36 UTC, nrh-cklimas commented on spa/src/components/content/contributor-portal/ContributorPortal.tsx
> +  const onlyCountryCode = contact_phone.length > 0 && contact_phone.length < 6;
```suggestion
  const onlyCountryCode = /^\+\d+$/.test(contact_phone);
```

I might have this wrong, but I think this approach is a little more flexible.

2024-06-13 20:43 UTC, nrh-cklimas commented on spa/src/components/base/TextField/PhoneTextField.tsx
> +  onChange?: (...event: any[]) => void;
I think, but I'm not 100% sure, that there are two onChange possibilities here and they receive different arguments.

- onChange on the TextField component sends a React.ChangeEvent.
- onChange coming from usePhoneInput sends just the value.

There's [a MUI example](https://react-international-phone.vercel.app/docs/Advanced%20Usage/useWithUiLibs#material-ui-example) in react-international-phone's docs that shows this, though in this example it only has a single onChange prop, the one provided by the hook. It's possible we only need to use the onChange from the hook to capture all changes. I'd try it out and see.

2024-06-14 14:42 UTC, GuiMend commented on spa/src/components/content/contributor-portal/ContributorPortal.tsx
> +  const onlyCountryCode = contact_phone.length > 0 && contact_phone.length < 6;
This doesn't work @nrh-cklimas. `usePhoneInput` has 2 phone strings, `{ phone: string; inputValue: string }`
1. inputValue is the formatted one, +1 (555) 555555 (this is the one displayed in the input)
2. phone is unformatted, +1555555555 (this one is the actual value in `contact_phone`)

Your suggestion works with `inputValue`, but not with `phone` (which is what we use).

2024-06-14 14:46 UTC, GuiMend commented on spa/src/components/base/TextField/PhoneTextField.tsx
> +  onChange?: (...event: any[]) => void;
> onChange on the TextField component sends a React.ChangeEvent.

Yes, but this onChange is being used with `onChange={handlePhoneValueChange}` (we do not override this with the onChange prop)

> onChange coming from usePhoneInput sends just the value

The component prop, `onChange`, is used inside the `usePhoneInput` hook

> There's [a MUI example](https://react-international-phone.vercel.app/docs/Advanced%20Usage/useWithUiLibs#material-ui-example) in react-international-phone's docs that shows this, though in this example it only has a single onChange prop, the one provided by the hook. It's possible we only need to use the onChange from the hook to capture all changes. I'd try it out and see.

We are using in the same way as the example. Are you mistaken about something or am I not getting what you mean?

2024-06-14 17:23 UTC, nrh-cklimas commented on spa/src/components/base/TextField/PhoneTextField.tsx
> +  onChange?: (...event: any[]) => void;
Ah, I get it now. I think the typing on `onChange` should be `(value: string) => void` in this case.

2024-06-14 20:19 UTC, nrh-cklimas commented on spa/src/components/content/contributor-portal/ContributorPortal.tsx
> +  const onlyCountryCode = contact_phone.length > 0 && contact_phone.length < 6;
As discussed on Slack, I was seeing weird behavior with leftover data from the previous PR. I don't think that's going to be a problem here so resolving.

2024-06-17 16:14 UTC, GuiMend commented on spa/src/components/base/TextField/PhoneTextField.tsx
> +  onChange?: (...event: any[]) => void;
[89cd623](https://github.com/newsrevenuehub/rev-engine/pull/1546/commits/89cd623913a2e8ff0300ad6ddbc6a026089d9f13)

2024-06-17 18:03 UTC, nrh-cklimas approved these changes

2024-06-25 19:08 UTC, merged