[DRAFT] DEV-4706: Add payment history to recurring contribution resend receipt email
newsrevenuehub/rev-engine pull request #1552
Opened 2024-06-24 17:54 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2024-06-26 14:54 UTC, benjaminEwhite requested changes
Have some requests for changes. Also, noting that there were several failing tests at time of review.

2024-06-26 14:54 UTC, benjaminEwhite commented on apps/contributions/models.py
> +    def handle_thank_you_email(self, billing_history: list[Contribution.Billing] | None = None):
Seems strange to define this class on the Contribution class. I'd move it to module scope.

2024-06-26 14:54 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            return None
There should still be a billing history in case of one time contribution, no? It would have one payment object for successful payment and could have additional for refunds.

2024-06-26 14:54 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        payments: list[Payment] = self.payment_set.all()
This can just be referenced in place at line 588, no need to assign to var.

2024-06-26 14:54 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        contribution.handle_thank_you_email(billing_history)
Given this context, might make more sense to have `handle_thank_you_email` make call to `.get_billing_history` internally, rather than passing as param.

2024-06-26 14:54 UTC, benjaminEwhite commented on apps/emails/views.py
> +        ],
Should use `BillingHistory` typed dict here.

2024-06-26 14:54 UTC, benjaminEwhite commented on conftest.py
> +        )
Why create two refunded payments?  Should be one that is normal and one that's refund, no?

2024-06-26 15:01 UTC, benjaminEwhite commented on apps/emails/views.py
> +            },
Should use `BillingHistory` typed dict here.

2024-06-26 18:14 UTC, GuiMend commented on apps/contributions/views.py
> +        contribution.handle_thank_you_email(billing_history)
Ok. But I still need a flag to indicate if the billing history should show or not.

2024-06-26 18:20 UTC, GuiMend commented on conftest.py
> +        )
Sure, I'm not familiar with how the data should actually be. I was just creating a mock with refunded payment

2024-06-28 13:54 UTC, benjaminEwhite requested changes
Had some comments and requests.

2024-06-28 13:54 UTC, benjaminEwhite commented on apps/contributions/tests/test_models.py
> +        contribution.handle_thank_you_email(show_billing_history)
Better to be explicit here since tests serve as documentation:

```suggestion
        contribution.handle_thank_you_email(send_billing_history=show_billing_history)
```

2024-06-28 13:54 UTC, benjaminEwhite commented on apps/contributions/models.py
> +class BillingHistory(TypedDict):
Can we call this `BillingHistoryItem` or something similar since it refers to individual items that together comprise an entire billing history?

2024-06-28 13:54 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            }
Shouldn't this use the `BillingHistory` typed dict?

2024-06-28 13:54 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            if isinstance(payment, Payment)
This should be guaranteed by virtue of calling `.payment_set.all()`. That will be empty or else it will have instances of payments.

```suggestion
```

2024-06-28 13:54 UTC, benjaminEwhite commented on apps/contributions/tests/test_models.py
> +            }
Use the typed dict here too.

2024-06-28 13:54 UTC, benjaminEwhite commented on apps/contributions/models.py
> +                data["billing_history"] = self.get_billing_history()
I think i'd prefer to always send a billing history in the template, and introduce a `send_billing_history` flag for the templates.  This would guarantee referential integrity of  'billing_history' in the template.

2024-06-28 13:54 UTC, benjaminEwhite commented on apps/contributions/tests/test_models.py
> +            assert billing_history == []
As mentioned in earlier review, I think that one time contributions should still have a billing history. They will typically have a single payment,  and occasionally may have refunds.

2024-06-28 13:54 UTC, benjaminEwhite commented on apps/contributions/tests/test_models.py
> +            expected_data["billing_history"] = contribution.get_billing_history()
Given earlier comment, think this test should not have conditionality here around whether show billing history is true.

2024-06-28 13:54 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        contribution.handle_thank_you_email(contribution.interval != ContributionInterval.ONE_TIME.value)
```suggestion
        contribution.handle_thank_you_email(send_billing_history=contribution.interval != ContributionInterval.ONE_TIME.value)
```

2024-06-28 13:54 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        contribution.handle_thank_you_email(contribution.interval != ContributionInterval.ONE_TIME.value)
I still think we should be sending back billing history in case of one-time. See earlier comments.

2024-06-28 13:54 UTC, benjaminEwhite commented on apps/emails/templates/nrh-default-contribution-confirmation-email.html
> +  {% if billing_history %}
If going with my suggestion around having flag for `show_billing_history` and always sending billing history data even if we don't show in case of one-time, this would probably become (assuming we don't want to show a headers only table in case of show_billing_history being true and empty billing history being passed)

```
  {% if billing_history and show_billing_history %}
```

2024-06-28 13:54 UTC, benjaminEwhite commented on apps/contributions/tests/test_models.py
> +            assert billing_history == []
Still think we want to get back a billing history here and handle view-layer display conditionality elsewhere.

2024-07-01 14:08 UTC, benjaminEwhite requested changes
@GuiMend had one final (99% confident on that 😄 ) round of suggestions around the type hinting issue, DRYing up format amount, and using an Enum class to capture the statuses that BillingHistoryItem can have.

2024-07-01 14:08 UTC, benjaminEwhite commented on apps/contributions/models.py
> +    def format_amount(self, amount: int, symbol="$", code="USD") -> str:
Didn't notice this in previous reviews because the `formatted_amount` method didn't appear in diff here and only saw in VSCode.

I think it would make sense to change `format_amount` to a `@staticmethod` here.  

```
@staticmethod
def format_amount(amount: int, symbol="$", code="USD") -> str:
```


Then refactor `formatted_amount` so it uses `Contribution.format_amount`. 

```
    @property
    def formatted_amount(self) -> str:
        currency = self.get_currency_dict()
        return self.format_amount(self.amount, currency["symbol"], currency["code"])
```

This allows us to DRY this code up.

2024-07-01 19:15 UTC, benjaminEwhite requested changes
@GuiMend my apologies and thanks for your patience but another round (hopefully last) here.

- Think we need to back out of the enum change, but we can discuss reason why in Slack huddle.
- Added request to include `"show_billing_history": True` in preview email template so we can see the billing history there (FWIW, that's what led me to discover the problem with the enum for status).
- Question about if we actually need to import annotations from __future__

2024-07-01 19:15 UTC, benjaminEwhite commented on apps/emails/views.py
> +        "billing_history": [
Should add `show_billing_history: True` here so can see billing history in template preview.

2024-07-01 19:15 UTC, benjaminEwhite commented on apps/emails/tasks.py
> +# Needed for postponing evaluation of annotations (because of "if TYPE_CHECKING")
Is this actually needed? I was able to get type hints to work as expected with no complaints from VSCode wihtout doing import from future. But if you're finding it's required @GuiMend that's fine (and is what was recommended in the reddit post I shared).

2024-07-01 20:04 UTC, benjaminEwhite commented on apps/contributions/models.py
> +
Apologies, but after using email template preview locally, looks like this was bad advice. Problem is that payment_status won't be a string value, but an enum object if we take this approach, and we'd need to do item.PAID.value (for instance).

Instead we could consider doing 

```
# imports at top of module:

from typing import  Literal

...

PaymentStatus = Literal["Paid", "Refunded"]

class BillingHistoryItem(TypedDict):
    payment_date: datetime.datetime
    payment_amount: int
    payment_status: BillingHistoryItemStatus
```

That gets us typing, but doesn't solve for the issue of being consistent about statuses (i.e., the place i pointed out earlier that changed the capitalization).

Think might make most sense to just remove enum, not use literal here, and just make sure we're consistent with spelling.

2024-07-02 14:53 UTC, GuiMend commented on apps/contributions/models.py
> +
I like the Literal approach Ben. It doesn't enforce the correct string, but it shows an autocomplete that facilitates the correct usage.
![image](https://github.com/newsrevenuehub/rev-engine/assets/9381325/4325c5ef-1183-4208-871d-c2f3dfdb5faa)

2024-07-02 15:46 UTC, benjaminEwhite requested changes
@GuiMend looks like you might have forgotten to push up a commit? It's for the one-remaining open conversation (around show_payment_history).

2024-07-02 15:46 UTC, benjaminEwhite commented on apps/emails/views.py
> +        "billing_history": [
@GuiMend I see this acknowledged, but no change. Maybe you missed pushing up a commit?

2024-07-02 15:49 UTC, GuiMend commented on apps/emails/views.py
> +        "billing_history": [
It's in the above line, so your comment didn't get the `Outdated` flag
![image](https://github.com/newsrevenuehub/rev-engine/assets/9381325/bc8f3310-0d47-4f08-b5f2-efc34342b400)

2024-07-02 15:51 UTC, benjaminEwhite approved these changes

2024-07-03 15:12 UTC, merged