DEV-4868: Handle empty Billing History section in Portal
newsrevenuehub/rev-engine pull request #1572
Opened 2024-07-11 21:08 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
Handles when Billing History is empty in Portal
#### Why are we doing this? How does it help us?
Improves usability for donors that have active payments, but no payment history to understand what is going on
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
yes
#### Have automated unit tests been added? If not, why?
yes
#### How should this change be communicated to end users?
n/a
#### Are there any smells or added technical debt to note?
no
#### Has this been documented? If so, where?
no
#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-4868
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2024-07-22 13:29 UTC, nrh-cklimas requested changes

2024-07-22 13:29 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/BillingHistory.test.tsx
> +      usePortalMock.mockReturnValue({
Can this be moved into a `beforeEach()`?

2024-07-22 13:29 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/BillingHistory.tsx
> +                <TableCell>{dateFormatter.format(new Date(payment.created))}</TableCell>
DEV-5035 changes the logic of the date shown--we should possibly combine these two PRs, or keep an eye on this if 5035 merges first so that we don't accidentally revert the change.

2024-07-22 13:29 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/BillingHistory.tsx
> +            <TableRow>
If we can, it would be better to display this message instead of the table entirely. It'll make life easier for screen readers and also simplify the HTML.

2024-07-22 13:29 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/BillingHistory.tsx
> +                  Please contact {page?.revenue_program.name}
If `page` is undefined, we should show a spinner, or skip display to avoid a message like "Please contact for billing history and prior receipts for this contribution." I'm good with either option since this is mostly a theoretical concern today--but might not be if we change the portal design later.

2024-07-22 13:29 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/common.styled.ts
> +      cursor: not-allowed;
We should get Rachel's opinion on this, and if this is behavior we do want, it should be moved into the base component for consistency across the app.

2024-07-22 18:57 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/BillingHistory.test.tsx
> +      usePortalMock.mockReturnValue({
Actually, I can remove it from this test and only leave the one that needs a different state

2024-07-22 18:59 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/BillingHistory.tsx
> +                <TableCell>{dateFormatter.format(new Date(payment.created))}</TableCell>
I'll make this ticket blocked by 5035 so that I can fix any merge conflicts.

2024-07-22 19:02 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/BillingHistory.tsx
> +                  Please contact {page?.revenue_program.name}
We could display a fallback message. I'll talk to Rachel to see what's appropriate.

2024-07-22 19:09 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/BillingHistory.tsx
> +            <TableRow>
[d083be0](https://github.com/newsrevenuehub/rev-engine/pull/1572/commits/d083be0f5cfe14e24167692cb328c5b1f5f1109c)

2024-07-22 19:09 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/BillingHistory.test.tsx
> +      usePortalMock.mockReturnValue({
[d083be0](https://github.com/newsrevenuehub/rev-engine/pull/1572/commits/d083be0f5cfe14e24167692cb328c5b1f5f1109c)

2024-07-25 18:38 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/common.styled.ts
> +      cursor: not-allowed;
[a855503](https://github.com/newsrevenuehub/rev-engine/pull/1572/commits/a8555038e4c59e7daa17ddc830e64ec0d4cf559d)

2024-07-25 18:38 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/BillingHistory.tsx
> +                  Please contact {page?.revenue_program.name}
[a855503](https://github.com/newsrevenuehub/rev-engine/pull/1572/commits/a8555038e4c59e7daa17ddc830e64ec0d4cf559d)

2024-07-26 14:00 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/BillingHistory.tsx
> +                <TableCell>{dateFormatter.format(new Date(payment.created))}</TableCell>
FYI I merged 5035 this morning.

2024-07-26 18:22 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingHistory/BillingHistory.tsx
> +                <TableCell>{dateFormatter.format(new Date(payment.created))}</TableCell>
[ae82290](https://github.com/newsrevenuehub/rev-engine/pull/1572/commits/ae822908be5ae9b016828726e9433b1e0e8bfa54)

2024-07-26 19:35 UTC, nrh-cklimas approved these changes

2024-07-31 14:39 UTC, merged