DEV-4456: Launch New Portal for all users
newsrevenuehub/rev-engine pull request #1575
Opened 2024-07-15 22:29 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
- Launches new portal for all users
#### Why are we doing this? How does it help us?
- Launching new portal
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
- Yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
- Yes
#### Have automated unit tests been added? If not, why?
- Yes
#### How should this change be communicated to end users?
- New portal live
#### Are there any smells or added technical debt to note?
- no 
#### Has this been documented? If so, where?
- no
#### What are the relevant tickets? Add a link to any relevant ones.
- https://news-revenue-hub.atlassian.net/browse/DEV-4456
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
- no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
- no

2024-07-15 23:44 UTC, GuiMend commented on spa/cypress/e2e/08-contributor.cy.js
> +describe('New Portal', () => {
@nrh-cklimas, as the new portal changes a lot of things, do you think it's OK to remove the cypress tests that I deleted?

2024-07-16 14:15 UTC, nrh-cklimas requested changes

2024-07-16 14:15 UTC, nrh-cklimas commented on spa/src/utilities/getPageLinks.ts
> +  urlJoin(getRevenueProgramDomain(page.revenue_program), PORTAL.ENTRY.replaceAll('/', ''));
Why do we need the `replaceAll` here? I think we would want the trailing slash on the route, at first glance.

2024-07-16 15:34 UTC, GuiMend commented on spa/src/utilities/getPageLinks.ts
> +  urlJoin(getRevenueProgramDomain(page.revenue_program), PORTAL.ENTRY.replaceAll('/', ''));
I could have added just the `'portal'` text, but I wanted to use `PORTAL.ENTRY` so that it's easily searchable all the places we use `PORTAL.ENTRY`.

The replace all is here because PORTAL.ENTRY has `/portal/` as value and we need just `portal` for this.

2024-07-16 16:07 UTC, GuiMend commented on spa/src/components/PortalRouter.test.tsx
> +    it('track access at /contributor/contributions/', async () => {
[327b992](https://github.com/newsrevenuehub/rev-engine/pull/1575/commits/327b99283f1838bec474f480351170e3e7d7f4b8)

2024-07-16 16:07 UTC, GuiMend commented on spa/cypress/e2e/08-contributor.cy.js
> +      cy.get('button').click();
[327b992](https://github.com/newsrevenuehub/rev-engine/pull/1575/commits/327b99283f1838bec474f480351170e3e7d7f4b8)

2024-07-16 16:08 UTC, GuiMend commented on spa/src/components/ContributorRouter.tsx
[327b992](https://github.com/newsrevenuehub/rev-engine/pull/1575/commits/327b99283f1838bec474f480351170e3e7d7f4b8)

2024-07-16 16:08 UTC, GuiMend commented on spa/cypress/e2e/05-pageViewAnalytics.cy.js
> +  HUB_TRACKED_PAGES_REQUIRING_NO_LOGIN.forEach((page) => {
[327b992](https://github.com/newsrevenuehub/rev-engine/pull/1575/commits/327b99283f1838bec474f480351170e3e7d7f4b8)

2024-07-16 16:08 UTC, GuiMend commented on spa/src/components/PortalRouter.tsx
> +      {/* Legacy Contributor Portal - Adds redirects to new Portal */}
[327b992](https://github.com/newsrevenuehub/rev-engine/pull/1575/commits/327b99283f1838bec474f480351170e3e7d7f4b8)

2024-07-16 18:35 UTC, nrh-cklimas commented on spa/cypress/e2e/05-pageViewAnalytics.cy.js
> +  HUB_TRACKED_PAGES_REQUIRING_NO_LOGIN.forEach((page) => {
I'm sorry, I'm still seeing this as a foreach.

2024-07-16 19:19 UTC, guilhermegoes-sunrun commented on spa/src/utilities/getPageLinks.ts
> +  urlJoin(getRevenueProgramDomain(page.revenue_program), PORTAL.ENTRY.replaceAll('/', ''));
[9ea4449](https://github.com/newsrevenuehub/rev-engine/pull/1575/commits/9ea4449cf6c91e798ed59d6ce024250ef0f077fa)

2024-07-16 19:19 UTC, guilhermegoes-sunrun commented on spa/cypress/e2e/05-pageViewAnalytics.cy.js
> +  HUB_TRACKED_PAGES_REQUIRING_NO_LOGIN.forEach((page) => {
[9ea4449](https://github.com/newsrevenuehub/rev-engine/pull/1575/commits/9ea4449cf6c91e798ed59d6ce024250ef0f077fa)

2024-07-16 19:21 UTC, GuiMend commented on spa/src/utilities/getPageLinks.ts
> +  urlJoin(getRevenueProgramDomain(page.revenue_program), PORTAL.ENTRY.replaceAll('/', ''));
[9ea4449](https://github.com/newsrevenuehub/rev-engine/pull/1575/commits/9ea4449cf6c91e798ed59d6ce024250ef0f077fa)

2024-07-16 19:21 UTC, GuiMend commented on spa/cypress/e2e/05-pageViewAnalytics.cy.js
> +  HUB_TRACKED_PAGES_REQUIRING_NO_LOGIN.forEach((page) => {
[9ea4449](https://github.com/newsrevenuehub/rev-engine/pull/1575/commits/9ea4449cf6c91e798ed59d6ce024250ef0f077fa)

2024-07-16 19:40 UTC, nrh-cklimas approved these changes

2024-07-17 13:30 UTC, merged