DEV-4814: Add PATCH endpoint for contribution to change amount
newsrevenuehub/rev-engine pull request #1582
Opened 2024-07-25 18:19 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
- Enables changes to contribution amount with PATCH
- Modifies Stripe's Subscription amount to reflect new value

#### Why are we doing this? How does it help us?
- Enable user to change donation amount
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
- n/a. I don't think it's testable without the FE.
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
- no
#### Have automated unit tests been added? If not, why?
- yes
#### How should this change be communicated to end users?
- n/a
#### Are there any smells or added technical debt to note?
- no
#### Has this been documented? If so, where?
- no
#### What are the relevant tickets? Add a link to any relevant ones.
- https://news-revenue-hub.atlassian.net/browse/DEV-4814
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
- no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
https://news-revenue-hub.atlassian.net/browse/DEV-5005

2024-07-29 13:42 UTC, benjaminEwhite requested changes
Left some comments and requests.

Additionally, I think we should have a test that shows amount update behavior via API layer, not only via model layer. In particular, we should show that if you send an amount of `1` in patch request, that ends up as `100` in the contribution.amount.

2024-07-29 13:42 UTC, benjaminEwhite commented on README.md
> +Obs 2: You will probably need to add `"https://*.stripe.com/"` to `CSRF_TRUSTED_ORIGINS` list
I searched for this in repo, and only place it comes up is README.md. So i guess would need to add `CSRF_TRUSTED_ORGINS` to local settings.

2024-07-29 13:42 UTC, benjaminEwhite commented on apps/contributions/models.py
> +
It's possible for the NRE contribution status to be out of sync with the Stripe subscription status.  I think we probably want to be looking at the Stripe sub statu to be safe.

2024-07-29 13:42 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            raise ValueError("Cannot update amount for inactive subscription")
In line with earlier comment, I think we should be checking the underlying Stripe subscription's status here.

2024-07-29 13:42 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    amount = serializers.IntegerField(required=False)
Probably this is the place to do the validation around minimum amount.

2024-07-29 13:42 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +                )
This block is not tested.

2024-07-29 13:42 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            raise ValueError("Subscription should have only one item")
This path is not tested.

2024-07-30 01:23 UTC, GuiMend commented on README.md
> +Obs 2: You will probably need to add `"https://*.stripe.com/"` to `CSRF_TRUSTED_ORIGINS` list
Yes, this is added to our `local.py`. I updated `local.example.py` with this

2024-07-30 13:22 UTC, nrh-cklimas commented on apps/contributions/models.py
> +            stripe.Subscription.modify(
@x110dc should sign off on this, but my opinion is that the backend should use the amount as it's provided by the SPA, same as what we do with initial contributions. This will be more an issue when we do the SPA side of this, as we'd (probably) want the new amount to reflect the existing fee setting. Changing pay fees/don't pay fees is also a separate story.

2024-08-01 21:53 UTC, njharman requested changes

2024-08-01 21:53 UTC, njharman commented on apps/contributions/models.py
> +        metadata["donor_selected_amount"] = amount
Is assigning to `metadata `an attempt to not modify self.contribution_metadata. But assignment creates a "reference", not a copy. [it also appears no as changes to `contribution_metadata `are saved below]. Is also not saving "space" as metadata is not used often, once I believe.

Unnecessary, confusing, and adds another entry in namespace to keep track of/cause errors/etc.

`self.contribution_metadata["donor_selected_amount"] = amount`

2024-08-01 21:53 UTC, njharman commented on apps/contributions/models.py
> +                "Encountered a Stripe error while trying to update payment method for subscription on contribution %s",
Would it be useful to log more data, amount, other parameters to `stripe.Subscription.modify()`?

I believe Sentry will capture all the locals(). So, maybe redundant?

2024-08-01 21:53 UTC, njharman commented on apps/contributions/models.py
> +        if amount < 100:
REVENGINE_MIN_AMOUNT inplace of literal `100`?

2024-08-01 21:53 UTC, njharman commented on apps/contributions/models.py
> +            raise ValueError("Subscription should have only one item")
It is now.

2024-08-01 21:53 UTC, njharman commented on apps/contributions/models.py
> +        without proration (paying difference of existing month).
Does Stripe just handle making it the "next payment" for all three; billing_date is before today, today and after today?

2024-08-01 21:53 UTC, njharman commented on apps/contributions/models.py
> +        if amount < 100:
The serializer validates amount is between REVENGINE_MIN_AMOUNT and STRIPE_MAX_AMOUNT. Should we not do same here?

2024-08-02 13:54 UTC, GuiMend commented on apps/contributions/models.py
> +
Actually @njharman , I'd like to confirm these statuses as I don't know what indicates an "active" subscription. Would you know? I read the documentation and assumed these were the statuses that seemed inactive / amount updates didn't make sense. (But it's my opinion)

These are the available options:
![image](https://github.com/user-attachments/assets/84f6fabe-55a9-434b-8c30-05833a5644ff)

2024-08-02 13:57 UTC, GuiMend commented on apps/contributions/models.py
> +        metadata["donor_selected_amount"] = amount
I did this because in line `1232` I assigned the metadata in the Stripe subscription payload:
```python
...
metadata=metadata,
stripe_account=self.stripe_account_id,
proration_behavior="none",
```

Would you prefer that I did this instead?
```python
self.contribution_metadata["donor_selected_amount"] = amount

# and later
metadata= self.contribution_metadata
```

2024-08-02 14:01 UTC, GuiMend commented on apps/contributions/models.py
> +                "Encountered a Stripe error while trying to update payment method for subscription on contribution %s",
I'm not sure @njharman , but in other places that we log stripe.Subscription.modify errors, it's in the same format as this one.

2024-08-02 14:06 UTC, GuiMend commented on apps/contributions/models.py
> +        without proration (paying difference of existing month).
Yes. Stripe will make the next payment with the updated amount.

2024-08-02 17:39 UTC, njharman requested changes

2024-08-02 17:39 UTC, njharman commented on apps/contributions/models.py
> +        metadata["donor_selected_amount"] = amount
Yes. It's minor.

Each time is minor, but (in reviews and when coding) I'm always looking to reduce name space "pollution", vertical space and the "vertical distance" something has to be remembered.

The more things in namespace (assignments to local variables, from x import y, etc)

- The more chances there are for bugs; typos, name collisions 
- The more items that need to be kept in ones head when understanding and refactoring code (this is also main reason for less vertical distance, such as code blocks that are ~ one screenful and assigning things close to were they are used.

2024-08-02 17:39 UTC, njharman commented on apps/contributions/models.py
> +
Oh, opinions are dangerous ;) 

I also only have an opinion. Really should have been defined in AC. Should ask whoever wrote the AC to add clarification (to AC) what inactive means. Probably @ them what you posted above in a comment on this ticket. [ticket comments are more visible and permanent than PR ones]

If you don't know who to ask, ping DC.

2024-08-02 17:39 UTC, njharman commented on apps/contributions/models.py
> +            stripe.Subscription.modify(
@x110dc eh?

2024-08-05 13:39 UTC, GuiMend commented on apps/contributions/models.py
> +
Added a comment there @njharman. Thanks

2024-08-07 03:53 UTC, x110dc commented on apps/contributions/models.py
> +            stripe.Subscription.modify(
Yes, I agree that it should be consistent with the way it happens with the initial contribution.

2024-08-07 20:59 UTC, GuiMend commented on apps/contributions/models.py
> +            stripe.Subscription.modify(
This means that BE stays the way it is now, and we will address this in the FE.

2024-08-07 20:59 UTC, GuiMend commented on apps/contributions/models.py
> +
Daniel confirmed in JIRA that the only active status is the one with value `active`, all the others are considered `inactive`

2024-08-07 23:10 UTC, njharman requested changes
build failing

2024-08-08 21:32 UTC, njharman approved these changes

2024-08-12 18:46 UTC, nrh-cklimas approved these changes

2024-08-22 17:59 UTC, merged