DEV-5037 | Short term fix for excluding duplicated recurring contributions
newsrevenuehub/rev-engine pull request #1584
Opened 2024-07-26 20:49 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

This PR makes a small code change to exclude contributions from portal where both of following are true:

- recurring
- missing provider_subscription_id

For a lengthy explanation of reasoning behind this, [please see this comment in JIRA](https://news-revenue-hub.atlassian.net/browse/DEV-5037?focusedCommentId=120074)

#### Why are we doing this? How does it help us?

Unblocks portal release and removes potentially confusing data from portal.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

Yes.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

N/A

#### Have automated unit tests been added? If not, why?

Yes

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

No

#### What are the relevant tickets? Add a link to any relevant ones.

- [DEV-5037](https://news-revenue-hub.atlassian.net/browse/DEV-5037)
- [DEV-5059](https://news-revenue-hub.atlassian.net/browse/DEV-5059)
- [DEV-5062](https://news-revenue-hub.atlassian.net/browse/DEV-5062)

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

- [DEV-5059](https://news-revenue-hub.atlassian.net/browse/DEV-5059)
- [DEV-5062](https://news-revenue-hub.atlassian.net/browse/DEV-5062)

2024-07-26 21:21 UTC, nrh-cklimas requested changes

2024-07-26 21:21 UTC, nrh-cklimas commented on apps/contributions/tests/test_models.py
> +    def test_exclude_recurring_missing_provider_subscription_id(self, mocker):
I think I don't totally get the intent of this. My reading of it as written is "exclude_recurring_missing_provider_subscription_id doesn't exclude things it shouldn't". Should we add tests around contributions that would be excluded, though?

2024-07-26 21:21 UTC, nrh-cklimas commented on apps/contributions/views.py
> +        return (
Think `test_get_contributor_queryset` should be updated to test that this new method is called.

2024-07-26 22:24 UTC, benjaminEwhite commented on apps/contributions/tests/test_models.py
> +    def test_exclude_recurring_missing_provider_subscription_id(self, mocker):
@nrh-cklimas 

```
ContributionFactory(provider_subscription_id=None, monthly_subscription=True, status=ContributionStatus.PAID)
```

That creates a contribution that ends up excluded because it's missing `provider_subscription_id`. There's no need to assign it to a var because there's nothing to assert about it.

2024-07-26 22:27 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        return (
Good catch.

69e95ea35

2024-07-29 16:49 UTC, x110dc approved these changes

2024-07-31 14:43 UTC, merged