DEV-5059: Add first_payment_date method to Contribution model
newsrevenuehub/rev-engine pull request #1586
Opened 2024-07-29 20:16 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

- Adds a `first_payment_date` field to the Contribution model. It is required to have a value.
- Populates this field with `created` during the initial migration.
- Overrides the `save` method to set this field to `created` when an object is initially created.

#### Why are we doing this? How does it help us?

Allows us to show correct dates for backfilled contributions in the contributor portal.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

Yes.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No.

#### Have automated unit tests been added? If not, why?

Yes.

#### How should this change be communicated to end users?

n/a

#### Are there any smells or added technical debt to note?

I am unsure about testing around the save() override. It would be nice to assert that `super().save()` is getting called correctly by it, but not sure how to go about it.

#### Has this been documented? If so, where?

No.

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-5059

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

- https://news-revenue-hub.atlassian.net/browse/DEV-5064
- https://news-revenue-hub.atlassian.net/browse/DEV-5065

2024-08-01 22:26 UTC, njharman requested changes

2024-08-01 22:26 UTC, njharman commented on apps/contributions/migrations/0012_DEV_5059_contribution_first_payment_date.py
> +        contribution.save()
I'm triggered by loop over all rows with DB save.

Recommend some method of bulk update; https://docs.djangoproject.com/en/5.0/ref/models/querysets/#bulk-update

2024-08-01 22:26 UTC, njharman commented on apps/contributions/tests/test_models.py
> +        assert contribution.first_payment_date == contribution.created
This is testing ContributionFactory more than Contribution. If ContributionFactory now (or is changed in future) to set first_payment_date it's prone to false positive.  Contribution it self may not set default.

Also, should not first_payment_date be added to ContributionFactory?

2024-08-01 22:26 UTC, njharman commented on apps/contributions/migrations/0012_DEV_5059_contribution_first_payment_date.py
> +        migrations.AlterField(
Consider constraint that first_payment_date must be >= created?

2024-08-01 22:26 UTC, njharman commented on apps/contributions/models.py
> +        super().save(*args, **kwargs)
I'm surprised this works. I didn't think self.created got set until after save(). It also won't catch if first_payment_date passed in kwargs.

I would like to see the following model tests on existing Contribution, and new Contribution() [not ContributionFactory, see below]

1. save()
2. save(first_payment_date=None)

btw, I believe agood way to cover kwargs case is [setdefault](https://docs.python.org/2/library/stdtypes.html#dict.setdefault).
```
def save(self, *args, **kwargs):
    kwargs.setdefault("first_payment_date", self.created)
    super().save(*args, **kwargs)
```

2024-08-02 14:19 UTC, nrh-cklimas commented on apps/contributions/migrations/0012_DEV_5059_contribution_first_payment_date.py
> +        contribution.save()
Makes sense-- 2b07a7daf3dbc82239e52064f37f625177eb2178

2024-08-02 14:20 UTC, nrh-cklimas commented on apps/contributions/tests/test_models.py
> +        assert contribution.first_payment_date == contribution.created
Is the fix here to create a `Contribution()` directly and assert on that?

2024-08-02 14:30 UTC, nrh-cklimas commented on apps/contributions/migrations/0012_DEV_5059_contribution_first_payment_date.py
> +        migrations.AlterField(
Added in c812529b717a136594b097d83ea9b1174f1c212a, but double-check my work--I did this all by hand and haven't done that before.

2024-08-02 14:32 UTC, nrh-cklimas commented on apps/contributions/models.py
> +        super().save(*args, **kwargs)
I don't love this approach either and am open to doing it in a better way if you have a suggestion. I was looking at [Django docs that suggested preferring this override to using a signal](https://docs.djangoproject.com/en/5.0/ref/signals/#module-django.db.models.signals) but it felt like there has to be a better way here. If not, can do the suggestions you had here.

2024-08-02 16:14 UTC, njharman requested changes

2024-08-02 16:14 UTC, njharman commented on apps/contributions/models.py
> +        super().save(*args, **kwargs)
Believe doing it in save() is fine. Mostly interested in tests to verify it works way we think it does (and to proof against future changes breaking it).

2024-08-02 16:14 UTC, njharman commented on apps/contributions/tests/test_models.py
> +        assert contribution.first_payment_date == contribution.created
yes.

2024-08-02 16:14 UTC, njharman commented on apps/contributions/migrations/0012_DEV_5059_contribution_first_payment_date.py
> +    Contribution.objects.bulk_update(all_contributions, ["first_payment_date"])
depending how many rows in production, batch_size is probably appropriate. batch_size = 1,000 or 2,000

2024-08-02 17:59 UTC, nrh-cklimas commented on apps/contributions/migrations/0012_DEV_5059_contribution_first_payment_date.py
> +        migrations.AlterField(
@njharman realized in the stacked PR we can't do a constraint on the field because `created` will be after the first payment occurred for migrated contributions. e.g. We are creating contributions today that correspond to contributions that occurred in legacy last year. I backed this out in 70ee13f31bc78757badb7a04411cd4227b7d527b

2024-08-02 18:56 UTC, nrh-cklimas commented on apps/contributions/tests/test_models.py
> +        assert contribution.first_payment_date == contribution.created
I'm trying this approach but the assert fails if I don't save the instance, which makes sense given the implementation approach. However, if I do try to save it, it complains about a lot of validation errors... and to fix that, it feels like I would have to essentially re-implement ContributionFactory.

What if we do it like this?

```python
    def test_first_billing_date_defaults_to_created(self):
        contribution = ContributionFactory(first_payment_date=None)
        assert contribution.first_payment_date == contribution.created
```

2024-08-02 18:58 UTC, nrh-cklimas commented on apps/contributions/migrations/0012_DEV_5059_contribution_first_payment_date.py
> +    Contribution.objects.bulk_update(all_contributions, ["first_payment_date"])
:+1: 8b1634236c6724d2c32c8fb655327f4b138cfd88

2024-08-02 19:11 UTC, nrh-cklimas commented on apps/contributions/models.py
> +        super().save(*args, **kwargs)
If I try the code snippet you suggested, I get this error in tests:
```
TypeError: Model.save() got an unexpected keyword argument 'first_payment_date'
```

I think this is because [save() doesn't let you set model fields](https://docs.djangoproject.com/en/5.0/ref/models/instances/#saving-objects) in the call? I might have this totally wrong.

2024-08-04 19:45 UTC, njharman commented on apps/contributions/migrations/0012_DEV_5059_contribution_first_payment_date.py
> +        migrations.AlterField(
>  created will be after the first payment occurred for migrated contributions. 

Well, that seems like should set created on migration. But investigating what that'll break is way out of scope so 

+!

2024-08-04 20:00 UTC, njharman commented on apps/contributions/models.py
> +        super().save(*args, **kwargs)
No. I'm wrong... I think I've made same wrong assumption before (the *args, **kwargs) meaning it optionally takes fields.

Sorry for wasting your time.  my #2 test case above is N/A. #1 is discussed elsewhere.

2024-08-04 20:29 UTC, njharman commented on apps/contributions/tests/test_models.py
> +        assert contribution.first_payment_date == contribution.created
The worry I have is that by using ContributionFactory, we are testing **test code** and not **production code**.  Factory would be and is fine when we just need a Contribution to test something else. But this test, is testing that Contributions are created correctly, not that ContributionFactory returns correct Contribution.

As a contrived example; could delete you're changes to def save()  and add to ContributionFactory [I forget the exact faker syntax, but it's something like...]` first_payment_date = lazyAttribute(lambda o: o.created)`. You're obviously not gonna do that now. But future edits of `def save()` / other code might unintentionally break it in similar way where test won't fail, but production code would.

You have to decide if you think that risk large enough to justify test effort. As reviewer, I'd not disagree if you decided it was. 

How are Contributions instantiated in production? I gave up trying to figure out by looking at code.  At some point something must be calling Contribution(). But there might be some higher level function analogous to ContributionFactory(). If all production calls to Contribution() are via that "factory"; could use that production factory for test (the assumption being that would handle all the validation errors).

2024-08-13 17:21 UTC, njharman approved these changes

2024-08-14 17:40 UTC, joelfkehub commented on apps/contributions/models.py
> +    first_payment_date = models.DateTimeField(null=False, default=timezone.now)
My training/experience tells me to never, ever store datetime info in anything but UTC.  Is that not "de rigeur" anymore?  I guess if we know the timezone that applies, we can still do comparisons and whatnot, but the potential of having to do careful conversions within a query to make comparisons and/or filtrations frightens me.  Am I overblowing the issue?

2024-08-14 17:58 UTC, njharman commented on apps/contributions/models.py
> +    first_payment_date = models.DateTimeField(null=False, default=timezone.now)
[just happened to notice this comment]

UTC never goes out of style ;)

Good catch.  django.timezone.now() https://docs.djangoproject.com/en/5.1/ref/utils/#django.utils.timezone.now appears to return naive or UTC depending on setting of [USE_TZ](https://docs.djangoproject.com/en/5.1/ref/settings/#std-setting-USE_TZ)

I'm reasonably sure Postgress will interpret naive as UTC. But I don't like that expected behavior can flip based on setting. Assuming my interpretation is correct. Maybe use some now() function that always returns aware UTC datetime.

2024-08-14 18:05 UTC, joelfkehub commented on apps/contributions/tests/test_views.py
> +            set(contributor.contribution_set.values_list("donation_page__revenue_program", flat=True).distinct())
Also, if we make sure distinct is working properly at the database, we should not need to convert the results to `set`.

2024-08-14 18:10 UTC, joelfkehub requested changes
Two comments/questions.  See conversations!

2024-08-14 18:26 UTC, joelfkehub commented on apps/contributions/tests/test_views.py
> +            set(contributor.contribution_set.values_list("donation_page__revenue_program", flat=True).distinct())
I just noticed this is in the context of a test, so not as important, and unlikely to produce positive results given the likely scale of the test data.

2024-08-14 18:27 UTC, nrh-cklimas commented on apps/contributions/tests/test_views.py
> +            set(contributor.contribution_set.values_list("donation_page__revenue_program", flat=True).distinct())
My gut says that this would be a premature optimization because this test is using a Pytest fixture (`portal_contributor_with_multiple_contributions_over_multiple_rps`) that has only three contributions ([definition](https://github.com/newsrevenuehub/rev-engine/blob/f1682fec9b487c6ad2b5d5decfd4b58d8bd4b8e5/apps/contributions/tests/test_views.py#L1573), [fixture that it's based on](https://github.com/newsrevenuehub/rev-engine/blob/f1682fec9b487c6ad2b5d5decfd4b58d8bd4b8e5/apps/contributions/tests/test_views.py#L1534)). But if you feel strongly about it, can look at writing this in a way that makes this fact clearer.

2024-08-14 18:36 UTC, joelfkehub commented on apps/contributions/tests/test_views.py
> +            set(contributor.contribution_set.values_list("donation_page__revenue_program", flat=True).distinct())
If tests are documentation, and even sometimes a guide as to how one might "do things" elsewhere in the code, then I vote we change line 1658 above to this:
`contributor.contribution_set.order_by().values_list("donation_page__revenue_program", flat=True).distinct())`

That would satisfy me.

2024-08-14 18:39 UTC, joelfkehub commented on apps/contributions/models.py
> +    first_payment_date = models.DateTimeField(null=False, default=timezone.now)
I'll do some quick reading of the relevant documentation and of DEV-2329 and then go create that ticket.

We can resolve this convo based on Chris's suggestion to address this in a different changeset.

2024-08-14 18:46 UTC, joelfkehub commented on apps/contributions/tests/test_views.py
> +            set(contributor.contribution_set.values_list("donation_page__revenue_program", flat=True).distinct())
Meh.  Norm is right.  Juice, squeeze, not worth it.

2024-08-14 18:49 UTC, joelfkehub approved these changes
As discussed, we'll open another tech debt ticket to address the timezone-switch-based-on-settings issue (which is both minor and out of scope).

And, I've "stood down" on my critique of Contribution query structure within the tests given that we're filtering over a very small number of items in that test.   Address it for bonus points, if you like.

So, Approved!

2024-08-15 04:03 UTC, x110dc approved these changes
lgtm

2024-08-15 19:41 UTC, merged