DEV-5064 | Backfill contribution first billing date for imported contributions
newsrevenuehub/rev-engine pull request #1588
Opened 2024-07-30 18:25 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2024-07-30 21:28 UTC, benjaminEwhite commented on apps/contributions/management/commands/fix_dev_5064.py
> +        Revelancy criteria:
```suggestion
        Relevancy criteria:
```

2024-08-01 23:02 UTC, njharman requested changes

2024-08-01 23:02 UTC, njharman commented on apps/contributions/management/commands/fix_dev_5064.py
> +            importer.list_and_cache_payment_intents_with_metadata_version(
(my) coverage report complains these importer lines don't jump to function exit.  No idea what that means. Seems  false positive bug by pycoverage.

If this is not just happening in my dev env; suggest suppressing branch coverage checking on these two lines. Unless you understand what's it's complaining about.

2024-08-02 17:51 UTC, nrh-cklimas commented on apps/contributions/models.py
> +        # Cast object_id to integer if it's not already
Removed this comment in d4fb74c73a0c49b654b8b9148063b2e31d8c48de -- felt like they were equivalent.

2024-08-02 17:53 UTC, nrh-cklimas commented on apps/contributions/management/commands/fix_dev_5064.py
> +        self.stdout.write(self.style.HTTP_INFO("Retrieving contributions with relevant metadata or revision comment"))
Added in

2024-08-02 18:31 UTC, nrh-cklimas commented
@njharman I rebased on DEV-5059 and seem to have lost your suggestion about simplifying the returned value of `get_contributions()`, but it's here: 452277fe0639a1630ce551541a90aa77cd2beb63

2024-08-02 18:35 UTC, nrh-cklimas commented on apps/contributions/management/commands/fix_dev_5064.py
> +        if via_metadata_ids := relevant_via_metadata.values_list("id", flat=True):
I agree. 55fb9800b36ffefd15a45bcadd5cc546531a4b80

2024-08-02 18:35 UTC, nrh-cklimas commented on apps/contributions/management/commands/fix_dev_5064.py
> +        contributions = (relevant_via_metadata | relevant_via_revision_comment).with_stripe_account()
https://github.com/newsrevenuehub/rev-engine/commit/452277fe0639a1630ce551541a90aa77cd2beb63

2024-08-02 18:44 UTC, nrh-cklimas commented on apps/contributions/management/commands/fix_dev_5064.py
> +            importer.list_and_cache_payment_intents_with_metadata_version(
Googling suggested it was because the line was covered but the lambdas never got called. Feelings on this? I could write tests that assert that the lambdas prune to the fields we want, I guess...

2024-08-04 19:57 UTC, njharman commented on apps/contributions/management/commands/fix_dev_5064.py
> +            importer.list_and_cache_payment_intents_with_metadata_version(
I would `# pragma: no cover` with comment explaining why, the lambdas and so they aren't "covered"

My argument for not testing

1. It's annoyingly fiddly to test / low likelyhood of bug in these particular lambdas / low ROI
2. Testing that list_and_cache...() proper take prune_fn should be tested elsewhere (I might add these two lambdas as test cases to that)
3. [maybe rubber ducking myself into thinking we should test...] It depends if list_and_cache...()s are mocked out in handle_account() test, (now or in future).

2024-08-04 20:34 UTC, njharman approved these changes

2024-08-12 14:31 UTC, nrh-cklimas commented on apps/contributions/management/commands/fix_dev_5064.py
> +            importer.list_and_cache_payment_intents_with_metadata_version(
a914f0310d48d2fe4f4e332d779bed376c64b74f

2024-08-13 17:51 UTC, joelfkehub commented on apps/contributions/management/commands/backfill_first_payment_date.py
> +        account_ids = set(contributions.values_list("stripe_account", flat=True))
I don't have a good feel for how many account_ids we may end up with.  It might be more scalable to do a distinct query here, rather than load all results into memory at once by creating the set.  If we stick with a distinct query, we can rely on lazy evaluation in the for loop below.  Again, if we're dealing with a relatively small number of accounts, perhaps this is less important.

2024-08-13 20:53 UTC, joelfkehub approved these changes
Looks good!  I have a couple of nitpicky comments for your consideration but, depending on expected scale, they may not be worth the squeeze.

2024-08-13 21:12 UTC, nrh-cklimas commented on apps/contributions/management/commands/backfill_first_payment_date.py
> +        account_ids = set(contributions.values_list("stripe_account", flat=True))
I think the number of accounts is going to be somewhat sizable (likely hundreds).

Would this get at what you're suggesting?

```python
account_ids = contributions.values_list("stripe_account", flat=True).distinct()
```

2024-08-13 21:17 UTC, joelfkehub commented on apps/contributions/management/commands/backfill_first_payment_date.py
> +        account_ids = set(contributions.values_list("stripe_account", flat=True))
Yes.  That would do it.

2024-08-13 22:26 UTC, joelfkehub commented on apps/contributions/management/commands/backfill_first_payment_date.py
> +        account_ids = set(contributions.values_list("stripe_account", flat=True))
As we discussed, the default ordering on the Contribution model is fouling up our initial idea of using `distinct` instead of converting the queryset to a `set`.  I think we might be able to "turn off" default ordering by adding an order_by call with empty arguments to line 205, where create the contributions queryset.  So, I'm going to investigate whether this gets us what we want:  
```
        contributions = self.get_contributions().with_stripe_account().order_by().distinct()
        account_ids = contributions.values_list("stripe_account", flat=True)
```

2024-08-13 22:40 UTC, joelfkehub commented on apps/contributions/management/commands/backfill_first_payment_date.py
> +        account_ids = set(contributions.values_list("stripe_account", flat=True))
Since we're later filtering contributions by account_id, perhaps it will be better to explicitly order by stripe_account:
```
contributions = (
    self.get_contributions()
    .with_stripe_account()
    .order_by('stripe_account')
    .distinct('stripe_account')
)
account_ids = contributions.values_list("stripe_account", flat=True)
```

2024-08-14 10:17 UTC, joelfkehub commented on apps/contributions/management/commands/backfill_first_payment_date.py
> +        account_ids = set(contributions.values_list("stripe_account", flat=True))
The empty order_by clause will probably deserve a comment explaining that we're using it to "turn off" default ordering.

2024-08-14 13:31 UTC, nrh-cklimas commented on apps/contributions/models.py
> +        contribution_ids = list(map(int, contribution_ids))
7b576b7b8ce8f29a2096e7b1e46c57c728601179

2024-08-14 13:43 UTC, joelfkehub commented on apps/contributions/models.py
> +            versions_with_comment.annotate(integer_id=models.functions.Cast("object_id", models.IntegerField()))
Nice.

2024-08-14 13:47 UTC, joelfkehub commented on apps/contributions/management/commands/backfill_first_payment_date.py
> +        contributions = self.get_contributions().with_stripe_account()
Aha.  You have added the empty order_by clause in get_contributions.  good plan.

2024-08-14 13:50 UTC, joelfkehub approved these changes
The latest changes look good to me.  We're disabling default ordering in the get_contributions clause, allowing us to run distinct when we're fetching unique stripe_account_ids rather than creating a set in memory of the entire result set.  And, we're casting reversion object_ids at the db level rather than loading that whole queryset into memory and then passing all those values back in to the associated subquery.  Much improved.

2024-08-14 19:33 UTC, x110dc requested changes
Minor requests. I'll add one more comment to the ticket itself.

2024-08-14 19:33 UTC, x110dc commented on apps/contributions/management/commands/backfill_first_payment_date.py
> +import datetime
The name of the command here doesn't match the name in the PR description.

2024-08-14 19:33 UTC, x110dc commented on apps/contributions/management/commands/backfill_first_payment_date.py
> +            else:
Just style I suppose but I prefer seeing a `continue` here instead of the `else` so this whole clause is de-indented.

2024-08-14 20:06 UTC, nrh-cklimas commented on apps/contributions/management/commands/backfill_first_payment_date.py
> +import datetime
Updated in description.

2024-08-14 20:13 UTC, nrh-cklimas commented on apps/contributions/management/commands/backfill_first_payment_date.py
> +            else:
4b4215c8e070d0c7d71f7086992cda3e6385ca80

2024-08-14 20:13 UTC, nrh-cklimas commented on apps/contributions/stripe_import.py
> +        """Get and cache subsriptions with given metadata version for a given stripe account."""
4b4215c8e070d0c7d71f7086992cda3e6385ca80

2024-08-15 19:26 UTC, merged