DEV-5000: Add default value for contributor name in email templates
newsrevenuehub/rev-engine pull request #1593
Opened 2024-08-12 14:56 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
Adds default value for contributor name in email templates
#### Why are we doing this? How does it help us?
If the contributor name is undefined, we display "Dear contributor," instead of "Dear None,"
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
no
#### Have automated unit tests been added? If not, why?
yes
#### How should this change be communicated to end users?
The contributor name on the email now has a default value
#### Are there any smells or added technical debt to note?
no
#### Has this been documented? If so, where?
no
#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-5000
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2024-08-12 19:14 UTC, nrh-cklimas reviewed
This seems OK to me but I think this is a good opportunity to expand test coverage. I see two possibilities here:

1. We move the "if defined, contributor_name, if not, 'contributor' literal" logic into a method or property and add tests around that.
2. We add tests on the output of the other emails.

I like option 1 better because it's probably simpler to do :).

2024-08-21 13:10 UTC, nrh-cklimas commented on apps/emails/tasks.py
> +        timestamp=custom_timestamp or convert_to_timezone_formatted(contribution.created, "America/New_York"),
Could you talk through why this date formatting is done differently than when custom_timestamp is set in models.py:655? My naive take on this would be to make custom_timestamp a datetime value and only format it here so that it's always consistent.

2024-08-21 13:22 UTC, nrh-cklimas commented on apps/emails/tasks.py
>  def make_send_thank_you_email_data(
Consider renaming this since this is being used for other types of emails as well?

2024-08-21 13:34 UTC, GuiMend commented on apps/emails/tasks.py
> +        timestamp=custom_timestamp or convert_to_timezone_formatted(contribution.created, "America/New_York"),
I don't know the reason for the different formatting @nrh-cklimas, I left that part unchanged and only added the prop `custom_timestamp` to override the default `contribution.created` time so that this function is more generic

2024-08-21 13:37 UTC, GuiMend commented on apps/emails/tasks.py
>  def make_send_thank_you_email_data(
[b5b6ac2](https://github.com/newsrevenuehub/rev-engine/pull/1593/commits/b5b6ac2660982d4929530a44713e11dd499ae731)

2024-08-21 14:24 UTC, nrh-cklimas commented on apps/emails/tasks.py
> +        timestamp=custom_timestamp or convert_to_timezone_formatted(contribution.created, "America/New_York"),
I looked into the history and the reason for this distinction is that this method is used for upcoming charge reminders, and we specify only a date there for when the next charge will occur. This feels complex to untangle because the timestamp is serving multiple purposes (e.g. it mostly refers to when a contribution occurs, which makes sense to include a time). I'm OK with proceeding here but it feels like next time we touch this code, we try to re-organize it better.

2024-08-21 14:25 UTC, nrh-cklimas approved these changes

2024-08-21 23:51 UTC, njharman requested changes

2024-08-21 23:51 UTC, njharman commented on apps/emails/tasks.py
> +        timestamp=custom_timestamp or convert_to_timezone_formatted(contribution.created, "America/New_York"),
I suggest this be summarized into code comment

2024-08-21 23:51 UTC, njharman commented on apps/emails/tasks.py
> +        timestamp=custom_timestamp or convert_to_timezone_formatted(contribution.created, "America/New_York"),
Also, using TZ "America/New_York" deserves and explanatory comment. [Unless I'm missing something obvious]

2024-08-21 23:51 UTC, njharman commented on apps/emails/tasks.py
> +        ),
I don't know if it matters, but this is slightly different behavior than replaced code. This will always have key "default_contribution_page_url". Whereas previous code will only have key when default_page.page_url is truthy.

```
 if default_page := self.revenue_program.default_donation_page:
            data["default_contribution_page_url"] = default_page.page_url
```

2024-08-21 23:51 UTC, njharman commented on apps/emails/tasks.py
>          copyright_year=contribution.created.year,
Was this change from original intentional? If so, it probably should be documented in AC along with why.

`"copyright_year": datetime.datetime.now(datetime.timezone.utc).year,`

2024-08-21 23:51 UTC, njharman commented on apps/emails/tasks.py
> +        logger.error("[generate_email_data]: No Stripe customer id for contribution with id %s", contribution.id)
Unless this is a new standard. I don't think` [function_name]` should be included. Or, rather I do think it should be included via logging/sentry configuration. I get our two projects confused. But I belive at least one of them has logging configured to automatically include "where was this log statement from" information.

But I also don't think this needs to be changed back if it delays high priority ticket.

2024-08-22 14:35 UTC, GuiMend commented on apps/emails/tasks.py
> +        logger.error("[generate_email_data]: No Stripe customer id for contribution with id %s", contribution.id)
This is a pattern I saw in several places in rev-engine, so I think we can keep it this way for now @njharman .

2024-08-22 14:39 UTC, GuiMend commented on apps/emails/tasks.py
>          copyright_year=contribution.created.year,
This `"copyright_year": datetime.datetime.now(datetime.timezone.utc).year,` is only located in `preview_contribution_email_template` (so it's only visible for devs when previewing emails).

The code `copyright_year=contribution.created.year,` has been like this for at least 17 months. I don't believe it's a mistake

2024-08-22 14:41 UTC, GuiMend commented on apps/emails/tasks.py
> +        ),
Thanks for pointing that out, but it isn't a problem @njharman. 
It is currently used only in `recurring-contribution-canceled` email, and we render it conditional `{% if default_contribution_page_url %}` (so having the key exist as `None` won't affect the usage).

2024-08-22 14:49 UTC, GuiMend commented on apps/emails/tasks.py
> +        timestamp=custom_timestamp or convert_to_timezone_formatted(contribution.created, "America/New_York"),
I'm not sure about the reason for America/New_York timezone, but I added a comment with @nrh-cklimas' findings

2024-08-22 18:59 UTC, njharman approved these changes

2024-08-22 18:59 UTC, njharman commented on apps/emails/tasks.py
>          copyright_year=contribution.created.year,
Your explaination re: only visible for devs makes resolves issue. But...

I understood that you replaced this code  

https://github.com/newsrevenuehub/rev-engine/pull/1593/files#diff-80bc4fbf647c521d99e0b1e9e38a568c928ed7477e600e7bd110a8e9bc870ae1L671

line 671 has

`"copyright_year": datetime.datetime.now(datetime.timezone.utc).year,`

with calling the function in emails/tasks.py The actual line here might be old. Replacing the original code with this call on line 652 changes functionality.

2024-08-22 19:12 UTC, GuiMend commented on apps/emails/tasks.py
>          copyright_year=contribution.created.year,
Oh, right, that's a good point. I'd like to ask @benjaminEwhite for this.

Ben, do you think we can always use `copyright_year` as the current year instead of `contribution.created`?
Or do we need both cases? If we do, I'll update the function to also accept a `copyright_year` override.

2024-08-23 13:39 UTC, benjaminEwhite commented on apps/emails/tasks.py
> +        contributor_name=customer.name or "contributor",
"contributor" gets hard coded in two places in this file. better off to define as constant at top of module and refer to by var name.

2024-08-23 13:40 UTC, benjaminEwhite commented on apps/emails/tasks.py
> +def generate_email_data(
Also, would be nice to have a docstring.

2024-08-23 13:42 UTC, benjaminEwhite commented on apps/emails/tasks.py
>          copyright_year=contribution.created.year,
@GuiMend I don't have a strong opinion on what is right source for copyright year. I think that's ultimately a product question (do we always have current year as copyright, or is it the year at time of contribution). Personally, I'd lean to defaulting to current year, but again, that's a product/design question more than anything else.

2024-08-23 15:09 UTC, GuiMend commented on apps/contributions/views.py
> +            contribution: Contribution = self.get_contributor_queryset(contributor).get(pk=contribution_id)
I think there is a slight improvement, as it makes the function "findable" and "clickable".
<img width="534" alt="image" src="https://github.com/user-attachments/assets/38c579b8-b779-4fd5-834c-5efca975c558">

You can also see the documentation of the function:
<img width="916" alt="image" src="https://github.com/user-attachments/assets/2c0cd40f-fa90-415d-be51-78519a9af264">

2024-08-23 15:11 UTC, GuiMend commented on apps/emails/tasks.py
> +def generate_email_data(
We do have it here: 
<img width="591" alt="image" src="https://github.com/user-attachments/assets/67ed3bb2-95ee-4d5c-bd5d-ba134b263967">

Or do you mean something different?

2024-08-23 15:17 UTC, GuiMend commented on apps/emails/tasks.py
> +        # We are not formatting the "custom_timestamp" in "convert_to_timezone_formatted"
This is the context @benjaminEwhite: https://github.com/newsrevenuehub/rev-engine/pull/1593#discussion_r1725028823

Let me know if you still think I need to change anything.

2024-08-23 16:08 UTC, GuiMend commented on apps/emails/tasks.py
>          copyright_year=contribution.created.year,
Confirmed with Sophie and Rachel: `It should always be current year, consistent with all our emails`

2024-08-26 10:18 UTC, benjaminEwhite approved these changes

2024-08-26 17:00 UTC, x110dc requested changes
One question. But I think we also need to revise the "what does this ticket so" section of the PR description. Because it looks like this ticket could've been accomplished with a 3-line change (adding the constant for contributor and then using it in two places). So some refactoring has been done. Please explain that in the PR description.

2024-08-26 17:51 UTC, GuiMend commented on apps/emails/tasks.py
> +        timestamp=custom_timestamp or convert_to_timezone_formatted(contribution.created, "America/New_York"),
Yes, [DEV-5170](https://news-revenue-hub.atlassian.net/browse/DEV-5170)

2024-08-26 20:27 UTC, merged