DEV-5162: Sort contributions in list by first_payment_date
newsrevenuehub/rev-engine pull request #1611
Opened 2024-08-29 14:42 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

Creating review app for testing

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2024-08-29 15:30 UTC, GuiMend approved these changes

2024-09-05 16:29 UTC, benjaminEwhite requested changes

2024-09-05 16:29 UTC, benjaminEwhite commented on apps/contributions/tests/test_models.py
> +
```suggestion
    def test_with_first_payment_date_when_no_payments(self, one_time_contribution):
        contributions = Contribution.objects.with_first_payment_date()
        assert contributions.count() == 1
        assert contributions.first().first_payment_date is None
```

Also, might be good to have an initial assertion that the contribution has no payments.

2024-09-05 16:29 UTC, benjaminEwhite commented on apps/contributions/tests/test_models.py
> +        assert contributions[0].first_payment_date == first_payment.transaction_time
Can get away with not defining var `first_payment` and also add exclude to ensure that we don't include any payments missing transaction time since that field is nullable.

```suggestion
        contributions = Contribution.objects.with_first_payment_date()
        assert contributions.count() == 1
        assert (con:=contributions.first()).first_payment_date == con.payment_set.exclude(transaction_time__isnull=True).order_by("transaction_time").first().transaction_time
```

2024-09-05 17:59 UTC, nrh-cklimas commented on apps/contributions/tests/test_models.py
> +
👍 6e903fec3082f59f7f165f3436cd0c7c1aa6a7cb

2024-09-05 18:29 UTC, benjaminEwhite approved these changes

2024-09-05 18:29 UTC, benjaminEwhite commented on apps/contributions/tests/test_models.py
> +        assert Payment.objects.filter(contribution_id=contributions.first().id).count() == 0
Optional (more an FYI):

```
assert not Payment.objects.filter(contribution_id=contributions.first()).exists()
```

2024-09-06 01:13 UTC, njharman approved these changes

2024-09-06 01:13 UTC, njharman commented on apps/contributions/models.py
> +        return self.annotate(first_payment_date=Min("payment__transaction_time"))
I believe this will annotate Nulls if Contribution has no payments [I see that is tested below]. The replaced code would default to created.  `else instance.created`.

I'm not really sure it matters (will there ever be Contribution without payments in these views)? I'm not sure how null will be sorted in SPA.

Just hi-lighting, in case it does matter.

2024-09-06 01:13 UTC, njharman commented on apps/contributions/tests/test_models.py
> +            transaction_time__isnull=True
Can transaction_time really be None? Not sure I understand excluding from test here.  They're not excluded by the annotation(min(...) are they?

2024-09-10 18:43 UTC, nrh-cklimas commented on apps/contributions/models.py
> +        return self.annotate(first_payment_date=Min("payment__transaction_time"))
Yep--we do want the `null` behavior here. The contributions where this has happened should be otherwise excluded from view (e.g. they're pending a payment, or were flagged).

2024-09-10 18:44 UTC, nrh-cklimas commented on apps/contributions/tests/test_models.py
> +            transaction_time__isnull=True
See https://github.com/newsrevenuehub/rev-engine/pull/1611#discussion_r1745831981

2024-09-10 20:12 UTC, x110dc approved these changes

2024-09-12 13:42 UTC, merged