DEV-4806: Update billing history detail in Portal to include status column
newsrevenuehub/rev-engine pull request #1612
Opened 2024-08-29 15:43 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
- Adds "status" to Payment Serializer so we can display it in the Portal Billing History's section
#### Why are we doing this? How does it help us?
- Display payment status on Portal Billing History
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
yes
#### Have automated unit tests been added? If not, why?
yes
#### How should this change be communicated to end users?
n/a
#### Are there any smells or added technical debt to note?
no
#### Has this been documented? If so, where?
no
#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-4806
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2024-08-30 13:50 UTC, benjaminEwhite requested changes

2024-08-30 13:50 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    def get_status(self, obj):
Let's have type hints for args and return value.

2024-08-30 13:50 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +        return "paid" if obj.amount_refunded == 0 else "refunded"
"paid" and "refunded" are magic values. probably makes sense to set in constant and refer to that var here.

2024-08-30 13:50 UTC, benjaminEwhite commented on apps/contributions/tests/test_serializers.py
> +    return PaymentFactory(refund=True)
PaymentFactory could change its implementation and assumptions in this code might no longer be met.  Might make sense to create the payment then assert about it (prove it's paid or prove it's refunded) then return the value.

2024-08-30 13:50 UTC, benjaminEwhite commented on apps/contributions/tests/test_serializers.py
> +        assert serialized.data["status"] == "paid"
Can use constant val for "paid" here too.

2024-08-30 13:50 UTC, benjaminEwhite commented on apps/contributions/tests/test_serializers.py
> +        assert serialized.data["status"] == "refunded"
Can use constant val for "refunded" here.

2024-08-30 17:13 UTC, GuiMend commented on apps/contributions/tests/test_serializers.py
> +    return PaymentFactory(refund=True)
Talked over slack. Added "paid=True" as Factory trait

2024-08-30 17:16 UTC, GuiMend commented on apps/contributions/tests/test_serializers.py
> +        assert serialized.data["status"] == "refunded"
[e1685b3](https://github.com/newsrevenuehub/rev-engine/pull/1612/commits/e1685b3ba3b845a579fa74facebf460e6957f448)

2024-08-30 17:16 UTC, GuiMend commented on apps/contributions/tests/test_serializers.py
> +        assert serialized.data["status"] == "paid"
[e1685b3](https://github.com/newsrevenuehub/rev-engine/pull/1612/commits/e1685b3ba3b845a579fa74facebf460e6957f448)

2024-08-30 17:16 UTC, GuiMend commented on apps/contributions/tests/test_serializers.py
> +    return PaymentFactory(refund=True)
[e1685b3](https://github.com/newsrevenuehub/rev-engine/pull/1612/commits/e1685b3ba3b845a579fa74facebf460e6957f448)

2024-08-30 17:16 UTC, GuiMend commented on apps/contributions/serializers.py
> +        return "paid" if obj.amount_refunded == 0 else "refunded"
[e1685b3](https://github.com/newsrevenuehub/rev-engine/pull/1612/commits/e1685b3ba3b845a579fa74facebf460e6957f448)

2024-08-30 17:16 UTC, GuiMend commented on apps/contributions/serializers.py
> +    def get_status(self, obj):
[e1685b3](https://github.com/newsrevenuehub/rev-engine/pull/1612/commits/e1685b3ba3b845a579fa74facebf460e6957f448)

2024-09-03 13:36 UTC, benjaminEwhite requested changes
Overall looks good, with a couple of small requests.

2024-09-03 13:36 UTC, benjaminEwhite commented on apps/contributions/tests/test_serializers.py
> +        assert serialized.data["status"] == PAYMENT_REFUNDED
```suggestion
@pytest.mark.parametrize(
        ("payment_fixture", "expected_status"),
        [
            ("paid_payment", PAYMENT_PAID),
            ("refunded_payment", PAYMENT_REFUNDED),
        ],
    )
    def test_status(self, payment_fixture, expected_status, request):
        payment = request.getfixturevalue(payment_fixture)
        serialized = serializers.PortalContributionPaymentSerializer(instance=payment)
        assert serialized.data["status"] == expected_status
```

2024-09-03 13:36 UTC, benjaminEwhite commented on apps/contributions/tests/test_serializers.py
> +    return PaymentFactory(refund=True)
since these are only used in TestPortalContributionPaymentSerializer, seems better to store these fixtures on that class.

2024-09-03 18:12 UTC, benjaminEwhite approved these changes

2024-09-10 18:46 UTC, nrh-cklimas approved these changes

2024-09-10 19:42 UTC, merged