DEV-4744: RevEngine not sending country code to Bad Actor API (Cf-Ipcountry header)
newsrevenuehub/rev-engine pull request #1616
Opened 2024-09-04 13:14 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
Sends user's country_code to bad actor
#### Why are we doing this? How does it help us?
Help identify in bad actor if card issuer and user country are the same
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
not yet
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
no
#### Have automated unit tests been added? If not, why?
n/a
#### How should this change be communicated to end users?
n/a
#### Are there any smells or added technical debt to note?
no
#### Has this been documented? If so, where?
no
#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-4744
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2024-09-05 14:24 UTC, GuiMend commented on apps/contributions/serializers.py
> +        logger.info("BadActorSerializer data: %s", data)
Needed for QA. If removing this log is better, I can remove the commit right after QA passes.

2024-09-05 15:52 UTC, benjaminEwhite requested changes
One small comment inline. Aside from that, I think it would make sense to have a unit test around the business logic here (show that when header has CF-Ipcountry, the data passed to `make_bad_actor_request` contains the value, and when header does not a have an entry, not included in data).

2024-09-05 15:52 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            "country_code": self.context["request"].headers.get("Cf-Ipcountry", None),
Believe it will default to `None` by default.

2024-09-05 15:55 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            "country_code": self.context["request"].headers.get("Cf-Ipcountry", None),
Also, the AC say that if no code in request header, then should not be included in request to bad actor.  So need some conditionality around that.

2024-09-05 17:35 UTC, GuiMend commented on apps/contributions/serializers.py
> +            "country_code": self.context["request"].headers.get("Cf-Ipcountry", None),
Got it, my bad. I thought that sending `"country_code": None` was enough to pass AC2.

2024-09-05 19:50 UTC, benjaminEwhite approved these changes

2024-09-06 20:49 UTC, x110dc approved these changes

2024-09-06 20:49 UTC, x110dc commented on apps/contributions/serializers.py
> +        logger.info("BadActorSerializer data: %s", data)
I think it's fine to leave it as-is.

2024-09-17 02:07 UTC, benjaminEwhite approved these changes

2024-09-17 18:00 UTC, merged