DEV-5209: Add org id and action to bad actor
newsrevenuehub/rev-engine pull request #1621
Opened 2024-09-09 12:49 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
Adds "action" and "org_id" to bad actor request
#### Why are we doing this? How does it help us?
We need to be able to treat some orgs differently in bad actor and knowing the org would enable that.
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
no
#### Have automated unit tests been added? If not, why?
yes
#### How should this change be communicated to end users?
n/a
#### Are there any smells or added technical debt to note?
no
#### Has this been documented? If so, where?
n/a
#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-5209
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2024-09-10 01:47 UTC, benjaminEwhite requested changes

2024-09-10 01:47 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    def get_bad_actor_score(self, data, action: str = "contribution"):
"contribution" here is a "magic value" so probably should be defined in all caps const at top of module and can be referenced elsewhere (or alternatively defined somehwere else that makes sense and imported here).

2024-09-10 01:47 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    def get_bad_actor_score(self, data, action: str = "contribution"):
All else equal, it would be nice to provide more detailed type hints about `data` param.

2024-09-10 01:47 UTC, benjaminEwhite commented on apps/users/tests/test_views.py
> +        assert mock_bad_actor_request.call_args[0][0]["action"] == "create-account"
"create-account" should be in a const var in object code that gets imported into tests.

2024-09-10 01:47 UTC, benjaminEwhite commented on apps/users/views.py
> +                    "action": "create-account",
define in constant

2024-09-10 01:47 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +
Thes should be set to constant vals accessible in (relatively) global scope.

2024-09-10 01:47 UTC, benjaminEwhite commented on apps/users/tests/test_views.py
> +        assert mock_bad_actor_request.call_args[0][0]["last_name"] == ""
Seems fine, but the reason for these particular values is kind of opaque, if i'm trying to understand what the business logic is here. Are first name and last name empty string because that's default value for those fields? If so, shared in situ var to that effect with appropriate name will make that meaning clear

2024-09-10 01:47 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            "org": data["page"].organization.id,
How confident are we about data['page"].organization.id having referential integrity?  Do we have a strong gaurantee here, and if not, what happens if this long chain isn't found at runtime?

2024-09-10 01:47 UTC, benjaminEwhite commented on apps/users/tests/test_views.py
> +    def test_make_bad_actor_request_payload(self, mocker, api_client, valid_create_request_data):
Docstring describing higher level what this test is trying to prove would be helpful here.

2024-09-10 13:50 UTC, GuiMend commented on apps/contributions/serializers.py
> +            "org": data["page"].organization.id,
`data['page']` is a `DonationPage` instance. I'd think a `DonationPage` would always have an `RP` and `Org` associated with it. What do you think?

Or should we do something like:
```suggestion
            "org": data["page"].organization.id if data["page"].organization else None,
```

2024-09-10 14:05 UTC, GuiMend commented on apps/users/tests/test_views.py
> +        assert mock_bad_actor_request.call_args[0][0]["last_name"] == ""
I did some testing, and both `first_name` and `last_name` will always return `""` as the serializer doesn't even have these fields available
<img width="627" alt="image" src="https://github.com/user-attachments/assets/63f8f873-7b45-47f2-97b5-f3f327187848">

I could change these lines to 
<img width="717" alt="image" src="https://github.com/user-attachments/assets/b2726612-7a1d-4208-8854-5b6956816289">

```python
"first_name": "",
"last_name": "",
```

Or remove these fields entirely.

2024-09-10 14:12 UTC, GuiMend commented on apps/contributions/serializers.py
> +    def get_bad_actor_score(self, data, action: str = "contribution"):
I'm not sure how to type hint here. The `data` type is the same as `validated_data` in the `create` function, and it is `any` over there.
<img width="543" alt="image" src="https://github.com/user-attachments/assets/db01c5e2-ea50-436e-aaf2-576e2d81444d">

2024-09-10 14:31 UTC, GuiMend commented on apps/contributions/serializers.py
> +    def get_bad_actor_score(self, data, action: str = "contribution"):
[b571797](https://github.com/newsrevenuehub/rev-engine/pull/1621/commits/b571797add900d583b11524af66b19e2cc63a570)

2024-09-10 14:31 UTC, GuiMend commented on apps/users/tests/test_views.py
> +        assert mock_bad_actor_request.call_args[0][0]["action"] == "create-account"
[b571797](https://github.com/newsrevenuehub/rev-engine/pull/1621/commits/b571797add900d583b11524af66b19e2cc63a570)

2024-09-10 14:31 UTC, GuiMend commented on apps/users/views.py
> +                    "action": "create-account",
[b571797](https://github.com/newsrevenuehub/rev-engine/pull/1621/commits/b571797add900d583b11524af66b19e2cc63a570)

2024-09-10 14:31 UTC, GuiMend commented on apps/contributions/serializers.py
> +
[b571797](https://github.com/newsrevenuehub/rev-engine/pull/1621/commits/b571797add900d583b11524af66b19e2cc63a570)

2024-09-12 14:18 UTC, benjaminEwhite approved these changes
Had one comment about a default value. Feel free to resolve that on your own @Gui without re-review from me.  I'm approving with understanding you'll resolve that before assigning to next reviewer.

2024-09-12 14:18 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    def get_bad_actor_score(self, data, action: BadActorAction = BadActorAction.CONTRIBUTION):
Think it's better to have no default here and to force callers to specify. Either that or default to None.

2024-09-13 15:14 UTC, benjaminEwhite approved these changes

2024-09-13 21:36 UTC, x110dc approved these changes

2024-09-20 13:32 UTC, merged