DEV-5249. exclude contributions with dummy pm id from portal
newsrevenuehub/rev-engine pull request #1624
Opened 2024-09-18 21:19 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

This solves for a bug whereby portal does not load for contributors who have one or more contributions with a provider payment method id value of "pm_this_is_temp_for_2445".  When contributors access the portal, the endpoint pulls in payment method data from Stripe, and there's an uncaught error around this ID because it's fake.

There's another ticket — [DEV-4693](https://news-revenue-hub.atlassian.net/browse/DEV-4963) — which will solve for the underlying problem (getting correct payment method ID on these contributions). This ticket just prevents that data state from breaking portal.

#### Why are we doing this? How does it help us?

Unbreaks portal for about 6k users

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

Yes

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No

#### Have automated unit tests been added? If not, why?

Yes

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

-[DEV-5249](https://news-revenue-hub.atlassian.net/browse/DEV-5249)
-[DEV-4693](https://news-revenue-hub.atlassian.net/browse/DEV-4963)

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No

2024-09-18 21:25 UTC, x110dc requested changes

2024-09-18 21:25 UTC, x110dc commented on apps/contributions/tests/test_models.py
> +    def test_exclude_exclude_dummy_payment_method_id(self, settings):
only one `exclude`?

2024-09-18 21:25 UTC, x110dc commented on revengine/settings/base.py
> +# DEV-4693
DEV-4693 is marked as done already. Is that a typo and a different ticket should appear here?

2024-09-18 21:34 UTC, benjaminEwhite commented on apps/contributions/tests/test_models.py
> +    def test_exclude_exclude_dummy_payment_method_id(self, settings):
973b446b67

2024-09-18 21:50 UTC, benjaminEwhite commented on revengine/settings/base.py
> +# DEV-4693
This was a typo (meant DEV-4963) and on top of that, had the ticket wrong.  Should be DEV-4967.

bab721dcb

2024-09-19 02:30 UTC, x110dc approved these changes

2024-09-19 15:36 UTC, merged