DEV-5005: implement amount change UI spa
newsrevenuehub/rev-engine pull request #1625
Opened 2024-09-19 15:33 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
Allow contributors to edit amount on existing contributions if org has a PLUS plan
#### Why are we doing this? How does it help us?
Allow contributors to edit contribution amount
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
yes
#### Have automated unit tests been added? If not, why?
yes
#### How should this change be communicated to end users?
Contributors can change amount on contribution if org has a PLUS plan
#### Are there any smells or added technical debt to note?
no
#### Has this been documented? If so, where?
no
#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-5005
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2024-09-19 18:50 UTC, benjaminEwhite approved these changes
Only looked at backend changes, but those look fine.

2024-09-20 20:33 UTC, nrh-cklimas requested changes

2024-09-20 20:33 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingDetails/BillingDetails.tsx
> +  );
1. I think it'd be a good idea to move this logic up to ContributionDetail so that everything deciding whether the section is editable is in one place.
2. I think it's more efficient to pull the RP from `usePortal()` since contributors are logging into a portal for a particular RP. Would mean that this could be a SPA-only change.

2024-09-20 20:33 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/DetailSection/DetailSectionEditControls.tsx
:+1: For centralizing repeated logic here

2024-09-20 20:33 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/DetailSection/DetailSectionEditControls.tsx
> +  disabled: PropTypes.bool,
Quibble: consider renaming to `saveDisabled` to make it clear Cancel is always enabled.

2024-09-20 20:33 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/ContributionDetail.tsx
> +            editable={editableSection === 'paymentMethod' && contribution.is_modifiable}
Good catch!

2024-09-20 20:33 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingDetails/BillingDetails.styled.ts
> +export const StyledTextField = styled(TextField)`
```suggestion
export const AmountField = styled(TextField)`
```
Clearer about its purpose (e.g. offsetting the adornment)

2024-09-20 20:33 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingDetails/BillingDetails.tsx
> +    // Amount will be a valid number at this point and we need to convert it to cents
Let's throw an error if this isn't true, just in case. I think throwing is appropriate here because we don't want to put bad data into the backend. Doesn't need test coverage since this should be an impossible condition.

2024-09-20 20:33 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingDetails/BillingDetails.tsx
> +  useEffect(() => {
I think the goal of this effect is to reset the amount field if the user cancels out and then re-edits the field, since you're giving `amount` an initial value?

If so, let's add a small function that's called by `onCancel` on DetailSectionEditControls:

```tsx
function handleCancel() {
  setAmount(amountInDollars?.toString());
  onEditComplete();
}
```

2024-09-23 17:49 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingDetails/BillingDetails.tsx
> +  const disableSave = useMemo(() => {
Following up on Slack conversation--we no longer have this function. How would you feel about this?

```tsx
const disableSave = useMemo(() => {
  const parsedValue = parseFloatStrictly(amount);

  return isNaN(parsedValue) || parsedValue <= 0 || parsedValue == amountInDollars;
}, []);
```

2024-09-23 19:04 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingDetails/BillingDetails.tsx
> +  const disableSave = useMemo(() => {
I like your suggestion. When I implemented this function, I didn't think `parseFloatStrictly` would handle the "isEmpty" and "isOnlyZero" cases as well.

2024-09-23 19:04 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingDetails/BillingDetails.tsx
> +  const disableSave = useMemo(() => {
[215ad4f](https://github.com/newsrevenuehub/rev-engine/pull/1625/commits/215ad4fadb9d2a8cd4a4b84c9de59707e12f5544)

2024-09-23 19:05 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingDetails/BillingDetails.tsx
> +  useEffect(() => {
[7651576](https://github.com/newsrevenuehub/rev-engine/pull/1625/commits/76515762ab213924e73bdbc66a8be458453a81fb)

2024-09-23 19:05 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingDetails/BillingDetails.tsx
> +    // Amount will be a valid number at this point and we need to convert it to cents
[7651576](https://github.com/newsrevenuehub/rev-engine/pull/1625/commits/76515762ab213924e73bdbc66a8be458453a81fb)

2024-09-23 19:05 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingDetails/BillingDetails.styled.ts
> +export const StyledTextField = styled(TextField)`
[7651576](https://github.com/newsrevenuehub/rev-engine/pull/1625/commits/76515762ab213924e73bdbc66a8be458453a81fb)

2024-09-23 19:05 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/DetailSection/DetailSectionEditControls.tsx
> +  disabled: PropTypes.bool,
[7651576](https://github.com/newsrevenuehub/rev-engine/pull/1625/commits/76515762ab213924e73bdbc66a8be458453a81fb)

2024-09-23 19:06 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingDetails/BillingDetails.tsx
> +            <StyledTextField
I think a follow-up ticket would be best as this ticket is important for our sprint goals

2024-09-23 19:06 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingDetails/BillingDetails.tsx
>  // This will eventually have an editable state.
[7651576](https://github.com/newsrevenuehub/rev-engine/pull/1625/commits/76515762ab213924e73bdbc66a8be458453a81fb)

2024-09-23 19:32 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/ContributionDetail.test.tsx
> +      it("BillingDetails doesn't allow edit mode if contribution.is_modifiable = true", () => {
Think it _does_ allow edit mode in this case?

2024-09-23 19:39 UTC, nrh-cklimas commented on spa/src/components/portal/ContributionsList/ContributionDetail/BillingDetails/BillingDetails.tsx
> +            <StyledTextField
https://news-revenue-hub.atlassian.net/browse/DEV-5267

2024-09-23 19:41 UTC, nrh-cklimas approved these changes

2024-09-23 20:16 UTC, GuiMend commented on spa/src/components/portal/ContributionsList/ContributionDetail/ContributionDetail.test.tsx
> +      it("BillingDetails doesn't allow edit mode if contribution.is_modifiable = true", () => {
That's correct. My bad
```suggestion
      it("BillingDetails allows edit mode if contribution.is_modifiable = true", () => {
```

2024-09-25 14:59 UTC, nrh-cklimas approved these changes

2024-09-25 18:42 UTC, merged