DEV-5276: Send amount change email
newsrevenuehub/rev-engine pull request #1633
Opened 2024-10-01 12:42 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
- Sends email for contributors when they change a contribution amount
#### Why are we doing this? How does it help us?
- Improve communication 
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
- ye
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
- yes
#### Have automated unit tests been added? If not, why?
- yes
#### How should this change be communicated to end users?
- Email is sent for contributors when they change a contribution amount
#### Are there any smells or added technical debt to note?
- no
#### Has this been documented? If so, where?
- no
#### What are the relevant tickets? Add a link to any relevant ones.
- https://news-revenue-hub.atlassian.net/browse/DEV-5276
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
- no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
- no

2024-10-01 20:56 UTC, nrh-cklimas requested changes

2024-10-01 20:56 UTC, nrh-cklimas commented on apps/contributions/models.py
> +        self.amount = amount
I think there's a potential problem here if the Stripe update fails. In that case, the db model has the amount that the user wanted to update to, but Stripe doesn't.

I think this can be solved by either:
- Passing the updated amount to `send_recurring_contribution_amount_updated_email` (I think I prefer this but I'm not 100% on it)
- Moving the change to the model field to after the Stripe call and add a unit test for this scenario

2024-10-01 20:56 UTC, nrh-cklimas commented on apps/emails/templates/nrh-default-contribution-base-template.html
Since we're changing the base template, it makes sense to me to add regression tests in QA instructions to run through existing emails to make sure there aren't any unintended changes.

2024-10-02 15:32 UTC, GuiMend commented on apps/contributions/models.py
> +        self.amount = amount
I don't think this will be a problem @nrh-cklimas.
We only ever `save` the contributor after the try/except (line 1274)

```python
self.save(update_fields={"contribution_metadata", "amount", "modified"})
```

2024-10-02 18:23 UTC, nrh-cklimas commented on apps/contributions/models.py
> +        self.amount = amount
I see what you're saying. If it's ok with you, would like an opinion from @benjaminEwhite on approach here.

2024-10-02 18:23 UTC, nrh-cklimas approved these changes

2024-10-02 18:47 UTC, benjaminEwhite requested changes

2024-10-02 18:47 UTC, benjaminEwhite commented on apps/contributions/models.py
> +
I know we already save contribution at this moment in status quo, but all else equal, I think we would want to rely on Stripe webhooks to trigger a handler that updates revengine contribution amount and triggers reminder email, because that's evidence of transation finality on Stripe side (which is the source of truth here).

As implemented here, we can end up in a situation where Stripe is updated, but revengine is not.

2024-10-02 19:46 UTC, nrh-cklimas commented on apps/contributions/models.py
> +
@GuiMend could you clarify if on the main branch, we are updating amount in Django correctly when a subscription amount is changed? I thought we were but looking at [the original PR](https://github.com/newsrevenuehub/rev-engine/pull/1633), I'm getting confused.

2024-10-02 19:57 UTC, benjaminEwhite commented on apps/contributions/models.py
> +
FWIW, another way we also might be able to use `@transaction.atomic` such that we update we first save the changes to revengine then call stripe to update. If things work out with stripe, the amount change is committed to DB, but if not, it is not (despite being first in terms of code line).  This would require that we allow exceptions to bubble up.

2024-10-02 20:01 UTC, GuiMend commented on apps/contributions/models.py
> +        # Need to update contribution amount here so that it reflects the new amount in the email
This comment is unnecessary. I'll remove it. It could have been a GitHub PR comment instead.

I just wanted to point out that we are already saving the "amount" change, but I had to make it earlier so that the email data generation works as expected.

```
# File /contributions/serializers.py > line 974
 with reversion.create_revision():
                instance.save(update_fields={*validated_data.keys(), "modified"})
                reversion.set_comment("Updated by PortalContributionDetailSerializer.update")
```

```suggestion
```

2024-10-02 20:03 UTC, GuiMend commented on apps/contributions/models.py
> +
Yes @nrh-cklimas , we are. The amount is being saved here:

```python
# File /contributions/serializers.py > line 974
 with reversion.create_revision():
                instance.save(update_fields={*validated_data.keys(), "modified"})
                reversion.set_comment("Updated by PortalContributionDetailSerializer.update")
```

2024-10-03 15:34 UTC, benjaminEwhite approved these changes

2024-10-04 19:28 UTC, merged