DEV-5216 | Make BadActorSerializer more idiomatic
newsrevenuehub/rev-engine pull request #1635
Opened 2024-10-01 19:52 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

This PR refactors `BadActorSerializer`, removing an over-ride of `to_internal_value`. As noted in ticket for this PR, I discovered the following oddity:

```
from apps.contributions.serializers import BadActorSerializer

instance  = BadActorSerializer(data={"first_name": "foo", "last_name": "bar", "email": "foo@bar.com", "amount": "12400", "ip":  "192.0.2.1", "referer": "https://fundjournalism.org" })
instance.is_valid()
# false
instance.errors
Out[4]: {'street': [ErrorDetail(string='This field may not be null.', code='null')], '.....
```

Not totally clear why, but somehow using the over-ride of to_internval_value cased the default values for those fields to not be present, triggering a validation error.

Unclear if any bugs directly resulted from that, but it causes the serializer to behave in unexpected ways.

To solve for this, instead of mapping source values to destination values in `to_internal_value` we just create input data with necessary keys ahead of initializing serializer.

#### Why are we doing this? How does it help us?

Make BadActorSerializer's behavior more predictable

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

Yes

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No

#### Have automated unit tests been added? If not, why?

No. We remove existing code.

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-5216](https://news-revenue-hub.atlassian.net/browse/DEV-5216)

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No

2024-10-03 20:22 UTC, njharman requested changes

2024-10-03 20:22 UTC, njharman commented on apps/contributions/serializers.py
> +    city = serializers.CharField(
I don't see any changes in these lines. Wonder why formatter chose to break apart, ... Oh, probably the trailing comma.

I find that annoying.

2024-10-03 20:22 UTC, njharman commented on apps/contributions/serializers.py
> +        data = {
Given docstring 
> Note that this method is meant to be ironclad against exceptions. If anything goes wrong, it should return None.

All of this should be in try block

2024-10-03 20:22 UTC, njharman commented on apps/contributions/serializers.py
> +        data = {
There's a typo in the catch Exception "sore" should be "score".  But real reason for comment is consider adding debugging info to exception log. Such as "data" (before it's modified)

2024-10-03 20:22 UTC, njharman commented on apps/contributions/serializers.py
> -                "page": data["page"].id,
I don't see "page" replicated above.

Was it intentional removal?

2024-10-03 20:22 UTC, njharman commented on apps/contributions/serializers.py
> +        data = {
Suggest not reusing name "data" also used as argument.

2024-10-03 20:30 UTC, njharman requested changes

2024-10-03 20:30 UTC, njharman commented on apps/contributions/serializers.py
> +            "complement": data["mailing_complement"],
complement, captcha_token, ip, referer, reason_for_giving don't seem to be tested for in `test_get_bad_actor_score_fields()`

But there probably should be a separate test to prove AC2. Something with all default values and none of those defaults are `None`. At least that is my understanding of issue

> string='This field may not be null.'

2024-10-03 21:08 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> -                "page": data["page"].id,
And that's why we have code review...

2024-10-04 19:32 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +        data = {
25c2a0e899

2024-10-04 19:38 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            "complement": data["mailing_complement"],
fd41aec9ff0

2024-10-07 17:57 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +        data = {
1abbbc571

2024-10-07 18:00 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +        data = {
Resolved the typo, but not sure which commit.

RE: adding data d59fb117e49b

2024-10-07 18:01 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +        data = {
Resolved the typo, but not sure in which commit.

Re: data and logging d59fb117e49b

2024-10-08 13:56 UTC, nrh-cklimas approved these changes

2024-10-09 13:25 UTC, merged