DEV-5295 | First pass at using uv in revengine
newsrevenuehub/rev-engine pull request #1638
Opened 2024-10-04 15:55 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2024-10-08 00:42 UTC, benjaminEwhite commented on .envrc.example
> +export export VIRTUAL_ENV=".venv"
```suggestion
export VIRTUAL_ENV=".venv"
```

2024-10-09 21:54 UTC, njharman requested changes

2024-10-09 21:54 UTC, njharman commented on Makefile
> +VENV_DIR="./.venv"
Prepending superfluous "./" is weird.

2024-10-09 21:54 UTC, njharman commented on Makefile
> +	source $(VENV_DIR)/bin/activate
source is bash built in (for me under ubuntu) and make is using sh. Thus

```
source "./.venv"/bin/activate
/bin/sh: 1: source: not found
```

Setting default shell wfm, copied from 

https://stackoverflow.com/questions/7507810/how-to-source-a-script-in-a-makefile

> Makefile default shell is /bin/sh which does not implement source.
> Changing shell to /bin/bash makes it possible:
> 
> ```
> # Makefile
> 
> SHELL := /bin/bash
> ```

2024-10-09 21:54 UTC, njharman commented on README.md
> +Note that unlike Poetry, uv does not automatically update the `pyproject.toml` file and `uv.lock` files after adding/removing dependencies. You'll want to manually add/remove from `pyproject.toml` an
I would cut "unlike Poetry, "

Also consider moving this to top of section, under ### How to...  [reckon it's harder to miss there].

2024-10-09 21:54 UTC, njharman commented on README.md
> +This command will create a virtual environment in the project directory at `/.venv` and will install dependencies (inclusive of dev deps).
Step 2 "Set up virtual environment" seems no longer relevant.

And while we're messing with this.  Shouldn't step 7 envvars be one of the first, before JS/Python. I can imagine those using envvars.

2024-10-09 21:54 UTC, njharman commented on Makefile
>  setup:
I believe the method to "start work" is `source $(VENV_DIR)/bin/activate`. It would be nice to have make entry for this

activate:
  source $(VENV_DIR)/bin/activate
  python --version

I miss poetry shell (or rather vex) there's workarounds https://github.com/astral-sh/uv/issues/1910

2024-10-09 21:54 UTC, njharman commented on .github/workflows/test-python.yml
> +          uv venv create --python=python3.10
Do we have "upgrade python docs"?  If so should add mention to look here and in Dockerfile to update python versions.

2024-10-09 21:54 UTC, njharman commented on .pre-commit-config.yaml
> +    rev: 0.4.18
The installer gave me version 0.4.20. 

Leo and I have this problem with ruff. They upgrade it so frequently, often occurs between dev and review.

2024-10-09 21:54 UTC, njharman commented on Dockerfile
> +COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv
latest is probably easier than updating specific version all the time?

2024-10-09 21:54 UTC, njharman commented on pyproject.toml
>  # TODO @njh: reduce complexity to 10 or less
This comment should go with `[tool.ruff.lint.mccabe]` section

`[tool.uv]` was inserted in-between

2024-10-17 16:05 UTC, benjaminEwhite commented
Closing this PR because it's served purpose as PoC and we've decided not to move forward with uv in revengine just yet.

2024-10-17 16:05 UTC, closed without merging