DEV-3528: Handle missing router state in thank you page
newsrevenuehub/rev-engine pull request #1639
Opened 2024-10-04 19:51 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
Fixes error when returning to Generic Thank you page
#### Why are we doing this? How does it help us?
When going back to Generic Thank you page, user saw an error and the page breaks
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
no
#### Have automated unit tests been added? If not, why?
yes
#### How should this change be communicated to end users?
n/a
#### Are there any smells or added technical debt to note?
no
#### Has this been documented? If so, where?
n/a
#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3528
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2024-10-04 20:23 UTC, nrh-cklimas requested changes

2024-10-04 20:23 UTC, nrh-cklimas commented on spa/src/components/donationPage/live/GenericThankYou/GenericThankYou.tsx
> +    !routedState?.page
Can this be simplified to `if (!routedState)`?

2024-10-07 19:06 UTC, GuiMend commented on spa/src/components/donationPage/live/GenericThankYou/GenericThankYou.tsx
> +    !routedState?.page
We could do that. But this is asserting that we have all the necessary fields to render the Thank You page. If we substitute for only `!routedState` there could be a missing field.

2024-10-07 19:10 UTC, nrh-cklimas commented on spa/src/components/donationPage/live/GenericThankYou/GenericThankYou.tsx
> +    !routedState?.page
Got it, makes sense.

2024-10-07 19:11 UTC, nrh-cklimas approved these changes

2024-10-09 13:35 UTC, merged