DEV-5039 | management command to fix payment method id (and details)
newsrevenuehub/rev-engine pull request #1644
Opened 2024-10-10 19:51 UTC by benjaminEwhite

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2024-10-17 19:21 UTC, njharman requested changes

2024-10-17 19:21 UTC, njharman commented on apps/contributions/management/commands/fix_contributions_missing_provider_payment_method_id.py
> +    """Find contributions with missing or dummy val for provider_payment_method_id try to update.
"val" -> "value"

2024-10-17 19:21 UTC, njharman commented on apps/contributions/management/commands/fix_contributions_missing_provider_payment_method_id.py
> +                | Q(~Q(interval=ContributionInterval.ONE_TIME), provider_subscription_id__isnull=False)
AFIK ~ is bitwise operator. Is it overloaded by Django Q()?  I did not figure out after few moments of searching.  If not, I don't believe we shouldn't be using bitwise here.

Does `interval != ContributionInter...` not work here?

2024-10-17 19:31 UTC, benjaminEwhite commented on apps/contributions/management/commands/fix_contributions_missing_provider_payment_method_id.py
> +    """Find contributions with missing or dummy val for provider_payment_method_id try to update.
f182501902

2024-10-17 19:32 UTC, benjaminEwhite commented on apps/contributions/management/commands/fix_contributions_missing_provider_payment_method_id.py
> +                | Q(~Q(interval=ContributionInterval.ONE_TIME), provider_subscription_id__isnull=False)
This is idimoatic Django (and no you can't do `!=`).

https://docs.djangoproject.com/en/4.2/topics/db/queries/#complex-lookups-with-q-objects

2024-10-17 19:40 UTC, benjaminEwhite commented on apps/contributions/models.py
> +                "null value for provider_payment_id that cannot be updated because account is disconnected or some other problem "
Good catch. Copied this over from a more specific contex and missed cleaning up that log message.

2024-10-18 19:39 UTC, njharman submitted a review, later dismissed

2024-10-18 19:39 UTC, njharman commented on apps/contributions/management/commands/fix_contributions_missing_provider_payment_method_id.py
> +                | Q(~Q(interval=ContributionInterval.ONE_TIME), provider_subscription_id__isnull=False)
Thanks that's the docs I couldn't find / overloaded by Q().

2024-10-18 19:39 UTC, njharman commented on apps/contributions/management/commands/fix_contributions_missing_provider_payment_method_id.py
> +                for con in Contribution.objects.filter(
Should we not (re)use the `qs` built above. Seems very WET, (un DRY).

Perhaps not convenient/possible here?; should get in habit of using batch versions of update/save.

2024-10-18 19:39 UTC, njharman commented on apps/contributions/management/commands/fix_contributions_missing_provider_payment_method_id.py
> +        qs = Contribution.objects.filter(provider_payment_method_id=settings.DUMMY_PAYMENT_METHOD_ID).all()
Duplicate.  `qs` is built twice here, and in if clause.

2024-10-18 20:03 UTC, benjaminEwhite commented on apps/contributions/management/commands/fix_contributions_missing_provider_payment_method_id.py
> +                for con in Contribution.objects.filter(
I generally prefer batch update/save, but then you don't get reversion comments, and I wanted to ensure we have those.

2024-10-18 20:06 UTC, benjaminEwhite commented on apps/contributions/management/commands/fix_contributions_missing_provider_payment_method_id.py
> +        qs = Contribution.objects.filter(provider_payment_method_id=settings.DUMMY_PAYMENT_METHOD_ID).all()
bacfc09b4ce

2024-10-22 18:49 UTC, x110dc approved these changes
Approved.

2024-10-22 20:47 UTC, merged