DEV-5359: Conditionally update donor_selected_amount
newsrevenuehub/rev-engine pull request #1646
Opened 2024-10-23 19:50 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

When a contribution amount is updated, this conditionally updates `donor_selected_amount`.

#### Why are we doing this? How does it help us?

Only some contributions' metadata schemas support `donor_selected_amount`.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

Yes.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No.

#### Have automated unit tests been added? If not, why?

Yes.

#### How should this change be communicated to end users?

n/a

#### Are there any smells or added technical debt to note?

No.

#### Has this been documented? If so, where?

No.

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-5359

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

https://news-revenue-hub.atlassian.net/browse/ITS-2610

2024-10-24 18:35 UTC, benjaminEwhite requested changes

2024-10-24 18:35 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        if "donor_selected_amount" in self.contribution_metadata:
I think we might want to be stricter here by:

1. cast contribution_metadata to an instance of known schema version via `cast_metadata_to_stripe_payment_metadata_schema`
2. update the condition to be current condition + "donor_selected_amount" is in the specific schema

2024-10-24 18:35 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            self.contribution_metadata["donor_selected_amount"] = amount
Would also be good to use the metadata schema to validate the value being set for donor selected amount (since the schemas are pydantic models).

2024-10-24 18:35 UTC, benjaminEwhite commented on apps/contributions/tests/test_models.py
> +    @pytest.mark.parametrize("contribution_metadata", [{}, {"donor_selected_amount": 123}])
Getting stricter above would potentially requiring fully mocking out the metadata here (though there may be pre-existing fixtures that would help, i don't recall off hand).

2024-10-24 19:08 UTC, nrh-cklimas commented on apps/contributions/models.py
> +        if "donor_selected_amount" in self.contribution_metadata:
So semi-pseudocoding your suggestion, are you saying..?

```python
typed_metadata = cast_metadata_to_stripe_payment_metadata_schema(contribution.contribution_metadata)

if (isinstance(typed_metadata, StripePaymentMetadataSchemaV1_4) or \
    isinstance(typed_metadata, StripePaymentMetadataV1_5)):
    self.contribution_metadata["donor_selected_amount"] = amount
```

or:

```python
typed_metadata = cast_metadata_to_stripe_payment_metadata_schema(contribution.contribution_metadata)

if (hasattr(type(typed_metadata), "donor_selected_amount")):
    self.contribution_metadata["donor_selected_amount"] = amount
```

2024-10-29 14:43 UTC, benjaminEwhite requested changes

2024-10-29 14:43 UTC, benjaminEwhite commented on apps/contributions/tests/test_models.py
> +            "agreed_to_pay_fees", not contribution.contribution_metadata["agreed_to_pay_fees"]
if only testing one field, might as well use "donor_selected_amount" since that's the only field we're going to be setting with this function for now.

2024-10-29 20:26 UTC, nrh-cklimas commented on apps/contributions/tests/test_models.py
> +            "agreed_to_pay_fees", not contribution.contribution_metadata["agreed_to_pay_fees"]
19bdff7a2ff7f1eb06300eb65d502a1998795ad2

2024-10-29 20:36 UTC, nrh-cklimas commented on apps/contributions/models.py
> +        self.contribution_metadata[key] = value
- I'm on board with blocking schema version changes.
- Would it make sense to ask callers to log as appropriate? e.g. it wouldn't make sense here, I don't think, unless we do it as a debug log?
- I tried the code suggestion and got test regressions elsewhere:

```
FAILED apps/contributions/tests/test_models.py::TestContributionModel::test_update_subscription_amount_when_success_update_contribution - TypeError: Object of type Url is not JSON serializable
FAILED apps/contributions/tests/test_models.py::TestContributionModel::test_update_subscription_amount_updates_donor_selected_amount_metadata[contribution_metadata1] - TypeError: Object of type Url is not JSON serializable
FAILED apps/contributions/tests/test_models.py::TestContributionModel::test_sends_updated_email_when_update_subscription_amount_success - TypeError: Object of type Url is not JSON serializable
```
I think this might indicate real issues? I think the issue is that the `dict()` call is transforming all metadata to the Pydantic-parsed version.

2024-10-30 17:11 UTC, benjaminEwhite requested changes
@nrh-cklimas I resolved some conversations and left an updated suggestion for `set_metadata_field` that solves for test issue you encountered.

2024-10-30 17:11 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        self.contribution_metadata[key] = value
@nrh-cklimas ah looks like there was issue converting the pydantic.http url field.

I just updated a line in the suggestion to solve for that (need to output the pydantic instance to JSON string then load that as dict...).

2024-10-30 17:11 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        if "donor_selected_amount" in self.contribution_metadata:
Closing this thread cause I don't htink it's relevant anymore.

2024-10-30 17:11 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            self.contribution_metadata["donor_selected_amount"] = amount
Also resolving this because I believe it's subsumed by other open conversations.

2024-10-30 18:29 UTC, nrh-cklimas commented on apps/contributions/models.py
> +        self.contribution_metadata[key] = value
Works for me. Added in c11e24e560c7249611814c40c5d13ca6b4349b0d with a check at the top to make sure we're not changing the schema version, as previously discussed.

2024-10-31 13:50 UTC, benjaminEwhite approved these changes
Looks good. Two minor suggestions that you can resolve on your own without re-review from me @nrh-cklimas.

2024-10-31 13:50 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            raise InvalidMetadataError(f"No schema found for version {version}") from error
Looks like this path doesn't get executed in tests. Think we should add a test for this case, but no need for me to re-review.

2024-10-31 14:11 UTC, nrh-cklimas commented on apps/contributions/models.py
> +            raise InvalidMetadataError(f"No schema found for version {version}") from error
3cf1f6cb88b105cd51fd2c43705989f702f597d0

2024-10-31 14:13 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            raise InvalidMetadataError(f"Change to {key} results in invalid contribution metadata") from error
Might be worth a code comment here -- think this error message is fine (since the attempt to update the key in question would indeed be the immediate dcause), but it's logically possible that the key we're trying to update the value for is not the culprit -- there's no guarantee that the value in db for contribution_metadata is valid, and outstanding invalid dict entries could actually be what trigger this error.

2024-10-31 14:15 UTC, nrh-cklimas commented on apps/contributions/models.py
> +            raise InvalidMetadataError(f"Change to {key} results in invalid contribution metadata") from error
a9b451a65380ae10c9fe3a91760296ca7f39efd7

2024-11-01 17:53 UTC, njharman approved these changes

2024-11-01 17:53 UTC, njharman commented on apps/contributions/models.py
> +            raise InvalidMetadataError(f"Change to {key} results in invalid contribution metadata") from error
Consider adding `value` to error message. [Seems useful in diagnosing if bad value vs bad key fails validation]

2024-11-01 17:53 UTC, njharman commented on apps/contributions/models.py
> +            raise InvalidMetadataError("Schema version may not be changed")
When `InvalidMetadataError `is contextlib.suppressed (below), I assume Sentry never sees it? Thus there is no log of it ever happening.

Do any of error these conditions warrant logging? Perhaps just debug?  And if so, log here? or let the caller decide to log or not (by catching logging and possibly ignoring exception)?

2024-11-01 17:53 UTC, njharman commented on apps/contributions/models.py
> +
no empty line between comment and code it is commenting

2024-11-01 19:47 UTC, nrh-cklimas commented on apps/contributions/models.py
> +            raise InvalidMetadataError(f"Change to {key} results in invalid contribution metadata") from error
I think this could possibly put data we don't want into logs, so skipping for now.

2024-11-01 19:48 UTC, nrh-cklimas commented on apps/contributions/models.py
> +            raise InvalidMetadataError("Schema version may not be changed")
My approach here is to let the caller decide, but could re-evaluate if it ends up being a common pattern.

2024-11-01 19:50 UTC, nrh-cklimas commented on apps/contributions/models.py
> +
bc3e86db89e74f522f38e00ae89a8cd08a564d5e

2024-11-05 01:08 UTC, x110dc approved these changes
Noted one tiny typo in a comment. Otherwise LGTM.

2024-11-05 01:08 UTC, x110dc commented on apps/contributions/models.py
> +            # pre-existing incorrect metadata, then validation would fail here.
super minor: extraneous period in comment

2024-11-22 18:56 UTC, merged