DEV-5348: Add command to clear Mailchimp status
newsrevenuehub/rev-engine pull request #1649
Opened 2024-10-29 15:10 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

Adds a management command, `clear_mailchimp_integration`.

#### Why are we doing this? How does it help us?

Semi-automates a support task.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

Yes.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No.

#### Have automated unit tests been added? If not, why?

Yes.

#### How should this change be communicated to end users?

n/a

#### Are there any smells or added technical debt to note?

There was one questionable thing that came up writing tests I'll comment on.

#### Has this been documented? If so, where?

No.

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-5348

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No.

2024-10-29 15:11 UTC, nrh-cklimas commented on apps/organizations/tests/test_management.py
> +        edited_rp = RevenueProgram.objects.get(id=revenue_program.id)
I needed to re-fetch the RP here because changes made by the command weren't applied to the local model, which makes sense. But it felt like there might be a better way to do this.

2024-10-30 01:19 UTC, njharman requested changes

2024-10-30 01:19 UTC, njharman commented on apps/organizations/management/commands/clear_mailchimp_integration.py
> +    def handle(self, *args, **options):
Why only somethings Typing return value?

[As official grumpy greybeard I'm not a typing proponent/user. But being such also means I'm triggered by inconsistency.]

2024-10-30 01:19 UTC, njharman commented on apps/organizations/management/commands/clear_mailchimp_integration.py
> +        revenue_program = RevenueProgram.objects.get(slug=options["slug"])
Possibly not worth effort; but consider a nicer error message for user than the NotFound traceback I assume will happen if they enter bad/typo'd slug.

2024-10-30 01:19 UTC, njharman commented on apps/organizations/management/commands/clear_mailchimp_integration.py
> +            revenue_program.save()
Curious why these are not "deleted"

- mailchimp_list_id
- mailchimp_contributor_segment_id
- mailchimp_recurring_contributor_segment_id
- mailchimp_all_contributors_segment_id

There's also several cached properties like `mailchimp_client`. That maybe want to "uncache".

2024-10-30 01:19 UTC, njharman commented on apps/organizations/management/commands/clear_mailchimp_integration.py
> +class Command(BaseCommand):
I would consider adding comment in apps/organizations/models.py near RevenueProgram mailchimp fields along the lines of "Any mailchimp fields should also be cleaned up in clear_mailchimp_integration.py::handle"

Or, RevenueProgram.clear_mailchimp_integration() method and moving logic below to there. [I'd still probably add above comment and just reference this method instead, but being "closer" to origin may help future refactorings to notice it]

2024-10-31 15:23 UTC, nrh-cklimas commented on apps/organizations/tests/test_management.py
> +        edited_rp = RevenueProgram.objects.get(id=revenue_program.id)
Outdated

2024-10-31 15:23 UTC, nrh-cklimas commented on apps/organizations/management/commands/clear_mailchimp_integration.py
> +    def handle(self, *args, **options):
Updated in c980c4e562be04cd3fbe72bcdb53f7e54518e103 to drop the return value here because it looks like it can be inferred.

2024-10-31 15:25 UTC, nrh-cklimas commented on apps/organizations/management/commands/clear_mailchimp_integration.py
> +class Command(BaseCommand):
This was a really good catch. Looking this up, I discovered we already had a `disable_mailchimp_integration()` method on `RevenueProgram`, so I refactored to make the command call it in c980c4e562be04cd3fbe72bcdb53f7e54518e103.

2024-10-31 15:25 UTC, nrh-cklimas commented on apps/organizations/management/commands/clear_mailchimp_integration.py
> +            revenue_program.save()
I think outdated now that we have c980c4e562be04cd3fbe72bcdb53f7e54518e103.

2024-11-01 18:13 UTC, njharman approved these changes

2024-11-04 19:05 UTC, benjaminEwhite reviewed
Had one minor question. Code changes look good.

2024-11-04 19:10 UTC, benjaminEwhite approved these changes

2024-11-05 01:48 UTC, x110dc approved these changes
lgtm

2024-11-06 14:41 UTC, merged