Dev 5429 set amount metadata correctly
newsrevenuehub/rev-engine pull request #1656
Opened 2024-11-07 22:15 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

- Adds a `donor_selected_amount` that is only available when PATCHing an individual contribution. Sending a value here updates the contribution metadata.
- Changes the SPA to send both `amount` and `donor_selected_amount`.

#### Why are we doing this? How does it help us?

Corrects a problem where donor_selected_amount is getting to set to an amount in cents rather than dollars.

I went with this approach to minimize the amount of math we are doing to amounts, to avoid possible problem sources re: rounding.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

Yes.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No.

#### Have automated unit tests been added? If not, why?

Yes.

#### How should this change be communicated to end users?

n/a

#### Are there any smells or added technical debt to note?

No.

#### Has this been documented? If so, where?

No.

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-5429

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No.

2024-11-07 22:19 UTC, nrh-cklimas commented on apps/contributions/models.py
> +            self.set_metadata_field("donor_selected_amount", donor_selected_amount)
I'm not sure what tests, if any, we need on this.

2024-11-12 15:03 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        This doesn't prorate the change (e.g. paying difference of existing month next time).
It might be noting in this comment the following oddity: although our `StripePaymentMetadataSchema...` classes treat `donor_selected_amount` as a float when representing in revengine, that value gets converted to a string when it's peristed in Stripe's metadata.

2024-11-12 15:05 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        This doesn't prorate the change (e.g. paying difference of existing month next time).
This makes me wonder if we should consider a follow up ticket that refactors our conversion/validation logic for donor selected amount in revengine. 

We could have our pydantic model validate that donor selected amount can be be cast to a float before ultimately storing casting it a string value, which is what its terminal state will be when stored in Stripe metadata.

2024-11-12 15:07 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    # Note that donor_selected_amount is float dollars, not int cents.
The nuance around string conversion also worth noting here.

2024-11-12 15:12 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            if donor_selected_amount and (amount := validated_data.get("amount", None)):
Think we should remove conditionality and just assume that if amount that there is donor selected amount. Add a code comment here that that is expected to be guaranteed by our override of `.validate`, and this code only runs if we have valid data.

2024-11-12 15:19 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            if donor_selected_amount and (amount := validated_data.get("amount", None)):
Also, noting that the conditionality at line 988 shouldn't be required. This update method will only run if the data is valid. See `.handle_patch` in `apps.contributions.views.py`:

```
def handle_patch(self, serializer: serializers.PortalContributionDetailSerializer) -> Response:
        serializer.is_valid(raise_exception=True)
        try:
            serializer.save()
        except stripe.error.StripeError:
            return Response({"detail": "Problem updating contribution"}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
        return Response(serializer.data, status=status.HTTP_200_OK)

```


When .save() gets called, it (by default) calls .update() on the serializer.

2024-11-12 15:23 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            )
Minor, but think it's worthwhile to put this logic into separate named function both so it's self-documenting, and so if we need to add further "late" validation, we can extend that pattern of organizing into separate self-documenting, named functions. 

Otherwise, future maintainer needs to read this entire block of code and then reach the right conclusion that the purpose is to ensure both fields if one is there.

2024-11-12 15:49 UTC, nrh-cklimas commented on apps/contributions/models.py
> +        This doesn't prorate the change (e.g. paying difference of existing month next time).
77b994b336c96ed0edea24c24a686b5039c25846 for docs. I think I'm onboard with beefing up the Pydantic model, but what would happen if the metadata was set to a non-float value externally? Or is that just something we need to live with using Pydantic in general.

2024-11-12 15:49 UTC, nrh-cklimas commented on apps/contributions/serializers.py
> +    # Note that donor_selected_amount is float dollars, not int cents.
77b994b336c96ed0edea24c24a686b5039c25846

2024-11-12 20:17 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            if donor_selected_amount and (amount := validated_data.get("amount", None)):
Looking at this code block more, I see why the conditionality is there at line 988. Looks like I wrote that line, and I'm guessing it's because it's logically possible for validated_data to be an empty dict (we don't stop someone from patching an empty dict since there are no required keys in the serializer for write ops). 

I'm going to close this conversation and will look at that commit in non-stale conversation thread.

2024-11-12 20:23 UTC, benjaminEwhite reviewed
Resolved some of the conversations, and had follow up comments in some others.

2024-11-12 20:48 UTC, nrh-cklimas commented on apps/contributions/models.py
> +        This doesn't prorate the change (e.g. paying difference of existing month next time).
Not sure why it didn't autolink, but try https://github.com/newsrevenuehub/rev-engine/pull/1656/commits/77b994b336c96ed0edea24c24a686b5039c25846. Yes, I meant a user editing manually in the dashboard or something like that.

2024-11-12 20:48 UTC, nrh-cklimas commented on apps/contributions/serializers.py
> +    # Note that donor_selected_amount is float dollars, not int cents.
https://github.com/newsrevenuehub/rev-engine/pull/1656/commits/77b994b336c96ed0edea24c24a686b5039c25846

2024-11-12 20:48 UTC, nrh-cklimas commented on apps/contributions/serializers.py
> +                instance.update_subscription_amount(amount=amount, donor_selected_amount=donor_selected_amount)
I think we need to pop `donor_selected_amount` in any case since it's not a model field?

2024-11-13 18:25 UTC, benjaminEwhite approved these changes
Leaving two conversations around that you can resolve without re-review from me @nrh-cklimas and approving.

2024-11-13 18:25 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        This doesn't prorate the change (e.g. paying difference of existing month next time).
Got it re: external. That makes sense and we'll need to account for it.

I created https://news-revenue-hub.atlassian.net/browse/DEV-5465 as a follow up ticket to pursue this. Do you mind adding as a TODO for this branch?

No need for me to re-review, you can resolve.

2024-11-13 18:25 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +                instance.update_subscription_amount(amount=amount, donor_selected_amount=donor_selected_amount)
Good point. We don't actually need it popped as far as the model is concerned (if i'm not mistaken, you can set arbitrary properties on a model instance and then save it and system won't complain).  But we _do_ need it so we don't send as an update field when calling .save(). 

Think it's worth leaving a code comment for line where donor selected amount is popped from dictionary so it's obvious why we're doing that.

No need for me to re-review to resolve this.

2024-11-13 20:27 UTC, nrh-cklimas commented on apps/contributions/serializers.py
> +                instance.update_subscription_amount(amount=amount, donor_selected_amount=donor_selected_amount)
6a21ad7ceec87fdbd367238d8ca72263bbd07720

2024-11-15 20:34 UTC, njharman requested changes

2024-11-15 20:34 UTC, njharman commented on apps/contributions/tests/test_models.py
> +            one_time_contribution.update_subscription_amount(amount=100, donor_selected_amount=1)
Are `amount `and` donor_selected_amount` required to be identical? All the tests seem to imply so, but I didn't notice any validation for that.

2024-11-15 20:34 UTC, njharman commented on apps/contributions/tests/test_serializers.py
> +
tests 

- for minimum, maximum?
- differing values of amount and donor_selected_amount

2024-11-15 20:34 UTC, njharman commented on apps/contributions/serializers.py
> +                # We can trust that donor_selected_amount is not None because of
`In tests line 1825         updated_contribution = serializer.update(monthly_contribution, {"amount": 123})`

This does not have donor_selected_amount.  Which means it's value is None. So, we can't really trust it, cause .validate() doesn't have to be called before calling .update()?

I'm getting a little lost trying to trace all the code paths. But, it seems the oversight in test (not including donor_selected_amount) should be "caught", no?

2024-11-15 20:34 UTC, njharman commented on apps/contributions/serializers.py
> +                # We can trust that donor_selected_amount is not None because of
That test `def test_update_amount_monthly_contribution `should probably include assert for `donor_selected_amount`

2024-11-15 21:18 UTC, nrh-cklimas commented on apps/contributions/tests/test_models.py
> +            one_time_contribution.update_subscription_amount(amount=100, donor_selected_amount=1)
No, they can and often are different. If the donor chooses to cover fees on a $10 donation, `donor_selected_amount` is `10.0` but `amount` would be `1053` ($10.53). I kept them the same in most tests because both args are required now, but not really relevant to most tests.

2024-11-18 17:06 UTC, nrh-cklimas commented on apps/contributions/serializers.py
> +                # We can trust that donor_selected_amount is not None because of
I talked with Ben about this because it delves in DRF stuff I don't feel that familiar with yet. The feeling I have is, it falls under "things that should never happen in real life", because DRF ensures validate() is called before update(). However, it's still true that update() could be called directly and it will cause data problems if it was. So I added a check in 9a6b8fda35b93ac06b3a2547bd126c9c6d8adfec.

I also added an assertion on `donor_selected_amount` in the test that runs through a successful update in the same commit.

2024-11-19 17:03 UTC, njharman approved these changes

2024-11-19 17:03 UTC, njharman commented on apps/contributions/serializers.py
> +                # We can trust that donor_selected_amount is not None because of
Yeah, I had thought that there was DRF "magic" to ensure data was validated before validated_data could be used.  

Like I thought this was automatically called.  https://www.django-rest-framework.org/api-guide/serializers/#raising-an-exception-on-invalid-data

There's probably a good reason update takes validated_data as parameter instead of using self.validated_data. But seems error prone, as this test showed.

2024-11-19 18:04 UTC, x110dc approved these changes

2024-11-20 19:43 UTC, merged