DEV-5339 | allow superusers to access contributions list endpoint (via API)
newsrevenuehub/rev-engine pull request #1657
Opened 2024-11-08 20:53 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

Changes permissions on portal contributions list view such that superuser's can access the endpoint in order to help debug contributor issues.

#### Why are we doing this? How does it help us?

Better respond to bug reports about portal

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

Yes

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No

#### Have automated unit tests been added? If not, why?

Yes: existing updated

#### How should this change be communicated to end users?

We should create a confluence that explains how to do this (for less technical folks)

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

No, but see above about how to communicate.

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-5449](https://news-revenue-hub.atlassian.net/browse/DEV-5339)

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No

2024-11-10 23:54 UTC, njharman approved these changes

2024-11-13 03:44 UTC, x110dc requested changes
Just one question.

2024-11-13 03:44 UTC, x110dc commented on apps/contributions/views.py
> +        permission_classes=[(IsContributor & UserIsRequestedContributor) | IsActiveSuperUser],
Why not just make this IsHubAdmin so that other members of the staff (like success) could do this as well?

2024-11-14 22:23 UTC, x110dc approved these changes

2024-11-18 20:05 UTC, merged