DEV-5079: Add API error to org update
newsrevenuehub/rev-engine pull request #1658
Opened 2024-11-12 14:50 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
Shows user API error when updating Org Name information
#### Why are we doing this? How does it help us?
Improve error handling and UX, while also removing sentry noise
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
yes
#### Have automated unit tests been added? If not, why?
yes
#### How should this change be communicated to end users?
n/a
#### Are there any smells or added technical debt to note?
no
#### Has this been documented? If so, where?
no
#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-5079
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2024-11-12 20:55 UTC, nrh-cklimas requested changes

2024-11-12 20:55 UTC, nrh-cklimas commented on spa/src/components/base/TextField/TextField.tsx
> +        }
I'm guessing this is to fix a formatting issue with the error message? I'd prefer to fix that on the backend if possible.

2024-11-12 20:55 UTC, nrh-cklimas commented on spa/src/components/settings/Organization/Organization.tsx
> +  const [error, setError] = useState<Partial<OrganizationFormFields> | null>(null);
The naming here is a bit confusing. Let's make line 80:

```tsx
    formState: { errors: formErrors }
```

and here:

```tsx
  const [apiError, setApiError] = useState<Partial<OrganizationFormFields>>({});
```

That way it's clearer below that we're making the form validation errors supercede the API error.

Also in my suggestion, I don't think we need to set it as `null` here to indicate no errors. I think easier to use an empty object--think it should make some of the logic below simpler.

2024-11-12 20:55 UTC, nrh-cklimas commented on spa/src/components/settings/Organization/Organization.tsx
> +        }
```suggestion
      } catch (err) {
        const typedError = err as AxiosError<PatchOrganizationNameErrors>;
        
        if (typedError.response?.data?.name) {
            setError({ companyName: typedError.response.data.name[0] });
            return;
          }
        }
```

2024-11-12 20:55 UTC, nrh-cklimas commented on spa/src/components/settings/Organization/Organization.tsx
> +                helperText={errors?.companyName?.message || error?.companyName}
Prefer `??` on `helperText instead of `||`, since we're trying to coalesce down undefined values.

2024-11-13 17:03 UTC, GuiMend commented on spa/src/components/base/TextField/TextField.tsx
> +        }
Yes. I talked to @benjaminEwhite, and we can use the approach that requires updating the model's custom name.

2024-11-13 17:04 UTC, GuiMend commented on spa/src/components/settings/Organization/Organization.tsx
> +                helperText={errors?.companyName?.message || error?.companyName}
[3137c86](https://github.com/newsrevenuehub/rev-engine/pull/1658/commits/3137c86a95ada8e5ca8e46df1d297090f91b064d)

2024-11-13 17:04 UTC, GuiMend commented on spa/src/components/settings/Organization/Organization.tsx
> +        }
[3137c86](https://github.com/newsrevenuehub/rev-engine/pull/1658/commits/3137c86a95ada8e5ca8e46df1d297090f91b064d)

2024-11-13 17:04 UTC, GuiMend commented on spa/src/components/settings/Organization/Organization.tsx
> +  const [error, setError] = useState<Partial<OrganizationFormFields> | null>(null);
[3137c86](https://github.com/newsrevenuehub/rev-engine/pull/1658/commits/3137c86a95ada8e5ca8e46df1d297090f91b064d)

2024-11-13 17:04 UTC, GuiMend commented on spa/src/components/base/TextField/TextField.tsx
> +        }
[3137c86](https://github.com/newsrevenuehub/rev-engine/pull/1658/commits/3137c86a95ada8e5ca8e46df1d297090f91b064d)

2024-11-14 13:50 UTC, GuiMend commented on spa/src/components/settings/Organization/Organization.tsx
> +        }
I'd rather leave it with the optional chaining, just in case typedError doesn't contain a response object so the code doesn't break.

2024-11-14 14:30 UTC, nrh-cklimas approved these changes

2024-11-14 16:52 UTC, benjaminEwhite requested changes
Migration looks fine. Request for a code comment and a unit test.

2024-11-14 16:52 UTC, benjaminEwhite commented on apps/organizations/models.py
> +        verbose_name_plural = "Organizations"  # Plural custom name
This change is being made so that serialized errors have formatting we want in API layer, yes?  I think it's worth putting a code comment explaining that here.

2024-11-14 16:52 UTC, benjaminEwhite commented on apps/organizations/models.py
> +        verbose_name_plural = "Organizations"  # Plural custom name
If that is indeed the reasoning, think we probably also want a test (either on serializer or on model) around this behavior.

2024-11-15 13:44 UTC, GuiMend commented on apps/organizations/models.py
> +        verbose_name_plural = "Organizations"  # Plural custom name
Done! [625424c](https://github.com/newsrevenuehub/rev-engine/pull/1658/commits/625424c6eeee4fb04035baad58f8d647629a5b4f)

2024-11-15 14:32 UTC, benjaminEwhite approved these changes

2024-11-18 20:27 UTC, merged