DEV-5232: Add First Payment Date to Contribution admin
newsrevenuehub/rev-engine pull request #1662
Opened 2024-11-20 14:01 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
Add First Payment Date to Contribution admin
Remove Created date from Contribution admin
#### Why are we doing this? How does it help us?
To make it match current contributor portal.
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
yes
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
no
#### Have automated unit tests been added? If not, why?
n/a
#### How should this change be communicated to end users?
n/a
#### Are there any smells or added technical debt to note?
no
#### Has this been documented? If so, where?
no
#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-5232
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2024-11-20 14:58 UTC, benjaminEwhite requested changes
Code changes look good. Think it's worthwhile to have a minimal unit test that proves that there's a first payment date column in list view (but I don't think we need to do much beyond that).

2024-11-20 14:58 UTC, benjaminEwhite commented on apps/contributions/admin.py
> +    def lookups(self, request, model_admin):
Minor: please add type hints

2024-11-20 14:58 UTC, benjaminEwhite commented on apps/contributions/admin.py
> +    def queryset(self, request, queryset):
Type hints here as well.

2024-11-22 03:34 UTC, GuiMend commented on apps/contributions/admin.py
> +    def queryset(self, request, queryset):
[f827d8b](https://github.com/newsrevenuehub/rev-engine/pull/1662/commits/f827d8bb9a39005c353bd41e8ceb6c614b1d5e66)

2024-11-22 03:34 UTC, GuiMend commented on apps/contributions/admin.py
> +    def lookups(self, request, model_admin):
[f827d8b](https://github.com/newsrevenuehub/rev-engine/pull/1662/commits/f827d8bb9a39005c353bd41e8ceb6c614b1d5e66)

2024-11-22 20:21 UTC, benjaminEwhite approved these changes
One minor request you can resolve on your own without need for re-review from me @GuiMend

2024-11-22 20:21 UTC, benjaminEwhite commented on apps/contributions/admin.py
> +    def first_payment_date_display(self, obj):
Minor: type hints would also be good here.

Also, instead of returning queryset.annotate, i think you should be able to do `queryset.with_first_payment_date()`

2024-11-26 22:22 UTC, merged