DEV-4404 | Remove old portal backend code
newsrevenuehub/rev-engine pull request #1663
Opened 2024-11-20 19:23 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

Removes a bunch of no longer used code that provided API + caching layer for old portal.

Additionally, opportunistically removes some unrelated, unused fixtures that I came across.

#### Why are we doing this? How does it help us?

Remove dead code. Also, we're still filling cache in status quo when magic links are requested, and there's no need to do that (and it negatively affects review apps, in particular).

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

Yes - basic instructions to go through some standard flows and make sure no regression.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No

#### Have automated unit tests been added? If not, why?

No

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

No

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-4404](https://news-revenue-hub.atlassian.net/browse/DEV-4404)
[DEV-2320](https://news-revenue-hub.atlassian.net/browse/DEV-2320)
[DEV-3987](https://news-revenue-hub.atlassian.net/browse/DEV-3987)
[DEV-2438](https://news-revenue-hub.atlassian.net/browse/DEV-2438)
[DEV-2287](https://news-revenue-hub.atlassian.net/browse/DEV-2287)

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No

[DEV-4404]: https://news-revenue-hub.atlassian.net/browse/DEV-4404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-11-21 16:14 UTC, benjaminEwhite commented on apps/api/tests/test_views.py
> +class TestAuthorizedContributor:
This test needed to change because was pointing at old portal contributions list endpoint. I opportunistically removed dependency on `RevEngineApiAbstractTestCase.

2024-11-21 18:42 UTC, njharman requested changes

2024-11-21 18:42 UTC, njharman commented on apps/contributions/tasks.py
> -def task_pull_serialized_stripe_contributions_to_cache(self, email_id, stripe_account_id):
There is a test `test_task_pull_serialized_stripe_contributions_to_cache` in emails/tests/test_tasks.py

It looks to be testing other stuff.  Suggest to rename test.

2024-11-21 18:42 UTC, njharman commented on apps/contributions/stripe_contributions_provider.py
> -    cache = caches[DEFAULT_CACHE]
revengine/settings/base.py `DEFAULT_CACHE `seems unused.

2024-11-21 18:42 UTC, njharman commented on apps/contributions/views.py
> -        (
[I see security change, I hi-light it for double/re consideration when I don't know enough re implications. ]

Should there be QA around access, verifying owning Contributor still has access?  Or, functional change mentioned in PR/ticket.

2024-11-21 18:42 UTC, njharman commented on apps/contributions/views.py
> -        if isinstance(user, Contributor):
I'm guessing `serializer_class = ...` replaces this?

```
       if isinstance(user, Contributor):
            return self.filter_queryset_for_contributor(user)
```

Checking that the QA regression tests mentioned in ticket cover this case. Seem so, but wonder about owning contributor vs other user

2024-11-21 18:42 UTC, njharman commented on apps/contributions/views.py
> +        logger.warning("Encountered unexpected user")
Suggest adding context such as "identifier" of unknown user

2024-11-21 19:37 UTC, benjaminEwhite commented on apps/contributions/tasks.py
> -def task_pull_serialized_stripe_contributions_to_cache(self, email_id, stripe_account_id):
Great catch. Strange test name!

2024-11-21 21:13 UTC, benjaminEwhite commented on apps/contributions/tasks.py
> -def task_pull_serialized_stripe_contributions_to_cache(self, email_id, stripe_account_id):
Think what I did here makes sense. I broke this up into two tests -- one for send templated email with attachment task, and another for the csv export template. As best I can tell, the earlier test, despite its name was about testing those two units of business logic.

fbbb182eea

2024-11-21 21:15 UTC, benjaminEwhite commented on apps/contributions/stripe_contributions_provider.py
> -    cache = caches[DEFAULT_CACHE]
0a140ea6d

2024-11-21 21:18 UTC, benjaminEwhite commented on apps/contributions/views.py
> -        (
I'll add a QA instruction. We actually want to show the opposite: that contributors cannot access this endpoint. Old portal used this endpoint which for non-contributors got data from db but for contributors pulled into cache from Stripe.  

Contributors have been de-facto blocked from endpoint insofar as the UI is no longer using it, but with this change, contributors will be explicitly prohibited from accessing.

2024-11-21 21:23 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        logger.warning("Encountered unexpected user")
73fa338

2024-11-25 18:32 UTC, njharman approved these changes

2024-11-27 16:33 UTC, x110dc approved these changes
Had one question on a comment that I didn't understand. No need to re-review.

2024-11-27 16:33 UTC, x110dc commented on apps/contributions/views.py
> +        query to Stripe will happen in background, and this will return an empty list).
Is this new comment correct? Stripe won't be called, will it? Nothing is cached, is it?

2024-12-04 14:25 UTC, merged