DEV-5494 | include related contributions via ci contributor.email
newsrevenuehub/rev-engine pull request #1668
Opened 2024-11-26 22:32 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2024-11-27 21:16 UTC, njharman requested changes

2024-11-27 21:16 UTC, njharman commented on apps/contributions/stripe_import.py
> +        return Contributor.objects.create(email=email), common_utils.CREATED
Wouldn't this logging be useful in get_or_create_contributor_for_email().

And if get_or_create_contributor_for_email() used same signature as get_or_crate returning (obj, created) then the duplicate logic/query here could be eliminated.

2024-11-27 21:16 UTC, njharman commented on apps/contributions/serializers.py
> +        if existing := Contributor.objects.filter(email=email).order_by("created").first():
The docstring says insensitive, but the query doesn't seem to do case insensitive query.

And the related test is not verifying case insensitive matching.

2024-12-02 16:35 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +        if existing := Contributor.objects.filter(email=email).order_by("created").first():
Ugg. I moved this logic into its own method at some point, and missed the case insensitivity from original "in-line" implementation.

6d9c8db3687

2024-12-02 17:18 UTC, benjaminEwhite commented on apps/contributions/stripe_import.py
> +        return Contributor.objects.create(email=email), common_utils.CREATED
In bd6b37c0d I added a log to `get_or_create_contributor_for_email` and in 0a871d6fb065 I dried up this logic (and moved it to a static method on Contributor model because seemed weird to have this logic either on serializer or on stripe import).

2024-12-02 18:42 UTC, njharman approved these changes

2024-12-03 20:05 UTC, x110dc approved these changes
Approved with a question about the name of the new method.

2024-12-03 20:05 UTC, x110dc commented on apps/contributions/serializers.py
> +        contributor, _ = Contributor.get_or_create_contributor_for_email(validated_data["email"])
`get_or_create_contributor_by_email` sounds more idiomatic but I don't feel strongly about it

2024-12-03 21:14 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +        contributor, _ = Contributor.get_or_create_contributor_for_email(validated_data["email"])
bc2564b19f

2024-12-05 19:28 UTC, merged