DEV-5388 | API and model changes to support active campaign
newsrevenuehub/rev-engine pull request #1669
Opened 2024-11-27 13:02 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2024-11-27 16:15 UTC, benjaminEwhite commented on apps/contributions/tests/test_views.py
> -    @pytest.fixture
This moved to conftest.py because needed in two places.

2024-12-03 17:29 UTC, benjaminEwhite commented on apps/organizations/views.py
> +            serializer.save()
Serializer.save() calls .update internally, and overridden update on serializer adds update fields.

2024-12-08 20:39 UTC, njharman requested changes

2024-12-08 20:39 UTC, njharman commented on apps/organizations/models.py
> +        logger.info("Publishing RP_ACTIVECAMPAIGN_CONFIGURATION_COMPLETE_TOPIC for rp_id=[%s]", self.id)
Should RP_AC...IC be substituted with the value? The topic name.

Also, FYI, can f-string docstrings. Not useful here cause I don't believe we autogenerate docs from code/docstrings.

2024-12-08 20:39 UTC, njharman commented on apps/organizations/models.py
>      def publish_revenue_program_mailchimp_list_configuration_complete(self):
Should publish_revenue_program_mailchimp_list_confituration_complete also have `if google_cloud_pub_sub_is_configured()`

2024-12-08 20:39 UTC, njharman commented on apps/organizations/models.py
> +        if google_cloud_pub_sub_is_configured():
[I'm probably just confused on how these things interact...]

Shouldn't we include `and activecampaign_integration_connected()` in if clause

2024-12-08 20:39 UTC, njharman commented on apps/organizations/serializers.py
> +    def update_with_update_fields_and_revision(self, instance, validated_data):
+1 should use this all over

Fan of pulling common functionality into tiny, one aspect, mix-ins. Rather than ginormous classes or deep inheritance hierarchies.

2024-12-08 20:39 UTC, njharman commented on apps/organizations/serializers.py
> +        return self.update_with_update_fields_and_revision(instance, validated_data)
Use inheritance, name base class method `update()`. Same other places `update_with_update_fields_and_revision()` is called in `update()` method

Or, am I missing something?

2024-12-08 20:39 UTC, njharman commented on apps/organizations/signals.py
> +                    any(_ in update_fields for _ in ("activecampaign_access_token", "activecampaign_server_url")),
Suggest "x" instead of "_".  Underscore has meaning of "don't care/unused".

Also, another option for "does iterable contain any of these" is to use set intersection.

`set("activecampaign_access_token", "activecampaign_server_url") | set(update_fields)`

2024-12-09 14:28 UTC, benjaminEwhite commented on apps/organizations/migrations/0028_DEV-5388_revenueprogram_activecampaign_server_url.py
> +            field=models.URLField(blank=True, max_length=100, null=True),
4a0db4b39

2024-12-09 14:35 UTC, benjaminEwhite commented on apps/organizations/signals.py
> +                    any(_ in update_fields for _ in ("activecampaign_access_token", "activecampaign_server_url")),
67dd56e082

2024-12-09 15:07 UTC, benjaminEwhite commented on apps/organizations/serializers.py
> +    def update_with_update_fields_and_revision(self, instance, validated_data):
this made me realize that should just call this `.update` and then can rely on inheritance so it gets called in normal flow, and not need to call this bespoke method.

b0102cdd87

2024-12-09 15:08 UTC, benjaminEwhite commented on apps/organizations/serializers.py
> +        return self.update_with_update_fields_and_revision(instance, validated_data)
Yeah, good point. b0102cdd87

2024-12-09 15:10 UTC, benjaminEwhite commented on apps/organizations/models.py
> +        if google_cloud_pub_sub_is_configured():
IMO, it's not necessary.  While in principle this method could get called elsewhere, it's intended to be called in context of `handle_rp_activecampaign_setup`, and that signal already checks if it's connected.

2024-12-09 21:47 UTC, njharman approved these changes

2024-12-09 21:47 UTC, njharman commented on apps/organizations/models.py
> +        if google_cloud_pub_sub_is_configured():
I'm defensive, belts and suspenders type programmer.

2024-12-09 21:47 UTC, njharman commented on apps/organizations/serializers.py
> +    activecampaign_server_url = serializers.URLField(max_length=100, required=False)
Cut max_length=100 (or set to default of 200) to match model field.

2024-12-10 14:35 UTC, benjaminEwhite commented on apps/organizations/serializers.py
> +    activecampaign_server_url = serializers.URLField(max_length=100, required=False)
Good catch!

2024-12-10 14:39 UTC, benjaminEwhite commented on apps/organizations/serializers.py
> +    activecampaign_server_url = serializers.URLField(max_length=100, required=False)
be5859495

2024-12-10 19:21 UTC, x110dc approved these changes
Approved.

2024-12-17 15:48 UTC, merged