DEV-5524 | API endpoint for retrieving, creating, and updating contributors from switchboard
newsrevenuehub/rev-engine pull request #1670
Opened 2024-12-04 19:19 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2024-12-05 16:31 UTC, benjaminEwhite commented on apps/contributions/tests/views/test_views.py
No substantive changes to these tests.

2024-12-05 16:32 UTC, benjaminEwhite commented on apps/contributions/views/checkout.py
No substantive changes, just moved.

2024-12-05 16:33 UTC, benjaminEwhite commented on apps/contributions/views/orgs.py
No substantive changes.

2024-12-05 16:33 UTC, benjaminEwhite commented on apps/contributions/views/portal.py
No substantive changes.

2024-12-05 16:33 UTC, benjaminEwhite commented on apps/contributions/views/webhooks.py
No substantive changes.

2024-12-06 15:38 UTC, benjaminEwhite commented on apps/contributions/views.py
Broken up into:

- ../views/checkout.py
- ../views/orgs.py
- ../views/portal.py
- ../views/switchboard.py
- ../views/webhooks.py

2024-12-06 15:38 UTC, benjaminEwhite commented on apps/contributions/views/webhooks.py
No net changes, just moved.

2024-12-08 19:41 UTC, njharman requested changes

2024-12-08 19:41 UTC, njharman commented on apps/api/views.py
> +    By default DRF uses `Token` in the hezder instead of `Bearer` but the value is the same.
hezder typo

2024-12-08 19:41 UTC, njharman commented on apps/api/views.py
> +        logger.info("Request received for user (%s)", request.user)
If data such as url is not automagically included in log, consider adding url or unique string so logs can be more easily grepped for this internal security endpoint.

2024-12-08 19:41 UTC, njharman commented on apps/contributions/urls.py
> +)
Obviously you thought appending `_views` was clearer. Seems, unneeded in such a short file as urls.py. Adds verbosity, which is less clear to me.

It would be worse to name the files something like `contributions/views/webhook_views.py`

If you don't want to have "bare" `switchboard`, `wehooks `etc imported from views, consider 

```
from apps.contributions import views

router.register(r"contributions", views.orgs.ContributionsViewSet, basename="contribution")
```

2024-12-08 19:41 UTC, njharman commented on apps/contributions/views/switchboard.py
> +# Note: will this even work without CSRF being passed? Who's calling this?
This comment seems like "note to self". Should be revised, checked, explained, deleted, follow up ticket.

2024-12-08 19:41 UTC, njharman commented on apps/contributions/views/switchboard.py
> +            return Response(
I believe attempting to create existing contributor is an expected occurrence.

If not, consider info/warn log.

2024-12-09 15:18 UTC, benjaminEwhite commented on apps/api/views.py
> +    By default DRF uses `Token` in the hezder instead of `Bearer` but the value is the same.
7852cead

2024-12-09 15:32 UTC, benjaminEwhite commented on apps/contributions/urls.py
> +)
The approach you suggested doesn't work out (`AttributeError: module 'apps.contributions.views' has no attribute ...`), but I made this change to address:  38fc1376

2024-12-09 15:33 UTC, benjaminEwhite commented on apps/contributions/views/switchboard.py
> +# Note: will this even work without CSRF being passed? Who's calling this?
702a8b241

2024-12-09 15:37 UTC, benjaminEwhite commented on apps/contributions/views/switchboard.py
> +            return Response(
Correct: it's expected occurrence.

2024-12-10 19:58 UTC, x110dc requested changes
Added more comments in Jira.

2024-12-10 19:58 UTC, x110dc commented on revengine/settings/base.py
>  # and dtm complains about their migration file names
missing word "ignore"?

2024-12-10 19:58 UTC, x110dc commented on apps/contributions/urls.py
> +    r"switchboard-contributions", switchboard.SwitchboardContributionsViewSet, basename="switchboard-contribution"
why "switchboard-contributors" and not "switchboard/contributors"?

2024-12-10 19:58 UTC, x110dc commented on apps/contributions/views/switchboard.py
> +    """Viewset for switchboard to update contributions."""
I don't see anything in the ticket or the PR description about contributions, just contributors. If this is new, why is it here?

2024-12-10 20:22 UTC, benjaminEwhite commented on apps/contributions/views/switchboard.py
> +    """Viewset for switchboard to update contributions."""
It's not new, just shows up in diff because part of file/folder restructuring noted in PR description.

See https://github.com/newsrevenuehub/rev-engine/blob/bdf5bc651c878fc98757a29763532bddb4801314/apps/contributions/views.py#L308C1-L312C34 in main.

2024-12-10 20:25 UTC, benjaminEwhite commented on apps/contributions/urls.py
> +    r"switchboard-contributions", switchboard.SwitchboardContributionsViewSet, basename="switchboard-contribution"
That's slated to happen in [DEV-5534](https://news-revenue-hub.atlassian.net/browse/DEV-5534) where we'll consolidate both switchboard facing views under `api/v1/switchboard/...` .

In short term, i repeated the existing URL structure for the contributions endpoint.

2024-12-10 22:03 UTC, benjaminEwhite commented on revengine/settings/base.py
>  # and dtm complains about their migration file names
dfa0b0bfab

2024-12-12 15:39 UTC, benjaminEwhite commented on apps/api/permissions.py
> +    def user_has_permission(cls, user: User) -> bool:
This is here because it was useful to reuse in our auth token login view `SwitchboardLoginView.post` (where it will not work as the `permission_class` because we need to initially authenticate using provided credentials and then ask if it's switchboard or not).

2024-12-12 16:25 UTC, benjaminEwhite commented on apps/contributions/urls.py
> +    basename="switchboard-contribution-deprecated",
We're changing base-name here to reflect that this will be replaced by canonical `switchboard_router.register(r"contributions", SwitchboardContributionsViewSet, basename="switchboard-contribution")`.

2024-12-12 16:34 UTC, benjaminEwhite commented on apps/contributions/views/switchboard.py
> +    authentication_classes = [TokenAuthentication, JWTHttpOnlyCookieAuthentication]
This TODO is net new, as is the addition of the authentication class overrides. Adding JWTHttpOnlyCookieAuthentication makes this work with status quo, and adding TokenAuthentication will be forward compatible when we transition to using only token auth in followup ticket for SB.

2024-12-12 20:50 UTC, x110dc requested changes
Requested changes.

2024-12-12 20:50 UTC, x110dc commented on apps/contributions/views/switchboard.py
> +    authentication_classes = [TokenAuthentication, JWTHttpOnlyCookieAuthentication]
I don't think there's a requirement that this endpoint work with the old auth method. Since this hasn't been implemented on Switchboard yet, when it is it can use the bearer/token auth.

2024-12-12 21:56 UTC, benjaminEwhite commented on apps/contributions/views/switchboard.py
> +    authentication_classes = [TokenAuthentication, JWTHttpOnlyCookieAuthentication]
Good catch.

62f322957da0

2024-12-13 19:14 UTC, x110dc approved these changes

2024-12-16 16:22 UTC, merged