DEV-5493: Stripe metadata v1.6
newsrevenuehub/rev-engine pull request #1686
Opened 2024-12-26 17:10 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
Add support for metadata schema 1.6 on rev engine
#### Why are we doing this? How does it help us?
Add support for metadata schema 1.6 on rev engine
#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?
tbd
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
no
#### Have automated unit tests been added? If not, why?
yes
#### How should this change be communicated to end users?
n/a
#### Are there any smells or added technical debt to note?
no
#### Has this been documented? If so, where?
no
#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-5493
#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:
no
#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2024-12-30 15:06 UTC, benjaminEwhite requested changes

2024-12-30 19:59 UTC, benjaminEwhite approved these changes

2024-12-30 21:31 UTC, x110dc requested changes

2024-12-30 21:31 UTC, x110dc commented on apps/contributions/types.py
> +    marketing_consent: bool | None = None
Right, it's only on Customer.

2024-12-30 21:31 UTC, x110dc commented on apps/contributions/types.py
> +    frequency: Literal["one-time", "monthly", "yearly"]
frequency is valid only on setup intents. I've updated the sheet to indicate that most of the rest (except marketing_consent) apply to Subscriptions and Payment Intents.

2025-01-02 22:58 UTC, x110dc requested changes
This looks okay, but I don't see schema definitions for Setup Intent or Customer. Are those just not relevant for RevEngine?

2025-01-02 22:59 UTC, x110dc requested changes

2025-01-02 22:59 UTC, x110dc commented on apps/contributions/types.py
> +    @pydantic.field_validator("agreed_to_pay_fees", "marketing_consent")
Don't need the marketing consent validator here.

2025-01-06 23:01 UTC, benjaminEwhite commented on apps/contributions/types.py
> +    @pydantic.field_validator("agreed_to_pay_fees", "marketing_consent")
1c3c3095ae

2025-01-08 14:32 UTC, merged