[NRH-330] Footer RevProgram name, email
newsrevenuehub/rev-engine pull request #179
Opened 2021-08-30 17:50 UTC by michael-caktus

#### What's this PR do?
Replaces org name in footer content with rev program name, removes field organization.contact_email, adds revenue_program.contact_email and uses it in footer as well.

#### How should this be manually tested?
Check footer content for above changes.

#### Do any changes need to be made before deployment to staging? production? (adding environment variables, for example)?
No.

2021-09-01 20:58 UTC, JeremyGibson commented on apps/common/models.py
> +        return f"{self.address1}{address2}, {self.city}, {self.state}{postal_code}"
__str__ is typically used for humans, and __repr__ is for machine consumption.  Since it looks like you are using this further down the line to send to the frontend. I would put this in the `__repr__` and I would have the string offer a bit more context like `return f"{self.organization}: {self.city} {self.state}"`. It's not a big deal but just a tad more pythonic.

2021-09-01 20:59 UTC, JeremyGibson commented on apps/organizations/serializers.py
> +            return str(obj.address)
if you like the suggestion above `repr(obj.address)`

2021-09-01 21:01 UTC, JeremyGibson commented on spa/cypress/integration/donation-page.spec.js
> +  describe.only('Donation page side effects', () => {
remove the only

2021-09-01 21:02 UTC, JeremyGibson requested changes
I'm fine if you want to keep the str representation in address. 

The `only` should be removed. 

And I am curious about the renaming of ModelAdmin to admin.ModelAdmin.

2021-09-02 18:45 UTC, michael-caktus commented on apps/common/admin.py
> +class RevEngineBaseAdmin(admin.ModelAdmin):
Ah, accident. Leftover from a change that I ended up removing. Switching it back.

2021-09-02 18:50 UTC, michael-caktus commented on apps/common/models.py
> +        return f"{self.address1}{address2}, {self.city}, {self.state}{postal_code}"
It sounds like by that convention **str** should be okay here, since it's going out to the user. One problem with providing more context is that we don't know if this Address is related to an Org or a RevProgram. Thoughts?

2021-09-02 19:03 UTC, JeremyGibson commented on apps/common/models.py
> +        return f"{self.address1}{address2}, {self.city}, {self.state}{postal_code}"
If it could be either, perhaps a simple check f"{self.organization if self.organization else self.rev_program}: ..." I mostly just concerned with looking through these objects in the shell later on down the road and all we see is just the address. Not a big deal in the grand scheme.

2021-09-02 19:21 UTC, JeremyGibson approved these changes

2021-09-03 13:16 UTC, merged