[NRH-280] Social metatags
newsrevenuehub/rev-engine pull request #205
Opened 2021-09-08 16:21 UTC by michael-caktus

Before merging to develop:
- [ ] Previous bugs fixed?
- [ ] Release created?

#### What's this PR do?
Adds some social media metatag fields to revenue program in the admin.
Adds <meta> tags for OG and twitter crawlers. Uses rev program values or defaults.

#### How should this be manually tested?
You can inspect the head of the donation page for meta tags. Or you can visit the [facebook share debugger](https://developers.facebook.com/tools/debug/) or the [twitter card validator](https://cards-dev.twitter.com/validator).

#### Do any changes need to be made before deployment to staging? production? (adding environment variables, for example)?
No

2021-09-13 13:35 UTC, JeremyGibson requested changes
Looks to be missing configurable twitter handle.

2021-09-13 13:35 UTC, JeremyGibson commented on spa/src/components/donationPage/DonationPageRouter.js
> +          console.log('that org stripe id: ', responseData);
extra console logs

2021-09-13 13:35 UTC, JeremyGibson commented on apps/common/models.py
> +    card = SorlImageField(null=True, blank=True)
From the AC it looks like this is missing a twitter handle

2021-09-14 13:38 UTC, michael-caktus commented on apps/common/models.py
> +    card = SorlImageField(null=True, blank=True)
`twitter_handle` was added to RevProgram in a previous ticket.

2021-09-14 15:09 UTC, JeremyGibson approved these changes

2021-09-30 18:49 UTC, merged