News revenue hub  sc 3591 set hub strip publishable key as environment
newsrevenuehub/rev-engine pull request #271
Opened 2021-11-18 21:05 UTC by LorienOlive

#### What's this PR do?
This PR adds all of the front-end env vars to the django app and to the Heroku account, to be set on the window via a django request on the index.html of the React app.

#### How should this be manually tested?
Start up python server and navigate to localhost:8000 check window object to see if .ENV object is present.

#### Do any changes need to be made before deployment to staging? production? (adding environment variables, for example)?
Please review to ensure I've included all necessary config vars.  I wasn't able to find a Google Analytics ID, for example.

2021-11-18 23:09 UTC, LorienOlive commented on revengine/views.py
> +
Not certain I'm doing this correctly.

2021-11-18 23:10 UTC, LorienOlive commented on spa/public/index.html
> +
hypothetically the json_script should generate a new script tag, the contents of which can be read by the next script tag, but it's not working properly locally at least.

2021-11-19 14:25 UTC, JeremyGibson commented on revengine/views.py
> +
No you will need to add the SPA_ENV_VARS to a context variable after the call to super(). 

context['SPA_ENV_VARS'] = self._serve_spa_env_vars()

or without the function call:

context['SPA_ENV_VARS'] = json.dumps(settings.SPA_ENV_VARS)

2021-11-19 19:37 UTC, michael-caktus requested changes

2021-11-19 19:37 UTC, michael-caktus commented on spa/.gitignore
> +.envrc
Isn't this redundant? This is already in /.gitignore, right? There shouldn't be an .envrc in /spa, as far as I know.

2021-11-19 19:37 UTC, michael-caktus commented on spa/public/index.html
> +
Alas, this won't work in a deployed environment. Both of the script tags used here need a "nonce=<that nonce tho>" attribute. Easy enough to add it to the script on line 20, but there doesn't seem to be a way to add arbitrary attributes to the script generated by `json_script`. We _can_, however,  create our own template filter (`json_script` is one of those) that wraps `json_script` and allows us to add the nonce. And maybe even does a little bit more.

2021-11-19 19:37 UTC, michael-caktus commented on spa/src/ajax/axios.js
> +import { REACT_API_VERSION } from 'constants/genericConstants';
I think `REACT_API_VERSION` here should be `REVENGINE_API_VERSION` or something like that. This is the version of the backend API that the frontend should be hitting.

2021-11-19 19:37 UTC, michael-caktus commented on spa/src/constants/analyticsConstants.js
> +// export const { HUB_V3_GOOGLE_ANALYTICS_ID: HUB_GA_V3_ID } = process.env;
I think the comments in this file apply to this PR-- we should set line 8 (not visible here), which is:
```export const HUB_GA_V3_ID = NONSENSICAL_HUB_GA_V3_ID;```

to 

```export const HUB_GA_V3_ID = window.ENV.HUB_V3_GOOGLE_ANALYTICS_ID;```

2021-11-19 19:37 UTC, michael-caktus commented on revengine/settings/base.py
> +}
Need to also add `HUB_V3_GOOGLE_ANALYTICS_ID` here.

2021-11-19 19:37 UTC, michael-caktus commented on revengine/settings/base.py
> +    "REACT_API_VERSION": os.getenv("SPA_ENV_REACT_API_VERSION"),
See `REACT_API_VERSION` = `REVENGINE_API_VERSION` comment below.

2021-11-19 21:08 UTC, LorienOlive commented on spa/.gitignore
> +.envrc
yeah. that's weird. sorry.

2021-11-29 18:20 UTC, michael-caktus approved these changes

2021-11-29 18:22 UTC, michael-caktus commented
Approved, aside from the test failure and merge conflict. Then, onward!

2021-11-30 15:20 UTC, michael-caktus commented
I think the failure is misleading-- I think the actual failure here is this:
`> Cannot read properties of undefined (reading 'HUB_GOOGLE_MAPS_API_KEY')`

In test, window.ENV is undefined. We might set window.ENV to {{ spa_env }} || {}, or just make all the refs to window.ENV look like this `window.ENV?.MY_ENV_VAR`

2021-11-30 20:09 UTC, merged