Create componentLoader util and ChunkErrorBoundary component + styles
newsrevenuehub/rev-engine pull request #285
Opened 2021-12-03 18:48 UTC by LorienOlive

#### What's this PR do?
Creates a custom component loader to handle chunk loading errors from code splitting as well as an error boundary that shows the error and reloads the page.

#### How should this be manually tested?
You can try to test locally, I can provide the settings for throttling, though I was never able to trigger it.  My guess is that it must be tested in a deployed environment.

#### Do any changes need to be made before deployment to staging? production? (adding environment variables, for example)?

2021-12-14 14:42 UTC, michael-caktus requested changes

2021-12-14 14:42 UTC, michael-caktus commented on spa/src/components/errors/ChunkErrorBoundary.js
> +  const [message, setMessage] = useState();
This doesn't seem to get used anywhere. Leftovers from a previous iteration?

2021-12-14 14:42 UTC, michael-caktus commented on spa/src/components/errors/ChunkErrorBoundary.js
> +  };
This seems to be called, but to no effect.

2021-12-14 14:42 UTC, michael-caktus commented on spa/src/components/errors/ChunkErrorBoundary.js
> +                handleReset('An error has occurred');
This can probably be removed-- it doesn't appear to do anything anymore
```suggestion
```

2021-12-14 14:42 UTC, michael-caktus commented on spa/src/components/errors/ChunkErrorBoundary.js
> +                resetError();
From what I can tell, resetError will try to render the children of the ErrorBoundary, but I don't think it will try to re-import them.  When I run this locally it renders a blank page without an error (but that could be because of the way I'm triggering an error)

2021-12-14 14:42 UTC, michael-caktus commented on spa/src/utilities/componentLoader.js
> +const componentLoader = (lazyComponent, attemptsLeft = 3, interval = 1000) => {
Love this! Might not be unreasonable to bump the number of attempts up to 5 or even 10. This doesn't use a lot of resources.

2021-12-14 14:42 UTC, michael-caktus commented on spa/src/utilities/componentLoader.js
> +          componentLoader(lazyComponent, attemptsLeft - 1, interval).then(resolve, reject);
What if we do interval * 1.5 or something, to give it that exponential backoff feeling? We'd probably want to cap the attempts at 5 or so if we did that, counter to what I said above

2022-01-07 22:47 UTC, LorienOlive commented
Hey Michael,  So I reviewed all of these.  In summary, my main goal was to just get this into staging and see if I could catch a chunk loading error in the wild. But if you'd rather have the code be as close to complete as possible before merging into staging (understandable).  I can make a local test branch with the extra code for local testing, so it's there in case I need to fix anything further.  I'll work on this first thing Monday.

2022-01-14 12:51 UTC, michael-caktus requested changes

2022-01-14 12:51 UTC, michael-caktus commented on spa/src/components/errors/ChunkErrorBoundary.js
> +const ChunkErrorFallback = (error) => {
error prop not used here

2022-01-14 12:51 UTC, michael-caktus commented on spa/src/components/errors/ChunkErrorBoundary.js
> +    <Sentry.ErrorBoundary fallback={({ error }) => ChunkErrorFallback(error)}>{props.children}</Sentry.ErrorBoundary>
I think we can jsut do this:

```suggestion
    <Sentry.ErrorBoundary fallback={<ChunkErrorFallback />}>{props.children}</Sentry.ErrorBoundary>
```

Or something like it.

2022-01-14 12:51 UTC, michael-caktus commented on spa/src/components/errors/ChunkErrorBoundary.js
> +          <h2>😰 We've encountered a problem!</h2>
I personally love emojis on websites, but I'm guessing this isn't the right tone for Hub.

2022-01-17 20:08 UTC, LorienOlive commented
@michael-caktus re:  emoji.  I'm kinda literal brained, so I use the content you gave me, esp since I'm not as familiar with the client as you are.  Just an fyi for the future.

2022-01-18 15:44 UTC, merged