#11349 add required static disclaimer text
newsrevenuehub/rev-engine pull request #301
Opened 2022-01-20 21:34 UTC by michael-caktus

#### What's this PR do?
Implements [this basecamp todo item](https://3.basecamp.com/3120230/buckets/21497549/todos/4500174537). Specifically:
Adds some different text below the submit button on donation pages. This text will remain static even after we introduce a "new page template" that includes some small-print near this section.

#### How should this be manually tested?
View a donation page and observe the text. Notice how it changes when you change the amount, frequency, or payFees toggle.

#### Do any changes need to be made before deployment to staging? production? (adding environment variables, for example)?
No

2022-01-24 16:04 UTC, benjaminEwhite requested changes

2022-01-24 16:04 UTC, benjaminEwhite commented on spa/src/test-server.js
> +  // Log unhanlded requests for debugging.
```suggestion
  // Log unhandled requests for debugging.
```

2022-01-24 16:04 UTC, benjaminEwhite commented on spa/src/test-utils.js
> +import * as rtl from '@testing-library/react';
Doesn't look like this is used anywhere, and unclear how related to the narrow scope of this PR.

2022-01-25 15:38 UTC, benjaminEwhite commented on spa/src/components/analytics/Analytics.spec.js
> -import React, { useEffect } from 'react';
@michael-caktus dug into this, and it looks like this is the only place we're testing the Facebook conversion tracking functionality. The other analytics are about page views specifically, and as you pointed out, are in fact tested by Cypress. This one is narrowly about testing FB conversion, and should probably stay.

2022-01-26 13:02 UTC, michael-caktus commented
@benjaminEwhite there's a PR before this one that this branch is based from that includes all the test related stuff separately.

2022-01-26 14:17 UTC, benjaminEwhite commented
@michael-caktus i had missed that PR. Just added comments about the analytics test (and a couple other small test-related things) on the other one.

2022-01-27 14:09 UTC, michael-caktus commented on spa/src/components/analytics/Analytics.spec.js
> -import React, { useEffect } from 'react';
Thanks for looking in to that-- I've restored the test in the originating branch.

2022-01-27 16:55 UTC, benjaminEwhite approved these changes
Approved the test-related PR which addresses comments here.

2022-01-27 20:16 UTC, merged