Dev 1092 pay fee toggle
newsrevenuehub/rev-engine pull request #336
Opened 2022-03-11 05:31 UTC by gurjittoptal

#### What's this PR do?
The pay toggle section is moved out of stripe-section thats hidden.
ref
https://news-revenue-hub.atlassian.net/browse/DEV-1092

#### How should this be manually tested?
Check on safari(iPhone) and Chrome(Android Phone)

#### Do any changes need to be made before deployment to staging? production? (adding environment variables, for example)?
No

Before
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/30353391/157808142-82f10d60-53da-403a-8356-364b64964958.png">

After this PR
<img width="922" alt="image" src="https://user-images.githubusercontent.com/30353391/157808197-838e2b26-95f8-420d-b811-5dfa865a6cc2.png">

2022-03-11 23:11 UTC, x110dc requested changes
- I think we'd like the "pay fees" toggle to remain before the submit button. 
- We also need to confirm that it is usable and visible regardless of the type of button. It should be fairly easy to test with Google Pay and Browser-Saved cards, but Apple Pay is tougher because it won't show outside of production.

2022-03-16 18:30 UTC, gurjittoptal commented
This was updated. Toggle is duplicated in the two sections. ( single line change now )

2022-03-17 14:48 UTC, benjaminEwhite approved these changes
Code looks good to me 👍

2022-03-30 19:54 UTC, x110dc approved these changes

2022-03-30 21:19 UTC, merged