use NODE_ENV instead of domain
newsrevenuehub/rev-engine pull request #337
Opened 2022-03-11 11:12 UTC by harsha09

#### What's this PR do?
Shows up only a handful environments in Sentry.

#### How should this be manually tested?

#### Do any changes need to be made before deployment to staging? production? (adding environment variables, for example)?

2022-03-15 19:09 UTC, x110dc requested changes

2022-03-17 20:08 UTC, x110dc approved these changes
LGTM.

2022-03-18 13:14 UTC, benjaminEwhite approved these changes
This looks good to me.

2022-03-18 13:14 UTC, benjaminEwhite commented on spa/src/settings.js
> +export const ENVIRONMENT = resolveConstantFromEnv('ENVIRONMENT');
Should this also pass in a default value for second argument? That's a genuine question -- it's fine if the answer is no, I just saw that `resolveConstantFromEnv` can take a default value.

2022-03-18 13:26 UTC, harsha09 commented on spa/src/settings.js
> +export const ENVIRONMENT = resolveConstantFromEnv('ENVIRONMENT');
I've removed the default value here as it get's the default value from Django's `ENVIRONMENT` env variable, which makes sense to me.

2022-03-21 22:20 UTC, merged