[DEV-699] Introduce roles and use them to programmatically manage access to orgs, rev programs, and other data models
newsrevenuehub/rev-engine pull request #345
Opened 2022-03-15 15:56 UTC by benjaminEwhite

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

NA

#### What's this PR do?

- Introduces role-based access for the primary resources exposed through the REST API.
- Introduces three new user roles: 
  - Hub admin - prototypically can CRUD everything
  - Org admin - prototypically can CRUD only things belonging to their org
  - Revenue program admin - prototypically can CRUD only things belonging to their RPs
- Allows role assignments to be managed in Django admin. Role assignments connect a user, a role type, an organization, and a set of revenue programs.
- Adds custom testing mixins that provide extensive domain model data setup and convenient test assertions to standardize testing the API in light of permissions
- Extensively tests CRUD operations for each role type, plus superusers (and in some places, authed users and contributor users) for most API resources.

#### Why are we doing this? How does it help us?

Documented extensively in the related JIRA ticket

#### How should this be manually tested?

In test environment, go to Django admin. Assuming it's already populated with org/rp/page etc. data, create different users with different role types, and interact with the API via postman, authenticating as each distinct user.

In theory, this can also be tested by logging in to the SPA as, say, a revenue program admin and looking at the contributions list. You should only see contributions listed for your rps.  This pattern is true for any of the resources listed in the SPA admin.

#### Have automated unit tests been added?

- Adds custom testing mixins that provide extensive domain model data setup and convenient test assertions to standardize testing the API in light of permissions
- Extensively tests CRUD operations for each role type, plus superusers (and in some places, authed users and contributor users) for most API resources.
- Adds some tests in otherwise untouched code in order to get coverage > 95%

#### How should this change be communicated to end users?

NA

#### Are there any smells or added technical debt to note?

NA

#### Has this been documented? If so, where?

#### What are the relevant tickets?
**(Note: Please use syntax [JIRA-123] to link any relevant tickets)**

[DEV-699]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them?

**(Note: Please use syntax [JIRA-123] to link any relevant tickets)**

2022-03-17 21:35 UTC, njharman requested changes
Various in line comments and 

Coverage
FAIL Required test coverage of 95% not reached. Total coverage: 93.87%

CI failures

-   build_test_python The hosted runner: GitHub Actions 10 lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
 -  js_test  Same error

Big commit/unfamiliar/etc... 
I did not see user with no roles is denied all these things (which I also didn't see as acceptance criteria). But seems that case handled by this, eh? But also see some endpoints set classes to [] which overrides this default, right?

  "DEFAULT_PERMISSION_CLASSES": [
          "apps.api.permissions.HasRoleAssignment",

2022-03-17 21:35 UTC, njharman commented on apps/pages/serializers.py
> +            raise serializers.ValidationError({"rp_slug": "RevenueProgram.slug is required when creating a new page"})
"rp_slug" -> f"{settings.RP_SLUG_PARAM}" . 
Maybe same with the RP not found below

unless you meant f"{rp_slug}" ???  Which I like even less.

2022-03-17 21:35 UTC, njharman commented on apps/pages/serializers.py
> +    # revenue_program_pk = serializers.IntegerField(allow_null=True, required=False)
add comment why commented out or delete.

2022-03-17 21:35 UTC, njharman commented on apps/pages/serializers.py
>              raise serializers.ValidationError({"revenue_program_pk": "Could not find revenue program with provided pk"})
same as above re: rp_slug, revenue_program_pk

2022-03-17 21:35 UTC, njharman commented on apps/public/permissions.py
> +        return hasattr(request.user, "is_active") and request.user.is_active and request.user.is_superuser
minor, the test if obj has attr and that attr is truthy can be simplifed to getattr with default

`getattr(obj, attar, False)`

2022-03-17 21:35 UTC, njharman commented on apps/users/forms.py
> +                ] = f"The following RevenuePrograms do not belong to your chosen Org: {', '.join([rp.name for rp in mismatched_rps])}"
Is there security/privacy concern showing non-owned RP names?

2022-03-17 21:35 UTC, njharman commented on apps/users/forms.py
> +    # class Media:
Add comment why commented out or delete.

2022-03-17 21:35 UTC, njharman commented on apps/users/management/commands/bootstrap-review-app.py
> +            self.stdout.write("**Not running bootstrap tasks**")
Helpful to user running to explain why,  either not "review env" or "qatester exits.

2022-03-17 21:35 UTC, njharman commented on apps/users/models.py
> +    role_type = models.CharField(max_length=max(len(x) for x in Roles.values), choices=Roles.choices)
Rusty on django, help me out. I'm queasy about dynamically generated model field parameter

Will the db migration generator tool (forget name, South?) detect and create migration to change size if we add a longer role?

[Also with Postgres having tight max_length doesn't get you anything (re storage) and I think it silently truncates.  you do get validation on the django side. I guess I'm asking why not just max_length 20 or 40]

2022-03-17 21:35 UTC, njharman commented on apps/users/serializers.py
> +    """
Thank you!

2022-03-17 21:35 UTC, njharman commented on revengine/settings/base.py
> +            "level": "DEBUG",
Was this intentential commit to change debug level, or forgotten local edit?

2022-03-18 13:33 UTC, benjaminEwhite commented on apps/contributions/views.py
> +    organization_slug = request.GET.get(settings.ORG_SLUG_PARAM, None)
I don't disagree, but I'm reluctant to start pulling threads like that on this PR because it's already big, and that's additional scope creep.

2022-03-18 13:38 UTC, benjaminEwhite commented on apps/users/forms.py
> +                ] = f"The following RevenuePrograms do not belong to your chosen Org: {', '.join([rp.name for rp in mismatched_rps])}"
I believe these would be submitted by the user (they come from the form submission), and not generated by the server, so there shouldn't be a security concern.

2022-03-18 13:40 UTC, benjaminEwhite commented on apps/users/models.py
> +    role_type = models.CharField(max_length=max(len(x) for x in Roles.values), choices=Roles.choices)
I believe the Django's migration capabilities would catch the change, but I agree, @njharman I'm not a fan of the dynamic generation of the role type. I'm going to update.

2022-03-18 13:46 UTC, benjaminEwhite commented on revengine/settings/base.py
> +            "level": "DEBUG",
Good question. I'm guessing it's forgotten local edit (from previous dev), and at any rate it's not clearly tied to narrow scope of this PR, so will revert this change.

2022-03-18 13:56 UTC, benjaminEwhite commented on apps/organizations/views.py
> +    permission_classes = [ReadOnly]
Good to have pause on this. I'm going to ask about the business logic for this, because I'm not entirely certain.

2022-03-18 14:48 UTC, benjaminEwhite commented on apps/pages/models.py
> +        merged_page = template if template else page
Ohhhhh, yeah that makes a lot more sense. It also explains the failing test i was getting which prompted me to make this change. I was getting a test failing where creating a page from template was causing the name field to not be set correctly, IIRC. 

Personally, I find the starkwargs syntax less ambiguous, and it also resembles object-destructuring syntax in Javascript, so for full stack folks, it might make it a bit more intuitive sense. 

At the same time, I simply wasn't aware of this usage of the `|` operator which appears to have come with Python 3.9. I'm open to using it. As you can see, my intuitive read of `|` here as "or" was wrong, so that's an interesting small fact.

2022-03-18 14:57 UTC, benjaminEwhite commented on apps/pages/models.py
> +        merged_page = template if template else page
Oh wait. According to pyproject.toml, we're targeting 3.8 currently, so the `|` won't work here. Indeed, I get failing tests locally because of this.

There's another example of this in make_template_from_page that I need to take a look at.

2022-03-18 15:27 UTC, benjaminEwhite commented
@njharman I responded/made commits based on your inline comments.

Re, coverage: I mentioned in the opening comments for this PR where there were some gaps in testing (and that was without realizing we weren't hitting the coverage min threshold we have set). Running `coverage -m`, it looks like `apps/api/permissions` only has 76% coverage. I think the best way to up that coverage is through API testing of resources that use the permissioning system -- which would mean additional API integration tests for some of the viewsets with using different RoleAssignments.


Re: CI failures, I'll go have a look. I know that there were some issues with the GitHub API yesterday, so that may account for what you were seeing.

RE: user with no roles. There are default permissions set in revengine/settings/base.py for IsAuthenticated and HasRoleAssignment.  You rightly point out that some views override/reset default permissions. I've tried to go through and look at each view and ask "Do the permissions on this view make sense based on my understanding of the app?". In a few places I tightened permissions based on this.

All of that said, it's entirely possible I missed something. If any specific resources need to be more tightly secured, we can do that.

2022-03-18 22:15 UTC, x110dc requested changes
The PR section titled "How should this be manually tested?" is blank. Can you fill that out please?

2022-03-18 22:15 UTC, x110dc commented on apps/users/management/commands/bootstrap-review-app.py
> +        User = get_user_model()
Something's gone wrong here as I removed (most of) this code in this PR: https://github.com/newsrevenuehub/rev-engine/pull/343

2022-03-18 22:15 UTC, x110dc commented on revengine/settings/base.py
> +        },
And again here, I intentionally removed all of this in: https://github.com/newsrevenuehub/rev-engine/pull/342

It shouldn't be added back.

2022-03-18 22:15 UTC, x110dc commented on revengine/settings/base.py
> +ADMINS = [("nrh-team", "nrh-team@caktusgroup.com")]
And here: https://github.com/newsrevenuehub/rev-engine/pull/342

2022-03-30 19:21 UTC, benjaminEwhite commented on apps/users/choices.py
> +class Roles(models.TextChoices):
FWIW, this was moved here and out of models.py because of a circular import.

2022-04-06 21:25 UTC, njharman requested changes
This commit is too big

In line comments on python code. Didn't look at tests or js.

2022-04-06 21:25 UTC, njharman commented on apps/pages/validators.py
> +                raise serializers.ValidationError(UNOWNED_TEMPLATE_FROM_PAGE_PAGE_PK_MESSAGE)
Believe ra could be None and elif ra.role_type clauses reached. Maybe change to 

```
If user.is_super_user:
  return
if ra is None
  raise?
if ra.role_type == HUB
   return
elif ...
```

2022-04-06 21:25 UTC, njharman commented on apps/pages/views.py
>      permission_classes = [IsAuthenticated]
black don't force trailing comma in list :(

2022-04-06 21:25 UTC, njharman commented on apps/public/permissions.py
> +        return getattr(request.user, "is_active", False) and request.user.is_superuser
What am I missing. how can user not have is_active?  Is it because there's a fake user for contributors now? If so that fake user should implement is_active instead of relying on remembering to do this everywhere.

If it's because request.user can be None then `request.user and request.user.is_active` is the way. Short circut boolean logic ftw!

2022-04-06 21:25 UTC, njharman commented on apps/users/models.py
> +    revenue_programs = models.ManyToManyField("organizations.RevenueProgram", blank=True)
Can't remember how/if django supports constraint to limit to only rps that belong to organization. It would be good.  Even if only as a todo note to implement in future.

2022-04-06 21:25 UTC, njharman commented on apps/users/serializers.py
> +        elif role_assignment and role_assignment.role_type != Roles.HUB_ADMIN:
Other places you raise on unrecognized Role.  should this also not be "future proofed" by inclusivity rather than != ?

ra.rt in (Roles.ORG_ADM, Roles.RP_ADM)

2022-04-06 21:25 UTC, njharman commented on apps/users/serializers.py
> +        if not role_assignment and not obj.is_superuser:
Do super users never have role_assignment? If they can have role, they'll get limited by it here.

2022-04-06 21:25 UTC, njharman commented on apps/users/serializers.py
> +        if not role_assignment and not obj.is_superuser:
Do super users never have role_assignment? If they can have role, they'll get limited by it here.

2022-04-06 21:25 UTC, njharman commented on apps/users/serializers.py
> +                qs = role_assignment.revenue_programs
```
else:
   qs = qs.none()
```
to guard against new roles added in future seeing all.

2022-04-06 21:25 UTC, njharman commented on apps/users/views.py
> +            elif role_assignment := getattr(user, "roleassignment"):
weird that this is only elif

2022-04-06 21:25 UTC, njharman commented on apps/users/views.py
> +                return queryset.model.filter_queryset_by_role_assignment(role_assignment, queryset)
final "if none of the above" return queryset.none() or raise some error?

2022-04-06 21:25 UTC, njharman commented on revengine/settings/base.py
> +NON_DONATION_PAGE_SUBDOMAINS = os.getenv("NON_DONATION_PAGE_SUBDOMAINS", ["support", "www"])
Yes! That split weirds me out. "Too lazy to type list punctuation, get Python to do it for me"?

2022-05-05 19:50 UTC, merged