dev-1457 and dev-1092 header-image and url ..pretttier
newsrevenuehub/rev-engine pull request #347
Opened 2022-03-17 19:49 UTC by gurjittoptal

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested?

#### Have automated unit tests been added?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets?
**(Note: Please use syntax [JIRA-123] to link any relevant tickets)**

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them?
**(Note: Please use syntax [JIRA-123] to link any relevant tickets)**

2022-03-17 20:37 UTC, gurjittoptal commented on spa/src/utilities/getSubdomain.js
> +  if (splitHost[splitHost.length - 2] === 'herokuapp' && splitHost.length === 3) return '';
This is to make heroku-preview app work. Not part of scope of this ticket, and likely will be reverted before merge. https://news-revenue-hub.atlassian.net/browse/DEV-1457

2022-03-22 19:04 UTC, x110dc requested changes

2022-03-22 19:04 UTC, x110dc commented on spa/src/utilities/getSubdomain.js
> +  if (splitHost[splitHost.length - 2] === 'herokuapp' && splitHost.length === 3) return '';
Yeah, I'd prefer this be handled separately, but understand that it's helping for now.

2022-03-23 17:03 UTC, benjaminEwhite requested changes
Left a few comments.

2022-03-23 17:03 UTC, benjaminEwhite commented on spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.js
> +
```suggestion
  const showLogoInput = (
     page.header_logo_thumbnail
     && 'header_logo' in images
     && images['header_logo' ] !== ''
   );
```

2022-03-23 19:15 UTC, gurjittoptal commented on spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.js
> +
@benjaminEwhite the proposed code won't handle the condition below 

if ('header_logo' in images && images['header_logo'] !== '') {
    showLogoInput = true;
  }

its relevant even when page.header_logo_thumbnail is not set.

2022-03-23 19:20 UTC, gurjittoptal commented on spa/src/components/donationPage/DonationPageNavbar.js
> +
This is also not handling all cases. i.e. 
(Image, Link) -- so 4 conditions
(true,false) -> show logo only
(true,true) -> show logo with link
(false,false) -> null
(false,true) -> null

2022-03-23 19:22 UTC, gurjittoptal commented on spa/cypress/integration/02 - donation-page-edit.spec.js
> +    /*
This started failing as input-url needs to be shown only when image is uploaded and no image is being uploaded in the test

https://github.com/newsrevenuehub/rev-engine/blob/develop/spa/cypress/integration/02%20-%20donation-page-edit.spec.js#L270

2022-03-30 14:41 UTC, benjaminEwhite reviewed
Had one question about a test id name, but LGTM.

2022-03-30 14:41 UTC, benjaminEwhite commented on spa/src/components/donationPage/DonationPageNavbar.js
> +
Makes sense. I like to try to avoid nested conditionals but here i see why.

2022-03-30 14:41 UTC, benjaminEwhite commented on spa/cypress/integration/02 - donation-page-edit.spec.js
> +      cy.getByTestId('errors-Thank You page link').contains(expectedErrorMessage);
Is this test id correct? Not sure how/where this is getting set, but seems strange to have an ID with spaces in it.

2022-03-30 21:17 UTC, gurjittoptal commented on spa/cypress/integration/02 - donation-page-edit.spec.js
> +      cy.getByTestId('errors-Thank You page link').contains(expectedErrorMessage);
Its based on Label and thats set here. https://github.com/newsrevenuehub/rev-engine/blob/main/spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.js#L132

2022-04-02 03:42 UTC, x110dc requested changes
It looks like DEV-1210 wasn't ready to be implemented. Can you work on decoupling with Mariclare?

2022-04-02 07:33 UTC, gurjittoptal commented
> It looks like DEV-1210 wasn't ready to be implemented. Can you work on decoupling with Mariclare?

Yes, 1210 confusion is on me. my bad. This handles DEV-740 and DEV-1209. I will share the preview-link with her on Monday and get this sorted.

2022-04-05 20:59 UTC, gurjittoptal commented
Update
dev-740 and dev-1209 have separate tickets and PRs have been updated accordingly.

2022-04-26 18:53 UTC, merged