Dev 1411 linelength
newsrevenuehub/rev-engine pull request #348
Opened 2022-03-21 18:59 UTC by njharman

#### What's this PR do?
Set black (and isort) line length to 140.  It does not reformat any of the code.  this will be required done as other commits make changes to files. Or, can be done in one fell swoop between sprints? 

#### Why are we doing this? How does it help us?
Consistancy across repos.

#### How should this be manually tested?
N/A

#### Have automated unit tests been added?
Already exists pre-commit and CI

#### How should this change be communicated to end users?
N/A

#### Are there any smells or added technical debt to note?
N/A

#### Has this been documented? If so, where?
should be https://news-revenue-hub.atlassian.net/wiki/spaces/TECH/pages/2047311873/Python+Style+Guide

#### What are the relevant tickets?
[DEV-1411]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
No

#### Are there next steps? If so, what? Have tickets been opened for them?
Part of larger (and existing tickets) to unify and improve code quality stuffs.

2022-03-21 23:41 UTC, njharman commented
I was hoping this would not require reformatting all the code. But the way pre-commit is run in github workflow action means it will always fail until we do.

Not sure but maybe this should be reviewed, tentatively approved and held until good time (between sprints?) to do all the black reformatting and merge.

2022-03-22 19:16 UTC, x110dc requested changes
Is there a way to make it not do `--all-files` for now and we could add that back later? Otherwise seems like yeah, need to do at beginning/end of sprint when no other outstanding PRs in flight.

2022-03-22 19:16 UTC, x110dc commented on pyproject.toml
> +black = "^20.8b1"
This is lower than the version here: https://github.com/newsrevenuehub/rev-engine/blob/develop/.pre-commit-config.yaml#L3

Does that matter? I guess the `^` is designating a minimum version right? So it's fine that these are different?

2022-03-23 15:28 UTC, njharman commented
removing --all-files, It won't process any files then. pre-commit looks at what is about to be committed. After commit, in CI, it's all committed, so it sees no files that need checking. Hence action uses --all-files.

I googled a bit and there was ways with other actions to get list of files that had been changed. It all looked more trouble than worth.

2022-03-23 15:32 UTC, njharman commented on pyproject.toml
> +black = "^20.8b1"
yes the circumflex(pointy hat) is minimum.  I was creeping scope here. These dev qa things should be "*" like in webhook-receiver.

2022-07-21 22:53 UTC, closed without merging