dev-1443_disable_slack_in_revengine
newsrevenuehub/rev-engine pull request #350
Opened 2022-03-23 20:05 UTC by gurjittoptal

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?
Disable slack notifications

#### Why are we doing this? How does it help us?
N/A

#### How should this be manually tested?
Can be but for that we will need to add an organizationslackintegration. Once that is done a successful donation will need to be done. And this won't trigger a slack notification.

#### Have automated unit tests been added?
N/A

#### How should this change be communicated to end users?
N/A

#### Are there any smells or added technical debt to note?
No

#### Has this been documented? If so, where?
N/A

#### What are the relevant tickets?
**(Note: Please use syntax [JIRA-123] to link any relevant tickets)**
[DEV-1443]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
No

#### Are there next steps? If so, what? Have tickets been opened for them?
**(Note: Please use syntax [JIRA-123] to link any relevant tickets)**

2022-03-24 16:00 UTC, harsha09 requested changes

2022-03-24 16:00 UTC, harsha09 commented on apps/contributions/webhooks.py
> +# from apps.slack.models import SlackNotificationTypes
Please remove the comments

2022-03-24 16:00 UTC, harsha09 commented on apps/contributions/webhooks.py
> -        contribution.save(slack_notification=SlackNotificationTypes.SUCCESS)
@x110dc : How about using a configuration variable to enable or disable slack notifications here?
At later point of time slack notification can be enabled if needed, without changing the code again.

2022-03-26 00:15 UTC, x110dc requested changes
After the comment is removed it will LGTM.

2022-03-26 00:15 UTC, x110dc commented on apps/contributions/webhooks.py
> +# from apps.slack.models import SlackNotificationTypes
Agreed, just remove the line.

2022-03-26 00:15 UTC, x110dc commented on apps/contributions/webhooks.py
> -        contribution.save(slack_notification=SlackNotificationTypes.SUCCESS)
I think it's fine disabled this way for now. I opened a ticket to consider a variable to enable/disable: https://news-revenue-hub.atlassian.net/browse/DEV-1544

2022-03-29 20:45 UTC, x110dc approved these changes

2022-03-29 20:48 UTC, merged