dev-1531 No pages displayed in "content" section
newsrevenuehub/rev-engine pull request #367
Opened 2022-03-31 01:13 UTC by gurjittoptal

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested?

#### Have automated unit tests been added?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets?
**(Note: Please use syntax [JIRA-123] to link any relevant tickets)**

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them?

2022-04-01 17:39 UTC, benjaminEwhite approved these changes
A couple of suggestions for more terse/contemporary JS, but they don't change implementation. Looks good to me.

2022-04-01 17:39 UTC, benjaminEwhite commented on spa/src/components/content/pages/Pages.js
> +        const pagesForRp = pgs.filter((p) => p.revenue_program && p.revenue_program.id === rpId);
```suggestion
        const pagesForRp = pgs.filter((p) => p?.revenue_program?.id === rpId);
```

2022-04-02 02:29 UTC, gurjittoptal commented on spa/src/components/content/pages/Pages.js
> +    const revPrograms = new Set(pgs.map((p) => (p.revenue_program ? p.revenue_program.id : null)));
yeah. thats better way. thnx

2022-04-02 03:32 UTC, x110dc requested changes
Can we add a unit test please?

2022-04-02 03:32 UTC, x110dc commented on spa/src/components/content/pages/Pages.js
> +    console.log(revPrograms);
this should probably be removed.

2022-04-02 05:51 UTC, gurjittoptal commented on spa/src/components/content/pages/Pages.js
> +    console.log(revPrograms);
test has been inserted and debug removed

2022-04-02 18:59 UTC, x110dc requested changes

2022-04-02 18:59 UTC, x110dc commented on spa/cypress/integration/07 - pages.spec.js
> +    cy.getByTestId('pages-list').should('exist');
This really isn't my area so I could be off base here, but can this be unit-tested with jest instead of (or in addition to) Cypress? 

Testing like this? https://github.com/newsrevenuehub/rev-engine/blob/main/spa/src/components/errors/GenericErrorBoundary.test.js

2022-04-03 04:32 UTC, gurjittoptal commented on spa/cypress/integration/07 - pages.spec.js
> +    cy.getByTestId('pages-list').should('exist');
yes, ideally should be a unit test and not an e2e.

its a bigger discussion on how to proceed. Ideally in front-end ( unlike back end), more focus is on customer-journeys ie captured by e2e. 

On the unit-test level coding testing is mostly limited to some generic functions ( complicated logic ones) and code is structured such that there are more of pure-functions ( so simple that well test-cases are just overkill ). 

In our repo, there are two file and around ~10 unit tests. So, likely its was decided to have comprehensive focus on e2e cypress tests while ignoring unit test. 

Also, noteworthy that if state, functions & jsx intermingle are present in component/functions writing test cases can be quite messy. Maybe we refactor a bit here and there to get unit-test-cases in for some really important stuff

2022-04-05 20:57 UTC, gurjittoptal commented on spa/cypress/integration/07 - pages.spec.js
> +    cy.getByTestId('pages-list').should('exist');
@x110dc 
cypress-e2e test is removed and unit tests have been implemented. please review.

2022-04-20 22:33 UTC, x110dc approved these changes
LGTM

2022-04-20 22:34 UTC, x110dc commented on spa/cypress/integration/07 - pages.spec.js
> +    cy.getByTestId('pages-list').should('exist');
Thanks!

2022-04-26 18:35 UTC, merged