Dev 1111 contributor portal rp branded
newsrevenuehub/rev-engine pull request #405
Opened 2022-05-03 05:42 UTC by gurjittoptal

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested?

#### Have automated unit tests been added?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets?
**(Note: Please use syntax [JIRA-123] to link any relevant tickets)**

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them?

2022-05-09 13:48 UTC, benjaminEwhite requested changes
Left some inline comments. 

Also, think there should be a few tests added (could be via Cypress or Jest, not sure what makes most sense here).  There should be tests that show the happy path for applying custom RP branding on the related user facing routes in the SPA. And there should be parallel tests showing the happy path for applying default branding when custom not set up.

2022-05-11 16:26 UTC, gurjittoptal commented on spa/src/components/DashboardRouter.js
> +  const isContributorApp = isContributorAppPath();
makes sense. divided on applying this fix in this PR or handling via another ticker. will check with McH

2022-05-11 16:31 UTC, gurjittoptal commented on spa/src/components/contributor/ContributorEntry.js
> +function ContributorEntry(props) {
fair point.

2022-05-11 16:31 UTC, gurjittoptal commented on spa/src/components/DashboardRouter.js
> +  if (isContributorApp) return <ContributorRouter />;
agreed.

2022-05-11 16:35 UTC, gurjittoptal commented on spa/src/components/contributor/ContributorEntry.js
> +    portalName = page?.revenue_program.name;
done

2022-05-11 20:04 UTC, benjaminEwhite approved these changes

2022-05-17 03:54 UTC, x110dc approved these changes

2022-05-17 04:44 UTC, merged