Dev 1578 and dev 699 (for merge to main)
newsrevenuehub/rev-engine pull request #407
Opened 2022-05-05 21:11 UTC by x110dc

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

Changes to SPA (and recursive changes to API that emerged) to enable role based permissions.

One consequence of this PR is that page, template, style, and contribution data will be filtered via user roles.

Some noteworthy code changes:

*Backend*

- Simplifies API endpoint configuration for creation, such that there are not query parameters being passed to endpoints that otherwise expect a body of data (aka, no longer faceting based on RP and ORG slugs)
- Adds `apps.common.fields.SerializedOnReadElsePk` field which can be used to enable an API resource where a field is PK on creation, otherwise serialized
- Cleans up some use of custom mixins that were not rquired in views
- Adds some fields to OrganizationInlineSerializer to make front end work
- Adds a validator (`RpPkIsForOwnedRp`) which can be used to validate if the requesting user should be able to reference a related revenue program

*SPA*

- Adds a `forceLogin` command that can be used to directly force login without going through sign on page flow in tests, and replaces a bunch of current use of cy.login with this new method.
- Removes unused revenue program route
- Renames `OrganizationContext` to `PaymentProviderContext`
- In `AddPageModal`, the list of revenue programs that appear in the dropdown now comes from the list of available RPs in a user's role information instead of pulled from API resource.
- Removes unused src/components/organization/Organization.js

#### Why are we doing this? How does it help us?

will allow us to ship role-based permissions

#### How should this be manually tested?

Run the dev server locally (preferably after retrieving a recent back up from staging and restoring it, then running migrations). Log in to the SPA as a hub admin or super user and you should see all content. Log in as an org or rp user, and you should only see content that you own.

#### Have automated unit tests been added?

Added and edited.

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets?
**(Note: Please use syntax [JIRA-123] to link any relevant tickets)**

[DEV-1578]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No

#### Are there next steps? If so, what? Have tickets been opened for them?

Revisit DEV-699 once this is merged into it, and do clean up before submitting that PR for final review.

2022-05-09 16:43 UTC, njharman requested changes
Doing review, but right now there's
1. Test coverage under 95% (CI run fail)
2. Merge conflicts.

2022-05-09 18:30 UTC, njharman requested changes
Did not review javascript/SPA as I'm unqualified.
Did not manually test.
Only glanced at tests (very large commit to also pour over these and test coverage is below 95%)

A few questions/clarifications, a few minor changes.

2022-05-09 18:30 UTC, njharman commented on apps/pages/validators.py
> +MISSING_REFRENCE_TO_REV_PROGRAM_MESSAGE = "Can't determine relationship with revenue program"
Why do we do this, instead of subclassing ValidationError, with the text.  I really dislike GLOBALS. I'm mostly ranting. At least these are marked _MESSAGE and so can be ignored.

2022-05-09 18:30 UTC, njharman commented on apps/pages/validators.py
> +        return
Bare return

2022-05-09 18:30 UTC, njharman commented on apps/public/permissions.py
> +        return getattr(request.user, "is_active", False) and request.user.is_superuser
getattr, isn't suppose to look for existence of is_superuser?

Currently, if request.user lacks "is_active" they are not a superuser regardless of what user.is_superuser says.
and will raise AttributeError, if is_active exists and is truish and is_superuser does not exist.

2022-05-09 18:30 UTC, njharman commented on apps/users/models.py
> +            return f"{Roles.RP_ADMIN.label} for {self.organization.name}"
Not listing RPs they're admin for?

2022-05-09 18:30 UTC, njharman commented on apps/users/models.py
> +        return f"Unspecified RoleAssignment ({self.pk})"
Unknown role_type, eh?  unspecified would be org null and/or rp null, depending, for ORG or RP admins.

2022-05-09 18:30 UTC, njharman commented on apps/users/models.py
> +    revenue_programs = models.ManyToManyField("organizations.RevenueProgram", blank=True)
Could add constraints to guarantee ORG/RP hav org defined and RP have rps defined. and NULL otherwise.

2022-05-10 17:27 UTC, benjaminEwhite commented on apps/users/models.py
> +    revenue_programs = models.ManyToManyField("organizations.RevenueProgram", blank=True)
That business logic appears to be enforced in `RoleAssignmentAdminForm.clean`, which is the only interface for creating role assignments, so I think we're okay.

2022-05-10 19:11 UTC, njharman approved these changes
assumming cypress test will finish and pass eventually.
lgtm

2022-05-10 19:52 UTC, x110dc commented
I pushed a couple commits to fix what looks like a bad merge (probably from when I created the dual-ticket branch). Approving.

2022-05-12 22:15 UTC, merged