Dev 1089 associate stripe acc with rp from orgs
newsrevenuehub/rev-engine pull request #408
Opened 2022-05-06 04:38 UTC by harsha09

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
Associate Stripe details with RP instead of ORG.

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested?

#### Have automated unit tests been added?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets?
**(Note: Please use syntax [JIRA-123] to link any relevant tickets)**
[DEV-1089]
#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them?

2022-05-06 22:25 UTC, x110dc requested changes
I just had a couple of questions about directly linking contributions to revenue programs. It seems like you could determine that from the donation page instead and then it avoids data inconsistencies.

2022-05-06 22:25 UTC, x110dc commented on apps/contributions/models.py
> +    revenue_program = models.ForeignKey("organizations.RevenueProgram", on_delete=models.SET_NULL, null=True)
Do we need this? A contribution is always associated with a contribution page and a contribution page is always associated with an RP, so we can always determine the RP through that relation. What benefit does this give us?

2022-05-06 22:25 UTC, x110dc commented on apps/contributions/payment_managers.py
> +            revenue_program=revenue_program,
Again, can't we just grab the RP from the donation page relation? 

The reason I'm worried about two paths, is that one could be manually changed and then the data/state would be inconsistent.

2022-05-09 12:37 UTC, benjaminEwhite commented on apps/contributions/models.py
> +    revenue_program = models.ForeignKey("organizations.RevenueProgram", on_delete=models.SET_NULL, null=True)
I agree. For convenience, it might be nice to add a `revenue_program` property, but I don't think we need an additional FK here.

2022-05-09 12:41 UTC, benjaminEwhite commented on apps/contributions/payment_managers.py
> +    def create_stripe_customer(self, revenue_program: RevenueProgram):
This syntax looks off.

2022-05-09 12:47 UTC, benjaminEwhite commented on apps/contributions/views.py
>          # An org that doesn't have a stripe_account_id hasn't gone through onboarding
This code comment needs to be updated so doesn't refer to `org` (also, I know this is a WIP PR :) ).

2022-05-09 13:00 UTC, benjaminEwhite reviewed
This is looking good. Made a suggestion about having `.revenue_program` be a property instead of FK.

Also, not sure if this is being tracked elsewhere, but we'll want to circle back to the SPA and ensure that any fixtures related to serialized orgs or RPs are updated to reflect the new schema. Also, will need to ensure no regressions in SPA with the changed schema.

2022-05-09 19:46 UTC, harsha09 commented on apps/contributions/models.py
> +    revenue_program = models.ForeignKey("organizations.RevenueProgram", on_delete=models.SET_NULL, null=True)
I've removed revenue_program FK and added as a property as suggested by @benjaminEwhite

2022-05-19 21:18 UTC, x110dc approved these changes
LGTM.

2022-05-19 21:45 UTC, x110dc requested changes
Also, there's a couple of merge conflicts to resolve.

2022-05-19 21:45 UTC, x110dc commented on apps/organizations/admin.py
>      list_display = ["name", "donation_range", "organization"]
I think it's complaining about having `organization` here. 

```
remote: Running Migrations
remote: SystemCheckError: System check identified some issues:
remote:
remote: ERRORS:
remote: <class 'apps.organizations.admin.BenefitLevelAdmin'>: (admin.E108) The value of 'list_display[2]' refers to 'organization', which is not a callable, an attribute of 'BenefitLevelAdmin', or an attribute or method on 'organizations.BenefitLevel'.
```

2022-05-20 04:07 UTC, harsha09 commented on apps/organizations/admin.py
>      list_display = ["name", "donation_range", "organization"]
Yeah this is due to DEV-1160 merge. Will be resolving this.

2022-05-23 23:43 UTC, x110dc approved these changes

2022-05-23 23:59 UTC, x110dc approved these changes

2022-06-02 21:57 UTC, x110dc approved these changes
This LGTM. I'd like @benjaminEwhite to review it as well.

2022-06-08 00:06 UTC, benjaminEwhite reviewed
Overall looks great. Had a few questions/suggestions, but nothing too big.

2022-06-08 00:06 UTC, benjaminEwhite commented on apps/slack/slack_manager.py
> +        org_channel = self.get_org_channel(contribution.donation_page.organization)
Should this be `contribution.revenue_program.organization`?

2022-06-08 19:32 UTC, harsha09 commented on apps/organizations/tests/factories.py
> +    # stripe_verified = True
done

2022-06-08 19:36 UTC, harsha09 commented on apps/slack/slack_manager.py
> +        org_channel = self.get_org_channel(contribution.donation_page.organization)
DonationPage has property organization

2022-06-08 19:36 UTC, harsha09 commented on apps/organizations/serializers.py
> +            representation["domain_apple_verified_date"] = revenue_program.domain_apple_verified_date
I've added these not to break the UI due to current changes. The data is being stored in local storage.

2022-06-08 19:36 UTC, harsha09 commented on apps/contributions/views.py
> +    if not revenue_program:
yeah, you are right

2022-06-08 19:36 UTC, harsha09 commented on apps/contributions/tests/test_views.py
> +        ).first()
done

2022-06-08 19:37 UTC, harsha09 commented on apps/contributions/tests/test_payment_managers.py
> +        self.contributor = ContributorFactory()
done

2022-06-08 19:39 UTC, harsha09 commented on apps/contributions/serializers.py
> +        payment_provider = obj.revenue_program.payment_provider
Handled it

2022-06-08 19:39 UTC, harsha09 commented on apps/contributions/models.py
> +            stripe_account=self.revenue_program.payment_provider.stripe_account_id,
Handled it

2022-06-08 23:43 UTC, x110dc commented on apps/organizations/serializers.py
> +            representation["domain_apple_verified_date"] = revenue_program.domain_apple_verified_date
I think it's okay to break something on the FE as long as we have a ticket to address it there. Alternatively we can make a ticket to fix the FE and then another ticket to remove this code after that's done. I'll create those tickets so we can move this one forward.

2022-06-09 15:59 UTC, harsha09 commented on apps/contributions/views.py
> +            revenue_program.save()
done

2022-06-09 15:59 UTC, harsha09 commented on apps/contributions/views.py
> +    revenue_program = RevenueProgram.objects.filter(id=revenue_program_id).first()
done

2022-06-09 16:00 UTC, harsha09 commented on apps/contributions/tests/test_views.py
> +            )
done

2022-06-09 22:40 UTC, x110dc approved these changes

2022-06-13 22:03 UTC, merged