Dev 1056 deliver initial confirmation emails for recurring donations mvp
newsrevenuehub/rev-engine pull request #409
Opened 2022-05-06 20:51 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

This is complete in terms of being ready for review, but do need to upload the new email template (/email_templates/nrh-default-contribution-confirmation-email.html) to Mailgun and confirm everything works as expected.

#### What's this PR do?

Causes contribution confirmation emails to be sent to contributors making recurring donations (vs. status quo where only contributors making one time donations get a confirmation email).

Along the way:

- Retires apps.emails.models.PageTemplateEmail and related admin, signals, and management command files
- Enables eager celery task execution in tests
- Adds `ESP_TEMPLATE_ID_FOR_CONTRIBUTION_CONFIRMATION` to settings/base.py. This value is pulled from environment, so will need to be set up in Heroku when deploy. We'll get this value when we upload the template to Mailgun.
- Renames `send_donor_email` task to `send_email` task, since nothing about implementation was tied to contributors.
- Adds a new task `send_contribution_confirmation_email` which is used to trigger contribution confirmation emails. This allows us in short term to use a single email template to handle both recurring and one time contributions.
- Removes `uses_email_templates` from organization model and also removes conditional logic around whether or not confirmation emails are sent. In the status quo, a confirmation email is only sent if the org receiving the contribution has `use_email_templates` set to True (with it defaulting to False).
- Refactors the view tests around one-time and recurring payments to assert that send_contribution_confirmation_email gets called.

#### Why are we doing this? How does it help us?

Business reasons are discussed in parent ticket.

More specifically, regarding retiring the PageTemplateEmail model, there was no clear use case for the abstraction provided by the model, and it was built in such a way that using a single template to handle both one-time and recurring contributions would go against the semantics of the code.  There's a fair amount of overhead to having this data model without any clear business value.

The advantage of the new approach is that it simplifies the connection with the ESP. The `send_contribution_confirmation_email` (as well as `send_email` which it calls internally) take a template identifier, a to email address, a subject, and template variables (a dict) that gets sent to the ESP, and the task gets called (with `.delay`) in the stripe payment function. 

#### How should this be manually tested?

- After uploading the template to MailGun, in the environment running the app, set an environment variable with the name `ESP_TEMPLATE_ID_FOR_CONTRIBUTION_CONFIRMATION` to the value of the uploaded MailGun email template identifier.
- Start the server (or restart after ensuring updated env is sourced)
- Visit a donation page and make a recurring contribution using an email address that you have access to.
- Check your inbox and confirm that a confirmation email came.

#### Have automated unit tests been added?

Not added, but updated to ensure task for sending confirmation emails gets called in both one time and recurring cases.

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

There were two old migrations that were importing directly from apps.emails.models in order to dynamically set default values. In general, it's best to avoid importing models in this way into migrations because it can make it tricky to remove models. 

After removing the PageTemplateEmail and its models file, I was unable to make or run migrations because refs to the PageTemplateEmail model were broken. To get around this, I removed these references from the old migrations. This doesn't seem to create any problems locally, but changing old migrations is possibly tricky (in this case, I think it's fine).

#### Has this been documented? If so, where?

#### What are the relevant tickets?
**(Note: Please use syntax [JIRA-123] to link any relevant tickets)**

[DEV-1056]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

- Upload the new email template to MailGun and grab the template identifier
- Set `ESP_TEMPLATE_ID_FOR_CONTRIBUTION_CONFIRMATION` env var on Heroku to the value of the identifier

#### Are there next steps? If so, what? Have tickets been opened for them?

2022-05-09 22:17 UTC, njharman requested changes
Conflicts from CI need to be resolved.

It's hard to review this as it includes all the changes from other branch mentioned in PR that I just reviewed (I think).

Can that, DEV-1578_and_DEV-699, be merged first.

2022-05-10 13:04 UTC, benjaminEwhite commented
@njharman merged in main, so no more conflicts.

Tests pass, but it looks like in retiring some of the apps.email code, the overall test coverage has fallen below 95%. Should be good for a review, and we'll have to decide what to do re: test coverage.

2022-05-10 22:21 UTC, njharman requested changes
Your PR notes are excellent. Answered several questions.

Do I understand correctly; the "nrh-default..." email template is example of what would be uploaded to ESP. And the specific template to be used is set by that environment var. (also envar to set magic link email tempalte). This is in place of / why we nuked template from our database?

But don't customers need to customize those templates? and there is only one template (set by envvar)?  We run rev-engine as service / not customer self-hosted right?

Few other questions / thoughts done in line.

2022-05-10 22:21 UTC, njharman commented on revengine/settings/base.py
> +ESP_TEMPLATE_ID_FOR_CONTRIBUTION_CONFIRMATION = os.environ.get("ESP_TEMPLATE_ID_FOR_CONTRIBUTION_CONFIRMATION")
Please add comment explaining what this setting/envvar is or reference to explanation (if on confluence for example).

2022-05-11 12:36 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        template_data = {
I copied the template from an existing one, and at time, had not run down whether or not the ESP somehow provided values for those template vars (they're in status quo template too, but nothing gets passed in). 

Just pushed up a commit that removes intro and blurb and formats the template file so it's more readable.

2022-05-11 12:37 UTC, benjaminEwhite commented on apps/organizations/models.py
> -    uses_email_templates = models.BooleanField(default=False)
Yeah, I think that's more a description of the status quo. Mariclare and I Slacked about removing this criterion. I'll confirm with her.

2022-05-11 12:54 UTC, benjaminEwhite commented
@njharman re: high level questions:

> Do I understand correctly; the "nrh-default..." email template is example of what would be uploaded to ESP. And the specific template to be used is set by that environment var. (also envar to set magic link email tempalte). This is in place of / why we nuked template from our database?

All correct, with a bit of nuance on the last point. The app already had that page email template model, which collects a donation page and a reference to a template on an ESP. We only have one use case for transactional emails right now, and I concluded that the maintenance and ease of adding new email functionality would be better if we removed the data model entirely, and instead send emails more directly.  One specific reason I reached this conclusion is that it made sense to have a single email template for both one-time and recurring donations. As implemented, the PageTemplateEmail model wanted me to choose between distinct template types, where one-time and recurring were distinct options.

Overall, I think if you're using an ESP, you kinda just wanna throw the right data over the fence, and lean on the template layer. Sometimes it can be nice to model that an email attempt was made so you can track a denominator of attempts vs, say, bounce rate, but that's not what the PageTemplateEmail model was getting at. 

> But don't customers need to customize those templates? and there is only one template (set by envvar)? We run rev-engine as service / not customer self-hosted right?

There's no business requirement around customizing templates at the moment. And if that need does arise, I think we'll want to model things a bit differently.

Yes, rev-engine as a service. 

And yes re: only one template (set by env var). That's how things work in status quo as well (but only for one time contributions).

2022-05-11 12:57 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        contribution_date = timezone.now()
That's actually a good question. I'm not sure what we want here.

2022-05-11 13:13 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        contribution_date = timezone.now()
Asked, and answer is that this is desired behavior for status quo. We're tracking a separate ticket for moving to what's stored in Stripe.

2022-05-17 16:30 UTC, njharman commented on apps/contributions/views.py
> +            logger.warning(f"stripe_payment view recieved unexpetected interval value: {interval}")
logging should use % formatting.

2022-05-17 16:30 UTC, njharman commented on apps/contributions/views.py
> +        logger.warning(
logging should use % formatting.

2022-05-18 15:34 UTC, benjaminEwhite commented
@njharman I made requested changes re: string formatting in log messages.

@x110dc your ship for final(?) review.

Also, fwiw, I don't see any merge conflicts locally (main is merged into this branch). Think the conflicting files above are a relic of the PR (or may in fact have to be resolved when ready to merge).

2022-05-19 20:04 UTC, x110dc approved these changes
Excellent PR description. Thanks. LGTM.

2022-05-20 21:34 UTC, x110dc requested changes

2022-05-20 21:34 UTC, x110dc commented on revengine/celery.py
> +app.config_from_object("django.conf:settings", namespace="CELERY")
Why was the namespace added?

2022-05-23 13:25 UTC, benjaminEwhite commented on revengine/celery.py
> +app.config_from_object("django.conf:settings", namespace="CELERY")
I had to do that in order to get Celery to run locally, which I needed to do in order to confirm that the feature was working. Was an oversight letting that go through PR. Will remove.

2022-05-23 18:28 UTC, benjaminEwhite commented
@x110dc made requested changes. As noted in PR notes at top (after I edited them), the merge issues stemmed from an upgrade of django-simple-history. In order to move this ticket across the board, I pinned django-simple-history to 3.0.0, which solves the problem, but at some point in future we may want to look into this issue.

2022-05-23 23:09 UTC, x110dc approved these changes

2022-05-31 18:39 UTC, x110dc approved these changes

2022-05-31 20:31 UTC, merged