Dev 1517/Dev 1518 add query params to thank you page internal
newsrevenuehub/rev-engine pull request #415
Opened 2022-05-09 07:14 UTC by gurjittoptal

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested?

#### Have automated unit tests been added?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets?
**(Note: Please use syntax [JIRA-123] to link any relevant tickets)**

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them?

2022-05-09 16:45 UTC, benjaminEwhite requested changes
Overall looks good. Think should consider getting rid of the try + bare catch statement.

2022-05-09 16:45 UTC, benjaminEwhite commented on spa/src/components/paymentProviders/stripe/StripePaymentForm.js
> +      .catch((err) => console.log(err));
This line is unreachable because `getSHA256Hash` catches all errors and doesn't re-raise.

2022-05-09 16:45 UTC, benjaminEwhite commented on spa/src/utilities/getSHA256Hash.js
> +    console.log(err.message);
Seems to me the try/catch should be removed here. As is, any exceptions will be caught, and the function will successfully complete, which if i'm not mistaken means that emailHash will be set to undefined but the query string will still be generated.

2022-05-09 16:50 UTC, benjaminEwhite commented
One more high-level comment: there should be a test demonstrating that `handlePaymentSuccess` causes the right query params to be pushed onto history. Otherwise we're depending entirely on maintainers remembering the business logic around these changes and preserving their implementation.

2022-05-09 17:00 UTC, gurjittoptal commented on spa/src/components/paymentProviders/stripe/StripePaymentForm.js
> +      .catch((err) => console.log(err));
hmm. right. this has been removed now.

2022-05-09 17:04 UTC, gurjittoptal commented on spa/src/utilities/getSHA256Hash.js
> +    console.log(err.message);
So, the reason to keep the try/catch is that Crypto.subtle is available only in secure contexts or localhost in browsers that implement specs ( most modern browsers ). In others a '' is passes as uid. 

@x110dc this is an FYI for you too. Let me know is some change is needed here.

2022-05-23 16:16 UTC, benjaminEwhite approved these changes

2022-05-23 23:29 UTC, x110dc approved these changes

2022-05-25 21:45 UTC, merged