Pre-commit Updates
newsrevenuehub/rev-engine pull request #416
Opened 2022-05-10 16:14 UTC by njharman

#### What's this PR do?
Update pre-commit tools, fix existing issues reported by pre-commit

Ran pre-commit autoupdate
Ran pre-commit --all-files Which fixed bunch of line endings and trailing white space issues.

The relevant files changed:
- .pre-commit-config.yaml
- manual fixes to Dockerfile (I guessed at proper FROM base... usage)
- added .talismanrc
- rest were updated by line ending and trailing whitespace checkers

#### Why are we doing this? How does it help us?
More current checks. Part of getting py3.9/3.10 in CI, broken out.

#### How should this be manually tested?
`pre-commit --all-files`  should not report issues outside of .spa/

#### Have automated unit tests been added?
N/A

#### How should this change be communicated to end users?
N/A

#### Are there any smells or added technical debt to note?
Did not commit the fixes to .spa/*, they were legion and did not want the merge conflict potential in code I do not grok. Perhaps reviewer will request they be applied.

#### Has this been documented? If so, where?
N/A.

#### What are the relevant tickets?
[DEV-1745]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
No.

#### Are there next steps? If so, what? Have tickets been opened for them?
Devs should configure their editors to auto delete trailing whitespace (or at least highlight it for manual deletion)

2022-05-11 20:34 UTC, x110dc requested changes
One change requested.

2022-05-11 20:34 UTC, x110dc commented on Dockerfile
> +FROM base:3.9-slim  AS deploy
Why was this changed? It makes the Docker image fail to build.

2022-05-11 20:55 UTC, njharman commented on Dockerfile
> +FROM base:3.9-slim  AS deploy
The docker linter complained about having "non-pegged" FROM xxx.

I don't know Docker very well. I guessed at 3.9-slim cause that is what  FROM .... as base line had. linter didn't want :latest.  I didn't know how else to say "the one we just created, right here, figure it out computer!"

2022-05-12 02:28 UTC, njharman commented on Dockerfile
> +FROM base:3.9-slim  AS deploy
commented out and punted on See DEV-1763

2022-05-12 22:00 UTC, x110dc approved these changes
LGTM.

2022-05-12 22:00 UTC, merged