DEV-1756_style_preview_are_blank - DRAFT
newsrevenuehub/rev-engine pull request #425
Opened 2022-05-17 17:12 UTC by gurjittoptal

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
DRAFT

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested?

#### Have automated unit tests been added?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets?
**(Note: Please use syntax [JIRA-123] to link any relevant tickets)**

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them?

2022-05-20 14:10 UTC, benjaminEwhite requested changes
Requested 2 small stylistic changes, but implementation looks good.

2022-05-20 14:10 UTC, benjaminEwhite commented on spa/src/components/content/Content.js
> +        },
```suggestion
        onSuccess: ({ data }) => {
          setStyles(data.map(({styles, id, revenue_program, name, used_live}) => {
            return {...styles, id, revenue_program, name, used_live}
          }));
        },
```

2022-05-20 15:38 UTC, gsclb commented on spa/src/components/content/Content.js
> +        },
updated

2022-05-20 15:38 UTC, gsclb commented on spa/cypress/fixtures/styles/list-styles-1.json
> +    "styles":{
agreed. changes done.

2022-05-23 14:06 UTC, benjaminEwhite approved these changes

2022-05-24 17:35 UTC, merged