DEV-1021 enable feature flagging
newsrevenuehub/rev-engine pull request #426
Opened 2022-05-17 18:02 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

This PR is the first in several that will bring feature flagging to the front- and back-end for rev-engine.

This PR adds django-waffle and integrates feature flagging with the permissions layer (initially for a single endpoint: contributions). 

Later PRs will expose a custom flag model created in this PR as an API resource which can be used in the SPA to gate access to features there. 

#### What's this PR do?

- Adds a custom `Flag` model (which initially is functional equivalent of the default waffle flag) that can later be extended to integrate with roleassignment (so flags can be rolled out for entire programs, etc.).
- Adds an admin model for `Flag`
- Adds a `HasFlaggedAccessToContributionsApiResource` permission that is used to gate the contributions api endpoint to users for whom the related flag is not active. 
- Uses the new feature flag approach to gate access to the contributions API resource (not inclusive of stripe specific API endpoints).
- Adds two tests to `apps.contributions.tests.test_views.TestContributionsViewSet` around feature flagging. The first is the "happy path", and the second shows behavior if `HasFlaggedAccessToContributionsApiResource` can't find its required flag on initialization.

#### Why are we doing this? How does it help us?

Described in detail on JIRA.

#### How should this be manually tested?

(first three steps are only if you're running locally)

1. Check out this branch.
2. Run migrations
3. Run dev server 
4. In the Django admin, go to the Flag admin, and create a flag whose name is the same value as `apps.flags.constants.CONTRIBUTIONS_API_ENDPOINT_ACCESS_FLAG_NAME` is set to (in source code right now, that's "contributions-api-endpoint-access"). Set `.everyone` to False, `superusers` to True, and add the user ID for a non superuser to `.users`. Save.
5. Try logging in as a superuser, then go to `/api/v1/contributions/` in a browser tab. You should be able to access. Alternatively, you can log in to the SPA as a superuser, and the contributions tab should populate with any contributions that are in the db.
6. Try logging in as a non super user who hasn't been explicitly added. Follow the same steps as 5. This time the API should return a 403 error.
7. Try logging in as the explicitly added user from step 4. Follow same steps as 5. This time the API should return any results (and 200).
8. In the Django admin, update the feature flag's `everyone` value to True. 
9. Repeat step 6. This time the API should 200 and return any results that user is allowed to see.

#### Have automated unit tests been added?

Yes

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

I don't believe so. Once this and initial, related SPA-side feature flag tickets are complete, would make sense to consolidate knowledge around feature flagging in Confluence.

#### What are the relevant tickets?
**(Note: Please use syntax [JIRA-123] to link any relevant tickets)**

[DEV-1021]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them?

After this is merged, we'll need to create a feature flag with name set to the value of `apps.flags.constants.CONTRIBUTIONS_API_ENDPOINT_ACCESS_FLAG_NAME`. That flag should have `superusers` set to True, `everyone` to "Unknown", and any individual users should have their IDs added to the `users` field in the admin.

2022-05-18 15:42 UTC, njharman requested changes
Just code review, no testing.

Questions, suggested comment/docs, and philosophical ramblings.

2022-05-18 15:42 UTC, njharman commented on apps/contributions/views.py
> +            # will not be granted permission by those.
I think this is saying flag not checked for contributors because flags aren't implemented for roles? contributors yet?

2022-05-18 15:42 UTC, njharman commented on apps/contributions/views.py
> +            | (IsActiveSuperUser & HasFlaggedAccessToContributionsApiResource)
Minor but it conveys they logic better IMO (assuming I understood logic correctly)

change to be IsCon... | (Hasflag & (Hasrole.. | isacivie...| N...))

2022-05-18 15:42 UTC, njharman commented on apps/contributions/tests/test_views.py
> +            self.contributor_user,
I think Inderstand why contibutor_user has access despite no flag set for them.  A comment here along lines of "contributor bypasses flag check because ???, not implemented yet?"

2022-05-18 15:42 UTC, njharman commented on apps/contributions/tests/test_views.py
> +    def test_feature_flagging(self):
This test is susceptible to false positives because it sets up several conditions and and checks them together.

It is better to construct tests setting one thing, all other things "false", and check that one thing. Also check the inverse.

So, set only flag.superusers = True, verify superuser allowed, allothers denied.  Then set flag.superusers = false verify superuser denied. 

pytest.parameterize is good for this.

2022-05-18 15:42 UTC, njharman commented on apps/flags/models.py
> +    Initially, we are not overriding anything from `AbstractUserFlag`,
You argue reasonable "justification". Still feels icky, https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it

2022-05-18 15:42 UTC, njharman commented on apps/contributions/tests/test_views.py
> +    def test_feature_flagging_when_flag_not_found(self):
Why did the CREATE_FLAGIFMISSING waffle setting not create this flag?

2022-05-18 18:14 UTC, benjaminEwhite commented on apps/contributions/views.py
> +            # will not be granted permission by those.
Some how I deleted part of the code comment! Thanks for catching this!

2022-05-18 18:23 UTC, benjaminEwhite commented on apps/contributions/views.py
> +            | (IsActiveSuperUser & HasFlaggedAccessToContributionsApiResource)
Agree

2022-05-18 18:26 UTC, benjaminEwhite commented on apps/contributions/tests/test_views.py
> +            self.contributor_user,
Left a comment. Reason here is actually because I did not apply the flag to contributors since that would prohibit them from getting any meaningful data out of the contributor dashboard.  Believe this is desired behavior, but will confirm.

2022-05-18 18:27 UTC, benjaminEwhite commented on apps/flags/models.py
> +    Initially, we are not overriding anything from `AbstractUserFlag`,
Confidence is relatively high that this will be needed in short order, but I agree with the general principle and will remove.

2022-05-18 18:35 UTC, benjaminEwhite commented on apps/flags/models.py
> +    Initially, we are not overriding anything from `AbstractUserFlag`,
Am removing models and admin, but I'm keeping the app, since the next ticket I'm working on will require exposing flags as an API resource, and that will happen in the flags app.

2022-05-18 18:50 UTC, benjaminEwhite commented on apps/contributions/tests/test_views.py
> +    def test_feature_flagging_when_flag_not_found(self):
I'm removing `WAFFLE_CREATE_MISSING_FLAGS` because there's not an immediate use case. 

To answer your question: it looks like missing flags only get created when calling the `is_active` method on a flag, whereas `HasFlaggedAccessToContributionsApiResource` calls `.is_active_for_user` on the flag.

2022-05-18 18:52 UTC, benjaminEwhite commented on apps/contributions/tests/test_views.py
> +    def test_feature_flagging(self):
Good reason for me to finally get up to speed on `pytest.parameterize`.

2022-05-20 17:59 UTC, njharman approved these changes
LGTM

2022-05-23 22:38 UTC, x110dc approved these changes

2022-05-23 22:38 UTC, x110dc commented on apps/api/permissions.py
> +from apps.flags.constants import CONTRIBUTIONS_API_ENDPOINT_ACCESS_FLAG_NAME
What's the value of having this as a variable? In what cases would we want to change the value?

2022-05-24 12:51 UTC, benjaminEwhite commented on apps/api/permissions.py
> +from apps.flags.constants import CONTRIBUTIONS_API_ENDPOINT_ACCESS_FLAG_NAME
When there are flags being managed across several files, IMO it's helpful to have a convention around storing flag names in a single place. That makes it easy to see at-a-glance what all the flags are.

Not a strongly held opinion though.

2022-05-25 21:45 UTC, merged