Dev 1774 hash email for uid in donation thank you page
newsrevenuehub/rev-engine pull request #439
Opened 2022-05-28 12:04 UTC by gurjittoptal

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
Incomeplete

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested?

#### Have automated unit tests been added?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets?
**(Note: Please use syntax [JIRA-123] to link any relevant tickets)**

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them?

2022-05-31 13:47 UTC, benjaminEwhite requested changes
Requested a few changes (most importantly, `handlePaymentSuccess` needs to be called, which it isn't right now).

I also made a comment about how we should be fully testing the contribution user flow (currently those tests are skipped). I don't think that needs to be in scope for this ticket, but something we should consider separately).

2022-05-31 13:47 UTC, benjaminEwhite commented on spa/src/components/paymentProviders/stripe/StripePaymentForm.js
> +      () => handlePaymentSuccess,
There's a bigger issue here (which doesn't necessarily need to be addressed in this PR):  as best I can tell, currently there is *not a single SPA-side test that shows the flow around making a donation*. This strikes me as problematic since that is probably the single most important element of business logic in this entire application.


It looks like there are some skipped tests in `01 - donation-page.spec.js` that were meant to test this. I unskipped them and was able to get them to pass locally (intermittently, sometimes they don't pass), so I suspect that's why they were toggled to skip, but what really should happen here is figuring out the underlying. problem with the tests and solving that so that we can test the basic business logic of this app.

2022-06-01 07:15 UTC, gurjittoptal commented on apps/contributions/views.py
> +    def getUIDHashFromEmail(pi_data):
this is moved to utils now.

2022-06-01 07:15 UTC, gurjittoptal commented on apps/contributions/views.py
> +            import hashlib
resolved by moving to utils.

2022-06-01 07:16 UTC, gurjittoptal commented on apps/contributions/views.py
> +
so. catching exception is defensive programming for handling the scenario of excepting donations without email ( ie maybe based on phone etc )

2022-06-08 12:18 UTC, benjaminEwhite approved these changes

2022-06-08 12:18 UTC, benjaminEwhite commented on apps/contributions/tests/test_views.py
> +    def test_one_time_payment_serializer_get_uid_as_email_hash(self, *args):
```suggestion
    def test_one_time_payment_serializer_gets_uid_as_email_hash(self, *args):
```

2022-06-08 12:18 UTC, benjaminEwhite commented on apps/contributions/views.py
> +
Just curious what exception you think might happen here, and if it's possible that could catch that specific exception.

2022-06-08 22:11 UTC, x110dc commented on apps/contributions/views.py
> +
I think what Ben is referring to is described well here (in point #3): https://jerrynsh.com/stop-using-exceptions-like-this-in-python/#:~:text=Avoid%20Bare%20except,such%20as%20SystemExit%20or%20KeyboardInterrupt%20.

It's best to catch the exception you're expecting not all exceptions.

2022-06-08 22:14 UTC, x110dc requested changes
There's some unresolved suggestions from @benjaminEwhite . I commented on one of them. Can you address those @gurjittoptal ? Thanks.

2022-06-09 10:09 UTC, gurjittoptal commented on apps/contributions/views.py
> +
defensive  programming. Now its replaced by a conditional to handle the issue of email not being present in  form if it arises.

2022-06-09 23:13 UTC, x110dc approved these changes

2022-06-13 21:39 UTC, merged