Dev-1691 new data source for contributor portal
newsrevenuehub/rev-engine pull request #459
Opened 2022-06-13 19:36 UTC by harsha09

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
Modify existing Endpoint to pull contributions data from stripe instead of application database for contributors portal.

#### What's this PR do?
1. Celery tasks will pull contributions data from stripe and loads it to redis cache when ever a magic link is requested.
2. As contributor access the contributor portal, the stripe data from cache is served.
3. Revenue Program is send as query params from contributor portal.
4. All contributions are faceted by revenue program.

#### Why are we doing this? How does it help us?
Contributor will be able to view contributions done before RevEngine went live.

#### How should this be manually tested?
Request for magic link.
Open the contributor portal with the magic link you got.
You should be able to view the contributions faceted by the revenueprogram.

#### Have automated unit tests been added?
Yes.

#### How should this change be communicated to end users?
NA

#### Are there any smells or added technical debt to note?
Celery worker runs when the user requests a magic link, data gets saved in redis for about 30 mins.
If data is not available in cache / expired the celery worker gets triggered again on contributor portal access.
This causes delay to view contributions and user has to keep on refreshing the page for contributions. This problem needs to be addressed in future.

#### Has this been documented? If so, where?
Not yet

#### What are the relevant tickets? Add a link to any relevant ones.
[DEV-1691]
[DEV-283]
[DEV-1567]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
NA

#### Are there next steps? If so, what? Have tickets been opened for them?
NA

[DEV-1691]: https://news-revenue-hub.atlassian.net/browse/DEV-1691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-06-16 04:30 UTC, x110dc requested changes
This looks great. I'd like @benjaminEwhite or @njharman to review as well.

2022-06-16 04:30 UTC, x110dc commented on apps/contributions/serializers.py
> +    status = serializers.CharField(max_length=10)
I'm not sure exactly how these fields work, but should some be more specific, like a `ChoiceField` since their values can only be a limited set of choices? Like status, payment_type, interval, and maybe card_brand?

2022-06-16 04:30 UTC, x110dc commented on apps/contributions/stripe_contributions_provider.py
> +REDIS_TTL = 60 * 60 * 2
I'd a comment about the unit, i.e. seconds.

2022-06-16 04:30 UTC, x110dc commented on apps/contributions/stripe_contributions_provider.py
> +class InvalidIntervalError(StripeEventIgnoreError):
I'd recommend calling them something besides events here, because that could be confused with actual Stripe events, which isn't what these are, right?

2022-06-16 04:30 UTC, x110dc commented on apps/contributions/stripe_contributions_provider.py
> +            return ContributionInterval.MONTHLY
While these are the only three intervals that NRE supports directly, there could be other intervals in Stripe. I don't think we should assume it's "one time" if it's not monthly or yearly. If one comes across with interval=month and interval_count=2 (bi-monthly) this would call it one-time. I think it's okay for now to throw an exception for an unexpected interval.

2022-06-16 04:30 UTC, x110dc commented on apps/contributions/stripe_contributions_provider.py
> +    def id(self):
This overrides the built-in `id` function. I usually append an underscore to avoid this. I.e. `def id_(self)`

2022-06-16 04:30 UTC, x110dc commented on apps/contributions/stripe_contributions_provider.py
> +            logger.info(ex)
Maybe it can/should be done in a subsequent ticket, but I think we should segregate by RP by including the RP slug in the cache key.

2022-06-16 04:30 UTC, x110dc commented on apps/contributions/stripe_contributions_provider.py
> +    data = caches[CACHE_DB].get(email_id)
Are we distinguishing between a cache result that's empty (because Stripe had no charges for the email) and an entry that's expired/non-existent? 

I'd think for the former we'd want to return the cached results and for the latter we'd want to fetch new results. I'm not sure at what abstraction layer that would be best. Also, given that the cache TTL is longer than the magic link TTL maybe this is an edge case that doesn't need to be solved (yet).

2022-06-16 04:30 UTC, x110dc commented on revengine/settings/dev.py
> +    # See: https://github.com/mirumee/saleor/issues/6926
Did you actually run into an issue here or just coding defensively?

2022-06-16 04:30 UTC, x110dc commented on revengine/settings/dev.py
Shouldn't most/all of this go into `settings/base.py`?

2022-06-16 11:25 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        return serializers.PaymentProviderContributionSerializer
Should the check here be for `isinstance(self.request.user, Contributor)` (in which case `PaymentProviderContributionSerializer`), instead?  Seems like should be same check as `get_queryset`.

2022-06-16 11:25 UTC, benjaminEwhite commented on apps/api/views.py
> +            pull_stripe_contributions_to_cache(email)
Would it make sense for this to be an async Celery task instead of blocking (which might also handle re-pulling from Stripe if cache is empty?)

2022-06-16 11:25 UTC, benjaminEwhite commented on apps/contributions/stripe_contributions_provider.py
> +    data = caches[CACHE_DB].get(email_id)
I was also wondering about this edge case too. If nothing else, there should be a big code comment next to the cache TTL var explaining that the contributions API resource depends on this relationship with magic link TTL in order for there to be results.

Also wondering what happens if a past contributor 1.) gets a magic link to review past contributions; 2) soon after, makes a new contribution; 3.) then follows their magic link to look at their contributions again.  For the duration of the magic link TTL, they'll only be able to get cached results, which might lead someone to believe they haven't been charged again (in which case they might make an additional payment, or otherwise think the the system is flakey).

2022-06-16 11:25 UTC, benjaminEwhite commented on apps/contributions/views.py
> +
Give that contributor users get both a different queryset and a different serializer, and that they will be consuming the results of this resource in a different UI (the contributor dashboard), it makes me wonder if it would make more sense to create a distinct viewset (something like `ContributorContributionsViewSet`) — one that is limited to contributor users for now.

2022-06-16 11:25 UTC, benjaminEwhite commented on apps/api/views.py
> +            pull_stripe_contributions_to_cache(email)
Or, would it make sense to move the stripe pull/cache to the view layer? That would decouple the stripe caching layer TTL from magic link TTL, and also possibly make re-fetching more straightforward.

2022-06-16 16:21 UTC, x110dc commented on apps/contributions/stripe_contributions_provider.py
> +            logger.info(ex)
After thinking about it more, the cache key should probably include something to identify the Stripe account (like Stripe account ID or the PK for it in Django).  Only using the email for the key means that someone could get cache results for an entirely different account.

2022-06-16 16:24 UTC, x110dc commented on apps/contributions/stripe_contributions_provider.py
> +    data = caches[CACHE_DB].get(email_id)
There's already a disclaimer at the top of the portal results addressing this ("Changes made may not be reflected immediately."). But yes, we should think through these scenarios. And thinking about it more, I guess it's not only the TTL for the magic link itself but the TTL for the session created by the magic link. And that is longer than the TTL for the cache. So they could expire while someone is still logged in unless we adjust that TTL to match.

2022-06-16 17:01 UTC, harsha09 commented on apps/contributions/stripe_contributions_provider.py
> +    data = caches[CACHE_DB].get(email_id)
@x110dc: I agree with you, we can make cache TTL to match magic links TTL.
Based on @benjaminEwhite's concern, we can store the `max_contribution_created_date` and query StripeAPI for each request where `created_date > max_contribution_created_date` and store in the cache and return the cached results. This will make things complicate a bit, I made it simple as this will not be a long-term solution.

@x110dc : What would you suggest?

2022-06-16 17:03 UTC, harsha09 commented on revengine/settings/dev.py
> +    # See: https://github.com/mirumee/saleor/issues/6926
@x110dc : I just copied it from `deploy.py` file. I think we can move it to `base.py` if redis cache is available for all deployments in Heroku.

2022-06-16 17:16 UTC, harsha09 commented on apps/api/views.py
> +            pull_stripe_contributions_to_cache(email)
@benjaminEwhite : Added it before sending magic link to improve the response time for user whenever he opens contribution portal.
[DEV-1691] is for enabling stripe contributions, will consider it in [DEV-283].

@x110dc : Your opinion?

2022-06-16 17:19 UTC, harsha09 commented on apps/contributions/views.py
> +
In this case there will be a new endpoint right @benjaminEwhite?

2022-06-16 19:29 UTC, harsha09 commented on apps/contributions/stripe_contributions_provider.py
> +    def id(self):
This doesn't override the `id`built-in function
<img width="545" alt="image" src="https://user-images.githubusercontent.com/3693673/174149743-ff8b91cb-400f-471f-bebd-7b0bd09b7a7b.png">

2022-06-16 19:35 UTC, harsha09 commented on apps/contributions/serializers.py
> +    status = serializers.CharField(max_length=10)
Added `ChoiceField` for status, payment_type, interval and card_brand.

2022-06-16 19:38 UTC, harsha09 commented on apps/contributions/stripe_contributions_provider.py
> +class InvalidIntervalError(StripeEventIgnoreError):
changed it to `ContributionIgnorableError, LMK if this doesn't sounds good

2022-06-16 19:41 UTC, harsha09 commented on revengine/settings/dev.py
It's there in `deploy.py`, not sure why it's so.

2022-06-16 19:45 UTC, harsha09 commented on apps/contributions/stripe_contributions_provider.py
> +REDIS_TTL = 60 * 60 * 2
I've moved it to `base.py`.
`# Set cache TTL to magic link token lifetime so that the stipe contributions in cache will expire with it and contributions will again pulled from stripe and stored in cache with the magic link request.
CONTRIBUTION_CACHE_TTL = CONTRIBUTOR_LONG_TOKEN_LIFETIME`

2022-06-16 20:08 UTC, harsha09 commented on apps/contributions/stripe_contributions_provider.py
> +            logger.info(ex)
We can get revenue program slug from https://github.com/newsrevenuehub/rev-engine/blob/main/apps/api/views.py#L153 but how do we get revenue program slug in https://github.com/newsrevenuehub/rev-engine/blob/main/apps/contributions/views.py#L258

2022-06-16 20:56 UTC, benjaminEwhite commented on apps/contributions/views.py
> +
Yeah, that's what I'm imagining. Contributor portal would be the consumer of this endpoint.

2022-06-22 05:04 UTC, x110dc commented on apps/contributions/stripe_contributions_provider.py
> +            logger.info(ex)
Like I said, we shouldn't use an identifier for the RP, we should use something to identify the Stripe account itself (which can be inferred from the RP). 

As for how you get that, can't you retrieve it from the `request` object? @benjaminEwhite would know.

2022-06-22 05:15 UTC, x110dc commented on apps/contributions/stripe_contributions_provider.py
> +    data = caches[CACHE_DB].get(email_id)
To be clear, I think there are 3 TTLs here:
- the cache
- the magic link (currently hardcoded to 15m)
- the session created by the magic link (currently hardcoded to 3h)

So, as long as the cache is at least as long as the magic link then their results should be there when they visit the link after requesting it. 

For now, I think we could store empty results and return those to the FE. But if the user makes a request and there's nothing in the cache we should fetch new results (and cache them).  I don't think we need to worry at this point about the edge case given we state a disclaimer on the page. 

Let's create a variable for this TTL that we can tune. We can log when there are no cache hits and tune later. A good default could be 30m for now.

2022-06-22 05:18 UTC, x110dc commented on revengine/settings/dev.py
> +    # See: https://github.com/mirumee/saleor/issues/6926
Maybe we just expect `redis://` URLs in `dev.py`.

2022-06-22 05:20 UTC, x110dc commented on revengine/settings/dev.py
I'd think this should go in `base.py` unless @benjaminEwhite knows otherwise.

2022-06-22 05:24 UTC, x110dc commented on apps/api/views.py
> +            pull_stripe_contributions_to_cache(email)
I agree it should be a celery background task. Otherwise it will slow down the the sending of the magic link.

2022-06-22 05:27 UTC, x110dc commented on apps/contributions/stripe_contributions_provider.py
> +        results = stripe.Customer.search(query=f"email:'{email_id}'", limit=MAX_STRIPE_RESPONSE_LIMIT)
I'm confused about which Stripe account this is fetching data from. Where is that being set?

2022-06-22 05:28 UTC, x110dc commented on apps/api/views.py
> +            pull_serialized_stripe_contributions_to_cache(email)
The RP or Stripe account should be a parameter on this so you know which Stripe account to fetch data from.

2022-07-04 16:34 UTC, harsha09 commented on revengine/settings/dev.py
> +    # See: https://github.com/mirumee/saleor/issues/6926
moved it to base.py

2022-07-04 16:35 UTC, harsha09 commented on apps/contributions/stripe_contributions_provider.py
> +    data = caches[CACHE_DB].get(email_id)
I made it 30m

2022-07-04 16:37 UTC, harsha09 commented on apps/contributions/stripe_contributions_provider.py
> +            logger.info(ex)
@x110dc : I'm not able to get that from request object. I've added I've added https://github.com/newsrevenuehub/rev-engine/pull/459/files#diff-58df16d1548a5310067158c74972c58a99aed8e6b29d88808ca3e9bd6e07e18aR65 to get revenue program from query params

2022-07-08 01:18 UTC, benjaminEwhite commented
Closing and reopening to trigger review app creation.

2022-07-08 02:21 UTC, benjaminEwhite requested changes
Left a bunch of inline comments. 

As a general comment, doc strings would be helpful on a lot of the methods and functions, because their purpose and context is not always obvious, and this will only become more so the more time passes.

Running locally, I was able to see confirmation and magic link emails sending (printing to terminal), and contributions showed up in db/django admin. Magic link emails were expired on arrival, so wasn't able to check out that side of things.

In review app environment, was able to make contribution, but didn't appear in db -- probably a problem with webhooks?  I also wasn't able to get confirmation emails or magic link emails to appear, but maybe that's because emails don't send for review apps???

2022-07-08 09:59 UTC, harsha09 commented on revengine/settings/dev.py
> +    # See: https://github.com/mirumee/saleor/issues/6926
@benjaminEwhite 
It's useful to switch the broker between Redis (For Dev environment) or a DummyCache (For UnitTests).
Otherwise UTs are failing due unavailability of Redis.
LMK if there is a different way to approach this problem.

2022-07-08 10:15 UTC, harsha09 commented on apps/contributions/tests/test_views.py
> +        self.rp2 = RevenueProgramFactory(organization=self.org, payment_provider=self.payment_provider2)
@benjaminEwhite 
I was using `.set_up_domain_model` but raised duplicate email exception and few other issues.
And moreover `.set_up_domain_model` will setup lot of things which is not useful for my code, but I forgot to remove inheriting from `AbstractTestCase`.
Now I've changed it to `APITestCase`.

2022-07-08 15:45 UTC, harsha09 commented on apps/contributions/views.py
> +        if isinstance(self.request.user, Contributor):
Got an error due to one PR merged with main and it was returning Contributor object, so in order to resolve the issue I've added this code to return dict if it's a contributor.
I don't exactly remember which PR was that.
I've re-visited it now and there is no error if I remove this code.
Hence removed.

2022-07-08 15:50 UTC, harsha09 commented on apps/contributions/serializers.py
> +    id = serializers.CharField(max_length=255)
It's a stripe object id, in this case it's a charge object and it will start with `ch_*`.
Here is the doc I found out to be helpful https://stripe.com/docs/upgrades#what-changes-does-stripe-consider-to-be-backwards-compatible.

2022-07-08 15:51 UTC, harsha09 commented on apps/contributions/serializers.py
> +    id = serializers.CharField(max_length=255)
I've added the comment as well.

2022-07-08 16:19 UTC, harsha09 commented on apps/api/views.py
> +            revenue_program = RevenueProgram.objects.get(slug=data.get("subdomain"))
@benjaminEwhite 
We are taking revenue program slug from subdomain, I assume subdomain will not form for an rp which doesn't exist.
Still considering a scenario where url is malformed, this might happen.
I've added the code which will raise 404 error if not found.

2022-07-08 16:26 UTC, harsha09 commented on apps/contributions/migrations/0003_alter_contribution_status.py
> +        ("contributions", "0002_contribution_donation_page"),
Done

2022-07-08 16:36 UTC, harsha09 commented on apps/contributions/models.py
> +    WECHAT = "wechat", "wechat"
I just followed `ContributionStatus`. Modified `CardBrand` and `PaymentType`, LMK if `ContributionStatus` also can be modified.

2022-07-08 17:25 UTC, harsha09 commented on apps/contributions/serializers.py
> +    revenue_program = serializers.CharField(max_length=255)
Thank you for reminding this. RevenueProgram.name is of 255 char length in DB schema. We are considering only RevenueProgram.slug here and it's 63 char length.

2022-07-08 17:25 UTC, harsha09 commented on apps/contributions/serializers.py
> +    provider_customer_id = serializers.CharField(max_length=255)
same applies here like charge object id

2022-07-08 17:27 UTC, harsha09 commented on apps/contributions/serializers.py
> +    credit_card_expiration_date = serializers.CharField(max_length=30)
mm/yyyy - keeping it 7

2022-07-08 17:49 UTC, harsha09 commented on apps/contributions/stripe_contributions_provider.py
> +        self.charge = charge
Yeah it violates DRY, made it a common prop

2022-07-08 17:49 UTC, harsha09 commented on apps/contributions/stripe_contributions_provider.py
> +        interval = self.charge.invoice.lines.data[0].plan.interval
To my knowledge I've not seen an invoice without line item. I added the check to make it more robust.

2022-07-08 17:52 UTC, harsha09 commented on apps/contributions/stripe_contributions_provider.py
> +            data.update(cached_data)
It will not because we are updating the data here.
If you visualise the data will be like
{
    "<email-id>-<stripe_account_id>": {
         "ch_000000": {<data>},
         "ch_000001": {<data>},
    }
}

2022-07-08 17:55 UTC, harsha09 commented on apps/contributions/tests/test_stripe_contributions_provider.py
> +            StripeCharge(self.charge).interval
Most primarily to increase UT coverage, otherwise it's failing.
Considering positive and negative cases and testing the interval as well.

2022-07-08 19:32 UTC, harsha09 commented on apps/contributions/stripe_contributions_provider.py
> +    def revenue_program(self):
In the context of contributions revenue_program is slug and we are not using revenue program name anywhere.

2022-07-11 14:05 UTC, benjaminEwhite approved these changes

2022-07-11 14:05 UTC, benjaminEwhite approved these changes

2022-07-13 22:35 UTC, njharman requested changes
tests pass, but under 95% will have to address that. looking at html coverage report 

- org.models.stripe_account_id lacks coverage
- strijp_contributions_provider has some easy to fill coverage gaps
- api/view missing coverage if no RP subdomain

Made few comments / suggestions. Nothing that would "block" approval.

2022-07-13 22:35 UTC, njharman commented on apps/contributions/stripe_contributions_provider.py
> +            yield data[i : i + size]
Only used in generate_chunked_customers_query I believe.  I would have put it inside of that method as a plain function. Or really, just as outer for loop.

2022-07-13 22:35 UTC, njharman commented on apps/contributions/stripe_contributions_provider.py
> +            return datetime.utcfromtimestamp(int(next_attempt))
I'd expect a date, not datetime from something called next_payment_date.  But, maybe the use case is to return datetime, despite name?

2022-07-13 22:35 UTC, njharman commented on apps/contributions/views.py
> +                )
Should we not return some sort of message to user (maybe SPA does?). 
Or, populate cache synchronically here only on cache miss (delay HTTP response until data retrived)? 

Instead of returning empty contributions. which just seems it would confuse user.

2022-07-13 22:35 UTC, njharman commented on revengine/settings/base.py
> +if CACHE_HOST.startswith("rediss"):
is the misspelling "rediss" two esses, correct?

2022-07-13 22:35 UTC, njharman commented on revengine/settings/base.py
> +CONTRIBUTION_CACHE_DB = "default"
Believe we should use specific name, "contribution" or "stripe" rather than "default".

2022-07-14 16:35 UTC, harsha09 commented on revengine/settings/base.py
> +if CACHE_HOST.startswith("rediss"):
It's right, redis url will start with `rediss://<host>:<port>` to communicate over ssl.
This was already there in `deploy.py`, I just moved it to `base.py`.

2022-07-14 16:58 UTC, harsha09 commented on revengine/settings/base.py
> +CONTRIBUTION_CACHE_DB = "default"
We are using Redis as default cache provider and only one instance, this confusion might be due to the naming.
I'm going to rename it to `DEFAULT_CACHE` which is more accurate instead of `CONTRIBUTION_CACHE_DB`.

2022-07-14 17:16 UTC, harsha09 commented on apps/contributions/stripe_contributions_provider.py
> +            return datetime.utcfromtimestamp(int(next_attempt))
Yeah it returns a datetime field just like `last_payment_date = models.DateTimeField(null=True)` in contributions but this is future payment date.

2022-07-14 18:36 UTC, harsha09 commented on apps/contributions/stripe_contributions_provider.py
> +            yield data[i : i + size]
You are right, not using this anywhere else.

2022-07-14 20:58 UTC, x110dc commented on apps/contributions/views.py
> +                )
Can't we just do this call synchronously as Norm suggests if there's a cache miss? It won't be fast but at least they'll get the data. Can just remove the `.delay`, no?

2022-07-15 06:12 UTC, harsha09 commented on apps/contributions/views.py
> +                )
@x110dc 
`task_pull_serialized_stripe_contributions_to_cache` will call `task_pull_charges` asynchronously for a set of 10 (Stripe's MAX customer query values) customers at a time and doesn't return anything.

It'll need some changes to the tasks to make it happen, will it not beat the purpose of a celery task?

2022-07-15 16:08 UTC, harsha09 commented on apps/contributions/views.py
> +                )
@x110dc 
This will also make the response very slow because all calls will be asynchronous as we need to fetch customers first and then corresponding charges.
Instead how about moving this strategy to UI by show loading icon until there is some data in cache with a hard limit? - This doesn't take much time because the cache will be populated incrementally.

2022-07-18 17:53 UTC, njharman commented on apps/contributions/views.py
> +                )
The syncrhously was only on the edge case of cache miss. Idea is, a slow response is better than no/empty response. But, I'm also worrying about a what if that may never happen enough to justify effort.

We have ticket DEV-2092 to look at this with metrics. If we notice problem before then we can fix then.

2022-07-19 19:20 UTC, x110dc approved these changes

2022-07-21 20:59 UTC, closed without merging