DEV-1186 - Only record object changes when triggered by a user action
newsrevenuehub/rev-engine pull request #466
Opened 2022-06-14 22:19 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

##### The problem:

Presently, rev-engine relies on [django-simple-history](https://django-simple-history.readthedocs.io/en/latest/) in order to provide an audit log of changes to model instances.  The primary use case for this functionality is to enable admin users to monitor and at times revert user triggered actions to a model instance. For instance, if an org admin changes the layout for a live page through the org dashboard, or if an admin deletes a contribution in the Django admin, those changes are recorded.

However, `django-simple-history` tracks all changes to model instances, including those generated by system level events like webhooks or signals. In practice, these audit logs end up drowning out the signal (which is user-generated changes), making our object-level audit logs less useful than they might otherwise be. There is not an "off the shelf" way to make `django-simple-history` only record user generated changes.

##### The solution:

In order to clean up object level audit log to make it useful, we should retire [django-simple-history](https://django-simple-history.readthedocs.io/en/latest/) in favor of [django-reversion](https://django-reversion.readthedocs.io/en/stable/).

`django-reversion` can be registered on particular model admin instances and at the view level, which will allow us to only add revision history objects for the limited cases we care about (I've already got a proof of concept of this running locally, and have confirmed that changes through org dashboard and django admin cause new revisions, while updating model through `python manage.py shell` does not). 

`django-reversion` will also nicely support [DEV-86 - Hub admin can revert versions of a donation page](https://news-revenue-hub.atlassian.net/browse/DEV-86). It does so out of the box, and there is also a related package ([django-reversion-compare](https://github.com/jedie/django-reversion-compare)) that provides an interface that allows a user to more easily compare the differences between any given two revisions.

*Additionally*, I propose that we retire [django-safedelete](https://github.com/makinacorpus/django-safedelete), as django-reversion will give allow us to revert both revisions and deletions.  This will allow us to consolidate audit logs and reversion of deletions into a single package and admin utility.

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested?

#### Have automated unit tests been added?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-1186](https://news-revenue-hub.atlassian.net/jira/software/c/projects/DEV/boards/3?modal=detail&selectedIssue=DEV-1186)

[DEV-86](https://news-revenue-hub.atlassian.net/browse/DEV-86)

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

On initial merge of this PR, and on any subsequent registration of a model with django-reversion, there is a management command that needs to be run. [See here](https://django-reversion.readthedocs.io/en/stable/commands.html#createinitialrevisions).

#### Are there next steps? If so, what? Have tickets been opened for them?

2022-06-16 21:43 UTC, njharman requested changes
Would like the [createinitialrevisions ](https://django-reversion.readthedocs.io/en/stable/commands.html#createinitialrevisions) command mentioned in README. That's something we will forget I bet.

Could not get migrations to apply after 
> git co main
> poetry install
> make nuclear
> docker-compose up -d
> ./manage migrate
> ./manage createsuperuser
> git co DEV-1186...
> poetry install
> ./manage migrate
>
>  django.db.utils.ProgrammingError: column "organization_id" of relation "contributions_historicalcontribution" does not exist

But wiping db, and doing migrations from DEV-1186 works.

2022-06-16 21:43 UTC, njharman commented on pyproject.toml
> +django-simple-history = "^3.1.1"
Deserves comment here why simple-history kept and when it can be removed.

2022-06-17 14:55 UTC, benjaminEwhite commented
@njharman I did a cleanup of `README.md` and then added a section giving all the details re: django-reversion.

2022-06-20 19:12 UTC, njharman approved these changes
lgtm

2022-06-22 18:03 UTC, benjaminEwhite commented
Closing in order to destroy current review so I can get a fresh one to investigate the migration error happening in CI on build/deploy for review app.

2022-06-22 18:14 UTC, benjaminEwhite commented
Closing and reopening again because want to confirm that change i'm making to bootstrap-review-app.py works as expected.

2022-06-25 00:24 UTC, merged