dev-1920 dashboard side-bar and top-bar
newsrevenuehub/rev-engine pull request #470
Opened 2022-06-19 12:03 UTC by gurjittoptal

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested?

#### Have automated unit tests been added?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them?

2022-06-21 14:22 UTC, benjaminEwhite requested changes
Left a few inline comments.

Some additional notes:

- The comps call for Roboto font for nav elements, but this is using Montserrat
- Clicking on the signout takes to root and 404. I'm pretty sure that's pre-existing, but might be worth changing behavior so logout redirects to login as long as some of the log out code is being touched anyways.
- Probably should have follow up tickets for descoped features. Namely, the top bar elements that were mentioned in the JIRA ticket as being descoped for now.
- I suspect this is a temporary issue, but when clicking on a style or  page, when you get taken to the edit view, there's a flash of white content, and it's pretty abrupt. If there's an easy way to animate that transition so it feels smoother, that would be nice.
- There should be some unit tests, at a minimum describing what elements we expect to find in the side and top bar, and demonstrating their expected configuration (for instance, that the href for contributions is the contributions URL, etc).

2022-06-21 14:22 UTC, benjaminEwhite commented on spa/src/components/dashboard/topbar/DashboardTopbar.js
> +      <S.TopMenu onClick={logout} whileHover={{ scale: 1.05, x: -3 }} whileTap={{ scale: 1, x: 0 }}>
This element needs a margin-right (or else parent needs padding). The sign out text gets cut off.

<img width="1784" alt="Screen Shot 2022-06-21 at 9 24 16 AM" src="https://user-images.githubusercontent.com/960351/174820474-6060979b-64e0-408a-951f-63bfd18ad3eb.png">

2022-06-22 02:57 UTC, gurjittoptal commented on spa/src/components/dashboard/Dashboard.js
> +    <div>
can't use fragment here so instead used an outer element for consistency, to handle styling later.

2022-06-22 03:08 UTC, gurjittoptal commented
> Left a few inline comments.
> 
> Some additional notes:
> 
>     * The comps call for Roboto font for nav elements, but this is using Montserrat
yes, i did not change as it will be a follow up ticket. Likely we change the site-wide default font and this fixes
> 
>     * Clicking on the signout takes to root and 404. I'm pretty sure that's pre-existing, but might be worth changing behavior so logout redirects to login as long as some of the log out code is being touched anyways.
PR for this was already merged to main. 
> 
>     * Probably should have follow up tickets for descoped features. Namely, the top bar elements that were mentioned in the JIRA ticket as being descoped for now.
https://news-revenue-hub.atlassian.net/browse/DEV-1950 handles the next steps
> 
>     * I suspect this is a temporary issue, but when clicking on a style or  page, when you get taken to the edit view, there's a flash of white content, and it's pretty abrupt. If there's an easy way to animate that transition so it feels smoother, that would be nice.
hmm. i see that and shall fix it in a follow up of DEV-1950. issue is updated
> 
>     * There should be some unit tests, at a minimum describing what elements we expect to find in the side and top bar, and demonstrating their expected configuration (for instance, that the href for contributions is the contributions URL, etc).
so, right now all elements are exactly like they were earlier. but, yes we need to refactor a bit for more unit tests.

2022-06-23 18:01 UTC, x110dc submitted a review, later dismissed
Hi @gurjittoptal can you add the unit tests that @benjaminEwhite requested. Thanks!

2022-06-29 17:41 UTC, benjaminEwhite reviewed
This is moving in good direction. Left some comments, but also wanted to reply to comment you left in JIRA here.

> However i did keep the hasAccess in the smaller functions for a few reasons. First, we can unit-test the featureFlag tests much more easier, and secondly the code is more readable.
>
> in the future there will be at least 3 more components inserted and this way we can isolate and test while keeping the sidebar code compact and clean.
>
> ```
><S.DashboardSidebar>
>	<S.NavList role="list" data-testid="nav-list" aria-labelledby="sidebar-label-id">
>		...
>		<DashboardHomeNav ...  />
>		<ContentSectionNav ... />
>		<ContributionSectionNav ... />
>		<AnalyticsNav ...  />
>		<ColorThemeNav ...  />
>		...
>	</S.NavList>
></S.DashboardSidebar>
> ```

In general, unit tests only get more as components further down the tree get smarts in them. For the case of unit testing around feature flags in particular, as currently implemented, an isolated test of `ContentSectionNav` when `hasContentSectionAccess` is set to false actually doesn't prove the feature flag is correctly implemented / hasn't reverted. All it demonstrates is that the component respects an attribute called `hasContentSectionAccess`, which really should be called `shouldDisplay`.  The parent context for `ContentSectionNav` may or may not set that attribute with respect to feature flag state.  Which means, if you want to build confidence about the business logic around content section access insofar as it effects the sidebar, that test should be on the sidebar element itself, which is what makes the call to `flagIsActiveForUser`.

Regarding readability, nothing requires putting a bunch of conditionals in the JSX. In the example you provided, you could instead do something like this (in this example I'm assuming that each sidebar components:

```
const sidebarElements = [
    [<DashboardHomeNav foo={bar} />, true],
    [<ContentSectionNav disabled={disabled} />, flagIsActiveForUser(CONTENT_SECTION_ACCESS_FLAG_NAME, featureFlags)],
    [<ContributionSectionNav disabled={disabled} />, flagIsActiveForUser(CONTRIBUTIONS_SECTION_ACCESS_FLAG_NAME, featureFlags)],
    // ...etc.
  ].filter(([section, shouldDisplay]) => shouldDisplay);

  return (
    <S.DashboardSidebar>
      <S.NavList role="list" data-testid="nav-list" aria-labelledby="sidebar-label-id">
        {/* ... */}
        {sidebarElements}
```

2022-06-29 17:41 UTC, benjaminEwhite commented on spa/src/components/dashboard/sidebar/DashboardSidebar.js
> +          shouldAllowDashboard={shouldAllowDashboard}
Also here, I don't think we want `ContentSectionNav` having a notion of dashboard access. Instead it should only care about whether or not it's in a disabled state. Indirectly, it may be in a disabled state because of dashboard access state, but in the future, it could be some other condition that might cause it to be in disabled state.

2022-06-29 17:41 UTC, benjaminEwhite commented on spa/src/components/dashboard/sidebar/DashboardSidebar.styled.js
> +import { ICONS } from 'assets/icons/SvgIcon';
`ICONS` is not used anywhere and should be removed.

2022-06-29 17:41 UTC, benjaminEwhite commented on spa/src/components/dashboard/sidebar/navs/ContentSectionNav.js
> +function ContentSectionNav({ hasContentSectionAccess, shouldAllowDashboard }) {
Same comment here about `shouldAllowDasbhoard` — think it should be `disabled`.

2022-06-29 17:41 UTC, benjaminEwhite commented on spa/src/components/dashboard/sidebar/navs/ContributionSectionNav.js
> +function ContributionSectionNav({ hasContributionsSectionAccess, shouldAllowDashboard }) {
Same comments re: `hasContributionSectionAccess` and `shouldAllowDashboard`. The former logic should live in higher order component, and `shouldAllowDashboard` should be renamed to something more semantic like `disabled`.

2022-06-29 17:41 UTC, benjaminEwhite commented on spa/src/components/dashboard/sidebar/navs/ContributionSectionNav.test.js
> +});
Same comment here -- the relevant test would be enabled vs. disabled state, and logic for whether or not its displayed should live higher up.

2022-06-29 18:48 UTC, gurjittoptal commented on spa/src/components/dashboard/Dashboard.js
> +      {isEditPage ? null : <DashboardTopbar shouldAllowDashboard={getShouldAllowDashboard()} />}
Fair Point.

See this
https://github.com/newsrevenuehub/rev-engine/blob/main/spa/src/components/dashboard/Dashboard.js#L61

As we have moved logout to topbar, sidebar does not need to know of getShouldAllowDashboard(), because none of pages/styles/contribution routes are allowed if !getShouldAllowDashboard()

So all navs become jsx functions with no inputs/ conditional logic.

2022-06-29 18:50 UTC, gurjittoptal commented on spa/src/components/dashboard/sidebar/DashboardSidebar.styled.js
> +import { ICONS } from 'assets/icons/SvgIcon';
removed

2022-06-29 18:50 UTC, gurjittoptal commented on spa/src/components/dashboard/sidebar/navs/ContentSectionNav.test.js
> +});
agreed. its made into a totally dumb one with just jsx

2022-06-29 18:52 UTC, gurjittoptal commented on spa/src/components/dashboard/sidebar/navs/ContentSectionNav.js
> +function ContentSectionNav({ hasContentSectionAccess, shouldAllowDashboard }) {
not relevant anymore as these navs are just jsx blocks

2022-06-29 18:52 UTC, gurjittoptal commented on spa/src/components/dashboard/Dashboard.js
> +        {isEditPage ? null : <DashboardSidebar shouldAllowDashboard={getShouldAllowDashboard()} />}
See above comment

2022-06-29 19:49 UTC, benjaminEwhite reviewed
@gurjittoptal changes look great. There are a couple references to `shouldAllowDashboard` to be removed, but then I'm 👍 (and after you do those, no need for me to re-review — you can pass on to Daniel).

2022-06-29 19:49 UTC, benjaminEwhite commented on spa/src/components/dashboard/sidebar/navs/ContentSectionNav.js
> +    </S.NavSection>
Given recent commit, `shouldAllowDashboard` references should be removed here.

2022-06-29 19:49 UTC, benjaminEwhite commented on spa/src/components/dashboard/sidebar/navs/ContributionSectionNav.js
> +    </S.NavSection>
Also should remove `shouldAllowDashboard` here.

2022-06-29 19:49 UTC, benjaminEwhite commented on spa/src/components/dashboard/sidebar/DashboardSidebar.test.js
> +  render(<DashboardSidebar shouldAllowDashboard={true} />);
Need to update this to remove `shouldAllowDashboard={true}`.

2022-06-29 19:58 UTC, gurjittoptal commented on spa/src/components/dashboard/sidebar/DashboardSidebar.test.js
> +  render(<DashboardSidebar shouldAllowDashboard={true} />);
done

2022-07-07 17:18 UTC, benjaminEwhite approved these changes

2022-07-20 13:01 UTC, benjaminEwhite approved these changes
LGTM.

2022-07-21 20:58 UTC, closed without merging