DEV-1856 | logs should use %s formatting
newsrevenuehub/rev-engine pull request #479
Opened 2022-06-24 21:26 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

N/A

#### What's this PR do?

- Adds flake8-logging-format as a dev dependency and to `.pre-commit-config.yaml`. 
- Cleans up log string formatting in 15 Python files

#### Why are we doing this? How does it help us?

Will enable log grouping in Sentry

#### How should this be manually tested?

N/A

#### Have automated unit tests been added?

N/A

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

N/A

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-1856 | logs should use %s formatting](https://news-revenue-hub.atlassian.net/browse/DEV-1856)

[DEV-1977 | Reduce Sentry Noise for initial public release](https://news-revenue-hub.atlassian.net/jira/software/c/projects/DEV/boards/3?modal=detail&selectedIssue=DEV-1977)

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No

#### Are there next steps? If so, what? Have tickets been opened for them?

No

2022-06-28 19:58 UTC, njharman requested changes
re flake8-logging, the "extra=" logging argument is new to me. Seems best method (more consistent with f-string). Why was % formatting selected instead? [I originally suggested it, as at the time it was the way I knew of sentry grouping]

2022-06-28 19:58 UTC, njharman commented on .flake8
> +    G003,   # Logging statements should not use + concatenation for their first argument
-1 on ignoring this. Where do we use concatenation? Or more to point, why shouldn't it be rewritten to not use concatenation. Curious I checked, doesn't see there are any concatenations???

Removing G003 and running flake8 didn't find any violations of G003. removing all the GXXX didn't show any violations.

Oddly, did find a bunch of other flake8 issues... see team-eng post and ticket

2022-06-28 19:58 UTC, njharman commented on apps/common/utils.py
> +            logger.exception()
This changes log level from warning to error. The "template" I've used for logging exception data is

> logger.[level]("msg", exc_info=error)  

See https://docs.python.org/3/library/logging.html#logging.debug

2022-06-28 19:58 UTC, njharman commented on apps/organizations/models.py
> +                logger.exception(
Changes log level from warning to error.

[I don't like logger.exception() it violates zen of python ought to be one way to do things, it obscures what log level this will be logged at, and denies the ease of changing log level that the warn/error/etc methods provide.

Bah humbug!]

2022-06-28 19:58 UTC, njharman commented on apps/organizations/tests/test_org_models.py
> +        mock_logger.exception.assert_called_once()
Changes log level

2022-06-28 19:58 UTC, njharman commented on apps/slack/slack_manager.py
> +                logger.exception("SlackApiError. HubSlackIntegration has invalid token")
Was it intentional to change a few of these here to log full exception/traceback vs just the slack_error.response. But further on, in send_org_message, still logging just the response and not full traceback?

2022-06-28 20:22 UTC, benjaminEwhite commented on apps/slack/slack_manager.py
> +                logger.exception("SlackApiError. HubSlackIntegration has invalid token")
Yes, intentional. I figured there's no reason to log only part of the exception, given that the new flake8 settings prohibit error + exception reference in the message.

2022-06-29 15:49 UTC, benjaminEwhite commented
> re flake8-logging, the "extra=" logging argument is new to me. Seems best method (more consistent with f-string). Why was % formatting selected instead? [I originally suggested it, as at the time it was the way I knew of sentry grouping]

@njharman - Yes, this is why we are making the move to enforce %s. From what [I've read online ](https://discuss.python.org/t/safer-logging-methods-for-f-strings-and-new-style-formatting/13802/18)(though can't find this directly mentioned in Sentry docs), the only way to get consistent grouping is via %s formatting.  It seems there are also some security concerns around using f-strings in logs ([see here](https://discuss.python.org/t/safer-logging-methods-for-f-strings-and-new-style-formatting/13802/18)) .

I found [where `extra=""` is mentioned in the Sentry docs](https://docs.sentry.io/platforms/python/guides/logging/), but I didn't get the impression that extra data plays into grouping at all, just that the extra data will available in the event data, and that you can search by it. 

Unless you know differently, @njharman , IIUC the only way to get grouping is by using %s formatting.

2022-06-29 16:19 UTC, benjaminEwhite commented on apps/common/utils.py
> +            logger.exception()
Good catch. Changed back to warning, and added a msg that has domain as %s arg.

2022-06-29 16:32 UTC, benjaminEwhite commented on apps/organizations/tests/test_org_models.py
> +        mock_logger.exception.assert_called_once()
reverted to warning.

2022-06-29 18:18 UTC, njharman approved these changes
lgtm, ship it!

re "% format" vs "extra="; I don't know, and didn't read the Sentry docs on this (recently).  "% formatting is what I've always used and know it solves this issue. Just wondering/hoping extra= was "better" alternative.

2022-06-29 20:33 UTC, x110dc approved these changes
Added a tiny commit to unpin the flake8 dep in `pyproject.toml`

2022-06-29 20:45 UTC, merged