Dev 1545 env vars
newsrevenuehub/rev-engine pull request #494
Opened 2022-06-30 00:00 UTC by njharman

#### What's this PR do?
Reorganize settings into categories; django, apps, 1st party, etc
Document settings, apps.
Standardize on os.getenv over os.environ.get
Move all environment access to settings.

#### Why are we doing this? How does it help us?
Documentation.  Onboarding new devs, even old devs trying to understand code/debug/etc. 
Clearer to have all the "external" environment access in one place.

#### How should this be manually tested?
N/A

#### Have automated unit tests been added?
N/A

#### How should this change be communicated to end users?
N/A

#### Are there any smells or added technical debt to note?
N/A

#### Has this been documented? If so, where?
It is documentation!

#### What are the relevant tickets? Add a link to any relevant ones.
[DEV-1545]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no, should not be. But since lots of environment variable code touched, there is a higher chance of regression/introduced bugs.

#### Are there next steps? If so, what? Have tickets been opened for them?
no, but going forward we should add settings to appropriate sections and add comments linking settings to their apps/purpose.

2022-06-30 20:44 UTC, x110dc requested changes

2022-06-30 20:44 UTC, x110dc commented on revengine/settings/base.py
> +ENVIRONMENT = os.getenv("ENVIRONMENT", "dev")
This should be set to `unknown` so we can distinguish Sentry alerts from unconfigured systems from DEV. I encourage devs to set `ENVIRONMENT` locally to their names.

2022-06-30 20:44 UTC, x110dc commented on revengine/settings/base.py
> +# First in this list will be default.
"Djanog" typo.

2022-06-30 20:44 UTC, x110dc commented on revengine/settings/base.py
> +# CURRENCIES is not Djanog setting, is used in models, related to I18N.
"Djanog" typo again.

2022-06-30 20:44 UTC, x110dc commented on revengine/settings/base.py
> +STATIC_ROOT = os.path.join(BASE_DIR, "public/static")
Should we make the link to 3.2 instead of 3.0? Not that important.

2022-06-30 20:44 UTC, x110dc commented on revengine/settings/base.py
> +    "solo",  # Single row models, e.g. HubSlackInteration.
Typo "HubSlackInteration"

2022-06-30 20:44 UTC, x110dc commented on revengine/settings/base.py
> +    "waffle",  # Djanog feature flag support.
"Djanog" typo.

2022-06-30 20:44 UTC, x110dc commented on revengine/settings/base.py
> +THUMBNAIL_PRESERVE_FORMAT = True
Duplicate line.

2022-06-30 20:44 UTC, x110dc commented on revengine/settings/base.py
> +STRIPE_API_VERSION = "2020-08-27"  # Stripe API Target Version
Could add a link here to https://stripe.com/docs/upgrades#api-changelog

2022-06-30 20:44 UTC, x110dc commented on revengine/settings/base.py
> +### Heroku Settings
These are only used in the bootstrapping script for review apps. Should probably note that here.

2022-06-30 20:44 UTC, x110dc commented on revengine/settings/base.py
> +# TODO: These appear to be for django-phonenumber-field which isn't in apps, isn't imported, but is in poetry.
Can we add tickets for these TODOs?

2022-06-30 20:44 UTC, x110dc commented on revengine/settings/base.py
> +# TODO: USER_TTL is not referenced anywhere in codebase.
Can we create a ticket for this TODO?

2022-06-30 20:44 UTC, x110dc commented on revengine/settings/base.py
> +BAD_ACTOR_API_URL = os.getenv("BAD_ACTOR_API_URL", "https://bad-actor-test.fundjournalism.org/v1/bad_actor/")
I don't think we should have this default in the code.

2022-06-30 20:44 UTC, x110dc commented on revengine/settings/base.py
> +BAD_ACTOR_API_KEY = os.getenv("BAD_ACTOR_API_KEY", "testing_123")
Is there a reason to have a default here?

2022-06-30 22:16 UTC, njharman commented on revengine/settings/base.py
> +ENVIRONMENT = os.getenv("ENVIRONMENT", "dev")
Done

2022-06-30 22:20 UTC, njharman commented on revengine/settings/base.py
> +STATIC_ROOT = os.path.join(BASE_DIR, "public/static")
yes

2022-06-30 22:23 UTC, njharman commented on revengine/settings/base.py
> +# TODO: USER_TTL is not referenced anywhere in codebase.
cutting it instead. also not mentioned anywhere in ./site-packages/...

2022-06-30 22:24 UTC, njharman commented on revengine/settings/base.py
> +BAD_ACTOR_API_URL = os.getenv("BAD_ACTOR_API_URL", "https://bad-actor-test.fundjournalism.org/v1/bad_actor/")
replaced with empty default

2022-06-30 22:25 UTC, njharman commented on revengine/settings/base.py
> +BAD_ACTOR_API_KEY = os.getenv("BAD_ACTOR_API_KEY", "testing_123")
replaced with empty default

2022-06-30 22:28 UTC, njharman commented on revengine/settings/base.py
> +### Heroku Settings
That's not true.

HEROKU_APP_NAME in common/utils.py test ofr same. HEROKU_BRANCH in teardown-review-app.py. CF_ZONE_NAME in all of those.

2022-06-30 22:31 UTC, njharman commented on revengine/settings/base.py
> +# TODO: These appear to be for django-phonenumber-field which isn't in apps, isn't imported, but is in poetry.
To what? Investigate if django-phonenumber is used or not?

Rather just delete it now, Or replace todo with explanation if you know it is needed.

2022-06-30 22:38 UTC, njharman commented on revengine/settings/base.py
> +BAD_ACTOR_API_URL = os.getenv("BAD_ACTOR_API_URL", "https://bad-actor-test.fundjournalism.org/v1/bad_actor/")
Actually removing either default caused test failures. Removing them and fixing tests should be separate ticket.

2022-06-30 22:38 UTC, njharman commented on revengine/settings/base.py
> +BAD_ACTOR_API_KEY = os.getenv("BAD_ACTOR_API_KEY", "testing_123")
Actually removing either default caused test failures. Removing them and fixing tests should be separate ticket.

2022-07-01 20:59 UTC, x110dc requested changes

2022-07-01 20:59 UTC, x110dc commented on revengine/settings/base.py
> +# TODO: These appear to be for django-phonenumber-field which isn't in apps, isn't imported, but is in poetry.
AFAIK it's not used. Let's delete.

2022-07-01 20:59 UTC, x110dc commented on revengine/settings/base.py
> +BAD_ACTOR_API_URL = os.getenv("BAD_ACTOR_API_URL", "https://bad-actor-test.fundjournalism.org/v1/bad_actor/")
I'll open a ticket for it.

2022-07-21 20:59 UTC, closed without merging