Nrh 12 organization revenue
newsrevenuehub/rev-engine pull request #5
Opened 2021-04-26 14:55 UTC by JeremyGibson

Adds the models for Organization, RevenueProgram

Plan and Feature are modeled but may be substantially changed by a forthcoming ticket, but were needed for the relationship to organization.

- [ ] Tests

2021-04-26 20:08 UTC, michael-caktus commented on apps/organizations/admin.py
> +    fieldsets = organization_fieldset
Why this pattern?
`fieldsets = [model]_fieldset`?

2021-04-26 20:28 UTC, JeremyGibson commented
Its really a just in case thing. Just in case a different set of fields is configured and appended. So you could have fieldsets = organization_fieldsets + runtime_fieldsets

On Apr 26 2021, at 4:08 pm, Michael Ashton ***@***.***> wrote:
>
>
> @michael-caktus commented on this pull request.
> In apps/organizations/admin.py (https://github.com/newsrevenuehub/rev-engine/pull/5#discussion_r620611281):
>
> > + "org_addr1",
> + "org_addr2",
> + ("org_city", "org_state", "org_zip"),
> + )
> + },
> + ),
> + ("Plan", {"fields": ("non_profit", "plan", "stripe_account", "salesforce_id")}),
> + )
> +
> + readonly_fields = ["slug"]
> +
> + list_display = ["name", "slug", "plan", "org_state"]
> +
> + list_filter = ["name", "plan", "org_state"]
> +
> + fieldsets = organization_fieldset
> Why this pattern?
> fieldsets = [model]_fieldset?
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub (https://github.com/newsrevenuehub/rev-engine/pull/5#pullrequestreview-645070873), or unsubscribe (https://github.com/notifications/unsubscribe-auth/AAWUFYQQFGZ7T6KHM4MWDITTKXB3NANCNFSM43TBYKSA).
>

2021-04-27 13:52 UTC, copelco commented on apps/organizations/tests/factories.py
> +        organization = kwargs.get("organization", None)
Isn't passing related objects supported by default with FactoryBoy? For example: https://github.com/deardurham/dear-petition/blob/master/dear_petition/petition/conftest.py#L44

2021-04-27 13:55 UTC, JeremyGibson commented on apps/organizations/tests/factories.py
> +        organization = kwargs.get("organization", None)
Cool. I ran into this problem awhile ago and have just been following the pattern. I'll refactor

2021-04-28 12:46 UTC, michael-caktus commented on apps/organizations/models.py
> +        return
What's this?

2021-04-28 18:09 UTC, JeremyGibson commented on apps/organizations/models.py
> +        return
removed.

2021-05-05 13:47 UTC, michael-caktus requested changes

2021-05-05 14:23 UTC, JeremyGibson commented on apps/organizations/views.py
> +        return serializers.OrganizationListSerializer
Hmm. Any need to leave this open for access through the DRF api browser?

2021-05-06 17:12 UTC, michael-caktus approved these changes

2021-05-06 20:55 UTC, merged