DEV-1577_spa_payment_provider_not_provided_handler
newsrevenuehub/rev-engine pull request #501
Opened 2022-07-02 12:54 UTC by gurjittoptal

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
draft, to be discussed.

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested?

#### Have automated unit tests been added?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them?

2022-07-04 15:39 UTC, benjaminEwhite requested changes
I think we may want a slightly different approach here. If I understand correctly, this PR makes it so that the only state the app can return is connected, for payment provider, regardless of whether or not a provider is in fact connected on the backend. In that case, it would make more sense to remove the payment provider set up logic altogether.

I also noted in the review app, that when you remove the payment provider from an RP, it is no longer possible to load existing pages in the editor.

<img width="1440" alt="Screen Shot 2022-07-04 at 11 23 19 AM" src="https://user-images.githubusercontent.com/960351/177185867-cdb99072-25b8-441e-a617-a0a339c125ab.png">

2022-07-04 15:39 UTC, benjaminEwhite commented on spa/cypress/integration/10 - connect.spec.js
> +/*
This whole file should be deleted.

2022-07-04 15:39 UTC, benjaminEwhite commented on spa/src/components/Main.js
> +  // Given we are tying payment_provider at RP level, all this can be cleaned.
Should this be a todo (with associated JIRA ticket)?

2022-07-04 15:39 UTC, benjaminEwhite commented on spa/src/utilities/getGlobalPaymentProviderStatus.js
> +  return PP_STATES.CONNECTED;
This seems strange to have a function that invariably returns the connected state. If connected state is always going to be true, then the conditional logic around this should be entirely removed.

2022-07-04 15:39 UTC, benjaminEwhite commented on spa/src/utilities/getGlobalPaymentProviderStatus.js
>  function getStripePaymentManagerProviderStatus(accountIdPresent, accountVerified) {
Realize this is not touched by this PR, but this is not used anywhere and can be removed.

2022-07-04 15:39 UTC, benjaminEwhite commented on spa/src/utilities/getGlobalPaymentProviderStatus.js
> +  }*/
Realize this commented code is not touched by this PR, but should be removed.

2022-07-04 16:29 UTC, gurjittoptal commented
@benjaminEwhite 
re: I also noted in the review app, that when you remove the payment provider from an RP, it is no longer possible to load existing pages in the editor.

This has to be handled in the backend. i.e. If an RP cannot be created unless a payment provider is provided, a payment-provider SHOULD-NOT be allowed to be physically deleted from the backend IF it is attached to an RP.

I think we should keep the front-end code clean of this logic.

2022-07-05 03:41 UTC, gurjittoptal commented on spa/src/components/Main.js
> +  // Given we are tying payment_provider at RP level, all this can be cleaned.
yes, connected_state code has to be cleaned as payment_provider is moved to rp level via a new jira.

2022-07-05 03:41 UTC, gurjittoptal commented on spa/src/utilities/getGlobalPaymentProviderStatus.js
> +  return PP_STATES.CONNECTED;
yes. via new jira ticket. see comment above.

2022-07-05 03:42 UTC, gurjittoptal commented on spa/src/utilities/getGlobalPaymentProviderStatus.js
> +  }*/
comment above.

2022-07-05 03:42 UTC, gurjittoptal commented on spa/src/utilities/getGlobalPaymentProviderStatus.js
>  function getStripePaymentManagerProviderStatus(accountIdPresent, accountVerified) {
comment above.

2022-07-07 03:11 UTC, benjaminEwhite requested changes
Given that we'll be revisiting the flows around payment provider set up soon anyways, I still would lean towards removing the payment provider logic entirely in this PR, rather than commenting out most of the existing getGlobalPaymentProviderStatus function body and having it return a static value.

There's not much value in keeping this old code around, and if for some reason we ever want to go back and look at it, it will be in the repo history anyways.

I've also suggested another possibility which is removing the call to getGlobalPaymentProviderStatus in Main.js and just hard coding the PP_STATES.CONNECTED value into the useState instantiation, along with a comment explaining why.  

Between the two options, I'd lean more toward the first.

@gurjittoptal , I agree that this PR doesn't necessitate new unit tests, as it's removing functionality, and we'll want to add unit tests to new business logic around payment provider set up, which will be landing soon.

2022-07-07 03:13 UTC, benjaminEwhite commented on spa/cypress/integration/10 - connect.spec.js
> +/*
I don't understand why this diff shows up as only adding a line at bottom of this file since in `main` this file is not commented out.

🤷 🤷‍♀️

2022-07-07 08:12 UTC, gurjittoptal commented on spa/src/components/Main.js
>      getGlobalPaymentProviderStatus(JSON.parse(localStorage.getItem(LS_USER)))
@benjaminEwhite 
_on "I still would lean towards removing the payment provider logic entirely in this PR"_

i agree. I did cleanup all the code in commit [1cd3b7e9](https://github.com/newsrevenuehub/rev-engine/pull/501/commits/1cd3b7e95f80d0b9aa7fbe882425c326079da134)

But we should do this after new-nav  is merged.

It also does make code cleaner and more readable which is a good thing

[dashboard.js - dev-1577](https://github.com/newsrevenuehub/rev-engine/blob/DEV-1577_spa_payment_provider_not_provided_handler/spa/src/components/dashboard/Dashboard.js)
vs
[dashboard.js - main](https://github.com/newsrevenuehub/rev-engine/blob/main/spa/src/components/dashboard/Dashboard.js)

2022-07-21 20:58 UTC, closed without merging