Dev 1854 allow contributors not in nre
newsrevenuehub/rev-engine pull request #515
Opened 2022-07-12 18:11 UTC by harsha09

#### What's this PR do?
1. Creates a new contributor in NRE if the contributor doesn't exist already and sends magic link.
2. Users who aren't recognised by NRE will be able to get magic_link and able to access contributor portal.
3. Right now users who are not recognised by NRE will be able to see blank contributor portal page, when [DEV-1691] is merged they should be able to view contributions from stripe directly.

#### Why are we doing this? How does it help us?
When [DEV-1691] is merged, users should not be limited to access contributor portal.

#### How should this be manually tested?
Request a magic link with new user who is not a contributor in NRE.
Access contributor portal using the magic link.

#### Have automated unit tests been added?
Not added any UTs but fixed few as they were breaking with the code change.

#### How should this change be communicated to end users?
NA

#### Are there any smells or added technical debt to note?
NA

#### Has this been documented? If so, where?
NA

#### What are the relevant tickets? Add a link to any relevant ones.
[DEV-1854]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them?
[DEV-1691] needs to be completed.

2022-07-12 20:11 UTC, x110dc approved these changes

2022-07-12 21:07 UTC, benjaminEwhite requested changes
As noted, IMO the contributor creation logic should live in the view layer,  not the serializer layer.

I also think there should be a single, simple view test that demonstrates that this view creates a contributor if they do not already exist. That's important and not very obvious business logic, and should therefore be tested.

2022-07-12 21:07 UTC, benjaminEwhite commented on apps/api/serializers.py
> +        contributor, _ = Contributor.objects.get_or_create(email=data.get("email"))
Having a validate method create a new instance seems like an anti-pattern to me. IMO, serializer validation methods shouldn't have any side effects like that, and this business logic should live in the view layer.

Seems like it would be pretty straightforward to refactor this serializer so its only fields are `email` and `subdomain`. Then in `apps.api.views.RequestContributorTokenEmailView`, after line 146, do the get or create for the contributor, and create token after that step, instead of pulling out of serializer data.

2022-07-13 16:57 UTC, harsha09 commented on apps/api/serializers.py
> +        contributor, _ = Contributor.objects.get_or_create(email=data.get("email"))
`access` key in the response body is needed for the client to process.
I've extracted out the `Contributor` creation to view layer. Also I've removed token generation and setting the access token in `validate` method as it's doing more than one thing other than validation.

2022-07-13 18:08 UTC, benjaminEwhite commented on apps/api/tests/test_views.py
> +        self.assertEqual(Contributor.objects.filter(email=target_email).count(), 1)
```suggestion
        # this view creates a contributor if none exists
        self.assertEqual(Contributor.objects.filter(email=target_email).count(), 1)
```

2022-07-13 18:08 UTC, benjaminEwhite approved these changes
Added a suggestion to test code that adds comment explaining why. 

Approved.

2022-07-14 21:20 UTC, merged