[WIP] DEV-2037 | API support for user creation
newsrevenuehub/rev-engine pull request #530
Opened 2022-07-18 18:44 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested?

#### Have automated unit tests been added?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them?

2022-07-20 17:32 UTC, njharman requested changes

2022-07-20 17:32 UTC, njharman commented on apps/users/tests/test_views.py
> +        self.assertIn("Datetime has wrong format", response.json()["accepted_terms_of_service"][0])
~Would maybe use pytest.paramaterize. Test these two; field missing, field blank and when fal...~  oh, it's probably a check box and blank is the "false" response, eh?

2022-07-20 17:32 UTC, njharman commented on apps/users/tests/test_views.py
> +    def test_create_when_email_already_taken(self):
Do we also need similar already taken test for PATCH?

2022-07-20 17:32 UTC, njharman commented on apps/users/serializers.py
> +    def update(self, instance, validated_data):
If email changes, should we set email_verified to False?

2022-07-20 17:32 UTC, njharman commented on apps/users/tests/test_views.py
> +        self.assertIsNotNone((user := get_user_model().objects.filter(id=data["id"]).first()))
I don't like this use of := one bit.

2022-07-20 17:32 UTC, njharman commented on apps/users/serializers.py
> +        read_only_fields = [
Is this just our additions to user model / it's layered on top of what Django default
Should is_active, is_staff, ... others be added to read_only_fields

2022-07-20 17:32 UTC, njharman commented on apps/users/tests/test_views.py
> +        self.assertFalse(data["email_verified"])
check email_verified on user object (perhaps in addition to data)
would also check that password and email set on user. Because we overrode code for former and both are listed in AC.

2022-07-20 17:32 UTC, njharman commented on apps/users/serializers.py
> +    def update(self, instance, validated_data):
What if any is the Business Rule around updating accepted_terms_of_service to False (or even resetting date of acceptance).  I did not see it defined in AC (maybe new ticket).
allow, error?

2022-07-20 17:32 UTC, njharman commented on apps/users/tests/test_views.py
> +    def test_create_when_no_password(self):
Can all these password tests be genericized and applied to patch as well? 
Should test, at least (and I think sufficient), that our password code is called for patch.

2022-07-20 17:32 UTC, njharman commented on apps/users/tests/test_views.py
> +    def test_cannot_partial_update_when_email_not_verified(self):
I agree should not be able to update until verified email. But I did not see in AC. was it somewhere else.  Think worth adding somewhere; communicating to/ validating with business folks that is desired behavior.

2022-07-20 17:32 UTC, njharman commented on apps/users/tests/test_views.py
> +    def test_partial_update_when_not_my_user(self):
Depending on responses to some other comments. Probably addition tests for patch.

- password
- bad email
- accepted_terms_of_service
-

2022-07-20 19:06 UTC, benjaminEwhite commented on apps/users/serializers.py
> +        password = validated_data.pop("password") if "password" in validated_data else None
Changed.

2022-07-20 19:07 UTC, benjaminEwhite commented on apps/emails/templates/nrh-org-account-creation-verification-email.html
> +	<p>Please <a href="{verification_url}">click on this link</a>to verify your email address.
Fixing

2022-07-21 13:44 UTC, benjaminEwhite commented on apps/users/serializers.py
> +            return []
Both should be returning empty list. That's some "haste makes waste" on my end, as I was rushing to get done on last day of sprint.  Updating the other one to return empty list.

2022-07-21 13:45 UTC, benjaminEwhite commented on apps/users/serializers.py
> +            return None
Fixing.

2022-07-21 14:18 UTC, benjaminEwhite commented on apps/users/tests/test_views.py
> +    def test_create_when_email_already_taken(self):
Adding test

2022-07-21 15:28 UTC, benjaminEwhite commented on apps/users/views.py
> +            raise ValidationError(detail={"password": exc.messages})
Yeah, I understand that in the general case, but here, the validation error should be predictable, as we're narrowly using Django's built in p/w validation. I suppose we could explicitly check that messages are expected, and only send those that are, and if unexpected, send a generic.

2022-07-21 16:26 UTC, benjaminEwhite commented on apps/users/views.py
> +            raise ValidationError(detail={"password": exc.messages})
Pushing up a change that ensures message is in expected list, else defaults to generic.

2022-07-21 16:34 UTC, benjaminEwhite commented on apps/users/tests/test_views.py
> +        self.assertFalse(data["email_verified"])
Done, in commit about to push up.

2022-07-21 16:41 UTC, benjaminEwhite commented on apps/users/serializers.py
> +    def update(self, instance, validated_data):
Good question. Consulting with Mariclare to figure this out.

2022-07-21 20:59 UTC, closed without merging

2022-07-22 19:45 UTC, njharman commented on apps/users/tests/test_views.py
> +        self.assertIsNotNone((user := get_user_model().objects.filter(id=data["id"]).first()))
Bah! With great power, comes great responsibility.

2022-07-31 15:52 UTC, benjaminEwhite commented on apps/users/tests/test_views.py
> +    def test_cannot_partial_update_when_email_not_verified(self):
This is indeed business logic.

2022-07-31 15:54 UTC, benjaminEwhite commented on apps/users/tests/test_views.py
> +    def test_partial_update_when_not_my_user(self):
Added tests for password and email. Will need to get clarification on accepted_terms_of_service, and will likely handle in follow up.