redo DEV-1577
newsrevenuehub/rev-engine pull request #543
Opened 2022-07-21 23:35 UTC by x110dc

2022-08-01 00:32 UTC, gurjittoptal approved these changes

2022-08-01 20:20 UTC, benjaminEwhite requested changes
Left a couple of inline comments.

I ran locally and tried two different paths. 

First, I tried setting a payment provider as unverified and removing stripe_product_id (both in Django admin). After doing that, I was able to edit pages and do everything expected from dashboard. However, I was not prevented from publishing pages, which is one of the AC.

Second, I tried deleting a payment provider entirely (after temporarily changing some backend code in DonationPageFullDetailSerializer, which would otherwise fail if there is no payment provider).  In this state, I was still able to navigate around the dashboard, but preview of the donation page in editor has a bug.

<img width="879" alt="Screen Shot 2022-08-01 at 4 17 13 PM" src="https://user-images.githubusercontent.com/960351/182239126-3d376f3b-749c-4997-9f83-8d30a2c083f8.png">

In this state, I was also able to publish a page, and in both cases when trying to access the published pages via public-facing URL, I got a 404.

2022-08-01 20:20 UTC, benjaminEwhite commented on spa/src/components/errors/ChunkErrorBoundary.js
> +        </ErrorS.Logout>
Was unable to test this locally because I don't know how to get app in this state.

This should also be tested.

2022-08-02 10:46 UTC, gurjittoptal commented on spa/src/components/errors/ChunkErrorBoundary.js
> +        </ErrorS.Logout>
cypress test has been added for this.

2022-08-02 10:47 UTC, gurjittoptal commented on spa/src/components/dashboard/Dashboard.js
> -        {isEditPage ? null : getShouldAllowDashboard() && <DashboardSidebar />}
Agreed and fixed.

2022-08-02 10:55 UTC, gurjittoptal commented
@benjaminEwhite 
The scope of this ticket changed as backend work is needed for non-payment-provider RP support/ other case.

So this PR cleans-up/ factors code to allow users to login without seeing an error message
Ref: 
https://news-revenue-hub.atlassian.net/browse/DEV-1577?focusedCommentId=49228


What you mentioned above can be handled will be handled in ticket below
https://news-revenue-hub.atlassian.net/browse/DEV-2042

2022-08-03 15:11 UTC, benjaminEwhite requested changes
Test looks good.

Locally, I tested live donation pages with payment provider stripe verified set to False, and deleting payment provider. In both cases, you get a 404 page, which seems right.

Testing the org portal app with an RP admin user, I was still able to publish/add pages when stripe verified is set to False. Not sure if this is desired behavior, but seems like might not be ideal because an org user could think they have a live page but end user gets 404 because stripe is not verified.

Also tried deleting RP's payment provider, and logging in as RP admin. I was able to load initial dashboard screen, but get blank screen with empty error message when accessing page editor. Am able to click to create new page, but after initial modal submits, there's error in console, and the modal remains, with no indication to user that something has gone wrong.

<img width="1093" alt="Screen Shot 2022-08-03 at 11 00 41 AM" src="https://user-images.githubusercontent.com/960351/182643548-684de9b7-b2ac-43a8-af06-7a390de86d26.png">

<img width="1141" alt="Screen Shot 2022-08-03 at 11 05 36 AM" src="https://user-images.githubusercontent.com/960351/182643645-6d2e501a-68ad-4c42-a585-c09012e5a68a.png">

2022-08-05 15:07 UTC, benjaminEwhite approved these changes
I'm 👍 on this, with the understanding that [DEV-2042](https://news-revenue-hub.atlassian.net/browse/DEV-2042) is a follow up task, that is inclusive of merging in this PR: https://github.com/newsrevenuehub/rev-engine/pull/577

2022-08-08 23:38 UTC, x110dc reviewed
LGTM

2022-08-10 22:40 UTC, merged