Dev 2044 accounts screens v2
newsrevenuehub/rev-engine pull request #556
Opened 2022-07-26 21:13 UTC by gurjittoptal

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
DRAFT

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2022-08-01 15:10 UTC, benjaminEwhite requested changes
Screens look good (and I checked at different viewport sizes).

Left a good number of inline comments.

Have a few higher level comments as well.

First, since this is such a "form heavy" set of changes, I think this might be the right moment to introduce a form management package along with form validation.  I'm most experienced with [react-hook-form](https://react-hook-form.com/) plus [Yup.js](https://github.com/jquense/yup) for validation.  

The argument for using these packages (or something like them) is that it will standardize our approach for handling forms, validation, and displaying error states. It also means we won't have to do things like code-from-scratch for email validation or similar.  Another argument for is that react-hook-form, in particular, will allow us to simplify some of our components because it encourages users to use uncontrolled form inputs, which means that we won't have to track state for our inputs and errors (we'll get that via its registration interface).

I don't have a view of whether or not this suggestion should block pushing out this set of changes — could happen in a follow up — but I do think we should do this as part of the work on account creation rather than kicking can down the road.

Second comment is around use of the `fetch-reducer.js` pattern. In some of the components, it looks like that's being used to manage loading/error etc. state, while in others, it's being handled by internal state management. I think we should be consistently using one or the other. I may be wrong, but I don't get the impression we're getting too much from the `fetch-reducer` approach.

Final comment, at some point, I'd like us to start transitioning to using something like [react-query](https://tanstack.com/query/v4/?from=reactQueryV3&original=https://react-query-v3.tanstack.com/) for making API requests. Among other reasons, it provides a dependable, robust API for handling loading vs. not loading state.  This doesn't necessarily need to be the moment we introduce that package, but could make sense.

2022-08-02 11:46 UTC, gurjittoptal commented on spa/src/components/DashboardRouter.js
> +//const Login = lazy(() => componentLoader(() => import('components/authentication/Login')));
done

2022-08-02 12:03 UTC, gurjittoptal commented on spa/src/components/account/common/leftbar/Leftbar.js
> +}
It was kept because i thought its quite possible  messaging might get different in the future.

2022-08-02 12:06 UTC, gurjittoptal commented on spa/src/components/account/common/elements/InputAccount.js
> +    <S.Input ref={ref} value={value} onChange={onChange} type={type} data-testid={props.testid} />
Thats used because we using the base input and we need to assign a different id for various form elements e.g. email, password1, password2 to test this.

2022-08-02 12:07 UTC, gurjittoptal commented on spa/src/components/account/common/elements/InputWrapped.js
> +function InputWrapped({ value, onChange, type, label, disabled, instructions, testid, errorMessage }) {
It also handles four things
1. Label
2. Instructions
3. Error Messages
4. For passwords the text toggle.

2022-08-09 01:09 UTC, gurjittoptal commented on spa/cypress/integration/05 - page-view-analytics.spec.js
> +const HUB_TRACKED_PAGES_REQURING_NO_LOGIN = [SIGN_IN, CONTRIBUTOR_ENTRY, CONTRIBUTOR_VERIFY];
done

2022-08-09 01:45 UTC, gurjittoptal commented on spa/src/components/account/SignUp/SignUp.test.js
> +
invalid email unit test is inserted.

2022-08-15 15:55 UTC, benjaminEwhite approved these changes
Have a couple of small suggestions, based on commits since I last reviewed.

Please have a look at those and respond, and then this can move forward (keeping in mind that there's now a separate ticket tracking the feedback I provided re: standardizing form validation and data fetching: https://news-revenue-hub.atlassian.net/browse/DEV-2207).

2022-08-16 21:11 UTC, x110dc requested changes
I'd like to see the changes Ben requested about form validation and related included in this PR. Also there were several comments resolved without leaving a response. Please indicate how a comment was resolved. This requirement is listed in our policies. Lastly, this PR description is inadequate as sections like "What's this PR do?" are blank. This needs more work.

2022-08-16 21:22 UTC, gurjittoptal commented
@x110dc Form validations, everything was done via custom code and has unit tests to cover it up.

And Ben had a lot of comments which were similar in nature and were resolved.

The PR creates Account Screen skeletons, the test-links show that so text was not added to PR description 

@benjaminEwhite fyi

2022-09-09 02:02 UTC, closed without merging