[WIP] DEV-1372 | Contributor portal links expired on arrival
newsrevenuehub/rev-engine pull request #564
Opened 2022-08-01 17:24 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2022-08-01 22:07 UTC, njharman approved these changes
lgtm; 99% coverage

Did not fill out pre-review checklist

Guess we have no way to automate pulling link from email and seeing that it 200's against "test" server.

2022-08-02 20:14 UTC, x110dc requested changes
Following the testing instructions I contributed (https://billypenn-dev-1372.revengine-review.org/nrhadmin/contributions/contribution/37/change/) but when I followed the email link to the portal it said it was expired:

<img width="464" alt="Screen Shot 2022-08-02 at 3 13 17 PM" src="https://user-images.githubusercontent.com/1091864/182464812-58f3ed67-6a23-406d-b34f-ec687c6e52e8.png">

2022-08-03 21:42 UTC, x110dc approved these changes

2022-08-03 21:42 UTC, x110dc commented on apps/api/tests/test_views.py
> +
That is one sophisticated, beautiful test!

2022-08-04 17:33 UTC, merged