DEV-2133 | Make ReactAppView not fail when no social_meta
newsrevenuehub/rev-engine pull request #569
Opened 2022-08-02 18:41 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

Fixes a bug in ReactAppView whereby the view would fail when a RevenueProgram didn't have an associated SocialMeta instance (which lies in one-to-one relation).

Adds a test for this case.

#### Why are we doing this? How does it help us?

So donation pages won't be broken for RPs that don't have social meta.

#### How should this be manually tested? Please include detailed step-by-step instructions.

In NRH admin, find the RP for a live donation page. Delete that RP's social meta instance (which can be done from the detail view for the RP).  

Now visit the donation page. It should load. If you inspect the head of the HTML file in developer tools, none of the social meta related values should appear (the values are pictured below, but this is what you shouldn't see on this page):

<img width="817" alt="Screen Shot 2022-08-02 at 2 39 22 PM" src="https://user-images.githubusercontent.com/960351/182449426-1f1d7a37-fe6d-4f84-8988-05cdafb77c69.png">

#### Have automated unit tests been added? If not, why?

Yes

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-2133](https://news-revenue-hub.atlassian.net/jira/software/c/projects/DEV/boards/3?modal=detail&selectedIssue=DEV-2133)

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No

2022-08-08 01:29 UTC, njharman approved these changes
Looks good. Tests pass. Could not check coverage because ./revengine/ isn't part of test coverage (fix that in other ticket/follow on to DEV-1808)

The except branch is covered so lgtm!

2022-08-08 01:31 UTC, njharman commented
Needs to have main merged into it

2022-08-09 02:16 UTC, x110dc requested changes
One minor request.

2022-08-09 02:16 UTC, x110dc commented on pyproject.toml
> +pytest-mock = "^3.8.2"
This should be a dev dep, no?

2022-08-11 21:06 UTC, x110dc commented on pyproject.toml
> +pytest-mock = "^3.8.2"
This is here but it's also in dev deps. I removed it from here.

2022-08-12 20:06 UTC, x110dc approved these changes

2022-08-12 20:06 UTC, merged