Dev 2198 show connect to stripe setup if applicable
newsrevenuehub/rev-engine pull request #593
Opened 2022-08-13 19:00 UTC by gurjittoptal

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2022-08-15 14:50 UTC, GuiMend requested changes

2022-08-15 14:50 UTC, GuiMend commented on spa/src/components/Main.js
> +  const [userDetails, setuserDetails] = useState();
Camel case missed
```suggestion
  const [userDetails, setUserDetails] = useState();
```

2022-08-15 14:50 UTC, GuiMend commented on spa/src/components/dashboard/connectStripe/ConnectStripeElements.js
> +  const { open, handleClose } = useModal(true);
Shouldn't we check the cookies to see if the default modal state should be open or closed as we are setting cookies for when it's closed?

Probably won't need the `ConnectStripeElements` component in this case

2022-08-15 14:50 UTC, GuiMend commented on spa/src/components/dashboard/connectStripe/ConnectStripeElements.js
> +          Check out our <S.StripeFAQ href="/">Stripe Connection FAQ</S.StripeFAQ>.
Add a TODO to update FAQ link?

2022-08-15 14:50 UTC, GuiMend commented on spa/src/components/dashboard/connectStripe/ConnectStripeElements.styled.js
> +  border-radius: 10px;
Could add this `10px` to the theme file in `muiBorderRadius`?

2022-08-15 14:50 UTC, GuiMend commented on spa/src/components/dashboard/connectStripe/ConnectStripeElements.styled.js
> +export const h2 = styled.h2`
h1 would probably be the correct html semantics

2022-08-15 14:50 UTC, GuiMend commented on spa/src/components/dashboard/connectStripe/ConnectStripeElements.styled.js
> +    border-radius: 6px;
Here as well `muiBorderRadius`.
Naming convention could be the same as Mui: `xs, sm, md, lg, ...`

2022-08-15 14:50 UTC, GuiMend commented on spa/src/components/dashboard/connectStripe/ConnectStripeElements.styled.js
> +  font-size: 16px;
We have the `theme > fontSizesUpdated.md`

2022-08-15 14:50 UTC, GuiMend commented on spa/src/components/dashboard/connectStripe/ConnectStripeElements.styled.js
> +    font-size: 14px;
fontSizesUpdated.sm

2022-08-15 14:50 UTC, GuiMend commented on spa/src/components/dashboard/connectStripe/ConnectStripeElements.styled.js
> +    font-size: 18px;
fontSizesUpdated.lg

2022-08-15 14:50 UTC, GuiMend commented on spa/src/components/dashboard/connectStripe/ConnectStripeToast.js
> +})(Tooltip);
Can move this to the `styled` file?

2022-08-15 14:50 UTC, GuiMend commented on spa/src/components/dashboard/connectStripe/ConnectStripeToast.js
> +        <S.ConnectStripeToastCollapsed data-testid={'connect-stripe-toast-collapsed'} onClick={handleExpand}>
If it's just a string shouldn't it be `"` instead of `{'` ? I guess pre-comit doesn't change this, but in all the other component properties it's like that. Example: `<RETooltip title="Minimize" placement="bottom-end">`
```suggestion
        <S.ConnectStripeToastCollapsed data-testid="connect-stripe-toast-collapsed" onClick={handleExpand}>
```

2022-08-15 14:50 UTC, GuiMend commented on spa/src/components/dashboard/connectStripe/ConnectStripeToast.styled.js
> +//import lighten from 'styles/utils/lighten';
Delete line?
```suggestion
```

2022-08-15 14:50 UTC, GuiMend commented on spa/src/components/dashboard/connectStripe/ConnectStripeToast.styled.js
> +  font-size: 14px;
fontSizesUpdated.sm

2022-08-15 14:50 UTC, GuiMend commented on spa/src/components/dashboard/connectStripe/ConnectStripeToast.styled.js
> +  font-size: 12px;
fontSizesUpdated.xs

2022-08-15 14:50 UTC, GuiMend commented on spa/src/components/dashboard/connectStripe/ConnectStripeToast.styled.js
> +    font-size: 12px;
fontSizesUpdated.xs

2022-08-15 14:50 UTC, GuiMend commented on spa/src/components/dashboard/connectStripe/userHasSingleRPNotConnectedToStripe.js
> +    // Add a check for the RP Payment Provider when api returns
Add `TODO:`, there are some toold in VS Code that identifies all `TODO:`s in project. It helps to know where changes need to be done 
```suggestion
    // TODO: Add a check for the RP Payment Provider when api returns
```

2022-08-15 17:19 UTC, gurjittoptal commented on spa/src/components/dashboard/connectStripe/ConnectStripeElements.js
> +  const { open, handleClose } = useModal(true);
Do note only one of the two(toast or modal) needs to be shown.

ConnectStripeElements just ensures one of the two is shown

Cookie check happens here
https://github.com/newsrevenuehub/rev-engine/blob/DEV-2198-connect-to-stripe-setup-one-time-modal/spa/src/components/dashboard/connectStripe/ConnectStripeElements.js#L51

multiple ways of doing this.

2022-08-15 17:19 UTC, gurjittoptal commented on spa/src/components/dashboard/connectStripe/ConnectStripeToast.js
> +})(Tooltip);
I tried this but styles were not being applied as expected. will check once more in evening.

2022-08-16 01:10 UTC, gurjittoptal commented
@GuiMend left two comments, others are resolved.

2022-08-16 18:53 UTC, GuiMend approved these changes
Have two small somments.

The rest is looking good 👍 
![image](https://user-images.githubusercontent.com/9381325/184957590-9a29ac45-2562-4d56-82f9-cb4a96c40ef5.png)
![image](https://user-images.githubusercontent.com/9381325/184957007-b08af3cf-5072-4f4b-a01d-2dcfc9fc8b22.png)
![image](https://user-images.githubusercontent.com/9381325/184957110-18ef0760-9245-4ff9-87c5-bbe382c649c3.png)

2022-08-16 19:48 UTC, gurjittoptal commented on spa/src/components/dashboard/connectStripe/ConnectStripeElements.js
> +        <S.Button>Connect to Stripe</S.Button>
This got pushed up to a declaration

`// TODO: Insert Stripe FAQ Link
const CONNECT_STRIPE_FAQ_LINK = '';`

https://github.com/newsrevenuehub/rev-engine/pull/593/files#diff-496c5fa4596e87b96bb71f54c5b3fa11c5525d1f12d0afefd9762396e5ac31c7R15

2022-08-16 19:54 UTC, gurjittoptal commented on spa/src/styles/themes.js
> +    xxxl: '28px'
hmm. yeah, agreed readable. and updated.

2022-08-16 20:03 UTC, GuiMend approved these changes
LGTM 👍

2022-09-08 18:48 UTC, x110dc approved these changes

2022-09-08 18:48 UTC, merged