DEV-2196 Revengine Coverage
newsrevenuehub/rev-engine pull request #600
Opened 2022-08-16 21:49 UTC by njharman

#### What's this PR do?
Add test coverage, only 4 files < 95% coverage. Almost got to 98%

- Add revengine to coverage report.
- Cut revengine/storages.py unused, untested.
- Increase revengine/* coverage to 100%.
- Increase apps/* coverage to get total coverage > 98%
- Cut things that were untested, broken, and unused.
- Do not ignore testing simple things like __str__(). Fixed several errors.

#### Why are we doing this? How does it help us?
Less bugs

#### How should this be manually tested? Please include detailed step-by-step instructions.
N/A

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
No

#### Have automated unit tests been added? If not, why?
Indeed

#### How should this change be communicated to end users?
N/A

#### Are there any smells or added technical debt to note?
There's a bunch of pragma no-cover on code that should probably be tested.

Had weird issues with ApplePayDomain, missing RevenueProgram._get_host().

#### Has this been documented? If so, where?
N/A

#### What are the relevant tickets? Add a link to any relevant ones.
[DEV-2196]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
Discovered maybe tests are making network connections [DEV-2244]

2022-08-16 23:15 UTC, x110dc requested changes
One question and one minor change request.

2022-08-16 23:15 UTC, x110dc commented on revengine/tests/test_celery.py
> +def test_debug_task():
What's this testing? Maybe I'm misunderstanding.

2022-08-16 23:15 UTC, x110dc commented on revengine/urls.py
> +if settings.DEBUG:  # prgma: no cover Is covered, but reimport confuses coverage
pragma misspelling

2022-08-17 04:52 UTC, njharman commented on revengine/tests/test_celery.py
> +def test_debug_task():
The debug_task, obviously! :)

I don't know why debug_task() exists, but it wasn't covered. It consists only of a print statement. This just tests function runs without error. Mostly just "covers" the code.

2022-08-17 19:16 UTC, x110dc approved these changes

2022-08-17 19:17 UTC, merged