Dev 2071 remove quarantine from contributions
newsrevenuehub/rev-engine pull request #604
Opened 2022-08-19 12:16 UTC by harsha09

Please fill out each section even if it's just with "N/A"

#### What's this PR do?
Stop showing flagged contributions in the contributions dashboard.
Removes UI elements (filters, table columns) related to flagged contributions.

#### Why are we doing this? How does it help us?
This is a sub-step involved in quarantine management. Subsequent ticket will create another view to show the quarantine and the user will be able to directly manage Approval/Rejection of flagged contributions.

#### How should this be manually tested? Please include detailed step-by-step instructions.
Login to the app -> Click on Contributions dashboard.
Flagged contributions shouldn't be displayed.
`Flagged` and `Rejected` filters shouldn't be shown.
`Date flagged` and `Auto-resolution Date` shouldn't be shown in table.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
Yes

#### Have automated unit tests been added? If not, why?
Yes

#### How should this change be communicated to end users?
May be using user-manual.

#### Are there any smells or added technical debt to note?
No

#### Has this been documented? If so, where?
Not yet

#### What are the relevant tickets? Add a link to any relevant ones.
[DEV-2071]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
NA

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
[DEV-2250]
[DEV-1619]

2022-08-22 19:18 UTC, GuiMend requested changes
I have a few comments regarding the code, but the functionality is working as expected

Flags are not showing 👍 
![image](https://user-images.githubusercontent.com/9381325/185999781-0ec32b39-ff78-4e7b-ba25-3d5f0c057550.png)

2022-08-22 19:18 UTC, GuiMend commented on spa/src/components/donations/Donations.js
> +import { PAYMENT_STATUS_EXCLUDE_IN_CONTRIBUTIONS } from 'constants';
```suggestion
import { PAYMENT_STATUS, PAYMENT_STATUS_EXCLUDE_IN_CONTRIBUTIONS  } from 'constants';
```

2022-08-22 19:18 UTC, GuiMend commented on spa/src/components/donations/filters/StatusFilter.js
> +                <S.StatusBadge
I would prefer to use something like the `filter` method:
You can add the `!` to choose if you want to select the subset, or if you want to exclude the subset values.

![image](https://user-images.githubusercontent.com/9381325/186000505-6608f058-1266-4afe-bb73-b4e88f7019d0.png)
```suggestion
          {STATUS_FILTERS.filter(status => excludeStatusFilters.includes(status)).map(
            (status) => (
                <S.StatusBadge
```

2022-08-22 19:18 UTC, GuiMend commented on spa/src/components/donations/filters/StatusFilter.js
> +                </S.StatusBadge>
Also, I didn't see this when I edited this page, but could you rename `f` for `status` or another more descriptive name? 
`f` is really hard to understand what it stands for 
```suggestion
                  key={status}
                  data-testid={`status-filter-${status}`}
                  selected={filter.includes(status)}
                  onClick={() => handleFilterChange('status', status)}
                >
                  <StatusCellIcon status={status} showText size="sm" />
                </S.StatusBadge>
```

2022-08-23 18:40 UTC, njharman approved these changes
[Only reviewed Python backend]

Code 100% covered.
It doesn't seem that the QA instructions include checking AC 4 or 5. Which seem important to check.

2022-08-24 17:35 UTC, GuiMend approved these changes
Changes made 👍

2022-08-24 23:00 UTC, x110dc approved these changes

2022-08-26 22:22 UTC, x110dc approved these changes

2022-08-26 22:38 UTC, merged