[draft] DEV-1849: Page edits do not appear on page save unless user refreshes the page
newsrevenuehub/rev-engine pull request #606
Opened 2022-08-19 20:52 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
N/A

#### What's this PR do?
Fixes bugs

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2022-08-23 13:44 UTC, gurjittoptal reviewed
Changes look good, but on preview I still see thumbnails not being refreshed ( due to caching )

Specifically
DEV-1849.7 and DEV-1941

Its mostly a caching issue so likely should be resolved via a separate ticket.
**But do note** that the new image *2 below, css was not applied properly. Thats' something that can be investigated as part of this ticket

Check 
https://washingtoncitypaper-dev-1849.revengine-review.org/cheesecake
vs
https://storage.googleapis.com/rev-engine-media/Washington%20City%20Paper/page_screenshots/Cheesecake_latest.png *2

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/30353391/186173971-3ee9c5cc-07d8-4832-adca-334b7c65c3bf.png">'

<img width="968" alt="image" src="https://user-images.githubusercontent.com/30353391/186174914-d91ae596-6d90-40e6-965c-ef15bf9e1805.png">



----

On localhost, all looks good.

2022-08-23 14:57 UTC, gurjittoptal approved these changes
Approving, the scope of tickets is met.

There is likely a caching issue, and an issue of css not being applied (seen once ). both can be handled via separate tickets.

2022-08-25 13:43 UTC, benjaminEwhite requested changes
This looks good overall and was able to confirm locally that it fixes the bug.

It would be good to have at least one test that shows that when you make a change in the editor, the page preview updates. I just looked over `02 - donation-page-edit.spec.js`, and doesn't look like there were any pre-existing tests to that effect ( 👎 ). I think a minimal test would be to edit one attribute in the editor, click the checkmark, and then assert that the page preview has changed as expected.

2022-08-25 13:43 UTC, benjaminEwhite commented on spa/src/components/pageEditor/PageEditor.js
> +      if (CAPTURE_PAGE_SCREENSHOT) data = await addScreenshotToCleanedData(data, page.name);
I know that was existing code, but appeared in diff. Might as well use const.

2022-08-25 13:43 UTC, benjaminEwhite commented on spa/src/elements/modal/GlobalConfirmationModal.js
> +    text: ''
Maybe have a more descriptive var name here so understand this is the main message / CTA in the modal.

2022-08-25 14:41 UTC, GuiMend commented on spa/src/components/pageEditor/PageEditor.js
> +      if (CAPTURE_PAGE_SCREENSHOT) data = await addScreenshotToCleanedData(data, page.name);
Can't use `const` here because we are reassigning data on the next line `addScreenshotToCleanedData`

2022-08-25 14:55 UTC, benjaminEwhite requested changes
Was able to get page thumbnails working locally after @GuiMend explained i needed to set `export REACT_APP_CAPTURE_PAGE_SCREENSHOT=true` in my `.envrc` file.

With that in mind, I think it would be a good idea to add a `.envrc.example` file to this repo that has default/dummy values, and then in README.md, tell devs to copy that file to `.envrc` and update required values.

2022-08-25 17:08 UTC, GuiMend commented
@benjaminEwhite , comments addressed.
Added cypress test for preview mode + envrc example file

2022-08-25 22:25 UTC, benjaminEwhite approved these changes
Just need to remove the `.only` from the Cypress test and then good to go. No need for me to re-review after that change.

2022-08-25 22:25 UTC, benjaminEwhite commented on spa/cypress/integration/02 - donation-page-edit.spec.js
> +    it.only('should update donation page view with new content and display it in preview mode', () => {
Looks like you forgot to remove this `.only` after getting your test working.

2022-08-25 22:25 UTC, benjaminEwhite commented on spa/cypress/integration/02 - donation-page-edit.spec.js
> +      cy.getByTestId('s-page-heading').contains(newHeading);
👍

2022-09-01 17:40 UTC, x110dc requested changes
@GuiMend There's a merge conflict here that needs resolution. I think those lines can just be removed altogether.

2022-09-01 17:40 UTC, x110dc commented on scripts/heroku-postdeploy.sh
> +CREATE TABLE config_denylistword (id integer not null, word heroku_ext.citext not null);
Why was this changed? I think neither line should be here, so probably merge conflict resolution needs to happen?

2022-09-01 20:09 UTC, GuiMend commented
@x110dc I resolved the conflict by letting it the same as is in `main` already. Not sure how those changes got to this PR, I didn't edit that file, must have been a merge from before

2022-09-01 23:25 UTC, x110dc approved these changes

2022-09-01 23:26 UTC, merged