Dev 805 add tooltips to page editor menu
newsrevenuehub/rev-engine pull request #615
Opened 2022-08-24 16:41 UTC by gurjittoptal

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
This PR will add tooltips for the buttons in Edit Page. 

#### What's this PR do?
Adds tooltips for View, Edit, Save, Delete and Back buttons in Edit Page

#### Why are we doing this? How does it help us?
Better UX/UI

#### How should this be manually tested? Please include detailed step-by-step instructions.
tbd

#### Did this PR make changes to the user interface that may require changes to the user-facing docs? 
no

#### Have automated unit tests been added? If not, why?
no. 

#### How should this change be communicated to end users?
n/a

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
n/a

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-805

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2022-08-30 15:26 UTC, GuiMend requested changes
Typo and a few small changes

2022-08-30 15:26 UTC, GuiMend commented on spa/src/components/pageEditor/PageEditor.js
> +                  tootTipText="View"
Typo
```suggestion
                  tooltipText="View"
```

2022-08-30 15:26 UTC, GuiMend commented on spa/src/components/pageEditor/PageEditor.styled.js
> +width:50px`;
Seems a bit off:
```suggestion
export const PageEditorBackButton = styled.div`
  text-align: center;
  height: 50px;
  width: 50px;
`;
```

2022-08-30 15:26 UTC, GuiMend commented on spa/src/elements/buttons/CircleButton.js
> +  const { tootTipText } = props;
Can add the prop to the first line:


function CircleButton({ icon, type, color, onClick, disabled, loading, children, `tooltip,` ...props }) {
----

2022-08-30 15:26 UTC, GuiMend commented on spa/src/elements/buttons/CircleButton.styled.js
> +export const CircleButtonDiv = styled.div``;
If it's just a `div` I would rather not have a styled component, it makes things more difficult to understand at a glance

2022-08-30 15:26 UTC, GuiMend commented on spa/src/elements/buttons/CircleButton.js
> +      <S.CircleButtonDiv>
Better to just add a div instead of styled component
```suggestion
      <div>
```


Did you try removing this div altogether?
```suggestion
```

2022-08-30 15:34 UTC, gurjittoptal commented on spa/src/elements/buttons/CircleButton.js
> +  const { tootTipText } = props;
fixed

2022-08-30 15:34 UTC, gurjittoptal commented on spa/src/components/pageEditor/PageEditor.styled.js
> +width:50px`;
fixed.

2022-08-30 15:34 UTC, gurjittoptal commented on spa/src/elements/buttons/CircleButton.js
> +      <S.CircleButtonDiv>
updated.

2022-08-30 15:35 UTC, gurjittoptal commented on spa/src/elements/buttons/CircleButton.styled.js
> +export const CircleButtonDiv = styled.div``;
fixed.

2022-08-30 15:35 UTC, gurjittoptal commented on spa/src/components/pageEditor/PageEditor.js
> +                  tootTipText="View"
fixed

2022-08-31 13:38 UTC, GuiMend approved these changes
Have another small suggestion. No need for re-review.

Tooltips working 👍 
![image](https://user-images.githubusercontent.com/9381325/187691823-4f61dfd5-039a-4ba0-bcf2-dda72d56e6a6.png)

2022-08-31 13:38 UTC, GuiMend commented on spa/src/components/pageEditor/PageEditor.js
> +                  toolTipText="View"
**Tooltip** is a single word, so no need for it to be **camelCase**

2022-08-31 13:41 UTC, GuiMend requested changes
Actually @gurjittoptal, would you mind creating a unit test for this?
We can add a `fireEvent` for hover and check if the tooltip is rendering

2022-08-31 14:37 UTC, GuiMend requested changes

2022-08-31 14:37 UTC, GuiMend commented on spa/src/elements/buttons/CircleButton.test.js
> +describe('Tooltips on CrcleButton', () => {
```suggestion
describe('Tooltips on CircleButton', () => {
```

2022-08-31 14:37 UTC, GuiMend commented on spa/src/elements/buttons/CircleButton.js
> +  return <>{cButton}</>;
```suggestion
  return cButton;
```

2022-08-31 14:37 UTC, GuiMend commented on spa/src/components/pageEditor/PageEditor.js
> +                  toolTiptext="View"
CamelCase was swapped. `tooltip` + `Text`
```suggestion
                  tooltipText="View"
```

2022-08-31 14:46 UTC, gurjittoptal commented on spa/src/elements/buttons/CircleButton.js
> +  return <>{cButton}</>;
resolved

2022-08-31 14:46 UTC, gurjittoptal commented on spa/src/elements/buttons/CircleButton.test.js
> +describe('Tooltips on CrcleButton', () => {
resolved

2022-08-31 14:46 UTC, gurjittoptal commented on spa/src/components/pageEditor/PageEditor.js
> +                  toolTipText="View"
resolved now :)

2022-08-31 15:20 UTC, GuiMend approved these changes
👍

2022-09-01 23:29 UTC, x110dc approved these changes

2022-09-02 19:50 UTC, merged