Dev 2038 api support account customisation
newsrevenuehub/rev-engine pull request #617
Opened 2022-08-25 21:12 UTC by leo-dcfa

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

Opening this PR to start discussion - unsure how to test it manually, used a TDD approach to cover all points in the acceptance criteria

#### What's this PR do?

Add API support for account customisation

#### Why are we doing this? How does it help us?

@x110dc can you help me answer this questions?

#### How should this be manually tested? Please include detailed step-by-step instructions.

See above

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

N/A

#### Have automated unit tests been added? If not, why?

Yes, all points in the AC are covered

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

- Still learning how to write pydantic code and best practices - please be candid if this is not how we should do in Python
- I initially tried to use the `put` http method but it's been disabled with a comment:
```python
# we're explicitly setting these in order to prohibit put updates
http_method_names = ["get", "post", "patch"]
```
Based on this, sounds like we don't want to enable it again?

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-2038]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

N/A

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

N/A

2022-08-27 15:36 UTC, njharman commented
```
# we're explicitly setting these in order to prohibit put updates
http_method_names = ["get", "post", "patch"]
```

> Based on this, sounds like we don't want to enable it again?

No, I don't believe that was intent.  The framework we use defaults to allowing PUT, which didn't implement (till now). Maybe, I'm not 100% sure. This kind of question (doubt about or change to AC, Acceptance Crit...) should be posted on the ticket. [It's visible to all stakeholders there. And it's a record of discussions/decisions.]

Changes to AC should also be reflected.  Although, don't make them willy-nilly ;) [The front end ticket/dev would likely check there for implementation details]

2022-08-27 16:43 UTC, njharman requested changes
Good coverage. Looks pythonic to me!  Nowhere did I cringe in pain and nothing made my eyes bleed ;) I posted several questions re AC in ticket. I think those need to be addressed before final review.

re QA look how ben does it for different API ticket https://github.com/newsrevenuehub/rev-engine/pull/616

2022-08-27 16:43 UTC, njharman commented on apps/users/views.py
> +        """Allows customizing an account"""
The """Docstring""" must be first line after def/class, with no intervening blank lines.

2022-08-27 16:43 UTC, njharman commented on apps/users/views.py
> +        logger.debug("Received request to customize account for user %s", user)
If bother with this debug log, might as well include the values firt_name, etc posted too.

2022-08-27 16:43 UTC, njharman commented on apps/users/views.py
> +        ]
This is novel.  I'd ditch the temp var "required_data" and just put the list inline 

> for key in ["first_name", "last_name", "job_title", "organization_name", "organization_tax_status"]

btw, anytime (almost) I see something used once. I'm gonna say get rid of that! [Naming things gives them importance. It increases the cognitive load of understanding a block of code. Have to wonder if the name is used elsewhere lower down in code. More things to keep in head at once.  It is opportunity for bug (typo, name clash). Temp, single use variables have zero importance, they should get zero name! :) ]

2022-08-27 16:43 UTC, njharman commented on apps/users/views.py
> +            raise ValidationError(USER_CUSTOMIZE_ACCOUNT_MISSING_APARAMS)
Pretty sure they way to do validation with DRF is to use a serializer.  So this and the required_data lines replaced with serializer.  https://www.django-rest-framework.org/api-guide/serializers/ Might be extending/reusing an existing User Serializer, but probably a specific one cause this end point is weird the AC for it.

2022-08-27 16:43 UTC, njharman commented on apps/users/views.py
> +    def customize_account(self, request, pk=None):
this action needs to be added to get_permssions method above. IsAuthenticated, proly UserOwnsUser

2022-08-27 16:43 UTC, njharman commented on apps/users/views.py
> +        if not user.email_verified:
instead do in get_permssions by adding UserIsAllowedToUpdate permisison

2022-08-27 16:43 UTC, njharman commented on apps/users/views.py
> +        if not user.accepted_terms_of_service:
Would create a new permission (didn't look like one existed) and add it to get_permissions for this action

2022-08-27 16:43 UTC, njharman commented on apps/users/tests/test_views.py
> +        )
Personnally I'd put all this repeated code in a helper method, or create new TestCase and put in setUp. But, I'm willing to go to great effort to support laziness, ymmv.

2022-08-27 16:43 UTC, njharman commented on apps/users/tests/test_views.py
> +        self.assertTrue(RevenueProgram.objects.filter(name=expected_organization_name).exists())
Just saying was good case to test for and implemtation.

2022-08-27 22:28 UTC, leo-dcfa commented on README.md
> +pg_restore --verbose --clean --no-acl --no-owner -d postgres://postgres@127.0.01:54000/revengine latest.dump
thanks

2022-08-27 22:29 UTC, leo-dcfa commented on README.md
> +pg_restore --verbose --clean --no-acl --no-owner -d postgres://postgres@127.0.01:54000/revengine latest.dump
The command as it was did not work; pg_restore would automatically try to look at the standard psql port, `5432` but docker-compose has the mapping `"54000:5432"`; I though adding it here explicitly would help the next developer

2022-08-27 22:32 UTC, leo-dcfa commented on apps/users/constants.py
> +USER_CUSTOMIZE_ACCOUNT_MISSING_APARAMS = "Please provide values for 'first_name', 'last_name', 'job_title', 'organization_name' and 'organization_tax_status'."
I understand your argument; I am prefer to have constants declared in the files where they are used or at least closer to the domain. Since current `UserViewset` was using `constants.py` my approach was to stick with current convention. I don't have a strong opinion about this one though, would you prefer it if I change it?

2022-08-27 22:38 UTC, leo-dcfa commented on apps/users/views.py
> +    def customize_account(self, request, pk=None):
nice, thanks!

2022-08-27 23:01 UTC, leo-dcfa commented on apps/users/views.py
> +        logger.debug("Received request to customize account for user %s", user)
good point

2022-08-27 23:01 UTC, leo-dcfa commented on apps/users/views.py
> +        """Allows customizing an account"""
missed it when I was adding debug logs

2022-08-27 23:28 UTC, leo-dcfa commented
`But, the correct verb would be PATCH, maybe. This endpoint is just weird and wrong. It's updating User and, possibly, also creating an Organization.` <- Completely agree that the endpoint is weird and wrong.

2022-08-27 23:57 UTC, leo-dcfa commented on apps/users/views.py
> +        if not user.accepted_terms_of_service:
nice, loved it

2022-08-28 00:37 UTC, leo-dcfa commented on apps/users/tests/test_views.py
> +        )
good idea

2022-08-28 01:03 UTC, leo-dcfa commented on apps/users/views.py
> +            raise ValidationError(USER_CUSTOMIZE_ACCOUNT_MISSING_APARAMS)
ah nice, thanks!

2022-08-28 06:44 UTC, leo-dcfa commented
@njharman changed PR to merge into main instead of develop - just checked other open PRs and saw that they are against main

2022-08-29 19:02 UTC, njharman commented on README.md
> +pg_restore --verbose --clean --no-acl --no-owner -d postgres://postgres@127.0.01:54000/revengine latest.dump
The README section 8 instructs how to configure this up using direnv.

That is how "local configuration" should be done.

2022-08-29 19:07 UTC, njharman commented on apps/users/constants.py
> +USER_CUSTOMIZE_ACCOUNT_MISSING_APARAMS = "Please provide values for 'first_name', 'last_name', 'job_title', 'organization_name' and 'organization_tax_status'."
> Opinions vary on this.

Is my way of indicating "no" answer to 

>would you prefer it if I change it?

2022-08-29 20:27 UTC, leo-dcfa commented on apps/users/constants.py
> +USER_CUSTOMIZE_ACCOUNT_MISSING_APARAMS = "Please provide values for 'first_name', 'last_name', 'job_title', 'organization_name' and 'organization_tax_status'."
cheers mate

2022-08-29 20:38 UTC, leo-dcfa commented on README.md
> +pg_restore --verbose --clean --no-acl --no-owner -d postgres://postgres@127.0.01:54000/revengine latest.dump
no problem, removed from readme

2022-08-30 21:30 UTC, njharman approved these changes
lgtm.

2022-08-31 05:08 UTC, x110dc requested changes
Just the tiniest of changes per our style guide: "nonprofit" not "non-profit"

2022-08-31 05:08 UTC, x110dc commented on apps/users/serializers.py
> +    organization_tax_status = serializers.ChoiceField(choices=["for-profit", "non-profit"], required=True)
```suggestion
    organization_tax_status = serializers.ChoiceField(choices=["for-profit", "nonprofit"], required=True)
```

2022-08-31 05:08 UTC, x110dc commented on apps/users/serializers.py
> +    organization_tax_status = serializers.ChoiceField(choices=["for-profit", "non-profit"], required=True)
Per our style guide: https://news-revenue-hub.atlassian.net/wiki/spaces/COM/pages/1814659105/Style+Guide

2022-08-31 05:08 UTC, x110dc commented on apps/users/views.py
> +            non_profit=True if organization_tax_status == "non-profit" else False,
```suggestion
            non_profit=True if organization_tax_status == "nonprofit" else False,
```
Style guide.

2022-08-31 05:08 UTC, x110dc commented on apps/users/tests/test_views.py
> +            data={**self.customize_account_request, "organization_tax_status": "non-profit"},
```suggestion
            data={**self.customize_account_request, "organization_tax_status": "nonprofit"},
```

2022-08-31 05:08 UTC, x110dc commented on apps/users/tests/test_views.py
> +            "organization_tax_status": "non-profit",
```suggestion
            "organization_tax_status": "nonprofit",
```

2022-09-02 19:53 UTC, x110dc approved these changes

2022-09-05 20:46 UTC, x110dc approved these changes

2022-09-05 21:04 UTC, merged