dev-2123-spa-url-changes
newsrevenuehub/rev-engine pull request #619
Opened 2022-08-26 12:45 UTC by gurjittoptal

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
This PR shall change SPA URLs

#### What's this PR do?
Changes SPA URLs 

#### Why are we doing this? How does it help us?
To Clarify App Structure (page paths + page slugs) for Launch

#### How should this be manually tested? Please include detailed step-by-step instructions.
URLs to test
https://dev-2123.revengine-review.org/sign-in  
https://dev-2123.revengine-review.org/pages 
https://dev-2123.revengine-review.org/customize 
https://dev-2123.revengine-review.org/contributions 
https://dev-2123.revengine-review.org/edit/berkleyside-dev-2123/donate 

/sign-up → create-account is out of scope as that feature is in development dev-2044

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
yes. spa paths will change

#### Have automated unit tests been added? If not, why?
no. existing cypress tests have been updated

#### How should this change be communicated to end users?
n/a

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-2123

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2022-08-29 08:33 UTC, GuiMend requested changes
Small changes

2022-08-29 08:33 UTC, GuiMend commented on spa/cypress/integration/06 - donation-detail.spec.js
> +      cy.visit(`${DONATIONS_SLUG}/${CONTRIBUTION_PK}`);
Could do the same as the previous test, create a const and use it in all places where this repeats

2022-08-29 08:33 UTC, GuiMend commented on spa/src/components/dashboard/Dashboard.js
> +  const isEditPage = useLocation().pathname.includes('/edit');
Would be better to use the constant so that if it changes this verification is always updated
```suggestion
  const isEditPage = useLocation().pathname.includes(EDITOR_ROUTE);
```

2022-08-29 08:33 UTC, GuiMend commented on spa/src/routes.js
>  export const DASHBOARD_SLUG = '/dashboard';
If it's not being used anymore, it's better to remove this line
```suggestion
```

2022-08-29 12:30 UTC, gurjittoptal commented on spa/src/components/dashboard/Dashboard.js
> +  const isEditPage = useLocation().pathname.includes('/edit');
done

2022-08-29 21:10 UTC, GuiMend approved these changes
👍 

![image](https://user-images.githubusercontent.com/9381325/187299553-2d959699-dad9-4d14-b627-549527880429.png)
![image](https://user-images.githubusercontent.com/9381325/187299581-2239408b-193a-4993-b3d4-7c34a6a1fe2e.png)
![image](https://user-images.githubusercontent.com/9381325/187299612-f9d646e3-048d-41be-8545-b83a7ff0d64b.png)

2022-09-01 17:45 UTC, x110dc requested changes
There are merge conflicts.

2022-09-05 21:16 UTC, x110dc approved these changes

2022-09-05 21:17 UTC, merged