Dev 2205 deactivate contributions for early adopters
newsrevenuehub/rev-engine pull request #620
Opened 2022-08-26 16:17 UTC by harsha09

#### What's this PR do?
Limit access to Contributions dashboard for selected users by allowing access to everyone.

#### Why are we doing this? How does it help us?
Need a mechanism to disable Contributions dashboard access for few Orgs / RP users but should be accessible to all other users.

#### How should this be manually tested? Please include detailed step-by-step instructions.
To test this feature a waffle flag `spa-contributions-section-deny` need to be created using Django Admin.

How to create Waffle flag? Login to Django Admin portal -> Flags Section -> Add
Flag name should be `spa-contributions-section-deny`
1. Can enable this flag to everyone (No user should be able to access contributions dashboard).
2. Can also enable this flag by specifying users where the specified users will not be able to access the contributions dashboard.
3. `spa-contributions-section-deny` will take precedence over `spa-contributions-section-access`, you can play around with the combinations.

After creating the Waffle Flag login to Contributions with the user for whom `spa-contributions-section-deny` is enabled, Contributions tab should not be visible and navigation to /contributions redirects to 404 page.

Users for whom `spa-contributions-section-deny` is disabled and `spa-contributions-section-access` is enabled Contributions tab should be visible and be able to list contributions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
No changes to UI but enabling and disabling Contributions for few set of users.

#### Have automated unit tests been added? If not, why?
Yes

#### How should this change be communicated to end users?
Probably user manual.

#### Are there any smells or added technical debt to note?
NA

#### Has this been documented? If so, where?
Not yet

#### What are the relevant tickets? Add a link to any relevant ones.
[DEV-2205]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
NA

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
NA

2022-08-29 08:23 UTC, GuiMend requested changes
Minor comments + suggestion to add more tests to cover the changes

2022-08-29 08:23 UTC, GuiMend commented on spa/cypress/integration/11 - dashboard.spec.js
> +  flags: [{ ...contribSectionsAccessFlag }]
No need to deconstruct object into a new object
```suggestion
  flags: [contribSectionsAccessFlag]
```

2022-08-29 08:23 UTC, GuiMend commented on spa/cypress/integration/11 - dashboard.spec.js
> +  flags: [{ ...contribSectionsDenyFlag }, { ...contribSectionsAccessFlag }]
Here too
```suggestion
  flags: [contribSectionsDenyFlag, contribSectionsAccessFlag]
```

2022-08-29 08:23 UTC, GuiMend commented on spa/cypress/integration/11 - dashboard.spec.js
> +  flags: [{ ...contentSectionFlag }, { ...contribSectionsAccessFlag }]
here again

2022-08-29 08:23 UTC, GuiMend commented on spa/src/components/dashboard/sidebar/DashboardSidebar.test.js
>  it('should have expected appearance and links', () => {
You could also add a unit test to check that the navigation is hidding/showing as expected. It's better to have this test as a Unit test than a cypress test (it runs quicker and checks the same thing)

2022-08-29 08:23 UTC, GuiMend commented on spa/src/utilities/hasContributionsDashboardAcessToUser.js
> +function hasContributionsDashboardAcessToUser(featureFlags) {
Could also create unit tests for this function

2022-08-29 18:18 UTC, harsha09 commented on spa/cypress/integration/11 - dashboard.spec.js
> +  flags: [{ ...contribSectionsAccessFlag }]
Addressed here 3beadee40bae770316d5ca5dc8e0e2a066e53da8

2022-08-29 18:19 UTC, harsha09 commented on spa/cypress/integration/11 - dashboard.spec.js
> +  flags: [{ ...contentSectionFlag }, { ...contribSectionsAccessFlag }]
Addressed 3beadee40bae770316d5ca5dc8e0e2a066e53da8

2022-08-30 17:35 UTC, harsha09 commented on spa/src/components/dashboard/sidebar/DashboardSidebar.test.js
>  it('should have expected appearance and links', () => {
Added the test using 55e6666e6897992a368530c19a0579e94f705900

2022-08-30 18:20 UTC, harsha09 commented on spa/src/utilities/hasContributionsDashboardAcessToUser.js
> +function hasContributionsDashboardAcessToUser(featureFlags) {
Added tests using 8d415556506828acd455a6663a0cc96e2a3fa979

2022-08-31 13:34 UTC, GuiMend approved these changes
Code LGTM 👍 
Thanks for adding the additional tests @harsha09

2022-09-02 20:08 UTC, x110dc approved these changes

2022-09-02 20:08 UTC, merged