DEV-2053_account_verification
newsrevenuehub/rev-engine pull request #621
Opened 2022-08-26 19:57 UTC by njharman

#### What's this PR do?
Add verification endpoint for users to validate email. and API endpoints to trigger resending verification email.

  AC1.c.i 200 with JSON {"detail": "Success"}
  AC1.c.ii 200 with JSON {"detail": "Account already verified"}
  added 200 with JSON {"detail": "Account inactive"}

  AC2.c SPA URL as undefined and implemented AC2.b as redirect to SPA
  instead of custom html template. These SPA routes need to be
  implemented in DEV-2027
    - "verified"           good to go!
    - "verified/expired"   took too long to follow verification link
    - "verified/inactive"  user.is_active == False
    - "verified/unknown"   user matching given email not found (maybe it got changed?)

  Note: It should not be possible to malactor to generate verification
  links with arbitrary email addresses to fish our database.

Also,
  - Cut commented import that black/isort had different opinions on.
  - Fix error in README.md and duplication in settings/local.example.py.
  - Move create_test_user to factory.

#### Why are we doing this? How does it help us?
Unblock [DEV-2027]

#### How should this be manually tested? Please include detailed step-by-step instructions.
I believe the testing would be done in DEV-2027

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
No

#### Have automated unit tests been added? If not, why?
Yes

#### How should this change be communicated to end users?
N/A

#### Are there any smells or added technical debt to note?
No, well maybe the SPA urlstructure detailed above not being "how SPA does things". And exposing inactive/unknown in url ?

#### Has this been documented? If so, where?
N/A

#### What are the relevant tickets? Add a link to any relevant ones.
[DEV-2053]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

New setting ACCOUNT_VERIFICATION_LINK_EXPIRY if non-zero will expire
account verification links after that many seconds. If "0" or None links never expire

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
Yes [DEV-2027]

2022-08-27 03:48 UTC, x110dc requested changes
Didn't review business logic, I'll leave that to @benjaminEwhite. Just a couple of comments/requests.

2022-08-27 03:48 UTC, x110dc commented on apps/contributions/tests/test_views.py
> +    def atest_intervals(self):  # TODO: njharman forgot to reenable/fix this test
What did njharman do? 😉

2022-08-27 03:48 UTC, x110dc commented on revengine/settings/base.py
>  UID_SALT = os.getenv("UID_SALT", "")
If it's going to be used for multiple purposes I think I'd prefer that it be renamed to something more generic.

2022-08-29 17:33 UTC, benjaminEwhite requested changes
Left a bunch of comments.

I ran locally, changed `send_templated_email.delay` to `send_templated_email` in the `.send_verification_email` method so I could see the email that gets sent in log.  Looks like the verification URL is not getting converted in the email:

<img width="944" alt="Screen Shot 2022-08-29 at 1 30 33 PM" src="https://user-images.githubusercontent.com/960351/187262914-d8d0b387-d625-4b6a-894b-e223db57f5bd.png">

2022-08-29 17:33 UTC, benjaminEwhite commented on apps/users/tests/test_views.py
> +        assert sent.delay.called or sent.called
Would be better to not stub out send email functionality, and instead to inspect the sent email and make assertions about it.  Can see an example of that here: https://github.com/newsrevenuehub/rev-engine/pull/616/files#diff-fced53f883ab4297c7fd07e9170237ecf4a1c5e4378c0d91000253e5cf520b6fR115

As is, we don't have any tests that prove that the email that gets sent to users behaves as expected.

2022-08-29 17:33 UTC, benjaminEwhite commented on apps/users/tests/test_views.py
> +        assert sent.delay.called or sent.called
Also, this test should be happening via the API layer, not calling the send_verification_email method on the viewset directly, IMO.

2022-08-29 20:23 UTC, njharman commented on revengine/settings/base.py
>  UID_SALT = os.getenv("UID_SALT", "")
changed / documented to ENCRYPTION_SALT

2022-08-29 20:24 UTC, njharman commented on apps/contributions/tests/test_views.py
> +    def atest_intervals(self):  # TODO: njharman forgot to reenable/fix this test
created DEV-2295 to resolve

2022-08-29 21:03 UTC, njharman commented on apps/api/authentication.py
> +        # Validate users that don't have is_active, or, that do and it's set True.
I added comment after "simplyfying" logic line and breaking things. But, I'll accept that is failure of reader and not lack of clarity in code.  Cutting comment

2022-08-29 21:04 UTC, njharman commented on apps/contributions/tests/test_views.py
> +    def atest_intervals(self):  # TODO: njharman forgot to reenable/fix this test
I'm not. Already added ticket.

2022-08-29 21:07 UTC, njharman commented on apps/users/tests/test_views.py
> +    @override_settings(ACCOUNT_VERIFICATION_LINK_EXPIRY=None)
test should not assume/be dependent on state of world.  This setting change should not be able to cause test to start failing (or change which branches it covers)

Also I did (or will if I forgot) add test with / without expiry. As they'll exercise different code paths.

2022-08-29 21:22 UTC, njharman commented on apps/users/tests/test_views.py
> +    def test_failed(self):
I added more tests. But still won't like my terse names test_unknown_user, test_inactive_user, test_failed_bad_token, test_expired_token   [the first word after test_ corresponds to url]

2022-08-29 21:38 UTC, njharman commented on apps/users/tests/test_views.py
> +class TestAccountVerification:
I did go back and add view tests for all but expiration, which is pain (all those tests vary only by one word). Originally the view tests were just to get coverage % over two branches. But there is little value in better testing there.

Disagree on where logic should be tested though.

I'm pretty "pure" on unit tests should test the unit and not be integration tests. [attenuated by pragmatism and lack of integration testing framework better than pytest]  I put all the logic in a separate class and not the view, to make it simple and direct to test. And to separate logic layer from view layer. Ideally views should be devoid of "logic" and only concern with display. rendering, encoding, protocol stuff like status code.

You don't test that django.orm.select works cause you expect that to be tested in django.orm. Likewise you don't test the AccountVerification works (when you use it) cause you expect that ito be tested in AccountVerification.

in my opinion anyways ;)

btw in other projects we've used pytest to explicitly write integration tests. they were kept separate and run separately (to keep unittests fast).

2022-08-29 21:49 UTC, njharman commented on apps/users/tests/test_views.py
> +        )  # RFC-3986 URL Safe, plus "=", equal, cause base64 says URL doesn't include query portion.
The regex? Really? It's a single regex element. The group "[]" of those characters, zero or more times "*", bounded by start "^" and end "$" of string. I don't know how to write it more verbosely even with regex whitespace (which I loath) it'd be "~ [=a-zA-Z0-9._~-]* $" or with spaces between each character class in group.

The comment pointing to RFC explains intention better than any comment restating the regex in english would. 
I'll update to "Ensure string contains only RFC-3986 URL Safe characters plus equalsign, "=". Because base64 lib uses equalsigns in violation of RFC."

2022-08-29 21:52 UTC, njharman commented on apps/users/tests/test_views.py
> +        assert {"detail": "Account inactive"} == response.json()
No laziness under Ben's watch!  :)

Splitting up like I should have initially.

2022-08-29 21:53 UTC, njharman commented on apps/users/tests/test_views.py
> +        # Requires Authenticated User.
agree

2022-08-29 22:21 UTC, njharman commented on apps/users/tests/test_views.py
> +        assert sent.delay.called or sent.called
> Why the or? 
I'm not testing how (sync or async) it's called. Don't want to test to fail if that changes.

Updated test to check email contents.

2022-08-29 22:44 UTC, njharman commented on apps/users/views.py
> +        return HttpResponseRedirect(reverse("spa_account_verification_fail", kwargs={"failure": checker.fail_reason}))
per AC2 This is non-API endpoint. It's the link users click in email.  The endpoints that SPA uses to trigger sending email are in UserViewset.request_account_verification

2022-08-29 22:44 UTC, njharman commented on apps/users/urls.py
> +    path("verify-account/<email>/<token>/", views.account_verification, name="account_verification"),
per AC2 This is non-API endpoint. It's the link users click in email. The endpoints that SPA uses to trigger sending email are in UserViewset.request_account_verification

2022-08-29 22:47 UTC, njharman commented on apps/users/views.py
> +        return HttpResponseRedirect(reverse("spa_account_verification_fail", kwargs={"failure": checker.fail_reason}))
My understanding DRF is API only. No?

2022-08-29 22:50 UTC, njharman commented on apps/users/views.py
> +        self.fail_reason = "failed"  # Single word [inactive, expired, unknown], other failures are empty string.
Rewrote and explained.

2022-08-29 22:52 UTC, njharman commented on apps/users/views.py
> +        return get_sha256_hash(plaintext)
It's used in 3 places, one far from others. Don't want someone to change one place and not others. [Sort expected get_sha..() to not work cause the truncation it does and expected to have to change it.]

2022-08-29 22:57 UTC, njharman commented on apps/users/views.py
> +        if self.max_age is None:
AC didn't mention having expiration. So don't want to force that implementation (and I don't want to deal with discussing it with stakeholders).  But I agree there is no use case for not expiring. Why I made settings default to have one.

I agree with test to require settings be set (in general) [I desperately want to add test that fails if ENCRYPTION_SALT is empty string]

I did add expiry and no expiry test paths (to endpoint tests).

2022-08-29 22:59 UTC, njharman commented on apps/users/views.py
> +                logger.warning("Account Verification: URL Expired for email:%s", email)
yes, updated to include space all over.

2022-08-29 23:04 UTC, njharman commented on apps/users/views.py
> +                self.fail_reason = "expired"
This was poor decision on my part (having default be "failed") I've changed to have default be empty string and explicitly  set "failed" in the other previously dependent on default branches.

"failed" cause we don't want to leak info.  I would want to use "failed" for "unknown" but as stated in commit/PR comments I don't believe malactor should be able to generate a arbitrary links to probe for emails.  "inactive" proly should be failed too. But none of this was explored/defined in AC. "expired" seems like needful information to convey to good but slow user.

2022-08-29 23:10 UTC, njharman commented on apps/users/views.py
> +        for user in get_user_model().objects.filter(email=email):
Yes. I copied this from somewhere, and looking at it now, it's too goofy. changing.

2022-08-29 23:17 UTC, njharman commented on apps/users/views.py
> +        if not user.email:
It can be empty string. If method passed User that hasn't been saved to db or validated it can be anything.

Can catch and log (these, admittedly, edge cases) or let django send_mail to raise or fail silently (no idea what it does)?

eh?

2022-08-29 23:19 UTC, njharman commented on apps/users/views.py
> +            {"verification_url": reverse("account_verification", kwargs={"email": encoded_email, "token": token})},
done

2022-08-29 23:26 UTC, njharman commented on revengine/settings/base.py
> +ACCOUNT_VERIFICATION_LINK_EXPIRY = 60 * 60 * 4  # Four hours
I did consider! But 1) I don't think it will change often (or per environment, or need to be secret (the two reasons I'd put something in envvar)) 2) wasn't even an AC so reluctant to add more code/documentation/work for it.

i did change it to be in hours and not seconds to be more consistent with something I think I saw you working on.  
Maybe this? DJANGO_REST_MULTITOKENAUTH_RESET_TOKEN_EXPIRY_TIME = 24

I'm changing four hours to 24 to match that

2022-08-29 23:32 UTC, njharman commented on revengine/urls.py
> +    path("verified/<failure>/", index, name="spa_account_verification_fail"),  # for reverse()
Use reverse() anywhere. I was just copying existing comment. But it took me while to understand what it meant...

Will update to "Routing handled by SPA, urlpatten defined here only to allow use of reverse()"

2022-08-29 23:38 UTC, njharman commented on apps/users/tests/test_views.py
> +        )  # RFC-3986 URL Safe, plus "=", equal, cause base64 says URL doesn't include query portion.
This one is more complex, no? Uses (?:) group thing and has two elements?
 
> re_path(r"^(?:.*)/?$", ...

2022-08-30 13:21 UTC, benjaminEwhite approved these changes
LGTM!

2022-09-02 19:47 UTC, x110dc approved these changes

2022-09-02 19:47 UTC, merged