DEV 2289 separate API endpoint for Subscriptions
newsrevenuehub/rev-engine pull request #627
Opened 2022-08-31 00:01 UTC by x110dc

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2022-08-31 19:48 UTC, njharman requested changes
100% coverage!

1. Would prefer the follow up dev-2320 ticket referred back to this one
2. PR note: Doesn't this require changes to user facing docs? Even if not the front implementation?

Don't forget to log your time on ticket.

2022-08-31 19:48 UTC, njharman commented on apps/contributions/serializers.py
> +    def get_next_payment_date(self, instance):
https://news-revenue-hub.atlassian.net/wiki/spaces/TECH/pages/2065039378/Python+Tips

2022-08-31 19:48 UTC, njharman commented on apps/contributions/serializers.py
> +        raise serializers.ValidationError(f"Invalid interval: {interval}/{interval_count}")
Maybe also include instance["plan"] for context?

2022-08-31 19:48 UTC, njharman commented on apps/contributions/serializers.py
> +class SubscriptionsSerializer(serializers.Serializer):
new code 100% covered good job! But some easy coverage additions would 100% this file.

2022-08-31 19:48 UTC, njharman commented on apps/contributions/stripe_contributions_provider.py
> +        return True
Is it worth checking that with if and logging/raising error if an unknown status is given to us?

2022-08-31 19:48 UTC, njharman commented on apps/contributions/stripe_contributions_provider.py
> +        with self.cache.lock(f"{self.key}-lock"):
I'm surprised to see lock().  the caches I know memcache/redis set() is atomic?

I don't see lock() in docs https://docs.djangoproject.com/en/3.2/topics/cache/#cache-key-transformation
Nor could I find it in django/core/cache/*py 

What am I missing?

2022-08-31 19:48 UTC, njharman commented on apps/contributions/views.py
> +        revenue_program = RevenueProgram.objects.get(slug=revenue_program_slug)
Should we not 404 if rp matching slug not found?

2022-08-31 19:48 UTC, njharman commented on apps/contributions/views.py
> +        if not subscriptions:
Instead of just returning 404 (when we haven't loaded from cache yet) should we return different message so UI can display "loading, refresh in X" or whatever?

2022-08-31 19:48 UTC, njharman commented on apps/contributions/views.py
> +            return Response({"detail": "Not Found"}, status=status.HTTP_404_NOT_FOUND)
Wouldn't this be less convoluted and weird? (or see next comment about duplicated code) and keep the index exception around deduplication/extract method get_me_subscriptions_for()[0]
```
for x in subscriptions:
  if x.get... and x.get..:
    return Response(x)
return 404
```

2022-08-31 19:48 UTC, njharman commented on apps/contributions/views.py
> +        ]
Lot of duplicated code between this and retrieve()

2022-08-31 19:48 UTC, njharman commented on apps/contributions/views.py
>          if request.user.email.lower() != subscription.customer.email.lower():
I know you didn't touch this code. But, maybe add todo/or acknowledgement its a limitation we are accepting. I notice that if user changes email in our or stripe? they may be unable to cancel subscription?

2022-09-01 20:35 UTC, x110dc commented on apps/common/utils.py
> +            return [cls.construct_from_dict(i) for i in data]
I didn't author it, I just moved it! 😉 But point taken. I found a library that does just this that served as drop-in replacement. I think I actually prefer the method of testing in Stripe objects in the webhook receiver, but I was too lazy to wholesale replace what's here, but I'll open a separate ticket to look into that.

2022-09-01 20:36 UTC, x110dc commented on apps/contributions/serializers.py
> -    next_payment_date = serializers.DateTimeField()
It was never used on the frontend and was always null anyway.

2022-09-01 20:38 UTC, x110dc commented on apps/contributions/serializers.py
> +        return True
Agreed. I changed.

2022-09-01 20:39 UTC, x110dc commented on apps/contributions/serializers.py
> +    def _card(self, instance):
That's fine with me (done), and 👍 on updating style guide.

2022-09-01 20:42 UTC, x110dc commented on apps/contributions/views.py
> +        revenue_program = RevenueProgram.objects.get(slug=revenue_program_slug)
Not sure that can/should happen, but agreed, good defensive programming anyway. I'll do that.

2022-09-01 20:43 UTC, x110dc commented on apps/contributions/views.py
> +        if not subscriptions:
But that's not what it does. It only returns the 404 if it's not in the cache AND not found in Stripe either.

2022-09-01 20:43 UTC, x110dc commented on apps/contributions/views.py
> +            return Response({"detail": "Not Found"}, status=status.HTTP_404_NOT_FOUND)
Agreed. On both points. I'll change.

2022-09-01 20:48 UTC, x110dc commented on apps/contributions/views.py
> +        ]
You're right. I'll make a helper function (and put it at the top of the list).

2022-09-01 20:56 UTC, njharman commented on apps/contributions/views.py
> +        if not subscriptions:
Is my assumption that task_pull_serialized_stripe_contributions_to_cache() is an asynchronous celery task incorrect?

2022-09-01 20:56 UTC, njharman commented on apps/contributions/views.py
> +        if not subscriptions:
only when called with .delay()

2022-09-01 21:31 UTC, x110dc commented on apps/contributions/views.py
> +        ]
Thanks, that cleaned up those two methods nicely.

2022-09-01 21:32 UTC, x110dc commented on apps/contributions/views.py
>          if request.user.email.lower() != subscription.customer.email.lower():
There's no way for a user to change their email. Eventually we'll allow a user to link multiple email addresses together and it'll be addressed then.

2022-09-01 21:36 UTC, x110dc commented on apps/contributions/views.py
> +        if not subscriptions:
Yes, it's only async when called with `.delay` or `.apply_async`.

2022-09-01 21:38 UTC, njharman commented on apps/contributions/views.py
>          if request.user.email.lower() != subscription.customer.email.lower():
I don't believe there's anything stopping them API wise.  there's a PATCH on user and it doesn't block changing email. Just sayin...

2022-09-01 21:39 UTC, x110dc commented on apps/contributions/serializers.py
> +        raise serializers.ValidationError(f"Invalid interval: {interval}/{interval_count}")
But that'll be a big JSON blob. Maybe plan.id?

2022-09-01 21:48 UTC, njharman commented on apps/contributions/serializers.py
> +    def get_next_payment_date(self, instance):
oh, I thought I fixed all of them, back when I made that tip...  Maybe people have been adding wrong since then, horrors!

Def assign ticket to me, I'll do it right quick!

2022-09-01 22:56 UTC, merged