DEV-2295 Document pragma: no cover
newsrevenuehub/rev-engine pull request #637
Opened 2022-09-02 03:12 UTC by njharman

#### What's this PR do?
  - Fix test njharman forget to reenable and fix.
  - Cut pragma: no cover that aren't needed. Document the rest.
  - xfail tests for code that may be wrong rather than pragma: no cover it.
  - Add some coverage. Over 97%, nothing below 90%.

#### Why are we doing this? How does it help us?
Tested code is happy code. Ignoring code should be last resort and documented.

#### How should this be manually tested? Please include detailed step-by-step instructions.
N/A

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
No

#### Have automated unit tests been added? If not, why?
Indeed

#### How should this change be communicated to end users?
N/A

#### Are there any smells or added technical debt to note?
Added two expected fail tests in ./apps/common/context_processors.py seem maybe unused. 

#### Has this been documented? If so, where?
N/A

#### What are the relevant tickets? Add a link to any relevant ones.
[DEV-2295]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
No.

2022-09-05 23:25 UTC, x110dc requested changes
It's okay with me if the SENTRY_DSN and COMMIT_SHA removals happen separately. Otherwise just two requests to change language in comments.

2022-09-05 23:25 UTC, x110dc commented on apps/users/management/commands/bootstrap-review-app.py
> +class Command(BaseCommand):  # pragma: no cover Guess we're too lazy to test.
Please change this to something more factual and less judgmental.

2022-09-05 23:25 UTC, x110dc commented on apps/users/management/commands/teardown-review-app.py
> +class Command(BaseCommand):  # pragma: no cover Guess we're too lazy to test
Same as above. Please change.

2022-09-05 23:25 UTC, x110dc commented on apps/common/tests/test_context_processors.py
> +def test_sentry_dsn():
The COMMIT_SHA in cloudbuild.yaml is not related to anything in Django. I'm pretty sure neither of these are used in any way and can be removed.

2022-09-07 20:13 UTC, njharman commented on apps/users/management/commands/teardown-review-app.py
> +class Command(BaseCommand):  # pragma: no cover Guess we're too lazy to test
done

2022-09-08 19:53 UTC, x110dc approved these changes

2022-09-08 19:53 UTC, merged