DEV-2329 Do not use utcfromtimestamp
newsrevenuehub/rev-engine pull request #638
Opened 2022-09-02 03:49 UTC by njharman

#### What's this PR do?
Updated code and tests to use timezone aware datetimes.

https://docs.python.org/3/library/datetime.html#datetime.datetime.utcfromtimestamp

Warning Because naive datetime objects are treated by many datetime
methods as local times, it is preferred to use aware datetimes to
represent times in UTC. As such, the recommended way to create an object
representing a specific timestamp in UTC is by calling
datetime.fromtimestamp(timestamp, tz=timezone.utc).

#### Why are we doing this? How does it help us?
Cause The Python Authors probably know what they are taking about. timezones cause subtle and hard to track down bugs.

#### How should this be manually tested? Please include detailed step-by-step instructions.
N/A

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
No.

#### Have automated unit tests been added? If not, why?
Existing ones updated.

#### How should this change be communicated to end users?
N/A

#### Are there any smells or added technical debt to note?
No

#### Has this been documented? If so, where?
dev docs https://news-revenue-hub.atlassian.net/wiki/spaces/TECH/pages/2065039378/Python+Tips

#### What are the relevant tickets? Add a link to any relevant ones.
[DEV-2329]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
No

2022-09-05 22:52 UTC, x110dc requested changes

2022-09-05 22:52 UTC, x110dc commented on apps/contributions/serializers.py
> +import pytz
Can we use zoneinfo instead? https://docs.python.org/3/library/zoneinfo.html 

https://docs.djangoproject.com/en/3.2/topics/i18n/timezones/

I think use of pytz is kinda/sorta deprecated.

2022-09-06 19:33 UTC, njharman commented on apps/contributions/serializers.py
> +import pytz
Yes

2022-09-06 19:34 UTC, njharman commented on apps/contributions/serializers.py
> +import pytz
Also updated https://news-revenue-hub.atlassian.net/wiki/spaces/TECH/pages/2047311873/Python+Style+Guide

2022-09-08 19:38 UTC, x110dc approved these changes

2022-09-08 19:39 UTC, merged