DEV-2183: Server-side changes to support new Stripe PaymentElement in SPA
newsrevenuehub/rev-engine pull request #640
Opened 2022-09-03 18:40 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

This is the first of at least 2 stacked PRs to implement new Stripe PaymentElement on the front end. This PR contains only the initial server-side changes.

The PR is into DEV-2183-root-branch, which itself branched from main. Incremental PRs will be made into DEV-2183-root-branch until DEV-2183 is complete, at which point it should be merged into main in a separate PR.

Note that the server-side changes in DEV-2183 are breaking, and the status quo SPA will not work with the changes in this PR.  

#### What's this PR do?

This PR represents a major refactor of the server-side code that supports creation of Stripe customers, payment intents, and subscriptions.

An initial, high-level description of the overall strategy is warranted here.  The DEV-2183 ticket was initially a narrow bug ticket meant to address Google and Apple Pay not working in staging or production. Investigations revealed that the best strategy to solve the bug would be to refactor the SPA to [use the Stripe PaymentElement](https://stripe.com/docs/payments/payment-element).  

The PaymentElement has different requirements than the status quo CardElement we were using. Specifically, it requires that a Stripe client secret be provided to the PaymentElement at the time it is initialized. That client secret is obtained on the server by creating a Stripe PaymentIntent (in the case of one-time contributions) or a Stripe Subscription (in the case of recurring contributions). In order to create a Stripe Subscription requires knowing the contribution amount and interval, as well as customer data (name, email etc) at the time of creation.

In the status quo, users are presented with a single form in which they provide all their information, including their payment info. However, given the constraints around needing to know customer and contribution data ahead of displaying the Stripe PaymentElement, we needed to rethink the donation page experience. Specifically, we needed to break up the donation page into two separate forms. First, a "checkout form" in which the user provides all of the data they currently provide in the donation page form, _except for_ the PaymentInfo. Once DEV-2183 is fully implemented, the user will fill out this initial checkout form, which will be submitted to the server, resulting in the creation of (among other things) a Stripe client secret, which can be used to load a second payment info form that contains the Stripe PaymentElement.

Additionally, there was a need ([see DEV-2256](https://news-revenue-hub.atlassian.net/jira/software/c/projects/DEV/boards/3?selectedIssue=DEV-2256)) for the bad actor check to happen earlier in the contribution flow and to gate the creation of a Stripe customer and PaymentIntent or Subscription.

This PR represents the server-side changes required to support the new flow. At a high level, it retires the old `stripe_payment` view in favor two new viewsets: `OneTimePaymentViewSet` and `SubscriptionPaymentViewSet`.  The initial checkout form will submit to one of these two views depending on the choice of interval.

`OneTimePaymentViewSet` creates an NRE contributor and contribution and makes a call to the bad actor API to determine if the contribution should be flagged. If it should not be flagged, it goes on to create a Stripe Customer and PaymentIntent, relaying the Stripe client secret to the SPA (as `provider_client_secret_id` in the response body), which the SPA will use to load the PaymentElement in a second payment form. If the bad actor API determines that the contribution should be flagged,  the flow stops before creating a Stripe customer or contribution, and a `PermissionDenied` exception will be raised which causes the API to respond with a 403, which in turn will allow the SPA to display "Something went wrong" messaging.

`SubscriptionPaymentViewSet` does the same work as `OneTimePaymentViewSet`, with the exception that instead of creating a Stripe PaymentIntent, it creates a Stripe Subscription instance, which also yields a value for `provider_client_secret_id` that will be used by the SPA to load the PaymentElement. If a recurring contribution is flagged by the bad actor API, the logic described above for `OneTimePaymentViewSet` also applies: neither a Stripe customer nor a Stripe Subscription will be created, and the server will respond with a 403.

Both viewsets also feature a `success` action endpoint. This will be used by the SPA after a Stripe payment has been completed (which happens entirely on the front end). When using the PaymentElement, you provide a return URL value that the StripeElement will send the user to after successful payment. This will be a URL in the SPA where we can make a request to the success endpoint, which will cause a thank you email to be sent to the contributor if the org is configured to have NRE send its thank you emails. That same page will "next" the user to the NRE default thank you page or the RP's external thank you page, depending on configuration.

Here's a summary of some of the most important code changes:

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2022-09-03 21:25 UTC, benjaminEwhite commented on apps/pages/views.py
> +from django.views.decorators.csrf import ensure_csrf_cookie
This is a mistaken change and will remove later

2022-09-03 22:33 UTC, benjaminEwhite commented on apps/pages/views.py
> +from django.views.decorators.csrf import ensure_csrf_cookie
Just kidding. This is necessary to get a CSRF token on the request for Donation page API endpoint in, which subsequent requests in SPA to contribution creation endpoints will use.

2022-09-04 18:25 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> -    payment_method_id = serializers.CharField(max_length=255)
This is a mistake. Will change back.

2022-09-06 16:02 UTC, benjaminEwhite commented on spa/cypress/fixtures/pages/live-page-1.json
> -      "type": "DAdditionalInfo",
This is not actually a thing that can be in page data, and is probably just because this is an old fixture.

2022-09-06 17:19 UTC, njharman requested changes
Looks good, well tested. Just ran tests/reviewed code, no manual testing. Ignored ./spa/

Only one or two issues, rest are questions, quibbles or Norm editorializing.


[edit: reading more of your PR (serializers) it seems you largely did do this] I would like to see some of excellent "overview" added as docstrings. Specifically the parts describing viewsets "OneTimePaymentViewSet creates an..." and Subscription one. [possibly edited for size, etc] I find the best, most useful comments are hi-level, "this was general intent of this code". To give future refactorer/debugger a foundation on which to start comprehending. [maybe hold off for "we should create comprehensive docs about our Stripe integration."?]

2022-09-06 17:19 UTC, njharman commented on apps/contributions/serializers.py
> +            return None
I really don't like that this returns a response that is then interpreted by create_contribution.  that should not know or be dependent on the format/details of bad_actor api. Although it looks like we are storing entire response in the Contribution object.

Should just return score + if anything else is really needed.

But figuring that out is almost certainly out of scope of this ticket.

2022-09-06 17:19 UTC, njharman commented on apps/contributions/serializers.py
> +            raise GenericPaymentError()
Should log the strip_error (type/something). [for future debugging/issue resolution joy]

2022-09-06 17:19 UTC, njharman commented on apps/contributions/serializers.py
> +            raise GenericPaymentError()
This looks identical to previous expect block, why not combine both operations in one try/except.

2022-09-06 17:19 UTC, njharman commented on apps/contributions/serializers.py
> +            raise GenericPaymentError()
Duplicate, adjacent try/excpets. Combine to one.

2022-09-06 20:09 UTC, benjaminEwhite commented on apps/contributions/models.py
> +    def handle_thank_you_email(self, contribution_received_at=timezone.now()):
Ay ay ay. Can't believe i missed that gotcha 🤦 . Good catch.

2022-09-06 20:13 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            # TODO: confirm business requirements around these first two keys/vals
@x110dc when you review, can you let me know if there are any known business requirements around these values appearing in Stripe metadata?

2022-09-06 20:14 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            return None
Yeah, I didn't really consider the relative merits, and was just trying to make this side effect net same as the status quo.

2022-09-06 20:16 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            raise GenericPaymentError()
The log message is slightly different in both cases, so we can tell at exactly which step it failed.

2022-09-06 20:17 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            raise GenericPaymentError()
You mean in addition to the exception object being there by virtue of this being a `logger.exception`?

2022-09-06 20:20 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            raise GenericPaymentError()
Ditto.  Facilitates more granular log messaging about distinct context where error happened.

2022-09-06 20:31 UTC, x110dc requested changes

2022-09-06 20:31 UTC, x110dc commented on apps/contributions/serializers.py
> +stripe_errors = (
It looks like there's a parent exception class: https://github.com/stripe/stripe-python/blob/master/stripe/error.py#L8

2022-09-06 20:31 UTC, x110dc commented on apps/contributions/serializers.py
> +    mailing_postal_code = serializers.CharField(max_length=20, write_only=True)
Not critical, but we should probably remove the mailing prefix or change it "shipping" to avoid confusion in the future.

2022-09-06 20:31 UTC, x110dc commented on apps/contributions/serializers.py
> +            "ip": self.context["request"].META.get("REMOTE_ADDR"),
This should use the utility function here so it's more accurate: 

https://github.com/newsrevenuehub/rev-engine/blob/main/apps/common/utils.py#L118

2022-09-06 20:31 UTC, x110dc commented on apps/contributions/serializers.py
> +            # TODO: confirm business requirements around these first two keys/vals
The business requirements for these is listed in the sheet attached to DEV-739. The comment can be removed, I think as long as another comment I made about incrementing the schema version is addressed.

2022-09-06 20:31 UTC, x110dc commented on apps/contributions/serializers.py
> +            # In the case of a flagged contribution, we don't create a Stripe customer or
As we discussed previously it's out-of-scope for this ticket but we should think about how to handle 2 different cases of bad actor. https://news-revenue-hub.atlassian.net/browse/DEV-2342

2022-09-06 21:07 UTC, njharman commented on apps/contributions/serializers.py
> +            raise GenericPaymentError()
No. Overlooked call to exception(). All good as it.

2022-09-06 21:10 UTC, njharman commented on apps/contributions/serializers.py
> +            raise GenericPaymentError()
My bad, they are really close though!

2022-09-06 21:10 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            # TODO: Determine if this requires a different, new 'pre-processing' status
Ah, missed that comment. Thought behind the comment no longer relevant. Will remove.

2022-09-06 22:27 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            # TODO: confirm business requirements around these first two keys/vals
Removing comment because @x110dc has clarified elsewhere in review (will included, and need to increment value).

2022-09-06 22:31 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            address={
👍 -- changing to shipping address and incrementing to 1.1.

2022-09-06 22:42 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    mailing_postal_code = serializers.CharField(max_length=20, write_only=True)
@x110dc -- are there any concerns around existing donation pages out in the wild. This would result in a breaking change for existing donation pages ab sent doing a data migrations.

2022-09-06 22:50 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            "ip": self.context["request"].META.get("REMOTE_ADDR"),
Changing to use this.

2022-09-06 22:52 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +        contributor, _ = Contributor.objects.get_or_create(email=validated_data["email"])
I could see doing this. It seems to me it would be worth running this down alongside trying not to create duplicate Stripe customers.

2022-09-06 23:35 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +        contributor, _ = Contributor.objects.get_or_create(email=validated_data["email"])
I could see doing that but curious about business advantages. Agree out of scope.

2022-09-06 23:35 UTC, benjaminEwhite commented on revengine/settings/base.py
> +BAD_ACTOR_FAILURE_THRESHOLD = 3
Asked in Slack. Assuming confirmed, will update.

2022-09-07 12:13 UTC, benjaminEwhite commented on revengine/settings/base.py
> +BAD_ACTOR_FAILURE_THRESHOLD = 3
Upped to 5.

2022-09-07 12:14 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    mailing_postal_code = serializers.CharField(max_length=20, write_only=True)
Also, the in-Slack/JIRA discussion re: security implications of billing vs. shipping address is worth considering here.

2022-09-07 12:16 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            address={
Outside discussion re: security implications of billing vs. shipping address is relevant here @x110dc

2022-09-07 17:37 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    mailing_postal_code = serializers.CharField(max_length=20, write_only=True)
Okay. I'm going to create a separate ticket to track this. `mailing_postal_code` has references in SPA fixture data and in the page editor, so not a simple migration.

2022-09-07 17:40 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    mailing_postal_code = serializers.CharField(max_length=20, write_only=True)
See https://news-revenue-hub.atlassian.net/browse/DEV-2347

2022-09-07 17:50 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +stripe_errors = (
Changed.

2022-09-07 17:52 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +        for element in [elem for elem in data["page"].elements if len(elem["requiredFields"])]:
Changed.

2022-09-07 17:57 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            "revenue_program_id": validated_data["page"].revenue_program.id,
Added

2022-09-07 18:17 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    reason_for_giving = serializers.CharField(max_length=255, required=False, allow_blank=True, allow_null=True)
Vestigial of some reason at some point and shouldn't be here anymore. Removing.

2022-09-07 19:13 UTC, njharman approved these changes
lgtm ship it!

Good coverage 97.85% overall

2022-09-07 19:22 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +
Removed.

2022-09-08 18:33 UTC, x110dc submitted a review, later dismissed
There's a couple of requested changes that I didn't see actually happen. I did a hard refresh to try to confirm I'm looking at the latest code. Maybe there are unpushed commits?

2022-09-08 18:33 UTC, x110dc commented on apps/contributions/models.py
> +    def create_stripe_one_time_payment_intent(self, stripe_customer_id=None, metadata=None):
Looks like stripe_customer_id is still optional?

2022-09-08 18:33 UTC, x110dc commented on apps/contributions/models.py
> +    def create_stripe_one_time_payment_intent(self, stripe_customer_id=None, metadata=None):
We should also never be creating a one-time payment intent w/o metadata, right?

2022-09-08 18:33 UTC, x110dc commented on apps/contributions/models.py
> +    def create_stripe_subscription(self, stripe_customer_id=None, metadata=None):
Same here right? Should stripe_customer_id and metadata both be required?

2022-09-08 18:33 UTC, x110dc commented on apps/contributions/serializers.py
> +    reason_for_giving = serializers.CharField(max_length=255, required=False, allow_blank=True, allow_null=True)
It looks like "allow_null" is still there. Am I looking a cached out-of-date version of this PR?

2022-09-08 18:33 UTC, x110dc commented on apps/contributions/serializers.py
> +    mailing_postal_code = serializers.CharField(max_length=20, write_only=True)
✅

2022-09-08 18:33 UTC, x110dc commented on apps/contributions/serializers.py
> +
The ".s" is still showing for me. FWIW I just did a hard refresh to try to confirm that I'm looking at the latest version. Are there unpushed commits?

2022-09-08 18:33 UTC, x110dc commented on apps/contributions/serializers.py
> +            # TODO: confirm business requirements around these first two keys/vals
Still see TODO.

2022-09-08 18:33 UTC, x110dc commented on apps/contributions/serializers.py
> +            # TODO: Determine if this requires a different, new 'pre-processing' status
Still see the TODO.

2022-09-08 20:22 UTC, benjaminEwhite commented
Ugg, it looks like somehow overwrote those changes that responded to your comments (possibly switching between this branch and SPA side one, I got confused). Will fix again @x110dc

2022-09-08 20:26 UTC, benjaminEwhite commented on apps/contributions/models.py
> +    def create_stripe_subscription(self, stripe_customer_id=None, metadata=None):
Okay, definitely committed the change this time!

2022-09-08 20:48 UTC, benjaminEwhite commented on apps/contributions/models.py
> +    def create_stripe_one_time_payment_intent(self, stripe_customer_id=None, metadata=None):
Correct. Pushing up commit that fixes.

2022-09-08 20:49 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            # TODO: confirm business requirements around these first two keys/vals
It's really gone now.

2022-09-08 20:52 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            # TODO: Determine if this requires a different, new 'pre-processing' status
Actually committed this time.

2022-09-08 20:56 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    reason_for_giving = serializers.CharField(max_length=255, required=False, allow_blank=True, allow_null=True)
No. I messed up committing changes earlier when switching between branches. Fixed now.

2022-09-08 20:56 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +
Another place where I messed up committing earlier. Fixed now.

2022-09-08 21:15 UTC, x110dc approved these changes

2022-09-09 00:00 UTC, merged