DEV-1035-sign-in
newsrevenuehub/rev-engine pull request #641
Opened 2022-09-03 22:33 UTC by gurjittoptal

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
Sign In Draft

#### What's this PR do?
New Sign In Page based on new designs. Do note that figma designs were updated and JIRA has stale snapshots.

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-1035

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2022-09-07 16:15 UTC, GuiMend requested changes

2022-09-07 16:15 UTC, GuiMend commented on spa/src/components/account/SignIn/SignIn.test.js
> +    expect(screen.getByTestId(`signin-pwd-${Input.types.PASSWORD}`)).toBeInTheDocument();
Another suggestion, probably a bit more suitable for this, is to test that the `input` `hasAttribute("type", "password")` and `hasAttribute("type", "text")`. Than you know that the text is actually showing or if it's hidden.

2022-09-07 16:15 UTC, GuiMend commented on spa/src/components/account/SignIn/SignInForm.js
> +    setShowPassword(showPassword ? false : true);
If you don't want to use `useModal`, better to use previous state to toggle. This current implementation could add some unwanted bugs.
```suggestion
    setShowPassword(prevShow => !prevShow);
```

2022-09-07 16:15 UTC, GuiMend commented on spa/src/components/account/SignIn/SignInForm.js
> +  const [showPassword, setShowPassword] = useState(false);
You could also use the `useModal` hook. It already has that logic built in.
`const { open: showPassword, handleToggle: togglePasswordVisiblity } = useModal()`

2022-09-07 16:15 UTC, GuiMend commented on spa/src/components/account/SignIn/SignInForm.js
> +    await onSubmitSignIn(fdata);
If you aren't doing anything after, you don't need to `await` here

2022-09-07 16:15 UTC, GuiMend commented on spa/src/components/account/SignIn/SignInForm.js
> +              message: 'Please enter a valid email'
If you just remove this message, doesn't it use the default one?
```suggestion
```

2022-09-07 16:15 UTC, GuiMend commented on spa/src/components/account/SignIn/SignInForm.js
> +      <S.Submit type="submit" role="button" disabled={disabled} data-testid="signin-submit">
If `S.Submit` is ` <button>` you don't need to add `role="button"`

2022-09-07 16:30 UTC, gurjittoptal commented on spa/src/components/account/SignIn/SignInForm.js
> +    await onSubmitSignIn(fdata);
removed await.

2022-09-07 16:30 UTC, gurjittoptal commented on spa/src/components/account/SignIn/SignInForm.js
> +              message: 'Please enter a valid email'
removed

2022-09-07 16:31 UTC, gurjittoptal commented on spa/src/components/DashboardRouter.js
> +const SignIn = lazy(() => componentLoader(() => import('components/account/SignIn/SignIn')));
changed to index.js

2022-09-07 16:31 UTC, gurjittoptal commented on spa/cypress/integration/12 - account.spec.js
> +      cy.contains('No active account found with the given credentials');
changes done

2022-09-07 16:31 UTC, gurjittoptal commented on spa/cypress/integration/12 - account.spec.js
> +  flags: [{ ...contentSectionFlag }]
changes done

2022-09-07 16:48 UTC, gurjittoptal commented on spa/src/components/account/Account.styled.js
> +  font-size: 30px;
all font-sizes now use definitions in theming

2022-09-07 16:49 UTC, gurjittoptal commented on spa/src/components/account/SignIn/SignIn.js
> +import * as S from '../Account.styled';
its because same styles are used in multple screens

2022-09-07 17:24 UTC, gurjittoptal commented on spa/src/components/account/Account.styled.js
> +    font-size: 24px;
all font-sizes now use definitions in theming

2022-09-07 17:24 UTC, gurjittoptal commented on spa/src/components/account/Account.styled.js
> +  font-size: 11px;
done

2022-09-07 17:24 UTC, gurjittoptal commented on spa/src/components/account/Account.styled.js
> +  border-radius: 2px;
done

2022-09-07 17:24 UTC, gurjittoptal commented on spa/src/components/account/Account.styled.js
> +  font-size: 13px;
done

2022-09-07 17:29 UTC, gurjittoptal commented on spa/src/components/account/SignIn/SignIn.test.js
> +    const title = screen.queryByText('Welcome Back!');
changed

2022-09-07 17:30 UTC, gurjittoptal commented on spa/src/components/account/SignIn/SignIn.test.js
> +    const resetPassword = screen.queryByTestId('reset-password');
done

2022-09-07 17:32 UTC, gurjittoptal commented on spa/src/components/account/SignIn/SignIn.test.js
> +    ReactTestUtils.Simulate.change(password, { target: { value: 'password' } });
done

2022-09-07 17:32 UTC, gurjittoptal commented on spa/src/components/account/SignIn/SignIn.test.js
> +    expect(screen.getByTestId(`signin-pwd-${Input.types.PASSWORD}`)).toBeInTheDocument();
done

2022-09-07 17:33 UTC, gurjittoptal commented on spa/src/components/account/SignIn/SignInForm.js
> +              message: 'Please enter a valid email'
removed required message but kept pattern one.

2022-09-07 17:34 UTC, gurjittoptal commented on spa/src/components/account/Account.styled.js
> +  border-radius: 4px;
done

2022-09-07 17:47 UTC, gurjittoptal commented on spa/src/components/account/SignIn/SignIn.js
> +  const [loading, setLoading] = useState(false);
agreed. and changed.

2022-09-07 17:47 UTC, gurjittoptal commented on spa/src/components/account/SignIn/SignIn.js
> +            <SignInForm onSubmitSignIn={onSubmitSignIn} loading={loading} />
done.

2022-09-07 17:52 UTC, gurjittoptal commented on spa/src/components/account/SignIn/SignIn.js
> +            {formSubmitErrors ? <S.Message>{formSubmitErrors} </S.Message> : <S.MessageSpacer />}
done

2022-09-07 18:24 UTC, GuiMend requested changes

2022-09-07 18:24 UTC, GuiMend commented on spa/src/components/account/SignIn/index.js
> +
I would suggest leaving this file named `SignIn.ts` and create a separate `index.js` file with:
```
export { default } from "./SignIn"
```

I think it's better to have the file name `SignIn` becaue it's easier to find files.
The objective of the `index.js` is just to make importing less verbose/repetitive (`.../SignIn` instead of `.../SignIn/SignIn`)

2022-09-07 18:24 UTC, GuiMend commented on spa/src/components/account/common/leftbar/Leftbar.js
> +    <>
```suggestion
```

2022-09-07 18:24 UTC, GuiMend commented on spa/src/components/account/common/leftbar/Leftbar.js
> +    </>
```suggestion
```

2022-09-07 18:24 UTC, GuiMend commented on spa/src/components/account/common/leftbar/Leftbar.js
> +function Leftbar({ bgColor = '' }) {
I would suggest adding PropTypes for every component that has props to that it makes it easier to understand:
Generic:
```
Leftbar.propTypes = {
  bgColor: PropTypes.string
}
```

I was looking at the code and noticed a bgColor === 'purple'. If you have a specific value for this, the PropTypes could be:
More Specific:
```
const BG_COLOR = {
   PURPLE: "purple",
   DEFAULT: "",
   // other options
}

Leftbar.propTypes = {
  bgColor: PropTypes.oneOf(Object.values(BG_COLOR))
}

Leftbar.defaultProps= {
  bgColor: BG_COLOR.DEFAULT
}
```

2022-09-07 18:24 UTC, GuiMend commented on spa/src/components/account/common/leftbar/Leftbar.js
> +      <S.Logo data-testid={bgColor === 'purple' ? 'logo' : 'logo2'} src={bgColor === 'purple' ? logo : logo2} />
In case you do my previous suggestion:
```suggestion
      <S.Logo data-testid={bgColor === BG_COLOR.PURPLE ? 'logo' : 'logo2'} src={bgColor === BG_COLOR.PURPLE ? logo : logo2} />
```

2022-09-07 18:24 UTC, GuiMend commented on spa/src/components/account/common/leftbar/Leftbar.styled.js
> +    props.bgColor && props.bgColor === 'purple' ? props.theme.colors.white : props.theme.colors.account.purple[1]};
If you use the BG_COLOR variable here as well, probably need to create a constant file to have the declaration to avoid circular imports
```suggestion
    props.bgColor && props.bgColor === BG_COLOR.PURPLE ? props.theme.colors.white : props.theme.colors.account.purple[1]};
```

2022-09-07 18:24 UTC, GuiMend commented on spa/src/components/account/common/leftbar/Leftbar.styled.js
> +  font-size: 36px;
Font size -> theme.fontSizeUpdated

2022-09-07 18:24 UTC, GuiMend commented on spa/src/components/account/common/leftbar/Leftbar.styled.js
> +    font-size: 26px;
Font size -> theme.fontSizeUpdated

2022-09-07 18:24 UTC, GuiMend commented on spa/src/components/account/common/leftbar/Leftbar.styled.js
> +      props.bgColor && props.bgColor === 'purple'
```suggestion
      props.bgColor && props.bgColor === BG_COLOR.PURPLE
```

2022-09-07 18:24 UTC, GuiMend commented on spa/src/components/account/common/leftbar/Leftbar.styled.js
> +  font-size: 18px;
Font size -> theme.fontSizeUpdated

2022-09-07 18:24 UTC, GuiMend commented on spa/src/components/account/common/leftbar/Leftbar.styled.js
> +  font-size: 12px;
Font size -> theme.fontSizeUpdated

2022-09-07 18:24 UTC, GuiMend commented on spa/src/components/account/common/logobar/Logobar.styled.js
> +  font-size: 16px;
Font size -> theme.fontSizeUpdated

2022-09-07 18:24 UTC, GuiMend commented on spa/src/components/account/common/logobar/Logobar.styled.js
> +  color: #323232;
Use color from theme file

2022-09-07 18:24 UTC, GuiMend commented on spa/src/components/account/common/logobar/Logobar.styled.js
> +    font-size: 12px;
Font size -> theme.fontSizeUpdated

2022-09-07 18:24 UTC, GuiMend commented on spa/src/styles/themes.js
> +    grey: ['#eee', '#ccc', '#999', '#666', '#333', '#282828'],
We already have that color in `muiGrey[900]`

2022-09-07 18:24 UTC, GuiMend commented on spa/src/styles/themes.js
> +  fontSizes: ['12px', '16px', '24px', '32px', '48px', '84px', '96px', '72px'],
Better to add the new sizes to `fontSizesUpdated`. Maybe use `xl: 72px`

2022-09-07 18:24 UTC, GuiMend commented on spa/src/styles/themes.js
> +    mdUp: 'min-width: 890px'
We are using `tabletLandscapeDown` in several places, you have to update all those places with the new ones if you'd like to delete this value

![image](https://user-images.githubusercontent.com/9381325/188950571-6391572d-cbdb-46c6-84f6-db5baf023740.png)

2022-09-07 18:50 UTC, gurjittoptal commented on spa/src/styles/themes.js
> +    mdUp: 'min-width: 890px'
yeah! damn. nice catch. will revert that.

2022-09-07 18:52 UTC, gurjittoptal commented on spa/src/components/account/SignIn/SignInForm.js
> +  const disabled = watchEmail === '' || watchPassword === '' || loading;
its actually an AC in other tickets. Added for consistency

2022-09-07 19:35 UTC, gurjittoptal commented on spa/src/styles/themes.js
> +    mdUp: 'min-width: 890px'
done

2022-09-07 19:36 UTC, gurjittoptal commented on spa/src/styles/themes.js
> +  fontSizes: ['12px', '16px', '24px', '32px', '48px', '84px', '96px', '72px'],
done

2022-09-07 19:36 UTC, gurjittoptal commented on spa/src/styles/themes.js
> +    grey: ['#eee', '#ccc', '#999', '#666', '#333', '#282828'],
ok. removed

2022-09-07 19:36 UTC, gurjittoptal commented on spa/src/components/account/common/logobar/Logobar.styled.js
> +    font-size: 12px;
done.

2022-09-07 19:37 UTC, gurjittoptal commented on spa/src/components/account/common/logobar/Logobar.styled.js
> +  color: #323232;
done

2022-09-07 19:37 UTC, gurjittoptal commented on spa/src/components/account/common/logobar/Logobar.styled.js
> +  font-size: 16px;
done

2022-09-07 19:37 UTC, gurjittoptal commented on spa/src/components/account/common/leftbar/Leftbar.styled.js
> +  font-size: 12px;
done

2022-09-07 19:38 UTC, gurjittoptal commented on spa/src/components/account/common/leftbar/Leftbar.styled.js
> +  font-size: 18px;
done

2022-09-07 19:38 UTC, gurjittoptal commented on spa/src/components/account/common/leftbar/Leftbar.styled.js
> +    font-size: 26px;
done

2022-09-07 19:38 UTC, gurjittoptal commented on spa/src/components/account/common/leftbar/Leftbar.styled.js
> +  font-size: 36px;
done

2022-09-07 19:38 UTC, gurjittoptal commented on spa/src/components/account/common/leftbar/Leftbar.js
> +    </>
done

2022-09-07 19:39 UTC, gurjittoptal commented on spa/src/components/account/common/leftbar/Leftbar.js
> +    <>
done

2022-09-07 19:39 UTC, gurjittoptal commented on spa/src/components/account/SignIn/index.js
> +
done

2022-09-07 19:39 UTC, gurjittoptal commented on spa/src/components/account/SignIn/SignInForm.test.js
> +    fireEvent.submit(screen.getByRole('button'));
done

2022-09-07 19:40 UTC, gurjittoptal commented on spa/src/components/account/SignIn/SignInForm.js
> +  //const [showPassword, setShowPassword] = useState(false);
done

2022-09-07 19:41 UTC, gurjittoptal commented on spa/src/components/account/SignIn/SignIn.js
> +            <br />
done

2022-09-08 12:07 UTC, gurjittoptal commented on spa/src/components/account/common/leftbar/Leftbar.js
> +function Leftbar({ bgColor = '' }) {
agreed. we should make that a standard. For this component we needs a boolean, as there are two options. thats need committed.

2022-09-08 12:07 UTC, gurjittoptal commented on spa/src/components/account/common/leftbar/Leftbar.styled.js
> +    props.bgColor && props.bgColor === 'purple' ? props.theme.colors.white : props.theme.colors.account.purple[1]};
done

2022-09-08 12:07 UTC, gurjittoptal commented on spa/src/components/account/common/leftbar/Leftbar.js
> +      <S.Logo data-testid={bgColor === 'purple' ? 'logo' : 'logo2'} src={bgColor === 'purple' ? logo : logo2} />
done

2022-09-08 14:44 UTC, GuiMend requested changes
A few small changes

2022-09-08 14:44 UTC, GuiMend commented on spa/src/components/account/SignIn/SignInForm.js
> +        <a href={FORGOT_PASSWORD} data-testid="reset-password" tabIndex="-1">
Why do we have this `tabIndex`? Shouldn't the user be able to access this via "tab"?

I think this link should be accessible with tabs
```suggestion
        <a href={FORGOT_PASSWORD} data-testid="reset-password">
```

2022-09-08 14:44 UTC, GuiMend commented on spa/src/components/account/SignIn/SignInForm.test.js
> +    expect(password.getAttribute('type')).toEqual(Input.types.PASSWORD);
👍

2022-09-08 14:44 UTC, GuiMend commented on spa/src/components/account/common/leftbar/Leftbar.js
> +function Leftbar({ isCreateAccountPage }) {
Nice change. It's clearer now 👍

2022-09-08 14:44 UTC, GuiMend commented on spa/src/components/account/common/leftbar/Leftbar.styled.js
> +    font-size: ${(props) => props.theme.fontSizes[2]};
Better to use `fontSizesUpdated` so we can hopefully deprecate the old fontSizes soon

2022-09-08 14:44 UTC, GuiMend commented on spa/src/components/account/common/logobar/Logobar.styled.js
> +  font-size: ${(props) => props.theme.fontSizes[1]};
fontSizesUpdated

2022-09-08 14:44 UTC, GuiMend commented on spa/src/components/account/common/logobar/Logobar.styled.js
> +    font-size: ${(props) => props.theme.fontSizes[0]};
fontSizesUpdated

2022-09-08 15:37 UTC, gurjittoptal commented on spa/src/components/account/common/leftbar/Leftbar.styled.js
> +    font-size: ${(props) => props.theme.fontSizes[2]};
makes sense. how do i put 24px/48px in that?

2022-09-08 15:53 UTC, gurjittoptal commented on spa/src/components/account/common/logobar/Logobar.styled.js
> +    font-size: ${(props) => props.theme.fontSizes[0]};
done

2022-09-08 15:53 UTC, gurjittoptal commented on spa/src/components/account/common/logobar/Logobar.styled.js
> +  font-size: ${(props) => props.theme.fontSizes[1]};
done

2022-09-08 15:53 UTC, gurjittoptal commented on spa/src/components/account/common/leftbar/Leftbar.styled.js
> +    font-size: ${(props) => props.theme.fontSizes[2]};
done

2022-09-08 15:53 UTC, gurjittoptal commented on spa/src/components/account/SignIn/SignInForm.js
> +        <a href={FORGOT_PASSWORD} data-testid="reset-password" tabIndex="-1">
done

2022-09-08 15:55 UTC, gurjittoptal commented on spa/src/components/account/SignIn/SignIn.test.js
> +    expect(screen.getByTestId(`signin-pwd-${Input.types.PASSWORD}`)).toBeInTheDocument();
its been done since

2022-09-08 20:18 UTC, GuiMend approved these changes
Code LGTM 👍

2022-09-13 18:02 UTC, x110dc approved these changes

2022-09-14 21:36 UTC, merged