Dev 2039 forgot password and reset password
newsrevenuehub/rev-engine pull request #645
Opened 2022-09-05 16:26 UTC by gurjittoptal

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
Draft

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-2039
https://news-revenue-hub.atlassian.net/browse/DEV-2029

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2022-09-07 18:07 UTC, nrh-cklimas requested changes
I think there are some wording changes we'll need but checking about that, will update here when I know. Wanted to get the code suggestions to you as soon as I could.

2022-09-07 18:07 UTC, nrh-cklimas commented on spa/src/components/account/ResetPassword/index.js
> +      if (status === 200) {
Should this dispatch FETCH_FAILURE if status isn't 200?

2022-09-07 18:07 UTC, nrh-cklimas commented on spa/src/components/account/ForgotPassword/index.js
> +      setInfoMessage('Success. If your email is registered, an email with a reset-link will be sent. ');
I noticed that the reset password request checks status code, but this doesn't--should it?

2022-09-07 18:07 UTC, nrh-cklimas commented on spa/src/components/account/ForgotPassword/ForgotPassword.test.js
> +describe('ForgotPassword Tests', () => {
Could we add a test that it shows ForgotPasswordForm? Just a basic visibility test should do it.

2022-09-07 18:07 UTC, nrh-cklimas commented on spa/src/components/account/ResetPassword/ResetPassword.test.js
> +  it('should have password toggle icon to show/hide value of password if its visibility icon is clicked', () => {
Think these toggle tests should go under ResetPasswordForm?

2022-09-07 18:07 UTC, nrh-cklimas commented on spa/src/components/account/ResetPassword/ResetPassword.test.js
> +describe('ForgotPassword Tests', () => {
Same thought as ResetPassword--can we add a test that it shows ResetPasswordForm?

2022-09-07 19:09 UTC, nrh-cklimas commented on spa/src/components/account/ForgotPassword/ForgotPasswordForm.js
> +              message: 'Please enter a valid email id'
```suggestion
              message: 'Please enter a valid email address'
```

2022-09-07 19:09 UTC, nrh-cklimas commented on spa/src/components/account/ForgotPassword/index.js
> +      setInfoMessage('Success. If your email is registered, an email with a reset-link will be sent. ');
```suggestion
      setInfoMessage('Success. If your email is registered, an email with a reset link will be sent to it.');
```

2022-09-07 19:10 UTC, nrh-cklimas commented on spa/src/components/account/ResetPassword/ResetPasswordForm.js
> +                return 'Your passwords do no match';
```suggestion
                return 'The passwords you entered do not match';
```

2022-09-07 19:10 UTC, nrh-cklimas commented on spa/src/components/account/ResetPassword/index.js
> +            {PasswordUpdateSuccess ? 'Your password has been successfuly reset.' : 'Enter your new password below.'}
```suggestion
            {PasswordUpdateSuccess ? 'Your password has been successfully reset.' : 'Enter your new password below.'}
```

2022-09-07 19:56 UTC, GuiMend requested changes

2022-09-07 19:56 UTC, GuiMend commented on spa/src/components/account/Account.styled.js
> +  max-width: ${(props) => (props.type && props.type === 'PasswordUpdateSuccess' ? '310px' : '420px')};
Could we make `PasswordUpdateSuccess` a constant? Better than to be hardcoded, specially as it's being used in more than 1 place

2022-09-07 19:56 UTC, GuiMend commented on spa/src/components/account/Account.styled.js
> +  font-size: ${(props) => props.theme.fontSizes[1]};
Use `fontSizesUpdated` instead

2022-09-07 19:56 UTC, GuiMend commented on spa/src/components/account/ForgotPassword/ForgotPassword.test.js
> +import ForgotPassword from '.';
Same comment as the other PR. Would rather have 2 files: `./ForgotPassword.js` and `./index.js`

2022-09-07 19:56 UTC, GuiMend commented on spa/src/components/account/ForgotPassword/ForgotPasswordForm.js
> +  const disabled = loading || watchEmail === '';
Same as other PR: probably can use loading as disabled and if the email is empty and the user clicks submit, they will get an email error beneath the input

2022-09-07 19:56 UTC, GuiMend commented on spa/src/components/account/ForgotPassword/index.js
> +  const [loading, setLoading] = useState(false);
Not being used in the file
```suggestion
```

2022-09-07 19:56 UTC, GuiMend commented on spa/src/components/account/ForgotPassword/index.js
> +      setInfoMessage('Success. If your email is registered, an email with a reset-link will be sent. ');
Would be good to use a constant so that we can test if the text is being displayed correctly
```suggestion
      setInfoMessage('Success. If your email is registered, an email with a reset-link will be sent.');
```

2022-09-07 19:56 UTC, GuiMend commented on spa/src/routes.js
> +export const RESET_PASSWORD = '/password_reset';
Why change reset password to `_` and leave the other as `-`? Think it's best that we follow a url pattern

2022-09-07 19:56 UTC, GuiMend commented on spa/src/components/account/ResetPassword/index.js
> +  }
```suggestion
  const formSubmissionMessage = useMemo(() => {
     if (formSubmitErrors) {
       return <S.Message>{formSubmitErrors}</S.Message>;
     }
     return <S.MessageSpacer />;
  },[])
```

2022-09-07 22:39 UTC, gurjittoptal commented on spa/src/components/account/ForgotPassword/ForgotPassword.test.js
> +describe('ForgotPassword Tests', () => {
done

2022-09-07 22:39 UTC, gurjittoptal commented on spa/src/components/account/ResetPassword/ResetPassword.test.js
> +describe('ForgotPassword Tests', () => {
done

2022-09-07 22:39 UTC, gurjittoptal commented on spa/src/components/account/ResetPassword/ResetPassword.test.js
> +  it('should have password toggle icon to show/hide value of password if its visibility icon is clicked', () => {
agreed.

2022-09-07 22:39 UTC, gurjittoptal commented on spa/src/components/account/ResetPassword/ResetPasswordForm.js
> +  const onSubmit = async (fdata) => {
done

2022-09-07 22:40 UTC, gurjittoptal commented on spa/src/routes.js
> +export const RESET_PASSWORD = '/password_reset';
thats because, email has an _

JIRA is updated

2022-09-07 22:41 UTC, gurjittoptal commented on spa/src/components/account/ForgotPassword/ForgotPassword.test.js
> +    const signIn = screen.getByTestId('sign-in');
done

2022-09-07 22:41 UTC, gurjittoptal commented on spa/src/components/account/ResetPassword/ResetPasswordForm.js
> +              if (val.length < 8 || !/[a-zA-Z]/.test(val) || !/[0-9]/.test(val)) {
done

2022-09-07 22:41 UTC, gurjittoptal commented on spa/src/components/account/ResetPassword/ResetPasswordForm.js
> +      <S.InputLabel hasError={errors.password}>Password</S.InputLabel>
done

2022-09-07 22:42 UTC, gurjittoptal commented on spa/src/components/account/ResetPassword/index.js
> +  const token = qParams.get('token');
The backend does not accept and returns a 'Not Found' response.

2022-09-07 22:43 UTC, gurjittoptal commented on spa/src/components/account/ResetPassword/index.js
> +      if (status === 200) {
yeah, that fallback is added now.

2022-09-07 22:44 UTC, gurjittoptal commented on spa/src/components/account/ForgotPassword/index.js
> +      setInfoMessage('Success. If your email is registered, an email with a reset-link will be sent. ');
API always returns an OK, so just put this generic message for all scenarios.

2022-09-07 22:44 UTC, gurjittoptal commented on spa/src/components/account/ForgotPassword/ForgotPasswordForm.js
> +              message: 'Please enter a valid email id'
done

2022-09-07 22:44 UTC, gurjittoptal commented on spa/src/components/account/ForgotPassword/index.js
> +      setInfoMessage('Success. If your email is registered, an email with a reset-link will be sent. ');
done

2022-09-07 22:45 UTC, gurjittoptal commented on spa/src/components/account/ResetPassword/index.js
> +            {PasswordUpdateSuccess ? 'Your password has been successfuly reset.' : 'Enter your new password below.'}
done

2022-09-07 22:45 UTC, gurjittoptal commented on spa/cypress/integration/12 - account.spec.js
> +      cy.contains('Success. If your email is registered, an email with a reset-link will be sent.');
done

2022-09-07 22:45 UTC, gurjittoptal commented on spa/cypress/integration/12 - account.spec.js
> +      cy.contains('Your password has been successfuly reset.');
done

2022-09-07 22:46 UTC, gurjittoptal commented on spa/src/components/account/Account.styled.js
> +  max-width: ${(props) => (props.type && props.type === 'PasswordUpdateSuccess' ? '310px' : '420px')};
Changed to boolean properties as unlikely these will have more than two values.

2022-09-07 22:46 UTC, gurjittoptal commented on spa/src/components/account/ResetPassword/index.js
> +  const [PasswordUpdateSuccess, setPasswordUpdateSuccess] = useState(false);
done

2022-09-07 22:46 UTC, gurjittoptal commented on spa/src/components/account/ResetPassword/ResetPasswordForm.js
> +        {' '}
done

2022-09-07 22:55 UTC, gurjittoptal commented on spa/src/components/account/ResetPassword/ResetPasswordForm.js
> +        {' '}
yes. removed

2022-09-07 22:58 UTC, gurjittoptal commented on spa/src/components/account/ForgotPassword/ForgotPasswordForm.js
> +  const disabled = loading || watchEmail === '';
'they will get an email error beneath the input' - its an acceptance criteria AC4

<img width="849" alt="image" src="https://user-images.githubusercontent.com/30353391/188997676-43660df1-afcc-4993-a8f5-066862de27de.png">

2022-09-08 02:59 UTC, gurjittoptal commented on spa/src/components/account/ResetPassword/index.js
> +  }
done

2022-09-08 02:59 UTC, gurjittoptal commented on spa/src/components/account/Account.styled.js
> +  font-size: ${(props) => props.theme.fontSizes[1]};
done

2022-09-08 02:59 UTC, gurjittoptal commented on spa/src/components/account/ForgotPassword/index.js
> +  const [loading, setLoading] = useState(false);
done

2022-09-08 03:00 UTC, gurjittoptal commented on spa/src/components/account/ForgotPassword/index.js
> +      setInfoMessage('Success. If your email is registered, an email with a reset-link will be sent. ');
done

2022-09-08 03:00 UTC, gurjittoptal commented on spa/src/components/account/ForgotPassword/index.js
> +  }
done

2022-09-08 12:25 UTC, nrh-cklimas commented on spa/src/components/account/ResetPassword/ResetPassword.test.js
> +  it('should have password toggle icon to show/hide value of password if its visibility icon is clicked', () => {
I think these tests didn't get moved? I'm just suggesting moving them into ResetPasswordForm.test.js.

2022-09-08 12:32 UTC, gurjittoptal commented on spa/src/components/account/ResetPassword/ResetPasswordForm.js
> +  const onSubmit = async (fdata) => {
hmm. did in other form. pushing in next commit.

2022-09-08 12:32 UTC, gurjittoptal commented on spa/src/components/account/ResetPassword/ResetPassword.test.js
> +  it('should have password toggle icon to show/hide value of password if its visibility icon is clicked', () => {
they got moved to other but were not removed. pushing in next commit.

2022-09-08 12:41 UTC, gurjittoptal commented on spa/src/components/account/ResetPassword/ResetPasswordForm.js
> +  const onSubmit = async (fdata) => {
fixed in [https://github.com/newsrevenuehub/rev-engine/pull/645/commits/7eaf1152e6324d1d2da44ace230b8145c77daf32](https://github.com/newsrevenuehub/rev-engine/pull/7eaf1152e)

2022-09-08 12:50 UTC, nrh-cklimas approved these changes

2022-09-08 15:13 UTC, GuiMend requested changes
A few small changes

2022-09-08 15:13 UTC, GuiMend commented on spa/src/components/account/ResetPassword/ResetPassword.js
> +  const token = qParams.get('token');
If `FetchQueryParams` and `qParams` are being used only here, I think we don't need a separate function/constant for this:

```suggestion
function ResetPassword() {
  useConfigureAnalytics();
  const { search } = useLocation();
  const token = useMemo(() => new URLSearchParams(search).get('token'), [search]);
```

2022-09-08 15:13 UTC, GuiMend commented on spa/src/components/account/ResetPassword/ResetPassword.js
> +      dispatch({ type: FETCH_SUCCESS });
Same as before: `dispatch({ type: FETCH_SUCCESS })` should be inside `if (status === 200)`

2022-09-08 15:13 UTC, GuiMend commented on spa/src/components/account/ResetPassword/ResetPassword.test.js
> +  it('should have ResetPassword Form', () => {
Is only testing for `expect(screen.getByRole('button', { type: 'submit' })).toBeInTheDocument();` is enough for this test?
If yes, just ignore this comment

2022-09-08 15:13 UTC, GuiMend commented on spa/src/components/account/ResetPassword/ResetPasswordForm.js
> +    <form onSubmit={disabled ? () => {} : handleSubmit(onSubmit)}>
Same as before: if submit button is disabled, don't need this
```suggestion
    <form onSubmit={handleSubmit(onSubmit)}>
```

2022-09-08 15:13 UTC, GuiMend commented on spa/src/components/account/ResetPassword/ResetPasswordForm.test.js
> +    expect(password.getAttribute('type')).toEqual(Input.types.PASSWORD);
Suggestion, could also add a check for the initial:
```suggestion
    const toggleIcon = screen.getByTestId('toggle-password');
    expect(password.getAttribute('type')).toEqual(Input.types.PASSWORD);
    fireEvent.click(toggleIcon);
    expect(password.getAttribute('type')).toEqual(Input.types.TEXT);
    fireEvent.click(toggleIcon);
    expect(password.getAttribute('type')).toEqual(Input.types.PASSWORD);
```

2022-09-08 15:41 UTC, gurjittoptal commented on spa/src/components/account/ResetPassword/ResetPasswordForm.js
> +    <form onSubmit={disabled ? () => {} : handleSubmit(onSubmit)}>
[nrh-cklimas](https://github.com/nrh-cklimas) had this suggestion for a fallback. And it does not bother us, so lets keep i would say.

2022-09-08 21:55 UTC, gurjittoptal commented on spa/src/components/account/ForgotPassword/ForgotPassword.js
> +const FORGOT_PASSWORD_SUCCESS = 'Success. If your email is registered, an email with a reset link will be sent to it.';
done

2022-09-08 21:55 UTC, gurjittoptal commented on spa/cypress/integration/12 - account.spec.js
> +const FORGOT_PASSWORD_SUCCESS = 'Success. If your email is registered, an email with a reset link will be sent to it.';
done

2022-09-08 21:55 UTC, gurjittoptal commented on spa/src/components/account/ForgotPassword/ForgotPassword.js
> +      dispatch({ type: FETCH_SUCCESS });
done

2022-09-08 21:56 UTC, gurjittoptal commented on spa/src/components/account/ForgotPassword/ForgotPasswordForm.js
> +              message: 'Please enter a valid email address'
done

2022-09-08 21:56 UTC, gurjittoptal commented on spa/src/components/account/ResetPassword/ResetPassword.js
> +      dispatch({ type: FETCH_SUCCESS });
yes

2022-09-08 21:57 UTC, gurjittoptal commented on spa/src/components/account/ResetPassword/ResetPassword.test.js
> +  it('should have ResetPassword Form', () => {
yeah. just inferring that form exists bcas submt button is there

2022-09-08 21:57 UTC, gurjittoptal commented on spa/src/components/account/ResetPassword/ResetPasswordForm.test.js
> +    expect(password.getAttribute('type')).toEqual(Input.types.PASSWORD);
done

2022-09-08 21:58 UTC, gurjittoptal commented on spa/src/components/account/ResetPassword/ResetPassword.js
> +  const token = qParams.get('token');
done

2022-09-09 15:34 UTC, GuiMend approved these changes
LGTM 👍

2022-09-13 18:06 UTC, x110dc approved these changes

2022-09-13 23:00 UTC, merged