DEV-2305: GrabLink Button
newsrevenuehub/rev-engine pull request #647
Opened 2022-09-05 21:51 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
N/A

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2022-09-06 14:50 UTC, nrh-cklimas commented on spa/src/components/errors/GenericErrorBoundary.test.js
> +import { render, screen } from 'test-utils';
👍 on the cleanup here.

2022-09-06 15:08 UTC, nrh-cklimas reviewed
Only other thing I wondered about was, what do we want to do if copying text fails, e.g. someone has their browser locked down? We _could_ detect it by seeing if `navigator.clipboard.writeText()` rejects. Might be out of scope for the story.

2022-09-06 15:08 UTC, nrh-cklimas commented on spa/src/components/dashboard/topbar/DashboardTopbar.test.js
> +    const grabLink = screen.queryByRole('button', { name: /grab link/i });
Could we move this into a separate test for clarity?

2022-09-06 15:08 UTC, nrh-cklimas commented on spa/src/components/common/Button/GrabLink/GrabLink.test.js
> +    expect(screen.queryByRole('button', { name: /copy contribution page link/i })).toBeNull();
How about adding a test that the text got copied, like:

```
    expect(mockClipboard.writeText.mock.calls).toEqual([
      [`${page.revenue_program.slug}.${window.location.host}/${page.slug}`]
    ]);
```

2022-09-06 15:33 UTC, benjaminEwhite commented
@GuiMend reviewing now. Will go over code, but just tested in review app, and looks like the URLs aren't right, at least in review app.  For instance: http://berkleyside-dev-2305.dev-2305.revengine-review.org/donate , which should be https://berkleyside-dev-2305.revengine-review.org/donate

2022-09-06 15:50 UTC, benjaminEwhite approved these changes
This is great. Looks good, works well, has accessible elements, is well tested, and has Storybook stories.  Good stuff.

If there's a relatively low effort way to get the links working in review app environment, that would be great, but not essential.

Really good work!

2022-09-06 17:56 UTC, GuiMend commented on spa/src/components/common/Button/GrabLink/GrabLink.js
> +  const renderCopyButton = (title, link) => {
We could do that, but I opted for leaving it here because it should only be used in this `GrabLink` higher component, so I didn't think it would be necessary to create a hole new component structure for just this.

Perhaps we wait until we need to re-use it in other places before abstracting it into another component? Also, in the previous retro one of the feedbacks was to not abstract precociously to avoid unnecessary complexity

2022-09-06 17:58 UTC, GuiMend commented on spa/src/components/dashboard/topbar/DashboardTopbar.test.js
> +    const grabLink = screen.queryByRole('button', { name: /grab link/i });
I think it makes sense to be here because the grabLink isn't supposed to be shown when the sign out button is present. There is also another file with extensive testing of the grab link functionality

2022-09-06 18:10 UTC, gurjittoptal reviewed
For an unpublished page, grab-link shows e.g
https://dev-2305.revengine-review.org/edit/newsrevenuehub-dev-2305/20220728
AC2 is
“Grab link” CTA only displays in the page editor when the page is published 

----

All else looks perfect.

2022-09-06 18:34 UTC, gurjittoptal approved these changes

2022-09-06 18:48 UTC, nrh-cklimas commented on spa/src/components/common/Button/GrabLink/GrabLink.js
> +  const renderCopyButton = (title, link) => {
Your call here--I think it essentially is already a separate component as you have it and is covered by tests as it is.

2022-09-06 18:49 UTC, nrh-cklimas commented on spa/src/components/dashboard/topbar/DashboardTopbar.test.js
> +    const grabLink = screen.queryByRole('button', { name: /grab link/i });
Reacting to here that the test description is "should show logout link in topbar" -- doesn't say anything about the grab link not being present. I guess it could say "should show logout link in topbar and not grab link button" but it seems easier to me to just make a second test with what you've written here.

2022-09-06 19:00 UTC, nrh-cklimas requested changes
Small changes I left comments about.

2022-09-06 19:11 UTC, nrh-cklimas approved these changes

2022-09-08 18:36 UTC, x110dc approved these changes

2022-09-08 20:08 UTC, merged