Dev 1679 create account
newsrevenuehub/rev-engine pull request #648
Opened 2022-09-05 21:53 UTC by gurjittoptal

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
WIP . to check API endpoints are working well

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2022-09-09 17:04 UTC, GuiMend requested changes
@gurjittoptal , it would be better to import the icons as `svg` instead of `png`. If you are using figma, you can select the export method (png, svg or jpg)

![image](https://user-images.githubusercontent.com/9381325/189399690-391dfaa5-3c40-43f4-a7ab-1cfa43f00da7.png)

2022-09-09 17:04 UTC, GuiMend commented on spa/src/components/account/Verify/Verify.js
> +        window.location.href = mailto;
Would probably add the `mailto` string here
```suggestion
const Mailto = ({ mailto, label }) => {
  return (
    <Link
      to="#"
      onClick={(e) => {
        window.location.href = `mailto:${mailto}`;
```

2022-09-09 17:04 UTC, GuiMend commented on spa/src/components/account/Verify/Verify.js
> +            <Mailto label={VERIFIED_HELP_EMAIL} mailto={`mailto:${VERIFIED_HELP_EMAIL}`} />
```suggestion
            <Mailto label={VERIFIED_HELP_EMAIL} mailto={VERIFIED_HELP_EMAIL} />
```

2022-09-09 20:57 UTC, gurjittoptal commented on spa/src/components/account/Verify/Verify.js
> +            <Mailto label={VERIFIED_HELP_EMAIL} mailto={`mailto:${VERIFIED_HELP_EMAIL}`} />
done

2022-09-09 20:57 UTC, gurjittoptal commented on spa/src/components/account/Verify/Verify.js
> +        window.location.href = mailto;
done

2022-09-09 20:57 UTC, gurjittoptal commented on spa/src/components/account/SignUp/SignUpForm.js
> +              message: 'Please enter a valid email'
done

2022-09-09 20:58 UTC, gurjittoptal commented on spa/src/components/account/SignUp/SignUpForm.js
> +    <form onSubmit={disabled ? () => {} : handleSubmit(onSubmit)}>
keeping it for consistency.  Agreed, its kind of redundant but we can let it be.

2022-09-09 20:58 UTC, gurjittoptal commented on spa/src/components/account/SignUp/SignUp.js
> +}
done

2022-09-09 20:58 UTC, gurjittoptal commented on spa/src/components/account/SignUp/SignUp.js
> +    }
done

2022-09-09 20:58 UTC, gurjittoptal commented on spa/src/components/account/SignUp/SignUpForm.js
> +  };
done

2022-09-09 20:59 UTC, gurjittoptal commented on spa/src/components/account/SignUp/SignUp.js
> +      dispatch({ type: FETCH_SUCCESS });
fixed now.

2022-09-09 20:59 UTC, gurjittoptal commented on spa/src/components/account/SignUp/SignUp.js
> +          <Header />
done

2022-09-09 20:59 UTC, gurjittoptal commented on spa/src/components/account/Account.styled.js
> +    font-size: 11px;
done

2022-09-09 20:59 UTC, gurjittoptal commented on spa/src/components/account/Account.styled.js
> +  color: ${(props) => props.theme.colors.grey[3]};
done

2022-09-09 20:59 UTC, gurjittoptal commented on spa/src/components/account/Account.styled.js
> +  font-size: 12px;
done

2022-09-09 20:59 UTC, gurjittoptal commented on spa/src/components/account/Account.styled.js
> +  font-size: 11px;
done

2022-09-09 22:02 UTC, gurjittoptal commented on spa/src/components/DashboardRouter.js
> +
done

2022-09-09 22:02 UTC, gurjittoptal commented on spa/src/components/Main.js
> +const UserDataProviderContext = createContext(null);
done

2022-09-09 22:02 UTC, gurjittoptal commented on spa/src/components/Main.js
> +        <PageContextProvider>
done

2022-09-09 22:03 UTC, gurjittoptal commented on spa/src/components/account/SignUp/SignUpForm.test.js
> +    ReactTestUtils.Simulate.change(inp, { target: { checked: true } });
this one  i somehow could not get working. ( spent quite some time too )

2022-09-12 17:40 UTC, GuiMend commented on spa/src/components/account/SignUp/SignUpForm.test.js
> +    ReactTestUtils.Simulate.change(inp, { target: { checked: true } });
Did you try `fireEvent.change(slugInput, { target: { value: 'donate-now' } });` ? if it doesn't work it's ok to leave it like this

2022-09-12 17:49 UTC, GuiMend requested changes
Small changes

2022-09-12 17:49 UTC, GuiMend commented on spa/src/components/Main.js
> +  const { setUser: setUserContext } = useUserContext();
Can't you use `user` from Context as well?
```suggestion
  const { user, setUser } = useUserContext();
```

2022-09-12 17:49 UTC, GuiMend commented on spa/src/components/UserContext.js
> +const UserContextProvider = ({ children }) => {
Awesome 👍

2022-09-12 17:49 UTC, GuiMend commented on spa/src/components/account/SignUp/SignUpForm.js
> +            required: '',
Don't we remove the entire thing?
```suggestion
```

2022-09-12 17:49 UTC, GuiMend commented on spa/src/components/account/SignUp/SignUpForm.js
> +    <form onSubmit={disabled ? () => {} : handleSubmit(onSubmitSignUp)}>
You already disabled the button, no need to have this here
```suggestion
    <form onSubmit={handleSubmit(onSubmitSignUp)}>
```

2022-09-12 21:12 UTC, gurjittoptal commented on spa/src/components/account/SignUp/SignUpForm.test.js
> +    ReactTestUtils.Simulate.change(inp, { target: { checked: true } });
this and a few other things i tried did not work. fireEvent.change(inp, { target: { checked: true } });

so letting it be for now.

2022-09-12 21:33 UTC, gurjittoptal commented on spa/src/components/Main.js
> +  const { setUser: setUserContext } = useUserContext();
done

2022-09-12 21:33 UTC, gurjittoptal commented on spa/src/components/account/SignUp/SignUp.test.js
> +  expect(icons).toBeInTheDocument();
done.

2022-09-12 22:11 UTC, gurjittoptal commented on spa/src/components/account/SignUp/SignUpForm.js
> +    <form onSubmit={disabled ? () => {} : handleSubmit(onSubmitSignUp)}>
thats because checked is a muicheckbox. letting it be for now.

2022-09-12 22:11 UTC, gurjittoptal commented on spa/src/components/account/SignUp/SignUpForm.js
> +            required: '',
done

2022-09-13 14:11 UTC, GuiMend approved these changes

2022-09-13 14:11 UTC, GuiMend commented on apps/users/views.py
> +        print(url)
Print ?
```suggestion
```

2022-09-13 18:13 UTC, x110dc requested changes

2022-09-13 18:13 UTC, x110dc commented on apps/users/serializers.py
> +        user.is_active = True
Why was this changed @gurjittoptal ?

2022-09-13 18:53 UTC, gurjittoptal commented on apps/users/serializers.py
> +        user.is_active = True
@x110dc because else login fails.

2022-09-13 19:16 UTC, x110dc approved these changes

2022-09-13 19:16 UTC, x110dc commented on apps/users/serializers.py
> +        user.is_active = True
✅

2022-09-16 23:37 UTC, merged