DEV-1951: Update favicon, make static
newsrevenuehub/rev-engine pull request #651
Opened 2022-09-06 14:42 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

- Updates the SPA favicon following the recommendations at https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs.
- Makes the favicon a static asset instead of being loaded dynamically. This helps with scenarios where a browser tries to load the favicon for things like a home screen. If we decide later that we want custom favicons per org, we could make the favicon dynamic again.

#### Why are we doing this? How does it help us?

Better branding

#### How should this be manually tested? Please include detailed step-by-step instructions.

- Confirm the favicon in tabs and bookmarks is the yellow NRE icon, not the blue icon.
- Confirm the favicon shows up if you add the SPA to the Favorites list in Safari (Mac and iOS).
- Confirm the favicon shows up if you bookmark the SPA in Android (not sure exactly how this works, tbh).

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No

#### Have automated unit tests been added? If not, why?

No, this affects the favicon only.

#### How should this change be communicated to end users?

n/a

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

No

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-1951

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No

2022-09-06 21:31 UTC, GuiMend requested changes
Code looks good, but icon isn't rendering on my browser. Using Brave browser (based on chrome) using windows 10

![image](https://user-images.githubusercontent.com/9381325/188744238-6897ac78-2353-4882-a028-07f832cb89b8.png)

Btw: accessed https://dev-1951.revengine-review.org/sign-in

2022-09-07 14:21 UTC, nrh-cklimas commented
@GuiMend think this should be working now in the review app. I moved the favicons into a `static` directory--issue, I think, was that Django isn't configured to serve stuff out of the root SPA directory except index.html. I'm not sure if folks who are more Django knowledgable would have a suggestion here. For most of these files, the path shouldn't matter, but I think some (old?) browsers will look for `favicon.ico` at the root level no matter what.

2022-09-07 15:13 UTC, GuiMend approved these changes
Working 👍 

![image](https://user-images.githubusercontent.com/9381325/188914537-dbf31f23-32b0-47e7-8263-b0bbe1d2d8a8.png)

2022-09-08 18:38 UTC, x110dc approved these changes

2022-09-08 18:38 UTC, merged