[WIP] DEV-2183: SPA-side changes
newsrevenuehub/rev-engine pull request #657
Opened 2022-09-08 19:50 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2022-09-09 18:50 UTC, benjaminEwhite commented on spa/public/index.html
> -      {% comment %} the webpack nonce causes client libraries like styled-components to add a nonce and therefore not violate CSP{% endcomment %}
This change fixes a dev tools console error because the comment text above was making its way to browser.

2022-09-09 18:52 UTC, benjaminEwhite commented on spa/src/assets/icons/SvgIcons.js
> +          fillRule="evenodd"
This change was spurred by dev tools printing info about fill-rule not being a legit prop name.

2022-09-09 18:52 UTC, benjaminEwhite commented on spa/src/assets/icons/SvgIcons.js
> +          clipRule="evenodd"
This change was spurred by dev tools printing info about clip-rule not being a legit prop name.

2022-09-12 01:44 UTC, benjaminEwhite commented on revengine/settings/base.py
> +# TODO: [DEV-2359] Fix CSP violation caused by react-select emotion
This is temporarily here, and should be fixed before merging DEV-2103-root-branch into main. 

We're moving to report-only for now so we can get QA of the checkout form -- and in particular, the new select component used for choosing mailing country. When not in report-only mode, the CSP blocks loading styling for the react-select component we use to implement the mailing country selector.

2022-09-12 01:56 UTC, benjaminEwhite commented on spa/src/components/paymentProviders/stripe/StripePaymentForm.test.js
> -});
Payment methods are managed entirely in Stripe dashboard with this set of changes, so front end code is no longer responsible for turning methods on/off

2022-09-12 01:57 UTC, benjaminEwhite commented on spa/src/components/paymentProviders/stripe/stripeFns.js
> +  serializedData['page'] = state.pageId;
Backend changed and expects "page" now, not page_id

2022-09-12 16:46 UTC, GuiMend requested changes

2022-09-12 16:46 UTC, GuiMend commented on spa/src/components/donationPage/pageContent/DDonorAddress.js
> +import Select from 'react-select';
We could use the select from `material-ui` https://v4.mui.com/components/selects/#select

2022-09-12 16:46 UTC, GuiMend commented on spa/src/components/donationPage/pageContent/DDonorAddress.js
> +    option: (provided) => ({ ...provided, ...fontStyles })
If you use the material-ui select, you can use styled components

2022-09-12 16:46 UTC, GuiMend commented on spa/src/components/donationPage/pageContent/DPayment.js
> +  return <DElement>{liveMode ? <StripePaymentWrapper /> : <NotLivePlaceholder />}</DElement>;
Do we need to rename it? 
```suggestion
function DPayment({ live }) {
  return <DElement>{live ? <StripePaymentWrapper /> : <NotLivePlaceholder />}</DElement>;
```

2022-09-12 16:46 UTC, GuiMend commented on spa/src/components/donationPage/pageContent/DPayment.js
> +        onChange={(_e, { checked }) => setUserAgreesToPayFees(checked)}
Usually when I have to name a variable that is useless, I just use `_`. I've seen this pattern somewhere and used it since.
```suggestion
        onChange={(_, { checked }) => setUserAgreesToPayFees(checked)}
```

2022-09-12 16:46 UTC, GuiMend commented on spa/src/components/paymentProviders/stripe/stripeFns.js
> +/**s
Typo ?
```suggestion
/**
```

2022-09-12 16:46 UTC, GuiMend commented on spa/src/components/paymentProviders/stripe/StripePaymentForm.js
> +  }
Shouldn't we also check for current environment? And only allow when ENV === dev or development (not sure which value we are using for dev env)?

2022-09-12 16:46 UTC, GuiMend commented on spa/cypress/integration/01 - donation-page.spec.js
> +    cy.visitDonationPage();
It's a bit confusing to check it in github, but isn't this test also included in the `beforeEach -> visitDonationPage`?

2022-09-12 16:46 UTC, GuiMend commented on spa/cypress/integration/01 - donation-page.spec.js
> +      delete allButCaptcha['captcha_token'];
```suggestion
      const { captcha_token, ...allButCaptcha} = interception.request.body;
```

2022-09-12 16:46 UTC, GuiMend commented on spa/cypress/integration/01 - donation-page.spec.js
> +        body: { provider_client_secret_id: 'pi_3LgkV1pOaLul7_secret_QcpIANR9d6', email_hash: 'b4170aca0fd3e60' },
Don't you have a fake email hash to use here as const?

2022-09-12 16:46 UTC, GuiMend commented on spa/cypress/integration/01 - donation-page.spec.js
> +      delete allButCaptcha['captcha_token'];
Same as above

2022-09-12 17:04 UTC, benjaminEwhite commented on spa/src/components/donationPage/DonationPage.js
> +  const [mailingCountry, setMailingCountry] = useState();
Yeah, I agree. This component could / should be refactored more generally. Some of the useState could be removed if we were using react-hook-form or similar to track form state.

Out of scope for now though.

2022-09-12 20:16 UTC, benjaminEwhite commented on spa/cypress/integration/01 - donation-page.spec.js
> +    cy.visitDonationPage();
You're right. Removing this.

2022-09-12 20:22 UTC, benjaminEwhite commented on spa/cypress/integration/01 - donation-page.spec.js
> +      delete allButCaptcha['captcha_token'];
Did this locally and will push up.

2022-09-12 20:22 UTC, benjaminEwhite commented on spa/cypress/integration/01 - donation-page.spec.js
> +        body: { provider_client_secret_id: 'pi_3LgkV1pOaLul7_secret_QcpIANR9d6', email_hash: 'b4170aca0fd3e60' },
Thanks, that's extremely attentive!

2022-09-12 20:24 UTC, benjaminEwhite commented on spa/cypress/integration/01 - donation-page.spec.js
> +      delete allButCaptcha['captcha_token'];
Changing here as well.

2022-09-12 20:27 UTC, benjaminEwhite commented on spa/src/components/DonationPageRouter.js
> +const PaymentSuccess = lazy(() => componentLoader(() => import('components/donationPage/live/PaymentSuccess')));
Yeah, which seems weird to me. I created a JIRA to do to look into this at some point.

2022-09-12 20:45 UTC, benjaminEwhite commented on spa/src/components/donationPage/DonationPage.js
> +      case 'year':
Good suggestion. I am following this, but doing locally and pushing up change. Updating all references to raw strings to instead use constant values.

2022-09-12 20:51 UTC, benjaminEwhite commented on spa/src/components/donationPage/DonationPage.js
> +    const resolvedAmount = amount === '' ? 0 : amount;
👍 -- doing this locally so can run tests afterwards. Pushing up momentarily.

2022-09-12 20:52 UTC, benjaminEwhite commented on spa/src/components/donationPage/DonationPage.js
> +          console.error(message);
This console.error is just here to trigger Sentry.

In next line, we do `setDisplayErrorFallback(true)` which will cause a generic error message to be displayed to the user.

2022-09-12 20:53 UTC, benjaminEwhite commented on spa/src/components/donationPage/DonationPage.js
> +          console.error('Something unexpected happened', name, message);
See above

2022-09-12 20:53 UTC, benjaminEwhite commented on spa/src/components/donationPage/DonationPage.js
> +  const [paymentSubmitButtonText, setPaymentSubmitButtonText] = useState();
Yeah, tried to do that throughout and got sloppy here. I also like useState to be concentrated.

2022-09-12 20:55 UTC, benjaminEwhite commented on spa/src/components/donationPage/pageContent/DDonorAddress.js
> +import Select from 'react-select';
`react-select` was easiest to implement on short notice, but yes, could have also used Mui.

2022-09-12 20:56 UTC, benjaminEwhite commented on spa/src/components/donationPage/pageContent/DDonorAddress.js
> +    option: (provided) => ({ ...provided, ...fontStyles })
That's true, but for now, I think we should stick with react-select.

2022-09-12 20:57 UTC, benjaminEwhite commented on spa/src/components/donationPage/pageContent/DPayment.js
> +  return <DElement>{liveMode ? <StripePaymentWrapper /> : <NotLivePlaceholder />}</DElement>;
reverting this.

2022-09-12 20:58 UTC, benjaminEwhite commented on spa/src/components/donationPage/pageContent/DPayment.js
> +        onChange={(_e, { checked }) => setUserAgreesToPayFees(checked)}
Yeah, I do that as well. this was mainly existing code, but i'll update.

2022-09-12 20:59 UTC, benjaminEwhite commented on spa/src/components/paymentProviders/stripe/StripePaymentForm.js
> +  }
window.Cypress being present already implies we're in testing environment.

2022-09-12 21:00 UTC, benjaminEwhite commented on spa/src/components/paymentProviders/stripe/stripeFns.js
> +/**s
Removing typo

2022-09-13 14:03 UTC, GuiMend approved these changes
Code LGTM 👍

2022-09-13 14:03 UTC, GuiMend commented on spa/src/components/donationPage/DonationPageDisclaimer.js
> +import { CONTRIBUTION_INTERVALS } from '../../constants';
We can change the folder name so that jest doesn't mix our constants files with other packages with the same name

2022-09-13 15:14 UTC, benjaminEwhite commented on spa/cypress/integration/01 - donation-page.spec.js
> +import { CONTRIBUTION_INTERVALS } from '../../src/constants';
Yeah, the clearbit import was pre-existing, if i'm not mistaken. I tried with absolute import here, but for some reason it wasn't working in jest tests, hence relative.

2022-09-13 15:16 UTC, benjaminEwhite commented on spa/src/components/donationPage/DonationPageDisclaimer.js
> +import { CONTRIBUTION_INTERVALS } from '../../constants';
I don't see a package named `constants` in my local node_modules folder, just `constants-browserify` which I don't think should conflict, or am I not understanding?

2022-09-13 16:41 UTC, nrh-cklimas requested changes
Generally, this looks pretty solid to me-- the only comment I made that I think must get resolved pre-merge is the country select label issue, because it's an accessibility problem. Otherwise, my comments here are possible improvements that you could take or leave depending on time constraints/your own feelings.

2022-09-13 16:56 UTC, benjaminEwhite commented on spa/src/components/analytics/plugins/facebookPixel.js
> +  return document.querySelectorAll(`script[src='${FB_PIXEL_SCRIPT_SRC_URL}']`).length > 0 && window.fbq;
Removing.

2022-09-13 17:09 UTC, benjaminEwhite commented on spa/src/components/donationPage/DonationPage.js
> +function getCookie(name) {
👍 changing to use react-cookie

2022-09-13 17:13 UTC, benjaminEwhite commented on spa/src/components/donationPage/DonationPage.js
> +  // **
Yeah. I think this is from copy-pasta from where this used to live in another file, but will update.

2022-09-13 17:17 UTC, benjaminEwhite commented on spa/src/components/donationPage/DonationPage.js
> +  const getReCAPTCHAToken = () =>
[This is pre-existing code](https://github.com/newsrevenuehub/rev-engine/blob/ff31e875a5c22419578a01677b2f422add549698/spa/src/components/paymentProviders/stripe/StripePaymentForm.js#L164) that was just moved around. I've got a todo ticket noted at line 111 to revisit google captcha integration overall, which I think would be time to rethink implementation. I basically just wanted to get this working as before with as little change as possible.

2022-09-13 17:18 UTC, nrh-cklimas commented on spa/src/components/donationPage/DonationPage.js
> +  const getReCAPTCHAToken = () =>
Sounds good to me.

2022-09-13 17:34 UTC, benjaminEwhite commented on spa/src/components/donationPage/pageContent/DDonorAddress.js
> +    <BaseField errors={errors.mailing_country} label="Country" required={true}>
Using lighthouse a11y reporting in DevTools, I found that `inputId` solved for violation it was reporting. Pushing up commit momentarily.

2022-09-13 17:36 UTC, benjaminEwhite commented on spa/src/components/donationPage/pageContent/DDonorInfo.js
> +            testid="first_name"
It's passed as `data-testid` to the child styled Input inside Input component ([see here](https://github.com/newsrevenuehub/rev-engine/blob/main/spa/src/elements/inputs/Input.js#L17))

2022-09-13 17:37 UTC, benjaminEwhite commented on spa/src/components/donationPage/pageContent/DPayment.js
> +        data-testid={`pay-fees-${userAgreesToPayFees ? 'checked' : 'not-checked'}`}
Yeah, I agree. I don't see the point in having dynamic test ids based on checked state either.

That said, this is existing code, so reluctant to touch it in this PR.

2022-09-13 17:39 UTC, benjaminEwhite commented on spa/src/components/paymentProviders/stripe/StripePaymentWrapper.js
> +  const stripePromise = useRef(loadStripe(HUB_STRIPE_API_PUB_KEY, { stripeAccount }));
I believe the Stripe PaymentElement would be prevented from displaying.

2022-09-13 17:50 UTC, nrh-cklimas commented on spa/src/components/paymentProviders/stripe/StripePaymentWrapper.js
> +  const stripePromise = useRef(loadStripe(HUB_STRIPE_API_PUB_KEY, { stripeAccount }));
Something we might want to revisit later--sounds like a user would see an endless spinner in that case.

2022-09-13 17:51 UTC, nrh-cklimas commented
Looks good to me, thanks for addressing comments.

2022-09-13 17:51 UTC, nrh-cklimas approved these changes

2022-09-13 20:07 UTC, x110dc approved these changes

2022-09-17 01:29 UTC, merged