DEV-2302: Add "publish" button to global header in page editor and fire "publish page" modal
newsrevenuehub/rev-engine pull request #665
Opened 2022-09-13 01:27 UTC by GuiMend

…button-to-global-header-in-page-editor-and-fire-publish-page-modalPlease fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2022-09-14 14:46 UTC, nrh-cklimas requested changes
Overall looks good! Just questions here and there.

2022-09-14 18:15 UTC, GuiMend commented on spa/cypress/integration/02 - donation-page-edit.spec.js
> +      cy.get('body').click(0, 0);
Yes

2022-09-14 18:16 UTC, GuiMend commented on spa/src/components/common/Button/PublishButton/PublishButton.js
> +    patchPage({ published_date: addYears(new Date(), 10) });
That's a good question, will bring it on slack. From what I've seen the current implementation is that we don't have an "unpublish", we can only schedule a publish date in the future. Will double check just to be certain.

2022-09-14 18:23 UTC, GuiMend commented on spa/src/components/common/Button/PublishButton/PublishButton.js
> +const PublishButton = ({ page, setPage, className, alert, requestPatchPage }) => {
That's correct, it will blink for published pages while data loads. I haven't seen a loading state for the header, this is probably a question for Rachel or Mariclare

2022-09-14 21:16 UTC, GuiMend commented on spa/src/components/common/Button/PublishModal/PublishModal.js
> +              {/* TODO: add input error messages */}
TODO in a follow up ticket for improvements

2022-09-14 21:21 UTC, gurjittoptal approved these changes
approving. ( as no longer in this one )

2022-09-15 14:34 UTC, GuiMend commented on spa/src/components/common/Button/PublishButton/PublishButton.js
> +const PublishButton = ({ page, setPage, className, alert, requestPatchPage }) => {
Removed the publish button while page is loading 👍

2022-09-15 14:39 UTC, GuiMend commented on spa/src/components/common/Button/PublishButton/PublishButton.styled.js
> +    width: 123px;
Not sure where you are seeing the widht not being applied, but it's there because when we click "unpublish", a loading state will show and if I don't fix the widht it will shrink (and I want it to stay the same width)
![image](https://user-images.githubusercontent.com/9381325/190432573-ddf4ade0-5b59-4d81-857f-d81145b39c0b.png)
![image](https://user-images.githubusercontent.com/9381325/190432909-aa266ca3-4602-40c8-af15-3e9cbfceec79.png)

2022-09-15 15:10 UTC, GuiMend commented on spa/src/components/common/Button/PublishModal/PublishModal.styled.js
> +  margin: 8px 0 0 0 !important;
I tried messing around but couldn't override the style without important 😞

2022-09-15 15:16 UTC, GuiMend commented on spa/src/components/common/Button/PublishModal/PublishModal.js
> +    <Modal open={open} onClose={onClose} aria-labelledby={`Publish page ${page?.name}`}>
That's right, updated it to `aria-label` + strengthen unit test

2022-09-15 15:55 UTC, GuiMend commented on spa/src/components/common/Button/PublishButton/PublishButton.js
> +            aria-label={`${isPublished ? 'Published' : 'Publish'} page ${page?.name}`}
Done

2022-09-15 15:55 UTC, GuiMend commented
@nrh-cklimas , addressed all your comments on [fb050a5](https://github.com/newsrevenuehub/rev-engine/pull/665/commits/fb050a51e1bf83fc07ec127d7651c00b1950c953)

2022-09-15 16:19 UTC, nrh-cklimas commented on spa/src/components/common/Button/PublishButton/PublishButton.js
> +    patchPage({ published_date: addYears(new Date(), 10) });
I think looking at it, the intent is to remove unpublish functionality for now? If so I think we should hide the button--if I understand the code as it is, it'll display but do nothing.

2022-09-15 16:21 UTC, nrh-cklimas commented on spa/src/components/common/Button/PublishButton/PublishButton.styled.js
> +    width: 123px;
I see. I was looking at the button before you click on it. Something we should follow up on when we start to build out the style guide.

2022-09-15 16:28 UTC, nrh-cklimas commented on spa/src/components/common/Button/PublishModal/PublishModal.js
> +              <Input value={page?.revenue_program?.slug} start="true" onChange={() => {}} />
If it's not editable, can we put a `readonly` prop on the input instead of ignoring input in JS?

I see the same Jest error--weird that only Jest flags this but I guess jsdom is stricter than real life. I think the issue here is we're applying a non-standard prop, `start`, on a vanilla `<input>`. Something we can address when we standardize these lower level components.

2022-09-15 16:31 UTC, nrh-cklimas commented on spa/src/components/common/Button/PublishModal/PublishModal.styled.js
> +  margin: 8px 0 0 0 !important;
Weird. I can show you what I see locally on a screenshare. Margin definitely seems to require !important but padding doesn't for me.

2022-09-15 16:42 UTC, nrh-cklimas commented on spa/src/components/content/pages/AddPageModal.js
>    const [slug, setSlug] = useState('');
I think we can lessen some complexity here now that we know the user will never set the slug manually. Here's what I'm thinking...

- Remove `slug` state since it's always derived from `name`.
- Remove `handleNameBlur`.
- Move the logic of setting the slug to `handleSave`.

I might be missing something here though that would prevent us from doing this, though.

2022-09-15 19:55 UTC, GuiMend commented on spa/src/components/common/Button/PublishButton/PublishButton.js
> +    patchPage({ published_date: addYears(new Date(), 10) });
Removed it 👍

2022-09-15 19:57 UTC, GuiMend commented on spa/src/components/common/Button/PublishModal/PublishModal.js
> +              <Input value={page?.revenue_program?.slug} start="true" onChange={() => {}} />
Added `readOnly`.

yes, that is the problem, non-standard prop.

2022-09-15 19:59 UTC, GuiMend commented on spa/src/components/common/Button/PublishModal/PublishModal.styled.js
> +  margin: 8px 0 0 0 !important;
I couldn't make the element have the same design as Figma by only changing the padding. The defaut `margin: 20px 0;` need to be removed, that's why I added the important

2022-09-15 20:00 UTC, GuiMend commented on spa/src/components/content/pages/AddPageModal.js
>    const [slug, setSlug] = useState('');
Correct, just don't think we need to do that because a follow up ticket will remove the modal altogether

2022-09-16 20:25 UTC, nrh-cklimas commented
Looks good, just needs a merge/rebase from main.

2022-09-16 20:25 UTC, nrh-cklimas approved these changes

2022-09-20 01:17 UTC, x110dc approved these changes

2022-09-20 01:20 UTC, x110dc approved these changes

2022-09-20 17:45 UTC, merged