[WIP] DEV-1106 spa side changes
newsrevenuehub/rev-engine pull request #670
Opened 2022-09-15 05:00 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2022-09-15 14:05 UTC, benjaminEwhite commented on spa/src/components/DashboardRouter.js
> +            <Redirect from={ROUTES.STRIPE_ACCOUNT_LINK_RETURN} to={`${ROUTES.CONTENT_SLUG}?stripeAccountLinkSuccess`} />
FWIW, I initially tried doing this without adding a new route, thinking that it would be enough to send users back to dashboard with a query param. However, for reasons not entirely clear to me, the query param did not make its way all the way to the dashboard by the time it loads, and I saw this redirect pattern being used, tried it, and it solved my problem.

2022-09-15 14:22 UTC, benjaminEwhite commented
Closing and reopening to trigger new review app build. I've torn down review app from local. This is needed because I didn't use a subtask in JIRA to lead to separate ticket numbers for first PR and this one.

2022-09-15 17:23 UTC, benjaminEwhite commented on spa/cypress/integration/02 - donation-page-edit.spec.js
> +describe('Edit interface: Setup', () => {
Changes in this PR caused these tests to break. Fixing them was initially difficult because there were two (nested) `.before` blocks, which can create some gnarly path dependency between tests. Moved these tests out into own describe block to solve.

(Editorial comment: IMO nested before / beforeEach are to be avoided in Cypress because they lead to bugs and compromised tests where test order may impact outcome in unintended ways).

2022-09-15 18:30 UTC, nrh-cklimas requested changes
The only thing I feel strongly about here is moving the Stripe-related logic out of `<Dashboard>` and into a separate hook--rest are possible ideas. I haven't had time to test it out in the review app and might add a comment or two once I do, but I wanted to give you as much time as I could to look these over.

2022-09-15 18:30 UTC, nrh-cklimas commented on spa/src/components/dashboard/Dashboard.js
> +  useEffect(() => {
I'd suggest moving these three effects into a separate hook, which is easier to test and also less scary to read :). It looks like these all depend on the global user state, so the hook could either call `useUser()` directly or take the user object as an argument.

2022-09-15 18:30 UTC, nrh-cklimas commented on spa/src/components/dashboard/Dashboard.js
> +      [...params.keys()].includes('stripeAccountLinkSuccess') &&
```suggestion
      'stripeAccountLinkSuccess' in params &&
```

2022-09-15 18:30 UTC, nrh-cklimas commented on spa/src/hooks/useFeatureFlags.js
> +function useFeatureFlags() {
I'm not sure about this. If it's just a wrapper around `useUser()`, are we better off just refactoring everything feature flags-related to use the user object instead? I don't have much of a handle on how we use feature flags, so this could in fact be a good idea... e.g. if we want to one day set feature flags on both a user and their organization, this could be a useful indirection.

2022-09-15 18:30 UTC, nrh-cklimas commented on spa/src/hooks/useUser.js
> +    onSuccess: (data) => localStorage.setItem(LS_USER, JSON.stringify(data))
I don't know react-query well enough to say, do we need to add error handling here for `fetchUser` failing too?

2022-09-15 18:30 UTC, nrh-cklimas commented on spa/src/components/dashboard/connectStripe/ConnectStripeElements.js
>  import Cookies from 'universal-cookie';
Just noticed this--I know not in scope for this PR. We should someday refactor so we're using one cookie library. Sorry I missed that in the other PR... still getting up to speed, obviously.

2022-09-15 18:30 UTC, nrh-cklimas commented on spa/src/components/dashboard/connectStripe/ConnectStripeToast.js
> +const ConnectStripeToast = ({ revenueProgramId, createStripeAccountLinkMutation }) => {
Is there a way we can avoid prop drilling `createStripeAccountMutation`? e.g. having to have it passed down from Dashboard -> ConnectStripeElements -> ConnectStripeToast (if I have that right). I don't know react-query well enough to have a concrete suggestion, so tell me if I'm off-base here. The pattern I'm used to is that each component interacts with the shared state independently from each other.

2022-09-15 18:33 UTC, nrh-cklimas commented
Forgot to add, I really like the react-query usage here, and it's clear it's going to allow us to simplify things.

2022-09-15 18:48 UTC, nrh-cklimas commented
I walked through the test steps up until you set up Stripe, because I'm not sure how to do that in a test context, and things looked good there.

2022-09-15 19:13 UTC, benjaminEwhite commented on spa/src/components/DashboardRouter.js
> -                <UserContextProvider>
Hopefully you should be able to get what you need from useUser, but let's huddle on this.

2022-09-15 23:26 UTC, njharman requested changes
Reviewing backend/django only.

need to merge main, I believe.

2022-09-15 23:26 UTC, njharman commented on apps/organizations/views.py
> +    return Response(dict(stripe_response), status=status.HTTP_202_ACCEPTED)
Is stripe_response "dict-like"? And that's why make it a real dict? What issue was occurring [this is more education for me than "change request"]

2022-09-15 23:26 UTC, njharman commented on apps/organizations/views.py
> +        else request.build_absolute_uri(reverse("index") + "stripe-account-link-complete")
Why not create named url [in revengine/urls.py similar to verified urls], that can reverse directly?

2022-09-15 23:26 UTC, njharman commented on apps/organizations/views.py
>      except StripeError:
This file is so close to 100% coverage 😮. Can't you feel it? Doesn't it taunt/tempt you? Covering the if/and error branch of code block you edited here would do it!

2022-09-15 23:26 UTC, njharman commented on apps/users/tests/test_serializers.py
> +        self.assertGreaterEqual(len(data["revenue_programs"]), 1)
Please use pytest assert style tests `assert len(data["revenue_programs"]) >= 1`. In this test method, that you touched. No need to update rest of file, at this moment.

2022-09-15 23:26 UTC, njharman commented on apps/organizations/tests/test_org_views.py
> +        mock_get_return_url = mock.MagicMock(return_value=mock_return_url)
I'm not sure I understand need/advantage of mocking get_...link_return_url?  

Difference in URLs between local and "test" [aka CI] environments? Should the test environment not also return the local url?

2022-09-16 13:25 UTC, nrh-cklimas commented on spa/cypress/integration/02 - donation-page-edit.spec.js
> +describe('Edit interface: Setup', () => {
Stray thought: the issue with the nested before/beforeEach may be that we're missing some matching afters to clean up the behaviors so they don't leak into other tests. But a style point.

2022-09-16 14:39 UTC, benjaminEwhite commented on apps/organizations/views.py
> +    return Response(dict(stripe_response), status=status.HTTP_202_ACCEPTED)
Yeah, it's dict like and doesn't serialize unless explicitly cast to a dict.

2022-09-16 15:56 UTC, benjaminEwhite commented on spa/src/components/dashboard/Dashboard.js
> +      [...params.keys()].includes('stripeAccountLinkSuccess') &&
Yeah,  I actually tried `in` here and was surprised by the results. 

Check this out:

```
const foo = new URLSearchParms("?foo=bar");
console.log(foo.keys());
=> Iterator {}
"foo" in foo.keys()
=> false
"foo" in [...foo.keys()];  // to cast iterator to array
=> false

// BUT ¯\_(ツ)_/¯ this works...

[...foo.keys()].includes("foo")

```

2022-09-16 15:59 UTC, benjaminEwhite commented on spa/src/hooks/useFeatureFlags.js
> +function useFeatureFlags() {
I think it's easy to imagine using feature flags at org or rp-level in the future.


I guess the other thing I like about this approach is that it hides the implementation details from calling context. So if I care about feature flags, I don't have to think about user directly, I just think about using a hook that deals with feature flags.

2022-09-16 16:15 UTC, benjaminEwhite commented on spa/src/hooks/useUser.js
> +    onSuccess: (data) => localStorage.setItem(LS_USER, JSON.stringify(data))
With react-query, we get two chances to deal with error state. One is internal to the query/mutation, by providing an `onError` function. The other is by using the `isError` boolean returned by calling by `useQuery`, which would allow calling context to decide what to do in case of error. 

I think in this case, we'd want to deal with error in parent context. That said, at a minimum, I think we'd always want to do a `console.error(err)` so that Sentry knows about the issue.

With that in mind, I'm going to add console.error behavior to onError for `useUser` and `useCreateStripeAccountLink`.  

`useUser` gets called in a number of places, but crucially, it gets called at the top of the tree in src/components/Main.js.  If useUser is still loading (based in `.isLoading` attribute), we don't display the dashboard.  I'm adding new behavior so that if `isError` is true (from useUser), then we'll display an error fallback.

Will take a similar approach to `isError` in other places I'm using these hooks.

2022-09-16 20:06 UTC, nrh-cklimas commented on spa/src/components/dashboard/Dashboard.js
> +      [...params.keys()].includes('stripeAccountLinkSuccess') &&
Ah, my bad. I was thinking of plain old objects. How about `params.has('stripeAccountLinkSuccess')`?

https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/has

2022-09-16 20:06 UTC, nrh-cklimas commented on spa/src/hooks/useFeatureFlags.js
> +function useFeatureFlags() {
Sounds good for now.

2022-09-16 20:06 UTC, nrh-cklimas commented on spa/src/hooks/useUser.js
> +    onSuccess: (data) => localStorage.setItem(LS_USER, JSON.stringify(data))
Think we talked through this one on Slack today.

2022-09-19 14:11 UTC, benjaminEwhite commented on spa/src/components/dashboard/Dashboard.js
> +      [...params.keys()].includes('stripeAccountLinkSuccess') &&
👍 - updated. see 3562573f2d28

2022-09-19 14:25 UTC, benjaminEwhite commented on apps/users/tests/test_serializers.py
> +        self.assertGreaterEqual(len(data["revenue_programs"]), 1)
Updated. See 1657c2cfc96

2022-09-19 14:29 UTC, benjaminEwhite commented on apps/organizations/tests/test_org_views.py
> +        mock_get_return_url = mock.MagicMock(return_value=mock_return_url)
For the test environment, it's a non-issue. We only need this to return :3000 for local so that the full flow for stripe account connection can be tested locally without having to manually change :8000 to :3000.

2022-09-19 15:01 UTC, nrh-cklimas approved these changes

2022-09-19 15:50 UTC, benjaminEwhite commented on apps/organizations/views.py
> +        else request.build_absolute_uri(reverse("index") + "stripe-account-link-complete")
Done. See 13e2286fdb

2022-09-19 15:51 UTC, benjaminEwhite commented on apps/organizations/views.py
> +    return (
Now spans one line. See 13e2286fdb

2022-09-19 15:51 UTC, benjaminEwhite commented on apps/organizations/views.py
> +def get_stripe_account_link_return_url(request):
See https://github.com/newsrevenuehub/rev-engine/pull/670/files#diff-04fbcde936dbafc7cad39fed75b333113887a1ae8009c4c0e7c729f86f9d4ea1R439-R452

2022-09-19 15:53 UTC, benjaminEwhite commented on apps/organizations/views.py
> +def get_stripe_account_link_return_url(request):
To be clear: I removed the mocking of this function in the test you saw, and then created unit tests for this function.

2022-09-19 16:08 UTC, benjaminEwhite commented on apps/organizations/views.py
>      except StripeError:
Done. See 53a300d7740

2022-09-19 16:17 UTC, benjaminEwhite commented on apps/organizations/views.py
>      except StripeError:
Was able to get to 98%, but didn't add tests for FilterQuerySetByUserMixin.filter_queryset_for_user which would be necessary to get to 100%.

2022-09-19 16:17 UTC, benjaminEwhite commented on apps/organizations/views.py
>      except StripeError:
See 283f690cf8deadc0201cee38259ed243c71d2500

2022-09-19 17:55 UTC, njharman approved these changes

2022-09-19 17:58 UTC, njharman approved these changes
lgtm The somewhat rude and not helpful "Codacy Static Code Analysis" check failed with 

>This pull request quality could be better.

2022-09-19 18:37 UTC, benjaminEwhite commented
@njharman fwiw, I'm pushing a couple of small changes up to solve for some of the complaints of Codacy, but some of its warnings are false positives (for instance, [this one](https://app.codacy.com/gh/newsrevenuehub/rev-engine/file/76231301985/issues/source?bid=31147861&fileBranchId=31147904#l49)).  See 4e386b40 .

2022-09-20 19:48 UTC, x110dc requested changes
Just a couple minor change requests to using environment variable. Ping me if you'd like to discuss.

2022-09-20 19:48 UTC, x110dc commented on .envrc.example
> +export ENVIRONMENT=local
I'd prefer that this not be "hard-coded" -- it should instead be a dev's name so something like "export ENVIRONMENT=<dev's first name here>" -- otherwise won't be able to tell where errors are coming from in Sentry if a dev enables Sentry.

2022-09-20 19:48 UTC, x110dc commented on apps/organizations/views.py
> +        f"http://localhost:3000{reversed}" if settings.ENVIRONMENT == "local" else request.build_absolute_uri(reversed)
Now I know why you set the `ENVIRONMENT` specifically in `.envrc.sample`. Per 12-factor I prefer not to see code that relies on "environments". Instead I'd prefer a pattern of creating a new variable for this very purpose if this has to be different locally. (With a default that does the right thing in production if undefined). See https://news-revenue-hub.atlassian.net/wiki/spaces/TECH/pages/2047311873/Python+Style+Guide#Environment-variables

2022-09-20 22:44 UTC, benjaminEwhite commented on .envrc.example
> +export ENVIRONMENT=local
38b192eb2

2022-09-20 23:52 UTC, benjaminEwhite commented on apps/organizations/views.py
> +        f"http://localhost:3000{reversed}" if settings.ENVIRONMENT == "local" else request.build_absolute_uri(reversed)
SInce the value in non-local case needs to be `request.build_absolute_url(reversed)`, whose value can only be known at run time, what pattern would you suggest? Would it be something like `STRIPE_ACCOUNT_LINK_RETURN_BASE_URL` in `base.py` (defaulting to None if not set) and check here in `get_stripe_account_link_return_url` if that var is set, and if so return a URL using that var, otherwise use `request.build_absolute_url`?

2022-09-21 03:50 UTC, x110dc commented on apps/organizations/views.py
> +        f"http://localhost:3000{reversed}" if settings.ENVIRONMENT == "local" else request.build_absolute_uri(reversed)
Yes, that's exactly what I'm saying. Thanks for stating it better!

2022-09-21 13:34 UTC, benjaminEwhite commented on apps/organizations/views.py
> +        f"http://localhost:3000{reversed}" if settings.ENVIRONMENT == "local" else request.build_absolute_uri(reversed)
See 9f36a39a5

2022-09-21 20:42 UTC, x110dc requested changes
One small change request.

2022-09-21 20:42 UTC, x110dc commented on revengine/settings/base.py
> +STRIPE_ACCOUNT_LINK_RETURN_BASE_URL = os.getenv("STRIPE_ACCOUNT_LINK_RETURN_BASE_URL", None)
This should be added to `.envrc.sample`, no?

2022-09-22 01:25 UTC, benjaminEwhite commented on revengine/settings/base.py
> +STRIPE_ACCOUNT_LINK_RETURN_BASE_URL = os.getenv("STRIPE_ACCOUNT_LINK_RETURN_BASE_URL", None)
4272eeb99

2022-09-22 02:04 UTC, x110dc approved these changes

2022-09-23 20:53 UTC, merged