DEV-2028: Add profile finalization modal
newsrevenuehub/rev-engine pull request #671
Opened 2022-09-15 17:19 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

This is a draft based on Gurjit's work. Right now, I am filling in tests and correcting small issues where I find them.

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2022-09-19 13:36 UTC, GuiMend reviewed
Overall code looks good. 

I'm not being able to test create user:
![image](https://user-images.githubusercontent.com/9381325/191029972-155b042c-3769-4e9c-a828-7c9bc3c12e3f.png)

2022-09-19 13:36 UTC, GuiMend commented on spa/src/components/account/Profile/Profile.js
> +      }
dispatch success inside if?

2022-09-19 13:36 UTC, GuiMend commented on spa/src/components/account/Profile/Profile.js
> +    Array.isArray(profileState?.errors) && profileState?.errors.length === 0 ? null : 'An Error Occurred';
Probably could change it to just:
```suggestion
    !profileState?.errors?.length && 'An Error Occurred';
```

2022-09-19 13:36 UTC, GuiMend commented on spa/src/components/account/Profile/Profile.styled.js
> +export const Select = styled.select`
Why not use material select?

2022-09-19 13:36 UTC, GuiMend commented on spa/src/components/account/Profile/Profile.test.js
> +          url: `users/mock-user-id/${CUSTOMIZE_ACCOUNT_ENDPOINT}`
Question: how are we setting the fields to be `'mock-first-name', 'mock-user-id', 'mock-job-title'` so that we can test the expected return here if ProfileForm is mocked `jest.mock('./ProfileForm');`?

2022-09-19 13:36 UTC, GuiMend commented on spa/src/components/account/Profile/ProfileForm.js
> +
This is unnecessary, the `disabled` prop in the submit button already prevents submit from being called

2022-09-19 13:36 UTC, GuiMend commented on spa/src/components/account/Profile/ProfileForm.js
> +    <form onSubmit={handleSubmit(onSubmit)} data-testid="finalize-profile-form">
```suggestion
    <form onSubmit={handleSubmit(onProfileSubmit)} data-testid="finalize-profile-form">
```

2022-09-19 13:36 UTC, GuiMend commented on spa/src/components/account/Profile/ProfileForm.js
> +        <P.Column>
Could have done this without custom styled components using material ui `<Grid container> <Grid item xs={6}> ...`

2022-09-19 13:36 UTC, GuiMend commented on spa/src/components/account/Profile/ProfileForm.js
> +  disabled: PropTypes.bool
This is a bit confusing, do we want the disabled prop or not?

2022-09-19 13:36 UTC, GuiMend commented on spa/src/components/account/Profile/ProfileForm.test.js
> +    ['Last Name', 'mock-first-name'],
```suggestion
    ['Last Name', 'mock-last-name'],
```

2022-09-19 13:36 UTC, GuiMend commented on spa/src/components/account/Profile/__mocks__/ProfileForm.js
> +const mockFormData = {
Where is this file being used? I couldn't identify

2022-09-19 13:36 UTC, GuiMend commented on spa/src/components/account/Profile/Profile.test.js
> +jest.mock('./ProfileForm');
Does jest know that when we call `jest.mock('./ProfileForm')` to get the file `__mocks__/ProfileForm.js` ?

2022-09-19 13:36 UTC, GuiMend commented on spa/src/components/content/pages/AddPageModal.js
> +  const fetchTemplates = useRequest();
Is this needed?

2022-09-19 16:24 UTC, nrh-cklimas commented
> I'm not being able to test create user:

@GuiMend strange--it worked for me just now. Maybe let's do a screenshare on Slack to figure out what happened?

2022-09-19 16:27 UTC, nrh-cklimas commented on spa/src/components/account/Profile/Profile.js
> +      }
Seems like it can't hurt, though I don't think users will ever see the UI update since they're being redirected. Updated in 8d7ba9ce85840cd44b77fe5b9353a026899bb764

2022-09-19 16:28 UTC, nrh-cklimas commented on spa/src/components/account/Profile/Profile.js
> +    Array.isArray(profileState?.errors) && profileState?.errors.length === 0 ? null : 'An Error Occurred';
I think
```
profileState?.errors?.length && 'An Error Occurred';
```

(e.g. no `!` in front?)

2022-09-19 16:39 UTC, nrh-cklimas commented on spa/src/components/account/Profile/Profile.test.js
> +          url: `users/mock-user-id/${CUSTOMIZE_ACCOUNT_ENDPOINT}`
This is happening inside the ProfileForm mock (__mocks__/ProfileForm.js). Idea here is to treat the form as a black box that calls `onProfileSubmit` with canned data, to isolate unit tests on this component from the form implementation.

2022-09-19 16:43 UTC, nrh-cklimas commented on spa/src/components/account/Profile/Profile.test.js
> +jest.mock('./ProfileForm');
Yes -- see https://jestjs.io/docs/manual-mocks

2022-09-19 17:42 UTC, nrh-cklimas commented on spa/src/components/account/Profile/ProfileForm.js
> +
Fair point--was being overly defensive in my coding. Updated in f1421693322e32115dcbf971ac051b8195bc1e70--it's not exactly what you suggested because ProfileForm needs to send up field data and not the native submit event... I think.

2022-09-19 17:42 UTC, nrh-cklimas commented on spa/src/components/account/Profile/ProfileForm.js
> +    <form onSubmit={handleSubmit(onSubmit)} data-testid="finalize-profile-form">
See f1421693322e32115dcbf971ac051b8195bc1e70

2022-09-19 17:43 UTC, nrh-cklimas commented on spa/src/components/account/Profile/ProfileForm.js
> +  disabled: PropTypes.bool
I think the reason for this prop is so that when Profile is talking to the API, the user can't submit again.

2022-09-19 17:50 UTC, nrh-cklimas commented on spa/src/components/content/pages/AddPageModal.js
> +  const fetchTemplates = useRequest();
Removed in bdf0459279ab992dc1d23f3d6e77909cdb1dad79

2022-09-19 17:53 UTC, nrh-cklimas commented on spa/src/components/account/Profile/Profile.styled.js
> +export const Select = styled.select`
Want to do this in DEV-2387, this is a temp fix at best.

2022-09-19 18:36 UTC, GuiMend approved these changes
Looks good 👍 

Can't test it still though. Not sure why I'm getting this issue while creating an account. It worked in another test branch 🤔

As it's working with you, it might be something happenning here, so I'll approve it and we can probably check it further in QA

2022-09-19 18:36 UTC, GuiMend commented on spa/src/components/account/Profile/Profile.js
> +    Array.isArray(profileState?.errors) && profileState?.errors.length === 0 ? null : 'An Error Occurred';
Yes 👍

2022-09-19 18:36 UTC, GuiMend commented on spa/src/components/account/Profile/Profile.test.js
> +jest.mock('./ProfileForm');
Awesome :)

2022-09-20 19:08 UTC, benjaminEwhite commented on apps/users/views.py
> +        organization = Organization.objects.create(name=organization_name, slug=slugify(organization_name))
Probably want to have this wrapped in a try/catch in case of violating uniqueness constraint on slug. Same is true for RevenueProgram below, which also has uniqueness constraint on slug.

2022-09-20 19:23 UTC, benjaminEwhite commented on spa/src/components/account/Profile/Profile.js
> +      onClose={handleClose}
Noticed that you can close modal by clicking backdrop (maybe there's a separate ticket tracking this, not sure, didn't dig). Assuming that's not by design, that can be fixed by just removing `onClose` here altogether, if i'm not mistaken.

2022-09-20 19:29 UTC, nrh-cklimas commented
(resolving Gui's comments since he approved)

2022-09-20 19:30 UTC, nrh-cklimas commented on spa/src/components/account/Profile/Profile.js
> +      onClose={handleClose}
Yeah, want to address in DEV-2388--I want to clean up some modal-related things in here while I'm there if time permits.

2022-09-20 19:33 UTC, nrh-cklimas commented on spa/src/components/account/Profile/Profile.js
> +    Array.isArray(profileState?.errors) && profileState?.errors.length === 0 ? null : 'An Error Occurred';
Forgot to actually address this, did so in e823757195c65f58aa97f8e828490f29615d8652

2022-09-20 19:47 UTC, nrh-cklimas commented on apps/users/views.py
> +        organization = Organization.objects.create(name=organization_name, slug=slugify(organization_name))
If you can point me to an example I could crib from, I could give it a shot... last time I touched Python in any kind of serious way was around a decade ago, but I can probably follow an example. Otherwise yeah, I think I should create a followup story. I did some looking around the backend code myself and couldn't find something comparable, but I think that says more about me than the code.

2022-09-20 22:36 UTC, benjaminEwhite commented on apps/users/views.py
> +        organization = Organization.objects.create(name=organization_name, slug=slugify(organization_name))
I made [this PR](https://github.com/newsrevenuehub/rev-engine/pull/688) into DEV-2028-add-profile-finalization and am asking @njharman for a review. That need not block merging this -- if this gets merged before, we can change base for the linked PR to be main.

2022-09-20 22:38 UTC, benjaminEwhite commented
Looks like there are merge conflicts, but otherwise I'm 👍.

No opinion about whether https://github.com/newsrevenuehub/rev-engine/pull/688 should be done before or after this is merged. Equal level of effort with either strategy, if i'm not mistaken.

2022-09-20 22:38 UTC, benjaminEwhite approved these changes
Approved but see comment and decide on next steps: https://github.com/newsrevenuehub/rev-engine/pull/671/files#r975868342

2022-09-21 12:49 UTC, nrh-cklimas commented on apps/users/views.py
> +        organization = Organization.objects.create(name=organization_name, slug=slugify(organization_name))
Thank you!

2022-09-21 19:03 UTC, benjaminEwhite requested changes
@nrh-cklimas changes make sense. suggest [doing the change represented here](https://github.com/newsrevenuehub/rev-engine/compare/DEV-2028-add-profile-finalization...DEV-2028-add-profile-finalization-followup-suggestion). Didn't want the overhead of an actual PR for this, so just showing you the diff.

2022-09-21 19:33 UTC, nrh-cklimas commented
> @nrh-cklimas changes make sense. suggest [doing the change represented here](https://github.com/newsrevenuehub/rev-engine/compare/DEV-2028-add-profile-finalization...DEV-2028-add-profile-finalization-followup-suggestion). Didn't want the overhead of an actual PR for this, so just showing you the diff.

Did this in ffd347d36b8f7f728dac433a1f7311673f709552

2022-09-21 19:46 UTC, benjaminEwhite approved these changes

2022-09-22 13:34 UTC, nrh-cklimas commented
@GuiMend This is the new commit to review: 0466fbbcca6e8ba64e1a88713b019c669a8fbfb5

2022-09-22 13:40 UTC, GuiMend approved these changes
LGTM 👍

2022-09-22 22:16 UTC, x110dc requested changes
One small change request in the Python code.

2022-09-22 22:16 UTC, x110dc commented on apps/users/tests/test_views.py
> +        self.assertEqual(self.customize_account_request["last_name"], user.last_name)
No reason you should know, but we should be using pytest-style asserts for any new/modified tests. E.g.:

```suggestion
        assert self.customize_account_request["last_name"] == user.last_name
```

2022-09-23 12:59 UTC, nrh-cklimas commented on apps/users/tests/test_views.py
> +        self.assertEqual(self.customize_account_request["last_name"], user.last_name)
👍 Updated in 89350c52660c790fd8314009183b486e4bd65990

2022-09-23 21:04 UTC, x110dc approved these changes

2022-09-28 13:06 UTC, benjaminEwhite commented on apps/users/views.py
> +        organization = Organization.objects.create(name=organization_name, slug=slugify(organization_name))
This is being tracked separately in https://news-revenue-hub.atlassian.net/browse/DEV-2517

2022-09-28 15:27 UTC, merged