DEV-2341 User accepted_terms_of_service is read only
newsrevenuehub/rev-engine pull request #672
Opened 2022-09-15 20:29 UTC by njharman

#### What's this PR do?
Prevent User.accepted_terms_of_service date from being changed via API. Achieved through making field read_only in the Serializer.  It is not made read-only at DB layer. This is normal/standard otherwise it becomes difficult to manage your data through admin/other means. 

It seems that something in Serializer is ignoring META.read_only_fields for fields modified in get_fields(). Would maybe change to use Serializer(partial_updates=True), except fields we are making not required in get_fields() include "password" which is tricky special case.

Add test that past, future and same date for accepted_terms_of_service returns 200 and makes no changes.

Added comment to hopefully prevent future dev from frustration of debugging this behavior.

#### Why are we doing this? How does it help us?
Legal protection. Business needs.

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2022-09-19 14:20 UTC, benjaminEwhite requested changes
Code looks fine, but think the the code comment in the serializer could be a bit more verbose so it's crystal clear why we're setting read_only based on method.

2022-09-19 14:20 UTC, benjaminEwhite commented on apps/users/serializers.py
> +            ].read_only = True  # Read only does not work when set in META.read_only_fields.
Think this comment could be slightly more verbose. It "doesn't work" because we can't set `accepted_terms_of_service` to be a read only field in general, because for `post` we need it to be writable.  The comment as is makes it seem like there's something strange going on with the serializer, whereas it seems that this complexity just stems from our business requirements.

2022-09-19 18:51 UTC, njharman commented on apps/users/serializers.py
> +            ].read_only = True  # Read only does not work when set in META.read_only_fields.
The POST got me thinking... I added test to ensure accepted...service is writeable in POST and rewrote comments to match our intended logic.  R/W Post, R/O Patch. Also added comment to view, that if we ever add PUT need to address the custom logic in serializer.get_fields [forgetting that is the sort of thing that bites future Norm in the ...]  

https://github.com/newsrevenuehub/rev-engine/pull/672/commits/fd61caae399c7e662a1020f0f07a44a0c84986db

2022-09-19 18:58 UTC, benjaminEwhite approved these changes

2022-09-20 01:26 UTC, x110dc approved these changes

2022-09-20 01:27 UTC, x110dc approved these changes

2022-09-20 01:28 UTC, merged