DEV-2130: add stripe account id to public rp list view
newsrevenuehub/rev-engine pull request #675
Opened 2022-09-17 09:11 UTC by leo-dcfa

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

- Add stripe account id to public list response of `GET /revenue-programs`

#### Why are we doing this? How does it help us?

Missing feature on public endpoint

#### How should this be manually tested? Please include detailed step-by-step instructions.

While running rev-engine locally, authenticate with the api with a valid user:

```shell
 curl -c cookiejar -v -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"email":"foo@bar.com", "password": "foobar"}' http://localhost:8000/api/v1/token/
```

Call api

```
curl -b cookiejar -v -H "Content-Type: application/json" -H "Accept: application/json" -X GET "http://localhost:8000/api/v1/public/revenue-programs/" \ |jq .
```

Assert that stripe account id and slug are included in the api response

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

I'm not sure - what's the criteria to do it?

#### Have automated unit tests been added? If not, why?

Yes

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

N/A

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-2130]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

N/A

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

N/A

2022-09-23 21:07 UTC, x110dc requested changes

2022-09-23 21:07 UTC, x110dc commented on apps/public/tests/test_views.py
> +        self.assertEqual(response.status_code, 200)
Can you make these assertions pytest-style? Thanks.

2022-09-23 23:32 UTC, leo-dcfa commented on apps/public/tests/test_views.py
> +        self.assertEqual(response.status_code, 200)
No problem, I noticed most of existing code using self.assert and went with it. Assuming then we should prioritise pytest style for all rev engine code?

2022-09-26 16:21 UTC, x110dc approved these changes

2022-09-26 16:22 UTC, x110dc commented on apps/public/tests/test_views.py
> +        self.assertEqual(response.status_code, 200)
Yes, that's in our style guide: https://news-revenue-hub.atlassian.net/wiki/spaces/TECH/pages/2047311873/Python+Style+Guide

2022-09-26 16:24 UTC, merged