[NRH-158] Hub slack integration
newsrevenuehub/rev-engine pull request #68
Opened 2021-07-02 21:53 UTC by michael-caktus

Adds a new app, `slack`, to manage the integration.
So we've got a nice, agnostic set of models and classes to handle Slack integration.
- `SlackIntegration` is an abstract model
- `HubSlackIntegration` is a singleton model, subclassing from `SlackIntegration`, for managing Hub tokens and values
- `OrganizationSlackIntegration` subclasses `SlackIntegration` and it tracks Organization Slack integrations

As a matter of fact, this PR enables Organization slack integrations, with a few caveats:
- Hub must manually enter the organization's Slack Bot Token and target slack channel in to a new `OrganizationSlackIntegration` instance and attached it to the org.
- Acquiring this Bot Token will likely be a bit too technical for orgs, so will likely require help from Hub

2021-07-06 14:45 UTC, JeremyGibson commented on apps/contributions/admin.py
> -        "updated",
Is this relevant to this PR?

2021-07-06 14:56 UTC, JeremyGibson commented on apps/slack/models.py
> +        default="donations-",
Any reason the default shouldn't start with "#"

2021-07-06 15:30 UTC, JeremyGibson commented on apps/slack/models.py
> +    channel = models.CharField(max_length=255, help_text="All donation notifications will be sent to this channel")
Why not add a default here as well?

2021-07-06 15:52 UTC, JeremyGibson requested changes
Just a few questions.

2021-07-06 20:17 UTC, michael-caktus commented on apps/contributions/admin.py
> -        "updated",
Not directly-- contribution admin was crashing because "updated" doesn't exist.

2021-07-06 20:20 UTC, michael-caktus commented on apps/slack/models.py
> +    if val and val[0] != "#":
I'm operating under the understanding that if it gets to save, it's already passed serializer validation, which is where we should decide whether or not to permit empty strings.

2021-07-07 15:29 UTC, JeremyGibson approved these changes

2021-07-07 15:31 UTC, merged