DEV-2298: Only fire "New page" modal when user has access to multiple revenue programs
newsrevenuehub/rev-engine pull request #681
Opened 2022-09-20 14:04 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
N/A

#### What's this PR do?
When a user creates a new page we show a modal for them to add a page name and select Revenue program. If a user only has 1 revenue program, this PR now bypasses the modal and gives the page name the format "Page [number]", which number is the amount of pages already existent + 1.

#### Why are we doing this? How does it help us?
Reduces the friction for a user to create a page and have to come up with a name for it, not knowing what that is for at this point.

#### How should this be manually tested? Please include detailed step-by-step instructions.
- Login with a user that has only 1 revenue program
- Go to `/pages` and create a new page. 
- Should go directly to the new page edit mode and the page name should be in the format "Page #number" or show an alert error if something went wrong (you can test this by removing network access just before clicking "new page" button)
- Login with user with multiple revenue programs
- "New page" button should open the existing modal and work as expected.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
No

#### Have automated unit tests been added? If not, why?
No, the current modal is only temporary. There is a follow up ticket to update the create page modal and I believe it would be best not to use time creating tests for this modal if it's going to be removed really soon. (Follow up ticket: https://news-revenue-hub.atlassian.net/browse/DEV-2299)

#### How should this change be communicated to end users?
Create Donation Page is now simplified

#### Are there any smells or added technical debt to note?
Yes, the current AddPageModal implementation could be better. This will be addressed in the follow up ticket: https://news-revenue-hub.atlassian.net/browse/DEV-2299 when the modal is updated

#### Has this been documented? If so, where?
No

#### What are the relevant tickets? Add a link to any relevant ones.
[DEV-2298](https://news-revenue-hub.atlassian.net/browse/DEV-2298) Only fire "New page" modal when user has access to multiple revenue programs

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
Follow up ticket: https://news-revenue-hub.atlassian.net/browse/DEV-2299

2022-09-20 20:40 UTC, nrh-cklimas requested changes
One tweak here related to error handling.

2022-09-20 20:40 UTC, nrh-cklimas commented on spa/src/components/content/pages/AddPageModal.js
> +  useEffect(() => {
Something to consider is putting this logic in `<Pages>` instead, e.g. never fire the modal in the first place--it feels a little more elegant to never render the modal in the first place instead of having to force it to render null for a render cycle. But your call here.

If we do keep it here, we should catch any errors during handleSave() and show them as an alert--the existing error handling tries to display an error in a nonexistent dialog.

2022-09-21 16:53 UTC, GuiMend commented on spa/src/components/content/pages/AddPageModal.js
> +  useEffect(() => {
When working on the follow up ticket I'll rewrite this modal and do as you sugested. But for now I believe it's good enough. The error handling will show an alert for the user because the `if` should never be true in the way we are handling this part.

2022-09-21 18:16 UTC, nrh-cklimas approved these changes

2022-09-23 02:06 UTC, x110dc approved these changes

2022-09-23 02:07 UTC, merged