DEV-2178: Refactor Org Plans
newsrevenuehub/rev-engine pull request #683
Opened 2022-09-20 18:23 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

This PR refactors our approach to organization plans, retiring the `Feature` and `Plan` models, adding a `.plan_name` field to `Organization` that points to one two pre-defined `Plan` dataclasses: `free_plan`, and `plus_plan`. These plans correspond to the Free and Plus plans as described [here](https://fundjournalism.org/news-revenue-engine/). Note that in short term, we only need to support those two options even though the marketing materials refer to another plan called "Core".

As specified [in the ticket](https://news-revenue-hub.atlassian.net/jira/software/c/projects/DEV/boards/3?modal=detail&selectedIssue=DEV-2178), this ticket is meant to only encompass the data model changes, and plan-based restrictions are to be handled in follow up tickets. 

One exception to this is that I did go ahead and reimplement plan-based page limits. As you'll see, this involved moving this validation _off_ of the model layer and _onto_ the serializer layer, which is where it should be enforced. I created a [follow up ticket](https://news-revenue-hub.atlassian.net/browse/DEV-2434) to add a confirmation dialog to the Django admin when page creation would lead to an Org having more pages than allowed by its plan. For now, this won't be enforced though.  In contrast, the SPA will be prevented from triggering new page creation if an org is at its limit with the current changes.

Specifics:

- Removes all existing tests and references to `Plan` and `Feature` models
- Adds a single migration (apps/organizations/migrations/0008_DEV-2178_refactor_plan_modeling_and_migrate_legacy_clients.py) that adds `Organization.page_name` (defaulting to the free plan's name), migrates legacy clients to PLUS plan, and deletes the `Plan` and `Feature` models and their references.
- Adds a `Plan` dataclass that is for modeling org plans, but without the database layer being involved. There are two instances of `Plan`: `free_plan` and `plus_plan`.

 
#### Why are we doing this? How does it help us?

This is a requirement for self-onboarding.

#### How should this be manually tested? Please include detailed step-by-step instructions.

Will be easier to manually test in subsequent tickets that  restrict access to SPA-side functionality based on org plan. 

In short term, you can verify that the page limit functionality works by...

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No

#### Have automated unit tests been added? If not, why?

Yes

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-2178](https://news-revenue-hub.atlassian.net/jira/software/c/projects/DEV/boards/3?modal=detail&selectedIssue=DEV-2178)

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

In addition to other tickets already created for the parent epic, I created [DEV-2434](https://news-revenue-hub.atlassian.net/browse/DEV-2434) for next steps around adding confirmation view to Django admin when creating plan-limited entities.

2022-09-20 21:01 UTC, njharman requested changes
Good test coverage.

2022-09-20 23:59 UTC, benjaminEwhite commented on apps/organizations/migrations/0008_DEV-2178_refactor_plan_modeling_and_migrate_legacy_clients.py
> +    # orgs = RevenueProgram.objects.filter(slug__in=rp_slugs_for_legacy_clients).values_list("organization").distinct()
Missed that. Yes, stale.

3d51e6451

2022-09-21 00:08 UTC, benjaminEwhite commented on apps/organizations/models.py
> +FAKE_INFINITY = 200
a38b51646e

2022-09-21 00:13 UTC, benjaminEwhite commented on apps/organizations/models.py
> +CURRENCY_CHOICES = [(k, k) for k, _ in settings.CURRENCIES.items()]
06b2b8a1

2022-09-21 00:59 UTC, benjaminEwhite commented on apps/organizations/models.py
> +    PLUS = plus_plan.name, _(plus_plan.label)
f67d147a8

2022-09-21 00:59 UTC, benjaminEwhite commented on apps/organizations/models.py
> +plus_plan = Plan(
f67d147a8

2022-09-21 01:12 UTC, benjaminEwhite commented on apps/organizations/models.py
>  logger = logging.getLogger(f"{settings.DEFAULT_LOGGER}.{__name__}")
04a6a1106

2022-09-21 01:14 UTC, benjaminEwhite commented on apps/organizations/migrations/0008_DEV-2178_refactor_plan_modeling_and_migrate_legacy_clients.py
> +# from https://news-revenue-hub.atlassian.net/wiki/spaces/TECH/pages/2214625287/Existing+Client+Donation+Page+URLs
f893007a8

2022-09-21 01:32 UTC, benjaminEwhite commented on apps/organizations/models.py
> +        return ({Plans.FREE.value: free_plan, Plans.PLUS.value: plus_plan}).get(name, None)
f70fa261c2af

2022-09-21 01:33 UTC, benjaminEwhite commented on apps/organizations/models.py
> +        return ({Plans.FREE.value: free_plan, Plans.PLUS.value: plus_plan}).get(name, None)
Resolved in one of several cleanup commits. Didn't catch the has and don't want to dig. As you can see, it's outdated.

2022-09-21 01:33 UTC, benjaminEwhite commented on apps/organizations/models.py
> +        return ({Plans.FREE.value: free_plan, Plans.PLUS.value: plus_plan}).get(name, None)
f70fa261c2af

2022-09-21 02:44 UTC, njharman approved these changes

2022-09-21 21:21 UTC, x110dc requested changes
Requested a couple changes. Ping me and we can discuss the ad-hoc migration script.

2022-09-21 21:21 UTC, x110dc commented on apps/organizations/migrations/0008_DEV-2178_refactor_plan_modeling_and_migrate_legacy_clients.py
> +rp_slugs_for_legacy_clients = [
I don't like hardcoding this in the migration file. We can handle this as a one-off ad-hoc script.

2022-09-21 21:21 UTC, x110dc commented on apps/organizations/models.py
> +    custom_thank_you_pages_enabled: bool = False
Not sure of the pros/cons here, but is there value in only adding attributes here after we have a reason to implement them? E.g. should we wait to add `custom_fonts_enabled` here when we implement that limit?

2022-09-22 00:06 UTC, benjaminEwhite commented on apps/organizations/models.py
> +    custom_thank_you_pages_enabled: bool = False
Yeah, I agree, and was on fence. First pass at this was based on looking at the pricing page. I only subsequently looked at tickets for dealing with individual portions. 

I think I'll pare down to just what's essential for this PR.

2022-09-22 00:55 UTC, benjaminEwhite commented on apps/organizations/migrations/0008_DEV-2178_refactor_plan_modeling_and_migrate_legacy_clients.py
> +rp_slugs_for_legacy_clients = [
Okay. I'm breaking this current single PR into two separate ones, with the intention that we'll run the ad hoc script after merging first and before merging second. Shared a link to a Gist that has script in JIRA ticket.

2022-09-22 01:18 UTC, benjaminEwhite commented on apps/organizations/migrations/0008_DEV-2178_refactor_plan_modeling_and_migrate_legacy_clients.py
> +rp_slugs_for_legacy_clients = [
In  ab198d2cef,  removed hard coded data migration and saved as a Gist, which I linked to [in the JIRA issue](https://news-revenue-hub.atlassian.net/browse/DEV-2178).

2022-09-22 01:20 UTC, benjaminEwhite commented on apps/organizations/models.py
> +    custom_thank_you_pages_enabled: bool = False
908bf98e

2022-09-22 02:07 UTC, x110dc approved these changes

2022-09-22 23:00 UTC, merged