DEV-2435 | fix bug around next url for default donation page
newsrevenuehub/rev-engine pull request #686
Opened 2022-09-20 21:27 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

Merge this into DEV-2183-root-branch, then deploy that to test. Once passes UAT, PR DEV-2183-root-branch into main.

#### What's this PR do?

This solves a bug identified in [DEV-2435](https://news-revenue-hub.atlassian.net/browse/DEV-2435).

The root cause of the bug had to do with how a convenience function called `getPaymentSuccessUrl` was dealing with being passed the value `'\'` for its `pathname` parameter. That parameter ultimately determines redirection behavior of the PaymentSuccess component ([see here](https://github.com/newsrevenuehub/rev-engine/blob/DEV-2183-root-branch/spa/src/components/donationPage/live/PaymentSuccess.js#L106-L117)). 

The bug narrowly could be caused by default donation pages (note that billypenn.revengine-test.org/donate does not generate the reported error, while billypenn.revengine-test.org/ does).  In the default donation page context, `getPaymentSuccessUrl` was getting passed `\` for the pathname parameter, and that was leading to erroneous redirection as observed by @x110dc 

#### Why are we doing this? How does it help us?

To release DEV-2183

#### How should this be manually tested? Please include detailed step-by-step instructions.

Make a contribution to default donation page

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No

#### Have automated unit tests been added? If not, why?

Yes

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-2435](https://news-revenue-hub.atlassian.net/browse/DEV-2435)

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No

2022-09-21 15:13 UTC, nrh-cklimas requested changes
Couldn't test on a review app, but the code looks workable to me. Suggested some style improvements to try to make life easier on ourselves down the road.

2022-09-21 15:13 UTC, nrh-cklimas commented on spa/src/components/paymentProviders/stripe/stripeFns.js
> +  paymentSuccessUrl.searchParams.append('next', thankYouRedirectUrl);
How about

```js
paymentSuccessUrl.search = new URLSearchParams({
  amount,
  pageSlug,
  rpSlug,
  email: contributorEmail,
  frequency: frequencyDisplayValue,
  fromPath: pathname === '/' ? '' : pathname,
  next: thankYouRedirectUrl,
  payment_intent_client_secret: stripeClientSecret,
  uid: emailHash,
});
```

A little bit less verbose. I think the comments here are great, I think otherwise there would be a decent amount of magic here.

2022-09-21 15:13 UTC, nrh-cklimas commented on spa/src/components/paymentProviders/stripe/stripeFns.js
> +  // This is the URL that Stripe will send the user to if payment is successfully
Let's add a basic check + test to match:

```js
if (!baseUrl || !thankYouRedirectUrl || !amount || !emailHash || !frequencyDisplayValue || !contributorEmail || !pageSlug || !rpSlug || !pathname || !stripeClientSecret) {
  throw new Error('Missing argument for payment success URL');
}
```

Hopefully will never happen, but if it does we'll get a clear error.

2022-09-21 15:13 UTC, nrh-cklimas commented on spa/src/components/paymentProviders/stripe/stripeFns.js
> +  baseUrl,
How about we destructure these args like this:

```js
export function getPaymentSuccessUrl({ thankYouRedirectUrl, amount, emailHash, etc etc })
```

Reason I suggest it is because it would be easy to accidentally put the args in the wrong order, and it will more-or-less silently fail, but object prop order doesn't matter.

In other words...

```js
// not obviously a bug
const return_url = getPaymentSuccessUrl(
      window.location.origin,
      thank_you_redirect || '',
      emailHash,
      amount,
      getFrequencyThankYouText(frequency),
      contributorEmail,
      pageSlug,
      rpSlug,
      pathname,
      stripeClientSecret
    );

// works fine even though we flipped email and amount
const return_url = getPaymentSuccessUrl({
  baseUrl: window.location.url,
  thankYouRedirect: thank_you_redirect || '',
  emailHash,
  amount,
  frequencyDisplayValue: getFrequencyThankYouText(frequency),
  contributorEmail,
  pageSlug,
  rpSlug,
  pathname,
  stripeClientSecret
});
```

2022-09-21 16:19 UTC, benjaminEwhite commented on spa/src/components/paymentProviders/stripe/stripeFns.js
> +  baseUrl,
Had same thought. You busted me being lazy.

8302702706625c

2022-09-21 17:11 UTC, benjaminEwhite commented on spa/src/components/paymentProviders/stripe/stripeFns.js
> +  // This is the URL that Stripe will send the user to if payment is successfully
4f552a3fe

2022-09-21 17:12 UTC, benjaminEwhite commented on spa/src/components/paymentProviders/stripe/stripeFns.js
> +  paymentSuccessUrl.searchParams.append('next', thankYouRedirectUrl);
This is outdated cause I acted on suggestion

2022-09-21 17:37 UTC, nrh-cklimas approved these changes
Looks ready to go apart from a loose console.log(). I tested in the review app and it looks good there.

2022-09-21 20:35 UTC, x110dc requested changes
One small thing I noticed. If it's not an issue just ignore me.

2022-09-21 20:35 UTC, x110dc commented on spa/src/components/paymentProviders/stripe/stripeFns.js
> +  console.log(arguments);
This isn't my area so just tell me that this isn't an issue, but if this `console.log` was for debugging should it be removed?

2022-09-22 01:26 UTC, benjaminEwhite commented on spa/src/components/paymentProviders/stripe/stripeFns.js
> +  console.log(arguments);
Good catch. Missed that in final cleanup.

2022-09-22 01:27 UTC, benjaminEwhite commented on spa/src/components/paymentProviders/stripe/stripeFns.js
> +  console.log(arguments);
d2009d9428

2022-09-22 02:02 UTC, x110dc approved these changes

2022-09-22 23:14 UTC, merged