DEV 2437 add stripe account for update payment method
newsrevenuehub/rev-engine pull request #687
Opened 2022-09-20 21:31 UTC by x110dc

#### What's this PR do?

Returns the Stripe Account ID on the contributions and subscriptions endpoints. 

#### Why are we doing this? How does it help us?

The frontend needs the Stripe Account ID in order to create a new payment method to attach/update on a Subscription. It would've been difficult to get that otherwise. 

#### How should this be manually tested? Please include detailed step-by-step instructions.

1. Run the server locally or use the Review App. 
2. Request a magic link for a RP/email that has Subscriptions
3. View the contributor portal with that magic link
4. Using DevTools examine the API response from the `/contributions/` and `/subscriptions` endpoints. 
5. Confirm both have a `stripe_account_id` field that's populated. 

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No.

#### Have automated unit tests been added? If not, why?

Yes.

#### How should this change be communicated to end users?

No.

#### Are there any smells or added technical debt to note?

Since the Stripe objects themselves don't have a field indicating the Stripe Account they came from (when they come from a Connect webhook they do have this field) I opted to just add the field as an attribute before storing to the cache. That felt slightly ugly. Not sure if there's a better way to do it. 

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-2437

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

N/A

2022-09-20 23:29 UTC, njharman requested changes
pre-review checklist not completed.
time not logged.

Full coverage, but some logic is not tested.

2022-09-20 23:29 UTC, njharman commented on apps/contributions/stripe_contributions_provider.py
> +            data[k]["stripe_account_id"] = self.stripe_account_id
Are there a lot? I can't imagine it matters but iterating over values and doing `v["stripe_account_id"] = self.stripe_account_id` is more efficient than looking up value each time via key.

2022-09-20 23:29 UTC, njharman commented on apps/contributions/stripe_contributions_provider.py
>  class SubscriptionsCacheProvider:
Probably out of scope. But the amount of duplicated code between these CacheProviders makes me twitch.

2022-09-20 23:29 UTC, njharman commented on apps/contributions/stripe_contributions_provider.py
> +        # add the stripe account ID
Comment would be more useful and less "just repeating what code says" if it included some of this explanation
 
> Since the Stripe objects themselves don't have a field indicating the Stripe Account they came from (when they come from a Connect webhook they do have this field)

2022-09-20 23:29 UTC, njharman commented on apps/contributions/tests/test_stripe_contributions_provider.py
> +                stripe_account_id="bogus",
Should test that strip_account_id is present and the correct value in data returned from cache, no?

2022-09-20 23:29 UTC, njharman commented on apps/contributions/serializers.py
> +    stripe_account_id = serializers.CharField(max_length=255, required=False, allow_blank=True)
[Mostly just verifying I understand. (The AC where not specific)]

It's find only adding to this serializer, (and not the Contribution/Subscription ones) because we only need the stripe_account_id for the contribution portal name?. Thing contributors use to see their contributions. And not the other use cases of endpoints (users of nrh viewing/managing contributions to their org/rp) 

Also I don't understand why(aka don't like that) both use cases are jammed into the same endpoints.

2022-09-21 23:30 UTC, x110dc commented on apps/contributions/serializers.py
> +    stripe_account_id = serializers.CharField(max_length=255, required=False, allow_blank=True)
As far why we need it on these two endpoints and nowhere else: that's explained by @nrh-cklimas here: https://news-revenue-hub.atlassian.net/browse/DEV-1569?focusedCommentId=55830

I'm not sure I understand your second paragraph, but there's intentionally some overlap between the `/contributions/` and the `/subscriptions/` endpoint right now because the FE is relying on the former for too many things but reducing that overlap is addressed in these tickets: 

- https://news-revenue-hub.atlassian.net/browse/DEV-2320
- https://news-revenue-hub.atlassian.net/browse/DEV-2391
- https://news-revenue-hub.atlassian.net/browse/DEV-2438

While the FE transitions to use the latter API more. 

Also, I'm confused myself a bit about why the stripe_account_id was showing on the `/subscriptions/` endpoint when I hadn't explicitly declared it on the serializer, but I added that here: https://github.com/newsrevenuehub/rev-engine/pull/687/commits/4315d2e400ce2df6a84a3abffa7d84739428c9d4 I guess something about DRF that I don't fully understand.

2022-09-21 23:30 UTC, x110dc commented on apps/contributions/tests/test_stripe_contributions_provider.py
> +                stripe_account_id="bogus",
Fixed here: https://github.com/newsrevenuehub/rev-engine/pull/687/commits/ba97fb05b2cc27820bbfe2866c98d400c8107b60

2022-09-21 23:30 UTC, x110dc commented on apps/contributions/stripe_contributions_provider.py
> +        # add the stripe account ID
Agreed. Fixed here: https://github.com/newsrevenuehub/rev-engine/pull/687/commits/ba97fb05b2cc27820bbfe2866c98d400c8107b60

2022-09-21 23:33 UTC, x110dc commented on apps/contributions/stripe_contributions_provider.py
>  class SubscriptionsCacheProvider:
Agreed, out of scope for this ticket. But I added a TODO/ticket to address: https://github.com/newsrevenuehub/rev-engine/pull/687/commits/f0d62fc604821b6b1174797d93199474bc5f73b4

2022-09-21 23:33 UTC, x110dc commented on apps/contributions/stripe_contributions_provider.py
> +            data[k]["stripe_account_id"] = self.stripe_account_id
👍 Improved here: https://github.com/newsrevenuehub/rev-engine/pull/687/commits/ba97fb05b2cc27820bbfe2866c98d400c8107b60

2022-09-22 18:52 UTC, njharman approved these changes
no pre-review checklist

2022-09-22 23:22 UTC, merged