DEV-2408: Stripe webhooks fail for subscriptions
newsrevenuehub/rev-engine pull request #689
Opened 2022-09-21 15:23 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

This fixes a bug discovered in UAT for DEV-2183. It should be merged into DEV-2183-root-branch, and that branch will eventually be merged into main.

#### What's this PR do?

This PR fixes a bug that was causing Stripe webhooks to fail for recurring contributions ("Subscriptions" in Stripe lingo).

The root cause of the bug was that we were not saving the Stripe Customer ID back on to the NRE contribution after creating a Stripe PaymentIntent or Subscription. In our webhooks code, for subscriptions, we were attempting to retrieve by customer ID instead of subscription ID.

To solve for this, this PR changes the contribution retrieval behavior of our webhook so that it searches contributions by Stripe subscription ID for subscriptions. It also updates the payment intent and subscription creation methods in apps.contributions.models.Contribution so that the customer id gets written back to the contribution (even though the customer id is no longer relevant for the webhook in question).

#### Why are we doing this? How does it help us?

Fixes a bug that stops us from shipping DEV-2183.

#### How should this be manually tested? Please include detailed step-by-step instructions.

Create a recurring contribution, then check in NRH admin and its status should move past processing.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No

#### Have automated unit tests been added? If not, why?

Tests have been updated

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

- [DEV-2408 | Webhooks are broken for Subscriptions in DEV-2183](https://news-revenue-hub.atlassian.net/jira/software/c/projects/DEV/boards/3?modal=detail&selectedIssue=DEV-2408)
- [DEV-2183](https://news-revenue-hub.atlassian.net/browse/DEV-2183)

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No

2022-09-22 18:16 UTC, njharman commented on apps/contributions/models.py
> +        self.provider_customer_id = subscription["customer"]
It doesn't seem that test_stripe_subscription checks that this value is set.

2022-09-22 18:35 UTC, njharman requested changes
no time logged
no pre-review check list

2022-09-22 18:35 UTC, njharman commented on apps/contributions/models.py
> +        self.provider_customer_id = subscription["customer"]
It doesn't seem that test_stripe_subscription checks that this value is set.

2022-09-22 18:35 UTC, njharman commented on apps/contributions/models.py
> +        self.provider_customer_id = intent["customer"]
It doesn't seem that test_create_stripe_one_time_payment_intent checks that this value is set. In fact deleting this line causes no failure in test_models.py (where I'd expect failure) and no failure in any test.

2022-09-22 18:35 UTC, njharman commented on apps/contributions/webhooks.py
> +                    raise e
Pretty sure the "e" is superfluous and thus confusing (implying that code is modifying or raising some other exception than one being handled) https://docs.python.org/3/reference/simple_stmts.html#raise

2022-09-23 00:58 UTC, benjaminEwhite commented on apps/contributions/webhooks.py
> +                    raise e
b7405441

2022-09-23 00:58 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        self.provider_customer_id = intent["customer"]
b7405441

2022-09-23 00:58 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        self.provider_customer_id = subscription["customer"]
b7405441

2022-09-23 21:27 UTC, x110dc approved these changes

2022-09-23 21:30 UTC, merged