WIP | DEV-2445 — Server-Side changes for DEV-1869
newsrevenuehub/rev-engine pull request #692
Opened 2022-09-22 01:47 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2022-09-22 19:16 UTC, njharman requested changes

2022-09-22 19:16 UTC, njharman commented on apps/api/tests/__init__.py
> +        return self.assert_user_cannot_patch(url, self.superuser, data, expected_status_code)
Use pytest assert style testing on new and modified code

2022-09-22 19:16 UTC, njharman commented on apps/organizations/models.py
> +    custom_thank_you_page_enabled: bool = False
These Plan instances are "bags" on constants?  Not meant to change?

Consider https://docs.python.org/3/library/dataclasses.html#frozen-instances

2022-09-23 01:43 UTC, benjaminEwhite commented on apps/api/tests/__init__.py
> +        return self.assert_user_cannot_patch(url, self.superuser, data, expected_status_code)
This is a convenience function that does a number of things "wrapping" the assertion itself. While the `assert_user_cannot_patch` should be refactored when/if touched, refactoring that function to use pytest assert is not in scope for this PR.

2022-09-23 01:50 UTC, benjaminEwhite commented on apps/organizations/models.py
> +    custom_thank_you_page_enabled: bool = False
53d9e312

2022-09-23 21:19 UTC, x110dc approved these changes

2022-09-26 20:36 UTC, merged