DEV-2387: Add info tooltip to Tax Status field, refactor components
newsrevenuehub/rev-engine pull request #693
Opened 2022-09-22 14:09 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

This is stacked on DEV-2028 for clarity.

The headline feature here is that this adds an icon beside the Company Tax Status field that can be clicked to show more information. It also contains improvements to the form layout and controls so that they are closer to Figma.

Under the covers, I also added a new directory, `components/base`. These contain some basic building-block components that I use in this PR but I am hoping we can gradually adopt across the app. They have Storybook demos (`npm run storybook`) and should match Figma, and are definitely a first pass/not comprehensive for all possible uses.

#### Why are we doing this? How does it help us?

The tooltip is there to better inform users as to what implications choosing a tax status will have.

The new components have been added so we can gradually standardize how our basic components are used instead of using one-off styles. We have existing components that serve a similar purpose in `elements`, but they have a different appearance that what is in Figma for profile-related UI. I didn't want to touch the existing components right now, since they are used in many other parts of the app.

#### How should this be manually tested? Please include detailed step-by-step instructions.

1. Go to https://dev-2387.revengine-review.org/create-account.
2. Fill out the form, use a +test or similar in your email address.
3. Click the link to verify your email address.
4. Once you do this, you should immediately see a modal to customize your profile.
5. The Company Tax Status field should read "Select your status".
6. After choosing a tax status, you should not be able to choose the "Select your status" value.
7. There should be a tooltip above the Company Tax Status field. Clicking it should show the text below. Clicking anywhere else should hide the tooltip.

> Your tax status determines the contribution fees charged through Stripe.

8. Confirm you can't close the modal by clicking outside it or pressing the Escape key.
9. Submit the modal and confirm in the Django admin that data was properly saved, a la DEV-2028.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

It gets the profile modal closer to Figma, so screenshots might need updating depending on when DEV-2028 is documented.

#### Have automated unit tests been added? If not, why?

Yes.

#### How should this change be communicated to end users?

n/a

#### Are there any smells or added technical debt to note?

I hardcoded a lot of fonts, font sizes, and colors in the base components for now. I didn't want to try to change the MUI global theme to avoid causing any appearance regressions elsewhere in the app.

I used `&&` selectors to win specificity over Material UI. Eventually, we should modify Material UI so [it inserts CSS after Styled Components](https://v4.mui.com/guides/interoperability/#controlling-priority-3) but the effects of a change like that are unpredictable and problems likely wouldn't show up in CI.

#### Has this been documented? If so, where?

n/a

#### What are the relevant tickets? Add a link to any relevant ones.

- https://news-revenue-hub.atlassian.net/browse/DEV-2387
- https://news-revenue-hub.atlassian.net/browse/DEV-2388

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

https://news-revenue-hub.atlassian.net/browse/DEV-2390

2022-09-22 14:24 UTC, nrh-cklimas commented on spa/src/components/base/Button/Button.test.js
> +  it('displays a button', () => {
This test (and similar) are really basic--not trying to exercise the MUI button, just testing that it renders.

2022-09-22 15:37 UTC, GuiMend requested changes

2022-09-22 15:37 UTC, GuiMend commented on spa/src/components/account/Profile/InfoTooltip.js
> +import * as S from './InfoTooltip.styled';
I know that we have the custom to import all styles as `S`, but I think it's really bad to read `<S.Component>` in the JSX. What would you think if importing the components by name? I've been doing that in my PRs and I think it makes them more readable.

```suggestion
import { Icon } from './InfoTooltip.styled';
```

2022-09-22 15:37 UTC, GuiMend commented on spa/src/components/account/Profile/InfoTooltip.js
> +  const [open, setOpen] = useState(false);
You can use our custom hook `useModal`, it has all methods already created for open, close, toggle, etc

2022-09-22 15:37 UTC, GuiMend commented on spa/src/components/account/Profile/InfoTooltip.js
> +    <ClickAwayListener onClickAway={() => setOpen(false)}>
Than you could use `handleClose` here (from `useModal`)

2022-09-22 15:37 UTC, GuiMend commented on spa/src/components/account/Profile/InfoTooltip.js
> +          }}
Why would we want to disable portal? It might be a default config on MUI demo, but I don't know why it is 😅

2022-09-22 15:37 UTC, GuiMend commented on spa/src/components/account/Profile/InfoTooltip.js
> +          <ButtonBase aria-label="Help" disableRipple disableTouchRipple onClick={() => setOpen(true)}>
Would it be good for us to have a "title" prop in this component so we could label this as "Help with [Title]" eg: Help with Tax Selector

2022-09-22 15:37 UTC, GuiMend commented on spa/src/components/account/Profile/InfoTooltip.styled.js
> +`;
This one you could probably remove, if I'm not mistaken we have a `height` and `width` prop on the icons `<Icon height={18} ...`

2022-09-22 15:37 UTC, GuiMend commented on spa/src/components/account/Profile/InfoTooltip.js
> +          disableTouchListener
Shouldn't the tooltip be hover based?

2022-09-22 15:37 UTC, GuiMend commented on spa/src/components/account/Profile/InfoTooltip.test.js
> +  });
@nrh-cklimas , when we add this `is accessible` to popovers, tooltips and modals, does it check those components as well, or just the button that opens them?

2022-09-22 15:37 UTC, GuiMend commented on spa/src/components/account/Profile/Profile.js
> +    <S.Modal open={open} aria-labelledby="profile-modal-title" data-testid="finalize-profile-modal">
Is the onClose supposed to be removed or was it a mistake?

2022-09-22 15:37 UTC, GuiMend commented on spa/src/components/account/Profile/ProfileForm.js
> +        defaultValue=""
Not sure you need a defaultValue here. Belive removing it is fine
```suggestion
```

If you need a defaultValue, you can add it to `useHookForms`

2022-09-22 15:37 UTC, GuiMend commented on spa/src/components/account/Profile/ProfileForm.js
> +  const { control, handleSubmit, watch } = useForm();
Really nice refactor 👏

2022-09-22 15:37 UTC, GuiMend commented on spa/src/components/account/Profile/ProfileForm.styled.js
> +import InfoTooltip from './InfoTooltip';
Maybe update to absolute import? I'm thinking the tooltip might be moved to a more generic folder later

2022-09-22 15:37 UTC, GuiMend commented on spa/src/components/base/Button/Button.js
> +  <StyledMuiButton disableFocusRipple disableRipple ref={ref} variant="contained" {...props} />
The ripple is so beautifull 😢

2022-09-22 15:37 UTC, GuiMend commented on spa/src/components/base/TextField/TextField.js
> +TextField.propTypes = MuiTextField.propTypes;
No need to change anything now, but if we are going to have a default style for Button, TextFields, etc, we could override their styles in `theme` instead of having to have a custom component of each basic element

2022-09-22 15:37 UTC, GuiMend commented on spa/src/components/base/Tooltip/Tooltip.stories.js
> +  const [open, setOpen] = useState(false);
Can also use `useModal`

2022-09-22 15:37 UTC, GuiMend commented on spa/src/components/base/Tooltip/Tooltip.stories.js
> +    <>
This fragment is not needed
```suggestion
```

2022-09-22 16:37 UTC, nrh-cklimas commented on spa/src/components/account/Profile/InfoTooltip.styled.js
> +`;
I tried this, but it didn't make the appearance change. It looks like setting props directly does set height/width on the SVG element, but there's a CSS rule `.MuiSvgIcon-root` that overrides it.

2022-09-22 16:38 UTC, nrh-cklimas commented on spa/src/components/account/Profile/InfoTooltip.js
> +          disableTouchListener
No -- see https://news-revenue-hub.atlassian.net/browse/DEV-2387?focusedCommentId=56345

2022-09-22 16:41 UTC, nrh-cklimas commented on spa/src/components/account/Profile/Profile.js
> +    <S.Modal open={open} aria-labelledby="profile-modal-title" data-testid="finalize-profile-modal">
This is intentional--it should prevent the user from being able to close the modal without submitting the form. This addresses https://news-revenue-hub.atlassian.net/browse/DEV-2388 since it's a one-liner.

2022-09-22 16:42 UTC, nrh-cklimas commented on spa/src/components/account/Profile/ProfileForm.styled.js
> +import InfoTooltip from './InfoTooltip';
I agree, I'd like to move this into `components/base` as soon as we find a need for it in multiple places, but for now I'd like to keep it here.

2022-09-22 16:43 UTC, nrh-cklimas commented on spa/src/components/base/Button/Button.js
> +  <StyledMuiButton disableFocusRipple disableRipple ref={ref} variant="contained" {...props} />
:) I haven't seen design guidance one way or the other on focus styles, have you? Was trying to keep it simple for now.

2022-09-22 16:43 UTC, nrh-cklimas commented on spa/src/components/base/TextField/TextField.js
> +TextField.propTypes = MuiTextField.propTypes;
100% on board with this. Just don't want to touch the global theme for now.

2022-09-22 17:22 UTC, nrh-cklimas commented on spa/src/components/account/Profile/InfoTooltip.js
> +import * as S from './InfoTooltip.styled';
I don't have strong feelings about it one way or the other, so let's go with what you're suggesting. Could you add a note on our JS style guide Confluence doc about it?

Updated the files this PR touches in 66e85671e976a5e8dfc9be64ca3b05fad19872a1

2022-09-22 17:23 UTC, nrh-cklimas commented on spa/src/components/account/Profile/InfoTooltip.js
> +  const [open, setOpen] = useState(false);
Ah, I see. I feel like I want to argue for eventually renaming it to `useToggle` or something like that since it feels weird to use a modal state in a tooltip to me. Anyway, updated in 4b5e4757ce5d3c3e885277bc1158f2157c8bae42

2022-09-22 17:23 UTC, nrh-cklimas commented on spa/src/components/account/Profile/InfoTooltip.js
> +    <ClickAwayListener onClickAway={() => setOpen(false)}>
Updated in 4b5e4757ce5d3c3e885277bc1158f2157c8bae42

2022-09-22 17:25 UTC, nrh-cklimas commented on spa/src/components/account/Profile/InfoTooltip.js
> +          }}
I'll admit, this is a straight copy/paste. I couldn't see a functional difference when I took it out (maybe it was to get the display right on MUI's demo page?) so I removed it in 111ec87ea1da3e4afe1b8e7b791928113ca2ac64

2022-09-22 17:33 UTC, nrh-cklimas commented on spa/src/components/account/Profile/ProfileForm.js
> +        defaultValue=""
I started down this road because not setting a default on the select triggered this error: https://github.com/react-hook-form/documentation/issues/133

Appreciate the suggestion on the hook call--I like that it makes the JSX simpler, so I moved defaults into the hook call in f3a6d44288dba8365019f2bc4e135c22fe0ee1b4

2022-09-22 17:35 UTC, nrh-cklimas commented on spa/src/components/base/Tooltip/Tooltip.stories.js
> +  const [open, setOpen] = useState(false);
I kinda want to keep this as-is so we can keep story dependencies simple. e.g. if we rewrite useModal one day, we don't have to update our stories. Also, we may end up making InfoTooltip a shared component anyway so we wouldn't need this story. But if you feel strongly about it, I can rewrite in here.

2022-09-22 17:35 UTC, nrh-cklimas commented on spa/src/components/base/Tooltip/Tooltip.stories.js
> +    <>
Fixed in d412700006a246e46e5daf49459a78cfe233a216

2022-09-22 19:47 UTC, GuiMend commented on spa/src/components/base/Button/Button.js
> +  <StyledMuiButton disableFocusRipple disableRipple ref={ref} variant="contained" {...props} />
Also didn't see anything, but as it is a default Mui behaviour I left it unchanged in my PRs

2022-09-23 14:39 UTC, nrh-cklimas commented on spa/src/components/base/Button/Button.js
> +  <StyledMuiButton disableFocusRipple disableRipple ref={ref} variant="contained" {...props} />
Discussed this with our designer on Slack and it's a topic for future work, so makes sense to use defaults for now. Updated in 55e311c20a19037093b90df0672d99263677f56a

2022-09-23 19:33 UTC, GuiMend approved these changes
LGTM 👍

2022-09-27 17:44 UTC, merged