DEV-2446 SPA-side changes
newsrevenuehub/rev-engine pull request #695
Opened 2022-09-22 21:22 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

This is two of two planned stacked PRs to accomplish the AC in the parent ticket, [DEV-1869](https://news-revenue-hub.atlassian.net/jira/software/c/projects/DEV/boards/3?modal=detail&selectedIssue=DEV-1869)

This PR is initially into into DEV-2445-server-side-changes, as it branches from there, but once that's merged into DEV-1869-root-branch, this PR should change its base to `DEV-1869-root-branch`, which will ultimately be merged into `main` later.

#### What's this PR do?

Refactors PageSetup component in SPA so that it disables the thank you page input if the page's RP's org's `custom_thank_you_page_enabled` value is 'False`. It also causes a tooltip to be displayed when user hovers over the disabled input.

Note that the styling on the disabled input could be improved, but this was discussed with Mariclare and Rachel, and that will be pursued separately in [DEV-2443](https://news-revenue-hub.atlassian.net/browse/DEV-2443).

- Adds a `ConditionalWrapper` component that can be used to conditionally wrap another component. In this case we use it to conditionally wrap the tooltip.
- Adds basic unit tests for PageSetup for the thank you page behavior.

#### Why are we doing this? How does it help us?

Required for self-onboarding flow.

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2022-09-22 21:41 UTC, benjaminEwhite commented on spa/src/elements/inputs/Input.js
> +      id={props.label}
this is necessary for the accompanying label's `for` to point to the paired input.

2022-09-23 13:47 UTC, nrh-cklimas requested changes

2022-09-23 13:47 UTC, nrh-cklimas commented on spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.test.js
> +  screen.getByLabelText('Thank You page link');
At minimum, we're missing an expect() here, and I would set `mockThankYouRedirectEnabled` in each test explicitly to avoid accidentally depending on test order.

2022-09-23 13:47 UTC, nrh-cklimas commented on spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.test.js
> +// This would not be my preferred way of handling this, but the two
I have a suggestion on how to make this less gnarly at https://github.com/newsrevenuehub/rev-engine/commit/ed8f3f96ec3794a1ae9a3619ee19aedd5aa0a3bd. IMHO, it is always easier to create a test context directly instead of trying to mock a context provider, basically for the reason you write here.

2022-09-23 14:03 UTC, benjaminEwhite commented on spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.test.js
> +  screen.getByLabelText('Thank You page link');
Just double checked, and  this test fails with the message (after changing the label text search value to nonsense):

```
TestingLibraryElementError: Unable to find a label with the text of: Thank You pdsage link

```

If I change the test to `expect(screen.getByLabelText('Thank You pdsage link')).toBeInTheDocument();`, I get the same test failure, and identical message.

I believe that testing library's `getBy` methods are meant to cause test failure if the item can't be found: https://testing-library.com/docs/queries/about/#types-of-queries

2022-09-23 14:15 UTC, benjaminEwhite commented on spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.test.js
> +// This would not be my preferred way of handling this, but the two
Love it. Merged suggestions into this branch: ed8f3f96ec3794

2022-09-23 14:19 UTC, nrh-cklimas commented on spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.test.js
> +  screen.getByLabelText('Thank You page link');
That's 100% correct, I went a little too fast with my suggestion.

2022-09-23 14:20 UTC, nrh-cklimas approved these changes

2022-09-23 21:14 UTC, x110dc approved these changes

2022-09-26 20:15 UTC, merged