DEV-2456: fix mistaken approach to filtering
newsrevenuehub/rev-engine pull request #697
Opened 2022-09-23 04:41 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

Ideally, quick approval, and get this merged into test, so we can determine if Apple Pay is now working.

#### What's this PR do?

This fixes a bug observed after nearly getting apple pay working in test env. The way we were checking for missing args in `getPaymentSuccessUrl` was causing `amount` to appear as missing when its passed value was `"1"`. 

This should fix that bug, which will in turn hopefully reveal that we have functioning Apple Pay on front end.

#### Why are we doing this? How does it help us?

Ship new checkout flow

#### How should this be manually tested? Please include detailed step-by-step instructions.

We'll know this solved the problem if a.) there's not a console log error about amount being undefined after submitting the stripe payment form. and b.) ultimately, this should hopefully make apple pay work in test env, once it's been deployed there.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No

#### Have automated unit tests been added? If not, why?

No. Not worth the investment for this kind of bug.

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

No

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-2456](https://news-revenue-hub.atlassian.net/browse/DEV-2456)

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

NO

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

NO

2022-09-23 14:08 UTC, nrh-cklimas commented
Let's make our tests bulletproof just in case.

```jsx
  it('accepts an amount of 1', () => {
    getPaymentSuccessUrl({ ...fromDefaultPageParams, amount: 1 });
  });

  it('throws if a necessary param is missing', () =>
    expect(() => getPaymentSuccessUrl({ ...fromDefaultPageParams, baseUrl: undefined })).toThrow());
```

2022-09-23 14:10 UTC, nrh-cklimas requested changes
Code looks good, added a comment with some suggested added tests.

2022-09-23 14:13 UTC, nrh-cklimas commented on spa/src/components/paymentProviders/stripe/stripeFns.js
> +    }).filter(([_, v]) => [undefined, null, ''].includes(v))
e.g. `1 in ['a', 'b', 'c']` is true because the array has a value at index 1, just as `'a' in { a: 'b' }` is also true.

2022-09-23 14:20 UTC, benjaminEwhite commented
@nrh-cklimas see a175cf146bba where i added tests you suggested.

2022-09-23 14:22 UTC, nrh-cklimas approved these changes

2022-09-23 21:10 UTC, x110dc approved these changes

2022-09-26 13:50 UTC, nrh-cklimas commented
re: the Cypress test failing, it seems to be on the default donation page only. I added a console.log to getPaymentSuccessUrl() to see what it thought `pathName` was and it logs it as `/` once, then repeatedly as `undefined` (which it doesn't like).

I think an issue is that `handleSubmit` should be created via `useCallback`, but I don't know if that is actually what is causing the test to fail. I see locally this error message too:

```
If you are testing Apple Pay or Google Pay, you must serve this page over HTTPS as it will not work over HTTP. Please read https://stripe.com/docs/stripe-js/elements/payment-request-button#html-js-prerequisites for more details.
```

I'm not sure though if this is relevant since other donation page tests pass.

2022-09-26 17:02 UTC, merged