DEV-2304: Create Successful Publish Modal
newsrevenuehub/rev-engine pull request #702
Opened 2022-09-23 19:06 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
N/A

#### What's this PR do?
Creates a modal to display a successful publishment of a donation page with important information.

#### Why are we doing this? How does it help us?
This helps the user to easily know all related links to the donation page they just published.

#### How should this be manually tested? Please include detailed step-by-step instructions.
- Login
- Enter the edit screen for an unpublished donation page
- Publish the page
- You should view the modal on success
- You can also check the new stories: `Button > CopyInputButton` and `Modal > SuccessfulPublishModal`
![image](https://user-images.githubusercontent.com/9381325/192039375-edfa7259-31fe-4f65-a5b2-df535d10666b.png)

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
Yes

#### Have automated unit tests been added? If not, why?
Yes

#### How should this change be communicated to end users?
Publishing pages now opens a modal with all relevant information for the user and their clients.

#### Are there any smells or added technical debt to note?
No

#### Has this been documented? If so, where?
No

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-2304

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
https://news-revenue-hub.atlassian.net/browse/DEV-2299

2022-09-26 14:54 UTC, nrh-cklimas requested changes
Looks pretty good! Putting stuff in Storybook continues to make review easier. Just have a few comments, mostly around tests.

2022-09-26 14:54 UTC, nrh-cklimas commented on spa/src/components/common/Button/CopyInputButton/CopyInputButton.js
> +        <Input aria-label={link} value={link} onChange={() => {}} />
To me, it doesn't make sense to make the label for this input be the same thing as its value. I think this should be `title` instead, e.g. "Contribution Page Link" or "Contributor Portal Link."

Can we do `readOnly` on this instead of a no-op `onChange`, like with the other modal?

2022-09-26 14:54 UTC, nrh-cklimas commented on spa/src/components/common/Button/CopyInputButton/CopyInputButton.test.js
> +  it('should copy link to clipboard', async () => {
Would be nice to have a test for when the copy fails, for coverage reasons.

2022-09-26 14:54 UTC, nrh-cklimas commented on spa/src/components/common/Button/CopyInputButton/CopyInputButton.js
> +  const showCopied = copied === link;
I think this is OK for now, bu I think we may need to revisit this logic later. What I am envisioning is one day, we add a Copy button somewhere far away on the component tree. If we want only one button to show a Copied message, I think we'd have to add a context to track this global clipboard state, which feels like overkill.

Anyway, we're not there yet, so no changes are needed... but I feel like we are moving toward a direction where we abstract this clipboard logic into a hook.

2022-09-26 14:54 UTC, nrh-cklimas commented on spa/src/components/common/Button/GrabLink/GrabLink.js
> +        <CopyInputButton title="Contribution Page Link" link={pageLink(page)} copied={copied} setCopied={setCopied} />
:+1: for refactoring them all into the same component

2022-09-26 14:54 UTC, nrh-cklimas commented on spa/src/utilities/getPageLinks.js
> +export const pageLink = (page) => `${page?.revenue_program?.slug}.${getDomain(window.location.host)}/${page?.slug}`;
I like getting these in one place, but let's put some unit tests on them.

2022-09-26 18:56 UTC, GuiMend commented on spa/src/components/common/Button/CopyInputButton/CopyInputButton.js
> +  const showCopied = copied === link;
Not sure if I understood the need for this. Clipboard is always going to be the last value, right? So if there are Copy buttons throughout the application, the clipbord will reflect the latest one clicked.

2022-09-26 20:02 UTC, nrh-cklimas approved these changes

2022-09-26 20:02 UTC, nrh-cklimas commented on spa/src/components/common/Button/CopyInputButton/CopyInputButton.js
> +  const showCopied = copied === link;
What I'm picturing is something like this:

```jsx
const CopyButtons = ({urlOne, urlTwo}) => {
  const [copied, setCopied] = useState('');

  return (<>
    <CopyButton copied={copied} onClick={() => setCopied(urlOne)}>copy {urlOne}</CopyButton>
    <CopyButton copied={copied} onClick={() => setCopied(urlTwo)}>copy {urlTwo}</CopyButton>
  </>);
};
```

When you click one of these, it says "Copied" and the other one, if it had previously said "Copied", now goes back to "Copy".

However...

```jsx
const ManyCopyButtons = () => (
  <>
    <CopyButtons urlOne="aaa" urlTwo="bbb" />
    <CopyButtons urlOne="ccc" urlTwo="ddd" />
  </>
);
```

I think this would show inconsistent behavior. Clicking Copy on one button would make it say "Copied", but other buttons would not change.

We don't have this happening right now, but I could see it eventually occurring.

2022-09-26 22:50 UTC, GuiMend commented on spa/src/components/common/Button/CopyInputButton/CopyInputButton.js
> +  const showCopied = copied === link;
Oh ok, got it. Yes, that could happen

2022-09-27 17:48 UTC, x110dc approved these changes

2022-09-27 17:56 UTC, merged