DEV-1923: Upgrade Cypress to 10
newsrevenuehub/rev-engine pull request #719
Opened 2022-09-29 14:45 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

- Upgrades us to Cypress 10.
- Removes the component-related Cypress npm tasks, since we don't have plans to use them.

#### Why are we doing this? How does it help us?

- Good to be on the latest.
- This unblocks us on using TypeScript in the SPA.

#### How should this be manually tested? Please include detailed step-by-step instructions.

`npm run cypress:run` should pass and `npm run cypress:open` should work in a local dev enviromment.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No.

#### Have automated unit tests been added? If not, why?

No, this is an upgrade to our test framework.

#### How should this change be communicated to end users?

n/a

#### Are there any smells or added technical debt to note?

Because Cypress has changed its file naming scheme, this is going to cause merge conflicts for in-flight PRs.

I had to port forward our DIY plugin to leverage CRA webpack config because we import code from the SPA itself into Cypress. I think we should probably get stricter about this in the future to save ourselves heartburn.

#### Has this been documented? If so, where?

n/a

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-1923

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No.

2022-10-03 13:53 UTC, GuiMend approved these changes
LGTM 👍 
![image](https://user-images.githubusercontent.com/9381325/193594939-b7be74d0-2fbe-4503-abdb-47627d5612ce.png)

2022-10-03 22:06 UTC, benjaminEwhite commented on spa/cypress/e2e/02 - donation-page-edit.spec.js
> +import { DELETE_LIVE_PAGE_CONFIRM_TEXT } from 'constants/textConstants';
As long as we're touching all the spec files, would it be too much to ask that we rename all so there are no white spaces in file names? That's been bugging me for a while cause spaces are annoying to deal with in command line env, and seems serendipitously in scope.

2022-10-04 12:43 UTC, nrh-cklimas commented on spa/cypress.config.js
> +  chromeWebSecurity: false,
[Docs say](https://docs.cypress.io/guides/guides/web-security#Set-chromeWebSecurity-to-false) this lets us peek at other domains besides the one we test, and also to work with cross-domain iframes (comes up with Stripe, maybe analytics, I'm thinking).

2022-10-04 12:47 UTC, nrh-cklimas commented on spa/cypress.config.js
> +  component: {
Cypress's migration tool added this, but I don't see a use for it either. Removed in 5e09221061284cacfea45a35dc67e1fc3f7ba182

2022-10-04 12:48 UTC, nrh-cklimas commented on spa/cypress.config.js
> +    setupNodeEvents(on, config) {},
Well, nothing since it's an empty function :). But the intent of these functions is to allow customization of Cypress like we used to do in spa/cypress/plugins/index.js. I removed this with the rest of the component config in 5e09221061284cacfea45a35dc67e1fc3f7ba182

2022-10-04 12:49 UTC, nrh-cklimas commented on spa/cypress.config.js
> +    setupNodeEvents(on, config) {},
Docs FWIW: https://docs.cypress.io/guides/references/configuration#modifyObstructiveCode

2022-10-04 20:21 UTC, nrh-cklimas commented on spa/cypress/e2e/02 - donation-page-edit.spec.js
> +import { DELETE_LIVE_PAGE_CONFIRM_TEXT } from 'constants/textConstants';
Updated in fb0786a998ca195ba6e1f3853defdbc049ad897f

2022-10-04 21:27 UTC, benjaminEwhite commented on spa/cypress.config.js
> +  chromeWebSecurity: false,
That's right! It was the iframe that needed it. Might be worth putting a code comment here to that effect.

2022-10-04 21:28 UTC, benjaminEwhite commented on spa/cypress.config.js
> +  chromeWebSecurity: false,
```suggestion
  // this is set to false to enable testing pages that require iframes
  chromeWebSecurity: false,
```

2022-10-06 00:11 UTC, x110dc requested changes
LGTM but there are some merge conflicts.

2022-10-06 20:41 UTC, x110dc approved these changes

2022-10-06 20:41 UTC, merged