DEV-2234: Update Contributions layout
newsrevenuehub/rev-engine pull request #728
Opened 2022-10-03 17:08 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
N/A

#### What's this PR do?
Creates a banner that pops up in the Contributions Dashboard if the user hasn't done a step to enable the contributions to be displayed in the table

#### Why are we doing this? How does it help us?
Helps the user identify the steps needed to have the Contributions dashboard display usefull information. Without the banner, the user doesn't know why the dasboard is always empty

#### How should this be manually tested? Please include detailed step-by-step instructions.
4 scenarios to test:
Login with user as described below, go to  `/contributions`:
- Admin user:  no banner shold appear
- Non-admin user with stripe **not** connected and **no** live pages: banner should appear with Stripe related message
- Non-admin user with stripe connected and no live pages: banner should appear with Publish related message 
- Non-admin user with stripe and live pages: no banner should appear

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
Yes

#### Have automated unit tests been added? If not, why?
Yes, but not all. Still need to create some additional cypress tests

#### How should this change be communicated to end users?
Pop up banners now display to the user if they don't have the correct settings to get data in the contributions dashboard

#### Are there any smells or added technical debt to note?
No

#### Has this been documented? If so, where?
No

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-2235

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
No

2022-10-03 18:50 UTC, GuiMend commented
Chris, could you check if cypress fails for you locally? For me it's working locally 🤔

2022-10-03 21:14 UTC, nrh-cklimas requested changes
The Cypress test failure was a timeout--I reran it on the PR and it passed.

Overall looks very good to me, just have suggestions on the approach.

2022-10-04 12:34 UTC, GuiMend commented on spa/src/components/dashboard/Dashboard.js
> +  const bannerType = useMemo(() => {
I could move it to Donation, but all the data needed is already being used in Dashboard, so if I change it to Donations I'll have to import all data again inside Donation. I thought it was better to just use it there and pass it as props

2022-10-04 12:35 UTC, GuiMend commented on spa/src/components/dashboard/PageListContext.js
> +import { createContext, useState, useContext } from 'react';
I'm not familiar with that lib yet, it would take me some time to know how to implement it that way

2022-10-04 13:00 UTC, GuiMend commented on spa/src/components/common/Banner/Banner.js
> +        <Button onClick={handleClose} aria-label="Dismiss message" type={type}>
I'd like to leave it because "dismiss message" is clearer than "got it"

2022-10-04 13:01 UTC, GuiMend commented on spa/src/components/common/Banner/Banner.stories.js
> +export const Selected = Banner.bind({});
Removed

2022-10-04 14:13 UTC, nrh-cklimas commented on spa/src/components/common/Banner/Banner.js
> +        <Button onClick={handleClose} aria-label="Dismiss message" type={type}>
I agree that that phrasing is more clear, but if we believe that, we should make the label on the button this text for all users.

A somewhat contrived example where this kind of thing can be problematic:

1. Two users in an organization: one uses a screen reader, the other doesn't.
2. The screen reader user is new and being trained.
3. The non-screen reader user says, "Click the 'Got it' button at the top" on a call orienting them.
4. Screen reader user: "what 'Got It' button?"

2022-10-04 21:03 UTC, nrh-cklimas approved these changes

2022-10-05 15:23 UTC, benjaminEwhite requested changes
See my comment in this thread: https://github.com/newsrevenuehub/rev-engine/pull/728/files#r986220971

Pushed up a branch with light refactor to use react-query + custom hook here. That required tweaking one existing test as well, fwiw.

2022-10-05 15:23 UTC, benjaminEwhite commented on spa/src/components/dashboard/PageListContext.js
> +import { createContext, useState, useContext } from 'react';
Just pushed up this branch, which contains lightly refactors this branch to use react-query and a custom hook instead of context. I think this is a little cleaner, and moves us toward standardizing the use of react-query (which is proving to be a good pattern).

https://github.com/newsrevenuehub/rev-engine/tree/DEV-2235-conditional-banner-for-prompts-on-empty-contributions-section--bw-suggestion

Note that I didn't make a PR for this because I don't want to create overhead of additional review + review app + tearing down review app.

2022-10-05 19:38 UTC, benjaminEwhite approved these changes

2022-10-06 22:51 UTC, x110dc approved these changes

2022-10-11 21:12 UTC, merged