[WIP] DEV-2580 | Spa-side changes to support recursive stripe account verification flow
newsrevenuehub/rev-engine pull request #742
Opened 2022-10-06 16:07 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2022-10-07 14:12 UTC, nrh-cklimas requested changes
Looks like we have one unit test failure.

We don't have test coverage on useConnectStripeAccount--I can help out with that if you were running into trouble.

There's also an empty file, spa/src/components/dashboard/connectStripe/ConnectStripeToast.stories.js, that can be deleted if stories weren't feasible on this go-round.

2022-10-11 13:47 UTC, benjaminEwhite commented on spa/src/hooks/useConnectStripeAccount.js
> +  const { data } = await axios.post(getStripeAccountLinkStatusPath(rpId), {});
Yeah, i was on fence about making post or get. It ultimately does cause a Stripe Account Link to be created, but that's not something that we store, we just pass it on. Seemed "side effecty" enough to warrant POST, but that wasn't a strong opinion.

2022-10-11 15:58 UTC, benjaminEwhite commented on spa/src/components/dashboard/connectStripe/ConnectStripeElements.js
> +    const cookies = new Cookies();
e52e251d3255

2022-10-11 15:59 UTC, benjaminEwhite commented on spa/src/components/dashboard/connectStripe/ConnectStripeElements.js
> +    const cookies = new Cookies();
de653f8a99cbb92a

2022-10-11 16:01 UTC, benjaminEwhite commented on spa/src/hooks/useConnectStripeAccount.js
> +const pending_verification_message =
b895e9596a2b

2022-10-11 16:02 UTC, benjaminEwhite commented on spa/src/hooks/useConnectStripeAccount.js
> +      throw new Error();
I can return as is state instead, but fwiw, throwing error is what they demonstrate in official docs: https://reactjs.org/docs/hooks-reference.html#usereducer

2022-10-11 16:09 UTC, benjaminEwhite commented on spa/stripe-example.sjon
> +{
a8985b7234d0a

2022-10-12 14:52 UTC, benjaminEwhite commented on spa/src/hooks/useConnectStripeAccount.js
> +      throw new Error();
e91669a56

2022-10-12 14:52 UTC, benjaminEwhite commented on spa/src/hooks/useConnectStripeAccount.js
> +          alert.error(GENERIC_ERROR);
e91669a56

2022-10-12 15:10 UTC, benjaminEwhite commented on spa/src/hooks/useConnectStripeAccount.js
> -import { useEffect, useState } from 'react';
056d9aa2e2473b3

2022-10-17 17:39 UTC, njharman approved these changes
Just reviewed Python and really just the code. It's little too much to follow (in detail) the SPA/API flow/interactions. But reading PR and ticket. Nothing looked "crazy" or "wrong".

Good test coverage.

2022-10-17 17:39 UTC, njharman commented on apps/organizations/views.py
>          return f"{settings.STRIPE_ACCOUNT_LINK_RETURN_BASE_URL}{reversed}"
> STRIPE_ACCOUNT_LINK_RETURN_BASE_URL = os.getenv("STRIPE_ACCOUNT_LINK_RETURN_BASE_URL", None)

Are we assuming/hoping that this S...BASE_URL will be defined and not None? Then
1) I don't like that
2) It should be documented that, that has to be defined in PR "prod changes" and change settings to fail if not.

Or, rework so there's a "working" default.

2022-10-17 17:39 UTC, njharman commented on apps/organizations/views.py
> -    """
None of this docstring was applicable? Couldn't be refactored to become handle_stripe_account_link's doc string  :sadpanda

2022-10-17 17:39 UTC, njharman commented on apps/organizations/views.py
> +            payment_provider.stripe_verified = True
Does this have any implications/interactions with the Apple Payment bug DEV-2468?

2022-10-18 00:26 UTC, benjaminEwhite commented on apps/organizations/views.py
> -    """
Added a new doc string giving an overview of new flow: d1abf1c7f05

2022-10-18 00:29 UTC, benjaminEwhite commented on apps/organizations/views.py
> +            payment_provider.stripe_verified = True
Yes, good point. It will.  That PR should be merged into main ahead of this one, and we can deal with merge conflicts when we merge main back into this one. This is exactly where the domain registration will happen.

2022-10-18 00:41 UTC, benjaminEwhite commented on apps/organizations/views.py
>          return f"{settings.STRIPE_ACCOUNT_LINK_RETURN_BASE_URL}{reversed}"
As documented in [settings.base.py](https://github.com/newsrevenuehub/rev-engine/blob/main/revengine/settings/base.py#L525-L530), this setting is meant to facilitate the full round-trip user experience while running the app in a local dev environment. We actually want to avoid encouraging deployed environments from doing anything with this value. 

In deployed environments, we want the base case, which is `request.build_absolute_uri(reversed)`.

2022-10-18 21:40 UTC, njharman approved these changes

2022-10-20 14:46 UTC, nrh-cklimas approved these changes

2022-10-22 01:34 UTC, x110dc approved these changes
Server-side code LGTM.

2022-10-31 21:28 UTC, merged