DEV-2252: Update layout to match design
newsrevenuehub/rev-engine pull request #747
Opened 2022-10-10 21:27 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
Fix design mismatch between implementation and figma for Profile Steps modal

#### Why are we doing this? How does it help us?
To make design consistent accross all pages and modals

#### How should this be manually tested? Please include detailed step-by-step instructions.
- Create new account
- Ask for verification email and verify account
- Go back to application (should be `/setup/` page)
- Check that modal design matches figma

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
Slightly. Don't think requires doc changes

#### Have automated unit tests been added? If not, why?
n/a

#### How should this change be communicated to end users?
n/a

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-2555

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
Parent ticket: https://news-revenue-hub.atlassian.net/browse/DEV-2107

2022-10-11 13:52 UTC, nrh-cklimas requested changes
Changes look good in the review app, just have two comments on base component changes.

2022-10-11 13:52 UTC, nrh-cklimas commented on spa/src/components/account/Profile/InfoTooltip.test.js
> +  it('toogle the tooltip if the button is clicked repeatedly', async () => {
```suggestion
  it('toggles the tooltip if the button is clicked repeatedly', async () => {
```

2022-10-11 13:52 UTC, nrh-cklimas commented on spa/src/components/base/Tooltip/Tooltip.js
> -  ...MuiTooltip.propTypes,
Why remove this? My thought here was to give consumers an escape hatch to use MUI directly for special cases.

2022-10-11 13:52 UTC, nrh-cklimas commented on spa/src/components/base/Tooltip/Tooltip.js
> +    margin-top: 6px;
I don't think this will play well with different tooltip placements. If what we want is to ensure that tooltip is 6px away from its anchor, I think we want something like `PopperProps={{ modifiers: [{ name: 'offset', options: { offset: [0, 6]  }]  }}` on `MuiTooltip` (I didn't test this, though).

Docs:
- https://v4.mui.com/api/popper/
- https://popper.js.org/docs/v2/modifiers/offset/

2022-10-11 14:15 UTC, GuiMend commented on spa/src/components/base/Tooltip/Tooltip.js
> +    margin-top: 6px;
Btw: I tried using the `popperprops` but didn't get the expected results and didn't want to spend too much time figuring out the props if the margin worked in all cases

2022-10-11 17:28 UTC, GuiMend commented on spa/src/components/base/Tooltip/Tooltip.js
> +    margin-top: 6px;
I like that Chris, I've added your suggestion and updates storybook to so that the icon tooltip also shows the correct placement

2022-10-15 19:49 UTC, x110dc approved these changes

2022-10-18 19:44 UTC, merged