DEV-2252: Update layout to match design
newsrevenuehub/rev-engine pull request #748
Opened 2022-10-10 21:56 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
Updates stripe connection toast to match design in figma

#### Why are we doing this? How does it help us?
Make toast's design consistent and improve readibility (was really hard to read with small sizing and font color)

#### How should this be manually tested? Please include detailed step-by-step instructions.
- Log into an account that doesn't have stripe connected or create a new account
- Check that stripe toast that appears in the top right corner matches design from figma

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
Slightly

#### Have automated unit tests been added? If not, why?
N/a

#### How should this change be communicated to end users?
n/a

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-2557

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
Parent ticket: https://news-revenue-hub.atlassian.net/browse/DEV-2107

2022-10-11 13:57 UTC, nrh-cklimas requested changes
Looks good to me, just noticed a typo.

2022-10-11 13:57 UTC, nrh-cklimas commented on spa/src/components/account/Profile/InfoTooltip.test.js
> +  it('toogle the tooltip if the button is clicked repeatedly', async () => {
```suggestion
  it('toggles the tooltip if the button is clicked repeatedly', async () => {
```

2022-10-11 15:35 UTC, nrh-cklimas approved these changes

2022-10-15 20:04 UTC, x110dc approved these changes

2022-10-18 18:54 UTC, merged