DEV-2596: Restore /:pageSlug/thank-you/ route
newsrevenuehub/rev-engine pull request #751
Opened 2022-10-11 19:18 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

This fixes a bug where requests to `/:donationSlug/thank-you/` were not getting routed properly.

This also adds TypeScript support to the project 🌈 and adds unit tests for the donation page router.

#### Why are we doing this? How does it help us?

Fixes a very confusing situation for contributors where donating from a page with a slug didn't show a confirmation page.

#### How should this be manually tested? Please include detailed step-by-step instructions.

Repeat the steps below for both a page with a donation slug (like `/donate/`) and one using the default donation page (at the top-level domain, no subdirectories).

1. Go to the donation page.
2. Complete a test donation.
3. Confirm that after doing so, you see a thank you page. When you start at `/donate/`, the browser address bar should be `/donate/thank-you/`. When starting at the top-level domain, the browser address bar should be `/thank-you/`.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No.

#### Have automated unit tests been added? If not, why?

Yes.

#### How should this change be communicated to end users?

n/a

#### Are there any smells or added technical debt to note?

No.

#### Has this been documented? If so, where?

No.

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-2596

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No.

2022-10-11 19:46 UTC, nrh-cklimas commented on spa/src/components/DonationPageRouter.tsx
> +                path={[join(ROUTES.DONATION_PAGE_SLUG, ROUTES.THANK_YOU_SLUG), ROUTES.THANK_YOU_SLUG]}
This is the fix for the bug--everything else is tests and TypeScript setup.

2022-10-11 19:46 UTC, nrh-cklimas commented on spa/src/components/DonationPageRouter.test.tsx
> +  it('displays a tracked GenericThankYou at /thank-you/', async () => {
I'm hardcoding these paths in the tests to avoid a situation where slashes change in our route config, and we accidentally route to URLs like `/donate//thank-you` but tests continue to pass.

2022-10-11 19:51 UTC, GuiMend approved these changes
Really nice 👍

2022-10-12 19:20 UTC, nrh-cklimas commented on spa/package.json
> +    "build:for-heroku": "INLINE_RUNTIME_CHUNK=false NODE_ENV=production craco --max_old_space_size=2560 --optimize_for_size build",
This came from a combo of https://devcenter.heroku.com/articles/node-memory-use#heroku-memory-limits (describing what CLI switches to use) and pages like https://stackoverflow.com/questions/59205530/heroku-server-crashes-with-javascript-heap-out-of-memory-when-deploying-react which were suggesting 2560 as a limit.

This does potentially cause the build to be slower than it could be because Node is conserving memory.

2022-10-13 02:20 UTC, x110dc requested changes

2022-10-13 02:20 UTC, x110dc commented on Dockerfile
> +
This same Dockerfile/image gets deployed to production. So, I'd rather not have something name "for Heroku" that will run there (since I think it will be confusing for ppl that look at this later). I'm okay with a separate Dockerfile for Heroku (and may want to do that anyway for other performance reasons). 

For now maybe just rename it ":low-memory" or similar?

2022-10-13 02:20 UTC, x110dc commented on spa/package.json
> +    "build:for-heroku": "INLINE_RUNTIME_CHUNK=false NODE_ENV=production craco --max_old_space_size=2560 --optimize_for_size build",
👍

2022-10-13 02:20 UTC, x110dc commented on spa/src/components/DonationPageRouter.test.tsx
> +  it('displays a tracked GenericThankYou at /thank-you/', async () => {
I think this comment would be great as a comment in the actual code.

2022-10-13 13:13 UTC, nrh-cklimas commented on Dockerfile
> +
Makes sense. Updated in 50ddab3a3acf88376dd2bbb9bf535f69fe8e0495

2022-10-13 13:15 UTC, nrh-cklimas commented on spa/src/components/DonationPageRouter.test.tsx
> +  it('displays a tracked GenericThankYou at /thank-you/', async () => {
👍 Added in 7b52bb9916a3cf270d1ec7f19f81388422f2b2be

2022-10-13 20:05 UTC, x110dc approved these changes

2022-10-13 20:06 UTC, merged