DEV 2650 | style not appearing after clicking new style button reload
newsrevenuehub/rev-engine pull request #759
Opened 2022-10-14 21:05 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

Fixes a bug revealed in QA of DEV-1865.  Base for this PR is DEV-1863-restrict-page-creation-via-org-plan, which itself is queued up to be merged into main.

#### What's this PR do?

Ensures that new styles appear in Customize page list view after creation

- Adds a new hook `useStyleList` that follows pattern from `usePageList` and uses that hook in place of pre-existing AJAX functionality to retrieve styles
- After a style is created, invalidates the styles list query, causing them to be re-retrieved.

#### Why are we doing this? How does it help us?

Fixes bug and allows us to release DEV-1863 and DEV-1865

#### How should this be manually tested? Please include detailed step-by-step instructions.

Create a style in review app and you should immediately see it reflected in the customize list view without refreshing.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No

#### Have automated unit tests been added? If not, why?

yes

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

N/A

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-2650

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

As noted above, parent PR of DEV-1863 into main will need to be merged.

2022-10-17 14:18 UTC, nrh-cklimas requested changes
Some thoughts on the new hook, but overall I like the approach.

2022-10-17 14:18 UTC, nrh-cklimas commented on spa/src/hooks/useStyleList.ts
> +    retry: (failureCount, error:any) => {
Do we need a type on `error` at all? I'd expect that react-query would give us the function signature.

If we do need to type it ourselves, I'd think `Error` would be more appropriate... as much as possible, we want to avoid usage of `any`.

2022-10-17 14:18 UTC, nrh-cklimas commented on spa/src/components/content/Customize.js
> +          onStylesUpdated={() => queryClient.invalidateQueries('styles')}
I still think that `useStyleList` should encapsulate this functionality in some way. The scenario I see is one day we decide to call the query something other than `styles`, and then existing code breaks silently.

2022-10-17 14:18 UTC, nrh-cklimas commented on spa/src/hooks/useStyleList.ts
> +import { useQuery } from '@tanstack/react-query';
We should have Jest tests on this hook. I don't think they need to be complex--could test that they make the correct call to react-query, and that they force a re-auth if the fetch fails with an authentication error.

2022-10-18 01:32 UTC, benjaminEwhite commented on spa/src/hooks/useStyleList.ts
> +    retry: (failureCount, error:any) => {
I get TS2571 without type. Updating to `:Error`.

b3e5c15259

2022-10-20 13:16 UTC, nrh-cklimas commented on spa/src/hooks/useStyleList.test.tsx
> +    console.log(result.current.styles);
Leftover from dev, I think

2022-10-20 14:19 UTC, benjaminEwhite commented on spa/src/hooks/useStyleList.test.tsx
> +      expect(mockInvalidateQueries).toHaveBeenCalledWith(['styles']);
ce03d21a

2022-10-20 14:20 UTC, benjaminEwhite commented on spa/src/hooks/useStyleList.test.tsx
> +    console.log(result.current.styles);
1978b8b795

2022-10-20 15:29 UTC, nrh-cklimas approved these changes

2022-10-24 03:24 UTC, x110dc approved these changes

2022-10-24 03:26 UTC, merged