DEV-2569 Sentry Performance Monitoring
newsrevenuehub/rev-engine pull request #764
Opened 2022-10-17 18:09 UTC by njharman

Already is performance metrics (for HTTP type stuff). Automatic withe Django integration. We should enable other automatic metrics and evaluate if we need to create any custom "tracing"/metrics.

#### What's this PR do?
Add integrations for Celery, Redis, SQLAlchemy. Which should start automatically recording metrics including performance.

Set sampling rate to 1.0 (100%). This is temporary to aide in testing and analysis of what the default/automatic metrics are and if they meet our needs.

#### Why are we doing this? How does it help us?
Need to know how site is performing!

#### How should this be manually tested? Please include detailed step-by-step instructions.
Do stuff with API/SPA
Look at matching ENVIRONMENT in sentry io https://sentry.io/organizations/news-revenue-hub/performance/
Verify database (SQLAlchemy),  and redis  performance metrics are logged.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
No

#### Have automated unit tests been added? If not, why?
N/A this commit is only configuration of 3rd party Sentry / sentry.io logging.

#### How should this change be communicated to end users?
N/A

#### Are there any smells or added technical debt to note?
Not sure exactly how we run celery in production. If we run using something that does not "load" the django settings, then need to add similar celeryintegration sentry config to whatever runs celery workers. 

#### Has this been documented? If so, where?
No

#### What are the relevant tickets? Add a link to any relevant ones.
[DEV-2569]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
I do not believe so

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

[DEV-2683]

Also, poetry.lock includes SQLAlchemy even though we don't use it.  It also seems to have a lot of 3rd party packages we may not use. Could maybe use a review.

> looks like it’s part of Stripe SDK, and specifically used in testing: [Search · sqlalchemy · slackapi/python-slack-sdk](https://github.com/slackapi/python-slack-sdk/search?q=sqlalchemy)

[DEV-2569]: https://news-revenue-hub.atlassian.net/browse/DEV-2569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-10-18 00:50 UTC, benjaminEwhite requested changes
One small request...

2022-10-18 00:50 UTC, benjaminEwhite commented on revengine/settings/deploy.py
> +        traces_sample_rate=1.0,  # TODO: After testing will want to reduce this to less than 100% sampling rate.
This should have a JIRA todo.

2022-10-18 21:45 UTC, njharman commented on revengine/settings/deploy.py
> +        traces_sample_rate=1.0,  # TODO: After testing will want to reduce this to less than 100% sampling rate.
DEV-2683

2022-10-22 01:56 UTC, x110dc approved these changes

2022-10-22 02:03 UTC, merged