DEV-2300: Global Header Nav improvements
newsrevenuehub/rev-engine pull request #766
Opened 2022-10-18 13:26 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
Improves Global Header Naviagiton. Adds NRH logo, back button and page name to header and removes back button from sidebar. Back button logic remains the same, if no edits were made return imediatelly, if changes were made show confirmation modal.

#### Why are we doing this? How does it help us?
Improves UI/UX of edit page navigation and updates it to the curent designs.

#### How should this be manually tested? Please include detailed step-by-step instructions.
- Log in
- Go to any page edit screen
- Check that the top header matches design and usability

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
Yes

#### Have automated unit tests been added? If not, why?
Yes

#### How should this change be communicated to end users?
Header of edit page is now showing page name and back button.

#### Are there any smells or added technical debt to note?
No

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-2300

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2022-10-18 14:57 UTC, nrh-cklimas requested changes
Review app looks good to me, just had some code style suggestions.

2022-10-18 14:57 UTC, nrh-cklimas commented on spa/src/components/dashboard/topbar/DashboardTopbar.js
> +            <S.Logo src={logo} alt="NRH Logo" />
How about `News Revenue Engine` as alt text on this and the other images, since that's the text content in the image?

2022-10-18 14:57 UTC, nrh-cklimas commented on spa/src/components/dashboard/topbar/DashboardTopbar.js
> +                  <BackButton to={CONTENT_SLUG} style={{ fill: 'white' }} data-testid="back" aria-label="Exit" />
If you're setting a label here, I think it should be queryable in RTL on that--no need for a test id.

2022-10-18 14:57 UTC, nrh-cklimas commented on spa/src/components/dashboard/topbar/DashboardTopbar.test.js
> +    render(<DashboardTopbar isEditPage={true} page={page} />);
```suggestion
    render(<DashboardTopbar isEditPage page={page} />);
```

2022-10-18 14:57 UTC, nrh-cklimas commented on spa/src/components/dashboard/topbar/DashboardTopbar.test.js
> +    expect(screen.queryByTestId('modal-back')).toBeNull();
```suggestion
    expect(screen.queryByTestId('modal-back')).not.toBeInTheDocument();
```

2022-10-18 14:57 UTC, nrh-cklimas commented on spa/src/components/dashboard/topbar/DashboardTopbar.test.js
> +  it('should show NRH logo if isEditPage = true', () => {
I'm unsure about this test. Shouldn't the logo always be present?

2022-10-18 15:20 UTC, GuiMend commented on spa/src/components/dashboard/topbar/DashboardTopbar.js
> +                  <BackButton to={CONTENT_SLUG} style={{ fill: 'white' }} data-testid="back" aria-label="Exit" />
I do need the data-testid because there are 2 "Exit" button labels (added the label in the other one) and so I need a way to differentiate them on the test. Do you have a suggestion of doing it in another manner?

2022-10-18 19:18 UTC, nrh-cklimas commented on spa/src/components/dashboard/topbar/DashboardTopbar.js
> +                  <BackButton to={CONTENT_SLUG} style={{ fill: 'white' }} data-testid="back" aria-label="Exit" />
Ah... I see. I think then yeah, testid is the way to go.

2022-10-18 21:10 UTC, nrh-cklimas approved these changes

2022-10-21 19:42 UTC, nrh-cklimas commented on spa/src/components/pageEditor/PageEditor.js
> +import { Tooltip } from 'components/base';
🎉

2022-10-21 19:42 UTC, nrh-cklimas approved these changes

2022-10-21 19:48 UTC, nrh-cklimas commented
I am not sure about the Cypress errors.

```
`<li data-testid="styles-tab" class="sc-cBOWjd wLyqn">Styles</li>`

is being covered by another element:

`<div class="sc-fXynhf tHbwc">...</div>`
```

Looking at the screenshots (click Details on the check with the Cypress icon--I didn't realize this at first, at least), I think the failures are because of the extraneous Django tags in the HTML source + the style change for the top toolbar. I feel ambivalent about how to address this. If we can figure out a styling solution that can handle the extra space at the top when running the SPA alone, that's ideal... but in a pinch we can use the workaround the Cypress suggests, to put `{force: true }` on the clicks.

2022-10-24 19:31 UTC, GuiMend commented
> I am not sure about the Cypress errors.
> 
> ```
> `<li data-testid="styles-tab" class="sc-cBOWjd wLyqn">Styles</li>`
> 
> is being covered by another element:
> 
> `<div class="sc-fXynhf tHbwc">...</div>`
> ```
> 
> Looking at the screenshots (click Details on the check with the Cypress icon--I didn't realize this at first, at least), I think the failures are because of the extraneous Django tags in the HTML source + the style change for the top toolbar. I feel ambivalent about how to address this. If we can figure out a styling solution that can handle the extra space at the top when running the SPA alone, that's ideal... but in a pinch we can use the workaround the Cypress suggests, to put `{force: true }` on the clicks.

An "easy" bot not ideal solution would be to leave enough space for the tags, but then the design doesn't match what it should be. I think fixing with `{force: true }` would be ok in this instance because we know the tags only mess up local env

2022-10-28 16:46 UTC, x110dc approved these changes

2022-10-28 17:19 UTC, merged