DEV-2534: ignore test contributions in live mode and vice versa - DRAFT
newsrevenuehub/rev-engine pull request #767
Opened 2022-10-19 09:12 UTC by leo-dcfa

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2022-11-01 21:19 UTC, x110dc requested changes
One small change requested.

2022-11-01 21:19 UTC, x110dc commented on apps/contributions/webhooks.py
> +from revengine.settings.base import STRIPE_LIVE_MODE
This is the way to use settings in Django: https://docs.djangoproject.com/en/4.1/topics/settings/#using-settings-in-python-code

2022-11-01 22:14 UTC, leo-dcfa commented on apps/contributions/webhooks.py
> +from revengine.settings.base import STRIPE_LIVE_MODE
done

2022-11-03 19:44 UTC, x110dc approved these changes

2022-11-03 19:46 UTC, merged