DEV-2568: Config Sentry performance monitoring
newsrevenuehub/rev-engine pull request #769
Opened 2022-10-20 13:31 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
Configures Sentry performance monitoring + removes some code debt regarding routing setup

#### Why are we doing this? How does it help us?
So that we have better metrics regarding frontend performance and monitor if something goes wrong.

#### How should this be manually tested? Please include detailed step-by-step instructions.
Not sure

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
no

#### Have automated unit tests been added? If not, why?
n/a

#### How should this change be communicated to end users?
n/a

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-2568

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2022-10-24 13:58 UTC, nrh-cklimas requested changes
Same as Daniel, I don't see any data there for the review app--I think this is because useSentry looks for an environment variable named `SENTRY_ENABLE_FRONTEND`, and we're not doing that in our builds. I think that also means that the question about environment changes in the PR desc needs to update to include that.

I think first thing here is to get the env variable set on the review app so we can verify that we're getting data, and then from there, improve test coverage.

2022-10-24 13:58 UTC, nrh-cklimas commented on spa/src/components/routes/RouterSetup.js
> +import React from 'react';
```suggestion
import { Suspense } from 'react';
```
(since that's our usual pattern)

2022-10-24 13:58 UTC, nrh-cklimas commented on spa/src/components/routes/RouterSetup.js
> +import React from 'react';
Same thoughts as about the new hook--could this be a TSX file, and let's put unit tests on this. We don't need to test all the functionality of these components, just that this component wraps with the components we expect. An approach would be to mock the imported components with code like:

```tsx
jest.mock('components/errors/ChunkErrorBoundary', () => ({ children }) =>
  <div data-testid="mock-error-boundary>{children}</div>
);
```

And then from there, expect that these test ids are in the document as well as children.

2022-10-24 13:58 UTC, nrh-cklimas commented on spa/src/components/routes/RouterSetup.js
> +const RouterSetup = ({ children }) => (
I like standardizing our routing in this component a lot.

2022-10-25 19:19 UTC, GuiMend commented on spa/src/hooks/useSentry.js
Thanks for helping with the tests. They were commited [bbd80d4](https://github.com/newsrevenuehub/rev-engine/pull/769/commits/bbd80d43c0d98b7197e73593012aa0e45bb93f05)

2022-10-25 19:30 UTC, nrh-cklimas commented on spa/src/hooks/useSentry.ts
> + * Typically, just loading sentry at build time is sufficient.
```suggestion
 * Typically, just loading sentry at load time is sufficient.
```
I think that's what you mean here?

2022-10-25 20:13 UTC, nrh-cklimas commented on spa/src/hooks/useSentry.ts
> +const history = createBrowserHistory();
I think this is why we're still not seeing any info in Sentry on the review app (I tried clicking around after the most recent changes deployed). I _think_ what might work is to pull history out of `useHistory()` so that it connects to the history we are actually using in the router.

I think this means that the hook will need to be called by RouterSetup now, not App, so useHistory() will see the history the router has.

2022-10-27 20:39 UTC, GuiMend commented on spa/src/hooks/useSentry.ts
> +const history = createBrowserHistory();
I've tried changing the history object to `useHistory`. Let's see if anything changes

2022-10-28 17:16 UTC, nrh-cklimas commented on spa/src/hooks/useSentry.ts
> +const history = createBrowserHistory();
I get a white page on the review app now with a console error, I think because `useHistory()` is still in App, and it doesn't have a history to access. It looks like this doesn't fail locally, maybe because Sentry won't try to initialize on localhost? So I think you'll have to test in the review app to be sure it works.

2022-10-28 19:19 UTC, GuiMend commented on spa/src/hooks/useSentry.ts
> +const history = createBrowserHistory();
think now it's solved

2022-10-31 21:12 UTC, nrh-cklimas approved these changes

2022-11-04 16:36 UTC, x110dc approved these changes

2022-11-04 16:37 UTC, merged