Dev 2694 fix pay fees metadata
newsrevenuehub/rev-engine pull request #772
Opened 2022-10-21 19:14 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

Fixes a bug with the contribution page where two things were not accurately recorded:

- Whether the user paid fees
- The original amount the user chose to contribute (e.g. before fees)

I converted the underlying functions to TypeScript and expanded test coverage on these files.

#### Why are we doing this? How does it help us?

Gives us accurate tracking of contributions.

#### How should this be manually tested? Please include detailed step-by-step instructions.

To

1. Make a test contribution while choosing to pay fees.
2. Look at the contribution in Stripe and check that the metadata shows that the `agreed_to_pay_fees` field is true.
3. Confirm the Stripe metadata also shows that the `donor_selected_amount` field shows the amount you chose to contribute in step 1 minus fees.
4. Make a test contribution while not choosing to pay fees.
5. Repeat step 2, except this time Stripe should show the metadata `agreed_to_pay_fees` is false and `donor_selected_amount` shows the correct number.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No.

#### Have automated unit tests been added? If not, why?

I added extra Cypress tests for paying/not paying fees to check that the right `agreed_to_pay_fees` property is being sent.

I also added expanded unit tests on the functions that control that submission.

#### How should this change be communicated to end users?

n/a

#### Are there any smells or added technical debt to note?

n/a I think?

#### Has this been documented? If so, where?

No.

#### What are the relevant tickets? Add a link to any relevant ones.

- https://news-revenue-hub.atlassian.net/browse/DEV-2694
- https://news-revenue-hub.atlassian.net/browse/DEV-2699

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

https://news-revenue-hub.atlassian.net/browse/DEV-2698

2022-10-21 19:15 UTC, nrh-cklimas commented on spa/tsconfig.json
> +    "target": "es2015",
Reason for this is to allow `for (const key of object)`.

2022-10-21 19:15 UTC, nrh-cklimas commented on spa/src/utilities/calculateStripeFee.ts
> +  if (isNaN(amountInt) || amountInt < 0) {
We didn't have a check for negative numbers previously.

2022-10-21 19:16 UTC, nrh-cklimas commented on spa/src/components/paymentProviders/stripe/stripeFns.ts
> +    // TODO handle this better?
I'm not sure what we should do in this case.

2022-10-21 19:18 UTC, nrh-cklimas commented on spa/src/components/paymentProviders/stripe/stripeFns.ts
> +    billing_details.name = `${data.first_name ?? ''} ${data.last_name ?? ''}`.trim();
This fixes an incidental bug I noticed, that if only first or last name was set we were setting names like `John undefined`.

2022-10-24 19:24 UTC, GuiMend commented on spa/src/components/donationPage/DonationPage.js
> +  console.log({ paymentData });
COnsole log got commited

2022-10-24 19:24 UTC, GuiMend commented on spa/src/components/paymentProviders/stripe/stripeFns.ts
> +    // TODO handle this better?
You mean when "amount" is not a number? Couldn't we just force `amount: number` and just make sure when we cann the function we conver the value to number?

2022-10-24 19:24 UTC, GuiMend commented on spa/src/components/paymentProviders/stripe/stripeFns.ts
> +    }).filter(([, v]) => [undefined, null].includes(v as any))
Can we avoid using `any` here?

2022-10-24 19:40 UTC, nrh-cklimas commented on spa/src/components/paymentProviders/stripe/stripeFns.ts
> +    // TODO handle this better?
The way amount works right now in the contribution form is confusing. It is usually a number, but if the user hasn't chosen a contribution amount or typed anything into the freeform field, it's the empty string `''`. `calculateStripeFee('')` is `null`. A confusing aspect is, `calculateStripeFee(0)` returns around 30 cents (depending on nonprofit status).

The logic here is if the fee is null, don't do anything with that. But overall I feel like we could be doing better here, but I don't know exactly how to approach it without redoing everything.

2022-10-24 19:41 UTC, nrh-cklimas commented on spa/src/components/donationPage/DonationPage.js
> +  console.log({ paymentData });
Thanks for catching this--fixed in 60bc2f3dda74e87601c8564429e5e2fc05f34d65

2022-10-24 19:48 UTC, nrh-cklimas commented on spa/src/components/paymentProviders/stripe/stripeFns.ts
> +    }).filter(([, v]) => [undefined, null].includes(v as any))
I don't think so, but there could be a trick I don't know.

The reason why a cast is needed is because TypeScript correctly says "these types are specified as never being null or undefined, those will never be in `[undefined, null]`. So we need the cast to bypass the type check. I don't like removing the check until we have more code in TypeScript and can trust it to flag these issues in all cases.

2022-10-25 12:30 UTC, GuiMend approved these changes
👍

2022-10-26 13:55 UTC, benjaminEwhite requested changes
Looks good overall. A couple of suggestions (which you may choose to reject) re: tests. And one `.then` that we might not need.

2022-10-26 13:55 UTC, benjaminEwhite commented on spa/cypress/e2e/01-donationPage.cy.js
> +    // The donation page fixture has fees paid by default, but make sure that's true.
Should change this to "contribution page" instead of "donation page", to align with [DEV-1446](https://news-revenue-hub.atlassian.net/browse/DEV-1446).

FWIW, was going to leave change as suggestion, but for some reason, that button is not available in this PR...

2022-10-26 13:55 UTC, benjaminEwhite commented on spa/cypress/e2e/01-donationPage.cy.js
> +    cy.intercept({ method: 'GET', url: 'https://api.stripe.com/**' }, { statusCode: 200 });
There's a pre-existing Cypress command you could use here (refactoring it to also intercept api.stripe.com/**). See [here](https://github.com/newsrevenuehub/rev-engine/blob/DEV-2694-fix-pay-fees-metadata/spa/cypress/support/commands.js#L101).

2022-10-26 13:55 UTC, benjaminEwhite commented on spa/cypress/e2e/01-donationPage.cy.js
> +  specify('one-time contribution, paying fees', () => {
Not a big deal, but think you could parametrize the `pay fees` boolean, and compress the two one-time contribution tests into a single block. 

https://dev.to/tinesoft/be-smart-write-parameterized-tests-with-jest-3eab

2022-10-26 13:55 UTC, benjaminEwhite commented on spa/cypress/e2e/01-donationPage.cy.js
> +  specify('recurring contribution, paying fees', () => {
Could also parametrize the two recurring contribution tests.

I suppose you could even combine all 4 contribution tests here into a single parametrized test, but that would require a bit of overhead to decide which fixture to use, etc.

2022-10-26 13:55 UTC, benjaminEwhite commented on spa/cypress/e2e/03-donationPageList.cy.js
> +        cy.wait('@listPages').then(() => cy.get('button[aria-label="New Page"]').click());
Why the `.then` here? As I understand it, simply calling `cy.wait` as in original should cause the test not to move on until list pages has run.

2022-10-26 17:25 UTC, nrh-cklimas commented on spa/cypress/e2e/03-donationPageList.cy.js
> +        cy.wait('@listPages').then(() => cy.get('button[aria-label="New Page"]').click());
I was troubleshooting this with Gui. What we both saw is that Cypress would click New Page immediately, before the rest of the pages loaded, and would try to create a page numbered 1, when it should be creating a page numbered 2 (because 1 already exists). Annoyingly, this only seems to happen in CI-- Gui thought it was because CI is slower than running locally.

I see https://github.com/cypress-io/cypress-documentation/issues/1508 says you shouldn't need to chain on it, but if so, I don't understand why we're seeing this test fail. I think a lot of is it I don't know Cypress very well.

2022-10-26 18:21 UTC, nrh-cklimas commented on spa/cypress/e2e/01-donationPage.cy.js
> +    cy.intercept({ method: 'GET', url: 'https://api.stripe.com/**' }, { statusCode: 200 });
:+1: Updated in 58f5d1361dda4712589f6fb36243360f5f6ac7a5

2022-10-26 18:21 UTC, nrh-cklimas commented on spa/cypress/e2e/01-donationPage.cy.js
> +  specify('one-time contribution, paying fees', () => {
I liked this idea a lot. I did that also in 58f5d1361dda4712589f6fb36243360f5f6ac7a5

2022-10-26 18:22 UTC, nrh-cklimas commented on spa/cypress/e2e/01-donationPage.cy.js
> +  specify('recurring contribution, paying fees', () => {
Same thing, 58f5d1361dda4712589f6fb36243360f5f6ac7a5--I looked at trying to generate all four but it seemed a little hairy to make sure the logic for all was correct.

2022-10-26 20:38 UTC, nrh-cklimas commented on spa/cypress/e2e/03-donationPageList.cy.js
> +        cy.wait('@listPages').then(() => cy.get('button[aria-label="New Page"]').click());
Take a look: 4fcccdc45c2e15093782775f725f04c96e50b2f2

2022-10-27 13:16 UTC, benjaminEwhite approved these changes
LGTM

2022-10-28 18:54 UTC, x110dc approved these changes

2022-10-28 19:04 UTC, merged