Dev 2475 resend contributions receipt
newsrevenuehub/rev-engine pull request #788
Opened 2022-10-27 13:47 UTC by harsha09

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
Create an endpoint to email contribution.
The endpoint accepts contribution_id which is an integer.
Retrieves `PaymentIntent` and `Invoice` from `stripe` to populate `amount, interval, receipt_email_id and created_date`.

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2022-10-31 19:11 UTC, benjaminEwhite requested changes

2022-10-31 19:11 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        interval = payment_interval_from_stripe_invoice(invoice, ContributionInterval)
Why aren't we just using `contribution.interval`?

2022-10-31 19:11 UTC, benjaminEwhite commented on apps/contributions/views.py
> +@permission_classes([IsAuthenticated, HasRoleAssignment])
With these permission classes alone, it would be possible for an authenticated user with a role assignment to send email contributions for any contributor. We should be validating that the requesting user is the same user who created the underlying NRE contribution and related Stripe entities. Should also have tests that prove this new permission logic.

2022-10-31 19:11 UTC, benjaminEwhite commented on apps/contributions/views.py
> +    email_id = request.user.email
I think we should be confirming that the requesting user is the contributor for the requested contribution. Once we know that, we should send email to that user's address.

Given current permissions, it would be possible for a user to gain access to receipts they shouldn't be able to see: if they guess a contribution ID and that contribution, and if the payment_intent doesn't have `.receipt_email` defined, then the receipt will be sent to the requesting user, not the contributor email.

2022-11-01 09:39 UTC, harsha09 commented on apps/contributions/stripe_contributions_provider.py
> +        # [TODO]: logic being ambigious to be replaced by utils.payment_interval_from_stripe_invoice
I've added this comment to avoid code duplication and don't want to touch this particular code in this PR.
But, I've removed this as it's not required now, because I've modified to get interval from contribution.

2022-11-01 09:39 UTC, harsha09 commented on apps/contributions/views.py
> +
It'll return 500 status code but response is not JSON. I've modified it to return a JSON response.

2022-11-01 09:40 UTC, harsha09 commented on apps/contributions/views.py
> +        interval = payment_interval_from_stripe_invoice(invoice, ContributionInterval)
Yeah, that's a nice suggestion. I've modified it to get it from the Contribution object. I hope this will be fine @x110dc as we are anyhow getting contribution object.

2022-11-01 10:29 UTC, harsha09 commented on apps/contributions/utils.py
> +def convert_stripe_date_to_datetime(stripe_date):
Addressed using 48d0e2fcc12d4eb080b1091f91d756864562222a

2022-11-01 10:33 UTC, harsha09 commented on apps/contributions/views.py
> +    email_id = request.user.email
Will contributors will be able to login to the dashboard, they'll be able to view contributor portal with the magic token if I'm not wrong.
This API will be integrated into the frontend of contributor dashboard.
LMK if I'm wrong.

2022-11-01 16:40 UTC, harsha09 commented on apps/contributions/views.py
> +@permission_classes([IsAuthenticated, HasRoleAssignment])
As this API will be called from Contributions Dashboard, Contributors doesn't have access to it as they'll be routed to magic link url.
As per [DEV-1606], it'll be logically correct if the access is provided to RP Admin (Revenue Program Managers) where a particular contribution falls under his one of RPs.

2022-11-01 23:52 UTC, benjaminEwhite requested changes

2022-11-01 23:52 UTC, benjaminEwhite commented on apps/contributions/views.py
> +@permission_classes([IsAuthenticated, HasRoleAssignment])
There's nothing stopping someone from making requests to the API from somewhere other than contributions dashboard. For instance, if I sign up for a free account (as an org), I could be authenticated, and have a role assignment, and make a request to this endpoint and gain access to receipts that don't belong to me.

2022-11-01 23:52 UTC, benjaminEwhite commented on apps/contributions/views.py
> +    email_id = request.user.email
Ah, I see. So even if it's not contributors accessing this, the concern remains: we're not doing anything to ensure that the requesting user's org should have access to the requested contribution. We need to ensure that the requested contribution belongs to an RP that the requesting user has access to (via role assignment).

2022-11-04 11:15 UTC, harsha09 commented on apps/contributions/views.py
> +@permission_classes([IsAuthenticated, HasRoleAssignment])
I've created `IsRPAdmin` and `HasAccessToContribution` permissions and enforced them on the view.
I think this should solve the problem.

2022-11-04 11:16 UTC, harsha09 commented on apps/contributions/views.py
> +    email_id = request.user.email
I've created IsRPAdmin and HasAccessToContribution permissions and enforced them on the view.
I think this should solve the problem.

2022-11-04 17:51 UTC, benjaminEwhite requested changes

2022-11-04 17:51 UTC, benjaminEwhite commented on apps/api/permissions.py
> +            request.user.roleassignment.revenue_programs.filter(id=contribution.revenue_program.id).first() is not None
```suggestion
            request.user.roleassignment.revenue_programs.filter(id=contribution.revenue_program.id).exists()
```

2022-11-04 17:51 UTC, benjaminEwhite commented on apps/api/permissions.py
> +        return request.user.roleassignment.role_type == Roles.RP_ADMIN.value
We shouldn't be limiting to RPs. Our default user type is now an ORG_ADMIN (that's what people who go through self-onboarding get).

As long as we know that someone is authenticated, has a role assignment, and has access to the contribution by virtue of their role assignment, that should be enough.


FWIW, you can see [this custom validator ](https://github.com/newsrevenuehub/rev-engine/blob/main/apps/common/validators.py#L51)(which won't work here cause context if function-based view instead of class-based + serializer) which does something similar.

2022-11-04 17:51 UTC, benjaminEwhite commented on apps/contributions/tests/test_views.py
> +        assert response.status_code == 403
More relevant at the moment is when contribution is for another org (and user is org user)

2022-11-04 17:51 UTC, benjaminEwhite commented on apps/contributions/tests/test_views.py
> +    def test_when_logged_user_is_not_revenue_program_manager(self):
See above comment. We shouldn't restrict to rp role type.

2022-11-04 17:51 UTC, benjaminEwhite commented on apps/contributions/tests/test_views.py
> +        self.client.force_authenticate(user=self.rp_user)
ditto re: rp_user

2022-11-04 17:51 UTC, benjaminEwhite commented on apps/contributions/views.py
> +@permission_classes([IsAuthenticated, HasRoleAssignment, IsRPAdmin, HasAccessToContribution])
Ditto re: `IsRPAdmin`

2022-11-07 15:42 UTC, harsha09 commented on apps/api/permissions.py
> +    Check whether the user is an RP Admin and the contribution belongs to him.
Have modified to `Check whether the user has permission to access contribution via roleassignment.`

2022-11-07 15:44 UTC, harsha09 commented on apps/api/permissions.py
> +        return request.user.roleassignment.role_type == Roles.RP_ADMIN.value
Modified the permissions for `ORG_ADMIN` and `RP_ADMIN` who has access to the contribution will be able to send the receipt.

2022-11-07 15:44 UTC, harsha09 commented on apps/api/permissions.py
> +            request.user.roleassignment.revenue_programs.filter(id=contribution.revenue_program.id).first() is not None
This is not needed for the modified code.

2022-11-07 15:45 UTC, harsha09 commented on apps/contributions/tests/test_views.py
> +        assert response.status_code == 403
Added testcase for org user as well

2022-11-07 15:46 UTC, harsha09 commented on apps/contributions/tests/test_views.py
> +    def test_when_logged_user_is_not_revenue_program_manager(self):
This will be addressed by above mentioned comments.

2022-11-07 15:46 UTC, harsha09 commented on apps/contributions/views.py
> +@permission_classes([IsAuthenticated, HasRoleAssignment, IsRPAdmin, HasAccessToContribution])
This will be addressed by above comments.

2022-11-07 15:46 UTC, harsha09 commented on apps/contributions/tests/test_views.py
> +        self.client.force_authenticate(user=self.rp_user)
This will be addressed by above comments.

2022-11-07 16:46 UTC, benjaminEwhite commented on apps/contributions/tests/test_views.py
> +        contribution = [x for x in Contribution.objects.all() if x.status != ContributionStatus.PAID][0]
```suggestion
        contribution =  Contribution.objects.filter(status=ContributionStatus.PAID).first()
```

2024-03-08 18:23 UTC, closed without merging