DEV-1968: Avatar Menu
newsrevenuehub/rev-engine pull request #789
Opened 2022-10-27 16:24 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
Creates Avatar Menu component and add it to the top header/nav. Avatar Menu shows the user's initials and when clicked pop up several additional settings & options for the user (Example: sign out, FAQ link)

#### Why are we doing this? How does it help us?
Makes it easier for the user to understand what account they are logged in, and simplifies user interaction with settings.

#### How should this be manually tested? Please include detailed step-by-step instructions.
Design
- Access storybook `Components > AvatarMenu` and check that the design matches all use-cases and menu options.
Usability
- Access the dashboard with a logged in user
- Make sure avatar menu shows with the user's initials (probably will use the email's first letter)
- Click FAQ link and open in new tab
- Click logout and make sure user logs out

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
yes

#### Have automated unit tests been added? If not, why?
yes

#### How should this change be communicated to end users?
User menu now added with some functionality and will be added more in the future.

#### Are there any smells or added technical debt to note?
No

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-1968

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
No

2022-10-27 18:15 UTC, nrh-cklimas requested changes
Overall looks good, just had some small suggestions.

Could you run prettier on this PR? I noticed some stuff it should clean up -- missing semicolons, some inconsistencies about single/double quotes.

2022-10-27 18:15 UTC, nrh-cklimas commented on spa/src/components/common/AvatarMenu/AvatarMenu.test.tsx
> +    window.open = jest.fn()
We should restore this after the test finishes. Something like...

```ts
const oldOpen = jest.spyOn(window, 'open').mockImplementation(() => {});
// ... test ...
oldOpen.mockRestore();
```

2022-10-27 18:15 UTC, nrh-cklimas commented on spa/src/components/common/AvatarMenu/AvatarMenu.test.tsx
> +    userEvent.click(screen.getByRole('button', { name: settingsMenu }));
👍  checking AX both closed and open.

2022-10-27 18:15 UTC, nrh-cklimas commented on spa/src/components/common/AvatarMenu/AvatarMenu.tsx
> +      <Container open={open ? 'open' : ''} className={className!} onClick={handleClick} aria-label='settings menu'>
How about just `Settings` for the ARIA label to match what you put on ModalHeader?

2022-10-27 18:15 UTC, nrh-cklimas commented on spa/src/components/common/AvatarMenu/AvatarMenu.tsx
> +export const urlFAQ = 'https://news-revenue-hub.atlassian.net/servicedesk/customer/portal/11/article/2195423496'
We have this and the help URL already in DashboardSidebarFooter. How about we centralize them under `constants` so they don't fall out of sync?

2022-10-27 18:15 UTC, nrh-cklimas commented on spa/src/components/common/AvatarMenu/AvatarMenu.tsx
> +  const id = open ? 'grab link popover' : undefined;
Let's make this something like `avatar-menu-popover`.

2022-10-27 18:15 UTC, nrh-cklimas commented on spa/src/components/common/AvatarMenu/AvatarMenu.tsx
> +  user: undefined,
I don't think setting a default prop to undefined has any effect?

2022-10-27 18:15 UTC, nrh-cklimas commented on spa/src/components/common/AvatarMenu/AvatarMenu.test.tsx
> +}));
```suggestion
jest.mock('components/authentication/logout');
```

2022-10-27 20:42 UTC, GuiMend commented on spa/src/components/common/AvatarMenu/AvatarMenu.test.tsx
> +    window.open = jest.fn()
👍 
What is the issue with the current implementation? Would like to learn why it's not ideal

2022-10-27 20:52 UTC, GuiMend commented on spa/src/components/common/AvatarMenu/AvatarMenu.tsx
> +  user: undefined,
Correct

2022-10-28 13:29 UTC, nrh-cklimas commented on spa/src/components/common/AvatarMenu/AvatarMenu.test.tsx
> +    window.open = jest.fn()
It's kind of a theoretical problem here, but changing a global in a Jest test can cause it to pollute other tests if they rely on it without mocking it (which they shouldn't... but nobody's perfect). And this usually shows up as weird test failures dependent on which tests are running, order in which they run, etc.

2022-10-28 13:31 UTC, nrh-cklimas approved these changes

2022-11-04 16:38 UTC, x110dc approved these changes

2022-11-04 16:38 UTC, merged