DEV-2360  | Support back behavior from Stripe Payment form to checkout
newsrevenuehub/rev-engine pull request #790
Opened 2022-10-27 19:44 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

Adds a "Back" button to the Stripe Checkout form. When clicked, the user is taken back to the initial check out form, and a request is made to the API that:

- Sets the (NRE) contribution status to "cancelled"
- Cancels the payment intent (if one-time) or subscription (if recurring) on Stripe

#### Why are we doing this? How does it help us?

Better contributor experience.

#### How should this be manually tested? Please include detailed step-by-step instructions.

1. Go to a live donation page in review app. Fill out the first form. You'll be taken to the Stripe Checkout form.
2. Look in the Django admin for your contribution. It should have a status of "processing".  While in Django admin, grab the provider_payment_id (if one time) or provider_subscription_id (if recurring).
3. Go to Stripe dashboard and locate either the payment intent (if one time) or subscription (if recurring). 
4. Now, back in the donation page, click the "Back" button. 
5. You should get taken back to the initial donation page form. The values you originally chose should still be filled in.
6. Back in Django admin, refresh the contribution. Its status should now be "cancelled".
7. Back in Stripe, the payment intent / subscription should no longer appear (having been deleted).
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

Yes. On both front- and back-end.  

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

No

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-2360

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No

2022-10-28 14:03 UTC, nrh-cklimas requested changes
Just small changes here.

Our prettier precommit hook isn't working on TypeScript (yet)--see the fix on Slack, so I would either plug that in or run prettier manually. I noticed there's are also some extraneous line breaks here and there too.

2022-10-28 20:57 UTC, benjaminEwhite commented on spa/package.json
> +    "@testing-library/cypress": "^8.0.3",
Yeah, I think we can incrementally/opportunistically start supplanting getByTestId.

2022-10-28 20:58 UTC, benjaminEwhite commented on spa/src/components/common/Button/BackButton/BackButton.test.tsx
> +  it('should have an onClick callback function', () => {
b9244b6625af

2022-10-28 21:14 UTC, benjaminEwhite commented on spa/src/components/common/Button/BackButton/BackButton.tsx
> +  text?: string
8fcb29836

2022-10-28 21:14 UTC, benjaminEwhite commented on spa/src/components/donationPage/DonationPage.js
> +  // we manually set the XCSRFToken value in header here. This is an unauthed endpoint
Strictly speaking, it's `X-CSRFTOKEN' that gets set.

7d824f0c14

2022-10-28 21:32 UTC, benjaminEwhite commented on spa/src/components/donationPage/DonationPage.js
> +        cancelPayment: () => {
d36cbf7115eca5

2022-10-28 21:34 UTC, benjaminEwhite commented on spa/src/components/common/Button/BackButton/BackButton.tsx
> +  text: PropTypes.string,
I'm inclined to leave as is, and generalize when we have > 1 case.

2022-10-31 16:56 UTC, nrh-cklimas commented on spa/src/components/donationPage/DonationPage.js
> +  // we manually set the XCSRFToken value in header here. This is an unauthed endpoint
Ah ok. I honestly thought it was a typo because X is next is to the C key.

2022-10-31 16:57 UTC, nrh-cklimas approved these changes

2022-11-01 17:18 UTC, njharman requested changes
Only reviewed Python code.

Lacking test coverage for unhappy paths and one suggestion on logging/error reporting. Otherwise looks good.

2022-11-01 17:18 UTC, njharman commented on apps/contributions/views.py
> +            return Response(status=status.HTTP_409_CONFLICT)
Should we log or return more information (for future debugging/diagnosis?  Such as the contribution status that was not PROCESSING. And, for log, identifying "ids" of contribution, contributor, DP, etc.

2022-11-01 17:18 UTC, njharman commented on apps/contributions/views.py
> +            raise ValidationError({"interval": "The provided value for interval is not permittted"})
This "failure" path is not test covered.

2022-11-01 17:18 UTC, njharman commented on apps/contributions/views.py
> +        except StripeError:
This "failure" path is not test covered.

2022-11-01 17:42 UTC, benjaminEwhite commented on apps/contributions/views.py
> +            return Response(status=status.HTTP_409_CONFLICT)
I don't think we should return more info to client, but agree re: logging, as this is not something the user (or SPA more generally) can/should fix.

e03a1341d

2022-11-01 18:22 UTC, benjaminEwhite commented on apps/contributions/views.py
> +            raise ValidationError({"interval": "The provided value for interval is not permittted"})
1ec861552

2022-11-01 18:23 UTC, benjaminEwhite commented on apps/contributions/views.py
> +            raise ValidationError({"interval": "The provided value for interval is not permittted"})
See 1ec861552

2022-11-01 18:40 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        except StripeError:
See 838b60c36

2022-11-03 19:21 UTC, x110dc approved these changes

2022-11-04 15:07 UTC, merged