DEV-1867 | Restrict Swag Options and member benefits blocks via org plan
newsrevenuehub/rev-engine pull request #792
Opened 2022-10-28 18:03 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

This plan makes back- and front-end changes to restrict swag options and member benefits in the page editor, in live pages, and in the serialized data model.

- The available items in the Layout tab, when you try to add a page element, is filtered by those available in the org's plan
- The available items in the Sidebar tab, when you try to add a sidebar element, is filtered by those available in the org's plan
- The page elements that are provided in a serialized page are limited to those permitted by related org's plan (even if additional elements are stored in the underlying DonationPage model instance)
- The sidebar elements that are provided in a serialized page are limited to those permitted by related org's plan (even if additional sidebar elements are stored in the underlying DonationPage model instance)
- When creating a new page or updating an existing one, if you try to add page or sidebar elements that are not permitted by the related org's plan, you'll get a validation error.

Some notable code changes:

- Renames `Organization.plan` to `Organization.plan_name` and adds a `.plan` property to `Organization` that returns the plan data.
- Adds `sidebar_elements` and `page_elements` to the `Plan` dataclass.
- Adds `validate_page_element_permissions` and `validate_sidebar_element_permissions` to the `DonationPageFullDetailSerializer`. These methods are for ensuring that page/sidebar elements in a create/update API request only contain elements permitted by the org plan.
- Overrides `DonationPageFullDetailSerializer.to_representation` to filter out any page or sidebar elements that are not permitted by org plan, even if those elements are stored on the DonationPage model instance.
- Updates the `AddElementModal` component in the SPA such that the page editor will only display widgets for page and sidebar elements that are permitted by the org's plan.

#### Why are we doing this? How does it help us?

Part of rolling out tiered plans

#### How should this be manually tested? Please include detailed step-by-step instructions.

1. Log in to the review app's Django admin. Choose an organization (you'll look at pages for this org in a moment). If this org is not on the FREE plan, make that change in the admin.
2. Log in to the dashboard (you can do this as hub admin, no need to do it as org admin, though that also works). Find a page belonging to your selected org and open it in the page editor (or create a new page for your chosen org if none exists).
3. Click on the "Layout" tab in the page editor. You shouldn't see the Swag widget. If you click on the `+` icon to add an additional page element, you shouldn't see the Swag widget in the modal.
4. Click on the "Sidebar" tab in the page editor. You shouldn't see the "Donor benefits" widget. If you click on the `+` icon to add an additional page element, you shouldn't see the widget in the modal.
5. Back in the Django admin, update the org's plan to be PLUS.
6. Repeat steps 3 and 4. This time, you _should_ find the respective widgets.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No

#### Have automated unit tests been added? If not, why?

Yes

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-1867

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

I created a TODO and JIRA ticket  (DEV-2741 | Add granular validation for page and sidebar elements](https://news-revenue-hub.atlassian.net/browse/DEV-2741))to add more granular field validation for page_elements and sidebar_elements

2022-10-31 17:05 UTC, nrh-cklimas reviewed
Just a question here.

2022-10-31 17:05 UTC, nrh-cklimas commented on spa/src/components/pageEditor/editInterface/pageElements/addElementModal/AddElementModal.js
> +    if (page?.plan) {
The question mark here is just to accommodate a loading state? In other words, will pages always have a plan eventually?

I think to pendantic, we may want an else on this to set both states to `[]`. I don't see a code path right now where plan could go from having a value to being undefined, but it feels reasonable to code defensively here.

2022-10-31 18:45 UTC, benjaminEwhite commented on spa/src/components/pageEditor/editInterface/pageElements/addElementModal/AddElementModal.js
> +    if (page?.plan) {
@nrh-cklimas have a look at e06bc8d778e9

2022-10-31 18:47 UTC, nrh-cklimas approved these changes

2022-11-01 17:54 UTC, njharman requested changes
Only Reviewed Python code. Complete test coverage. Looks good couple inline questions and suggestions.  And these two re PR.


_> How should this change be communicated to end users?_

Isn't there a need to inform existing users that functionality they use to see (swag options) will no longer be present?  Or, do we have no restricted customers yet?

_> Has this been documented? If so, where?_

Are the features/restrictions of plans already documented?

2022-11-01 17:54 UTC, njharman commented on apps/pages/serializers.py
> +        if prohibited := set([elem["type"] for elem in data.get("elements", [])]).difference(
Shouldn't this be set comprehension (rather than make a list and then turn it into set)? Also, prefer throwaway variable, "x", for throwaway usage. Rather than abbreviation.

{x["type"] for x in data.get("elements", [])}

2022-11-01 19:09 UTC, benjaminEwhite commented on apps/pages/migrations/0003_DEV-1867_default_empty_list_for_sidebar_elements.py
> +class Migration(migrations.Migration):
See 9cc5bcfd7

2022-11-01 19:12 UTC, benjaminEwhite commented on apps/pages/serializers.py
> +        if prohibited := set([elem["type"] for elem in data.get("elements", [])]).difference(
`data` potentially has repeated elements, but we only want to count a repeated element type once for purposes of `prohibited`.

RE: var names, see 708aa3d7

2022-11-01 19:19 UTC, benjaminEwhite commented
@njharman re:

> _> Has this been documented? If so, where?_
> 
> Are the features/restrictions of plans already documented?


I'm not sure if there are internal docs, but there are user-facing descriptions here; https://fundjournalism.org/pricing/

2022-11-01 19:20 UTC, benjaminEwhite commented
@njharman  re:

> _> How should this change be communicated to end users?_
> 
> Isn't there a need to inform existing users that functionality they use to see (swag options) will no longer be present? Or, do we have no restricted customers yet?

I updated PR description and raised question in JIRA.

2022-11-01 19:22 UTC, benjaminEwhite commented on apps/organizations/models.py
> +    sidebar_elements=DEFAULT_SIDEBAR_ELEMENTS
it doesn't look like that's possible. making that change ->

> AttributeError: type object 'Plan' has no attribute 'sidebar_elements'

2022-11-01 20:01 UTC, njharman approved these changes
Approved with check on dependencies of migrations (data before not null) and very minor set comp thing. After resolving, please resolve conversations and move ticket on to next stage.

2022-11-01 20:17 UTC, benjaminEwhite commented on apps/pages/migrations/0003_DEV-1867_default_empty_list_for_sidebar_elements.py
> +class Migration(migrations.Migration):
Good catch. I missed the implicit not-nulling that happened here.

aaa214a2c

2022-11-01 20:17 UTC, benjaminEwhite commented on apps/pages/migrations/0003_DEV-1867_default_empty_list_for_sidebar_elements.py
> +class Migration(migrations.Migration):
aaa214a2c

2022-11-01 20:21 UTC, benjaminEwhite commented on apps/pages/serializers.py
> +        if prohibited := set([elem["type"] for elem in data.get("elements", [])]).difference(
Fixed in [ba4266be6d00b65d72b3a5b5799bcb557353657b](https://github.com/newsrevenuehub/rev-engine/pull/792/commits/ba4266be6d00b65d72b3a5b5799bcb557353657b)

2022-11-03 19:34 UTC, x110dc approved these changes

2022-11-10 01:41 UTC, merged