DEV-2470: add google cloud publisher
newsrevenuehub/rev-engine pull request #793
Opened 2022-10-29 23:59 UTC by leo-dcfa

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

- Discuss how to handle service accounts and if we should have a `fake-service-account.json` file to allow the application to bootapp; discuss alternatives
- Discuss if Signals is an acceptable solution here
- Decide if we should implement emulators for local development as part of this PR or create another ticket for it
- Finally, deploy this to a review app and validate that it works e2e

#### What's this PR do?

- Publish messages to Google Cloud PubSub when a new contributor is created

#### Why are we doing this? How does it help us?

When a new user is created on Production, we’d like to build passive awareness, as this is a key performance indicator for our self-service strategy. 

#### How should this be manually tested? Please include detailed step-by-step instructions.

TBC

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

N/A

#### Have automated unit tests been added? If not, why?

Yes

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

N/A

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-2470]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

N/A

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

To be decided

2022-10-30 21:56 UTC, leo-dcfa commented on apps/google_pub_sub/tests/tests.py
> +        assert result
I am running into issues with testing this properly, so this is just a placeholder test.

My test was initially this:
```python
@pytest.mark.no_patch_google_cloud_pub_sub_publisher
    @patch("apps.google_pub_sub.publisher.pubsub_v1.PublisherClient", MagicMock())
    def test_publishes_to_google_cloud_pub_sub(self):
        topic = "topic"
        expected = "result"
        future = asyncio.Future()
        future.set_result(expected)
        full_topic_path = f"projects/{GOOGLE_CLOUD_PROJECT}/topics/{topic}"
        publisher = GoogleCloudPubSubPublisher()
        publisher.client.topic_path.return_value = full_topic_path
        publisher.client.publish.return_value = future
        message = Message(data="some message")
        result = publisher.publish(topic, message)
        assert expected == result
        publisher.client.topic_path.assert_called_with(GOOGLE_CLOUD_PROJECT, topic)
        publisher.client.publish.assert_called_with(full_topic_path, message.data)
```
But for some reason, it looks like the `.publish` call from `GoogleCloudPubSubPublisher` patch from autouse fixture is not being removed. Any ideas on how to do this better are very welcome

2022-10-30 21:58 UTC, leo-dcfa commented on apps/google_pub_sub/tests/tests.py
> +        assert result
https://github.com/newsrevenuehub/rev-engine/pull/793/files#diff-a31c7ed5d35f5ed8233994868c54d625b18e6bacb6794344c4531e62bd9dde59R15

I also tried this:

```python
def patch_google_cloud_pub_sub_publisher(request):
    marker = request.node.get_closest_marker("no_patch_google_cloud_pub_sub_publisher")
    if marker:
        yield
    else:
        with mock.patch("apps.google_pub_sub.publisher.GoogleCloudPubSubPublisher.publish", MagicMock()):
            yield
```

But that resulted in errors on other classes:

```
self = <django.db.backends.postgresql.base.DatabaseWrapper object at 0x7f7956c05c00>
name = None

    @async_unsafe
    def create_cursor(self, name=None):
        if name:
            # In autocommit mode, the cursor will be used outside of a
            # transaction, hence use a holdable cursor.
            cursor = self.connection.cursor(name, scrollable=False, withhold=self.connection.autocommit)
        else:
>           cursor = self.connection.cursor()
E           psycopg2.InterfaceError: connection already closed

```

See this job for details

2022-11-01 19:51 UTC, x110dc requested changes
I think we can simplify this. I think we can assume that as long as properly configured the Google library will do what it advertises. We just need safety rails around something being unconfigured or misconfigured so if that's wrong it doesn't break anything. This is equivalent to sending an email or a Slack message. As long as the message is properly formatted a lot of testing shouldn't be necessary. Ping me if you'd like to discuss more.

2022-11-01 19:51 UTC, x110dc commented on revengine/settings/base.py
> +GOOGLE_APPLICATION_CREDENTIALS = os.getenv(
This variable isn't used anywhere. Why create it? The Google libraries that need this will read it from the environment directly.

2022-11-01 19:51 UTC, x110dc commented on revengine/settings/base.py
> +    "GOOGLE_CLOUD_NEW_USER_NOTIFICATION_TOPIC", "new-nre-customer-test"
The default here should be `None` or similar. And let's rename it to something shorter like `NEW_USER_TOPIC`.

2022-11-01 19:51 UTC, x110dc commented on revengine/settings/base.py
> +    "apps.google_pub_sub",
I don't think this needs to be a full-fledged Django app.

2022-11-01 19:51 UTC, x110dc commented on apps/google_pub_sub/apps.py
> +
I don't think this needs to be a full Django app. Just a class at most I'd think?

2022-11-01 19:51 UTC, x110dc commented on .pre-commit-config.yaml
> +        exclude: "fake-service-account.json"
I'd rather not complicate local set up with this at this point unless really necessary. Can we remove this, the fake json and related? How about just adding a `ENABLE_PUBSUB` variable that defaults to `True` and locally and in test we set it to False?

2022-11-01 19:51 UTC, x110dc commented on apps/users/models.py
> +        super().save(*args, **kwargs)
Won't this notify on every `save()` to the User? We only want to notify on new user creation. See here for a way to tell if it object is new: https://stackoverflow.com/a/35647389

2022-11-01 19:51 UTC, x110dc commented on google_cloud_pub_sub/fake-service-account.json
> +{
Let's remove this file.

2022-11-01 20:07 UTC, leo-dcfa commented on apps/google_pub_sub/apps.py
> +
my initial idea is to have it a more general purpose if we need to publish messages in other contexts.

2022-11-01 20:08 UTC, leo-dcfa commented on revengine/settings/base.py
> +GOOGLE_APPLICATION_CREDENTIALS = os.getenv(
ah good point, of course!

2022-11-01 20:42 UTC, leo-dcfa commented on apps/users/models.py
> +        super().save(*args, **kwargs)
ah good point, forgot this one

2022-11-01 21:43 UTC, leo-dcfa commented on .pre-commit-config.yaml
> +        exclude: "fake-service-account.json"
good idea

2022-11-01 21:43 UTC, leo-dcfa commented on google_cloud_pub_sub/fake-service-account.json
> +{
done

2022-11-01 21:44 UTC, leo-dcfa commented on revengine/settings/base.py
> +    "apps.google_pub_sub",
removed

2022-11-08 21:31 UTC, x110dc requested changes

2022-11-08 21:31 UTC, x110dc commented on Makefile
> +	sleep 5 && curl -s -X PUT 'http://localhost:8085/v1/projects/revenue-engine/topics/new-nre-customer-test' # sleep for 5 seconds to allow google cloud to boot up
I don't think we're going to want this most of the time. Can we either make this a comment about how to do this or make it a separate Makefile target?

2022-11-08 21:31 UTC, x110dc commented on docker-compose.yml
> +  gcloud_pub_sub_emulator:
Let's put this in `docker-compose-dev.yml`

2022-11-08 21:31 UTC, x110dc commented on apps/users/models.py
> +            self.google_cloud_pub_sub_publisher.publish(settings.NEW_USER_TOPIC, Message(data=self.email))
If `settings.NEW_USER_TOPIC` or `settings. GOOGLE_CLOUD_PROJECT` isn't defined I'd rather skip the notification than fail. So maybe do the `super()` first or catch exceptions here?

2022-11-10 15:55 UTC, benjaminEwhite requested changes

2022-11-10 15:55 UTC, benjaminEwhite commented on apps/common/utils.py
> +    return settings.ENABLE_PUBSUB and settings.NEW_USER_TOPIC and settings.GOOGLE_CLOUD_PROJECT
What you have here is totally fine. I have a slight stylistic preference for following syntax when there's > 1 `and`, but if you prefer the multiple `ands` you should keep them 😄 

```python
    return all([settings.ENABLE_PUBSUB, settings.NEW_USER_TOPIC, settings.GOOGLE_CLOUD_PROJECT])
```

2022-11-10 15:55 UTC, benjaminEwhite commented on apps/users/google_pub_sub.py
> +
Nitpicking, but no need for extra line here.

2022-11-10 15:55 UTC, benjaminEwhite commented on apps/users/google_pub_sub.py
> +logger = logging.getLogger(__name__)
Why this syntax here vs. `logger = logging.getLogger(f"{settings.DEFAULT_LOGGER}.{__name__}")` in apps/users/models.py?

2022-11-10 15:55 UTC, benjaminEwhite commented on apps/users/models.py
> +        return self._state.adding and self.email and not self.email.endswith("@fundjournalism.org")
Could also use the `all` approach here...

2022-11-10 15:55 UTC, benjaminEwhite commented on apps/users/google_pub_sub.py
> +        return cls.__instance
Might be good to have a doc string explaining why/how this is used. I'm not entirely sure why we are using a singleton pattern here.

2022-11-10 15:55 UTC, benjaminEwhite commented on apps/users/tests/test_google_pub_sub.py
> +        assert isinstance(Message("irrelevant").data, bytes)
Notwithstanding the fact that there's a bunch of existing test code that uses unitttest, when possible we're trying to move toward using pytest-based tests instead.  Here, can easily do that, and also do away with the class, since there's only a single test function. 

```suggestion
def test_message_encodes_string_to_bytes(self):
        assert isinstance(Message("irrelevant").data, bytes)
```

2022-11-10 15:55 UTC, benjaminEwhite commented on apps/users/tests/test_models.py
> +    def test_will_not_publish_external_emails_to_google_pubsub(self, publish):
Should this be "internal" (or maybe "hub") instead of "external"?

2022-11-10 15:55 UTC, benjaminEwhite commented on apps/users/tests/test_models.py
> +    def test_will_publish_external_emails_to_google_pubsub(self, publisher, new_user_topic):
This is minor, but I prefer present tense for these kind of test names. `test_publishes_external_emails_to_google_pubsub`

2022-11-10 18:40 UTC, leo-dcfa commented on apps/common/utils.py
> +    return settings.ENABLE_PUBSUB and settings.NEW_USER_TOPIC and settings.GOOGLE_CLOUD_PROJECT
nice, thanks for the suggestion. am fairly new to python so this sort of suggestion is very helpful

2022-11-10 20:22 UTC, leo-dcfa commented on apps/users/google_pub_sub.py
> +logger = logging.getLogger(__name__)
good catch, hadn't noticed it

2022-11-10 20:23 UTC, leo-dcfa commented on apps/users/google_pub_sub.py
> +        result = future.result(timeout=3)
nice, thanks

2022-11-10 20:27 UTC, leo-dcfa commented on apps/users/google_pub_sub.py
> +        return cls.__instance
Adding this
``text
"""Returns an instance of GoogleCloudPubSubPublisher;
           Singleton pattern was chosen here since it is not necessary to instantiate/authenticate multiple times with
           GoogleCloud, and it will only do it the first time the application requires it. Additionally, memory is saved by
           sharing the same instance across RevEngine"""
```

Let me know if you don't agree but I think it doesn't make sense to authenticate with GoogleCloud and keep multiple instances of the publisher, which is just a thin client that does a bit of formatting/logging

2022-11-10 20:34 UTC, leo-dcfa commented on google_cloud_pub_sub/subscribe.py
> +# this is a helpful script to connect to topic from the Django shell
good point about code coverage, removed it

2022-11-10 20:35 UTC, leo-dcfa commented on apps/users/tests/test_models.py
> +    def test_will_not_publish_external_emails_to_google_pubsub(self, publish):
good catch

2022-11-10 20:36 UTC, leo-dcfa commented on apps/users/tests/test_models.py
> +    def test_will_publish_external_emails_to_google_pubsub(self, publisher, new_user_topic):
no problem

2022-11-10 20:39 UTC, leo-dcfa commented on apps/users/tests/test_google_pub_sub.py
> +        publisher_client.publish.assert_called_with(full_topic_path, message.data)
Is this something you are very passionate about? I am happy to change it, just this sprint I have a lot in my plate

2022-11-10 21:03 UTC, x110dc commented on apps/users/tests/test_google_pub_sub.py
> +        publisher_client.publish.assert_called_with(full_topic_path, message.data)
@leo-dcfa It's our policy to use pytest: https://news-revenue-hub.atlassian.net/wiki/spaces/TECH/pages/2047311873/Python+Style+Guide

This ticket isn't urgent, so if you need to come back to it to address something else that's fine.

2022-11-10 21:08 UTC, leo-dcfa commented on apps/users/tests/test_google_pub_sub.py
> +        publisher_client.publish.assert_called_with(full_topic_path, message.data)
no worries, I'll reassign the ticket to myself

2022-11-10 21:11 UTC, leo-dcfa commented on apps/users/tests/test_google_pub_sub.py
> +        publisher_client.publish.assert_called_with(full_topic_path, message.data)
@benjaminEwhite would you mind pointing to what the equivalent in pytest is for `assert_called_with`

2022-11-10 21:33 UTC, x110dc commented on apps/users/tests/test_google_pub_sub.py
> +        publisher_client.publish.assert_called_with(full_topic_path, message.data)
I think there are examples in other tests here like in apps/contributions/tests/test_webhooks.py: 

`assert not mock_process_pi.called`

2022-11-10 21:35 UTC, leo-dcfa commented on apps/users/tests/test_google_pub_sub.py
> +        publisher_client.publish.assert_called_with(full_topic_path, message.data)
Ah I know about that one but slightly different no? Assert that something is called is different from asserting the calling arguments are correct

2022-11-11 15:31 UTC, benjaminEwhite commented on apps/users/tests/test_google_pub_sub.py
> +        publisher_client.publish.assert_called_with(full_topic_path, message.data)
@leo-dcfa we probably should make language in the wiki a bit clearer. I think what we're trying to avoid is the `self.assert...` methods that attach to a unittest test case class.

For this example, I believe you could do something along lines explained here: https://stackoverflow.com/a/69620212

2022-11-11 15:49 UTC, benjaminEwhite approved these changes

2022-11-15 21:55 UTC, x110dc requested changes
A couple of minor change requests.

2022-11-15 21:55 UTC, x110dc commented on revengine/settings/base.py
> +ENABLE_PUBSUB = os.getenv("ENABLE_PUBSUB", "False").lower() in ("true", "1")
I think we should probably be consistent here with the rest of our boolean/enable variables and do:
`SENTRY_ENABLE_FRONTEND = os.getenv("SENTRY_ENABLE_FRONTEND", "false").lower() == "true"`

2022-11-15 21:55 UTC, x110dc commented on pyproject.toml
> +google-cloud-pubsub = "^2.13.11"
Let's make this `^2.13`

2022-11-15 21:55 UTC, x110dc commented on apps/users/models.py
> +        return all([self._state.adding, self.email, not self.email.endswith("@fundjournalism.org")])
I'd rather not hardcode the `@fundjournalism.org` here. We can maybe make that a variable in the future, but for now let's just remove it and it won't be a big deal to get notifications for those addresses.

2022-11-15 21:55 UTC, x110dc commented on Makefile
> +	docker-compose -f docker-compose.yml -f docker-compose-dev.yml up -d --remove-orphans redis
To preserve the existing behavior this should be `--remove orphans redis db`

2022-11-20 19:58 UTC, x110dc approved these changes

2022-11-20 20:01 UTC, merged