DEV-2519: Add Tax Id field to onboarding
newsrevenuehub/rev-engine pull request #797
Opened 2022-10-31 20:52 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
Add Tax Id field on onboarding modal + backend to support change

#### Why are we doing this? How does it help us?
To be able to save the user's company tax id

#### How should this be manually tested? Please include detailed step-by-step instructions.
- Create new user
- Verify email
- Check that onboarding modal has EIN field (tax id) and that it only accepts number
- Fill in info and use more than 9 numbers in EIN field (error should show EIN related error message)
- Save: should save user info without error and continue onboarding steps (stripe modal)

Tax Id is being saved:
![image](https://user-images.githubusercontent.com/9381325/199107798-641c4dfe-5a94-4b46-a431-41ab10c4a90d.png)

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
Yes

#### Have automated unit tests been added? If not, why?
Yes

#### How should this change be communicated to end users?
Tax Id now is a field on the onboarding

#### Are there any smells or added technical debt to note?
No

#### Has this been documented? If so, where?
No

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-2519 [Frontend UI]
https://news-revenue-hub.atlassian.net/browse/DEV-2733 [Backend]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
Migration (?)

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
No

2022-11-01 13:15 UTC, nrh-cklimas commented on apps/organizations/migrations/0009_revenueprogram_tax_id.py
> +                blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)]
My Django knowledge is very low (and I'm also not an EIN/TIN expert either), but is there a way we can also validate that the number >= 111111111? e.g. it is a 9-digit, positive number?

2022-11-01 13:17 UTC, nrh-cklimas commented on spa/src/components/account/Profile/Profile.test.tsx
> +    (useHistory as jest.Mock).mockReturnValue({ push: historyPushMock });
Just a style thing--I like doing `const useHistoryMock = useHistory as jest.Mock;` at the top of tests so I don't have to cast every time I use it. But I think it's used infrequently enough here to be OK.

2022-11-01 13:19 UTC, nrh-cklimas commented on spa/src/components/account/Profile/ProfileForm.styled.ts
> +export const useStyles = makeStyles(() => ({
Is this leftover from dev? I don't see it imported in ProfileForm. If I missed where it's used, is this change not possible with styled-components? I'd prefer to keep us on that only instead of mixing JSS and styled-components.

2022-11-01 13:24 UTC, nrh-cklimas commented on spa/src/components/account/Profile/ProfileForm.tsx
> +export type FormDataType = typeof defaultValues;
Could we call this something like `ProfileFormFields` so that if you import it into some other module, the name is clear?

2022-11-01 13:26 UTC, nrh-cklimas commented on spa/src/components/account/Profile/__mocks__/ProfileForm.tsx
> +  function handleSubmit(event: any) {
```suggestion
  function handleSubmit(event: FormEvent) {
```
This would need a `import { FormEvent } from 'react';` at the top too.

2022-11-01 13:40 UTC, nrh-cklimas commented on spa/src/components/account/Profile/ProfileForm.tsx
> +          <TextField
This field doesn't have a max length on it (I think `inputProps={{ maxLength: 9 }}` would do it, but I didn't test this) and the error message from Django if you enter too many digits isn't great ("A valid integer is required").

It would be nice if the field filtered out dashes as typed instead of showing a validation error message when I click to submit.

2022-11-01 13:57 UTC, benjaminEwhite requested changes

2022-11-01 13:57 UTC, benjaminEwhite commented on apps/organizations/models.py
> +    tax_id = models.PositiveIntegerField(blank=True, null=True, validators=[MaxValueValidator(999999999)])
Made this comment below, but circling back up here: think we should be validating that the tax ID is exactly 9 digits long. In that case, probably need a custom validator.

2022-11-01 13:57 UTC, benjaminEwhite commented on spa/src/components/account/Profile/Profile.tsx
> +    } catch (e: any) {
Could this be `(e: Error)`?

2022-11-01 13:57 UTC, benjaminEwhite commented on spa/src/components/account/Profile/ProfileForm.tsx
> +  const { control, handleSubmit, watch } = useForm({ defaultValues });
We should consider using Yup + RHF for schema validation on form inputs. No need for round-trip to server to find out that the value for tax ID is invalid (too many or not enough digits, for instance).

https://react-hook-form.com/get-started#schemavalidation

2022-11-01 13:57 UTC, benjaminEwhite commented on spa/src/components/account/Profile/ProfileForm.tsx
> +          <TextField
Ideally, we'd do some sort of masking on this input such that as user types in numbers, the dash gets added after first two digits.

2022-11-01 21:41 UTC, GuiMend commented on spa/src/components/account/Profile/Profile.tsx
> +    } catch (e: any) {
Typescript blocks typing in catch statements to `any` or `unknown`

2022-11-02 19:42 UTC, GuiMend commented on apps/organizations/migrations/0009_revenueprogram_tax_id.py
> +                blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)]
Updated the field to have a better validator

2022-11-02 19:44 UTC, GuiMend commented on apps/users/tests/test_views.py
> +    def test_customize_account_sets_revenue_program_tax_id(self):
Not sure how to do this one. Could you point me in the right direction?

2022-11-02 19:45 UTC, GuiMend commented on spa/src/components/account/Profile/ProfileForm.tsx
> +  const { control, handleSubmit, watch } = useForm({ defaultValues });
I used the validation rules from react-hook-forms itself. Don't think it is necessary to have yup for this instance.

2022-11-02 20:24 UTC, nrh-cklimas commented on spa/src/components/account/Profile/ProfileForm.styled.ts
> +export const useStyles = makeStyles(() => ({
I see. Can we replace with styled components, then?

2022-11-02 20:27 UTC, nrh-cklimas commented on spa/src/components/account/Profile/ProfileForm.tsx
> +          <TextField
Masked input looks great now.

2022-11-03 14:02 UTC, benjaminEwhite commented on apps/users/tests/test_views.py
> +    def test_customize_account_sets_revenue_program_tax_id(self):
See https://github.com/newsrevenuehub/rev-engine/compare/DEV-2519-capture-tax-id-in-onboarding...DEV-2519-capture-tax-id-in-onboarding-bw-suggestions

2022-11-03 17:42 UTC, nrh-cklimas approved these changes

2022-11-04 05:14 UTC, benjaminEwhite approved these changes

2022-11-14 14:20 UTC, nrh-cklimas requested changes

2022-11-14 14:20 UTC, nrh-cklimas commented on spa/src/components/account/Profile/Profile.tsx
> +      const { data, status } = await axios.patch(`users/${user?.id}/${CUSTOMIZE_ACCOUNT_ENDPOINT}`, {
Under what circumstances would `user` not be defined when this function gets called? I think, at a glance, that this is a "should never happen" scenario. If so, I would rather this throw an error saying so rather than the API request failing because it'll try to PATCH `users/undefined/customize_account/`.

2022-11-16 11:54 UTC, GuiMend commented on spa/src/components/account/Profile/Profile.tsx
> +      const { data, status } = await axios.patch(`users/${user?.id}/${CUSTOMIZE_ACCOUNT_ENDPOINT}`, {
@nrh-cklimas , you are correct. This scenario will never happen, because for the user to get to this place the `user` object will have an `id`. But TS makes me add the `?` because the typing has undefined as a possibility 
![image](https://user-images.githubusercontent.com/9381325/202173912-fdf3500d-629c-4bf1-b34d-ca22e6cb83a8.png)

Do you want me to create something like:
```js
if (user.id) {
   // patch
} else {
  alert.error("User is undefined")
}
```

2022-11-16 13:51 UTC, nrh-cklimas commented on spa/src/components/account/Profile/Profile.tsx
> +      const { data, status } = await axios.patch(`users/${user?.id}/${CUSTOMIZE_ACCOUNT_ENDPOINT}`, {
Since this should never happen if things are working right, I'm thinking

```tsx
if (!user) {
  // Should never happen under normal circumstances.
  throw new Error('Asked to customize user, but user is undefined');
}

The user will see a "something went wrong" message and Sentry will log the problem.

2022-11-16 16:40 UTC, nrh-cklimas approved these changes

2022-11-22 20:06 UTC, x110dc approved these changes

2022-11-23 01:51 UTC, benjaminEwhite commented
Closing and reopening this PR in order to trigger a fresh review app build (see JIRA ticket for more context).

2022-11-23 14:55 UTC, merged