DEV-489: Refactor contributor dashboard to use react-query, hide deleted contribs locally
newsrevenuehub/rev-engine pull request #799
Opened 2022-11-01 17:51 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

User-facing:

This changes the contributor dashboard so that if you successfully cancel a subscription, that subscription will disappear from the table. However, this update is only temporary. Refreshing the browser or otherwise causing data to be fetched from the API will cause it to reappear. This is a limitation of what we can do with the SPA, since we don't have backend changes yet to support it updating during a user session.

The contribution list is no longer sortable, because it didn't work correctly in the first place (see DEV-2152) and clicking to sort too often caused errors. I'd like to bring that back in a separate story since the PR is big as it is.

Behind the scenes:

This is a refactor of the contributor dashboard because most of the existing components expected to be given an Axios request that resolved to data. This was replaced with a hook, useContributorContributionList. The name is because an admin will get a different set of data fields.

- Created base components for tables and pagination that are intended to match existing styling.
- Created a common component, PaymentStatus, that handles formatting of items like "Paid" and "Pending". The existing code had the org admin contributions list import the component from the contributor dashboard.
- Created a common component, ValueOrPlaceholder, to make the logic of "show children if this value is not nullish, otherwise show ----" reusable.

#### Why are we doing this? How does it help us?

This improves UX around cancelling a subscription and makes progress toward unifying our code around using react-query for data retrieval.

#### How should this be manually tested? Please include detailed step-by-step instructions.

To test the change:

- Create a test recurring contribution.
- Log into the contributor dashboard.
- Cancel the contribution.
- After confirming the cancellation, the subscription should disappear from the table. However, refreshing in your browser will see it come back.
- Confirm that after cancelling the test subscription, it appears as cancelled in Stripe.

To test regressions (important, because this changes a lot about how the contributor dashboard works behind the scenes):

- Log into the contributor dashboard.
- Confirm the table shows accurate data as compared to Stripe.
- Confirm that the pager buttons at the bottom of the table work.
- Confirm the table looks the same as on an existing deploy (like dev).
- Confirm that the pager buttons at the bottom of the table look the same as on an existing deploy.
- Confirm that editing a credit card on a subscription works.
   - Confirm that in the edit dialog, clicking the last 4 digits of the existing credit card does nothing. (This sounds weird but it uses the same component as in the table, which is editable.)

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

It removed the sortable table header in the contributor dashboard temporarily.

#### Have automated unit tests been added? If not, why?

Yes.

#### How should this change be communicated to end users?

We might want to explain that sorting the table will return.

#### Are there any smells or added technical debt to note?

Maintaining local state is not great, but it seems like the best we can do until backend changes happen.

#### Has this been documented? If so, where?

No.

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-489

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

https://news-revenue-hub.atlassian.net/browse/DEV-2152

2022-11-01 17:52 UTC, nrh-cklimas commented on spa/cypress/e2e/08-contributor.cy.js
> -      cy.get('td > p > span').should('have.length', 20);
I think the intent of the original test was to check the number of rows. But if my understanding is off, the replacement is too. I had to change this test because the underlying DOM structure has changed (no <p>s in the table cells).

2022-11-03 22:40 UTC, GuiMend approved these changes
Looking great Chris. Lot's of structure changes and I liked them 👍

2022-11-04 13:19 UTC, nrh-cklimas commented on spa/src/components/contributor/contributorDashboard/ContributionPaymentMethod.tsx
> +  disabled?: false;
What I'm trying here is to create a discriminated union in TypeScript based on the value of `disabled`. If the control is disabled, passing an `onUpdateComplete` prop is not allowed. If disabled is false or omitted, the onUpdateComplete prop is required. My thought was to keep ourselves (well, myself) from making a mistake and try to put an `onUpdateComplete` prop on a component instance that will never update.

Let me know if that sounds like overengineering it. We could pull it back to a standard interface.

2022-11-04 13:20 UTC, nrh-cklimas commented on spa/src/components/contributor/contributorDashboard/ContributionPaymentMethod.tsx
> +  | EnabledContributionPaymentMethodProps;
[Prettier took the wheel here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACGATwzjwGFoZsBLAIwFcZroAFAQ0IFsEYBZOGAAsIAExbYIGAM54AvHgAi1KW1oAbOCIqwaDJqw7dY-IaPGSZAHzwBRKKo1bKuxsyjsuPE8LETpAbhAAGhBJfSgpZFA2bAkAd3ZsBEiUNjU4jkiQ2mw2MABrAQBlNm4AGWooOGQAMzSpOGzcguKMPMqAc2QqekbUTlpNEU0ytigO+jYOuAAxHE42GCZx5BA2RghgkEEYTjUAdUFqeCk2sDgi5OPqADdjwlWwKSyQSobccSmF2vq+gCspGgip0NABFegQeA-NQNEJtbDvVa0VRwNRbDA0WD7agiITIAAcAAY4RIGvtchhVhi4O8btUQgBHCHwczSVZsKQAWiqmk0WySTOoSU+HW+SDqML6DU41G62F6ISkILg4Mh1XFvxCMFU2NxgmQACYtblqGpOhROGLUFIAKxbegNAAqqhSEthIBuvQAklBhrAimAaBgYABBX1FIgaaENAC+MaAA).

2022-11-04 13:23 UTC, nrh-cklimas commented on spa/src/components/contributor/contributorDashboard/ContributionsTable.test.tsx
> +    expect(error.mock.calls).toEqual([['We encountered an issue and have been notified. Please try again.']]);
Jest mock's `calls` attribute are 2d arrays, yeah. It's a little confusing...

- First layer is each mock call.
- Second layer is the args of each call.

So `error.mock.calls[0][1]` gives you the second argument of the first mock call.

This is a shortcut for writing:

```tsx
expect(error).toBeCalledTimes(1);
expect(error).toBecalledWith('We encountered an error etc');
```

But if there's a nicer way to do it, I'm up for it. Or maybe I should just be more verbose for clarity.

2022-11-04 17:47 UTC, GuiMend commented on spa/src/components/contributor/contributorDashboard/ContributionsTable.test.tsx
> +    expect(error.mock.calls).toEqual([['We encountered an issue and have been notified. Please try again.']]);
It's ok. I'm still getting familiar with jest

2022-11-04 17:56 UTC, GuiMend commented on spa/src/components/contributor/contributorDashboard/ContributionPaymentMethod.tsx
> +  disabled?: false;
Interesting, I've never used it that way but seem like a smart way to handle different props for different scenarios. I wonder if TS has an easy plug&play way to do this. But I'm ok leaving it as is 👍

2022-11-07 16:06 UTC, benjaminEwhite requested changes

2022-11-07 16:06 UTC, benjaminEwhite commented on spa/src/hooks/useContributorContributionList.ts
> +  // We use keepPreviousData so that switching pages is smoother.
That's nifty.

2022-11-07 18:18 UTC, nrh-cklimas commented on spa/cypress/e2e/08-contributor.cy.js
> +      cy.get('tbody tr').should('have.length', 10);
This is the page size the SPA asks for. I checked the Cypress intercept and it tries to mimic the API but doesn't assert that we ask for 10. I could update this check to compare it to the intercept call, maybe--what do you think?

2022-11-07 18:22 UTC, nrh-cklimas commented on spa/src/components/contributor/contributorDashboard/ContributionsTable.tsx
> +  // Test IDs are here for compatibility with existing Cypress tests.
I'd like to do this one in a followup story, personally. I like the pattern of splitting refactors into two steps (code, then tests) to avoid accidentally changing tests so that a regression passes.

I think this is one of those things we agree to fix as we touch tests, similar to TypeScript migration.

2022-11-07 18:24 UTC, nrh-cklimas commented on spa/src/hooks/useContributorContributionList.ts
> +  // update the local contributor cache when one is cancelled. (It gets updated
Makes sense: 48d91a9d31d2a12e61ad50333605e62b537b6106

2022-11-07 18:46 UTC, nrh-cklimas commented on spa/src/components/base/Table/Table.test.tsx
> +  return render(
I tried this out this afternoon but hit a TypeScript blocker. The issue... I think... is that Storybook marks all props optional in a story (I guess for flexibility?) but this makes TypeScript in Jest unhappy:

```tsx
function tree(props?: Partial<CancelRecurringButtonProps>) {
  return render(<Default {...Default.args} {...props} />);
}
```

TypeScript says this is wrong because `Default.args` can omit props that are required in `CancelRecurringButtonProps`. I found https://github.com/storybookjs/storybook/issues/13747 which seems to indicate it'll get fixed in a future Storybook update. I don't personally love the workarounds listed in the issue.

But... I have never actually integrated Jest + Storybook before, so I'm wondering if you have an idea on the right approach.

2022-11-07 19:49 UTC, benjaminEwhite approved these changes

2022-11-10 22:09 UTC, merged