WIP | DEV-2342 split bad actors into 3 buckets not just 2 for NRE
newsrevenuehub/rev-engine pull request #801
Opened 2022-11-02 16:19 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

This PR changes business logic around bad actor scores:

- If a contribution is marked as "good", everything is as before.
- If a contribution is marked as "bad" (i.e., score of 4), everything happens that happens in "good" case, but:
  - In case of one-time contribution
    - the payment intent is created with `capture_method` set to "manual"
    - the contribution status is set to "flagged"
  - In case of recurring contribution
    - the subscription is created with a trial period that is one day longer than `settings.FLAGGED_PAYMENT_AUTO_ACCEPT_DELTA = 3`
 
[more details coming soon]

#### Why are we doing this? How does it help us?

Ultimately allow a larger number of legitimate contributions to process, while keeping out illegit ones.

#### How should this be manually tested? Please include detailed step-by-step instructions.

##### Scenario 1: "Good" actor making one-time contribution

Make a contribution as a good actor. Everything should work as usual, inclusive of Stripe customer and payment intent being created. The PI's capture_method should be set to "automatic"

##### Scenario 2: "Good" actor making recurring contribution

##### Scenario 3: "Bad" actor making one-time contribution

##### Scenario 4: "Bad" actor making recurring contribution

##### Scenario 5: "SuperBad" actor making one-time contribution

##### Scenario 6: "SuperBad" actor making recurring contribution

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

I'm not sure if any user-facing docs exist in the first place. We potentially would want orgs to understand what happens when contributions are flagged and rejected. 

Additionally, we need hub staff to understand the quarantine/accept/reject flow. 

#### Have automated unit tests been added? If not, why?

Yes

#### How should this change be communicated to end users?

TBD

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

No

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-2342

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No

2022-11-04 18:41 UTC, nrh-cklimas commented
In your PR description, I think you missed finishing a sentence: 

> In the case of a one-time contribution, an NRE contributor and contribution are created, as well as a Stripe customer and payment intent. In the case

2022-11-04 19:00 UTC, nrh-cklimas requested changes
My request here isn't really code changes--it's almost all about documenting how this process works.

2022-11-04 19:00 UTC, nrh-cklimas commented on spa/src/components/paymentProviders/stripe/StripePaymentForm.js
> +    const { error } = await stripe[stripeClientSecret.startsWith('seti_') ? 'confirmSetup' : 'confirmPayment']({
I'd suggest a comment here to explain why we know that a `seti_` prefix indicates we're setting up a payment. Guessing from your PR description that `seti` = 'setup intent' but it would be good to document this outside the PR.

2022-11-04 19:00 UTC, nrh-cklimas commented on spa/src/components/paymentProviders/stripe/stripeFns.test.ts
> +    expect(search.get('contributionUuid')).toEqual(args.contributionUuid);
```suggestion
    expect(search.get('contributionUuid')).toBe(args.contributionUuid);
```

I think since it's a plain string, we can use the stronger comparison. `toEqual()` is good when asserting on objects.

2022-11-04 19:00 UTC, nrh-cklimas commented on spa/src/components/paymentProviders/stripe/stripeFns.ts
> +  contributionUuid: string;
I've read the PR description a few times but I'm still confused about what the purpose of this is vs. the Stripe client secret. Overall, I think we should get a lot of what you lay out in the PR description (which is pretty well-written!) into some permanent form, either as code comments or a Confluence page. I'd prefer code comments because they're less likely to fall out of date with the code.

2022-11-04 22:01 UTC, njharman requested changes
The documentation from PR, specifically the "this is what/how bad actor works" should be added to docstrings in code, preferably around bad actor code.  [I personally have been at loss as to what "bad actor" means re: code / logic]

2022-11-07 20:04 UTC, benjaminEwhite commented on spa/src/components/paymentProviders/stripe/StripePaymentForm.js
> +    const { error } = await stripe[stripeClientSecret.startsWith('seti_') ? 'confirmSetup' : 'confirmPayment']({
See 3f2a17bbc9

2022-11-07 20:14 UTC, benjaminEwhite commented on spa/src/components/paymentProviders/stripe/stripeFns.ts
> +  contributionUuid: string;
Stripe advises against storing the Stripe Client secret, which I was not aware of when working on original implementation of new checkout flow.  

I've added explanatory comments to the backend code, which seem to me to be the place where the explanation for this field should live.

0d276cfa5

2022-11-07 20:15 UTC, benjaminEwhite commented on spa/src/components/paymentProviders/stripe/stripeFns.ts
> +  contributionUuid: string;
Stripe advises against storing the Stripe Client secret, which I was not aware of when working on original implementation of new checkout flow.  

I've added explanatory comments to the backend code, which seem to me to be the place where the explanation for this field should live.

0d276cfa5

2022-11-07 20:23 UTC, benjaminEwhite commented on apps/contributions/models.py
> +    uuid = models.UUIDField(default=uuid.uuid4, primary_key=False, editable=False)
See [this comment in JIRA](https://news-revenue-hub.atlassian.net/browse/DEV-2342?focusedCommentId=62242) and this commit: 0d276cfa

2022-11-07 20:27 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            # we don't want to save this because it can be used to authorize payment attempt
7236a9de3

2022-11-07 20:30 UTC, benjaminEwhite commented on apps/contributions/serializers.py
>              if self.should_flag(contribution_data["bad_actor_score"]):
56676855

2022-11-07 20:31 UTC, benjaminEwhite commented on apps/contributions/serializers.py
>              # In the case of a flagged contribution, we don't create a Stripe customer or
5c0071086f

2022-11-07 20:34 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        if save:
fea0cce17b

2022-11-07 20:35 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            self.provider_customer_id = customer["id"]
fea0cce17b

2022-11-07 21:18 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            logger.warning(
Good catch on this. Refactored this block and the tests.

a5d14fe0b16

2022-11-07 21:19 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        except ContributionIntervalError:
Added in a5d14fe0b1

2022-11-07 21:26 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +        return bad_actor_score == settings.BAD_ACTOR_FLAG_THRESHOLD
Renamed to `BAD_ACTOR_FLAG_SCORE` and also renamed `BAD_ACTOR_REJECT_THRESHOLD` to `BAD_ACTOR_REJECT_SCORE` so meaning is clearer.  The "threshold" terminology stems from earlier when were rejecting anything above "bad" score (so 4 and 5).

9b3bd5a769

2022-11-08 01:48 UTC, benjaminEwhite commented
FYI -- very strange that the most recent commit pushed up has tests failing. When I run both cypress and Python tests locally, they pass. And there's nothing in that latest push that touched the front end.

2022-11-08 15:04 UTC, nrh-cklimas approved these changes
I'm good with this--recapping what we talked about offline.

- We may want a more descriptive name than `contributionUuid`-- perhaps `engineId` or `internalId`? Not sure.
- The comment strings in the code are good, but I think documenting the problem overall and the solution we took here in Confluence would be helpful.

2022-11-08 15:46 UTC, benjaminEwhite commented
Tests pass this morning. Looks like there were a number of GH status issues yesterday that I assume were behind this. https://www.githubstatus.com/history

2022-11-08 20:16 UTC, njharman approved these changes
gtg

2022-11-17 21:55 UTC, x110dc requested changes
Code looks good. Just one question about changing a threshold for org user creation.

2022-11-17 21:55 UTC, x110dc commented on revengine/settings/base.py
> +BAD_ACTOR_REJECT_SCORE_FOR_ORG_USERS = 4
Why was this changed from 5 to 4 for org users?

2022-11-17 22:20 UTC, benjaminEwhite commented on revengine/settings/base.py
> +BAD_ACTOR_REJECT_SCORE_FOR_ORG_USERS = 4
Good catch.  There was some back and forth around semantics of "threshold" vs. "score" when norm was reviewing, and I think this was a casualty of me making changes around that. Updated.

e460e46fb1cb

2022-11-17 22:23 UTC, x110dc approved these changes

2022-11-17 22:24 UTC, x110dc commented on revengine/settings/base.py
> +BAD_ACTOR_REJECT_SCORE_FOR_ORG_USERS = 4
👍

2023-01-26 15:46 UTC, merged