DEV-2262: add links to stripe on contribution page in django admin
newsrevenuehub/rev-engine pull request #803
Opened 2022-11-03 08:51 UTC by leo-dcfa

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

N/A

#### What's this PR do?

- Add links to open Stripe Dashboard from Django Admin

#### Why are we doing this? How does it help us?

- Easier debugging, allowing fast navigation to Stripe

#### How should this be manually tested? Please include detailed step-by-step instructions.

TBC

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

N/A

#### Have automated unit tests been added? If not, why?

Yes

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

Not sure if this is the Django way of doing things. Didn't feel quite right to return a link from the model, but unsure if there is a better way of doing it

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-2262]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

N/A 

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

N/A

2022-11-07 16:25 UTC, benjaminEwhite requested changes
Looking good overall, but have a couple of requests re: testing.

2022-11-07 21:06 UTC, leo-dcfa commented on apps/contributions/tests/test_payment_managers.py
> +from unittest.mock import ANY, patch
yes, because I updated the factories to include payment_id, customer_id and subscription_d, these values are no longer None for the these contrbutions. But you made a good point above, I should not use `Contribution.objects.all`, which means I can revert these changes

2022-11-07 21:20 UTC, leo-dcfa commented on apps/contributions/tests/test_admin.py
> +                self.contribution_admin.provider_customer_link(contribution) == f"<a href='"
great suggestion, tests updated

2022-11-08 00:38 UTC, benjaminEwhite approved these changes

2022-11-08 00:47 UTC, benjaminEwhite commented on apps/contributions/tests/test_admin.py
> +
These tests can be simplified a little bit, since the ContributionFactory's defaults give us most of what we need.

I confirmed locally that the following works:

```python
def test_provider_payment_link(self):
        contribution = ContributionFactory(provider_payment_id="pi_1234")
        assert (
            self.contribution_admin.provider_payment_link(contribution) == f"<a href='"
            f"https://dashboard.stripe.com/test/connect/accounts/{contribution.stripe_account_id}/payments/{contribution.provider_payment_id}' target='_blank'>{contribution.provider_payment_id}</a>"
        )

    def test_provider_subscription_link(self):
        contribution = ContributionFactory(provider_subscription_id="sub_1234")
        assert (
            self.contribution_admin.provider_subscription_link(contribution) == f"<a href='"
            f"https://dashboard.stripe.com/test/connect/accounts/{contribution.stripe_account_id}/subscriptions/{contribution.provider_subscription_id}' target='_blank'>{contribution.provider_subscription_id}</a>"
        )

    def test_provider_customer_link(self):
        contribution = ContributionFactory(provider_customer_id="cus_1234")
        assert (
            self.contribution_admin.provider_customer_link(contribution) == f"<a href='"
            f"https://dashboard.stripe.com/test/connect/accounts/{contribution.stripe_account_id}/customers/{contribution.provider_customer_id}' target='_blank'>{contribution.provider_customer_id}</a>"
        )

    def test_links_not_available(self):
        contribution = ContributionFactory(
            provider_customer_id=None, provider_subscription_id=None, provider_payment_id=None
        )
        assert self.contribution_admin.provider_customer_link(contribution) == "-"
        assert self.contribution_admin.provider_payment_link(contribution) == "-"
        assert self.contribution_admin.provider_subscription_link(contribution) == "-"
```

2022-11-08 00:50 UTC, benjaminEwhite approved these changes
@leo-dcfa this looks good to me. I made a suggestion to simplify the initialization  of `ContributionFactory` instances, but otherwise 👍 .  No need for me to re-review after dealing with that suggestion.

2022-11-08 06:50 UTC, leo-dcfa commented on apps/contributions/tests/test_admin.py
> +
nice, less good is better. Applied the suggestion.

2022-11-10 00:29 UTC, x110dc approved these changes

2022-11-10 00:30 UTC, merged