NRH-145:  add detail view to donations page
newsrevenuehub/rev-engine pull request #81
Opened 2021-07-15 16:01 UTC by benjaminEwhite

##  What's this PR do?

This PR adds a donation detail view to the donations dashboard. From the list view, you can click on the "Details..." link for any given row and get taken to a detail view that displays additional information.

## How should this be manually tested?

Log in as an org user. Assuming that there contributions have been seeded for the org, got to `/dashboard/donations/` , then click on the "Details..." link for any given row. You'll be taken to the detail view.

2021-07-16 18:08 UTC, JeremyGibson commented on spa/cypress/support/commands.js
> +  cy.intercept({ pathname: getEndpoint(CONTRIBUTIONS) }, (req) => {
Nice

2021-07-16 18:16 UTC, JeremyGibson requested changes
Look into the overflow issue with the `Details` link.

2021-07-19 13:47 UTC, benjaminEwhite commented
@JeremyGibson can you provide more context on the overflow issue?  I'm not sure what this means.

2021-07-19 13:49 UTC, JeremyGibson commented
@benjaminEwhite I put a screenshot in the ticket.

2021-07-20 15:42 UTC, benjaminEwhite commented
Temporarily commenting out the failing test, which we'll run down separately. @JeremyGibson re: your comment about overflow in table, we'll also handle that separately as part of ticket in backlog to make table responsive.

2021-07-20 15:47 UTC, merged