DEV-2299: Update New Page Modal design & functionality
newsrevenuehub/rev-engine pull request #813
Opened 2022-11-08 18:57 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
Updates create new page modal and underlying component that handles the logic
- Cleaning up code smells from previous add page modal
- Design updates to add page modal when user has multiple revenue programs

#### Why are we doing this? How does it help us?
Simplify create new page flow by pushing forward none critial information for the user to add only when it makes sense, not at the beginning. Also addressing code smells, updating create new page modal to match design

#### How should this be manually tested? Please include detailed step-by-step instructions.
Step 1)
- Log in with user that has multiple revenue programs
- Create new page (make sure modal opens to select RP)
- Show errors if needed (example: page limit = 1) or create page successfully

Step 2)
- Login with user with only 1 revenue program (or create a new one and fill in all setup steps)
- Create new page
- Should create page without showing modal or show alert error.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
Yes

#### Have automated unit tests been added? If not, why?
Yes

#### How should this change be communicated to end users?
Simplified create new page flow, only critical information is asked up front and the rest is delayed for when it is important

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-2299

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2022-11-08 21:39 UTC, nrh-cklimas requested changes
Really appreciate the work moving code to TypeScript! A lot of my comments are small style points.

2022-11-08 21:39 UTC, nrh-cklimas commented on spa/src/styles/defaultTheme.d.ts
> -      primary: string;
I haven't seen this approach before--could you talk through why the types are narrowed to constants here?

2022-11-08 21:39 UTC, nrh-cklimas commented on spa/src/components/content/pages/AddPage.tsx
> +      const pages = pagesByRevenueProgram?.find((_) => _.name === rp?.name)?.pages || [];
```suggestion
      const pages = pagesByRevenueProgram?.find(({ name }) => name === rp?.name)?.pages ?? [];
```

2022-11-08 21:39 UTC, nrh-cklimas commented on spa/src/components/content/pages/Pages.test.tsx
> +}));
```suggestion
jest.mock('hooks/useRequest');
```

This can also be done for the useUser mock too, it looks like.

2022-11-08 21:39 UTC, nrh-cklimas commented on spa/src/components/content/pages/Pages.tsx
> +    if ([USER_ROLE_HUB_ADMIN_TYPE, USER_SUPERUSER_TYPE].includes(user?.role_type?.[0] || '')) {
```suggestion
    if ([USER_ROLE_HUB_ADMIN_TYPE, USER_SUPERUSER_TYPE].includes(user?.role_type?.[0] ?? '')) {
```

2022-11-08 21:39 UTC, nrh-cklimas commented on spa/src/components/content/pages/Pages.test.tsx
>      result = await pagesbyRP(inp);
```suggestion
    result = pagesbyRP(inp);
```

2022-11-08 21:39 UTC, nrh-cklimas commented on spa/src/constants/buttonConstants.ts
> +export enum BUTTON_TYPE_ENUM {
We should come to agreement on using enums over string union types and be consistent in the constants directory. I'm of the "enums are overkill" school of thought, but if you feel in favor of them, Ben will need to be our tie-breaker :).

2022-11-08 21:39 UTC, nrh-cklimas commented on spa/src/components/common/Button/NewButton/NewButton.tsx
> +        aria-label={buttonLabel}
I realize this is old code but I'm not sure on this point. If we're setting alt text on the image, shouldn't we not need an `aria-label` here?

2022-11-08 21:39 UTC, nrh-cklimas commented on spa/src/components/common/Modal/AddPageModal/AddPageModal.test.tsx
> +    );
For consistency across tests...

```suggestion
function tree(props?: Partial<AddPageModalProps>)
    render(
      <AddPageModal
        open
        onClose={onClose}
        onClick={onClick}
        revenuePrograms={revenuePrograms}
        {...props}
      />
    );
```

2022-11-08 21:39 UTC, nrh-cklimas commented on spa/src/components/common/Modal/AddPageModal/AddPageModal.test.tsx
> +  it('should show outer error', async () => {
```suggestion
  it('should show outer error', () => {
```

2022-11-08 21:39 UTC, nrh-cklimas commented on spa/src/components/common/Modal/AddPageModal/AddPageModal.test.tsx
> +  it('should not show error message if loading', async () => {
```suggestion
  it('should not show error message if loading', () => {
```

2022-11-08 21:39 UTC, nrh-cklimas commented on spa/src/components/common/Modal/AddPageModal/AddPageModal.test.tsx
> +  it('should disable create button if loading', async () => {
```suggestion
  it('should disable create button if loading', () => {
```

2022-11-08 21:39 UTC, nrh-cklimas commented on spa/src/components/common/Modal/AddPageModal/AddPageModal.tsx
> +  onClick: (revenueProgram: string) => void;
How about we call this `onSubmit` or `onAddPage`?

2022-11-08 21:39 UTC, nrh-cklimas commented on spa/src/components/common/Modal/AddPageModal/AddPageModal.tsx
> +interface AddPageModalType extends InferProps<typeof AddPageModalPropTypes> {
For consistency across components...

```suggestion
export interface AddPageModalProps extends InferProps<typeof AddPageModalPropTypes> {
```

2022-11-10 23:26 UTC, GuiMend commented on spa/src/components/common/Modal/AddPageModal/AddPageModal.tsx
> +  const errorMessage = outerError || errors?.revenueProgram?.message;
I prefeer to leave it as `||` because if it's empty I want the other one to show. If I use `??` it only selects the right-hand side if the first is `null` or `undefined`
![image](https://user-images.githubusercontent.com/9381325/201226978-9854fbb5-31d7-4568-8720-43b0c274b578.png)

2022-11-10 23:30 UTC, GuiMend commented on spa/src/components/common/Modal/AddPageModal/AddPageModal.tsx
> +      component="form"
Think it's a preference questioin. I could wrap the entire modal content into a form, but I opted to add it to the modal (the way I usually do). The main difference in using component=form is: we also remove one additional html tag, and if we have any styles that apply to children, it could mess it up to have an intermediary element

2022-11-10 23:47 UTC, GuiMend commented on spa/src/styles/defaultTheme.d.ts
> -      primary: string;
My tought process here is: the theme values aren't suppossed to change a lot, so it's not needed to have a generic type as "string". And by specifying all the values, we then have TS help in translating what each value is, instead of having to open the `theme.js` file to know what is what.

We use TS not only to help with the theme structure, but also the values itself :)

With specific values:
![image](https://user-images.githubusercontent.com/9381325/201229270-12c06540-4b51-4780-a3ad-e36193ef76ca.png)
![image](https://user-images.githubusercontent.com/9381325/201229599-9b00588b-c8d6-436c-99da-121d36cb1c5d.png)


With generic "string"
![image](https://user-images.githubusercontent.com/9381325/201229440-d42d76af-bee7-47d5-804f-30c2cc9d112a.png)

2022-11-10 23:58 UTC, GuiMend commented on spa/src/constants/buttonConstants.ts
> +export enum BUTTON_TYPE_ENUM {
I used enums here because I had to use it as Type in a style file:

![image](https://user-images.githubusercontent.com/9381325/201230846-ecdc28e1-4624-4d67-9b71-c585b02fdd2a.png)

2022-11-11 00:01 UTC, GuiMend commented on spa/src/components/common/Button/NewButton/NewButton.tsx
> +        aria-label={buttonLabel}
I changed it to the other suggestion of using aria-labelledby, but removing it alltogether I'm not sure I know the answer.

![image](https://user-images.githubusercontent.com/9381325/201231245-f049fce8-c558-440d-90bf-230ce2e5f046.png)

2022-11-14 14:32 UTC, nrh-cklimas commented on spa/src/components/common/Modal/AddPageModal/AddPageModal.tsx
> +  const errorMessage = outerError || errors?.revenueProgram?.message;
Hmm, OK.

2022-11-14 14:34 UTC, nrh-cklimas commented on spa/src/components/content/pages/AddPage.tsx
> +      const pages = pagesByRevenueProgram?.find((_) => _.name === rp?.name)?.pages || [];
I think you changed the `||` to `??` but didn't destructure `name` in the update, unless I misread the diff.

2022-11-14 14:45 UTC, nrh-cklimas commented on spa/src/constants/buttonConstants.ts
> +export enum BUTTON_TYPE_ENUM {
The alternative would look like this:

```tsx
export type NewButtonType = 'page' | 'style';
```

And then you should be able to use `NewButtonType` everywhere you're using `BUTTON_TYPE`. Instead of `props.customType === BUTTON_TYPE.PAGE`, you'd write `props.customType === 'page'`. TypeScript will still flag incorrect usage like `props.customType === 'something else'` and you'll get red squigglies in VS Code as well.

2022-11-16 12:00 UTC, GuiMend commented on spa/src/components/content/pages/AddPage.tsx
> +      const pages = pagesByRevenueProgram?.find((_) => _.name === rp?.name)?.pages || [];
That's right, I missed that change.

2022-11-16 14:16 UTC, nrh-cklimas commented
Code looks good to me, but there are some test failures to resolve.

- In Styles.test.js, button lookups are being done by label but something like this should work:

```tsx
const newStyleButton = screen.getByRole('button', { name: 'New Style' });
```

- In AddPageModal.test.tsx, the name of the dialog has changed in this PR, so the first test fails.

2022-11-16 19:33 UTC, nrh-cklimas approved these changes

2022-11-19 05:34 UTC, x110dc approved these changes

2022-11-19 05:35 UTC, merged