DEV-2610 | Improve CTA to proceed to payment step
newsrevenuehub/rev-engine pull request #815
Opened 2022-11-08 21:00 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

This PR updates the text in the submit buttons for the initial checkout form and Stripe payment form. 

Additionally, it removes some `data-testid` attributes that were around just to allow Cypress queries, in favor of using more a11y-centric cypress-testing-library queries.

#### Why are we doing this? How does it help us?

Better UX for donation pages.

#### How should this be manually tested? Please include detailed step-by-step instructions.

1. Visit a donation page. The text in the initial checkout form should say 'Continue to Payment' if you've chosen a valid amount. 
2. Submit the checkout form.
3. The text in the submit button for the ensuing Stripe payment form should say 'Give <curency symbol> <amount> <frequency>' (with appropriate values substituted for currency symbol, amount, and frequency)

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No

#### Have automated unit tests been added? If not, why?

Yes

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-2610](https://news-revenue-hub.atlassian.net/browse/DEV-2610)

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No

2022-11-09 14:44 UTC, nrh-cklimas commented on spa/cypress/e2e/04-donations.cy.js
> +import { cy } from 'date-fns/locale';
VS Code strikes again

2022-11-09 14:57 UTC, nrh-cklimas requested changes
Mostly thoughts on code organization. Let me know if I can help out with the Cypress failures.

2022-11-09 14:57 UTC, nrh-cklimas commented on spa/src/components/paymentProviders/stripe/stripeFns.ts
> +export function getPaymentElementButtonText({ currencySymbol, amount, frequency }: GetPaymentElementButtonTextArgs) {
Do you see the function being used anywhere but in DonationPage? If not, I feel like it should live with that component in some shape, maybe extracting the submit button into its own component.

2022-11-09 14:57 UTC, nrh-cklimas commented on spa/src/components/paymentProviders/stripe/stripeFns.test.ts
> +    console.log(amount, frequency);
Extraneous console.log

2022-11-09 14:57 UTC, nrh-cklimas commented on spa/cypress/e2e/01-donationPage.cy.js
>  import { LIVE_PAGE_DETAIL, AUTHORIZE_STRIPE_PAYMENT_ROUTE } from 'ajax/endpoints';
I feel mixed about the Cypress changes. I really, really like the idea of lessening our dependence on test IDs. But I also think we'd be better off standardizing on using @cypress/testing-library instead of DIYing it here.

2022-11-09 15:01 UTC, benjaminEwhite commented on spa/cypress/e2e/04-donations.cy.js
> +import { cy } from 'date-fns/locale';
omg vs code.

2022-11-09 15:04 UTC, benjaminEwhite commented on spa/cypress/e2e/01-donationPage.cy.js
>  import { LIVE_PAGE_DETAIL, AUTHORIZE_STRIPE_PAYMENT_ROUTE } from 'ajax/endpoints';
@nrh-cklimas — not sure I understand, these changes all are replacing `data-testid` in favor of cypress testing library — specifically, `findByRole` [as documented here](https://testing-library.com/docs/cypress-testing-library/intro/#examples).

2022-11-09 15:07 UTC, benjaminEwhite commented on spa/cypress/e2e/04-donations.cy.js
> +import { cy } from 'date-fns/locale';
3db0c5910

2022-11-09 15:21 UTC, benjaminEwhite commented on spa/src/components/paymentProviders/stripe/stripeFns.ts
> +export function getPaymentElementButtonText({ currencySymbol, amount, frequency }: GetPaymentElementButtonTextArgs) {
This function will  probably only ever be used in `StripePaymentForm`, and same is true for the submit button it's used in, so I don't see much value in separating out into separate component/file. 

I'd prefer not to convert `StripePaymentForm` to typescript in this PR, but I think it's a good idea to make `getPaymentElementButtonText` type safe, which means that it can't really live inside `StripePaymentForm`.

2022-11-09 15:31 UTC, nrh-cklimas commented on spa/cypress/e2e/01-donationPage.cy.js
>  import { LIVE_PAGE_DETAIL, AUTHORIZE_STRIPE_PAYMENT_ROUTE } from 'ajax/endpoints';
I think I needed more coffee when I was reviewing this morning. My brain saw a lot of `cy.get('form')` calls and thought this was using the old-style assertions. I guess I'll modify my question to ask, do we need to use those scoping calls?

2022-11-09 15:36 UTC, benjaminEwhite commented on spa/cypress/e2e/01-donationPage.cy.js
>  import { LIVE_PAGE_DETAIL, AUTHORIZE_STRIPE_PAYMENT_ROUTE } from 'ajax/endpoints';
In this case, I like scoping to the form in question just as a guarantee that the button indeed lives in the respective form.

2022-11-09 15:39 UTC, nrh-cklimas commented on spa/cypress/e2e/01-donationPage.cy.js
>  import { LIVE_PAGE_DETAIL, AUTHORIZE_STRIPE_PAYMENT_ROUTE } from 'ajax/endpoints';
I don't feel strongly about it, but I think these tests would break if we ever added a second form to the page. Why would we do that? I dunno, but it could happen.

2022-11-09 15:40 UTC, nrh-cklimas approved these changes

2022-11-10 05:32 UTC, x110dc approved these changes

2022-11-11 12:40 UTC, merged