DEV-2632 | Improve copy in Connect to Stripe modal and toast message to clarify what Stripe is and when account creation happens
newsrevenuehub/rev-engine pull request #825
Opened 2022-11-10 17:42 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

This PR updates copy and tweaks styling on the Stripe Connect modal and toast components.

The ticket requires that the "Need help? Check out our FAQ" copy be added to the connect toast component, so I moved that into a separate component that can be shared by both `ConnectStripeModal` and `ConnectStripeToast`.

#### Why are we doing this? How does it help us?

Make the why and how of Stripe connection more obvious to new users 

#### How should this be manually tested? Please include detailed step-by-step instructions.

Go through the "new account" flow in the review app.

When first presented with the `ConnectStripeModal`, compare to requirements from ticket. 

Click "I'll connect to Stripe later" to hide modal and cause the `ConnectStripeToast` to appear. 

Inspect the toast component and compare to requirements from ticket.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No

#### Have automated unit tests been added? If not, why?

No. This is just copy changes and styling tweaks, so didn't seem necessary. 

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-2632](https://news-revenue-hub.atlassian.net/browse/DEV-2632)

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

N/A

2022-11-14 15:02 UTC, nrh-cklimas requested changes

2022-11-14 15:02 UTC, nrh-cklimas commented on spa/src/components/dashboard/connectStripe/ConnectStripeNeedHelpCTA.tsx
> +import * as S from './ConnectStripeNeedHelpCTA.styled';
Destructure this import?

2022-11-14 15:03 UTC, nrh-cklimas commented on spa/src/components/dashboard/connectStripe/ConnectStripeNeedHelpCTA.tsx
> +}
We should add tests for this component, as simple as it is. I'd go with a simple "is accessible" check and also test that the link is present and points to the correct URL.

2022-11-15 14:17 UTC, benjaminEwhite commented on spa/src/components/dashboard/connectStripe/ConnectStripeNeedHelpCTA.styled.ts
> +export const CheckOutOur = styled.span`
aa2d3a7e71e

2022-11-15 14:46 UTC, benjaminEwhite commented on spa/src/components/dashboard/connectStripe/ConnectStripeNeedHelpCTA.tsx
> +import * as S from './ConnectStripeNeedHelpCTA.styled';
40bb2efd8bf 

Ended up removing the `* as S` from the toast `ConnectStripeElements.js` and `ConnectStripeToast` as well.

2022-11-15 14:56 UTC, benjaminEwhite commented on spa/src/components/dashboard/connectStripe/ConnectStripeNeedHelpCTA.tsx
> +}
e302c5bdc24

2022-11-15 14:59 UTC, benjaminEwhite commented on spa/src/components/dashboard/connectStripe/ConnectStripeNeedHelpCTA.tsx
> +}
e302c5bdc24

2022-11-15 20:59 UTC, x110dc approved these changes

2022-11-22 00:46 UTC, merged