DEV-2870 | Create SystemNotification Component
newsrevenuehub/rev-engine pull request #840
Opened 2022-11-17 19:32 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

This PR adds a `SystemNotification` component to the SPA. This component will be used in parent ticket [DEV-2613 | Notify user when partial Stripe connection successfully completes (and build out new system notification component)](https://news-revenue-hub.atlassian.net/browse/DEV-2613) to display notification to user when Stripe account has been successfully completed. It is also expected to be used more widely for other system notifications in the future.

Please consult the JIRA ticket ([DEV-2780](https://news-revenue-hub.atlassian.net/browse/DEV-2870)) to get link to design files.

#### Why are we doing this? How does it help us?

Subtask for [DEV-2613](https://news-revenue-hub.atlassian.net/browse/DEV-2613) which will improve UX for newly onboarded org users such that it's obvious when their account is ready to publish pages.

#### How should this be manually tested? Please include detailed step-by-step instructions.

For this subtask PR, just look at the `SystemNotification` component in Storybook and compare to the Figma file.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No.

#### Have automated unit tests been added? If not, why?

Yes.

## How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

No

#### What are the relevant tickets? Add a link to any relevant ones.

- [DEV-2780](https://news-revenue-hub.atlassian.net/browse/DEV-2870)
- [DEV-2613](https://news-revenue-hub.atlassian.net/browse/DEV-2613)

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

This will unblock [DEV-2613](https://news-revenue-hub.atlassian.net/browse/DEV-2613)

2022-11-17 19:57 UTC, nrh-cklimas requested changes
Small changes here and there, overall seems good to me.

Could we move this into either components/common or components/base? I want to long-term deprecrate stuff under elements/ in favor of these two directories so there's a clear split between old stuff and new.

2022-11-17 19:57 UTC, nrh-cklimas commented on spa/src/elements/systemNotification/SystemNotification.styled.ts
> +function getIconBoxBackground({ notificationType }: { notificationType: SystemNotificationTypes }) {
I think this could just be a `Record<SystemNotificationTypes, string>` with a lookup in the style definition.

2022-11-17 19:57 UTC, nrh-cklimas commented on spa/src/elements/systemNotification/SystemNotification.styled.ts
> +function getHeaderColor({ notificationType }: { notificationType: SystemNotificationTypes }) {
Same thought as above--doesn't need to be a function.

2022-11-17 19:57 UTC, nrh-cklimas commented on spa/src/elements/systemNotification/SystemNotification.styled.ts
> +interface HeaderProps extends IconBoxProps {}
```suggestion
type HeaderProps = IconBoxProps;
```

2022-11-17 19:57 UTC, nrh-cklimas commented on spa/src/elements/systemNotification/SystemNotification.tsx
> +interface SystemNotificationProps {
The pattern we settled on for components was to create prop types, then use `InferProps` to generate a baseline type definition. That way, we can get runtime checking. See https://github.com/newsrevenuehub/rev-engine/blob/main/spa/src/components/common/ValueOrPlaceholder/ValueOrPlaceholder.tsx for an example of the pattern.

2022-11-17 19:57 UTC, nrh-cklimas commented on spa/src/elements/systemNotification/SystemNotification.tsx
> +  handleClose: Function;
```suggestion
  handleClose: () => void;
```

Prevents you from using the wrong function signature.

2022-11-17 19:57 UTC, nrh-cklimas commented on spa/src/elements/systemNotification/commonTypes.ts
> +export type SystemNotificationTypes = typeof notificationTypeValues[number];
Nitpick: how about `SystemNotificationType` instead? It feels weird to have a singular value have a plural type name.

2022-11-17 19:57 UTC, nrh-cklimas commented on spa/src/elements/systemNotification/SystemNotification.tsx
> +  let Icon;
I think this would be easier with a record lookup, similar to my comment in the style file.

2022-11-17 19:57 UTC, nrh-cklimas commented on spa/src/elements/systemNotification/SystemNotification.tsx
> +        <p>{body}</p>
This sticks out to me because someday we might want a notification that has multiple paragraphs or some styling inside it. My recommendation would be to use the `children` prop for this instead of a string prop.

2022-11-17 19:57 UTC, nrh-cklimas commented on spa/src/elements/systemNotification/SystemNotification.tsx
> +      <IconButton onClick={() => handleClose()} aria-label="close notification">
```suggestion
      <IconButton onClick={handleClose} aria-label="close notification">
```

2022-11-17 19:57 UTC, nrh-cklimas commented on spa/src/elements/systemNotification/SystemNotification.test.tsx
> +  it.each(notificationTypeValues)('should be accessible when type is %p', async (notificationType) => {
Something to consider, but isn't a must-- use a function like this to cut down on boilerplate:

```tsx
function tree(props?: Partial<SystemNotificationProps>) {
  return render(<SystemNotification handleClose={jest.fn()} header="Notification header!" {...props} />);
}
```

You might have to specify more defaults here, but it saves you from having to specify irrelevant props on each test.

2022-11-17 19:57 UTC, nrh-cklimas commented on spa/src/elements/systemNotification/SystemNotification.test.tsx
> +import { screen, fireEvent } from '@testing-library/react';
These should also get imported from `test-utils`.

2022-11-17 20:04 UTC, benjaminEwhite commented on spa/src/elements/systemNotification/SystemNotification.test.tsx
> +import { screen, fireEvent } from '@testing-library/react';
7161a07c45

2022-11-17 20:10 UTC, benjaminEwhite commented
Re: 

> Could we move this into either components/common or components/base? I want to long-term deprecrate stuff under elements/ in favor of these two directories so there's a clear split between old stuff and new.

See abe4d79e7057

2022-11-17 20:11 UTC, benjaminEwhite commented
Love that Cypress has failing tests when this code has touched  _**zero**_ lines of code that Cypress cares about.

2022-11-17 20:12 UTC, benjaminEwhite commented on spa/src/elements/systemNotification/SystemNotification.tsx
> +  handleClose: Function;
630271cb7d

2022-11-17 20:27 UTC, benjaminEwhite commented on spa/src/elements/systemNotification/SystemNotification.styled.ts
> +function getIconBoxBackground({ notificationType }: { notificationType: SystemNotificationTypes }) {
Now I know about `Record`s ...

40a0d8b56ab

2022-11-17 20:27 UTC, benjaminEwhite commented on spa/src/elements/systemNotification/SystemNotification.styled.ts
> +function getHeaderColor({ notificationType }: { notificationType: SystemNotificationTypes }) {
40a0d8b56ab

2022-11-17 20:35 UTC, benjaminEwhite commented on spa/src/elements/systemNotification/SystemNotification.tsx
> +  let Icon;
935b87471

2022-11-17 20:40 UTC, benjaminEwhite commented on spa/src/elements/systemNotification/SystemNotification.tsx
> +        <p>{body}</p>
ae2984861aa

2022-11-17 20:43 UTC, benjaminEwhite commented on spa/src/elements/systemNotification/SystemNotification.tsx
> +interface SystemNotificationProps {
Started going down that path and got blocked by not knowing how to make `SystemNotificationProps.type` more strongly typed than just being a string, based on infer props. Will dig some more and try to figure out how to do this, but if you have any pointers, please let me know @nrh-cklimas.

2022-11-17 20:49 UTC, benjaminEwhite commented on spa/src/elements/systemNotification/SystemNotification.tsx
> +interface SystemNotificationProps {
Ahhhh... `extends` is my friend.

2022-11-17 20:52 UTC, benjaminEwhite commented on spa/src/elements/systemNotification/SystemNotification.tsx
> +interface SystemNotificationProps {
ec7941afe47

2022-11-17 20:54 UTC, benjaminEwhite commented on spa/src/elements/systemNotification/commonTypes.ts
> +export type SystemNotificationTypes = typeof notificationTypeValues[number];
2b5d0b8c4f8

2022-11-17 21:11 UTC, benjaminEwhite commented on spa/src/elements/systemNotification/SystemNotification.test.tsx
> +  it.each(notificationTypeValues)('should be accessible when type is %p', async (notificationType) => {
f1e121498aa

2022-11-18 14:24 UTC, nrh-cklimas commented on spa/src/components/common/SystemNotification/SystemNotification.tsx
> +  children: ReactChild | ReactChild[];
```suggestion
  children: ReactNode;
```
This is just React + TypeScript trivia.

2022-11-18 14:25 UTC, nrh-cklimas approved these changes
Looks good to me now apart from a nitpick on types.

2022-11-22 20:59 UTC, x110dc approved these changes

2022-11-23 17:29 UTC, merged