[WIP] DEV-2750 | Stripe onboarding modal transition is delayed
newsrevenuehub/rev-engine pull request #841
Opened 2022-11-17 23:33 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2022-11-18 15:00 UTC, nrh-cklimas requested changes

2022-11-18 15:00 UTC, nrh-cklimas commented on spa/src/components/dashboard/Dashboard.test.tsx
> +  it('shows a loading status when Stripe account link status is loading', () => {
Could we add a test for the opposite, to prove the component doesn't get stuck in loading? I think it could literally be the opposite of this test.

2022-11-18 15:14 UTC, benjaminEwhite commented on spa/src/components/dashboard/Dashboard.test.tsx
> +  it('shows a loading status when Stripe account link status is loading', () => {
See 0c4e300

2022-11-18 15:15 UTC, nrh-cklimas approved these changes

2022-11-19 13:16 UTC, x110dc approved these changes

2022-11-22 01:32 UTC, merged