DEV-2231: Build out "Export" CTA on Contributions dashboard
newsrevenuehub/rev-engine pull request #845
Opened 2022-11-18 23:59 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
Creates the UI + wire-ups Export Data Button & it's confirmation modal

#### Why are we doing this? How does it help us?
Adds functionality for the user to receive in their email a csv file containing the information for all contributions

#### How should this be manually tested? Please include detailed step-by-step instructions.
As of now you can only test UI (functionality is blocked by [DEV-2230](https://news-revenue-hub.atlassian.net/browse/DEV-2230))
- Open storybook, check `Common/Button/ExportButton`
- Make sure design matches figma (Export button + confirmation modal + sending/loading)

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
Yes

#### Have automated unit tests been added? If not, why?
Yes

#### How should this change be communicated to end users?
New feature to export all contribution data in csv and receive it via email to be downloaded

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-2231

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
Completion blocked by: https://news-revenue-hub.atlassian.net/browse/DEV-2230

2022-11-21 14:46 UTC, nrh-cklimas requested changes

2022-11-21 14:46 UTC, nrh-cklimas commented on spa/src/components/common/Hero/Hero.tsx
> +  subtitle: undefined,
I think these undefined defaults can just be omitted.

2022-11-21 14:46 UTC, nrh-cklimas commented on spa/src/components/common/Button/ExportButton/ExportButton.test.tsx
> +  it('should render publish button', () => {
```suggestion
  it('should render an enabled export button', () => {
```

2022-11-21 14:46 UTC, nrh-cklimas commented on spa/src/components/common/Button/ExportButton/ExportButton.test.tsx
> +  it('should open export modal when clicked', async () => {
```suggestion
  it('should open export modal when the export button is clicked', async () => {
```

2022-11-21 14:46 UTC, nrh-cklimas commented on spa/src/components/common/Button/ExportButton/ExportButton.test.tsx
> +  it('should be disabled if export is confirmed in modal', async () => {
```suggestion
  it('should disabled the export button if export is confirmed in modal', async () => {
```

2022-11-21 14:46 UTC, nrh-cklimas commented on spa/src/components/common/Button/ExportButton/ExportButton.test.tsx
> +  it('should show tooltip if button disabled and hovered', async () => {
```suggestion
  it('should show tooltip on the export button if it is disabled', async () => {
```

2022-11-21 14:46 UTC, nrh-cklimas commented on spa/src/components/common/Button/ExportButton/ExportButton.test.tsx
> +    const button = screen.getByRole('button', { name: /Export/i });
It would be nice to put the logic of opening the modal into a function, e.g.

```tsx
async function openModal() {
  const button = screen.getByRole('button', { name: /Export/i });

  fireEvent.click(button);
  await waitFor(() => expect(screen.getByRole('presentation')).toBeVisible();
}
```

2022-11-21 14:46 UTC, nrh-cklimas commented on spa/src/components/common/Button/ExportButton/ExportButton.tsx
> +  const exportData = useCallback(() => {
I get that this is a placeholder function--if we're just waiting for backend to get done and then this PR will get updated, I'm fine with this. If we want to merge this and then do a followup story to update this once the backend work is ready, I think we should change this to throw an error like `Export not implemented yet` so that if this accidentally is visible to actual users, we know ASAP through Sentry.

2022-11-21 14:46 UTC, nrh-cklimas commented on spa/src/components/common/Button/ExportButton/ExportModal/ExportModal.styled.tsx
> +export const Modal = styled(MuiModal)`
Could this use base/modal instead?

2022-11-22 17:09 UTC, GuiMend commented on spa/src/components/common/Button/ExportButton/ExportButton.tsx
> +  const exportData = useCallback(() => {
I was thinking of waiting until the endpoint is done before merging this PR.

2022-11-22 18:38 UTC, nrh-cklimas approved these changes

2022-12-12 20:24 UTC, nrh-cklimas requested changes

2022-12-12 20:25 UTC, GuiMend commented on spa/src/components/common/Button/ExportButton/ExportButton.tsx
> +    setTimeout(() => setLoading(false), 30000);
Correct. I've fixed it in the follow up PR but as this will be merged before that one is introduced I'll fix it here as well.

2022-12-12 20:39 UTC, GuiMend commented on spa/src/components/common/Button/ExportButton/ExportButton.tsx
> +          setTimeout(() => setLoading(false), 30000);
No, because we want to avoid the user dispatching several exports at once. So this 30s is a cooldown for the user to wait a bit and check their email

2022-12-12 20:40 UTC, nrh-cklimas commented on spa/src/components/common/Button/ExportButton/ExportButton.tsx
> +          setTimeout(() => setLoading(false), 30000);
I see.

2022-12-12 20:40 UTC, nrh-cklimas approved these changes

2022-12-14 20:31 UTC, x110dc approved these changes

2022-12-14 20:51 UTC, merged