DEV-2783: Update layout in receipt emails (add required tax information, contributor portal link, and refer to RP in copyright)
newsrevenuehub/rev-engine pull request #851
Opened 2022-11-21 18:15 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
Create email template ✔️ 
Next steps.. ?

#### What's this PR do?
Create email template to send to user after contribution is made.

#### Why are we doing this? How does it help us?
Improves the template's design and adds additional information

#### How should this be manually tested? Please include detailed step-by-step instructions.
Not sure

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
Yes

#### Have automated unit tests been added? If not, why?
No

#### How should this change be communicated to end users?
Contribution emails were updated to show additional information + match the UI/UX design of the platform.

#### Are there any smells or added technical debt to note?
No

#### Has this been documented? If so, where?
No

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-2783

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
No

2022-11-22 15:08 UTC, nrh-cklimas requested changes
I haven't worked with HTML emails in a good long while so I might be off on some suggestions.

2022-11-22 16:01 UTC, GuiMend commented on apps/emails/templates/nrh-default-contribution-confirmation-email-temporary.html
> +            <table style="font-family:'Lato',sans-serif;" role="presentation" cellpadding="0" cellspacing="0"
Removed Lato, this was a mistake.

2022-11-22 18:35 UTC, nrh-cklimas approved these changes

2022-11-23 16:25 UTC, benjaminEwhite requested changes
Code here seems fine in isolation, but I compared the designs for this email with the designs for recurring contribution reminders ([DEV-2381](https://news-revenue-hub.atlassian.net/browse/DEV-2831)) and it looks like there's a lot of overlap for the "Contribution details" section for both emails (with slight variation).

We should probably abstract that part out into a reusable block instead of repeating. That can possibly be a subtask, or happen here.  Can discuss more in Slack or JIRA.

2022-11-25 14:52 UTC, GuiMend commented
@benjaminEwhite , would this be what you are talking about? The only issue I have is that I don't know how I would test the email block.

https://github.com/newsrevenuehub/rev-engine/pull/862

2022-11-29 01:47 UTC, benjaminEwhite requested changes
@GuiMend I reviewed more closely vis-a-vis the requirements for copy from the JIRA ticket, and made suggestions to fix some of the conditional copy in the templates.

It's possible there will be some issues with spaces/line breaks, but we can catch those once you accept changes and we can try out in review app.

2022-11-29 01:47 UTC, benjaminEwhite commented on apps/emails/templates/nrh-default-contribution-confirmation-email-temporary.html
> +<!DOCTYPE HTML
Don't think we need this temporary file. We should catch any issues with the template in QA, and we  always have Git history if we need to revert.

2022-11-29 01:47 UTC, benjaminEwhite commented on apps/emails/templates/nrh-default-contribution-confirmation-email-temporary.txt
> +Thank you for your contribution!
Same here. Get rid of temporary file, and just make changes in the original template file.

2022-11-29 01:47 UTC, benjaminEwhite commented on apps/emails/templates/nrh-default-contribution-confirmation-email.html
> +                  </p>
Didn't catch this the first time through, but looking at [this comment in the JIRA ticket,](https://news-revenue-hub.atlassian.net/browse/DEV-2783?focusedCommentId=61976) this part of the template needs to be changed along these lines:

```suggestion
                  <p class="disclaimer inner-center">
                    No goods or services were provided in exchange for this contribution.&nbsp;
                    {% if non_profit %}
                    This receipt may be used for tax purposes.&nbsp;
                    {{ rp_name }} is a 501(c)(3) nonprofit organization {% if tax_id %}with a Federal Tax ID
                    #{{tax_id}}{% endif %}.
                    {% else %}
                    Contributions to {{ rp_name }} are not deductible as charitable donations.
                    {% endif %}
                  </p>
```

Note that I've renamed `org_name` to `rp_name` because that's what is called for in ticket. 

I've also renamed `for_profit` to `non_profit`, which is the original name on the revenue program model. This should be a little more straightforward than negating the model field name.

2022-11-29 01:47 UTC, benjaminEwhite commented on apps/emails/templates/nrh-default-contribution-confirmation-email.html
> +                      <p style="font-size: 14px; line-height: 140%; font-family: Roboto, sans-serif;">©{{ copyright_year }} {{ org_name }} All
This should also reference `rp_name`, not `org_name`.

```suggestion
                      <p style="font-size: 14px; line-height: 140%; font-family: Roboto, sans-serif;">©{{ copyright_year }} {{ rp_name }} All
```

2022-11-29 01:47 UTC, benjaminEwhite commented on apps/emails/templates/nrh-default-contribution-confirmation-email.txt
> +{% endif %}.
```suggestion
No goods or services were provided in exchange for this contribution.
{% if non_profit %}
This receipt may be used for tax purposes.
{{ rp_name }} is a 501(c)(3) nonprofit organization {% if tax_id %}with a Federal Tax ID #{{tax_id}}{% endif %}.
{% else %}
Contributions to {{ rp_name }} are not deductible as charitable donations.
{% endif %}
```

2022-11-29 01:47 UTC, benjaminEwhite commented on apps/contributions/tests/test_models.py
> +            "nrh-default-contribution-confirmation-email-temporary.html",
I don't understand advantage of having temporary in short term. There's not really any risk of something breaking, and UAT will catch any issues.

2022-11-29 01:47 UTC, benjaminEwhite commented on apps/contributions/models.py
> +                    # "for_profit": '',
See comments below. This is better as original field name from RP.

```suggestion
                    # "non_profit": '',
```

2022-11-29 01:47 UTC, benjaminEwhite commented on apps/contributions/models.py
> +                    # "last_name": '',
[As it turns out,](https://news-revenue-hub.atlassian.net/browse/DEV-2892?focusedCommentId=64466) we'll be getting full name from the Stripe Customer name field, so let's rename to a single field called `contributor_name`:

```suggestion
                    # "contributor_name": '',
```

2022-11-29 01:47 UTC, benjaminEwhite commented on apps/contributions/models.py
> +                    # "company_type": '',
This is not something we track, and not necessary to render the template.

```suggestion
```

2022-11-29 17:47 UTC, GuiMend commented on apps/emails/templates/nrh-default-contribution-confirmation-email.html
> +                  </p>
Didn't see that comment when working in this ticket. Thanks for pointing that out.

2022-11-29 19:11 UTC, benjaminEwhite requested changes
@GuiMend this looks good overall.

I made some slight changes to the suggested commits, adding in placeholder values, just so we can see everything flow through in review app. I'm leaving those for you to commit (didn't want to step on your toes) and then you can resolve those conversations.

Also, added a note re: logo not being dynamic (at least as far as I know) and next steps for getting that in place.

Two more small requests re: PR at high level. 

First, would you mind updating the PR description in light of removing the temporary file names?

Second, I think I now understand reasoning behind using those temp names because the base for this branch is main. In retrospect, I would have probably created a parent "holding" branch that eventually gets merged into main, and then had a branch+ticket for your template  as well as the branch+ticket for the work I did to supply context variables (in DEV-2892).  

In this case, our ticket structure didn't quite align with this, so think easiest thing to do is to make DEV-2892 a blocker for merging this into main.  The branch for the PR for that ticket branched from this DEV-2783 branch, and the 2892 PR has this (DEV-2783) as its base. 

After DEV-2892 gets merged into this branch, we should be able to get full QA for DEV-2783 ticket overall through, and then can merge this branch into main.

Given all of the above, would you mind updating the "Plan" so the steps are clear?  

I'm going to go ahead and note in JIRA that DEV-2783 is blocked by DEV-2892. 

No need for me to re-review after these things.

2022-11-29 19:11 UTC, benjaminEwhite commented on apps/emails/templates/nrh-default-contribution-confirmation-email.html
> +                  <img class="logo inner-center" src="{{ logo }}">
Missed this in earlier reviews, but AFAIK, for now logo in these emails is the NRE one, not per RP.  That means don't need to send as context variable.

Instead, you should ask Rachel for where to find the yellow NRE logo and then store that file with an appropriate name in `revengine/static` (alongside the existing `NewsRevenueHub-Horizontal.png` which is a blue version of the logo).

Then, this should be updated to:

```
<img class="logo inner-center" src="{% static 'new-logo-file-name.png' %}" alt="NRE logo" >
```

(See Django docs on static files in templates [here](NewsRevenueHub-Horizontal)).

2022-11-29 19:30 UTC, benjaminEwhite commented on apps/emails/templates/nrh-default-contribution-confirmation-email.txt
> +Need to make changes to your contribution? {% autoescape off %}{{ magic_link }}{% endautoescape %}
I genuinely not know answer to this, but given that `magic_link` will already be wrapped in `mark_safe` ([see here in pending PR](https://github.com/newsrevenuehub/rev-engine/pull/868/files#diff-80bc4fbf647c521d99e0b1e9e38a568c928ed7477e600e7bd110a8e9bc870ae1R82)), I'm not sure if we'll need `autoescape off` here.

Once #868 is merged, we should try removing this and see if text email works without it.

2022-11-30 19:27 UTC, GuiMend commented on apps/emails/templates/nrh-default-contribution-confirmation-email.html
> +                  <img class="logo inner-center" src="{{ logo }}">
@benjaminEwhite , I'm not able to commit the static image. For some reason it's being ignored by git and I already checked .gitignore and it didn't seem to solve the issue
![image](https://user-images.githubusercontent.com/9381325/204890432-36bccf91-5712-47cd-86c2-fec3aa93790d.png)

2022-11-30 19:31 UTC, GuiMend commented on apps/emails/templates/nrh-default-contribution-confirmation-email.txt
> +Need to make changes to your contribution? {% autoescape off %}{{ magic_link }}{% endautoescape %}
Ok

2022-11-30 20:11 UTC, GuiMend commented on apps/emails/templates/nrh-default-contribution-confirmation-email.html
> +                  <img class="logo inner-center" src="{{ logo }}">
I force added the file 👍

2022-12-22 21:45 UTC, benjaminEwhite approved these changes

2022-12-23 12:28 UTC, GuiMend commented on apps/emails/templates/nrh-default-contribution-confirmation-email.txt
> +Need to make changes to your contribution? {% autoescape off %}{{ magic_link }}{% endautoescape %}
Hey @benjaminEwhite, not sure how to test this after making the changes. Could you tell me how to test?

2022-12-28 15:59 UTC, GuiMend commented on apps/emails/templates/nrh-default-contribution-confirmation-email.txt
> +Need to make changes to your contribution? {% autoescape off %}{{ magic_link }}{% endautoescape %}
Didn't work. Leaving it as is and resolving comment.

2023-01-10 16:53 UTC, benjaminEwhite reviewed
@GuiMend looking at PR write up, I see

> This PR used the same base template as https://github.com/newsrevenuehub/rev-engine/pull/871, so we need to merge that one before merging this one.

Looks like 871 was merged. Is there a TODO for this on this branch?

Code changes seem fine. Only thing that caught my eye was that we don't have any tests around what actually renders in the thank you email template based on for profit / non profit, etc, and ideally we'd test that.

We do have tests that show that `send_templated_email` gets called with the right context variables, but that alone is not a guarantee that our template is well formatted and displays as expected.

@GuiMend I'd be happy to write a test for this, though you're also welcome to have a go. If you'd like me to handle, please create a subtask in JIRA and assign to me. Should be able to get to it tomorrow. I'll merge directly into this branch, but having the separate subtask assigned to me will keep ownership and status clear in JIRA.

2023-01-11 16:38 UTC, benjaminEwhite approved these changes
Assuming this comment from earlier doesn't require next steps...

> @GuiMend looking at PR write up, I see
> 
> This PR used the same base template as https://github.com/newsrevenuehub/rev-engine/pull/871, so we need to merge that one before merging this one.
> 
> Looks like 871 was merged. Is there a TODO for this on this branch?

... this LGTM. Approved.

2023-01-12 15:07 UTC, GuiMend commented
The updates needed were done already 👍

2023-01-13 22:53 UTC, x110dc approved these changes

2023-01-13 22:53 UTC, merged