DEV-2613 | notify user when partial stripe connection successfully completes and build out new system notification component
newsrevenuehub/rev-engine pull request #852
Opened 2022-11-21 20:27 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

For now, this PR has DEV-2870 as its base because it presupposes those changes, but they have not yet been merged into main. I did this so that the narrow diff for this ticket can be easily reviewed in isolation of review of the System Notification component which has already been reviewed by @nrh-cklimas .

Once DEV-2870 has been merged, the base for this PR should be switched to `main`.

#### What's this PR do?

This PR modifies the org dashboard so that a system notification is displayed after a Stripe is successfully connected.

#### Why are we doing this? How does it help us?

To Improve UX for newly onboarded org users such that it's obvious when their account is ready to publish pages

#### How should this be manually tested? Please include detailed step-by-step instructions.

Go through the account onboarding flow in the review app, inclusive of Stripe onboarding. After you've done the required round trips to fully connect Stripe, back in the org dashboard, you should eventually see a system notification element in the bottom right hand corner indicating that Stripe connection is done and you can publish pages.  At this point, the "Connect to Stripe" toast should no longer display.

Click the "x" button in the top right of the system notification to close it.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No

#### Have automated unit tests been added? If not, why?

Yes

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-2613 | Notify user when partial Stripe connection successfully completes](https://news-revenue-hub.atlassian.net/browse/DEV-2613)

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No

2022-11-21 22:04 UTC, nrh-cklimas requested changes

2022-11-21 22:13 UTC, benjaminEwhite commented on spa/src/components/dashboard/Dashboard.js
> +      {displayConnectionSuccess && (
My inclination here would be to keep as is so can deliver business value in short term without significant refactoring, and then for us to converge on a notification approach (e.g., notistack) in a ticket whose aim is specifically around improving notifications.

I'm going to move this conversation to JIRA so can get Mariclare's input.

2022-11-22 11:55 UTC, benjaminEwhite commented on spa/src/components/dashboard/Dashboard.styled.js
> +  position: absolute;
500c5e7754

2022-11-22 13:13 UTC, benjaminEwhite commented on spa/src/components/dashboard/Dashboard.test.tsx
> +    axiosMock.onPost(getStripeAccountLinkStatusPath(rpId)).reply(200, { requiresVerification: false });
I agree and started to go down that path, but I wanted to test the functionality around closing the system notification, and didn't see an obvious way to do that if I mocked `useConnectStripeAccount` because the `hideConnectionStatus` function needs to toggle an state variable (displayConnectionStatus) that is internal to `useConnectStripeAccount`.

2022-11-22 15:56 UTC, nrh-cklimas commented on spa/src/components/dashboard/Dashboard.js
> +      {displayConnectionSuccess && (
Recording here that we decided to punt to a followup story

2022-11-22 16:01 UTC, benjaminEwhite commented on spa/src/components/dashboard/Dashboard.test.tsx
> +    axiosMock.onPost(getStripeAccountLinkStatusPath(rpId)).reply(200, { requiresVerification: false });
44d3509687

2022-11-22 16:20 UTC, nrh-cklimas approved these changes

2022-11-22 20:43 UTC, x110dc approved these changes

2022-11-29 20:12 UTC, merged