DEV-2892  provide requested data for receipt emails
newsrevenuehub/rev-engine pull request #868
Opened 2022-11-29 12:04 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

The branch for this PR branches from #DEV-2783-update-layout-in-receipt-emails-add-required-tax-information-contributor-portal-link-and-refer-to-rp-in-copyright, and that is also the base for this PR.

DEV-2783-update-layout-in-receipt-emails-add-required-tax-information-contributor-portal-link-and-refer-to-rp-in-copyright is being reviewed separately and will eventually be merged into main, while this branch narrowly provides changes to support the new thank you email template.

#### What's this PR do?

This PR supplies additional context variables to the task that sends thank you emails.

It also refactors that functionality, creating a new task called `send_thank_you_email` that is responsible for both retrieving the Stripe customer and sending the email. The new template requires customer name be supplied, and that data is currently only stored in Stripe on the Customer object. 

Since both sending the email and retrieving the Stripe customer can be "laggy" and possibly fail, I chose to create a new, single task that handles both of those steps, so that the `payment_success` view won't be slowed down or stopped by anything related to sending thank you emails.

#### Why are we doing this? How does it help us?

Better user experience for receipt emails.

#### How should this be manually tested? Please include detailed step-by-step instructions.

Make a contribution in the review app for an RP whose org has `send_receipt_email_via_nre` set to `True`.

Check your inbox for a thank you email. Should contain expected copy, as detailed in the JIRA ticket.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No

#### Have automated unit tests been added? If not, why?

Yes

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-2892](https://news-revenue-hub.atlassian.net/browse/DEV-2892)
[DEV-2783](https://news-revenue-hub.atlassian.net/browse/DEV-2783)

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

N/A

2022-11-29 12:07 UTC, benjaminEwhite commented on apps/api/views.py
> +def _construct_rp_domain(subdomain, referer=None):
NB: This method gets renamed to `construct_rp_domain` in [DEV-2832](https://news-revenue-hub.atlassian.net/browse/DEV-2832).  Once that's been merged into `main`, references to this function in this PR will need to be updated.

2022-12-01 19:28 UTC, njharman requested changes
Couple minor things that may be moot. [I didn't dig into all the logic, just what the code seemed to make possible]

2022-12-05 15:55 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            self.provider_customer_id, stripe_account=self.revenue_program.payment_provider.id
Shored this up:

f5f6659cd

2022-12-05 18:28 UTC, njharman approved these changes

2022-12-06 00:53 UTC, x110dc approved these changes

2022-12-07 15:37 UTC, merged