DEV-2831: Update email layout for recurring contributions
newsrevenuehub/rev-engine pull request #871
Opened 2022-11-29 18:25 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

This is the second of three planned stacked PRs to deliver the parent ticket [DEV-708](https://news-revenue-hub.atlassian.net/browse/DEV-2832)

1. (https://github.com/newsrevenuehub/rev-engine/pull/835) (corresponding to [DEV-2832 | Delivery management for new transactional email: recurring contribution reminder](https://news-revenue-hub.atlassian.net/browse/DEV-2832)
2. (https://github.com/newsrevenuehub/rev-engine/pull/871) (corresponding to [DEV-2831 | Layout for new transactional email: recurring contribution reminder](https://news-revenue-hub.atlassian.net/browse/DEV-2831)) - **THE CURRENT PR**
3. A future PR of branch DEV-708 (the base for this PR) into main. That PR has not yet been created in order to conserve review app slots. That branch will be solely for handling any merge conflicts ahead of merging into main.

Note that this PR initially takes DEV-2832 as its base, as it presupposes those changes. Once DEV-2832 has been merged into DEV-708, the base for this branch should be switched to DEV-708.

#### What's this PR do?
Updates the email layout for Recurring contributions to match design

#### Why are we doing this? How does it help us?
We didn't have an existing email. More information on parent PR (https://github.com/newsrevenuehub/rev-engine/pull/835)

#### How should this be manually tested? Please include detailed step-by-step instructions.
- Send a recurring contribution email (Refeer to parent PR https://github.com/newsrevenuehub/rev-engine/pull/835)

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
Yes

#### Have automated unit tests been added? If not, why?
In parent PR (https://github.com/newsrevenuehub/rev-engine/pull/835)

#### How should this change be communicated to end users?
New email will be sent out to users reminding them of a scheduled contribution

#### Are there any smells or added technical debt to note?
No

#### Has this been documented? If so, where?
No

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-2831
https://news-revenue-hub.atlassian.net/browse/DEV-708

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

[DEV-2919](https://news-revenue-hub.atlassian.net/browse/DEV-2919): After (unrelated) [DEV-2892](https://news-revenue-hub.atlassian.net/browse/DEV-2892) (aka #868) has been merged, and after (related) subtask ticket [DEV-2832](https://news-revenue-hub.atlassian.net/browse/DEV-2832) have both been merged, the magic link generation should be refactored to use the new static method `Contributor.create_magic_link` ([see here](https://github.com/newsrevenuehub/rev-engine/pull/868/files#diff-80bc4fbf647c521d99e0b1e9e38a568c928ed7477e600e7bd110a8e9bc870ae1R82)).

2022-11-29 19:42 UTC, benjaminEwhite requested changes
Left a few comments and questions.

One additional comment: after [DEV-2783](https://news-revenue-hub.atlassian.net/browse/DEV-2783) has been merged, this branch should make changes so that thank you emails also inherit from the base template you've created in this PR.

2022-11-29 19:42 UTC, benjaminEwhite commented on apps/emails/templates/recurring-contribution-email-reminder.html
> +{% endblock contribution_data_label %}
```suggestion
{% block contribution_date_label %}
Scheduled
{% endblock contribution_date_label %}
```

Right?

2022-11-29 19:42 UTC, benjaminEwhite commented on apps/emails/templates/recurring-contribution-email-reminder.txt
> +{{ rp_name }}
This should be parallel to what's happening with the HTML template. That is to say, I'd expect that we'd see a `apps/emails/templates/nrh-default-contribution-base-template.txt` file, and then `apps/emails/templates/recurring-contribution-email-reminder.txt` extending that base template.

2022-11-29 19:42 UTC, benjaminEwhite commented on apps/emails/templates/recurring-contribution-email-reminder.txt
> +Need to make changes to your contribution? {% autoescape off %}{{ magic_link }}{% endautoescape %}
FYI: Given the new approach taken for generating magic link in (unrelated) #868, and given that [DEV-2832](https://news-revenue-hub.atlassian.net/browse/DEV-2832) has already been reviewed and will soon be merged, I'm going to add a TODO to this PR description to update magic link generation to use new static method on Contributor that will be available after #868 is merged.

Also, I made a similar comment in PR for updated layout for thank you email, but do you know if we actually need the autoescape here?

2022-11-29 19:42 UTC, benjaminEwhite commented on apps/emails/templates/nrh-default-contribution-base-template.html
> +    }
This doesn't get used anywhere.  Not sure, but should this email always have a logo block?

2022-11-29 19:42 UTC, benjaminEwhite commented on apps/emails/templates/nrh-default-contribution-base-template.html
> +    }
This style is narrowly for thank you email, and is seemingly not used in recurring contribution reminders. If that is indeed the case, should remove from base template and have the inheriting template extend styles section, adding this (and any other styles that are specific only to thank you emails).

2022-11-29 19:42 UTC, benjaminEwhite commented on apps/emails/templates/nrh-default-contribution-base-template.html
> +    }
Also here -- these styles don't appear to be used in recurring email template, so shouldn't be in base template.

2022-11-29 19:42 UTC, benjaminEwhite commented on apps/emails/templates/nrh-default-contribution-base-template.html
> +<!DOCTYPE HTML
With this approach (using a base template), should also make changes so that the thank you email template inherits from this base template. That may need to happen after [DEV-2783](https://news-revenue-hub.atlassian.net/browse/DEV-2783) has been merged.

2022-11-30 18:55 UTC, GuiMend commented on apps/emails/templates/recurring-contribution-email-reminder.txt
> +Need to make changes to your contribution? {% autoescape off %}{{ magic_link }}{% endautoescape %}
I'll wait for both PRs to be merged before removing the `autoescape` for testing

2022-11-30 18:55 UTC, GuiMend commented on apps/emails/templates/nrh-default-contribution-base-template.html
> +    }
Removed it as it's related to the other email template

2022-11-30 18:58 UTC, GuiMend commented on apps/emails/templates/nrh-default-contribution-base-template.html
> +<!DOCTYPE HTML
Yes, I'll need to update one of the branches based on which PR is merged first. There isn't a correct merge order in this case

2022-11-30 20:56 UTC, benjaminEwhite commented on apps/emails/templates/nrh-default-contribution-base-template.html
> +                        </p>
Not a big deal, but the conditionality here could be limited to adding the `/{{contribution_interval_display_value}}`

2022-12-01 00:32 UTC, benjaminEwhite commented on apps/emails/templates/nrh-default-contribution-base-template.html
> +<!DOCTYPE HTML
Sounds good. Maybe make a TODO for this in JIRA and add to PR description? If you do that, go ahead and resolve this conversation.

2022-12-01 00:34 UTC, benjaminEwhite approved these changes
@GuiMend left a couple of small comments, but otherwise looking good. I'm going to go ahead and mark as "Approved" and leave you to deciding how to move forward with the comments.

2022-12-01 11:57 UTC, GuiMend commented on apps/emails/templates/nrh-default-contribution-base-template.html
> +<!DOCTYPE HTML
I've signaled the dependency in the PR https://github.com/newsrevenuehub/rev-engine/pull/851

2022-12-05 14:38 UTC, GuiMend commented on apps/emails/templates/nrh-default-contribution-base-template.html
> +                        </p>
Think we can leave it as is, I feel like they are equivalent approaches.

2022-12-15 18:36 UTC, x110dc approved these changes

2022-12-15 18:54 UTC, merged