DEV-2869 | Show alert when non-promise error when confirming Stripe payment
newsrevenuehub/rev-engine pull request #872
Opened 2022-11-29 22:56 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

- Catches non-promise errors (like the one that is captured in Sentry issue on the JIRA ticket for this PR) and displays an alert to user letting them know something has gone wrong.
- Adds tests for Stripe confirm payment errors
- Opportunistically removes unused, old Cypress commands

#### Why are we doing this? How does it help us?

Better UX in case of unexpected errors

#### How should this be manually tested? Please include detailed step-by-step instructions.

Not sure it can be. We've only seen one instance of the non-promise error that caused this, and not known how to reproduce.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No.

#### Have automated unit tests been added? If not, why?

Yes.

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

No.

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

- [DEV-2869](https://news-revenue-hub.atlassian.net/browse/DEV-2869)
- [DEV-2921](https://news-revenue-hub.atlassian.net/browse/DEV-2921)

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

[DEV-2921](https://news-revenue-hub.atlassian.net/browse/DEV-2921) -- there's a `console.error` call that should be updated after [DEV-2342](https://news-revenue-hub.atlassian.net/browse/DEV-2342) lands.

2022-11-30 14:54 UTC, nrh-cklimas requested changes

2022-11-30 14:54 UTC, nrh-cklimas commented on spa/cypress/e2e/01-donationPage.cy.js
> +    cy.intercept({ method: 'GET', url: 'https://www.google.com/recaptcha/*' }, { statusCode: 200 });
Does it make sense to do this globally? I see these requests pop up all the time in Cypress.

2022-11-30 14:54 UTC, nrh-cklimas commented on spa/cypress/e2e/01-donationPage.cy.js
> +  specify('when there is an unexpected but promise resolved error on Stripe payment element submission', () => {
```suggestion
  specify('displays an error when there is an unexpected error, but the Stripe payment element submission payment promise resolved', () => {
```

2022-11-30 14:54 UTC, nrh-cklimas commented on spa/cypress/e2e/01-donationPage.cy.js
> +  specify('There is an unexpected, non-promise error on Stripe payment element submission', () => {
```suggestion
  specify('displays an error when an unexpected, non-promise error on Stripe payment element submission occurs', () => {
```

2022-11-30 14:54 UTC, nrh-cklimas commented on spa/cypress/e2e/01-donationPage.cy.js
> +      .findByRole('button', { name: /Continue to Payment/ })
```suggestion
      .findByRole('button', { name: 'Continue to Payment' })
```

If we need a loose match on this, I'd vote for `exact: false` in the function call.

2022-11-30 14:54 UTC, nrh-cklimas commented on spa/cypress/support/commands.js
> -import { TOKEN } from 'ajax/endpoints';
:+1: for cleanup in this file

2022-11-30 14:54 UTC, nrh-cklimas commented on spa/src/components/paymentProviders/stripe/StripePaymentForm.js
> +      if (!['card_error', 'validation_error'].includes(error?.type)) {
Do these types of errors get handled elsewhere? I don't quite get this if statement.

2022-11-30 16:20 UTC, benjaminEwhite commented on spa/cypress/e2e/01-donationPage.cy.js
> +    cy.intercept({ method: 'GET', url: 'https://www.google.com/recaptcha/*' }, { statusCode: 200 });
It sounds like there's not any good options for global intercepts in Cypress, and if we end up with a test that is around recaptcha at some point, then we'd need to remember that recaptcha is being globally intercepted.

That said, it's mildly helpful to give this intercept a name, so I added a `cy.interceptGoogleRecaptcha` command, and replaced all of the recaptcha intercepts with this command.

4d032a2818e

2022-11-30 16:33 UTC, nrh-cklimas commented on spa/cypress/e2e/01-donationPage.cy.js
> +    cy.intercept({ method: 'GET', url: 'https://www.google.com/recaptcha/*' }, { statusCode: 200 });
Ah, right. I remember looking for this when I was trying to see if we could cause unintercepted requests to fail a test.

2022-11-30 16:34 UTC, nrh-cklimas approved these changes

2022-12-01 18:07 UTC, x110dc approved these changes

2022-12-01 18:13 UTC, merged