DEV-2761: Improve save/cancel buttons
newsrevenuehub/rev-engine pull request #875
Opened 2022-11-30 20:35 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

- Replaces the label-less save/cancel buttons in the page editor with new designs.
- Updates page editor tabs so that they stay on top of a panel when it scrolls. This looks weird locally because the Django code at the top of the page, but should look OK in a review app (and a real one).
- Adds a `className` prop to the base TabPanel component for styling purposes.

#### Why are we doing this? How does it help us?

Better UX.

#### How should this be manually tested? Please include detailed step-by-step instructions.

1. Edit a contribution page.
2. Confirm that the Update/Undo buttons on the Setup and Style tabs match the Figma comp.
3. Make a change on the Setup tab and hit Undo. Confirm that it reverts the change.
4. Make a change on the Setup tab and hit Update. Confirm that it updates the page preview.
5. Make a change on the Style tab and hit Undo. Confirm that it reverts the change.
6. Make a change on the Style tab and hit Update. Confirm that it updates the page preview.
7. Go to the Layout tab and scroll the tab content downward. Confirm the tabs at the top stay visible and are in the correct position (as opposed to scrolling with the rest of the tab content).
8. Edit an element on the Layout tab. Confirm the Update/Undo buttons match the Figma comp.
9. Make a change to an element on the Layout tab and hit Undo. Confirm that it reverts the change.
10. Make a change to an element on the Layout tab and hit Update. Confirm that it updates the page preview.
11. Edit an element on the Sidebar tab (you might have to add one). Confirm the Update/Undo buttons match the Figma comp.
12. Make a change to an element on the Sidebar tab and hit Undo. Confirm that it reverts the change.
13. Make a change to an element on the Sidebar tab and hit Update. Confirm that it updates the page preview.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

Yes. Screenshots will need to change of the edit interface.

#### Have automated unit tests been added? If not, why?

Yes.

#### How should this change be communicated to end users?

Updated documentation I think.

#### Are there any smells or added technical debt to note?

No.

#### Has this been documented? If so, where?

Not that I know of.

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-2761

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No.

2022-12-01 15:19 UTC, benjaminEwhite commented
Closing and reopening to attempt to trigger review app build on Heroku.

2022-12-07 01:49 UTC, GuiMend commented on spa/src/components/pageEditor/editInterface/EditInterface.js
> +              <S.TabPanel
Why go back to the `S.` style?

2022-12-07 01:49 UTC, GuiMend commented on spa/src/components/pageEditor/editInterface/EditInterfaceTabs.styled.ts
> +  z-index: 1;
Is `1` enough for this? Mui has some default values for zIndex, but I'm not sure if it has a tab value

2022-12-07 01:49 UTC, GuiMend commented on spa/src/components/pageEditor/editInterface/EditSaveControls.styles.ts
> +export const Root = styled('div')`
```suggestion
export const Root = styled.div`
```

2022-12-07 01:49 UTC, GuiMend commented on spa/src/components/pageEditor/editInterface/EditSaveControls.test.tsx
> +      tree({ variant: 'undo' });
Don't think the undo variant should be here

2022-12-07 01:49 UTC, GuiMend commented on spa/src/components/pageEditor/editInterface/EditSaveControls.tsx
> +      )}
I like using this pattern when we have a certainty that only these limited options will be available:
```
{
        {
          'foo': <Foo />,
          'bar': <Bar />
        }[param]
 }
```

```suggestion
      {{
         'cancel': (
         	<Button color="secondary" disabled={!!cancelDisabled} onClick={onCancel}>
             		Cancel
           	</Button>
           )
        'undo': (
        	<Button color="text" disabled={!!cancelDisabled} onClick={onCancel} startIcon={<Undo />}>
          		Undo
        	</Button>
      	)
      }[variant]}
```

2022-12-07 13:58 UTC, nrh-cklimas commented on spa/src/components/pageEditor/editInterface/EditInterface.js
> +              <S.TabPanel
Wasn't so much going back as it was not moving the file over to named export style (TabPanel became styled in this branch). I updated this and the rest of the imports in 58d97cd4796090554747bcb62e81dc23f9506589.

2022-12-07 13:59 UTC, nrh-cklimas commented on spa/src/components/pageEditor/editInterface/EditSaveControls.styles.ts
> +export const Root = styled('div')`
Fixed in 45528177b2144bc151dc851e5e986ab05c1d7beb

2022-12-07 13:59 UTC, nrh-cklimas commented on spa/src/components/pageEditor/editInterface/EditSaveControls.test.tsx
> +      tree({ variant: 'undo' });
Thanks for catching this, fixed in 56d2da6a7f47d4f16299b20b2e4a26eb9a7345d7

2022-12-07 14:01 UTC, nrh-cklimas commented on spa/src/components/pageEditor/editInterface/EditSaveControls.tsx
> +      )}
I like this suggestion--I rearranged it a little bit so that the lookup isn't in the render itself, let me know what you think: e7906a289fde922823035e9fde95c6fc88d2e08f

2022-12-12 19:22 UTC, GuiMend requested changes
When I edit something in the Setup or Style tab and click "undo", I go back to the "Layout" tab but the changed aren't undone

2022-12-12 19:22 UTC, GuiMend commented on spa/src/components/pageEditor/editInterface/EditSaveControls.tsx
> +      {secondaryButtons[variant]}
👍

2022-12-15 14:03 UTC, GuiMend approved these changes
👍

2022-12-16 18:15 UTC, x110dc approved these changes

2022-12-22 13:49 UTC, nrh-cklimas commented
I approved in Chromatic but the check is still showing as yellow.

2022-12-22 13:49 UTC, merged