DEV-2231: Add global context to storybook
newsrevenuehub/rev-engine pull request #879
Opened 2022-12-02 14:20 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
N/A

#### What's this PR do?
Adds notification manager and implements notification for Stripe connection and for Export button using this new method

#### Why are we doing this? How does it help us?
Showing the user system notifications makes their understanding of their actions in the app more visible and clear as to what happened

#### How should this be manually tested? Please include detailed step-by-step instructions.
- Connect to stripe and check that notification of stripe connection pops up and only vanishes when clicking the `close` button
- Click on Export button in Contributions screen and make sure it returns an error (backend api isn't yet working)

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
yes

#### Have automated unit tests been added? If not, why?
Yes

#### How should this change be communicated to end users?
System notification are now showing the user what the response to their action is in a clearer way

#### Are there any smells or added technical debt to note?
No

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-2836
Also relates to https://news-revenue-hub.atlassian.net/browse/DEV-2231 as it uses all the components created in that ticket

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2022-12-02 18:02 UTC, nrh-cklimas requested changes
Main thing here is to get the notistack version aligned with our MUI version, I think.

2022-12-02 18:02 UTC, nrh-cklimas commented on spa/src/components/dashboard/Dashboard.js
> +            <SystemNotification id={key} message={message} header="Stripe Successfully Connected!" type="success" />
I think it'd be better to connect the `SystemNotification` component to the `SnackbarProvider` as described in the Custom Component section of https://notistack.com/features/customization, so that consumers don't have to do this by hand.

2022-12-05 14:24 UTC, GuiMend commented on spa/package.json
> +    "notistack": "^2.0.8",
Not sure it's necessary @nrh-cklimas, the dependencies for notistack don't include mui v5. This package has only 2 dependencies that are: [clsx](https://www.npmjs.com/package/clsx) & [hoist-non-react-statics](https://www.npmjs.com/package/hoist-non-react-statics) (which I checked the dependency tree and they also don't have any dependencies themselves to a conflicting package version we use.
It does have mui v5 in dev-dependencies, but that shouldn't matter as builds ignore these dependencies.
![image](https://user-images.githubusercontent.com/9381325/205659720-d39ae794-ff1d-47be-b553-be0d7b5f6084.png)

Also, notistack's official documentation only goes back to v2.x, so that would make things harder to know how to implement/debug. 

What do you think?

2022-12-05 15:34 UTC, GuiMend commented on spa/src/components/common/Button/ExportButton/ExportButton.test.tsx
> +    axiosMock.onPatch(`mock-url`).reply(200);
I tried doing this, but then the `networkError` didn't work anymore. Axios would mock `200` even in the test that I added the  `axiosMock.onPatch().networkError();`

2022-12-05 16:33 UTC, nrh-cklimas commented on spa/package.json
> +    "notistack": "^2.0.8",
I think perhaps npmjs.com doesn't show peer deps? [Here's where I see the peer dep on MUI v5](https://github.com/iamhosseindhv/notistack/blob/master/package.json#L29).

2022-12-05 16:37 UTC, nrh-cklimas commented on spa/src/components/common/Button/ExportButton/ExportButton.test.tsx
> +    axiosMock.onPatch(`mock-url`).reply(200);
Ah, I had it wrong. You do need to reset the mock to override previously-set behavior. Up to you if you want to do that or use beforeEach--it doesn't feel like that big of a difference either way with the reset in place.

2022-12-06 13:56 UTC, nrh-cklimas approved these changes

2022-12-16 18:08 UTC, x110dc approved these changes

2022-12-16 18:34 UTC, merged