DEV-767: Update magic link email
newsrevenuehub/rev-engine pull request #881
Opened 2022-12-05 15:03 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
Updates the layout for magic link email

#### Why are we doing this? How does it help us?
We are updating all email layout/designs to match figma and be more consistent throughout the app and emails

#### How should this be manually tested? Please include detailed step-by-step instructions.
- Request a magic link email and make sure email matches figma
![image](https://user-images.githubusercontent.com/9381325/205669406-e0043d98-cf9a-4a1c-954c-179e413fe447.png)

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
Yes, email interface

#### Have automated unit tests been added? If not, why?
n/a

#### How should this change be communicated to end users?
n/a

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-767

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2022-12-05 18:40 UTC, benjaminEwhite approved these changes
Looks good to me. Left a question around CSP.

2022-12-05 18:40 UTC, benjaminEwhite commented on apps/emails/templates/nrh-manage-contributions-magic-link.html
> +    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,600,700&display=swap" rel="stylesheet" type="text/css">
Can you confirm that this doesn't produce any new CSP violations?

2022-12-06 13:41 UTC, GuiMend commented on apps/emails/templates/nrh-manage-contributions-magic-link.html
> +    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,600,700&display=swap" rel="stylesheet" type="text/css">
I believe it's OK. I've ran a CSP evaluator and nothing popped up. Also, this line isn't introducing anything new, it's still using google fonts api.

![image](https://user-images.githubusercontent.com/9381325/205927082-dafa04aa-cf68-47bb-a773-437e1eac71e4.png)

2022-12-06 14:08 UTC, benjaminEwhite approved these changes

2022-12-20 19:36 UTC, nrh-cklimas requested changes

2022-12-20 19:36 UTC, nrh-cklimas commented on apps/emails/templates/nrh-manage-contributions-magic-link.html
> +                    © News Revenue Hub 2022
Could we dynamically insert the year? Not sure what's possible with the template but this will soon be out-of-date :)

2022-12-20 19:36 UTC, nrh-cklimas commented on apps/emails/templates/nrh-manage-contributions-magic-link.html
> +        font-family: 'Roboto';
Maybe `'Roboto', sans-serif;` as a fallback?

2022-12-20 19:46 UTC, GuiMend commented on apps/emails/templates/nrh-manage-contributions-magic-link.html
> +                    © News Revenue Hub 2022
Will ask @benjaminEwhite to review the implementation, but I think it's done 👍

2022-12-20 19:51 UTC, nrh-cklimas commented on apps/emails/templates/nrh-manage-contributions-magic-link.html
> +                    © News Revenue Hub 2022
Cool. If we can't do it dynamically, I guess we should make a followup story to update it in January.

2022-12-20 19:51 UTC, nrh-cklimas approved these changes

2022-12-20 21:15 UTC, benjaminEwhite commented on apps/emails/templates/nrh-manage-contributions-magic-link.html
> +                    © News Revenue Hub 2022
Not the worst idea to make this dynamic. I'm open minded about if it comes ahead of deploy or as follow up.

@GuiMend leave that decision to you, keeping in mind there's additional overhead to creating a sep ticket. 

Solution looks like it would be to use [{% now "Y" %}](https://docs.djangoproject.com/en/dev/ref/templates/builtins/#now) in the templates.

2022-12-23 03:35 UTC, x110dc approved these changes

2022-12-28 00:23 UTC, merged