DEV-1758: Include timezone in receipt emails
newsrevenuehub/rev-engine pull request #884
Opened 2022-12-06 21:50 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
This is the **third** of **3** planned stacked PRs to deliver the ticket [DEV-2783](https://news-revenue-hub.atlassian.net/browse/DEV-2783)

1. (https://github.com/newsrevenuehub/rev-engine/pull/851) (corresponding to [DEV-2783 | Update layout in receipt emails (add required tax information, contributor portal link, and refer to RP in copyright)](https://news-revenue-hub.atlassian.net/browse/DEV-2783) 
2. (https://github.com/newsrevenuehub/rev-engine/pull/868) (corresponding to [DEV-2892 | provide requested data for receipt emails](https://news-revenue-hub.atlassian.net/browse/DEV-2892))  
3. (https://github.com/newsrevenuehub/rev-engine/pull/884) (corresponding to [DEV-1758](https://news-revenue-hub.atlassian.net/browse/DEV-1758) Improvement: Include time zone in receipt emails - **THE CURRENT PR**

#### What's this PR do?
Adds a helper function to convert datetimes without timezone or UTC timezones into a specific timezone. Our usecase in this PR is to convert UTC to EST to show in the contribution receipt email.

#### Why are we doing this? How does it help us?
The timestamp with timezone is important in the receipt email because clients can use that receipt for tax purposes. The exact time of the receipt needs to be returned to the user.

#### How should this be manually tested? Please include detailed step-by-step instructions.
- Create a contribution and make sure the receipt received contains the date + time + timezone information and that it is the correct values.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
Date + time + timezone instead of only date in receipt email

#### Have automated unit tests been added? If not, why?
Yes

#### How should this change be communicated to end users?
n/a

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
This PR corresponds to this ticket: https://news-revenue-hub.atlassian.net/browse/DEV-1758

But it is built upon:
https://news-revenue-hub.atlassian.net/browse/DEV-2783
https://news-revenue-hub.atlassian.net/browse/DEV-2892

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2022-12-07 14:18 UTC, benjaminEwhite requested changes

2022-12-07 14:18 UTC, benjaminEwhite commented on apps/emails/helpers.py
> +        # TODO: update function to get client's timezone
Can we remove this TODO? Or else create a JIRA ticket and link to that here?

2022-12-08 17:08 UTC, GuiMend commented on apps/emails/tests/test_helpers.py
> +        utc = test_date.replace(tzinfo=pytz.UTC)
I've updated the test so that this conversion makes sense

2022-12-09 17:41 UTC, benjaminEwhite commented on apps/emails/tests/test_helpers.py
> +class HelperTests(SimpleTestCase):
Also, when you move to pytest style, could consider compressing these into a single "test_convert_to_timezone" with `pytest.parametrize` for the paramaters that are varying. Think that would actually make test surface clearer than distinct test methods.

2022-12-12 20:14 UTC, GuiMend commented on apps/emails/tests/test_helpers.py
> +class HelperTests(SimpleTestCase):
@benjaminEwhite , how can I run the only the tests that I created to see if it's working as expected?
I tried running the same cmd that I used for testing it before I made these latest suggestions and it didn't work anymore.
```
python manage.py test --pattern="test_helpers.py"
```

Before it was showing:
```
Ran 4 tests in 0.000s

OK
```

But after this last change it's returning:
```
Ran 0 tests in 0.000s

OK
```

2022-12-13 16:29 UTC, benjaminEwhite commented on apps/emails/tests/test_helpers.py
> +def test__convert_to_timezone_formatted(timezone, fmt, isUTC, expect):
This is minor, but can we get rid of `__` in favor of `_`. We're using `_` consistently elsewhere I believe, and would like to keep consistent.

Also, should use snake_case for var names.

```suggestion
def test_convert_to_timezone_formatted(timezone, fmt, is_UTC, expect):
```

2022-12-13 16:30 UTC, benjaminEwhite commented on apps/emails/tests/test_helpers.py
> +    if isUTC:
```suggestion
    if is_UTC:
```

2022-12-13 16:30 UTC, benjaminEwhite commented on apps/emails/tests/test_helpers.py
> +    assert test_date.strftime("%m-%d-%y %H:%M %Z") == "12-06-22 00:00" + " UTC" if isUTC else " "
```suggestion
    assert test_date.strftime("%m-%d-%y %H:%M %Z") == "12-06-22 00:00" + " UTC" if is_UTC else " "
```

2022-12-14 20:38 UTC, x110dc approved these changes

2022-12-14 20:54 UTC, merged