Dev 2962 improve undo in editor
newsrevenuehub/rev-engine pull request #887
Opened 2022-12-09 19:19 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

- Improves the Undo functionality on the Setup and Style tabs so that it resets the fields on the respective tabs to match the original data, and no longer changes tab.
- Adds an ImageUpload base component. We have an existing one, ImageWithPreview, but it's not a controlled component so it's not possible to reset the field value. I created ImageUpload to handle this. We need to keep ImageWithPreview around for a little longer as it is also used by the Image block, and I wanted to limit PR scope.

#### Why are we doing this? How does it help us?

Better UX in the page editor, better functionality in our component library.

#### How should this be manually tested? Please include detailed step-by-step instructions.

Testing disabled state of Undo button:
1. Edit a page.
2. Confirm the Undo button is disabled in both Setup and Styles tab.

Testing Setup tab:
1. Edit a page and choose the Setup tab.
2. Change all of the fields in this tab.
3. Click the Undo button in the tab.
4. Confirm that all changes you made have been reversed to the original state of the page in the tab fields as well as the page preview.
5. Make an unrelated edit to the page and save it. Confirm that none of the changes you made in step 2 were saved.

Testing Styles tab:
1. Edit a page and choose the Style tab. 
2. Choose a different page style.
3. Click the Undo button in the tab.
4. Confirm that the style change you made has been reversed to the original state in the dropdown menu and on the page preview.
6. Make an unrelated edit to the page and save it. Confirm that the page style was not changed when you saved.
 
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

Yes, the Undo button is now disabled when the user hasn't made any relevant changes.

#### Have automated unit tests been added? If not, why?

Yes.

#### How should this change be communicated to end users?

See documentation answer above.

#### Are there any smells or added technical debt to note?

No.

#### Has this been documented? If so, where?

No.

#### What are the relevant tickets? Add a link to any relevant ones.

- https://news-revenue-hub.atlassian.net/browse/DEV-2761 (parent)
- https://news-revenue-hub.atlassian.net/browse/DEV-2962

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No.

2022-12-09 19:20 UTC, nrh-cklimas commented on spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.js
> -  const verifyUnpublish = (cb) => {
This code isn't related to the PR but I noticed it as I was working on it. Discussed on Slack--it sounds like to me that it would be a good idea to remove so it doesn't cause confusion when we implement unpublishing elsewhere.

2022-12-12 19:38 UTC, GuiMend requested changes
Undo style ✔️ 

When I undo the setings tab the page blink ❌. 
Probably the undo is causing a re-render somewhere. Could we prevent that?

2022-12-12 19:49 UTC, GuiMend commented on spa/src/components/base/ImageUpload/ImageUpload.styled.ts
> +  font-size: 16px;
Can we use the size from our theme file?

2022-12-12 19:49 UTC, GuiMend commented on spa/src/components/base/ImageUpload/ImageUpload.tsx
> +      onChange();
Do nothing instead of triggering onChange?

2022-12-12 19:49 UTC, GuiMend commented on spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.js
> +            type="ext"
```suggestion
            type="text"
```

2022-12-12 19:49 UTC, GuiMend commented on spa/src/components/pageEditor/editInterface/pageStyles/StylesChooser.js
> +  // from treating the select as an uncontrolled component.
Maybe add this comment right above the line with the change?
` selectedItem={selected === null ? '' : selected}`

2022-12-12 22:20 UTC, nrh-cklimas commented on spa/src/components/base/ImageUpload/ImageUpload.styled.ts
> +  font-size: 16px;
👍 Updated in a5e65a26f1919202c7851c111921128412aa583a

2022-12-12 22:20 UTC, nrh-cklimas commented on spa/src/components/base/ImageUpload/ImageUpload.tsx
> +      onChange();
Done in 7262b8f027530edc22a20904ad5fa043a140222a

2022-12-12 22:21 UTC, nrh-cklimas commented on spa/src/components/pageEditor/editInterface/pageSetup/PageSetup.js
> +            type="ext"
3281b46528bd4a05b7b7cb2e48ec5aacb16c1ee6

2022-12-12 22:21 UTC, nrh-cklimas commented on spa/src/components/pageEditor/editInterface/pageStyles/StylesChooser.js
> +  // from treating the select as an uncontrolled component.
da705fadef4a03f2d486c50cb780069d8b747e87

2022-12-13 13:54 UTC, nrh-cklimas commented
Addressed the blink when undoing or saving with 72dd433f9aea8d4cf74ee09f611e52b5dd356be5--eventually, I think we would want to use react-query to solve this problem though.

2022-12-13 23:00 UTC, GuiMend approved these changes
Small comment

2022-12-14 14:49 UTC, nrh-cklimas commented on spa/src/components/pageEditor/PageEditor.js
> +            console.log(data);
Fixed in f29574edee43f176574bb74d8452702a78244b76

2022-12-14 15:15 UTC, nrh-cklimas commented
Merging this for QA over in DEV-2761

2022-12-14 15:15 UTC, merged