[WIP] DEV-2477 | Hookdeck integration for Stripe Webhooks
newsrevenuehub/rev-engine pull request #890
Opened 2022-12-12 20:13 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-01-25 19:07 UTC, njharman requested changes
See in line comments

The QA instructions proly make more sense to someone who knows what hookdeck is and what the management commands should do.  It's not bad. It maybe better with more "checklist" of things to check for.

2023-01-25 19:07 UTC, njharman commented on apps/common/hookdeck.py
> +        logger.info("No connections found for ticket with prefix %s", ticket_prefix)
_if not conns_ (and _if not dests_ below) not covered.

2023-01-30 17:21 UTC, benjaminEwhite commented
> See in line comments
> 
> The QA instructions proly make more sense to someone who knows what hookdeck is and what the management commands should do. It's not bad. It maybe better with more "checklist" of things to check for.

Updated the instructions to be more checklisty and comprehensive.

2023-01-30 17:29 UTC, benjaminEwhite commented on apps/common/hookdeck.py
> +    if (resp_data := response.json())["archived_at"] is not None and auto_unarchive:
46c6c0a566

2023-01-30 17:30 UTC, benjaminEwhite commented on apps/common/hookdeck.py
> +    if (resp_data := response.json())["archived_at"] is not None and auto_unarchive:
46c6c0a566

2023-01-30 17:30 UTC, benjaminEwhite commented on apps/common/hookdeck.py
> +        logger.exception("Something unexpected happened: %s", response.content)
ecea203

2023-01-30 17:55 UTC, benjaminEwhite commented on apps/common/hookdeck.py
> +        params=dict(params),
7b0d69704b2

2023-01-30 18:01 UTC, benjaminEwhite commented on apps/common/hookdeck.py
> +    archived: bool = True,
e1c0583de

2023-01-30 18:24 UTC, benjaminEwhite commented on apps/common/hookdeck.py
> +        logger.info("No connections found for ticket with prefix %s", ticket_prefix)
3988e3

2023-01-30 18:24 UTC, benjaminEwhite commented on apps/common/hookdeck.py
> +        logger.info("No connections found for ticket with prefix %s", ticket_prefix)
3988e32e1

2023-01-30 18:25 UTC, benjaminEwhite commented on apps/common/hookdeck.py
> +        logger.exception("Something unexpected happened")
This was handled in a commit (whose hash I'm too lazy to track down).

2023-01-30 18:59 UTC, njharman approved these changes

2023-02-01 00:03 UTC, x110dc requested changes
The testing worked for me. Looks good! I just have a couple of small suggestions and questions.

2023-02-01 00:03 UTC, x110dc commented on pyproject.toml
> +pytest-cases = "^3.6.13"
And it should be unpinned.

2023-02-01 14:22 UTC, benjaminEwhite commented on pyproject.toml
> +pytest-cases = "^3.6.13"
56fed0f2

2023-02-01 14:30 UTC, benjaminEwhite commented on apps/contributions/management/commands/create_stripe_webhooks.py
> +            kwargs["enabled_events"] = ["*"]
Good question. Not sure now why I thought that was a good idea, especially since settings can be changed to achieve same end.

Removed in e81e6f21f3d

2023-02-01 23:19 UTC, x110dc approved these changes

2023-02-02 14:32 UTC, merged