Dev 949 remove slack app
newsrevenuehub/rev-engine pull request #897
Opened 2022-12-14 06:15 UTC by leo-dcfa

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

*Important* - do not merge before (https://github.com/newsrevenuehub/rev-engine/pull/896) - the current branch was branched off the previous PR branch; once previous PR is merged, please update the branch and the only change should only be removing files and uninstalling the app. 

#### What's this PR do?

- Uninstall Slack app
- Remove Slack app

#### Why are we doing this? How does it help us?

We are now using Switchboard API To manage Slack notifications

#### How should this be manually tested? Please include detailed step-by-step instructions.

N/A - this PR only removes files and uninstalls app that is no longer active; previous PR has testing instructions

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

N/A

#### Have automated unit tests been added? If not, why?

N/A

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

N/A

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-949]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

N/A

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

N/A

[DEV-949]: https://news-revenue-hub.atlassian.net/browse/DEV-949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-12-16 15:20 UTC, benjaminEwhite approved these changes
Code changes seem fine.

2022-12-20 03:32 UTC, x110dc approved these changes

2022-12-20 03:39 UTC, x110dc requested changes
Don't we need a migration to remove the tables from the db?

2022-12-20 03:39 UTC, x110dc commented on apps/slack/migrations/0001_initial.py
> -
Do we need a new migration to remove these tables?

2022-12-20 20:19 UTC, closed without merging