DEV-2791: Show user email & id in sentry
newsrevenuehub/rev-engine pull request #900
Opened 2022-12-14 15:35 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
Adds user email and id to sentry so that errors are identifiable with the user that got the error.

#### Why are we doing this? How does it help us?
This will be possibly be useful for a few different scenarios: 
- if we have an identifier for a contributor in Sentry we can use that to look in the logs/Stripe/Salesforce to get more detail about what happened
- if we have an ID of a Org Admin we can contact them about the issue to get more detail or assist them

With user id/email we can identify the above information.

#### How should this be manually tested? Please include detailed step-by-step instructions.
- Log into review app and try to break the app so that a sentry error is shown with the user's email/id

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
no

#### Have automated unit tests been added? If not, why?
n/a

#### How should this change be communicated to end users?
n/a

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-2791

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2022-12-14 18:47 UTC, nrh-cklimas commented on spa/src/hooks/useUser.ts
> +      Sentry.setUser({ email: data.email, id: data.id });
Do we want to record the IP address too? https://docs.sentry.io/platforms/javascript/enriching-events/identify-user/#ip_address I know it's not in AC but it seems like we may as well while we are here.

2022-12-14 21:12 UTC, GuiMend commented on spa/src/hooks/useUser.ts
> +      Sentry.setUser({ email: data.email, id: data.id });
Hey @nrh-cklimas , if you check sentry right now, it already captures the user's IP.

2022-12-14 21:20 UTC, nrh-cklimas requested changes

2022-12-14 21:20 UTC, nrh-cklimas commented on spa/src/hooks/useUser.ts
> +      Sentry.setUser({ email: data.email, id: data.id });
I was looking at this:

> If the field is omitted, the default value is null. However, due to backwards compatibility concerns, certain platforms (in particular JavaScript) have a different default value for "{{auto}}". SDKs and other clients should not rely on this behavior and should set IP addresses or "{{auto}}" explicitly.

It's hard for me to fully understand what they mean by this, but it sounds like we shouldn't depend on them recording IP addresses by default?

2022-12-14 21:21 UTC, nrh-cklimas approved these changes

2022-12-15 15:12 UTC, GuiMend commented on spa/src/hooks/useUser.ts
> +      Sentry.setUser({ email: data.email, id: data.id });
Adding ip address:
```suggestion
      Sentry.setUser({ email: data.email, id: data.id, ip_address: "{{auto}}" });
```

2022-12-28 00:49 UTC, x110dc approved these changes

2022-12-28 00:50 UTC, merged