DEV-2836: Notification manager
newsrevenuehub/rev-engine pull request #901
Opened 2022-12-15 20:43 UTC by GuiMend

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a
#### What's this PR do?
Shows Export button in Contributions dashboard even if there aren't any transactions yet

#### Why are we doing this? How does it help us?
Consistently show the user the Export Button so that they are aware of the functionality

#### How should this be manually tested? Please include detailed step-by-step instructions.
Login with a user with 0 contributions (if you don't have any accounts, you can create a new one)

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
No, just leaves it on screen in a scenario.

#### Have automated unit tests been added? If not, why?
Yes

#### How should this change be communicated to end users?
N/A

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-2974

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2022-12-16 13:48 UTC, nrh-cklimas requested changes

2022-12-16 13:48 UTC, nrh-cklimas commented on spa/src/components/common/Hero/Hero.test.tsx
>    it('should be accessible', async () => {
We should have a test for when the export button is not displayed, too.

2022-12-16 14:35 UTC, nrh-cklimas commented on spa/src/components/common/Hero/Hero.test.tsx
>    it('should be accessible', async () => {
How about also...

```ts
it("doesn't render the export button if no email has been set", () => {
    const { container } = tree({ exportData: {} });

    expect(screen.queryByRole('button', { name: 'mock-export-button' })).not.toBeInTheDocument();
});
```

2022-12-16 17:01 UTC, GuiMend commented on spa/src/components/common/Hero/Hero.test.tsx
>    it('should be accessible', async () => {
That shouldn't happen as I modified the proptypes of exportData so that `email` is required.
The options are null, undefined or at least { email: '' }

2022-12-16 17:05 UTC, nrh-cklimas commented on spa/src/components/common/Hero/Hero.test.tsx
>    it('should be accessible', async () => {
Ah, my mistake. I think either mark exportData as `isRequired` in prop types or go with this test:
```tsx
  it("shouldn't render export if exportData is not defined", () => {
    tree({ exportData: undefined });
    expect(screen.queryByRole('button', { name: 'mock-export-button' })).not.toBeInTheDocument();
  });
```

2022-12-19 13:55 UTC, nrh-cklimas approved these changes

2022-12-20 20:52 UTC, x110dc approved these changes

2022-12-20 21:19 UTC, merged