DEV-3010 | Contributions are not appearing in contributions tab after being accepted in test
newsrevenuehub/rev-engine pull request #910
Opened 2022-12-20 21:08 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-01-11 16:16 UTC, njharman requested changes
Clarifying questions and possibly one small issue.

2023-01-11 16:16 UTC, njharman commented on apps/contributions/payment_managers.py
> +                # we rely on Stripe webhook for payment_intent.canceled that updates status on contribution
Good to add comment why there's no contribution.save() here.  Does this mean payment_intent.canceled results in Contribution.cancel() being called?

[huh, my muscle memory does two els. "While both canceled and cancelled are acceptable for the past tense of cancel, the version with one L is more common in American English, while the version with two L's is more common in British English."

2023-01-11 16:16 UTC, njharman commented on apps/contributions/webhooks.py
> +        contribution.save(update_fields=["status", "payment_provider_data", "modified"])
Do the self.contribution.save() calls in ./payment_managers.py require similar update_fields? [Sorry don't understand flow enough to answer myself]

2023-01-11 16:16 UTC, njharman commented on apps/contributions/webhooks.py
> +        contribution.save(update_fields=["status", "last_payment_date", "payment_provider_data", "modified"])
provider_payment_id and others set above, but not updated? If unneeded, then delete above. If side effects, bleck and deserves comment.

2023-01-11 16:16 UTC, njharman commented on apps/contributions/tests/test_webhooks.py
> +        # the next two assertions are to ensure we're only allowing webhook to update a subset of fields
+1

2023-01-11 18:17 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        elif self.status == ContributionStatus.FLAGGED and self.provider_payment_method_id:
This is defensive coding, in light of what I learned about lifecycle of contributions. While it shouldn't normally happen, there's a logical possibility whereby a contribution could have a flagged status but not have a `provider_payment_method_id`. If we don't have `provider_payment_method_id`, there's no action to take. But if it is there, we tell Stripe to detach the payment method from the customer, which guarantees that it cannot be used  for future charges for that customer. You're right that this is a "forget about it method" in that we just tell Stripe to update its data model, but there's no downstream action for us.

`provider_payment_method_id` only will be present if one of the following events has completed and been processed on our end via webhooks: 

- `payment_intent.succeeded` (happens in normal checkout flow for one-time and recurring)
- `customer_subscription.updated` (happens in normal checkout flow for recurring contributions and in other cases, and sets pm id subject to certain conditions)
-  `payment_method.attached"` (happens in checkout flow involving a recurring contribution, whether flagged or accepted -- crucially, this is the way a flagged-then-accepted contribution can have everything work out how we need it to in our domain model and in Stripe's )

2023-01-11 18:57 UTC, benjaminEwhite commented on apps/contributions/webhooks.py
> +        contribution.save(update_fields=["status", "payment_provider_data", "modified"])
Good question. I don't think those need to be updated. There are two methods in that file that call `save`

- `complete_recurring_payment`
- `complete_one_time_payment`

These only get called when a flagged contribution is accepted via the Django admin or when the`auto_accept_flagged_contributions` task runs. Neither of those things will happen right around the time all of Stripe's webhooks fire having to with checkout flow.

2023-01-11 19:01 UTC, benjaminEwhite commented on apps/contributions/webhooks.py
> +        contribution.save(update_fields=["status", "last_payment_date", "payment_provider_data", "modified"])
Missed those, and added to update_fields (+ updating tests) in this commit: 1d69d4d28

2023-01-11 20:07 UTC, njharman commented on apps/contributions/payment_managers.py
> +                # we rely on Stripe webhook for payment_intent.canceled that updates status on contribution
I guess I should have been more clear, I didn't see where / how payment_intent.canceled updates status

2023-01-12 23:53 UTC, x110dc approved these changes

2023-01-17 14:36 UTC, merged