DEV-2720: Lay out Settings > Integrations Page
newsrevenuehub/rev-engine pull request #917
Opened 2022-12-27 19:29 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
Creates all base & common components necessary for Settings > Integration page + also creates the Integration Page and wires it up.

#### Why are we doing this? How does it help us?
Presents the user with a screen where they can see all possible integrations and how to implement them. Also shows status of connected integrations.

#### How should this be manually tested? Please include detailed step-by-step instructions.
- Log into a user with and without Stripe integration connected
- Navigate to the page `/settings/integrations`
- Check that design matches comp
- Check that Stripe integration status matches the actual user's status (connected/not connected)

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
Yes

#### Have automated unit tests been added? If not, why?
Yes

#### How should this change be communicated to end users?
Integrations screen now available.

#### Are there any smells or added technical debt to note?
No

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-2720

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2023-01-10 15:15 UTC, nrh-cklimas requested changes

2023-01-10 15:15 UTC, nrh-cklimas commented on spa/src/components/settings/Integration/Integration.styled.ts
> +  }
```suggestion
  display: grid;
  gap: 40px;
  grid-template-columns: repeat(auto-fit, 314px);
```

This way you don't have to target a testid.

2023-01-10 15:15 UTC, nrh-cklimas commented on spa/src/components/base/Switch/Switch.tsx
> +      background: #ffffff;
```suggestion
      background: ${(props) => props.theme.colors.white};
```

2023-01-12 15:13 UTC, GuiMend commented on spa/src/components/common/IntegrationCard/IntegrationCard.tsx
> +  onChange?: () => void;
Not really, it's input is a function that doesn't need any args.

2023-01-12 15:15 UTC, GuiMend commented on spa/src/components/common/IntegrationCard/IntegrationCard.tsx
> +        <p>{isActive! ? 'Connected' : card.toggleLabel || 'Not Connected'}</p>
In this case where `card.toggleLabel` is a string, I prefer to leave it as `||` because it will go to the default even if `card.toggleLabel = ''`. `??` only works if `card.toggleLabel` is undefined or null

2023-01-12 15:15 UTC, GuiMend commented on spa/src/components/common/IntegrationCard/IntegrationCard.tsx
> +              {isActive ? card.toggleConnectedTooltipMessage || card.toggleTooltipMessage : card.toggleTooltipMessage}
Same here

2023-01-12 15:16 UTC, GuiMend commented on spa/src/components/dashboard/sidebar/DashboardSidebarFooter.js
> +      rel="noopener noreferrer"
Got it 👍

2023-01-12 20:10 UTC, GuiMend commented on spa/src/components/base/Switch/Switch.tsx
> +export const StyledSwitch = styled(MuiSwitch)<SwitchProps>`
@nrh-cklimas, we already have the default focused state:
![image](https://user-images.githubusercontent.com/9381325/212170544-da999f53-2c6a-4050-939f-afa7e2ffe88e.png)

2023-01-12 20:20 UTC, GuiMend commented on spa/src/components/settings/Integration/Integration.tsx
> +const Integration = () => {
Wouldn't this be best done if we needed to reutilize the integration cards elsewhere? From what I know it's only used in this screen

2023-01-12 20:58 UTC, nrh-cklimas commented on spa/src/components/common/IntegrationCard/IntegrationCard.tsx
> +  onChange?: () => void;
I was looking at the definition in Switch.tsx--the base MUI component sends the change event so this type definition means that if a consumer did want to work with that event, TypeScript would flag it. I think another approach to it is to do:

```tsx
import { SwitchProps } from 'base/components';

...

onChange?: SwitchProps['onChange'];
```

2023-01-12 20:59 UTC, nrh-cklimas commented on spa/src/components/common/IntegrationCard/IntegrationCard.tsx
> +        <p>{isActive! ? 'Connected' : card.toggleLabel || 'Not Connected'}</p>
I'm not sure, what circumstances would you see where an empty string would be used?

2023-01-12 21:00 UTC, nrh-cklimas commented on spa/src/components/dashboard/sidebar/DashboardSidebarFooter.js
> +      rel="noopener noreferrer"
Same thing on the FAQ link below it too, I think.

2023-01-12 21:05 UTC, nrh-cklimas commented on spa/src/components/settings/Integration/Integration.tsx
> +const Integration = () => {
I'll leave this one up to you. But I think keeping components as self-contained as possible is a good thing.

2023-01-13 13:07 UTC, GuiMend commented on spa/src/components/common/IntegrationCard/IntegrationCard.tsx
> +        <p>{isActive! ? 'Connected' : card.toggleLabel || 'Not Connected'}</p>
It should never be `''`, but if it were to happen it would render the correct label. I can change it to your suggestion, I don't have a strong feeling about it either way

2023-01-13 14:48 UTC, GuiMend commented on spa/src/components/settings/Integration/Integration.tsx
> +const Integration = () => {
Done

2023-01-13 14:49 UTC, GuiMend commented on spa/src/components/base/Switch/Switch.tsx
> +export const StyledSwitch = styled(MuiSwitch)<SwitchProps>`
I spent a bit of time looking for this and didn't manage to find a solution yet. Do you have a suggestion? Or maybe we could create a ticket and leave it in the backlog to search further?

2023-01-13 15:13 UTC, nrh-cklimas commented on spa/src/components/common/IntegrationCard/IntegrationCard.tsx
> +        <p>{isActive! ? 'Connected' : card.toggleLabel || 'Not Connected'}</p>
Neither do I, really... I think either we make it explicit that the label gets overridden if it's an empty string in a comment, or we trust consumers to do the right thing.

2023-01-13 15:21 UTC, nrh-cklimas commented on spa/src/components/settings/Integration/Integration.tsx
> +const Integration = () => {
Small thing: several of the cards show errors in Storybook because they are making react-query calls. What I did in the DEV-2765 branch was to update .storybook/preview.js to have this...

```tsx
const queryClient = new QueryClient();

// The two MuiThemeProviders here are to force JSS scoping, e.g. so that MUI
// uses classes like MuiButton-5 instead of MuiButton. This helps us catch
// styling mistakes in Storybook as opposed to the app.

const providerFn = ({ children }) => (
  <QueryClientProvider client={queryClient}>
    <ThemeProvider theme={revEngineTheme}>
      <MuiThemeProvider theme={muiThemeOverrides}>
        <MuiThemeProvider>
          <AlertProvider template={Alert} {...alertOptions}>
            <SnackbarProvider anchorOrigin={{ horizontal: 'right', vertical: 'bottom' }}>
              <AdminGlobalStyles />
              <GlobalContext.Provider value={{ getReauth: () => {} }}>{children}</GlobalContext.Provider>
            </SnackbarProvider>
          </AlertProvider>
        </MuiThemeProvider>
      </MuiThemeProvider>
    </ThemeProvider>
  </QueryClientProvider>
);
```

2023-01-13 15:56 UTC, nrh-cklimas commented on spa/src/components/base/Switch/Switch.tsx
> +export const StyledSwitch = styled(MuiSwitch)<SwitchProps>`
Here's what I found--the issue seems related to the ripple itself, which by default picks up the background color of the track... I think. I think our issue is that the track color is light enough that the ripple becomes transparent, or nearly so. It's hard to debug because MUI hides the ripple when the control loses focus--I was able to set a DOM breakpoint in Chrome to try to inspect it, but still had a lot of trouble.

Anyway, the below seems to allow control over the ripple color when keyboard focus happens.

In the component itself:

```tsx
return (
    <StyledSwitch
      {...props}
      classes={{
        root: 'NreSwitchRoot',
        thumb: 'NreThumb',
        track: 'NreTrack',
        checked: 'NreChecked',
        ...props.classes
      }}
      TouchRippleProps={{
        classes: { child: 'NreTouchRippleChild' }
      }}
    />
  );
```

And then in styles:

```tsx
export const StyledSwitch = styled(MuiSwitch)<SwitchProps>`
  && {
    /* usual stuff */

    .NreTouchRippleChild {
      background: ${(props) => props.theme.colors.muiGrey[100]};
    }
  }
`;
```

2023-01-13 16:56 UTC, GuiMend commented on spa/src/components/common/IntegrationCard/IntegrationCard.tsx
> +        <p>{isActive! ? 'Connected' : card.toggleLabel || 'Not Connected'}</p>
Actually it only affects the devs. This field isn't poppulated with external data. As long as who implements the component knows this, we won't have any problems. I changed it with your suggestion

2023-01-13 16:58 UTC, GuiMend commented on spa/src/components/settings/Integration/Integration.tsx
> +const Integration = () => {
Yeah, I've seen it.  I have that change locally, that's why I didn't see it break. Will commit it.

2023-01-13 17:14 UTC, GuiMend commented on spa/src/components/base/Switch/Switch.tsx
> +export const StyledSwitch = styled(MuiSwitch)<SwitchProps>`
Thanks. That worked for me as well. I've spoken with Rachel and the color can be #969696

2023-01-13 21:37 UTC, nrh-cklimas approved these changes

2023-01-19 05:01 UTC, x110dc approved these changes

2023-01-19 17:26 UTC, merged