DEV-1539: Improve page title for Donation Pages
newsrevenuehub/rev-engine pull request #918
Opened 2022-12-28 19:32 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
Fixes Page title for Donation pages.
Before it was showing "RevEngine" and now it's showing "Join | [RV-name]"

#### Why are we doing this? How does it help us?
Helps the client have a personalized page title for their donation pages.

#### How should this be manually tested? Please include detailed step-by-step instructions.
- Check donation pages from different Revenue Programs
- Page title should be "Join | [RV-name]"

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
yes

#### Have automated unit tests been added? If not, why?
yes

#### How should this change be communicated to end users?
Page title now shows their revenue program name.

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-1539

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2023-01-04 15:42 UTC, benjaminEwhite requested changes

2023-01-04 15:42 UTC, benjaminEwhite commented on spa/src/elements/PageTitle.tsx
> +  hideRevEngine: false
Not sure if this is our established convention yet or not, but just wondering what is advantage of `.defaultProps` vs. having default param values in the original component definition. I don't have strong feelings on this (slight aesthetic preference for default param vals in component definition), and mainly just want to understand our convention (if any).

2023-01-04 15:42 UTC, benjaminEwhite commented on spa/src/elements/PageTitle.tsx
> +const PageTitle = ({ title, hideRevEngine }: PageTitleProps) => {
If `hideRevEngine` is only being used to determine whether or not a page title is set, why not just have parent context conditionally display and keep this component dumb?

Also, just curious about behavior of react Helmet here: what happens ultimately gets rendered in situ if `hideRevEngine` is false?

2023-01-04 15:42 UTC, benjaminEwhite commented on spa/src/components/donationPage/LiveDonationPageContainer.test.tsx
> +jest.mock('elements/PageTitle', () => ({ title }: { title: string }) => {
Why does `PageTitle` need to be mocked here?

2023-01-04 15:42 UTC, benjaminEwhite commented on spa/src/components/donationPage/LiveDonationPageContainer.test.tsx
> +  it('should render custom title', async () => {
Because we're mocking out the actual element that's used to display page title, this test doesn't give me much confidence that `LiveDonationPageContainer` succeeds at displaying page title.

2023-01-04 15:42 UTC, benjaminEwhite commented on spa/src/components/donationPage/LiveDonationPageContainer.test.tsx
> +      within(screen.getByTestId('mock-page-title')).getByText(`Join | ${mockData.revenue_program.name}`)
Instead of `getByTestId`, could we use `document.title` instead? I'm seeing that usage referenced here: https://github.com/testing-library/react-testing-library/issues/402#issuecomment-1013392720

2023-01-04 15:42 UTC, benjaminEwhite commented on spa/src/elements/PageTitle.test.tsx
> +  test('should render custom document header is updated', async () => {
_It should render custom document header is updated_ doesn't quite make sense. 

Does _should render updated document header_ capture the meaning?

2023-01-06 13:17 UTC, GuiMend commented on spa/src/elements/PageTitle.tsx
> +const PageTitle = ({ title, hideRevEngine }: PageTitleProps) => {
Actually the `hideRevEngine` is there to append or not `RevEngine` to the end of the title string. I've updated the variable name to make it clearer.

2023-01-06 13:22 UTC, GuiMend commented on spa/src/components/donationPage/LiveDonationPageContainer.test.tsx
> +jest.mock('elements/PageTitle', () => ({ title }: { title: string }) => {
My thought process at the time was to abstract all child components and difer the testing of each child component to their respective test file. On a second thought, it does make sense to leave this one unmocked. Thanks for catching it.

2023-01-06 13:22 UTC, GuiMend commented on spa/src/components/donationPage/LiveDonationPageContainer.test.tsx
> +  it('should render custom title', async () => {
Correct. Updated it 👍

2023-01-06 13:28 UTC, GuiMend commented on spa/src/elements/PageTitle.test.tsx
> +  test('should render custom document header is updated', async () => {
Sorry about that. I didn't read the whole sentence, just added the "should render" 🤦‍♂️ 
Fixed

2023-01-06 16:00 UTC, benjaminEwhite approved these changes
LGTM

2023-01-10 05:08 UTC, merged