DEV-2806: Update layout for contributions export
newsrevenuehub/rev-engine pull request #925
Opened 2023-01-03 15:25 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
Updates the email template that is sent when user's asks for contributions export.

#### Why are we doing this? How does it help us?
Email template was just text, so we needed to update the design.

#### How should this be manually tested? Please include detailed step-by-step instructions.
- Login
- Access contributions page
- Click Export button
- Check that email design matches figma

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
Yes

#### Have automated unit tests been added? If not, why?
Yes

#### How should this change be communicated to end users?
n/a

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-2806

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2023-01-04 16:26 UTC, benjaminEwhite requested changes
Overall looks good. Couple of tiny requests re: copy, but those may need to be confirmed with Mariclare and/or Rachel.

2023-01-04 16:26 UTC, benjaminEwhite commented on apps/emails/templates/nrh-contribution-csv-email-body.html
> +<p class="content-header">Your Export is Ready!</p>
```suggestion
<p class="content-header">Your export is ready!</p>
```

2023-01-04 16:26 UTC, benjaminEwhite commented on apps/emails/templates/nrh-contribution-csv-email-body.html
> +<p class="content-body">Download the attached csv to access your exported contributions data.</p>
```suggestion
<p class="content-body">Download the attached CSV file to access your exported contributions data.</p>
```

2023-01-05 18:03 UTC, GuiMend commented on apps/emails/templates/nrh-contribution-csv-email-body.html
> +<p class="content-header">Your Export is Ready!</p>
This one we want to keep it like it is. 👍

2023-01-06 16:12 UTC, benjaminEwhite approved these changes

2023-01-12 02:12 UTC, x110dc approved these changes

2023-01-13 13:46 UTC, merged