WIP DEV-3073 | Fix donor selected formatted amount and sync from Stripe management command
newsrevenuehub/rev-engine pull request #927
Opened 2023-01-04 20:10 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-01-05 21:09 UTC, njharman requested changes
Looks good, as per usual. Only a few minor suggestions. Sigh, you never code anything wrong enough for a meaty review ;)

I do see ticket comment about adjusting AC to match the limited scope of this ticket. In cases like that, it would be helpful (for review) to list the AC this PR purports to fulfill.  I don't think it does all of them, but, I believe that is intended.  Not 100% sure. Has the AC edit happened?

2023-01-05 21:09 UTC, njharman commented on apps/contributions/models.py
> +        for contribution in queryset.filter(interval=ContributionInterval.ONE_TIME):
Not worth change here, probably.  But if we're writing these two queries (one times) and (recurrings) all over. Might consider creating custom Contribution manager with methods like .onetime() and .recurring() that return those querysets.

https://docs.djangoproject.com/en/4.1/topics/db/managers/#adding-extra-manager-methods

2023-01-05 21:13 UTC, njharman commented on apps/contributions/payment_managers.py
> +    def attach_payment_method_to_customer(self, stripe_customer_id, org_stripe_account, payment_method_id=None):
This doesn't seem to be covered. But, it seems wrong to "punish" the guy fixing typo with having to also fix the lack of test coverage.

2023-01-05 22:04 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        ):
54a597b

2023-01-05 22:08 UTC, benjaminEwhite commented on apps/contributions/models.py
> +                    one_times_updated += 1
2db9a23b2

2023-01-05 22:08 UTC, benjaminEwhite commented on apps/contributions/models.py
> +                    one_times_updated += 1
2db9a23b2

2023-01-05 22:10 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            # For optimal data integrity, this function should be run only after `fix_contributions_stuck_in_processing`
019b9631136

2023-01-05 22:25 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        for contribution in queryset.filter(interval=ContributionInterval.ONE_TIME):
49d78c7617

2023-01-05 22:25 UTC, benjaminEwhite commented on apps/contributions/payment_managers.py
> +    def attach_payment_method_to_customer(self, stripe_customer_id, org_stripe_account, payment_method_id=None):
While I'm happy to clean up the road, I don't want to pay the toll.

2023-01-06 18:57 UTC, njharman commented on apps/contributions/models.py
> +                    one_times_updated += 1
nice

2023-02-09 21:07 UTC, benjaminEwhite commented
Closing, tearing down, then reopening as part of work for [DEV-3243 | fix hookdeck webhooks](https://news-revenue-hub.atlassian.net/browse/DEV-3243), to trigger fresh review app.

2023-03-21 20:45 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> -
This is weird and has no related test or apparent use case, and tests don't break without it, so removed.

2023-04-25 04:59 UTC, x110dc requested changes
I requested a few small changes and had a few questions. Nothing big I don't think.

2023-04-25 04:59 UTC, x110dc commented on apps/contributions/models.py
> +        else:
Is this `else` necessary?

2023-04-25 04:59 UTC, x110dc commented on apps/contributions/models.py
> +        else:
Is this `else` necessary?

2023-04-25 04:59 UTC, x110dc commented on apps/contributions/models.py
> +        else:
Is this `else` necessary?

2023-04-25 04:59 UTC, x110dc commented on apps/contributions/serializers.py
> +            logger.info("`CreateOneTimePaymentSerializer.create` is saving a new contribution with REJECTED status")
I appreciate the verbosity; but we can log the module, function name and line number by changing the logging format. That's probably the preferred way to capture this.

2023-04-25 04:59 UTC, x110dc commented on apps/contributions/views.py
> +        queryset = self.get_queryset() if request.user.is_staff else self.get_queryset()
It's the same result for both conditions, no?

2023-04-25 04:59 UTC, x110dc commented on apps/contributions/webhooks.py
> +                f"`StripeWebhookProcessor.handle_payment_intent_canceled` webhook handler ran for contribution with ID {contribution.id}"
I don't think these log statements need to change as part of this PR, but maybe we open a ticket and add TODOs with that ticket ID?

2023-04-25 13:26 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +            logger.info("`CreateOneTimePaymentSerializer.create` is saving a new contribution with REJECTED status")
I agree. Leo and I were discussing this last week and created [DEV-3520](https://news-revenue-hub.atlassian.net/browse/DEV-3520) to adopt function name prefixing in our logging formatters and to standardize throughout the app.

2023-04-25 13:26 UTC, benjaminEwhite commented on apps/contributions/webhooks.py
> +                f"`StripeWebhookProcessor.handle_payment_intent_canceled` webhook handler ran for contribution with ID {contribution.id}"
[DEV-3520](https://news-revenue-hub.atlassian.net/browse/DEV-3520)

2023-04-26 21:24 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        else:
98fb73bfd6c

2023-04-26 21:24 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        else:
98fb73bfd6c

2023-04-26 21:24 UTC, benjaminEwhite commented on apps/contributions/models.py
> +        else:
98fb73bfd6c

2023-04-26 21:26 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        queryset = self.get_queryset() if request.user.is_staff else self.get_queryset()
bc903576e8cf51

2023-05-02 03:34 UTC, x110dc approved these changes

2023-05-08 20:53 UTC, merged