DEV-2518: add tax_id field to revenue program response
newsrevenuehub/rev-engine pull request #929
Opened 2023-01-06 07:41 UTC by leo-dcfa

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

N/A

#### What's this PR do?

- Add `tax_id` to revenue program response from rev-engine
- Makes `tax_id` available in Django admin

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

- Start the app with `make run-dev`
- Navigate to Django Admin and open any revenue program
- Assert that the `tax_id` field is available on the page
- Add a value and save the record
- Copy the id for the revenue program
- Run ` curl -c cookiejar -v -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"email":"{your username}", "password": "{your password}"}' http://localhost:8000/api/v1/token/`
- Run `curl -b cookiejar -v -H "Content-Type: application/json" -H "Accept: application/json" -X GET "http://localhost:8000/api/v1/revenue-programs/{record id} /" \ |jq .`
- Assert that `tax_id` was included in the response

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

N/A

#### Have automated unit tests been added? If not, why?

Yes

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

N/A

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-2518]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-01-11 20:24 UTC, benjaminEwhite requested changes
Left a few comments. Biggest thing is we need to prevent org users from having access to other org's data, and that will require some refactoring to achieve.

2023-01-11 20:24 UTC, benjaminEwhite commented on apps/organizations/tests/test_org_views.py
> +        non_superusers = [self.hub_user, self.contributor_user]
There are some critical paths where there are missing tests, as well as data being leaked between orgs/RPs. Specifically, we need tests per method/endpoint that show that a user of a given type (in this case org user) who has access to the endpoints as such nevertheless does not other people's data in responses.

I added the following tests locally, which fail. Could probably be cleaned up, but this is what I'm talking about:


```
def test_cannot_retrieve_someone_elses_rp(self):
        other_org_user = create_test_user(
            role_assignment_data={"role_type": Roles.ORG_ADMIN, "organization": self.org2}
        )
        assert other_org_user.roleassignment.organization != self.org1
        self.assert_user_cannot_get(self.detail_url, other_org_user)

 def test_other_orgs_rps_not_appear_in_my_list_of_rps(self):
        other_org_user = create_test_user(
            role_assignment_data={"role_type": Roles.ORG_ADMIN, "organization": self.org2}
        )
        assert other_org_user.roleassignment.organization != self.org1
        assert (expected_rp_count := other_org_user.roleassignment.organization.revenueprogram_set.count()) == 1

        response = self.assert_user_can_get(self.list_url, other_org_user)
        assert len(response.json()) == expected_rp_count
        # assert that all returned have ids owned by requesting user etc.
```

2023-01-11 20:24 UTC, benjaminEwhite commented on apps/organizations/tests/test_org_views.py
> +        non_superusers = [self.hub_user, self.contributor_user]
These kinds of cases are covered extensively in the unit tests for contributions views, if you want to see how I handled testing (and implementation) there.

2023-01-11 20:24 UTC, benjaminEwhite commented on apps/organizations/views.py
>  class RevenueProgramViewSet(viewsets.ReadOnlyModelViewSet):
Now that we're adding `patch` to this viewset, might be better to not inherit from ReadOnlyModelViewset. As currently implemented, the `patch` method will run and works, but  when you see that this is ReadOnlyModelViewSet you don't expect it to have `patch`. I'd prefer to see a combination of viewset mixins, or barring that, perhaps a code comment here explaining why there's a patch on a readonly model view set.

2023-01-11 20:24 UTC, benjaminEwhite commented on apps/organizations/views.py
> +            errors = {**serializer.errors}
Is this casting something dict like to dict, or to avoid mutation, or what?

2023-01-11 20:29 UTC, leo-dcfa commented on apps/api/permissions.py
> +    """
good catch, thanks

2023-01-11 20:43 UTC, leo-dcfa commented on apps/organizations/views.py
> +            errors = {**serializer.errors}
ah thanks I copied a template piece of code to get started and didn't realise that it wasn't needed

2023-01-11 20:55 UTC, leo-dcfa commented on apps/organizations/views.py
>  class RevenueProgramViewSet(viewsets.ReadOnlyModelViewSet):
thanks, good point

2023-01-11 22:07 UTC, leo-dcfa commented on apps/organizations/tests/test_org_views.py
> +        non_superusers = [self.hub_user, self.contributor_user]
Thanks for that, code updated

2023-01-23 19:59 UTC, benjaminEwhite approved these changes

2023-02-09 20:20 UTC, benjaminEwhite commented
Closing, tearing down, then reopening to trigger new review app build, as part of [DEV-3243 | fix hookdeck webhooks](https://news-revenue-hub.atlassian.net/browse/DEV-3243).

2023-02-14 22:05 UTC, benjaminEwhite commented
Closing and reopening (after dealing with merge conflicts) to solve for migration conflict that will break review app deploys.

2023-02-15 14:19 UTC, benjaminEwhite approved these changes

2023-02-16 03:27 UTC, x110dc approved these changes

2023-02-16 03:57 UTC, merged