DEV-2213: Allow blob image URLs in CSP
newsrevenuehub/rev-engine pull request #934
Opened 2023-01-10 18:48 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

Creating review app to test the fix.

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-01-12 15:23 UTC, benjaminEwhite requested changes
@nrh-cklimas code change to solve for acute problem (image not appearing in preview) looks fine, and confirmed it works locally.

I love that we're going to be able to remove the unrendered template vars, but the bug I found with the missing images seems like it should be run down (even if conclusion is "we understand why this is happening and we can live with it).

If LOE on that is relatively high, might make sense to reduce this PR to just the change to solve for bug, and then handle the make command in a separate PR, in interest of getting ticket across board.

2023-01-12 15:23 UTC, benjaminEwhite commented on README.md
> +This reverses control locally. Django will serve the React app at `http://localhost:8000`, parsing template tags in the React app's HTML and enforcing CSP. If you use this task, you must set the envi
Why won't the nonces be correct? 

To be clear, this is a great improvement, and I'm happy to see the template crud going away. We're just so close to being able fully test CSP locally (inclusive of enforcing), I thought I'd ask.

2023-01-12 15:23 UTC, benjaminEwhite commented on revengine/urls.py
> -    urlpatterns += staticfiles_urlpatterns()
Not sure if this is related or not, but _some_ images are breaking when running with `make run-hybrid`. When I go to login page for dashboard with `make run-hybrid` running, there are two broken images.


<img width="1330" alt="Screenshot 2023-01-12 at 10 08 31 AM" src="https://user-images.githubusercontent.com/960351/212105070-16545a68-eae4-4193-9dc1-57b5257ae934.png">


However, when I run using usual approach (`python manage.py runserver` in one tab and `npm run start:subdomains` in another), the images render.

2023-01-12 20:46 UTC, nrh-cklimas commented on README.md
> +This reverses control locally. Django will serve the React app at `http://localhost:8000`, parsing template tags in the React app's HTML and enforcing CSP. If you use this task, you must set the envi
I added some more explanation in 162fd76c85216cc024f7ec854ba70af5fa5e2710. The problem (I think) is that Webpack injects script and style tags when serving up the SPA which don't get a nonce attribute applied to them. At least, I think that is what's going on.

2023-01-12 20:47 UTC, nrh-cklimas commented on revengine/urls.py
> -    urlpatterns += staticfiles_urlpatterns()
Fixed this in dc4e6da270f60fb612a3a89fb3cf4e92ea02529d. The issue was that the proxy was trying to send images as text content.

2023-01-26 21:25 UTC, x110dc requested changes

2023-01-26 21:25 UTC, x110dc commented on revengine/views.py
> +def proxy_spa_dev_server(request, upstream="http://localhost:3000"):
clever

2023-01-27 14:04 UTC, nrh-cklimas commented on revengine/urls.py
>      import debug_toolbar
My read of it is, git blame points to https://github.com/newsrevenuehub/rev-engine/commit/6756ba2b92d194f2bf5cff44895c0411013df88d where this was set up. It looks like at that point, the SPA was configured to build continuously to the Django static directory (e.g. look at webpack.local.config.js in that commit). At some point, our tooling drifted apart... create-react-app doesn't generate bundled files during local dev, so there are no files to serve up there anymore.

2023-01-27 21:59 UTC, x110dc commented on revengine/urls.py
>      import debug_toolbar
Got it. Thanks!

2023-01-27 21:59 UTC, x110dc approved these changes

2023-01-30 16:56 UTC, benjaminEwhite approved these changes

2023-01-30 18:33 UTC, merged