Dev 2745 user last login admin page
newsrevenuehub/rev-engine pull request #936
Opened 2023-01-11 20:00 UTC by harsha09

#### What's this PR do?
Adds `last_login` field to the users table in Django Admin.

#### Why are we doing this? How does it help us?
Admin to know the context of user in on-boarding process.

#### How should this be manually tested? Please include detailed step-by-step instructions.
Login to Django Admin -> Go to `Users` section -> `Last Login` column should be displayed.
Click on a user in user list -> `Last Login` field displayed which is read-only.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
Changes only in Django Admin.

#### Have automated unit tests been added? If not, why?
NA as this is only a field addition.

#### How should this change be communicated to end users?
NA

#### Are there any smells or added technical debt to note?
NA

#### Has this been documented? If so, where?
Not yet

#### What are the relevant tickets? Add a link to any relevant ones.
[DEV-2745]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
NA

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
NA

2023-01-12 23:13 UTC, leo-dcfa commented on apps/users/admin.py
>                      "email",
I know this is a small change but a unit test wouldn't hurt 
See example here:

https://github.com/newsrevenuehub/rev-engine/blob/main/apps/users/tests/test_admin.py#L33

I would add a unit test for both detail as well as list display

2023-01-12 23:13 UTC, leo-dcfa requested changes
Small change requested

2023-01-16 20:09 UTC, harsha09 commented on apps/users/admin.py
>                      "email",
addressed using 472dec2941a358700f53016787113e81ac0c5de5

2023-01-16 20:45 UTC, leo-dcfa approved these changes

2023-01-19 07:58 UTC, leo-dcfa approved these changes
Test performed:

Created new user leo.alves+dev-2745@fundjournalism.org
Logged in through sign-in page (not Django Admin)
Last login was updated

2023-01-23 23:57 UTC, x110dc approved these changes

2023-01-24 18:50 UTC, merged