DEV-2805: Fix payment selection highlight
newsrevenuehub/rev-engine pull request #937
Opened 2023-01-12 12:51 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
Show the correct contribution amount selection if user inputs a custom amount and changes frequency.

#### Why are we doing this? How does it help us?
The user was already contributing with the underlying amount selection, but it wasn't being highlighted correctly in the amount selection section.

#### How should this be manually tested? Please include detailed step-by-step instructions.
1. Enter a contribution page such as [RevEngine](https://alfa.revengine-test.org/donate/)
2. Enter a custom giving amount ie $500 for monthly contributions
3. See that you will be charged $500 if you submit your payment
4. Switch frequency to one-time or yearly frequency
5. See that the amount being charged changes to whatever is the default for the new frequency… but that frequency button is not colored in a way that shows it is being selected
6. Also see that the custom amount you entered earlier is still being shown despite it not being used

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
no

#### Have automated unit tests been added? If not, why?
yes

#### How should this change be communicated to end users?
n/a

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-2805

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2023-01-13 13:44 UTC, nrh-cklimas requested changes

2023-01-13 14:53 UTC, GuiMend commented on spa/src/components/donationPage/pageContent/DAmount.test.tsx
> +      // spinbutton = <input type="number" />
Not really, it's an explenation that role="spinbutton" relates to input with type=number. I'll make it clearer

2023-01-13 14:58 UTC, GuiMend commented on spa/src/components/donationPage/pageContent/DAmount.tsx
> +              currencySymbol={page.currency?.symbol ?? '$'}
I think TS complained about this, but I'll try again.

2023-01-13 16:51 UTC, GuiMend commented on spa/src/components/donationPage/pageContent/DAmount.test.tsx
>  import { axe } from 'jest-axe';
You are right. I've added a test for this.

2023-01-13 21:42 UTC, nrh-cklimas commented on spa/src/components/donationPage/pageContent/DAmount.test.tsx
>  import { axe } from 'jest-axe';
Sorry, I think I'm missing where you added the test?

2023-01-13 21:44 UTC, nrh-cklimas commented on spa/src/constants/contributionIntervals.ts
> +export const CONTRIBUTION_INTERVALS: { [x: string]: ContributionInterval } = {
Oh, I see. I think then yeah, the type then would be something like

```ts
export type ContributionIntervalKey = 'ONE_TIME' | 'MONTHLY' | 'ANNUAL';

export const CONTRIBUTION_INTERVALS: Record<ContributionIntervalKey, ContributionInterval> = {...
```

There might be a nicer way to put it, though.

2023-01-16 17:01 UTC, GuiMend commented on spa/src/components/donationPage/pageContent/DAmount.test.tsx
>  import { axe } from 'jest-axe';
To cypress. It's a test that involves multiple components

2023-01-16 20:29 UTC, GuiMend commented on spa/src/components/donationPage/pageContent/DAmount.test.tsx
>  import { axe } from 'jest-axe';
This file: `spa/cypress/e2e/01-donationPage.cy.js`
commit: [8ade874](https://github.com/newsrevenuehub/rev-engine/pull/937/commits/8ade87427c709db8d2e86dd4a20ac4a98b93ebfd)

2023-01-17 13:54 UTC, nrh-cklimas commented on spa/src/components/donationPage/pageContent/DAmount.test.tsx
>  import { axe } from 'jest-axe';
I see, thanks.

2023-01-17 13:55 UTC, nrh-cklimas approved these changes

2023-01-17 19:50 UTC, x110dc approved these changes

2023-01-17 20:42 UTC, merged