Dev 2718 org admins can patch org name
newsrevenuehub/rev-engine pull request #939
Opened 2023-01-12 22:38 UTC by leo-dcfa

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

Please merge this PR before merging #929 to main

#### What's this PR do?

- Adds ability to patch org name to the org admin
- Modifies `Organization` model such `authenticated_classes` to allow responses under the following conditions:

1. User is authenticated and
2. User is super user or
3. User is Org Admin and is a patch request or
4. User has a role and it's a get request

#### Why are we doing this? How does it help us?

This is part of larger epic [DEV-3067] - Org Settings V1

#### How should this be manually tested? Please include detailed step-by-step instructions.

- Start the app with `make run-dev`
- Navigate to Django Admin and open any revenue program
- Copy the id for the revenue program
- Run ` curl -c cookiejar -v -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"email":"{your username}", "password": "{your password}"}' http://localhost:8000/api/v1/token/`
- As part of the response from the above, a CSRF token is returned - you will use the token in the next step
- curl -b cookiejar -v -H "Content-Type: application/json" -H "Accept: application/json" -H "X-CSRFToken: {csrf token from response above}" -X PATCH "http://localhost:8000/api/v1/organizations/25/" -d '{ "name": "{some new name}"} '| jq .` and assert the response has the update name

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

N/A

#### Have automated unit tests been added? If not, why?

Yes

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

N/A

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-2718]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

N/A

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

N/A

2023-01-20 19:44 UTC, benjaminEwhite reviewed
As mentioned in line, need to wait on DEV-3149 to be merged before this can move forward. It establishes a paradigm around testing and model managers that we should use moving forward instead of extending some in retrospect idiosyncratic patterns I created several months ago.

2023-01-20 19:44 UTC, benjaminEwhite commented on apps/organizations/models.py
> +
I think we should converge on the approach I've started to try to standardize in PR for DEV-3149. That involves using a model manager, and by convention defining a common method called `filtered_by_role_assignment`, which takes a roleassignment instance as its argument and returns a filtered queryset.

You can see how we're using this method in a view for revenue programs here: https://github.com/newsrevenuehub/rev-engine/blob/DEV-3149-standardize-approach-for-testing-permissions-layer-of-api-with-organizations-app-as-first-instance/apps/organizations/views.py#L66-L70

2023-01-20 19:44 UTC, benjaminEwhite commented on apps/organizations/tests/test_org_views.py
> +        read_only_users = [self.hub_user, self.rp_user]
After DEV-3149 gets merged into DEV-2518, we'll need to revisit these tests and make sure everything's squared away.

2023-01-20 19:44 UTC, benjaminEwhite commented on apps/organizations/views.py
> +        patch_serializer = serializers.OrganizationPatchSerializer(organization, data=request.data, partial=True)
After DEV-3149 is merged into DEV-2518, we should be able to simplify this quite a bit. Need to revisit at that point.

2023-01-24 07:36 UTC, leo-dcfa commented on apps/organizations/tests/test_org_views.py
> +    def test_permissive_users(self, method, url_name, has_data, api_client, user, organization):
@benjaminEwhite did my best to incorporate these cases in the method above but the if/elses become so complex that it didn't make much sense anymore. So I separated this test into another method and kept some duplication for the sake of clarity. What do you think?

2023-01-24 07:36 UTC, leo-dcfa commented on apps/organizations/views.py
> +        if not request.user.is_superuser and not self.model.objects.filtered_by_role_assignment(request.user.roleassignment):
thanks for the updates, now using `filtered_by_role_assignment` as indicated @benjaminEwhite

2023-01-24 07:43 UTC, leo-dcfa commented on apps/organizations/models.py
> +
See implemented code and let me know if it's not ok

2023-02-08 16:09 UTC, benjaminEwhite commented
Closing then tearing down then reopening in order to trigger a fresh review app, as required by recently merged migrations.

2023-02-08 18:20 UTC, benjaminEwhite commented on apps/organizations/tests/test_org_views.py
> +    def test_patch_when_expected_user(
@leo-dcfa ideally tests for patching org name should be added in paramterize call above for this test function. If the test implementation would have to change a lot, can test for this else where, but ideally, AC4

> Display Name is not modifiable by Revenue Program Admins (only by Org Admins)

would be tested for as one case among the several other parametrized ones here.

2023-02-08 21:27 UTC, leo-dcfa commented on apps/organizations/views.py
To review: changes to OrganizationViewSet + patch method

2023-02-08 21:34 UTC, leo-dcfa commented on apps/organizations/tests/test_org_views.py
> +@pytest.fixture
to review: TestOrganizationViewSet and other

2023-02-09 06:28 UTC, leo-dcfa commented on apps/organizations/tests/test_org_views.py
> +    def test_patch_when_expected_user(
@benjaminEwhite confused about a couple of things:
- `test_patch_when_expected_user` exists twice, is this intended?
- you added a test for `invalid_patch_data_unexpected_fields` expecting a 200 - what are we testing here?
- Using this test function to validate negative cases doesn't seem right... because of the combination of two `parametrize` decorators, we would need a bunch of if/else to cover all the cases...

2023-02-09 15:26 UTC, benjaminEwhite requested changes
@leo-dcfa this is close (and again, my apologies for dumping this huge diff on your lap!).

Left one suggestion to simplify the `patch` method.

Also left some thoughts on the test of patch endpoint.

2023-02-09 15:26 UTC, benjaminEwhite commented on apps/organizations/views.py
> +            return Response(status=status.HTTP_404_NOT_FOUND)
```suggestion
    def patch(self, request, pk):
        organization = get_object_or_404(self.get_queryset(), pk=pk)
```

2023-02-09 15:26 UTC, benjaminEwhite commented on apps/organizations/tests/test_org_views.py
> +    def test_patch_when_expected_user(
@leo-dcfa `test_patch_when_expected_user` exists once on `TestOrganizationViewSet` and once on `TestRevenueProgramViewSet`.

Re: 200 and unexpected fields, that's just to codify the default behavior of our API -- namely, if you throw unexpected fields over the fence in patch data, things still work out okay. You can also choose to reject the entire request, but that would require higher LOE.

Re: 3rd comment IMO there's not an excessive amount of conditional nesting here.  There are other places where I've broken out thins out into more granular, specific tests when complexity in test set up / conditionality etc. is too much. That said, I like having a single test function that can succinctly tell the entire story of an endpoint  + method + set of users.

Would be totally fine to break this out into two separate tests -- one for happy path, one for validation errors. I can see why that might be easier to maintain.

2023-02-09 15:26 UTC, benjaminEwhite commented on apps/organizations/tests/test_org_views.py
> +    def test_patch_when_expected_user(
At the risk of being pedantic -- one thing we'll need to preserve if refactor this test is need to continue testing patch of owned vs. unowned resources for non-superuser.  Part of the reason I like the current implementation is because it tests many related behaviors in a small amount of code, but the downside is that it's easier to miss the point of each step in the test. But overall, I like being able to have a docstring like this one:

```
"""Show that expected users are able to patch (only) permitted RPs, with valid data"""
```

If your test actually does all that that docstring says, it's very clear how it aligns to business value.

(And again, to be clear, that has to be balanced vs. maintainability).

2023-02-10 14:43 UTC, benjaminEwhite requested changes
Trivial request for some explanation in a doc string. Other than that, there's a conversation from last review I think you may have missed: https://github.com/newsrevenuehub/rev-engine/pull/939/files#r1100519800

2023-02-10 14:43 UTC, benjaminEwhite commented on apps/organizations/tests/test_org_views.py
> +        """Show that user cannot patch another org they are not part of"""
Can be more specific in this comment — only org admins can access this patch endpoint.

2023-02-10 22:40 UTC, leo-dcfa commented on apps/organizations/tests/test_org_views.py
> +    def test_patch_when_expected_user(
Sorry for missing this comment yesterday! But I think the new tests do cover the extra cases, namely:

- test_patch_when_unexpected_user: covers negative cases
- test_patch_different_org: covers security aspect

test_patch_when_expected_user covers positive cases/happy path. From that perspective I think we covered everything. I did chose to not have a method that covers all tests as I believe this is easier to reason about (+ I could not get it to work 😓 )

2023-02-10 23:17 UTC, benjaminEwhite approved these changes

2023-02-10 23:33 UTC, leo-dcfa commented on apps/organizations/views.py
> +class OrganizationViewSet(
To review: `OrganizationViewSet`:

- permission classe updates
- patch method

2023-02-10 23:35 UTC, leo-dcfa commented on apps/organizations/tests/test_org_views.py
> +def org_valid_patch_data():
To review: `OrganizationViewSetTest` method

- `test_patch_when_expected_user`
- `test_patch_when_unexpected_user`
- `test_patch_different_org`

2023-02-14 03:49 UTC, x110dc approved these changes

2023-02-14 16:25 UTC, benjaminEwhite commented
After merging in upstream changes, need to close, then tear down, then reopen to deal with otherwise conflicting migrations that will block releases on review app.

2023-02-14 16:53 UTC, benjaminEwhite commented
In hindsight, since QA for this was local, probably could have not rebuilt review app...

2023-02-14 22:02 UTC, merged