DEV-3052: Create Color Picker Preview component
newsrevenuehub/rev-engine pull request #940
Opened 2023-01-16 19:18 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
Creates a Color Picker Preview component and add it to Create/Edit Styles Modal to make it easier for the user to understand what each color does.

#### Why are we doing this? How does it help us?
This addition will help users understand what the labels correspond to on the page template and make design decisions without going back-and-forth from the theme editor to the page editor. 

#### How should this be manually tested? Please include detailed step-by-step instructions.
- Check component story `Common/ColorPickerPreview` and make sure it's the same as [figma](https://www.figma.com/file/wrLXOnehGlR5zLWAy5tJTQ/%5BDES-46%5D-Style-Improvements?node-id=30%3A819&t=iUIxThuNzn5H9Dqp-0)
- Log in
- Edit a style
- Check that the Color preview is showing in the Create/Edit style modal.

![image](https://user-images.githubusercontent.com/9381325/212750571-4185410e-9c7d-46a1-8aef-509252d3e486.png)

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
yes

#### Have automated unit tests been added? If not, why?
yes

#### How should this change be communicated to end users?
Color preview is now available in the Create/Edit Style modal to facilitate seeing what each color affects

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3052

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
https://news-revenue-hub.atlassian.net/browse/DEV-2936

2023-01-17 16:15 UTC, nrh-cklimas requested changes

2023-01-17 16:15 UTC, nrh-cklimas commented on spa/src/components/common/ColorPickerPreview/ColorPickerPreview.test.tsx
> +  it('should apply custom inputBorderColor as "#a1b2c3"', () => {
Could this test and the one below it be moved into the `it.each()` above?

2023-01-17 16:25 UTC, GuiMend commented on spa/src/components/common/ColorPickerPreview/ColorPickerPreview.styled.ts
> +export const LineInput = styled.p<{ $color?: string | null; $border?: string | null }>`
I guess I wanted to do something but in the end wasn't needed and forgot to undo this part.

2023-01-17 17:32 UTC, GuiMend commented on spa/src/components/common/ColorPickerPreview/ColorPickerPreview.test.tsx
> +  it('should apply custom inputBorderColor as "#a1b2c3"', () => {
I've grouped them in a different loop because they are the temporary fields and it will be easier to remove it later.

2023-01-17 17:37 UTC, nrh-cklimas approved these changes

2023-01-23 23:52 UTC, x110dc approved these changes

2023-01-24 18:15 UTC, merged