Dev 3131 handle fiscal sponsorship tax status
newsrevenuehub/rev-engine pull request #950
Opened 2023-01-19 21:50 UTC by leo-dcfa

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

I went for the implementation choice that we infer a RevenueProgram is considered a nonprofit if there is an associated fiscal sponsor name. Removing the fiscal sponsor name will not remove the status of nonprofit automatically - is this something to be considered?

#### What's this PR do?

- Add new field `fiscal_sponsor_name` to `RevenueProgram`
- Add corresponding migration
- Expose new field through Django Admin
- Took opportunity to modify some assertions to use pytest `assert` and `pytest.raises` instead

#### Why are we doing this? How does it help us?

On the Revenue Program object in our data model, we feature several fields that help organizations define their tax status. These settings are used to determine how fees should be calculated on the donation page and during payment processing, as well as how the Org is described in disclaimer language in our transactional receipts and payment reminder emails. 

#### How should this be manually tested? Please include detailed step-by-step instructions.

- Go to Django Admin -> `Revenue Programs`
- Find a for profit Revenue Program
- Add a fiscal_sponsor_name and save the record
- Assert that the checkbox for `nonprofit` was automatically checked

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

N/A

#### Have automated unit tests been added? If not, why?

Yes

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

N/A

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-3113]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

N/A

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

N/A

2023-01-20 20:18 UTC, benjaminEwhite requested changes

2023-01-20 20:18 UTC, benjaminEwhite commented on apps/organizations/models.py
> +    fiscal_sponsor_name = models.CharField(max_length=63, null=True, blank=True)
63 is sort of a "magic number" here, so let's re-use the existing constant for that value `RP_SLUG_MAX_LENGTH` here, or else define a different constant (which could assign the value for `RP_SLUG_MAX_LENGTH` as its own value).

2023-01-20 20:18 UTC, benjaminEwhite commented on apps/organizations/models.py
> +        # Ensure the presence of a Fiscal sponsor automatically treats the RevenueProgram as nonprofit
```suggestion
        """Ensure the presence of a fiscal sponsor automatically treats the RevenueProgram as nonprofit"""
```

2023-01-20 20:18 UTC, benjaminEwhite commented on apps/organizations/models.py
> +        if self.fiscal_sponsor_name is not None and self.fiscal_sponsor_name != "":
Seems like it would be enough just to test that self.fiscal_sponsor_name is truthy.

```suggestion
        if self.fiscal_sponsor_name:
```

2023-01-20 20:18 UTC, benjaminEwhite commented on apps/organizations/tests/test_org_models.py
> +    def test_fiscal_sponsor_name_sets_non_profit(self):
I'd rather see this test broken out into a module level pytest function just so we can make use of `pytest.mark.parametrize` instead  of this subTest.

you can have a look at how that's being done in this PR, among other places. https://github.com/newsrevenuehub/rev-engine/pull/952

2023-01-20 20:18 UTC, benjaminEwhite commented on apps/organizations/tests/test_org_models.py
> +        for fiscal_sponsor_name, expected in [("", False), (None, False), ("NRH", True)]:
These are the values to parametrize.

2023-01-20 21:43 UTC, leo-dcfa commented on apps/organizations/tests/test_org_models.py
> +    def test_fiscal_sponsor_name_sets_non_profit(self):
I was split between doing that or not, initially tried to use `pytest.mark.parametrize` and discovered it doesn't work when a class extends `UnitTest` - will do it

2023-01-25 18:08 UTC, GuiMend submitted a review, later dismissed
@leo-dcfa , I believe this PR is also missing to add `fiscal_sponsor_name` in 
`patch: users/[userId]/customize_account`.
```
apps > users > serializer > CustomizeAccountSerializer
apps > users > views > UserViewset > customize_account
```

2023-01-30 16:51 UTC, benjaminEwhite requested changes
Left several comments/requests.

High-level, I wanted to respond to the following point you made, @leo-dcfa:

> I went for the implementation choice that we infer a RevenueProgram is considered a nonprofit if there is an associated fiscal sponsor name. Removing the fiscal sponsor name will not remove the status of nonprofit automatically - is this something to be considered?

I do think this is important to consider both from an implementation and testing standpoint. If we ship as is, we're all but guaranteed to have data integrity issues where we won't be able to naively trust that when the API reports an RP as non-profit, that it is indeed non-profit. 

So one solution is to revisit the clean step and to handle the case of going from having fiscal sponsor to not having one. 

That all seems pretty "side effecty" to me. Haven't fully thought it through, but we might consider doing something like having a derived model property called called from a custom serializer field that derives the value for `is_nonprofit`  _at the API layer_ from the state of the `fiscal_sponsor_name` and `non_profit` fields on the model. IMO, it's cleaner to handle the interplay between fiscal sponosor name and non profit boolean in that layer of app.

2023-01-30 16:51 UTC, benjaminEwhite commented on apps/organizations/tests/test_admin.py
> +def test_show_expected_fields_on_rp_pages(admin_client):
This test name either needs to be narrower (`test_rp_page_admin_has_fiscal_sponsor_name`) or else should assert what it claims to assert in test name, and show that all expected fields appear.

2023-01-30 16:51 UTC, benjaminEwhite commented on apps/organizations/tests/test_org_models.py
> +class RevenueProgramTest:
Believe this test class won't be picked up by pytest's test runner.
```suggestion
class TestRevenueProgram:
```

2023-01-30 16:51 UTC, benjaminEwhite commented on apps/organizations/tests/test_org_models.py
>      def setUp(self):
This method should be deleted entirely. `setUp` is a unittest specific method. Direction we should be trying to go in is data setup for tests in (parametrized) fixtures

2023-01-30 16:51 UTC, benjaminEwhite commented on apps/organizations/tests/test_org_models.py
> +    @pytest.mark.parametrize("fiscal_sponsor_name, expected", (("", False), (None, False), ("NRH", True)))
This is nitpicking, but i've been omitting space between commas in first arg to `.parametrize`. Though spaces are fine, i just followed convention in pytest docs (no space), and would prefer to keep this consistent throughout.  If there's a strong argument for adding space, that's something we can consider too, but probably would want to handle in a separate ticket. 

```suggestion
    @pytest.mark.parametrize("fiscal_sponsor_name,expected", (("", False), (None, False), ("NRH", True)))
```

2023-01-30 16:51 UTC, benjaminEwhite commented on apps/users/serializers.py
> +    fiscal_sponsor_name = serializers.CharField(write_only=True, required=False, default=None)
Do we want to consider a max length here?

2023-01-30 16:51 UTC, benjaminEwhite commented on apps/users/tests/test_views.py
> +            "fiscal_sponsor_name": "",
Out of scope for this PR, but sure would like to refactor this test suite to only use pytest + parametrized fixtures at some point.

2023-01-31 07:05 UTC, leo-dcfa commented
I see your point about having too much side effects in the transition between nonprofit and for-profit when a fiscal sponsor name is added. I did consider going down the route of using the view to derive if a record is nonprofit but that introduced another challenge: potential data integrity issues on Django Admin side. If on the Django Admin side we were to add a fiscal sponsor name and forget to make an RP for nonprofit, the UI would present a record that is technically incorrect. And if the org admin updates the fiscal sponsor name, then the RP would become nonprofit. 

A few alternatives:
- On the clean method, if the `fiscal_sponsor_name` has a value and `non_profit` is checked, we raise a validation error: fiscally sponsored RPs cannot be for profit. We remove the side effects but enforce integrity
- Introduce a new choice field `fiscal_status`: `for profit`, `nonprofit` and `fiscally sponsored`; make `is_nonprofit` a `@property` that `return True if self.fiscal_status in ("nonprofit", "fiscally sponsored")`. I am a bigger fan of this approach, but requires a bit more work

2023-01-31 07:05 UTC, leo-dcfa commented on apps/organizations/tests/test_admin.py
> +def test_show_expected_fields_on_rp_pages(admin_client):
that makes sense, fixed

2023-01-31 16:19 UTC, benjaminEwhite commented
@leo-dcfa I'm a big fan of the second solution. IMO it's worth the incremental additional effort spent (assuming that it is indeed incrementally more difficult) as we'll avoid an entire landscape of data integrity bugs that may otherwise end up consuming future dev time.

2023-02-02 06:06 UTC, leo-dcfa commented on apps/users/serializers.py
> +    fiscal_sponsor_name = serializers.CharField(write_only=True, required=False, default=None)
good idea

2023-02-02 06:07 UTC, leo-dcfa commented on apps/users/tests/test_views.py
> +            "fiscal_sponsor_name": "",
agreed, I changed the assertions to pytest style to pave the way for that

2023-02-03 09:42 UTC, leo-dcfa commented on apps/organizations/tests/test_org_models.py
>      def setUp(self):
reverted this change for now

2023-02-03 17:13 UTC, benjaminEwhite reviewed
Overall looking good. A couple of questions.

2023-02-03 17:13 UTC, benjaminEwhite commented on apps/users/serializers.py
> +        fiscal_sponsor_name = self.initial_data.get("fiscal_sponsor_name")
Wondering what would happen here if there's a first patch that sets both fiscal_sponsor_name and fiscal_status, and then a subsequent patch that only sets fiscal_status. IIUC, in that case, `self.initial_data.get("fiscal_sponsor_name")` will be None, even though the RP instance. in question that value might be set. I haven't fully run down how this plays out, but can you look into it and see if there's anything to this?

2023-02-03 17:13 UTC, benjaminEwhite commented on apps/users/serializers.py
> +        fiscal_sponsor_name = self.initial_data.get("fiscal_sponsor_name")
Further thought: may be that this should be a follow up ticket (non-blocking). Looking at the `customize_account` view function, looks like it doesn't have any guards against endpoint being hit up multiple times with same data, in which case on subsequent requests, there will be uncaught server errors. Probably want to get/or create or else validation behavior that catches this case, since it appears that this endpoint is only meant to be used once.

2023-02-04 00:20 UTC, leo-dcfa commented on apps/organizations/tests/test_org_models.py
> +        assert len(long_slug_rp.slug) < 100
good point!

2023-02-04 00:58 UTC, leo-dcfa commented on apps/users/serializers.py
> +        fiscal_sponsor_name = self.initial_data.get("fiscal_sponsor_name")
https://news-revenue-hub.atlassian.net/browse/DEV-3236 great point, added here. Maybe we could use this as an opportunity to remove `UnitTest` from `customize_account`

2023-02-06 14:27 UTC, GuiMend reviewed
LGTM @leo-dcfa 👍

2023-02-06 17:09 UTC, GuiMend commented
I've updated this PR's description to mention the stacked PRs.

2023-02-07 19:14 UTC, benjaminEwhite commented
Closing then tearing down then reopening to trigger fresh review app build so we don't get error triggered by renamed migration.

2023-02-08 02:26 UTC, GuiMend commented
Just a heads-up @leo-dcfa , https://github.com/newsrevenuehub/rev-engine/pull/963 was merged into this branch 👍

2023-02-08 04:15 UTC, leo-dcfa commented
thanks @GuiMend - cc @x110dc

2023-02-09 21:06 UTC, benjaminEwhite commented
Closing, tearing down, then reopening as part of work for [DEV-3243 | fix hookdeck webhooks](https://news-revenue-hub.atlassian.net/browse/DEV-3243), to trigger fresh review app.

2023-02-10 04:28 UTC, x110dc approved these changes

2023-02-14 22:03 UTC, merged