Dev 2765 page editor data layer refactor
newsrevenuehub/rev-engine pull request #957
Opened 2023-01-25 15:59 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

This is the feature branch that these subtasks were merged into:

- https://news-revenue-hub.atlassian.net/browse/DEV-2864
- https://news-revenue-hub.atlassian.net/browse/DEV-2865
- https://news-revenue-hub.atlassian.net/browse/DEV-2866
- https://news-revenue-hub.atlassian.net/browse/DEV-2867

This PR is mostly for QA purposes. No other additional commits have been added.

#### What's this PR do?

Refactors the page editor logic so the majority of it occurs in hooks instead of logic embedded into components, and adds tests around those hooks.

#### Why are we doing this? How does it help us?

Gets us closer to being able to use Jest tests, improves dev speed going forward because we won't have to write code for manual API interactions going forward for new functionality.

#### How should this be manually tested? Please include detailed step-by-step instructions.

A lot has changed behind the scenes in the page editor so comprehensive QA is needed. We may also want this on staging 

Here are suggested tasks to test:

1. Add an element to a page and confirm that it saves properly and displays in the live contribution page.
2. Edit an element to a page and confirm it saves and displays properly.
3. Remove an element from a page and confirm it saves and displays properly.
4. Add an element to a page sidebar, confirm it saves/displays.
5. Edit a sidebar element, confirm it saves/displays.
6. Remove a sidebar element, confirm it saves/displays.
7. Check the image fields in the setup tab for regressions--able to add and remove images (and that removing one doesn't affect unrelated fields).
8. Check that the text fields in the setup tab save correctly and are reflected in the donation page.
9. Check that changing styles on a page saves/displays.
10. Check that adding a new style to a page through the Style tab works.
11. 

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

No.

#### Have automated unit tests been added? If not, why?

Yes.

#### How should this change be communicated to end users?

n/a

#### Are there any smells or added technical debt to note?

No.

#### Has this been documented? If so, where?

No.

#### What are the relevant tickets? Add a link to any relevant ones.

- https://news-revenue-hub.atlassian.net/browse/DEV-2864
- https://news-revenue-hub.atlassian.net/browse/DEV-2865
- https://news-revenue-hub.atlassian.net/browse/DEV-2866
- https://news-revenue-hub.atlassian.net/browse/DEV-2867

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No.

2023-01-26 19:31 UTC, GuiMend requested changes
@nrh-cklimas, I'm having issues with:
1. Adding blocks to the sidebar:
![image](https://user-images.githubusercontent.com/9381325/214930793-682f7e6c-e344-4049-be83-dcf6de2f7e27.png)

2. After removing a block from the "Layout" tab > saving > the item still appears there. Give it a delay of around 5s and the screen updates with the correct blocks

3. Removing blocks from sidebar. Item disapears from preview, but it still shows in the sidebar. After saving, same behavior as item 2. occurs. (After save, block shows in the preview again, wait 5s, page refreshes, removs block and closes automatically the sidebar)

These are the issues I found so far. Will continue searching

2023-01-27 12:14 UTC, GuiMend requested changes
Update block on sidebar showing 👍 

1. Found other issues: in the sidebar, after adding 1 block each, I added some text and uploaded an image, saved the page, tried deleting all 3 block from sidebar and this happens:
When clicking the delete button, instead of removing the block it swapped `Contribution benefits` <-> `Image` back and forth
![image](https://user-images.githubusercontent.com/9381325/215083225-7ec51d87-57ff-4cdb-ac85-92c1485f7960.png)
![image](https://user-images.githubusercontent.com/9381325/215083345-5238ce46-c2ab-49f1-9483-2f9944dfd6be.png)


2. When changing the orther in Layout:
![image](https://user-images.githubusercontent.com/9381325/215083752-86cd538b-4535-4e9c-81b3-f4313f6e428f.png)
After clicking to save, the preview shows the "old" version, and only updates back to the correct order after the save is successfull
![image](https://user-images.githubusercontent.com/9381325/215084516-41874cfe-9542-4a25-bc4d-e3bd5756fc00.png)
![image](https://user-images.githubusercontent.com/9381325/215084124-9e2d9f88-ce70-4266-ab97-f133e987fb8c.png)

2023-01-31 18:14 UTC, GuiMend approved these changes

2023-02-08 19:03 UTC, GuiMend approved these changes

2023-02-08 19:03 UTC, GuiMend commented on spa/src/components/pageEditor/editInterface/EditInterfaceContextProvider.tsx
> +    throw new Error('EditInterfaceContext must be used inside an EditInterfaceContextProvider');
Could add this error message into a const as it's used several times in this file

2023-02-08 19:26 UTC, nrh-cklimas commented on spa/src/components/pageEditor/editInterface/EditInterfaceContextProvider.tsx
> +    throw new Error('EditInterfaceContext must be used inside an EditInterfaceContextProvider');
Updated in 27e1641e24d00488ed1f16e0dab230e52a32041d

2023-02-08 21:15 UTC, x110dc approved these changes

2023-02-09 15:07 UTC, merged