DEV-3129: Handle fiscal sponsor in onboarding
newsrevenuehub/rev-engine pull request #963
Opened 2023-01-26 15:22 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
- Adds option for organizations to add Fiscal Sponsor information during onboarding.

#### Why are we doing this? How does it help us?
- There are some orgs that fit this scenario and we needed to add the feature to the existing onboarding flow.

#### How should this be manually tested? Please include detailed step-by-step instructions.
- Create new account
- Check that onboarding modal fits all requirement AC:
```
1. Build matches spec 
2. Tooltip is present on EIN field in profile step and copy matches specs. 
3. “Fiscally sponsored” is featured as an option in the Organization Tax Status dropdown 
4. “Fiscally sponsored” is a selectable Org Tax Status option 
5. When “Fiscally sponsored” is selected, the field “Fiscal Sponsor Name” displays 
6. When Tax Status is changed from Fiscally Sponsored to another selectable option, “Fiscal Sponsor Name” field disappears from the view 
7. When “Fiscally sponsored” is selected, a “Fiscal Sponsor Name” value is required to successfully submit the profile step form. 
8. On submission, tax status, fiscal sponsorship, and fiscal sponsor name are all saved to the Revenue Program object. (Data model TBD based on ). 
9. Fiscal Sponsor field accepts an alphanumeric string with character limit of 63. 
10. When Tax Status is changed from Fiscally Sponsored to another selectable option, any previously entered but not submitted value for Fiscal Sponsor Name is not stored to the Revenue Program object. 
11. “Non-profit” selectable option is updated on front-end to read “Nonprofit”
```
#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
yes

#### Have automated unit tests been added? If not, why?
In progress

#### How should this change be communicated to end users?
Organizations with Fiscal Sponsorship now supported

#### Are there any smells or added technical debt to note?
no 

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-3129

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
https://news-revenue-hub.atlassian.net/browse/DEV-3018

2023-01-31 14:38 UTC, nrh-cklimas requested changes

2023-01-31 14:38 UTC, nrh-cklimas commented on spa/src/components/account/Profile/ProfileForm.tsx
> +export const FISCALLY_SPONSORED = 'fiscally-sponsored';
Consider making a union type for the different values (`'fiscally-sponsored'`, `'nonprofit'`, `'for-profit'`)--right now it feels a little strange to have a constant for fiscally-sponsored but use string literals for the other statuses.

2023-01-31 14:38 UTC, nrh-cklimas commented on spa/src/components/account/Profile/__mocks__/ProfileForm.tsx
> +    onProfileSubmit({ ...mockFormData, companyTaxStatus: 'fiscally-sponsored' });
```suggestion
    onProfileSubmit({ ...mockFormData, companyTaxStatus: FISCALLY_SPONSORED });
```

2023-01-31 21:46 UTC, nrh-cklimas approved these changes

2023-02-07 20:53 UTC, x110dc approved these changes

2023-02-07 21:17 UTC, merged