[WIP] DEV-3164 | Standardize page view tests and retire a bunch of technical debt
newsrevenuehub/rev-engine pull request #965
Opened 2023-01-27 19:22 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-01-30 15:58 UTC, benjaminEwhite commented on apps/pages/tests/test_viewsets.py
> +        "name": fake.company(),  # random
```suggestion
        "name": fake.company(),
```

2023-01-30 16:01 UTC, benjaminEwhite commented on apps/contributions/tests/test_views.py
> +        self.assert_user_cannot_get(reverse("contribution-list"), novel, expected_status_code=status.HTTP_403_FORBIDDEN)
This change is because we now get a more sensical status code after solving for a bug that caused an uncaught 500 when unexpected role type.

2023-01-30 16:03 UTC, benjaminEwhite commented on apps/pages/tests/factories.py
> +    styles = {
Previously, the value set for `styles` here was not one that validation would allow. Below constitutes a minimally valid `styles` value.

2023-01-30 16:04 UTC, benjaminEwhite commented on apps/pages/tests/test_models.py
> +from apps.users.models import Roles
```suggestion
from apps.users.choices import Roles
```

2023-01-31 01:03 UTC, njharman requested changes
Overall great direction and code clean up.  A scattering of minor things and suggestions. And...

pre-commit failed, safety, complaining about lib "future" vulnerability.  Also "Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them."

Those don't seem to fall under ticket disclaimer about failing tests due to cypress.

2023-01-31 17:03 UTC, benjaminEwhite commented on apps/common/validators.py
> +# todo: make this more "Django-esque"
Removed. 5eeac967878e8

2023-01-31 17:08 UTC, benjaminEwhite commented on apps/common/validators.py
> +            # logger.warning(f"")
743c28d6

2023-01-31 17:17 UTC, benjaminEwhite commented on apps/pages/models.py
> +                return self.none()
Dried up into a common manager used in both models.

1d6024a6a0a

2023-01-31 17:19 UTC, benjaminEwhite commented on apps/pages/serializers.py
> +        name = data.pop("name", self.instance.name if self.instance else None)
815c3b28c1

2023-01-31 17:27 UTC, benjaminEwhite commented on apps/pages/serializers.py
> +        if any([x.get("type", None) is None for x in data.get("elements", [])]):
82b861fd36

2023-01-31 17:28 UTC, benjaminEwhite commented on apps/pages/serializers.py
> +            [elem["type"] for elem in data.get("sidebar_elements", []) if elem.get("type", None)]
bb26bbf0f0

2023-01-31 17:52 UTC, benjaminEwhite commented on apps/organizations/views.py
> +        else:  # pragma: no cov
Weird. Comes up as uncovered even with no branch. Not sure what's going on here, but possibly a bug with Coverage.

2023-01-31 18:06 UTC, benjaminEwhite commented on apps/pages/serializers.py
> +        if prohibited := [
db9345bad

2023-01-31 18:16 UTC, benjaminEwhite commented on apps/organizations/views.py
> +        else:  # pragma: no cov
🤦 it needed to be `# pragma: no cover`

638131f12

2023-01-31 19:19 UTC, benjaminEwhite commented on apps/pages/views.py
> +            return self.model.objects.filtered_by_role_assignment(self.request.user.roleassignment)
Good point. 827dcb748

2023-01-31 19:23 UTC, benjaminEwhite commented
@njharman responded to all in-line comments.

Re: 

> pre-commit failed, safety, complaining about lib "future" vulnerability. Also "Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them."

I've merged in upstream changes and the `future` vulnerability is gone. 

I did `poetry update` which should take care of the other issue (and didn't seem otherwise problematic, but let me know if this is a bad idea): 6688a034ad

2023-02-03 19:54 UTC, njharman approved these changes
Looks good, ship it!

Thanks for ticket comment highlighting changed code (and why). It was very useful in helping me figure out what to look at for rereview.

2023-02-07 23:24 UTC, x110dc approved these changes
Great to see so much code removed. LGTM!

2023-02-08 15:54 UTC, merged