Dev 3070 add event indicates page published
newsrevenuehub/rev-engine pull request #974
Opened 2023-02-01 10:30 UTC by leo-dcfa

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

Pending ticket confirmation on how to add `publisher_email` and `publisher_name`

#### What's this PR do?

- Refactored Google Cloud PubSub into a separate Django app
- Adapted usage of Google Cloud PubSub emulator for M1 Macbook
- Introduced Django Signals and using it in two places: user signals and page signals. 
- Removed coupling between Google Cloud PubSub message publishing from User model

#### Why are we doing this? How does it help us?

- Introducing Django Signals means we can decouple operations independently from operations on Models
- We would like to notify whenever a page is first published (different ticket will tackle the notification to slack - [DEV-3069]
- Refactoring user model so that the publishing operation is decoupled from save operations leads us to a cleaner model

#### How should this be manually tested? Please include detailed step-by-step instructions.

- Add the following variables to your `.envrc`
```text
export NEW_USER_TOPIC=new-nre-customer-test
export GOOGLE_CLOUD_PROJECT=revenue-engine
export PUBSUB_PROJECT_ID=revenue-engine
export GOOGLE_APPLICATION_CREDENTIALS=fake-service-account.json
export PUBSUB_EMULATOR=[::1]:8085
export PUBSUB_EMULATOR_HOST=[::1]:8085
export PAGE_PUBLISHED_TOPIC=contribution-page-published
```
- Run `make run-gcloud-pub-sub`
- Start the dev server + google cloud pub sub emulator with make run-gcloud-pub-sub
- On a separate terminal window run  `python manage.py shell` and paste the following script:

```python
# this is a helpful script to connect to topic from the Django shell
import os

from google.cloud import pubsub_v1

topic_name = "projects/{project_id}/topics/{topic}".format(
    project_id=os.getenv("GOOGLE_CLOUD_PROJECT"), topic=os.getenv("PAGE_PUBLISHED_TOPIC")
)

print(f"Subscribing to topic {topic_name}")

subscription_name = "projects/{project_id}/subscriptions/{sub}".format(
    project_id=os.getenv("GOOGLE_CLOUD_PROJECT"),
    sub="TEST",
)

print(f"Will attempt to delete existing subscription with name {subscription_name}")

try:
    pubsub_v1.SubscriberClient().delete_subscription(request={"subscription": subscription_name})
except:  # noqa
    print("Subscription did not exist prior; will continue")

def callback(message):
    print(message.data)
    message.ack()

with pubsub_v1.SubscriberClient() as subscriber:
    subscriber.create_subscription(name=subscription_name, topic=topic_name)
    print(f"New subscription created; listening messages in topic {topic_name}")
    future = subscriber.subscribe(subscription_name, callback)
    future.result()
```

The above will create a subscription to your local Google Cloud PubSub emulator
- Sign in and go to `/pages`
- Choose any unpublished page and publish it
- Go back to your terminal and assert that a message was delivered

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

N/A

#### Have automated unit tests been added? If not, why?

Yes

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

No

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-3070]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

- We need to configure Google Cloud PubSub and create a new topic for publishing the page messages
- Rev Engine needs to have the environment variable `PAGE_PUBLISHED_TOPIC` set to new topic

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

- [DEV-3069]

2023-02-07 15:03 UTC, benjaminEwhite commented on apps/common/tests/test_utils.py
> +)
🥇

2023-02-07 15:26 UTC, benjaminEwhite requested changes
Overall this is a great direction. Really happy to see a bunch of side effects in save methods going away. Believe we should be able to emulate this approach to solve for [DEV-3026 | remove buried Stripe retrieve side effect from `Contribution.save`](https://news-revenue-hub.atlassian.net/browse/DEV-3026).

Left a few comments/requests for change, the biggest of which is probably the one about implications of page pub being a pre- rather than post-save signal.

2023-02-07 15:26 UTC, benjaminEwhite commented on apps/pages/signals.py
> +def donation_page_pre_save(sender, instance, update_fields, **kwargs) -> None:
I'm a little concerned about this being a pre-save signal in that we're signaling to outside world that a page is published, when the save itself could fail, in which case the page would not in fact be published. Tracking down and managing side effects in a pub/sub system will be complex.

Any reason we can't have this be a post save?

2023-02-07 15:26 UTC, benjaminEwhite commented on apps/users/tests/test_signals.py
> +    "gcloud_configured, created, user_topic",
Would prefer to consistently use "no space between param name" style as that's what's in pytest docs, and it' what the preponderance of existing usage is (and would like try to be uniform).

2023-02-07 15:26 UTC, benjaminEwhite commented on google_cloud_pub_sub/Dockerfile
> +FROM google/cloud-sdk:414.0.0-alpine
Just curious why we don't need the `RUN` commands. Does the updated cloud sdk version give us that for free?

2023-02-07 21:26 UTC, leo-dcfa commented on apps/common/tests/test_utils.py
> +)
🚀

2023-02-07 21:30 UTC, leo-dcfa commented on apps/pages/signals.py
> +def donation_page_pre_save(sender, instance, update_fields, **kwargs) -> None:
I had the same predicament. We need to know if the page is being published for the first time and in the post_save signal, we cannot determine it; at least I couldn't come up with a way of doing it. Do you have any suggestions?

2023-02-07 21:36 UTC, leo-dcfa commented on apps/users/tests/test_signals.py
> +    "gcloud_configured, created, user_topic",
I'm sorry - it's not the first time you asked me to do this; will try to remember next time, force of habit

2023-02-07 21:37 UTC, leo-dcfa commented on google_cloud_pub_sub/Dockerfile
> +FROM google/cloud-sdk:414.0.0-alpine
Exactly, the updated version just worked

2023-02-09 19:54 UTC, benjaminEwhite requested changes

2023-02-09 19:54 UTC, benjaminEwhite commented on apps/users/tests/test_signals.py
> +        instance.publish.assert_called_with(user_topic, Message(data=user.email))
See approach in equivalent test for pages. Think we need something similar here.

2023-02-09 21:03 UTC, benjaminEwhite commented
Closing, tearing down, then reopening as part of work for [DEV-3243 | fix hookdeck webhooks](https://news-revenue-hub.atlassian.net/browse/DEV-3243), to trigger fresh review app.

2023-02-09 23:31 UTC, leo-dcfa commented on apps/users/signals.py
> +def user_post_save_handler(sender, instance, created, **kwargs) -> None:
This is part of the overall goal to switch to signals, I thought it was an easy win

2023-02-09 23:33 UTC, leo-dcfa commented on apps/users/models.py
> -        return self._state.adding and self.email
At this point I would leave it here... when we decided to switch to signals + make google cloud a separate django app I thought it was an easy win. If you don't mind I prefer if we include it instead of trying to separate the changes

2023-02-09 23:34 UTC, leo-dcfa commented on apps/pages/models.py
> +            signals.page_published.send(sender=self.__class__, instance=self)
I think this suggestion wo't work. We need to save the value of should_send_first_publication_signal prior to calling the save method; that way we can check the db to see if the record was published for the first time

2023-02-09 23:52 UTC, leo-dcfa commented on apps/users/signals.py
> +def user_post_save_handler(sender, instance, created, **kwargs) -> None:
updated AC

2023-02-09 23:52 UTC, leo-dcfa commented on apps/users/tests/test_signals.py
> +        instance.publish.assert_called_with(user_topic, Message(data=user.email))
updated AC

2023-02-09 23:53 UTC, leo-dcfa commented on apps/pages/models.py
> +            return True if not existing_page.published_date else False
This method is called prior to saving the record (calling super().save()). That way we can check the value in db vs in flight record

2023-02-09 23:57 UTC, leo-dcfa commented on apps/pages/tests/test_signals.py
> +def test_donation_page_page_published_handler(publisher, gcloud_configured, topic, monkeypatch):
I thought that gets covered on `test_first_published_pub_sub_behavior_when_pubsub_configured`, no? Especially after your suggestion, unless I missed something

2023-02-10 04:15 UTC, leo-dcfa commented
I did rename `should_send_first_publication_signal` method as suggested but kept the flow to call the method before we save so that we can compare in flight record with db record prior to saving

2023-02-10 14:50 UTC, benjaminEwhite commented on apps/pages/models.py
> +        return f"{http_scheme}{self.revenue_program.slug}.{settings.SITE_URL.partition(http_scheme)[2]}/{self.slug}"
Huh! i never knew about `.partition`!

2023-02-10 15:18 UTC, benjaminEwhite requested changes
A few small requests left in line.

Other than that, there are a couple of unresolved conversations:

- https://github.com/newsrevenuehub/rev-engine/pull/974/files#r1101718624
- https://github.com/newsrevenuehub/rev-engine/pull/974/files#r1101736520

2023-02-10 15:18 UTC, benjaminEwhite commented on apps/pages/models.py
> +            return True if not existing_page.published_date else False
Is line 230 right? Shouldn't it be:

```
if not self.id and self.published_date:
```

?

2023-02-10 15:18 UTC, benjaminEwhite commented on apps/pages/tests/test_models.py
> +        )
Another advantage of moving message generation to a page model method is that test assertion around it here can be much cleaner (namely we could just do `publisher_spy.publish.assert_called_once_with(topic_name, Message(json.dumps(page.get_pubsub_page_published_message_data()`.

2023-02-10 15:18 UTC, benjaminEwhite commented on apps/pages/tests/test_signals.py
> +            publisher_instance.publish.assert_called_with(topic, Message(data=json.dumps(expected_payload)))
Ditto here. Moving generation of this payload to a model method allow this test to be more concise/cleaner.

2023-02-10 15:18 UTC, benjaminEwhite commented on apps/users/signals.py
> +def user_post_save_handler(sender, instance, created, **kwargs) -> None:
This should have a doc string that explains basic business logic of this (namely that on new user creation, we publish a message).

2023-02-10 15:27 UTC, benjaminEwhite commented on apps/pages/models.py
> +        if not self.id:
This works, but either an `elif` or `if not self.id and self.published_date` just so we're iron clad.

2023-02-10 23:43 UTC, leo-dcfa commented on apps/pages/models.py
> +        return f"{http_scheme}{self.revenue_program.slug}.{settings.SITE_URL.partition(http_scheme)[2]}/{self.slug}"
I also discovered it as part of this change, pretty cool right?

2023-02-10 23:44 UTC, leo-dcfa commented on apps/pages/models.py
> +        should_send_first_publication_signal = self.should_send_first_publication_signal()
good point

2023-02-10 23:44 UTC, leo-dcfa commented on apps/pages/models.py
> +        if not self.id:
updated it

2023-02-12 02:37 UTC, leo-dcfa commented on apps/pages/signals.py
> +        }
not sure it's a good idea to live it in the page model. I think the model stays cleaner, we pass on the instance to the signal and the signal worries about what it wants. Cleaner model, focused on business logic and not background processing

2023-02-12 04:18 UTC, leo-dcfa commented on apps/pages/tests/test_models.py
> +    return DonationPageFactory(published_date=datetime.datetime.now())
Is it ok if we apply that change later? Not a big deal, just don't want to block this ticket further because of DEV-2718 and DEV-2518 which have been blocked for a while

2023-02-12 04:20 UTC, leo-dcfa commented on apps/users/signals.py
> +def user_post_save_handler(sender, instance, created, **kwargs) -> None:
done

2023-02-12 04:22 UTC, leo-dcfa commented on apps/pages/tests/test_models.py
> +        )
See comment here https://github.com/newsrevenuehub/rev-engine/pull/974/files#r1103724985

2023-02-12 04:22 UTC, leo-dcfa commented on apps/pages/tests/test_signals.py
> +            publisher_instance.publish.assert_called_with(topic, Message(data=json.dumps(expected_payload)))
Same, comment here See comment here https://github.com/newsrevenuehub/rev-engine/pull/974/files#r1103724985

2023-02-12 04:27 UTC, leo-dcfa commented on apps/pages/signals.py
> +        }
I don't think there is a right or wrong answer about this one actually, in terms of implementation there is a balance between choosing how much we do on each side. If we consider `signals` as a flavour of events in event driven architectures, it's the debate between thin events or fat events. I went for the approach where the signal has more data and figures out what it needs on the handler size. the Django post_save and pre_save handlers pass the full instance to signal receivers. We could make a thin signal that has the very minimal for publishing data, which is another valid approach. 

I think before we have a clear direction between which we should adopt, I suggest we go with the current approach and refactor later if we think we prefer something different.

2023-02-14 17:17 UTC, benjaminEwhite commented on apps/pages/models.py
> +        """
```suggestion
        # should_send_first_publication_signal has to be called prior to saving the record
        # to allow us to compare in flight record with record in database
```

2023-02-14 17:24 UTC, benjaminEwhite approved these changes

2023-02-14 21:12 UTC, x110dc requested changes
Had one question.

2023-02-14 21:21 UTC, leo-dcfa commented on apps/pages/signals.py
> +    logger.warning(
Good catch! Fixed it

2023-02-14 21:36 UTC, x110dc approved these changes

2023-02-15 18:03 UTC, njharman approved these changes
Reviewed and approved. Wrote several typo / consideration comments. Nothing requiring rereview. You should just resolve them (ideally after reading them).

2023-02-15 18:06 UTC, njharman commented on apps/google_cloud/pubsub.py
>          return cls.__instance
This not covered by unittests

2023-03-01 03:34 UTC, x110dc approved these changes

2023-03-01 04:10 UTC, merged