DEV-2857: Add validation to URL setup fields
newsrevenuehub/rev-engine pull request #978
Opened 2023-02-02 19:13 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

Adds front-end validation of URL fields in the page editor setup tab.

#### Why are we doing this? How does it help us?

Improved UX; prevents users from losing changes on save--e.g. previous to this, if you tried to save a change with an invalid URL, Django would reject it and all changes would be lost.

#### How should this be manually tested? Please include detailed step-by-step instructions.

For each URL field in the Setup tab:

1. Edit it to text that isn't a valid URL (single space, URL without https:// in front of it, etc.)
2. Confirm that the field shows an error message and the Update button on the tab is disabled.
3. Edit the field to a valid URL and confirm you are able to save changes.
4. Confirm that deleting all text from the field is allowed.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

We might want to capture the validation messages in some way.

#### Have automated unit tests been added? If not, why?

Yes.

#### How should this change be communicated to end users?

n/a

#### Are there any smells or added technical debt to note?

I thought about using an external module to test for a valid URL, but it's such a small function it didn't feel worth it.

#### Has this been documented? If so, where?

No.

#### What are the relevant tickets? Add a link to any relevant ones.

https://news-revenue-hub.atlassian.net/browse/DEV-2857

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

No.

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No.

2023-02-02 19:14 UTC, nrh-cklimas commented on spa/cypress/fixtures/pages/live-page-1.json
> +  "header_link": "",
Needed because otherwise, Cypress tests would set these values to `undefined` which `isValidUrl` rejects. These should always be strings IRL, but they might be empty.

2023-02-03 13:50 UTC, GuiMend requested changes
Not sure it's working entirely @nrh-cklimas:

![image](https://user-images.githubusercontent.com/9381325/216619363-ac6934d7-c11d-4d29-b8c4-99eae0aaf87d.png)

It does work when I mess up the protocol part:
![image](https://user-images.githubusercontent.com/9381325/216619873-626ca02e-03be-48dc-b5b3-95406fcf81cc.png)

2023-02-06 12:43 UTC, GuiMend requested changes
Spaces in between the URL now throws error 👍 

![image](https://user-images.githubusercontent.com/9381325/216974294-29e49805-ca79-430d-ba19-7aba152a61b5.png)

But it's still allowing some weird URLs like `[any char in the place of http]:[any string even without dots in the middle]`. Is that acceptable?

2023-02-08 19:09 UTC, GuiMend approved these changes
One small comment. No need for re-review

2023-02-08 21:06 UTC, x110dc approved these changes

2023-02-08 21:53 UTC, merged