DEV-3325 | Last mile work for DEV-3073
newsrevenuehub/rev-engine pull request #982
Opened 2023-02-03 23:31 UTC by benjaminEwhite

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-02-09 20:57 UTC, benjaminEwhite commented
Closing, tearing down, then reopening as part of work for [DEV-3243 | fix hookdeck webhooks](https://news-revenue-hub.atlassian.net/browse/DEV-3243), to trigger fresh review app.

2023-02-14 14:21 UTC, benjaminEwhite commented
Closing, tearing down, and reopening to get upstream migration changes to work in review app build.

2023-02-16 16:10 UTC, benjaminEwhite commented on apps/common/utils.py
> -# class AttrDict(dict):
Came across this and there's no use of it, and we're using a library for this instead (addict.AttrDict).

2023-02-17 19:40 UTC, njharman requested changes
Many questions, a little missing test coverage.

2023-02-17 19:40 UTC, njharman commented on apps/contributions/views.py
> +        ids = (self.model.objects.all() if request.user.is_staff else self.get_queryset()).values_list("id", flat=True)
I couldn't find in AC (probably in previous ticket) So, I'm just gonna state the logic I see here. So, you can verify that is the intent.

1. if user.if_staff = True get all records
2. if user is Contributor get whatever ContributationsCacheProvider returns [I still don't see how cache miss is suppose to work, seems to me it will return empty and will have to refresh/call again until celery task fills in data.  Also, (I did not verify) it seems that until task runs and populates data every new call will spawn another task.  Like if user keeps refreshing page cause it has empty results]
3. if user.anon get nothing
4. if user.is_superuser = True get all records
5. if user is HUB/ORG/RP ADMIN get those records with the exclusions mentioned in AC flaged/rejected/processing
6. else if user is none of those raise ApiConfigurationError

One thing, which existed before this ticket, is if non-staff superuser or HUB/ORG/RP are also Contributors they lose their special access. [Although, I think I vaguely remember this is not possible (different accounts) or not an issue we care about today]

That seems correct all spelled out, than I thought. More rubber ducking myself.

2023-02-17 19:40 UTC, njharman commented on apps/contributions/models.py
> +            if not stripe_entity:
elif, else and if not strip_entity are not covered by tests.

2023-02-17 19:40 UTC, njharman commented on apps/contributions/models.py
> +            else:
else not covered by tests

2023-02-17 19:40 UTC, njharman commented on apps/contributions/models.py
> +            return False
if not covered by tests

2023-02-17 19:40 UTC, njharman commented on conftest.py
> +        "apps.contributions.models.Contribution.fetch_stripe_payment_method", lambda *args, **kwargs: None
fetch_strip_payment_method is uncovered by tests. Here and everywhere it is patched out.

I suggest patching out the least, the thing we don't want to happen because it is slow and/or external; stripe.PaymentMethod.retrieve()

This is probably task for another ticket. Maybe mention to @x110dc and if we all agree, I can create ticket.

2023-02-17 22:12 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            stripe_entity = None
510b9db21bca3b39e1

2023-02-17 22:14 UTC, benjaminEwhite commented on apps/contributions/models.py
> +                logger.info(
39f89ae15ab23

2023-02-17 22:14 UTC, benjaminEwhite commented on apps/contributions/models.py
> +                logger.info(
39f89ae15ab23

2023-02-17 22:15 UTC, benjaminEwhite commented on apps/contributions/tasks.py
> +    Note that this task is intentionally "dumb". It implicitly assumes that it is safe to data about contribution ids
795cf16ee80

2023-02-17 22:16 UTC, benjaminEwhite commented on apps/contributions/tasks.py
> +    if diff := set(contribution_ids).difference(set(list(contributions.values_list("id", flat=True)))):
bc2fcbb3ba611

2023-02-17 22:22 UTC, benjaminEwhite commented on apps/contributions/tasks.py
> +        subject="Check out your Contributions",
This is status quo behavior, and called for by designs.

2023-02-17 22:24 UTC, benjaminEwhite commented on apps/contributions/tasks.py
> +            ", ".join([str(x) for x in diff]),
20e3034cea02

2023-02-17 22:27 UTC, benjaminEwhite commented on apps/contributions/views.py
> +        ids = (self.model.objects.all() if request.user.is_staff else self.get_queryset()).values_list("id", flat=True)
Believe this is not something we need to worry about for now, but let's leave this comment thread unresolved and @x110dc can chime in when he reviews.

2023-02-22 00:39 UTC, benjaminEwhite commented on conftest.py
> +        "apps.contributions.models.Contribution.fetch_stripe_payment_method", lambda *args, **kwargs: None
f17a7e0758

2023-02-22 00:39 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            return False
f17a7e0758

2023-02-22 00:39 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            if not stripe_entity:
f17a7e0758

2023-02-22 00:40 UTC, benjaminEwhite commented on apps/contributions/models.py
> +            else:
f17a7e0758

2023-02-23 21:09 UTC, x110dc approved these changes

2023-02-23 21:09 UTC, x110dc commented on conftest.py
> +        "apps.contributions.models.Contribution.fetch_stripe_payment_method", lambda *args, **kwargs: None
@njharman Yes please, thanks.

2023-02-23 21:09 UTC, x110dc commented on apps/contributions/views.py
> +        ids = (self.model.objects.all() if request.user.is_staff else self.get_queryset()).values_list("id", flat=True)
I *think* that because Contributor users are completely separate from users with a password this shouldn't matter. But we can confirm in QA.

2023-02-24 22:41 UTC, njharman commented on conftest.py
> +        "apps.contributions.models.Contribution.fetch_stripe_payment_method", lambda *args, **kwargs: None
https://news-revenue-hub.atlassian.net/browse/DEV-3341

2023-03-17 17:40 UTC, benjaminEwhite commented on apps/contributions/serializers.py
> +    # def __init__(self, *args, **kwargs):
Came across this and have no idea why it's this way. Commenting out to see if anything breaks in test app environment.

2023-03-21 18:13 UTC, merged