Checkpointing
newsrevenuehub/rev-engine pull request #986
Opened 2023-02-06 15:12 UTC by nrh-cklimas

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

The general idea here is to keep hacking away at EditInterfaceContext and remove it from the element detail editors in favor of hooks and regular props.

- Add a new component, ElementEditor. It manages the content frame for the editor, similar to ElementProperties.
- Editor components don't see (or need to see) the larger context, just what element they are editing. They call `onChangeElementContent` when a change occurs.
- ElementEditor is in charge of what component to use for the content edit instead of components having a `for` property.
- ElementEditor falls back to the old ElementProperties component for element types that haven't been migrated yet.

This PR is just a proof of concept at this point, and only allows editing one checkbox in the amount element, and doesn't have any unit tests or styling yet.

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-02-09 20:28 UTC, benjaminEwhite commented
Closing, tearing down, then reopening as part of work for [DEV-3243 | fix hookdeck webhooks](https://news-revenue-hub.atlassian.net/browse/DEV-3243), to trigger fresh review app.

2023-02-13 20:27 UTC, GuiMend commented on spa/src/components/pageEditor/elementEditors/amount/AmountItem.tsx
> +    <Root $isDefault={!!isDefault}>
Maybe add a default?

```suggestion
export function AmountItem({ amount, isDefault = false, onRemove, onSetDefault, removable }: AmountItemProps) {
  return (
    <Root $isDefault={isDefault}>
```

2023-02-13 20:27 UTC, GuiMend commented on spa/src/components/pageEditor/elementEditors/amount/AmountItem.styled.ts
> +  }}
Can simplify this style: 

```suggestion
  ${(props) =>
    props.$isDefault &&
      `
        background: ${({ theme }) => theme.colors.muiLightBlue[800]};
        box-shadow: none;
        color: ${({ theme }) => theme.colors.white};
      `
  }
```

2023-02-13 21:37 UTC, nrh-cklimas commented on spa/src/components/pageEditor/elementEditors/amount/AmountItem.tsx
> +    <Root $isDefault={!!isDefault}>
Hmm, when I try that I get this complaint: `Type 'boolean | null' is not assignable to type 'boolean'.` I can change it to `isDefault!` but that seems like it defeats the purpose of trying to avoid a type coercion.

2023-02-13 21:41 UTC, nrh-cklimas commented on spa/src/components/pageEditor/elementEditors/amount/AmountItem.styled.ts
> +  }}
If I drop the `css` I get this error: `Binding element 'theme' implicitly has an 'any' type.` Do you know if there's a type annotation I can put on the `theme` args that will make TypeScript happy?

2023-02-13 21:50 UTC, nrh-cklimas commented on spa/src/components/pageEditor/elementEditors/amount/AmountInterval.stories.tsx
> +};
Sounds good--added in 62e5a42a9d55abf3e17145a49f8f5e5ab54cc320

2023-02-13 21:55 UTC, GuiMend commented on spa/src/components/pageEditor/elementEditors/amount/AmountItem.styled.ts
> +  }}
I've updated my suggestion in a way that might prevent this error.

2023-02-13 22:33 UTC, nrh-cklimas commented on spa/src/components/pageEditor/elementEditors/amount/AmountItem.styled.ts
> +  }}
:+1: aa523ee282cb2f3b15d95b1881eaf7bf5cb7569a

2023-02-14 16:44 UTC, GuiMend requested changes
Looking good 👍 

One question, shouldn't we order from lower to higher?
It gets confusing when you add numbers without an order
![image](https://user-images.githubusercontent.com/9381325/218801631-95b37c31-a1ab-474f-8b38-8ac8f5856e52.png)

![image](https://user-images.githubusercontent.com/9381325/218801211-7f341a96-6564-4ba4-8ce0-d3c657c051b5.png)

2023-02-14 18:37 UTC, GuiMend approved these changes

2023-02-16 01:00 UTC, x110dc approved these changes

2023-02-16 13:54 UTC, merged