DEV-2719: Include "Organization" link in avatar menu and link to Org Settings Page
newsrevenuehub/rev-engine pull request #993
Opened 2023-02-07 19:13 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)
n/a

#### What's this PR do?
- Adds a new Material UI icon library that is more complete than the other we have and the long-term objective is to remove the older lib and swap all icons to this new lib. Talked about this with @nrh-cklimas.
- Update TS, jest & package.json to work with svgr icons
- Added Organization menu item to AvatarMenu
- Create a new protected router wrapper to handle AC 4. `users with access to multiple orgs, and users with access to multiple orgs cannot navigate to these pages`

#### Why are we doing this? How does it help us?
- Make it possible for users to navigate to Organization page
- Standardize icon library

#### How should this be manually tested? Please include detailed step-by-step instructions.
Test all 3 scenarios:
1) - Log in with HUB admin
    - Check that AvatarMenu does not have Organization button
    - Access "settings/organization" in the URL and make sure it works

2) - Log in with user with access to multiple Orgs
    - Check that AvatarMenu does not have Organization button
    - Access "settings/organization" in the URL and make sure it redirects to "/pages"

3) - Log in with user with access to 1 Org
    - Check that AvatarMenu has Organization button and that it works (redirects to "settings/organization")
    - Access "settings/organization" in the URL and make sure it works

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
yes

#### Have automated unit tests been added? If not, why?
yes

#### How should this change be communicated to end users?
Users now have access to settings/organization page

#### Are there any smells or added technical debt to note?
no

#### Has this been documented? If so, where?
no

#### What are the relevant tickets? Add a link to any relevant ones.
https://news-revenue-hub.atlassian.net/browse/DEV-2719

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
no

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
no

2023-02-09 19:55 UTC, nrh-cklimas requested changes

2023-02-09 19:55 UTC, nrh-cklimas commented on spa/__mocks__/svgrMock.js
> +module.exports = { ReactComponent: 'icon-mock' };
```suggestion
export const ReactComponent = 'icon-mock';
```

2023-02-09 19:55 UTC, nrh-cklimas commented on spa/package.json
> +      "\\.svg": "<rootDir>/__mocks__/svgrMock.js"
```suggestion
      "\\.svg$": "<rootDir>/__mocks__/svgrMock.js"
```
Nitpicking

2023-02-09 19:55 UTC, nrh-cklimas commented on spa/src/components/settings/SettingsProtectedRoute.tsx
> +  return <SentryRoute {...props}>{children}</SentryRoute>;
This is a judgment call so feel free to disregard, but I feel like it would be easier to test if this just returns children instead of wrapping with a SentryRoute. My thinking is...

1) We can put tests around Sentry logging in one place
2) When updating routes, we don't have to remember that we don't need to wrap this component in SentryRoute

If we do have a SentryRoute here, we should have a unit test to make sure it's present.

2023-02-09 19:55 UTC, nrh-cklimas commented on spa/src/components/settings/SettingsProtectedRoute.tsx
> +const SettingsProtectedRoute = ({ children, ...props }: SettingsProtectedRouteProps) => {
How about a name like `SingleOrgUserOnlyRoute`? I could see us potentially using this outside the organizations menu, and we may end up protecting settings routes with different criteria down the road.

2023-02-09 19:55 UTC, nrh-cklimas commented on spa/src/components/settings/SettingsProtectedRoute.tsx
> +
We should have a check for `isLoading` and either return nothing or a GlobalLoading. While we don't know whether the user has one org, we shouldn't show them UI for single-org users.

2023-02-09 20:23 UTC, benjaminEwhite commented
Closing, tearing down, then reopening to trigger new review app build, as part of [DEV-3243 | fix hookdeck webhooks](https://news-revenue-hub.atlassian.net/browse/DEV-3243).

2023-02-10 14:48 UTC, GuiMend commented on spa/src/components/settings/SettingsProtectedRoute.tsx
> +  return <SentryRoute {...props}>{children}</SentryRoute>;
That was my first idea for this component as well but than I saw `ProtectedRoute` and made it similar to that. But I'll update it with your suggestion 👍 

```js
function ProtectedRoute({ contributor, ...props }) {
  if (isAuthenticated(contributor)) {
    return <SentryRoute {...props} />;
  }
  return <Redirect to={SIGN_IN} />;
}
```

2023-02-10 14:48 UTC, GuiMend commented on spa/src/components/settings/SettingsProtectedRoute.tsx
> +const SettingsProtectedRoute = ({ children, ...props }: SettingsProtectedRouteProps) => {
Makes sense. Will update it 👍

2023-02-10 15:45 UTC, nrh-cklimas commented on spa/src/components/settings/SettingsProtectedRoute.tsx
> +
Change looks good, but there should be a unit test around it too (unless I'm missing it).

2023-02-10 15:51 UTC, GuiMend commented on spa/src/components/settings/SettingsProtectedRoute.tsx
> +
It's there but I renamed the test to be clear.

2023-02-10 16:08 UTC, nrh-cklimas commented on spa/src/components/settings/SettingsProtectedRoute.tsx
> +
I see, thanks.

2023-02-10 16:08 UTC, nrh-cklimas approved these changes

2023-02-13 21:28 UTC, nrh-cklimas commented on spa/src/components/routes/AddSlashToRoutes.tsx
> +  // Only redirect if pathname doesn't end with `/` and doesn't start with `//`
Could you add a quick comment explaining how the edge case can happen? This change looks good (and yay migrating to TypeScript) but I don't get the circumstances when this could happen and why we shouldn't do anything in this case.

2023-02-14 14:31 UTC, GuiMend commented on spa/src/components/routes/AddSlashToRoutes.tsx
> +  // Only redirect if pathname doesn't end with `/` and doesn't start with `//`
Sure, will add that. But to explain it here: this edge case might happen if the user types in a url that starts with `//` and we shouldn't do nothing because:

1. If the URL doesn't match anything, we already have a redirect to `/pages/`
2. If we try to redirect with pathname containing 2 trailing slashes it thinks that it's because the pathname is part of `https://`. Example: if you type `www.[localhost].com:3000//settings` the function `AddSlashToRoutes` will try to redirect to `http://settings`, which will cause the sentry issue that popped up in Agustin's tests and will cause the app to crash (white screen).

2023-02-24 19:17 UTC, x110dc approved these changes

2023-02-24 19:45 UTC, merged