[WIP] DEV-2717: Org Settings page
newsrevenuehub/rev-engine pull request #994
Opened 2023-02-08 02:28 UTC by GuiMend

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

#### What's this PR do?

#### Why are we doing this? How does it help us?

#### How should this be manually tested? Please include detailed step-by-step instructions.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

#### Have automated unit tests been added? If not, why?

#### How should this change be communicated to end users?

#### Are there any smells or added technical debt to note?

#### Has this been documented? If so, where?

#### What are the relevant tickets? Add a link to any relevant ones.

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

2023-02-22 21:59 UTC, nrh-cklimas commented on spa/src/hooks/useContributionPage/useContributionPage.types.ts
> +   * Fiscal sponsor name. Will only have a non-null value if fiscal_status === "fiscally sponsored"
If this is the case, shouldn't the type be `string | null`?

2023-02-23 11:47 UTC, GuiMend commented on spa/src/hooks/useContributionPage/useContributionPage.types.ts
> +   * Fiscal sponsor name. Will only have a non-null value if fiscal_status === "fiscally sponsored"
Correct. Updated

2023-02-23 14:29 UTC, nrh-cklimas requested changes

2023-02-23 14:29 UTC, nrh-cklimas commented on spa/src/components/settings/Organization/Organization.test.tsx
> +  describe('onSubmit: Saving changes', () => {
We should add test cases for when the PATCHes fail (it looks like you have good error handling; we just need to exercise them).

2023-02-23 14:29 UTC, nrh-cklimas commented on spa/src/components/settings/Organization/Organization.test.tsx
> +  it('should render page texts', () => {
We should add a test showing that when user is loading, this displays a spinner.

2023-02-23 14:29 UTC, nrh-cklimas commented on spa/src/components/settings/Organization/Organization.tsx
> +      taxId: taxId.replace(/-/g, '') !== revenueProgramFromCurrentOrg?.[0]?.tax_id
Small bug here: if I do not specify a tax ID when I first create my account and then go to this page, `isDifferent.taxId` is immediately true. I'm guessing this is because it's comparing `null` or `undefined` to an empty string.

2023-02-23 14:29 UTC, nrh-cklimas commented on spa/src/components/settings/Organization/Organization.test.tsx
> +
We should have a test exercising the Undo button too.

2023-02-24 14:16 UTC, GuiMend commented on apps/organizations/serializers.py
> +            "non_profit",
We don't. I added it at the beginning and forgot to remove it after it wasn't being used anymore

2023-02-24 14:40 UTC, GuiMend commented on spa/src/components/common/SettingsSection/SettingsSection.styled.ts
> +export const Title = styled.p`
Thanks for catching that, but this one should be an `h3`.

<img width="701" alt="image" src="https://user-images.githubusercontent.com/9381325/221206303-ab54f5e9-2db0-42e8-8352-f1723c385f34.png">

2023-02-24 20:17 UTC, nrh-cklimas commented on spa/src/components/common/SettingsSection/SettingsSection.tsx
> +import PropTypes, { InferProps } from 'prop-types';
Discussed this on Slack

2023-02-24 20:21 UTC, nrh-cklimas commented on apps/organizations/serializers.py
> +            "non_profit",
Hm, I still see it in the branch.

2023-02-27 20:57 UTC, GuiMend commented on apps/organizations/serializers.py
> +            "non_profit",
Sorry, now I removed. I had added non_profit to another serializer in the same file that was also unused and removed that one in the previous commit.

2023-02-27 20:59 UTC, GuiMend commented on spa/src/components/settings/Organization/Organization.tsx
> +  const updateOrganizationNameMutation = useMutation(
These mutations are supposed to only be used in this page. Wouldn't it be better to make it a separate file only if it will be used in at least a couple of places?

2023-02-28 14:34 UTC, nrh-cklimas requested changes

2023-02-28 14:34 UTC, nrh-cklimas commented on spa/src/components/settings/Organization/Organization.styled.ts
> +  background: ${(props) => `${props.theme.colors.muiTeal[600]}1a`};
This feels brittle to me in that if we ever change our colors to not use hex triplets (e.g. HSL or something) this will break without us knowing it. My feeling is we should either just hardcode the color here or add something to the palette, my pref being hardcoding it because it's the only place the color is being used right now.

2023-02-28 14:34 UTC, nrh-cklimas commented on spa/src/components/settings/Organization/Organization.tsx
> +
```suggestion
  useEffect(() => {
    setShowSuccess(false);
  }, [companyName, companyTaxStatus, taxId, setShowSuccess]);
```

I tested this locally and it seemed harmless to set showSuccess to false repeatedly. The other approach here that would mean you wouldn't need to have `showSuccess` as a dep is to use the functional setter, e.g. `setShowSuccess((old) => old ? false : old);` but I think it's effectively the same as just setting it to false in all cases.

2023-02-28 14:34 UTC, nrh-cklimas commented on spa/src/components/common/AvatarMenu/AvatarMenu.tsx
> +              <LogoutIcon />
I think this should be `aria-hidden` since it's not interactible and it's redundant with the text next to it.

2023-02-28 18:14 UTC, GuiMend commented on spa/src/components/settings/Organization/Organization.tsx
> +
I wanted to avoid re-renders, but I just did a quick search and your suggestion doesn't re-render even if we call setstate repeated times 😄 
ref: https://dev.to/sunflower/reactjs-if-it-is-setting-a-state-with-the-same-value-will-the-component-be-re-rendered-5g24

2023-02-28 19:02 UTC, nrh-cklimas commented on spa/src/components/settings/Organization/Organization.tsx
> +  const updateOrganizationNameMutation = useMutation(
I feel that it's easier to test the API interactions separately (you can test different mutations without having to manipulate the DOM first), but it's a judgment call. I suspect this will not be the only place that we need to fetch and make changes to an organization or RP, but I don't know this for sure.

2023-02-28 19:02 UTC, nrh-cklimas approved these changes

2023-03-03 16:04 UTC, benjaminEwhite commented
Closing, tearing down, then reopening this PR because at time review app was created, there was bug in hookdeck integration code that means Stripe webhooks don't work in the review app.

2023-03-07 01:08 UTC, x110dc approved these changes

2023-03-07 14:21 UTC, merged