DEV-3146: fix error user allowed to reject/accept non-flagged contrib…
newsrevenuehub/rev-engine pull request #995
Opened 2023-02-08 06:27 UTC by leo-dcfa

…ution

Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

N/A

#### What's this PR do?

Fixed bug that allows users to reject or accept non-flagged contributions

#### Why are we doing this? How does it help us?

User is either not allowed to reject an accepted (already paid) payment via Django Admin, or if they are allowed to do so, then there should not be a discrepancy between a payment’s status in Django Admin + NRE Contributions tab and the payment’s status on Stripe.

#### How should this be manually tested? Please include detailed step-by-step instructions.

- Create a flagged recurring or one-time contribution
- Open [Django Admin’s contributions page]
- Find your payment, and accept it
- See that your payment switches to a paid status on Django Admin
- See that your payment appears in contributions tab
- See that payment, subscription, and customer are created in Stripe for the payment
- Find your payment again, and reject it
- Assert that error message is displayed and contribution status stays the same

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

N/A

#### Have automated unit tests been added? If not, why?

Yes

#### How should this change be communicated to end users?

N/A

#### Are there any smells or added technical debt to note?

N/A

#### Has this been documented? If so, where?

N/A

#### What are the relevant tickets? Add a link to any relevant ones.

[DEV-3146]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?

N/A

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

N/A

2023-02-08 15:12 UTC, benjaminEwhite approved these changes
Code changes look good. Had one question about `FallbackStorage`.

2023-02-08 15:29 UTC, benjaminEwhite requested changes
After going through review checklist in JIRA, realized there is one change I'd like to see. 

I know you're leaving `_process_flagged_payment` mainly as is, but we're trying to be more deliberate about adding server-side logging.

Could you add some logging at least to this function (prepending ``ClassName.method_name ``)? You could even add a log to`Contribution.process_flagged_payment` if you're up for it. Basically, it would be good to have info- (or possibly debug-) level logs that show function is called and gives us a peak into relevant args.

2023-02-08 20:42 UTC, leo-dcfa commented on apps/contributions/tests/test_admin.py
> +        setattr(request, "_messages", messages)
Messages need a middleware in order to work; if you don't have `FallbackStorage`, this test fails with:

```django.contrib.messages.api.MessageFailure: You cannot add messages without installing django.contrib.messages.middleware.MessageMiddleware```

https://docs.djangoproject.com/en/4.1/ref/contrib/messages/

This is the solution I found https://code.djangoproject.com/ticket/17971

2023-02-09 15:51 UTC, benjaminEwhite approved these changes

2023-02-10 19:21 UTC, x110dc approved these changes

2023-02-10 20:08 UTC, merged